### ISSUE TITLE
Compatibility for cardano-cli commands at root level across protocols

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-node#1002]
Since the CLI commands are being grouped under `cardano-cli byron` and `cardano-cli shelley`, my understanding is the commands still present in root (eg: `to-verification` or `print-genesis-hash`) should remain compatible with both Byron and Shelley.

I understand that this might be a to-do anyways but wanted to highlight from usage perspective.

Also, a side note - might be worth a seperate issue:
Wonder if it makes sense for create commands to create both signing and verification key, once we have `to-verification` working (assuming to-verification would work with all format of signing keys).

Jormungandr users would have been used to commands creating a secret key, and when required - converting it to public/verification keys on the fly.

**Comment by erikd** [comment]
> my understanding is the commands still present in root 

This is still a work in progress. I am not 100% sure this statement is correct.

This is however a good placeholder to remind us to revisit this.

**Comment by CarlosLopezDeLara** [comment]
Latest version has different structure. `to-verification` and `print-genesis-hash` are byron era subcommands: 

```
cardano-cli byron key to-verification
Usage: cardano-cli byron key to-verification 
            [--byron-legacy-formats | --byron-formats]
            --secret FILEPATH
            --to FILEPATH
```


```
cardano-cli byron genesis print-genesis-hash
Usage: cardano-cli byron genesis print-genesis-hash --genesis-json FILEPATH

  Compute hash of a genesis file.

Available options:
  --genesis-json FILEPATH  Genesis JSON file.
  -h,--help                Show this help text
```
