### ISSUE TITLE
[FR] - Add CLI command to check the pools an address is delegating to

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#1019]
**Describe the feature you'd like**
After delegating to a stake pool, it would be useful to have a cli command to check the pool(s) your address is currently delegating to

**Comment by intricate** [comment]
This seems to be a duplicate of https://github.com/input-output-hk/cardano-node/issues/1053 which was recently resolved.

**Comment by dorin100** [comment]
Fixed by `cardano-cli shelley query stake-address-info`
