### ISSUE TITLE
[BUG] - node deletes socket when using socket activation

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1023]
**Summary**
When socket activation is enabled, the node should not delete the socket when it's done running. Doing so causes systemd to think the socket still exists, so a restart of the node service results in node running with no socket file.

**Steps to reproduce**
1. systemctl restart cardano-node
2. ls -hal /run/cardano-node (no socket file shown)

To fix the issue:
1. systemctl restart cardano-node.socket

**Expected behavior**
If socket activation is enabled, don't delete the file.

**Comment by dcoutts** [comment]
Should have been fixed by https://github.com/input-output-hk/cardano-node/pull/1017
