### ISSUE TITLE
[FR] - CLI - Add more meaningful parameters into the output of `cardano-cli shelley query protocol-parameters`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#1034]
**Describe the feature you'd like**
Add more meaningful and useful parameters into the output of the `cardano-cli shelley query protocol-parameter` cli command. These parameters are important when creating scripts or when trying to understand the actual state/functionality of the blockchain.
- slotDuration
- slotsPerEpoch
- rewardParams
- fees
- block0Time
- block0Hash
- treasury values/tax/fee

**Comment by Jimbo4350** [comment]
I think this has been resolved via: https://github.com/input-output-hk/cardano-node/blob/master/cardano-api/src/Cardano/Api/ProtocolParameters.hs#L240

If not feel free to re-open a ticket.
