### ISSUE TITLE
[FR] - CLI - Display KES-period when querying node tip

### ISSUE THREAD

**Issue by brunjlar** [input-output-hk/cardano-node#1037]
The KES-period should be included in the output of `cardano-cli shelley query tip`, because it is important for properly issuing new operational node certificates.

**Comment by dcoutts** [comment]
I don't think we should do it like this, because it's ad-hoc and hard to do. We already have mechanism for reporting metrics, and we have structured logs. We should use those, not ad-hoc extra node RPCs.

See #1029 and #1030.

**Comment by kevinhammond** [comment]
Based on Duncan's comments, I will close this issue.
