### ISSUE TITLE
[FR] -  CLI Single address wallet operations (CAD-887)

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#1039]
This is just a convenience, but quite a big one for pool operators

**Comment by kevinhammond** [comment]
Is this complete now?

**Comment by intricate** [comment]
> Is this complete now?

Nope, but a draft PR has been open for a while now: https://github.com/input-output-hk/cardano-node/pull/916

Been a while since it's been rebased, so I will have to come back around to this soon.

**Comment by Jimbo4350** [comment]
Not sure if this is relevant anymore. The original issue mentions https://github.com/cardano-community/guild-operators

**Comment by intricate** [comment]
@Jimbo4350: This could still be relevant. Let's check with @dcoutts
