### ISSUE TITLE
[FR] -   Ledger state information

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#1041]

**Comment by intricate** [comment]
What sort of information are we interested in here? We've currently got a command in `cardano-cli` for querying the ledger state; is that sufficient?

**Comment by kevinhammond** [comment]
Can I close this one?  There are various requests for more ledger information, including leadership schedules etc

**Comment by intricate** [comment]
@kevinhammond: I'd agree with closing this issue in favour of more specific ones.

**Comment by JaredCorduan** [comment]
I am also in favor of closing this in favor of more specific ones.

**Comment by kevinhammond** [comment]
I have closed this.
