### ISSUE TITLE
[FR] -   CLI - Hot key update without restarting node (e.g. using SIGHUP)?

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#1044]
There’s a proper scheme that should be implemented...

**Comment by matiwinnetou** [comment]
+1

**Comment by matiwinnetou** [comment]
Why is it low prio? How can we make sure block-producing node runs uninterrupted without this feature?

**Comment by hodlonaut** [comment]
Any chance of an update on this Feature Request front? It's been 84 years...

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
