### ISSUE TITLE
[FR] - CLI - Mechanism to check block production

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#1051]
Pool operators would like to know whether their pools are producing blocks.  This could be explorer/db-sync functionality?

**Comment by kevinhammond** [comment]
This may be redundant.  I am told that we will have explorer-like capabilities next week (DevOps).

**Comment by bergr01** [comment]
Any updates on this issue, is it staying or going?

**Comment by Jimbo4350** [comment]
Closing, re-open if this is still relevant with more information.
