### ISSUE TITLE
[FR] - CLI - Mechanism to check delegation to a pool.

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#1052]
Pool operators would like to know what delegations have been made to their pools.  This could be explorer/db-sync functionality?   The fraction of total delegation is already available.

**Comment by kevinhammond** [comment]
Related to #1019

**Comment by CarlosLopezDeLara** [comment]
@kevinhammond  Would you consider this resolved by `cardano-cli query stake-snapshot --stake-pool-id` ? Of course dbsync also provides more granularity.

**Comment by kevinhammond** [comment]
Yes.  This is an old issue
