### ISSUE TITLE
CLI - CAD-564 - Node CLI: Component [Process] Status (DevOps, StakePool Operator) 

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#1059]

**Comment by cardanians** [comment]
:) #980  #801

**Comment by kevinhammond** [comment]
This relates to various feature requests.  It would be good to do this.

**Comment by kevinhammond** [comment]
This refers to knowing which components are running.  It may be that we can close it in favour of e.g. liveview.

**Comment by cardanians** [comment]
@kevinhammond 

is possible have there too KES expiry information to pool(s)?

for ex.:

{
uptime: ____,
peers: _____,
leaders: [ node_id_1, node_id_2],
lastBlockHeight: ____
kes_expiry: [ date(d-m-Y, H:i,NODE1_EXPIRY) , date(d-m-Y, H:i,NODE2_EXPIRY) ]
..................
#980
..................
}

thx

**Comment by denisshevchenko** [comment]
Corresponding task (CAD-564) is closed in June.
