### ISSUE TITLE
Run a small demo cluster on CI together with chairman application

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#106]
1. [x] Describe clusters of `cardano-node` as NixOS service
1. [x] Describe `chairman` as a NixOS service, so it can be integrated with the above
1. [x] Define a NixOS test running `chairman` as a check against the said cluster
1. [ ] Tune the `chairman`'s pass/failure criteria, so they are a useful measure of regression

1+2+3 were done in https://github.com/input-output-hk/cardano-node/pull/177
4 is being worked on in https://github.com/input-output-hk/cardano-node/pull/201

**Comment by deepfire** [comment]
Done (and much more) in https://github.com/input-output-hk/cardano-node/pull/269
