### ISSUE TITLE
[FR] - CLI - Include to-verification for various shelley keys

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-node#1065]
**Describe the feature you'd like**
Implement `to-verification` key to make it easier for wrapper scripts to not have to specify a signing key as well as verification key (or address). This would also allow us to recreate the verification key using the signing key.

Similar feature is available for Byron CLI (and was also commonly used in Jormungandr)

**Comment by kevinhammond** [comment]
Is this a duplicate?

**Comment by dcoutts** [comment]
I'm assuming what you're asking is for the ability to derive the verification key from the signing key. Can you confirm that's what you mean?

This already exists for some key types, e.g. `cardano-cli shelley genesis get-ver-key`.

So my interpretation of the request would be to provide this functionality consistently for all key types.

**Comment by rdlrt** [comment]
@dcoutts Yes - thats correct.

**Comment by kevinhammond** [comment]
So we should not close this now

**Comment by vix-io** [comment]
We will provide this functionality consistently for all key types with a sub command
