### ISSUE TITLE
Update cardano-cli README and cardano-node README cardano-cli section

### ISSUE THREAD

**Issue by tatyanavych** [input-output-hk/cardano-node#1071]
`cardano-node` README has section [cardano-cli](https://github.com/input-output-hk/cardano-node/blob/master/README.md#cardano-cli) created some time ago. It does not reflect the latest changes/additions in the recently extracted `cardano-cli` submodule that itself has its [README](https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/README.md), but currently empty. 

Both need update. Link to the new tutorials where applicable.

**Comment by kevinhammond** [comment]
Should be a very quick task

**Comment by kevinhammond** [comment]
Done
