### ISSUE TITLE
[FR] - Provide visual warning that node is minting blocks but they are not seen by the network

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#1072]
Running cardano-node/cardano-cli v 1.12.0

After registering a couple of stake pools on FnF network, I spun up a couple more nodes which were using new ports and referenced IOHK relay in their topology.json. Once the nodes were up and running and sufficient amount of time has passed from the pool creation/pledging/initial delegation, the TUI for these nodes started showing information about 'blocks minted' and 'node is leader' (i.e. numbers started to go up from zero).

However, later I was informed that unless there is some way for IOHK relay nodes to reach my new nodes via topology chain, these blocks that my new nodes are minting are just falling off the cliff and not being adopted into the blockchain / seen by other block-producing-or-otherwise nodes.

It would be helpful to provide a visual clue in the TUI (or elsewhere, I'm open to suggestions) to indicate that the node currently is not being queried for block announcements - so that operator can take appropriate corrective action (e.g. adjust the configuration) instead of remaining oblivious to the fact that blocks being minted serve no purpose and if I'm understanding it right have no chance of being rewarded in such a scenario.

**Comment by CodiePP** [comment]
maybe related to #1088 : the TUI should display more information about forged blocks

**Comment by bergr01** [comment]
> maybe related to #1088 : the TUI should display more information about forged blocks

1088 is about displaying information about issues with block minting. My request is related to node configuration with regards to network topology being incorrect (or perhaps operator did everything within their powers but IOHK master relay didn't pick up the latest version of the operator relays file - or even if by some chance the pool operator's relay node got cut off from the network (e.g. public port stopped being open, IP address changed)

**Comment by vix-io** [comment]
Hi bergr01, this is Viktor at IOHK Tech Support. Thank you for submitting this Feature Request. We have added it to our backlog and we`ll allocate it to one of our future development sprints. We appreciate your participation and support for the Cardano project!

**Comment by bergr01** [comment]
> Hi bergr01, this is Viktor at IOHK Tech Support. Thank you for submitting this Feature Request. We have added it to our backlog and we`ll allocate it to one of our future development sprints. We appreciate your participation and support for the Cardano project!

Hi Viktor
Where do I track progress of this issue - or is github issue entry still the right place?

**Comment by gufmar** [comment]
As remote peers are actively requesting blocks (they control the own verify resources) it's a common mistake to see the block producing node connected, receiving blocks and TXs, and also producing his blocks. 

It is difficult for a node to query remote nodes if they have seen his blocks. But as a simple and viable solution, I propose a **block request counter**. when this counter's delta remains at zero, something went wrong (relay chain registration, node port setup, firewall-config, fell out of all remote topologies ...)

**Comment by dcoutts** [comment]
In principle we can certainly observe the number of downstream peers, and the number of block bodies they have requested from us.

**Comment by Oqulent** [comment]
if it is at all possible, it would be great to track this statistic on prometheus/grafana too.

**Comment by aaastakepool** [comment]
Any updates on this front, amigos?

**Comment by vix-io** [comment]
Will be possible when peer to peer governor is merged, we don't plan to do this before that

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
