### ISSUE TITLE
[BUG] - Node hangs indefinitely on startup on Macbook while Opening Ledger DB

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#1081]
cardano-node version
cardano-cli 1.12.0 - darwin-x86_64 - ghc-8.6
git rev 036ea01f9d8d025e68e0570c1eeb15a6f8191039

Node that has been running for hours and is stopped from LiveView via 'Q' is later re-launched, but gets stuck in LiveView at epoch 0 / slot 0, block number 0 indefinitely. The last few lines in the configured logging file output are:

{"at":"2020-05-28T12:04:41.31Z","env":"1.12.0:036ea","ns":["cardano.node.ChainDB"],"data":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":134998,"tip":136010},"app":[],"msg":"","pid":"97522","loc":null,"host":"YARRISMA","sev":"Info","thread":"32"}
{"at":"2020-05-28T12:04:41.38Z","env":"1.12.0:036ea","ns":["cardano.node.ChainDB"],"data":{"kind":"LogValue","value":{"tag":"PureD","contents":100},"name":"block replay progress (%)"},"app":[],"msg":"","pid":"97522","loc":null,"host":"YARRISMA","sev":"Info","thread":"32"}
{"at":"2020-05-28T12:04:41.39Z","env":"1.12.0:036ea","ns":["cardano.node.ChainDB"],"data":{"kind":"LogValue","value":{"tag":"PureI","contents":135001},"name":"before next, messages elided"},"app":[],"msg":"","pid":"97522","loc":null,"host":"YARRISMA","sev":"Info","thread":"32"}
{"at":"2020-05-28T12:04:41.39Z","env":"1.12.0:036ea","ns":["cardano.node.ChainDB"],"data":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":136010,"tip":136010},"app":[],"msg":"","pid":"97522","loc":null,"host":"YARRISMA","sev":"Info","thread":"32"}
{"at":"2020-05-28T12:04:41.39Z","env":"1.12.0:036ea","ns":["cardano.node.ChainDB"],"data":{"kind":"TraceOpenEvent.OpenedLgrDB"},"app":[],"msg":"","pid":"97522","loc":null,"host":"YARRISMA","sev":"Info","thread":"32"}

Activity Monitor is showing cardano-node process as using up 95-100% of the CPU (on 4 core Macbook). Also worth noting that TUI/LiveView is not responding to 'Q' at this point in time, so I have to kill the cardano-node process eventually.

Only workaround that seems to help for now is killing the node, deleting the contents of the 'db' folder and starting from scratch.

**Comment by kevinhammond** [comment]
We are not prioritising Stake Pool Operation on Apple Macs.

**Comment by bergr01** [comment]
I believe this has been addressed by Karl in ourobouros-network - https://github.com/input-output-hk/ouroboros-network/issues/2188
