### ISSUE TITLE
[PERF] - starting node / bootstrapping from empty DB takes too long

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#1082]
cardano-cli 1.12.0 - darwin-x86_64 - ghc-8.6
git rev 036ea01f9d8d025e68e0570c1eeb15a6f8191039

Observed on a network with 35000 produced blocks so far and that is up to slot number 140394 or thereabouts. When starting a cardano-node on a Macbook machine with decent internet speeds, catching up to the blockchain tip seems to take way too long (in my humble opinion).

For example, after 15 minutes since startup the LiveView reports my node has caught up to block 10400 (out of 35000) and is up to epoch 1 / slot 19706.

After 28 minutes, it is up to block 19773 and epoch 3 / slot 14314....

Also worth noting that while this is happening the Network In value in LiveView is showing a wide variety of values, ranging from 3.0 KB/s to 60 KB/s... meaning it is not exactly trying really hard to fetch the block data from the peers. Also peer count as has been the case since Haskell Testne thas launched is fluctuating between 0 and 2, not sure how much of a factor that is in all of this. e.g.

{"at":"2020-05-28T12:59:20.26Z","env":"1.12.0:036ea","ns":["cardano.node.IpSubscription"],"data":{"event":"Skipping peer 88.99.83.86:6000","dests":"[88.99.83.86:6000,95.216.188.94:6001]","kind":"WithIPList SubscriptionTrace","localAddresses":"LocalAddresses {laIpv4 = Just 0.0.0.0:0, laIpv6 = Nothing, laUnix = Nothing}"},"app":[],"msg":"","pid":"97559","loc":null,"host":"YARRISMA","sev":"Info","thread":"63"}

without much explanation as to why one of my peers is being skipped..

also there are some

{"at":"2020-05-28T13:00:18.00Z","env":"1.12.0:036ea","ns":["cardano.node.Forge"],"data":{"kind":"TraceNoLedgerView","slot":140529},"app":[],"msg":"","pid":"97559","loc":null,"host":"YARRISMA","sev":"Error","thread":"51"}

messages, which I'm not sure what to make of...

All in all it's not a very smooth pleasant experience even on a very small network with a few running nodes. Please let me know if you want me to collect any more metrics/statistics/logs from my node - but if I'm not mistaken other people have reported similar slow bootstrapping-from-empty-DB issues even on non MacOS systems.

**Comment by kevinhammond** [comment]
We are planning to investigate performance issues.

**Comment by MarcelKlammer** [comment]
In Ubuntu I got the same issue. I always resort to changing the topology to a single entry, most of the time to ONYX' addr. 

When the node is connected to 30+ nodes, downloading the chain takes 3-5 times longer than when the node is only connected to a single other node.

**Comment by papacarp** [comment]
about an hour to sync 25 epochs from another relay on the same instance.  So its not bandwidth related.

**Comment by vix-io** [comment]
We have done a lot of optimizations, if you notice further issues please log a new ticket.
