### ISSUE TITLE
[BUG] - Incorrect tracing of chain information

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/cardano-node#1085]
The tracing done in [`traceChainInformation`](https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Tracing/Tracers.hs#L356-L374) is incorrect:

```haskell
    traceChainInformation :: Trace IO Text
                          -> ChainInformation
                          -> IO ()
    traceChainInformation tr ChainInformation { slots, blocks, density } = do
        -- TODO this is executed each time the chain changes. How cheap is it?
        meta <- mkLOMeta Critical Confidential
        let tr' = appendName "metrics" tr
            traceD :: Text -> Double -> IO ()
            traceD msg d = traceNamedObject tr' (meta, LogValue msg (PureD d))
            traceI :: Integral a => Text -> a -> IO ()
            traceI msg i = traceNamedObject tr' (meta, LogValue msg (PureI (fromIntegral i)))

        traceD "density"     (fromRational density)
        traceI "slotNum"     slots
        traceI "blockNum"    blocks
        traceI "slotInEpoch" (slots `rem` epochSlots)
        traceI "epoch"       (slots `div` epochSlots)
      where
        epochSlots :: Word64 = 21600  -- TODO
```

`slots` and `blocks` are both computed by in `chainInformation`, which uses the current chain fragment from the ChainDB. This chain fragment almost always the last `k` headers, unless near genesis, in which it will be less than `k`.

So we expect `blocks` to always be exactly `k`, unless near genesis or because there's an EBB in there.

`slots` is computed as the difference between the slot number of the most recent header on the fragment (the current tip) and the slot number of the oldest header on the fragment. For Byron, we expect a slot density near 1.0, so `slots` will also be `k`. For Shelley, we expect a slot density near 0.1, possibly 0.05 (only 1 in 10 or 20 slots will contain a block), so `slots` will be `10 * k` or `20 * k` on average.

So far, so good.

However, it looks like somebody interpreted `slots` and `blocks` as the *current* slot number and the *current* block number, likely because of the confusing label names `"slotNum"` and `"blockNum"` (number of slots vs. slot number), and tried to translate those to the epoch number and the relative slot in the epoch number. Of course, translating the number of slots in the fragment to an epoch number is entirely incorrect.

As mentioned in #848, the epoch size is hard-coded to 21600, which works for Byron mainnet, but not other nets with different size. Moreover, this will also be incorrect for mainnet when we transition to Shelley, because the epoch size for the Shelley era will be different than the Byron era. The epoch size will depend on the current ledger state, so there won't be a single value that can be used.

We propose that consensus includes the "epoch number" and "slot in epoch number" in the `SwitchedToAFork` and `AddedToCurrentChain` trace events. This values can then be traced, instead of computing them here incorrectly. This also means the hard-coded `epochSlots` can go.

**Comment by Jimbo4350** [comment]
Fixed via https://github.com/input-output-hk/ouroboros-network/issues/2168
