### ISSUE TITLE
[BUG] - Clean shutdown failing on Windows / Shelley

### ISSUE THREAD

**Issue by rvl** [input-output-hk/cardano-node#1086]
**Summary**

We are integrating `cardano-node` in `cardano-launcher` and have found that the tests fail when using the shelley ff testnet configuration.

When `cardano-launcher` stops both `cardano-node` and `cardano-wallet` using the `--shutdown-fd` clean shutdown method, `cardano-wallet` exits, but `cardano-node` gets stuck and never exits until it is killed by `cardano-launcher`.

This does not happen when using the mainnet configuration file.  Nor does it ever happen on Linux.

I can see `received shutdown request` in the log. But I think other exceptions prevent clean exit from happening.

**Version**

- `cardano-node` version: [1.12.0-17-g7f4e1970](https://github.com/input-output-hk/cardano-node/commit/7f4e19708d5a2dba8d0622cac65fd83d3fdac486)
- Config files: ff from https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest/download/1/index.html

**Steps to reproduce**

Either:
* Run the cardano-launcher integration tests, or
* Use the cardano-launcher CLI in PowerShell like this:
  ```
  PS E:\cardano-launcher> npm run build
  PS E:\cardano-launcher> $env:PATH += ";e:\cardano-launcher"
  PS E:\cardano-launcher> $env:CARDANO_NODE_CONFIGS = "E:\cardano-launcher\shelley_deployments"
  PS E:\cardano-launcher> node .\dist\cli.js shelley ff $env:CARDANO_NODE_CONFIGS\ff .\state-ff
  ```
  Then use task manager to kill `cardano-wallet-shelley`. This will cause `cardano-launcher` to stop `cardano-node`.

**Expected behavior**
`cardano-node` exits immediately and normally.

**Actual behavior**
`cardano-node` does not exit, until the `cardano-launcher` kill timeout is reached.

**System info**
- OS: Windows 10, Windows server 2016

**Log file**
- From `cardano-launcher` CI - https://github.com/input-output-hk/cardano-launcher/runs/719510499?check_suite_focus=true
- From local test run (more detailed logging) - [cardano-launcher-integration-shelley-20200529.txt](https://github.com/input-output-hk/cardano-node/files/4701141/cardano-launcher-integration-shelley-20200529.txt)

**Comment by deepfire** [comment]
I have a suspicion why this is happening -- https://github.com/input-output-hk/cardano-node/pull/1436 is a potential fix.

**Comment by newhoggy** [comment]
I've added a new option `--shutdown-file`.  Would be good to know if using the alternative method works.

https://github.com/input-output-hk/cardano-node/pull/1631

**Comment by rvl** [comment]
Still an issue on version 1.18.0, now with shelley mainnet configuration.

It was working on cardano-node with the byron configuration.
Then it stopped working on the exact same version of cardano-node with the ff testnet configuration.
I had automated tests in cardano-launcher covering both.

If cardano-node does not exit after 60 seconds, cardano-launcher (i.e. daedalus) will kill it.

I could see from the logs that it notices that the pipe has been closed, but then something gets stuck during shutdown.

**Comment by vix-io** [comment]
hi @rvl are you still seeing this issue? We need a clear test case

**Comment by rvl** [comment]
I thought I gave a clear test case...

Anyway, I retested on Daedalus 2.2.0 (cardano-node 1.19.0) with Windows and the bug appears to be fixed.

The logs now say:
```
[35m[DESKTOP-:cardano.node:Notice:19][0m [2020-09-23 10:33:44.31 UTC] received shutdown request
[31m[DESKTOP-:cardano.node.DnsSubscription:Error:60][0m [2020-09-23 10:33:44.39 UTC] [String "Application Exception: 54.241.90.49:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
[35m[DESKTOP-:cardano.node.ChainDB:Notice:18][0m [2020-09-23 10:33:44.53 UTC] before next, messages elided = 553653211699
[35m[DESKTOP-:cardano.node.ChainDB:Notice:18][0m [2020-09-23 10:33:44.57 UTC] Chain extended, new tip: 1d1bb62f9f89eaab60470061cf4565506f108bb805138710e392c3cd16784080 at slot 41572
[34m[DESKTOP-:cardano.node.ChainDB:Info:18][0m [2020-09-23 10:33:44.57 UTC] Closed db with immutable tip at 65b018a316e8e4c0bb776f544c15e3a58b48024108ae02ae27b17697ee255ce3 at slot 39410 and tip 1d1bb62f9f89eaab60470061cf4565506f108bb805138710e392c3cd16784080 at slot 41572
```
I suppose this means that cardano-node exited normally. Before, it used to get stuck at `received shutdown request`.

**Comment by rvl** [comment]
This appears to be resolved now, thanks!
