### ISSUE TITLE
[FR] - Display invalid block count in LiveView

### ISSUE THREAD

**Issue by kantp** [input-output-hk/cardano-node#1088]
Currently, the LiveView has an entry `blocks minted`, showing the total amount of blocks that the node created, as well as `node is leader` for the number of slots in which the node was a leader. The two counters agreeing should be a good hint that things are probably working correctly.

However, if the operator did a mistake in setting up the node, such as providing a wrong key, the node can create invalid blocks (which the node itself will reject as invalid), but they will still count towards the total displayed in the LiveView. It would be useful to either add a field for displaying the count of invalid blocks, or to subtract invalid blocks from `blocks minted`.

In the metrics, we already have this detailed view (`cardano_node_metrics_Forge_node_is_leader_int`, `cardano_node_metrics_Forge_forged_int`, `cardano_node_metrics_Forge_forged_invalid_int`), but it would be nice to have it in the LiveView as well.

**Comment by CodiePP** [comment]
tracking in https://jira.iohk.io/browse/CAD-1136

**Comment by kantp** [comment]
Thanks, Alex!

**Comment by CodiePP** [comment]
solved by PR https://github.com/input-output-hk/cardano-node/pull/1202 ?
