### ISSUE TITLE
[BUG] - keys names in genesis.json are expected to start with an upper case when running Docker image

### ISSUE THREAD

**Issue by rene84** [input-output-hk/cardano-node#1092]
**Summary**
I am running cardano-node in a Docker image with custom configuration, genesis and topology. The process is failing reporting missing keys in the genesis file

**Steps to reproduce**
1. Download testnet config files from https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1
2. Place the files in a directory
3. Convert config.json to configuration.yaml
4. Run 'docker run -v $PWD/chain-data:/data -v $PWD/config-core:/configuration inputoutput/cardano-node:latest'
5. ```There was an error parsing the genesis file: /configuration/genesis.json Error: "Error in $: key \"StartTime\" not found"```

**Expected behavior**
Cardano-node to start successfully loading the configuration and genesis from provided files

**System info (please complete the following information):**
- OS: MacOs 10.15.4
- Docker: 19.03.8
- inputoutput/cardano-node:latest 06b99788ff45421da315af48a8d573225e0fda40d355c23c4eb95fa3620cb57d

**Additional context**
The Docker image runs fine without externally provided configuration files.
I also tried with inputoutput/cardano-node:master which is more recent. This gives another error:
```There was an error parsing the genesis file: /configuration/genesis.json Error: "Error in $: key \"systemStart\" not found"```

**Comment by mrBliss** [comment]
`startTime` just got renamed to `systemStart` in https://github.com/input-output-hk/cardano-node/commit/b9b1163d9db401d980234cce45ee7132452e1c32#diff-b4421230c623824e910dca72b1d152a5R4

Solution: rename your `startTime` in your genesis.json to `systemStart`.

**Comment by rene84** [comment]
Thanks. That does help. I'm not sure if it's best to use latest or master. Docs say latest anyway.

After renaming to systemStart, using master, I get the following error

```There was an error parsing the genesis file: /configuration/genesis.json Error: "Error in $: key \"networkId\" not found"```
