### ISSUE TITLE
[FR] - Add snapshots to the output of `cardano-cli shelley query ledger-state` and `stake-distribution`

### ISSUE THREAD

**Issue by kantp** [input-output-hk/cardano-node#1098]
The node is taking snapshots of the stake distribution and stake pools that determine the leader schedule and rewards.
The output of `cardano-cli shelley query ledger-state` and `stake-distribution` only has the current stake distribution and stake pool data.
In order to check whether your pool should be producing blocks currently, it would be useful to also have access to the snapshots of the ledger state (either through the `ledger-state` query, or a dedicated command).

**Comment by kantp** [comment]
@JaredCorduan tells me that what I'm really looking for is the field `nesPd :: !(PoolDistr crypto)` from `NewEpochState` -- the pool distribution that is used for the leader election.

**Comment by papacarp** [comment]
Current (active) stake is already in ledger state in the snapshots section.  There are three types of snapshots named Mark, Set, Go.  If you pull the data from the "Set" snapshot you will get stake for the current active epoch.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
