### ISSUE TITLE
[BUG] - Cardano-node fails to open prometheus ports, no errors 

### ISSUE THREAD

**Issue by Oqulent** [input-output-hk/cardano-node#1100]
**Summary**
A clear and specific description of what the bug is.
Two cardano-node running on the same machine with different configuration files except EKG ports (which were left the same by mistake).

The first node reads the config files and opens EKG and prometheus ports. The second node reads the config file, sees a port conflict in EKG ports? and does not open a PROMETHEUS port. I could not find traces of any error in logs.

**Steps to reproduce**
1. Run two+ instances of cardano-node
2. Specify different prometheus ports for each instance
3. Leave the same port for EKG on both nodes
4. Specify two different jobs in prometheus scraping from both nodes. 

**Expected behavior**
1. note the port conflict in EKG ports in logs.
2. follow through with opening prometheus ports which had no conflict.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version 1.12.1

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by CodiePP** [comment]
you need to make a copy of the configuration file and change the ports of EKG and Prometheus in one of them, then run each of the nodes with their respective copy of the configuration.
it's possible to run two nodes on the same machine, they just have to use distinct ports and socket files, etc.

**Comment by Oqulent** [comment]
> you need to make a copy of the configuration file and change the ports of EKG and Prometheus in one of them, then run each of the nodes with their respective copy of the configuration.
> it's possible to run two nodes on the same machine, they just have to use distinct ports and socket files, etc.

I understand that ports should be different for the different nodes. the issue here is that the mistake in EKG ports (which were left the same) prevents Prometheus ports from opening, with no traceable errors...

**Comment by dcoutts** [comment]
Setting priority low since there is a clear workaround.

**Comment by vix-io** [comment]
Hi Oqulent, this is Viktor at IOHK Tech Support. Thank you for reporting this bug. We have added it to our backlog and we`ll allocate it to one of our future development sprints. We appreciate your participation and support for the Cardano project!

**Comment by CodiePP** [comment]
tracked in CAD-1148

**Comment by denisshevchenko** [comment]
If I start two nodes with the same EKG port in the configuration - I see this error message in the log:

```
[cardano.#ekgview.realizeFrom:Error:5] [2020-07-13 20:19:22.14 UTC] EKGView backend disabled due to initialisation error: EKGServerStartupError "Network.Socket.bind: resource busy (Address already in use)"
```

or (in JSON-log) this one:

```
{{{"at":"2020-07-13T20:19:22.14Z","env":"1.14.0:aef5a","ns":"cardano.#ekgview.realizeFrom","data":

{"kind":"LogError","message":"EKGView backend disabled due to initialisation error: EKGServerStartupError \"Network.Socket.bind: resource busy (Address already in use)\""}
,"app":[],"msg":"","pid":"2398","loc":null,"host":"","sev":"Error","thread":"5"}}}
```
