### ISSUE TITLE
[FR] - ability to specify the testnet-magic with environment variable

### ISSUE THREAD

**Issue by Proxiweb** [input-output-hk/cardano-node#1109]
**Describe the feature you'd like**
It's cumbersome to have to specify the --testnet-magic parameter all time long.

**Describe alternatives you've considered**
It would be neat to have the possibility to set an environment variable which would be used by cardano-cli if specified ( export CARDANO_NODE_TESTNET_MAGIC = 42 for example ), the same way as CARDANO_NODE_SOCKET_PATH

**Comment by matiwinnetou** [comment]
+1 albeit I see it as low prio

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
