### ISSUE TITLE
[BUG] - cardano-cli ignores --testnet-magic while creating genesis

### ISSUE THREAD

**Issue by rcmorano** [input-output-hk/cardano-node#1113]
**Summary**
Although it's included in `cardano-cli` help message, it ignores the argument `--testnet-magic` while generating the files.

**Steps to reproduce**
1. Create a genesis using `cardano-cli` providing a custom `--testnet-magic`
2. Check the `networkMagic` in generated files is always `42`

**Expected behavior**
`gensis.spec.json` and the actual `genesis.json` should contain the provided `networkMagic`.

**System info (please complete the following information):**
- OS: ubuntu-20.04 official Docker image
- cardano-[node|cli] version: 
```
root@4e4a952b4cd4:/# cardano-cli --version
cardano-cli 1.12.0 - linux-x86_64 - ghc-8.6
git rev 8b68c74e3eea0a0d5866f7edee6f0414030b8d5a
root@4e4a952b4cd4:/#
```
**Screenshots and attachments**
- Proof:
```
root@4e4a952b4cd4:/# cardano-cli shelley genesis create --testnet-magic 6969 --genesis-dir /tmp/
root@4e4a952b4cd4:/# grep networkMagic /tmp/genesis*json
/tmp/genesis.json:    "networkMagic": 42,
/tmp/genesis.spec.json:    "networkMagic": 42,
```

**Comment by kevinhammond** [comment]
Maybe related to #1109

**Comment by Jimbo4350** [comment]
This has been fixed, the `--testnet-magic` argument currently works as expected.
