### ISSUE TITLE
[BUG] - cardano-cli does not exit with correct errorcode

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#1118]
Tag: pioneer-wave2

Tried to submit a stakepool de-registration certificate on the chain, cli exited with the following message:
`ApplyTxError [LedgerFailure (DelegsFailure (DelplFailure (PoolFailure (StakePoolRetirementWrongEpochPOOL {pfPOOLcurrentEpoch = 32, pfPOOLintendedEpoch = 35, pfPOOLepochMax = 33}))))]`

**But the exitcode (echo $?) of cardano-cli was still 0 (no Error) !**

I haven't checked other cardano-cli errors, but cardano-cli should(must) always exit with an exitcode other then 0 if something went wrong. Otherwise it's a nightmare to integrate it safe in automated scripts.

Thx!

**Comment by intricate** [comment]
This seems to be a particular issue with the `cardano-cli shelley transaction submit` command. Should be addressed by #1226 (once it's merged).
