### ISSUE TITLE
[BUG] - default eMax is too short

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1119]
**Summary**
cardano-cli generates a genesis with eMax of 1. We should default to something higher, like 1000.

Ran this by @JaredCorduan in debugging some issues with telegram user retiring a stake pool on ff.

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by JaredCorduan** [comment]
Just for a little extra context, this protocol parameter `eMax` determines how far out in advance a stake pool can plan a retirement. For example, if `eMax = 100`, then during epoch `1` a stake pool can submit a retirement certificate for epoch `100`, but epoch `101` is too far out.

**Comment by kevinhammond** [comment]
1000 seems a bit high as a default.  20 might be reasonable?

**Comment by dcoutts** [comment]
Was fixed by https://github.com/input-output-hk/cardano-node/pull/1145/commits/8778ceb15e069ab54dc414253525fe58ec73cc00
