### ISSUE TITLE
[BUG] - Stake pool deregistration not allowed when intended and max epoch are equal

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1121]
**Summary**
eMax in genesis is set to 1. These commands should work for deregistering a pool, but fail to submit the tx.

```
[nix-shell:~/work/iohk/cardano-node/ff-environment/keys/mypool]$ cardano-cli shelley stake-pool deregistration-certificate --epoch 34 --out-file stake.dereg --stake-pool-verification-key-file test.node.vkey

[nix-shell:~/work/iohk/cardano-node/ff-environment/keys/mypool]$ cardano-cli shelley transaction build-raw --tx-in ad88c91b99eba7e1ba542e09b97afc73c7b875c554f723d581d0b98c8f079a3c#0 --tx-out 6125b36d57e010f92c3d6f806c790a56026e89c51ed1e6fa5e0c3e5ba353b1e0f1+9787997991169779 --ttl 730000 --fee 171309 --tx-body-file tx-mypool.body --certificate stake.dereg

[nix-shell:~/work/iohk/cardano-node/ff-environment/keys/mypool]$ cardano-cli shelley transaction sign --testnet-magic 42 --tx-body-file tx-mypool.body --tx-file mypool.signed --signing-key-file ../utxo2.skey --signing-key-file test.node.skey

[nix-shell:~/work/iohk/cardano-node/ff-environment/keys/mypool]$ cardano-cli shelley transaction submit --testnet-magic 42 --tx-file mypool.signed
ApplyTxError [LedgerFailure (DelegsFailure (DelplFailure (PoolFailure (StakePoolRetirementWrongEpochPOOL {pfPOOLcurrentEpoch = 33, pfPOOLintendedEpoch = 34, pfPOOLepochMax = 34}))))]
```

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by JaredCorduan** [comment]
currently, we check that the retirement epoch `e` is between the current epoch `ce` and `ce+eMax`:
```
ce < e < ce + eMax
```

so that `ce + eMax` marks the first un-allowed epoch. we could check `<= ce + eMax` instead, so that `ce + eMax` is the last allowed epoch.

**Comment by oneEdoubleD** [comment]
This should be fixed now that eMax has been set to 135. Deregistration has been performed on the FF, although we're still waiting to confirm it in the next epoch.
