### ISSUE TITLE
[FR] - More descriptive error/validation messages for cardano-cli

### ISSUE THREAD

**Issue by ItFlyingStart** [input-output-hk/cardano-node#1125]
When there is a validation error, for example: an input value in invalid, then **cardano-cli** returns a message which is very difficult to understand. The error message is really developer centric. It contains only the error codes and some values, which doesn't provide enough information for the end users (= non technical/developer) how to solve the issues.

Can **cardano-cli** return the error message which contains more description? This will help the end users to understand the problem and how to fix it.

**Comment by Jimbo4350** [comment]
@ItFlyingStart Can you paste some examples of error messages from `cardano-cli` that are hard to understand?

**Comment by ItFlyingStart** [comment]
**Example 1:**
ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO {pfUTXOconsumed = Coin 4000000000000, pfUTXOproduced = Coin 200000000})))]

I know what the problem is, but this error message is difficult to understand for a layman. What is **ValueNotConservedUTxO**? Is there a description for each error code?

**Example 2**
cardano-cli shelley transaction build-raw \
     --tx-in  6f0400fd869a15b686e70b3535aa95b066118b47ae4dfaa141d0901122778604#0 \
     --tx-out 61ceed17bd63d8ef9d224d02860b1693dee2c09f071d043d1af719f3252060005f+200000000 \
     --tx-out 6124a23e8d3302636847fe148b94d942180f0a7f3170bda63d4f0aa88d33a0dd65+‭3999800000000‬ \
     --ttl 3600 \
     --fee 0 \
     --tx-body-file transactions/tx1.txbody

returns the next error:
option --tx-out: cannot parse value `6124a23e8d3302636847fe148b94d942180f0a7f3170bda63d4f0aa88d33a0dd65+‭3999800000000‬'

It doesn't give a hint how to fix this issue.

**Comment by kevinhammond** [comment]
I think this replicates #1005 ?

**Comment by ItFlyingStart** [comment]
Yes it is. Thanks for pointing this out and your quick reply.

**Comment by Jimbo4350** [comment]
@ItFlyingStart the tx out parsing error was improved in #1209. Is your first error example the output of a cli command or in the logs?

**Comment by ItFlyingStart** [comment]
From a CLI command, version 1.12. I haven't tried this out with the version 1.13 yet.

**Comment by ItFlyingStart** [comment]
FYI: same error message shown in version 1.13.0

ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Coin 99999834895) (Coin 100000234895))))]

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
