### ISSUE TITLE
[BUG] - Increased CPU and connections dropping on shelley relays after a few days.

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-node#1128]
**Summary**
On FF relays, after the node (`1.12.0`) has been running for a day or two, there is a slow increase in CPU usage, along with connections dropping until one of the core kept being busy 100% of the time and all communications stopped, and thus the relays stopped adopting new blocks. Other nodes fails to connect to it:
```
[String "Application Exception: 18.156.109.92:3001 ExceededTimeLimit",String "SubscriptionTrace",String "\"e-a-1.cardano\""]
[String "Closed socket to 18.156.109.92:3001",String "SubscriptionTrace",String "\"e-a-1.cardano\""]
[String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace ExceededTimeLimit)) 200s 200s",String "ErrorPolicyTrace",String "18.156.109.92:3001"]
```

- https://monitoring.ff.dev.cardano.org/grafana/d/ZaqfSS6mz/node-system-dashboard?orgId=1&var-job=node&var-node=e-a-1-ip&var-port=9100&from=1590732000000&to=1590743588000

The machine has 4G of ram and process has been started with `-N2 -A10m -qg -qb -M3G`.

On a higher-spec relay, with 16G of ram and started with `-N4 -A10m -qg -qb -M10G` we have not  seen this behavior (yet?).

**Additional context**
Profiling info available on dev-deployer, in directory `~/ff-profiling`.

**Comment by kevinhammond** [comment]
Are other processes running on the relay?  1GB free might be too little?  You could be forcing paging, which would explain the CPU usage and maybe the dropped connections.

**Comment by erikd** [comment]
I a single node instance is using 1G or RAM there is a space leak. Node memory usage should be less than half that.

**Comment by karknu** [comment]
Node memory consumption is dependent on the number of peers listed in the topology file. For every peer the last `k` blocks are kept in memory. A node with 64 peers will end up consuming more than 1Gbyte memory.
The memory consumption should slowly increase over 12h and then plateau.

**Comment by bergr01** [comment]
> Node memory consumption is dependent on the number of peers listed in the topology file. For every peer the last `k` blocks are kept in memory. A node with 64 peers will end up consuming more than 1Gbyte memory.
> The memory consumption should slowly increase over 12h and then plateau.

I have a node with one peer running for 24 hours now, it's memory usage currently is being shown as 429.3 / max 429.3 (it minted about 75 blocks, processed about 9700 txs during it's uptime). At what point in time do we anticipate memory usage by a node to actually drop / be garbage collected - without me needing to do a forceful recycled restart to knock it down to 200-250 MB mem usage that this node would typically get after a restart?

**Comment by vix-io** [comment]
hi @jbgi @disassembler is this still ongoing?

**Comment by laplasz** [comment]
I have this issue
```
dell:cardano.node.DnsSubscription:Error:1152] [2020-12-15 21:28:49.43 UTC] [String "Application Exception: 18.158.99.68:3001 ExceededTimeLimit (ChainSync (Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (ServerAgency TokNext TokCanAwait)",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
```

**Comment by cgi1** [comment]
we are facing the same issue here.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
