### ISSUE TITLE
[BUG] - cardano node hung on startup after updating topology

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1130]
**Summary**
After restarting cardano-node, node hangs and doesn't connect to peers or move up the blockchain. Restarting a second time fixed the issue.

**Steps to reproduce**
1. Modify ff-topology.json to include additional peers.
2. Send `INT` signal to cardano-node process to shut it down.
3. Wait 5 seconds to allow systemd script to restart the cardano-node.
4. Phone blows up when prometheus alerts me that node has fallen behind others.
5. See in grafana that the node was stuck until it was restarted a second time.

**Expected behavior**
Node should recover fine from a restart.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- pioneer-wave2

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/245918/83560145-98ac5000-a4ca-11ea-94a3-3c1a09cd4989.png)

Log File:
[relay1_hang.json.zip](https://github.com/input-output-hk/cardano-node/files/4719189/relay1_hang.json.zip)

**Comment by vix-io** [comment]
Hi AndrewWestberg, this is Viktor at IOHK Tech Support. Thank you for reporting this bug. We have added it to our backlog and we`ll allocate it to one of our future development sprints. We appreciate your participation and support for the Cardano project!

**Comment by vix-io** [comment]
hi @AndrewWestberg , can you still reproduce this?

**Comment by AndrewWestberg** [comment]
Closing. Cannot reproduce.
