### ISSUE TITLE
Provide transparent dockerfiles

### ISSUE THREAD

**Issue by ksemaev** [input-output-hk/cardano-node#1133]
**Describe the feature you'd like**
I want to be able to build my own docker image, that I will be sure is stable, and will not be overwritten (like the ones that are on github)

Currently I can only rely on the ones on dockerhub, but for stable environment I need to build them myself using your releases and my custom start-scripts, security settings etc. Can you publisg such dockerfile please?

**Comment by rhyslbw** [comment]
You can build your own by cloning the repo then running:
```
docker load -i $(nix-build -A dockerImage --no-out-link)
```
https://github.com/input-output-hk/cardano-node/blob/master/nix/docker.nix

**Comment by ksemaev** [comment]
@rhyslbw this is not build, it is load. It doesn't give me any control on docker image (custom scripts, users, configs)

**Comment by ksemaev** [comment]
Also wouldn't it be nice to have a sample dockerfile for all those out there who don't know syntax of that nix you're using?

**Comment by rhyslbw** [comment]
> this is not build, it is load.

Actually it's **_both_** in a single command. The image is built by this part:
```
nix-build -A dockerImage --no-out-link
```
... and then loaded into the engine. There's no `Dockerfile`, but you can extend this image in your own to apply custom layering.
