### ISSUE TITLE
systemd >= 2.3.0 not available with index-state: 2020-04-01T00:00:00Z

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-node#1139]
The constraint `systemd >= 2.3.0` cannot be satisfied with `index-state: 2020-04-01T00:00:00Z` (published after that date).
Current work-around is 
https://github.com/input-output-hk/cardano-node/blob/a9d1d22118e262d101f5f192935167cbf1112191/nix/haskell.nix#L24-L28

I tried bumping `index-state` to `2020-06-01T00:00:00Z` but then some packages failed to compile:
- https://hydra.iohk.io/build/2854503/nixlog/22
- https://hydra.iohk.io/build/2854465/nixlog/165

**Comment by erikd** [comment]
That version of systemd (https://hackage.haskell.org/package/systemd) was uploaded on 2020/04/23. I would suggest trying "index_state: 2020-05-01T00:00:00Z" but it probably needs to be bubbled up from the bottom of the stack.

**Comment by erikd** [comment]
I have started updating the index-state throughout the stack. I had to delay it until after this week's release.

**Comment by vix-io** [comment]
hi @newhoggy is this resolved now? if yes - we can close this ticket

**Comment by newhoggy** [comment]
I don't think this is an issue anymore.
