### ISSUE TITLE
[BUG] - Pool minted many blocks but received zero reward.

### ISSUE THREAD

**Issue by onyxstakepool** [input-output-hk/cardano-node#1140]
*External* 

**Summary**
Pool minted many blocks but received zero reward.
PoolID: 7250f69e28cba8ece0dd15299747db6c8644a1e5f936949817c183efd1a96c84

The pool had an initial pledge of 500k ADA that has been increased to 4.5M ADA in the pledge account. The pool has only the pledge delegated.
DelegatorID: eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e

The minted blocks are attached:
[Blocks.txt](https://github.com/input-output-hk/cardano-node/files/4726319/Blocks.txt)

**Expected behavior**
 A non zero reward value.

**System info**
- OS: Ubuntu
- Version: 20.04 LTS
- Node version: pioneer-wave2

**Additional context**
The pledge account is funded via two addresses (*This is likely unusual!*):
```
cardano-cli shelley query utxo --address 0174d39ed77a86c21ba4241d4f05687aaf9a383d28d05a78ea25b9216119419288eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e --testnet-magic 42
                           TxHash                                 TxIx        Lovelace
----------------------------------------------------------------------------------------
0567c83f834af96c3d6c685d1c8bf0b6c48ad449c2458d1a35c4d318c73277f3     0     1000000000000
```
```
cardano-cli shelley query utxo --address 018ec4cc454427f3d17dc9d17e5234b92f548929eeef005c50cf28567052a554d3eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e --testnet-magic 42
                           TxHash                                 TxIx        Lovelace
----------------------------------------------------------------------------------------
68f7da3a0dc0c621d9ea09e0e5b49a497300af199b677e3b644ee93a3f32cd5f     0     1000000000000
87c378fe0da6c5f94c03f369f96104964876bd4006477fa408d9fd59e896fed0     0      500000000000
b903b21715b6d74dff8b10125c9795ae0ed53861715fc65628acc3fe59fcd64e     0     2000000000000
```

**Comment by dcoutts** [comment]
Need to see the pool registration. The reward addr has to be specified there. This addr must itself be registered. Also, rewards are not paid out immediately but at the end of the epoch after the blocks were produced.

**Comment by onyxstakepool** [comment]
**Pool registration:**
Pool registration command:
```
cardano-cli shelley stake-pool registration-certificate --cold-verification-key-file node.vkey --vrf-verification-key-file vrf.vkey --pool-pledge 500000000000 --pool-cost 0 --pool-margin 0.05 --reward-account-verification-key-file stake.vkey --pool-owner-staking-verification-key stake.vkey --out-file pool.cert
```
Pool margin update command:
```
cardano-cli shelley stake-pool registration-certificate --cold-verification-key-file node.vkey --vrf-verification-key-file vrf.vkey --pool-pledge 500000000000 --pool-cost 0 --pool-margin 0.57721566490153286060 --pool-reward-account-verification-key-file stake.vkey --pool-owner-stake-verification-key-file stake.vkey --out-file pool.cert
```

**Additional info from the ledger state:** 
@dcoutts I assume, since all bits and pieces appear in the ledger, that all certificates were registered correctly.

```
"_ptrs":
                [
                    [
                        614110,
                        0,
                        0
                    ],
                    {
                        "tag": "KeyHashObj",
                        "contents": "eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e"
                    }
                ],
```

```
"_stkCreds":
                [
                    {
                        "tag": "KeyHashObj",
                        "contents": "eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e"
                    },
                    614110
                ],
```

```
"_rewards":
                [
                    {
                        "tag": "KeyHashObj",
                        "contents": "eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e"
                    },
                    0
                ],
```

```
"_delegations":
                [
                    {
                        "tag": "KeyHashObj",
                        "contents": "eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e"
                    },
                    "7250f69e28cba8ece0dd15299747db6c8644a1e5f936949817c183efd1a96c84"
                ],
```

```
"_pParams":
                "7250f69e28cba8ece0dd15299747db6c8644a1e5f936949817c183efd1a96c84": {
                    "_poolMD": {
                        "tag": "SNothing"
                    },
                    "_poolCost": 0,
                    "_poolVrf": "49ba7d00369bbd9a600b2291969286701806bda4fc95532ed536b7abb858f4b7",
                    "_poolRAcnt": {
                        "tag": "KeyHashObj",
                        "contents": "eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e"
                    },
                    "_poolOwners": [
                        "eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e"
                    ],
                    "_poolPledge": 500000000000,
                    "_poolMargin": 0.5772156649015329,
                    "_poolPubKey": "7250f69e28cba8ece0dd15299747db6c8644a1e5f936949817c183efd1a96c84",
                    "_poolRelays": []
                },
```

**Comment by onyxstakepool** [comment]
@dcoutts I have an idea what could be wrong. For the pool update I did not include the delegation.cert. I actively removed the delegation.cert in the transaction to follow the proposed solution of a pool update on the pioneer exercise 6 solutions sheet (Exercise 4. Change the parameters for your original pool.) 

If ture then this is an error in the documentation. (pioneer exercise 6 solutions)

[https://github.com/input-output-hk/cardano-tutorials/blob/master/pioneers-testnet/solutions/pioneers-exercise-6-solutions.md](https://github.com/input-output-hk/cardano-tutorials/blob/master/pioneers-testnet/solutions/pioneers-exercise-6-solutions.md)

```
cardano-cli shelley stake-pool registration-certificate --cold-verification-key-file node.vkey --vrf-verification-key-file vrf.vkey --pool-pledge 500000000000 --pool-cost 0 --pool-margin 0.57721566490153286060 --pool-reward-account-verification-key-file stake.vkey --pool-owner-stake-verification-key-file stake.vkey --out-file pool.cert

cardano-cli shelley transaction calculate-min-fee --tx-in-count 1 --tx-out-count 1 --ttl 700000 --testnet-magic 42 --signing-key-file payment.skey --signing-key-file stake.skey --signing-key-file node.skey --certificate-file pool.cert --protocol-params-file protocol.json

cardano-cli shelley transaction build-raw --tx-in 8d419712742654200bb98d61c96329acb4aeebbf97d48d54051f789e9b3de34b#0 --tx-out $(cat payment.addr)+548996714504 --ttl 700000 --fee 181737 --out-file tx003.raw --certificate-file pool.cert

cardano-cli shelley transaction sign --tx-body-file tx003.raw --signing-key-file payment.skey --signing-key-file stake.skey --signing-key-file node.skey --testnet-magic 42 --out-file tx003.signed

cardano-cli shelley transaction submit --tx-file tx003.signed --testnet-magic 42
```

**Comment by JaredCorduan** [comment]
@onyxstakepool from the logs you provided, the reward account is registered and the the owner is registered and properly delegated (which happens to be the same). you do _not_ need to re-delegate unless you changed the owners when updating the pool parameters. the pool parameters listed above must be your original ones, since I see the 500k pledge. how many epochs did you wait after being sure you had met your pledge?

**Comment by JaredCorduan** [comment]
> The original pool configuration had fixed and variable fee set to zero, but since four days the variable fee is set to 57% and the pool should produce rewards.

ok, yes, four days is a long time on the testnet, it must be something besides having not waited long enough.

And you are saying that `eaeb2b5d16c3276c3dacbf7955228766a61a9a3e46021d383e38902fd5da625e` has always had enough to meet the pledge?

> Thus the numerator and denominator in the rational approximation are very large integers. Could that cause numerical problems during the reward computation?

I do not think that that large numerator and denominator would cause a problem with the reward calculation. we use rational arithmetic (which uses Integer) and floor at the end.

**Comment by onyxstakepool** [comment]
I think I did not pay for the delegation certificate of the pledge. There is no error shown in the pool registration that includes the pledge.cert because the pledge cannot be paid before the pool is registered. I close the issue.
