### ISSUE TITLE
[FR] - CLI - Trigger Hard Fork (DevOps)

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#1141]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Describe the feature you'd like**
DevOps need a way to trigger the hard fork combinator (a normal protocol parameter
proposal will presumably not be adequate?).  This should be signed by a quorum of genesis delegates.

**Comment by Jimbo4350** [comment]
@kevinhammond is this still relevant? If it is, can you provide more information? Closing until then.
