### ISSUE TITLE
[FR] - reward calculator needed to estimate rewards given a set of parameters

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#1148]
It would be handy to have a simple webpage with a calculator, or a couple of paragraph write-up with a simple step by step scenario of how to calculate the rewards that a pool likely to receive given a set of genesis / protocol parameter values x, delegated total y, pledged amount z per epoch. (for ITN / Jormungandr we had this document - https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/incentives.md - which was a lot easier to digest than a whitepaper/spec document and allowed one to whip up a simple formula to estimate payouts for epochs A to B for a network that is being set up)

Some of of the parameters that need to be provided include max supply, treasury expansion, monetary expansion, fees. Calculator would be handy for both delegators (with sensible defaults) as well as pool operators (with customized settings) to double check whether what they are getting in a test environment in their reward balances matches the expectation or whether there's something obviously amiss / gone wrong.

**Comment by kevinhammond** [comment]
A web based calculator is already in progress, as an extension to the one for the ITN.

**Comment by CyberCyclone** [comment]
@kevinhammond can you please let me know if there's a repo for the "in progress" calculator? Or was this a planned project that has actually started? Thanks!
