### ISSUE TITLE
cardano-node is allowed to be started with a genesis setttings combination that prevents rewards being paid out

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#1149]
We ran into this the other day with a non-FnF network, that had epoch length set to a short value (30 minutes - 900 of 2s slots), and had a securityParmeter set to a rather high value. While the network was able to be started, with BFT and eventually Praos nodes and pool registration and funds transfers and delegations/pledging, there were no rewards sighted in the ledger state even after a dozen epochs. 

After discussing this with IOHK developer we were referred to some documentation related to epoch stages and certain expectations by Ourobouros in regards to the k and f parameters - eventually we lowered our securityParameter setting value and reset the network and got rewards being paid out correctly - however it would be better if extra validation could be added on the genesis settings involved, to alert the operator / network manager about the incorrectly configured genesis.

**Comment by mrBliss** [comment]
See https://github.com/input-output-hk/cardano-ledger-specs/issues/1516

**Comment by kevinhammond** [comment]
This is a misconfiguration that we are not reporting.
