### ISSUE TITLE
Have "cardano-cli shelley query utxo" command return error if address not valid [FR] - 

### ISSUE THREAD

**Issue by lsc3** [input-output-hk/cardano-node#1198]
External

For the HTN, I followed the following tutorial to get to this issue: https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/address.md.

For section 3 building the payment address, the tutorial provides the following without the --testnet-magic parameter. So if I'm correct it will default to building a mainnet address?:

cardano-cli shelley address build \
 --payment-verification-key-file payment.vkey \
 --stake-verification-key-file stake.vkey \
 --out-file payment.addr

If I take the produced "mainnet" address from above and run the following:

cardano-cli shelley query utxo --testnet-magic 42 --address "mainnet address"

The result is a normal empty utxo output. Which leads me to believe that it is a valid address.
The "mainnet" address was rejected when someone tried to send funds to it on the HTN. 

Would it be better if the query utxo output shows an error indicating the address is not valid for --testnet-magic 42? This way one can find out if address is valid before submitting a transaction.

I do see there's a cardano-cli shelley transaction check command but seems like it's not implemented yet? Perhaps this will be the solution?

Update:
Using the same tutorial above in step 5 creating a stake address ...

cardano-cli shelley stake-address build \
 --staking-verification-key-file stake.vkey \
 --out-file stake.addr 

This returns an informative error:
Usage: cardano-cli shelley stake-address build --stake-verification-key-file FILE
                                               (--mainnet | 
                                                 --testnet-magic NATURAL) 
                                               [--out-file FILE]

Adding this type of error to the above:
cardano-cli shelley address build ..... command would be nice.

Thanks.

**Comment by rdlrt** [comment]
@Isc3 - this issue is invalid.

> So if I'm correct it will default to building a mainnet address?:

> cardano-cli shelley address build 
> --payment-verification-key-file payment.vkey 
> --stake-verification-key-file stake.vkey 
> --out-file payment.addr

If you're using the right version of cardano-cli, the above statement will give an error stating:
`Missing: (--mainnet | --testnet-magic NATURAL)`

Ensure you're using cardano-cli version _1.13.0_ .

**Comment by lsc3** [comment]
I think you're correct. I did generate that address over a week ago so I probably did it with version 1.12.0 prior to upgrading to 1.13.0.
Thanks. Will close the issue.
