### ISSUE TITLE
[BUG] - Stuck zombie node. EKG won't connect. No peers

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1201]
**Exernal**

**Summary**
EKG url is unresponsive. The node loses all peers is is unable to connect to any. I would have thought it was an issue with my local network, but other nodes on the same machine are unaffected.  Restarting the node with SIGINT doesn't work the first time. Second SIGINT will bring it down and allow systemd to restart it. Node quickly recovers after a restart.

I've seen this happen approximately 4 times on my relay nodes. It hasn't happened yet on my core nodes.

**Steps to reproduce**
1. Run a relay with a good number of peers
2. At some point, get an alert in the middle of the night that wakes you up saying a node is down.
3. Notice that the process is not actually down, but an unworking zombie process. Try to look at EKG page, notice infinite spinner. Look at logs, notice it's trying to continually connect to peers but cannot.

**Expected behavior**
Node should not enter this zombie state. At minimum, node should take itself completely down so it can be automatically restarted by systemd.

**System info (please complete the following information):**
- OS:Ubuntu
- Version 20.04
- cardano-node 1.13.0

**Screenshots and attachments**
![Screenshot from 2020-06-07 08-19-51](https://user-images.githubusercontent.com/245918/83972910-c4974f00-a897-11ea-8598-13262bd50891.png)

[relay0-zombie.tar.gz](https://github.com/input-output-hk/cardano-node/files/4742330/relay0-zombie.tar.gz)
[relay0-zombie-1.tar.gz](https://github.com/input-output-hk/cardano-node/files/4742331/relay0-zombie-1.tar.gz)

**Additional context**

**Comment by AndrewWestberg** [comment]
Happened again today.

![Screenshot from 2020-06-08 19-40-28](https://user-images.githubusercontent.com/245918/84100087-fd324800-a9bf-11ea-99a0-d99cada07af5.png)

**Comment by AndrewWestberg** [comment]
Here's another log from today. Since the earlier hangs, it's much less frequent by reducing number of peers, but it still appears to be occurring. Same results though. Node is in a hung state where it's not outputting ekg or prometheus data. SIGINT doesn't restart the node and requires SIGKILL.

[zombielog.zip](https://github.com/input-output-hk/cardano-node/files/4782395/zombielog.zip)

**Comment by AndrewWestberg** [comment]
Happened again today on the latest 1.14.1 version. EKG just doesn't respond. Nothing out of the ordinary as far as CPU or anything else goes. Had around 20 peers at the time so the node wasn't overloaded or anything.

[hung_relay1.tar.gz](https://github.com/input-output-hk/cardano-node/files/4841420/hung_relay1.tar.gz)

**Comment by karknu** [comment]
How many peers are "a good number of peers"?

**Comment by AndrewWestberg** [comment]
Closing this as I haven't seen it in recent versions of cardano-node. Will open a new ticket if it re-occurs.
