### ISSUE TITLE
[FR] - pass node socket as a cli argument

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#1205]
**Internal**

**Summary**
`cardano-cli` requires for some commands access to environment variable "CARDANO_NODE_SOCKET_PATH". It would be nice if this would also be possible to pass in as a command line argument. The problem arose using `stack` with `nix` which is run in a pure environment. Maybe a pure `nix` environment is also affected.

**Steps to reproduce**

* CARDANO_NODE_SOCKET_PATH=logs/sockets/1  $CLICMD shelley query utxo --testnet-magic ${MAGIC} --address 608ff528da31160faec4764643200fb8790b8c948e5122bb100f80af5648c4eac6
(where CLICMD="stack --nix exec cardano-cli --")

the resulting error message:

```
Error while looking up environment variable: CARDANO_NODE_SOCKET_PATH  Error: "CARDANO_NODE_SOCKET_PATH"
```

**System info (please complete the following information):**
- OS: NixOS
- Version: nixos-unstable
- Node version: 1.12

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
