### ISSUE TITLE
[FR] - Keys import/export for Daedalus

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#1206]
**External**

Please implement a method for any advanced user/enduser/operator/owner to be able to import address & staking vkeys/skeys into Daedalus via an "Advanced" option in the Menu or via specific cli calls on the commandline to the cardano-wallet.

Also please add the option to export keys like the staking vkey/skey in some way.

Thx!

**Comment by kevinhammond** [comment]
This is for the Daedalus team

**Comment by Jimbo4350** [comment]
@gitmachtl This is probably stale by now but this belongs in https://github.com/input-output-hk/daedalus
