### ISSUE TITLE
[BUG] - Dedicated Rewards Account is not showing any rewards

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#1208]
**External**
F&F Testnet
Cardano-Node&CLI Tag 1.13.0

**Summary**
A block producing StakePool since Epoch 2/3 was re-registered with an individual RewardsAccount (StakeAccount). But, the rewards are still adding up in the normal PoolOwner account the pool was originally registered with. The change was made in Epoch 10, now checking back in Epoch 14. No Rewards showing up in the dedicated account. But it should if it is implemented as the specs suggest?
The rewards stake account is NOT delegated to the pool. It is just a registered stake account.

The original owner rewards are still increasing, and the dedicated rewards account shows 0 coins in rewards:
 ```
./cardano-cli shelley query stake-address-info --address $(cat multirewards.payment.addr) --testnet-magic 42
Delegations: fromList []
Reward accounts: fromList [(RewardAcnt {getRwdNetwork = Testnet, getRwdCred = KeyHashObj (KeyHash c449e15356992dfbbff647b9a021feb81c811991c47d76494c507e9f13f72ff6)},Coin 0)]
```

Owner Account:
```
./cardano-cli shelley query stake-address-info --address $(cat owner.payment.addr) --testnet-magic 42
Delegations: fromList [(KeyHashObj (KeyHash 35e4aa02647ea21238cb7ad5345472a19984d191c365f244824be1a9a355b37f),KeyHash d7962dad418218986e48bd5dcab3d6f7926eb5cc091d7f22f8e55383e7ebf654)]
Reward accounts: fromList [(RewardAcnt {getRwdNetwork = Testnet, getRwdCred = KeyHashObj (KeyHash 35e4aa02647ea21238cb7ad5345472a19984d191c365f244824be1a9a355b37f)},Coin 1093822003379)]

```

**Expected behavior**
The rewards from all the stakepool owners and the rewards from the poolCosts & poolFees should all end up in the dedicated rewards account.

**Screenshots and attachments**

Design specification from https://hydra.iohk.io/build/2339958/download/1/delegation_design_spec.pdf
![image](https://user-images.githubusercontent.com/47434720/84036294-53da5a80-a99d-11ea-89a8-28d20ccf6c58.png)

Ledger-State is showing the dedicated rewards account:
![image](https://user-images.githubusercontent.com/47434720/84036377-6d7ba200-a99d-11ea-80c7-371def99adea.png)

**Comment by gitmachtl** [comment]
Can be closed, it is working now. It took 4 epochs to show some results in the rewards account!

**Comment by kevinhammond** [comment]
Great!  4 epochs is expected.
