### ISSUE TITLE
[BUG] - LiveView in 1.13.0 shows always 0 forks

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#1211]
**External**

LiveView in 1.13.0 shows always 0 forks, prometheus metrics output shows another number.

![image](https://user-images.githubusercontent.com/47434720/84057198-a0329400-a9b7-11ea-93df-1007ac8a970a.png)

**Comment by kevinhammond** [comment]
Duncan suggests that we should not be reporting this behaviour

**Comment by gitmachtl** [comment]
Ok i understand, so next version without the "forks created:" display.

**Comment by rcmorano** [comment]
I also expressed a doubt about this in the related issue #1212. 

Passive/Relay nodes always report a constanly increasing number of forks, is it normal? What does that metric exactly mean?

**Comment by rcmorano** [comment]
JFTR, someone (can't remember who, but I think a trustable one :)) told that this metric was related about the observed forks (not necessarily created by your own node).
