### ISSUE TITLE
[BUG] - Mismatch between LiveView and metrics on forks created

### ISSUE THREAD

**Issue by mamapool** [input-output-hk/cardano-node#1212]
**Exernal**

**Summary**
LiveView always indicates 0 forks created. 
I assume that this number is related to "cardano_node_ChainDB_metrics_forksCreatedNum_int" on prometheus. 
"cardano_node_ChainDB_metrics_forksCreatedNum_int" is not always 0, the metric is not correctly reported on LiveView

**Steps to reproduce**
1. Run a node for a few hours, in LiveView mode
2. Go to prometheus and display the cardano_node_ChainDB_metrics_forksCreatedNum_int
3. Confirm that cardano_node_ChainDB_metrics_forksCreatedNum_int is not 0, and thus, the mistmatch with LiveView

**Expected behavior**
Correct forks created number in LiveView mdoe

**System info (please complete the following information):**
- OS: Ubuntu
- 20.04
- 1.13.0

![image](https://user-images.githubusercontent.com/63516083/84057416-f273b500-a9b7-11ea-9a08-8d788900a7dc.png)

**Comment by rcmorano** [comment]
I'm running on a headless, `LiveView`-less setup on k8s, so I had to go with `SimpleView` and I'm not sure the metrics are mismatching, but I'm seeing a lot of forks being reported by that metric on my relay/passive nodes (also on the producer) and wondering what it really means and if it's normal to have them.

Forks are constantly raising:

![image](https://user-images.githubusercontent.com/55876/84567441-fcf7cb00-ad78-11ea-956e-b4f9c06d928b.png)
