### ISSUE TITLE
[BUG] - failed to build cardano-node and cardano-cli

### ISSUE THREAD

**Issue by bahamasbahamas** [input-output-hk/cardano-node#1213]
*External*   otherwise.

**Summary**
cabal install cardano-node cardano-cli error 

**Steps to reproduce**
cabal install cardano-node cardano-cli

**Expected behavior**
build  cardano-node cardano-cli 

**System info (please complete the following information):**
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

cabal-install version 3.2.0.0

branch (detached from 1.13.0)

**Screenshots and attachments**
Completed    exceptions-0.10.4 (lib)
cabal: Failed to build entropy-0.4.1.5 (which is required by exe:cardano-node
from cardano-node-1.13.0, exe:chairman from cardano-node-1.13.0 and others).
The failure occurred during the configure step. The exception was:
dieVerbatim: user error (cabal: '/usr/local/bin/ghc' exited with an error:
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib/x86_64-linux-gnu/libtinfo.so.5: no
version information available (required by
/usr/local/lib/ghc-8.6.5/bin/../haskeline-0.7.4.3/libHShaskeline-0.7.4.3-ghc8.6.5.so)
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib/x86_64-linux-gnu/libtinfo.so.5: no
version information available (required by
/usr/local/lib/ghc-8.6.5/bin/../ghc-8.6.5/libHSghc-8.6.5-ghc8.6.5.so)
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib/x86_64-linux-gnu/libtinfo.so.5: no
version information available (required by
/usr/local/lib/ghc-8.6.5/bin/../terminfo-0.4.1.2/libHSterminfo-0.4.1.2-ghc8.6.5.so)
/usr/bin/ld.gold: error:
/usr/local/lib/ghc-8.6.5/rts/libHSrts_thr.a(Linker.thr_o): unsupported reloc
42 against global symbol free
/usr/bin/ld.gold: error:
/usr/local/lib/ghc-8.6.5/rts/libHSrts_thr.a(Schedule.thr_o): unsupported reloc
42 against global symbol stg_returnToStackTop
/usr/bin/ld.gold: error:
/usr/local/lib/ghc-8.6.5/rts/libHSrts_thr.a(Capability.thr_o): unsupported
reloc 42 against global symbol __stg_gc_enter_1
/usr/bin/ld.gold: error:
/usr/local/lib/ghc-8.6.5/rts/libHSrts_thr.a(Capability.thr_o): unsupported
reloc 42 against global symbol __stg_gc_fun

**Comment by kevinhammond** [comment]
I could not replicate this with 1.13.0 on Ubuntu - the problem looks like it might be an error in the cabal application itself (a memory error).

**Comment by erikd** [comment]
@bahamasbahamas Any chance you are running out of memory while building? GHC and cabal are unlikely to work in less than 8Gig of RAM and when they fail, the error you saw is one of the many errors that can occur.

**Comment by rdlrt** [comment]
> libtinfo.so.5: no version information available

Usually this file should pre-exist in your lib64 (LIBPATH) by default, on CentOS/RHEL builds we have had to create the symlinks manually (see steps [here](https://github.com/cardano-community/guild-operators/blob/master/files/ptn0/scripts/prereqs.sh#L123-L129) ), but I am not aware of needing this step on Debian builds - unless you're running things as root , which could at times mess up your load library path inheritance.

**Comment by kevinhammond** [comment]
Please let us know if this is still an issue.

**Comment by bahamasbahamas** [comment]
This issue looks similar to me. https://github.com/haskell/cabal/issues/6521
Shall I close the ticket because its related to cabal?


free -h output normal:
                                    total       used       free     shared    buffers     cached
Mem:                          7.8G       252M       7.6G        13M        14M       110M
-/+ buffers/cache:    127M       7.7G
Swap:                         0B         0B         0B

free -h  output after error yesterday (memory used 5.5G :D)
                                       total       used       free     shared    buffers     cached
Mem:                             7.8G       5.5G       2.3G        13M        92M       5.1G
-/+ buffers/cache:       354M       7.5G
Swap:                            0B         0B         0B

free -h  output after error, rebooted,  today (memory used 696M)
                                   total       used       free     shared    buffers     cached
Mem:                         7.8G       696M       7.1G        13M        25M       529M
-/+ buffers/cache:   141M       7.7G
Swap:                        0B         0B         0B

lscpu output: 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7702P 64-Core Processor
Stepping:              0
CPU MHz:               1996.250
BogoMIPS:              3992.50
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0,1

**Comment by bahamasbahamas** [comment]
Ah okay I just saw the post from @rdlrt. I will check it later. 

>  unless you're running things as root 

no

**Comment by bahamasbahamas** [comment]
However ubuntu 20LTS works for me.
