### ISSUE TITLE
[PERF] - Transactions slow the production of blocks down significantly

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/cardano-node#1214]
**Exernal**

**Summary**
Over 1,5 hours I added around 100+ tx per block. This slowed down the network / block producing by around 40%. I'm not sure, that the major hickup, that let me to end my test, was due to the number of transactions not clearing from the nodes.

**Steps to reproduce**
1. Add 100+ transactions to the chain within 4 seconds.
2. Wait for the block to be produced (new tip)
3. Check whether all tx went through.
Repeat over 1,5 hours or longer.

**Expected behavior**
The block production should not slow down by 40%. (And maybe: The network shouldn't come to a halt)

**System info (please complete the following information):**
- OS: Ubuntu
- Version: 20.04
- Node version: 1.13.0

**Comment by MarcelKlammer** [comment]
![htn-tx-load](https://user-images.githubusercontent.com/2163046/84137704-54cac500-aa4d-11ea-9925-97ba0857ecf7.png)

Todays test shows a reduction of block production of 20%, if the network has a load of about 100-300 tx per block.

Nodes that are running on low end hardware are seeing CPU overloads, RAM maxed out. 

Transactions aren't cleared from the mempool although the block that includes those was received.

Due to many nodes failing the network has major hickups.

**Comment by vix-io** [comment]
We did a lot of optimizations, we consider it closed.
