### ISSUE TITLE
[PERF] - Core is loosing connectivity to relays under high network load

### ISSUE THREAD

**Issue by polypool** [input-output-hk/cardano-node#1216]
**External**

**Summary**
During the load test made by MarcelKlammer, my core lost connectivity twice to its two remote relays.  CPU usage was saturated on two cores, but never on all of them. 

Multiple possibilities : 
If the "peer connectivity metric" is based on received slots in a given timeframe
- The cardano-node is not using all available cpus, the high load ended in being a DDOS attack and the relays were not able to forward slots to the core fast enough

If the "peer connectivity metric" is based on a keep-alive between nodes
- This connectivity should not be impacted by another thread/process overload

**Steps to reproduce**
1. Transaction stress test of the network
2. Monitor the "peers" metric

**Expected behavior**
Either a better multi-processing usage or independence between transaction consumption and network connectivity in order to avoid peers loss (depending on what the peers connectivity metric is based on)

EDIT : Confirmed that the cardano-node uses a limited number of cores per default, and that this can be modified with -N option in the command line. If the answer is that the only solution to avoid this DDOS attack is more processing power, this should be documented.

**System info (please complete the following information):**
- Ubuntu
- 20.04
- 1.13.0

**Screenshots and attachments**
![peers_loss_cardano](https://user-images.githubusercontent.com/63516083/84091524-ea863600-a9f4-11ea-83f3-4d979a47665e.jpg)

- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**
The core and 1 relay are both 6 cores VMs, 1 relay is a decentralised 4 cores VM. This could explains why 1 relay seems to loose connectivity more often (cf graph)  .

**Comment by kevinhammond** [comment]
Passed on for investigation

**Comment by alan-mcnicholas** [comment]
@oneEdoubleD can you take a look at this when you get a chance? Thanks! :)

**Comment by vix-io** [comment]
hi @mamapool are you still seeing this issue?

**Comment by mxdbld** [comment]
No, seems good

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
