### ISSUE TITLE
[BUG] - CLI "shelley genesis create" does not set '--testnet-magic' number in genesis.spec.json

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#1217]
**Internal**

**Summary**
The CLI command "shelley genesis create" does not set 'networkMagic' number in genesis.spec.json even if passed in with command line argument "--testnet-magic"

It is always falling back to:
```
"networkMagic": 42,
```

**Steps to reproduce**
1. cardano-cli shelley genesis create ... --testnet-magic <num> ... 
2. check file 'genesis.spec.json'

**Expected behavior**
The passed in '--testnet-magic' should be included in "genesis.spec.json" so the command can be rerun.

**System info (please complete the following information):**
- OS: NixOS
- Node version: 1.13

**Comment by Jimbo4350** [comment]
This has been fixed
