### ISSUE TITLE
[BUG] - Block Height Divergence During and After Increased TCP Connection

### ISSUE THREAD

**Issue by craigem** [input-output-hk/cardano-node#1218]
**Internal**

**Summary**
As illustrated in the Prometheus graph below, average TCP connections had a steep increase a little after 06:00. Cardano-node on edge node `e-a-1` started diverging at ~07:14.

![prometheus](https://user-images.githubusercontent.com/6470493/84123648-72b01e00-aa7d-11ea-9629-42a0c1d45349.png)

The initial increase in connections coincided with the systemd restart of `cardano-node` on `e-a-2`. The the first of a rolling systemd restart of `cardano-node` on each of the seven edge nodes (`e-a-1` was excluded) at > 10 minute intervals.

The divergence did not begin expressing itself until just prior to restarting the final node, `e-d-2` - a restart that was put on hold until `e-a-1` was no longer divergent. It later diverged again the block height metric has been "unstable" since.

![2020-06-09-184155_1278x1438_scrot](https://user-images.githubusercontent.com/6470493/84126185-edc70380-aa80-11ea-8669-87b82c0575f5.png)

Log file shared internally due to GitHub size restrictions.

**System info (please complete the following information):**
- OS: NixOS
- Version 20.03
- Node 1.13.0

Potentially related to [#1216](https://github.com/input-output-hk/cardano-node/issues/1216).

**Comment by vix-io** [comment]
hi @craigem can you still reproduce this?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
