### ISSUE TITLE
[PERF] - cardano-cli - query: shelley query tip locks the node

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/cardano-node#1221]
**Exernal**

**Summary**
Waiting for a new tip in a "while true" bash script, querying the tip, then sleep 2 seconds will eventually lock the node (not loading new blocks) with 100%+ CPU load. When the script is stopped (sleep2 + query tip) the node immediately loads the missing blocks and returns to normal.

**Steps to reproduce**

```

WAIT_STR="waiting for new block: #"

# Waiting for the new tip. Then check for changes in balances.

newTip=$(${CLI} shelley query tip ${MAGIC_PARAM} | awk 'match($0,/unSlotNo = [0-9]+/) {print substr($0, RSTART+11,RLENGTH-11)}')

while [[ ${newTip} -eq ${tip} ]]; do

  WAIT_STR="${WAIT_STR}#"
  echo -en "\r$WAIT_STR"
  sleep 2

  newTip=$(${CLI} shelley query tip ${MAGIC_PARAM} | awk 'match($0,/unSlotNo = [0-9]+/) {print substr($0, RSTART+11,RLENGTH-11)}')

done

```
Create some transactions, submit them to the network. Then wait for a new tip. When you receive a new tip, check whether the balances of the transactions are correct.

Do this long enough and the node will have 100+% CPU and doesn't not receive "new tips".

**Expected behavior**
Only checking the tip every 2 seconds should not slow down the node.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- 1.13.0

**Comment by kevinhammond** [comment]
Thank you.  We will investigate this.

**Comment by vix-io** [comment]
hi @MarcelKlammer can you still reproduce this?

**Comment by MarcelKlammer** [comment]
Might be tested again on the Goguen Testnet later this year. Closed for now.
