### ISSUE TITLE
Change severity of `NewReader` trace message

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#1224]
**Internall**

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

```
 getSeverityAnnotation (ChainDB.TraceReaderEvent ev) = case ev of
    ChainDB.NewReader {} -> Info
```
It should be `Debug` rather than `Info`.

**Comment by mrBliss** [comment]
All cases of that `ev` should be `Debug` instead of `Info`.
