### ISSUE TITLE
[BUG] - Could not update KES key

### ISSUE THREAD

**Issue by Octalus** [input-output-hk/cardano-node#1235]
*External*

**Summary**
My node (with block-producing key parameters) finishes syncing and at the end it receives a crash in a thread while updating the KES key? (why updating at all?)

[ip-172-3:cardano.node.ChainDB:Info:5] [2020-06-10 20:24:44.64 UTC] Closed db with immutable tip at (Point 493870, HashHeader {unHashHeader = f349f4d44b710be4f0a34fd95e7caa63ddea76f6e0bd27977f2608ba92b1961d}) and tip (Point 496226, HashHeader {unHashHeader = d308cdf7756051848de70e8b1329ffd55e138ce445e5c14983eed88dc7e84cce})
cardano-node: ExceptionInLinkedThread "ThreadId 36" **Could not update KES key
CallStack (from HasCallStack):**
  error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-55b9be0c7f9422e6b7c44bac1ad30688d43492a52c18286a75d850bb52fcb084:Ouroboros.Consensus.Shelley.Ledger.Forge

**Steps to reproduce**
1. Have a relay node with finished syncing.
2. Start the 2nd node, which receives data from relay node (same machine). This node has KES-Key etc configured to produce blocks (pool registered).
3. crash after 10 seconds.

**Expected behavior**
Should stay synced

**System info (please complete the following information):**
Amazon Linux 64Bit (but same also locally with an ubuntu installation with these keys)

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/12777042/84315746-6bb30980-ab6a-11ea-9adf-955319c1a330.png)

**! UPDATE !**
The problem seems to be my wrong creation of operational node certificate with my KEY-key. In the guide it is written with "kes-period 0" but this has to be replaced with the current KES-period. After recreating this with the current period number, my node worked fine.

https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/node-op-cert.md
```
cardano-cli shelley node issue-op-cert \
     --kes-verification-key-file kes001.vkey \
     --cold-signing-key-file node.skey \
     --operational-certificate-issue-counter node.counter \
     --kes-period 0 <-- 185 \
     --out-file node001.cert
```

I'm sure it shouldn't crash with a wrong period in the creation and the guide could be more precise here.

**Comment by podowd** [comment]
I'm encountering the exact same issue:

`ExceptionInLinkedThread "ThreadId 63" Could not update KES key                                                                                                                                                                                                   │      
CallStack (from HasCallStack):                                                                                                                                                                                                                                                 │      
  error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-inplace:Ouroboros.Consensus.Shelley.Ledger.Forge`

**Comment by mogadget** [comment]
Same issue here, still can't figure out what i missed

**Comment by subnet-dev** [comment]
Same issue here
```
[ae650c87:cardano.node.ChainDB:Info:5] [2020-06-11 21:26:48.73 UTC] Closed db with immutable tip at (Point 588329, HashHeader {unHashHeader = 0b79384f0645fe6be667605124d9a13bb8ad852ece70339b4c6f461df3e428a7}) and tip (Point 591690, HashHeader {unHashHeader = 7d3af6db747bfefd411056d11b601b2a56f17a0f7b3dfd7cceaeeb83176aa1cb})
cardano-node: ExceptionInLinkedThread "ThreadId 47" Could not update KES key
CallStack (from HasCallStack):
  error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-inplace:Ouroboros.Consensus.Shelley.Ledger.Forge
Listening on http://127.0.0.1:12798
```

**Comment by tao** [comment]
I believe I've run into the same problem:

```
unrealize UserDefinedBK "LiveViewBackend"
ExceptionInLinkedThread "ThreadId 457" Could not update KES key
CallStack (from HasCallStack): error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-55b9be0c7f9422e6b7c44bac1ad30688d43492a52c18286a75d850bb52fcb084:Ouroboros.Consensus.Shelley.Ledger.Forge
```

<img width="682" alt="Screenshot 2020-06-16 at 14 40 20" src="https://user-images.githubusercontent.com/1446331/84782027-75f85c00-afdf-11ea-9094-beb4e3a43af5.png">

I generated my KES files the previous day with the period 91, which is the answer I calculated while my node was still syncing... but after I got the error it was more up to date and I re-calculated my KES and opcert with the latest period 275 and it seems to be working now.

**Comment by mrBliss** [comment]
It seems like most commenters fixed their problem by issuing the right opcert.

I don't think there's a bug, but what we *can do* is make the error message clearer, which I'm doing in https://github.com/input-output-hk/ouroboros-network/pull/2291, and perhaps clarify the docs, which has apparently already been done, see [060_node_keys.md](https://github.com/input-output-hk/cardano-tutorials/blob/3f630b13c90a42e52b8c0cf2053657b3b5ef0a43/node-setup/060_node_keys.md#4-generate-the-operational-certificate), although there is still a [TODO](https://github.com/input-output-hk/cardano-tutorials/blob/3f630b13c90a42e52b8c0cf2053657b3b5ef0a43/node-setup/061_KES_period.md).

**Comment by matiwinnetou** [comment]
```
unrealize UserDefinedBK "LiveViewBackend"                                                                                                                                                                               cannot lead:     0          │
cardano-node: ExceptionInLinkedThread "ThreadId 78" Could not update KES key                                                                                                                                            forks created:   0          │
CallStack (from HasCallStack):                                                                                                                                                                                                                      │
  error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-inplace:Ouroboros.Consensus.Shelley.Ledger.Forge                                                       TXs processed:   70         │
[mati@cardano ~]$
```

In my case block-producing node was running fine....  I just restarted it... and crash

**Comment by kevinhammond** [comment]
I believe this issue is resolved, so I will close it.
