### ISSUE TITLE
cardano-cli issue-utxo-expenditure ...  has error :  cannot parse value `1cc4d8d38434170

### ISSUE THREAD

**Issue by jhonkingcai** [input-output-hk/cardano-node#1239]
I used cardano-node to synchronize a byron mainnet node, and used cardano-wallet to create a wallet and generate an address, all of which were successful.
Then I use cardano-wallet transaction create to create and send a transaction is also successful.

But when I want to use cardano-cli issue-utxo-expenditure to generate a signed transaction and broadcast it through cardano-wallet transaction submit in order to complete the transfer of ada. But it has not been successful, I almost collapsed, I hope someone can help me, grateful.

The complete command:

./cardano-cli issue-utxo-expenditure --config ./configuration-mainnet.yaml --tx ./txfile/ --wallet-key ./tx_data_key/utxo.skey --txin a4a283ee9dd93675d36239806a9c8105c9c7cdc16c085f44df72ac72d03b1b91,0 --txout DdzFFzCqrhsthh57LzbgwtzXM8r1JfQnuQcijUihJC6VswdfeGZ9pHiWNpvNncxuL3TjftkjnmJSCRRxDfgGgRYLAkyyef2CGopzjWBp:100000

Keep returning
--txin: cannot parse value `1cc4d8d3843417008e6a2b2dfb04bc00b3e636e55158dcfd131551d40ffbc8e7,0'
or
--txout: cannot parse value `DdzFFzCqrhsthh57LzbgwtzXM8r1JfQnuQcijUihJC6VswdfeGZ9pHiWNpvNncxuL3TjftkjnmJSCRRxDfgGgRYLAkyyef2CGopzjWBp:100000'

I don't know where is the error?
I think I followed the instructions of cardano-cli issue-utxo-expenditure -h
'Usage: cardano-cli question-utxo-expenditure--config NODE-CONFIGURATION
                                          --tx FILEPATH --wallet-key FILEPATH
                                          --txin (TXID, INDEX)
                                          --txout address: LOVELACE
  Writing a document with a signed transaction costs normal UTxO. "
But there has been no way to succeed, can someone help me, grateful! !

**Comment by jhonkingcai** [comment]
> That looks like an issue with `cardano-cli`, not cardano-wallet actually. cardano-cli is "part of" `cardano-node`, so let me transfer the ticket to `cardano-node` repo.

I successfully generated a signed transaction using the following command
./cardano-cli keygen --byron-formats --secret ./signkey
./cardano-cli issue-utxo-expenditure --config ./configuration-mainnet.yaml --tx ./tx0 --wallet-key ./signkey --txin'("1cc4d8d3843417008e6a2b2dfb04bc00b3e636e55158dcfd131551d40ffbc8e7",0)' --tx ("DdzFFzCqrhsthh57LzbgwtzXM8r1JfQnuQcijUihJC6VswdfeGZ9pHiWNpvNncxuL3TjftkjnmJSCRRxDfgGgRYLAkyyef2CGopzjWBp", 200000)'
I think it is wrong for cardano-cli -h to suggest help information about --txout.

**Comment by jhonkingcai** [comment]
I have a new question, how do I use the 12 word mnemonic to generate a wallet-key file for cardano-cli issue-utxo-expenditure signed transactions?

**Comment by kevinhammond** [comment]
The mnemonic mechanism is not supported by the node.  cardano-wallet will support this. cardano-cli also does not yet support Bech32 addresses.  I think that is the issue?

**Comment by jhonkingcai** [comment]
I solved my problem with cardano-tx and cardano-addresses

**Comment by intricate** [comment]
In the Byron CLI, we should probably parse the `--txout` value similarly to how we do in the `shelley` CLI commands.

i.e. it should look more like `--txout address+lovelace`.

The current way, `--txout '("address", lovelace)'`, just seems odd.

**Comment by intricate** [comment]
Right, we should update the help text for `--txout`. At the moment, it's incorrect:

```
Usage: cardano-cli issue-genesis-utxo-expenditure --genesis-json FILEPATH 
                                                  (--mainnet | 
                                                    --testnet-magic INT) 
                                                  (--byron-legacy-formats | 
                                                    --byron-formats | 
                                                    --shelley-formats)
                                                  --tx FILEPATH
                                                  --wallet-key FILEPATH
                                                  --rich-addr-from ADDR
                                                  --txout ADDR:LOVELACE
  Write a file with a signed transaction, spending genesis UTxO.

Available options:
...
  --txout ADDR:LOVELACE    Specify a transaction output, as a pair of an address
                           and lovelace.
...
```

The actual `--txout` format is more like: `--txout '("ADDR", LOVELACE)'`.

**Comment by steakandbake** [comment]
Hi all, similar issue I'm hoping you could help with. The inability to spend from a byron address.

`--txout '("ADDR", LOVELACE)'` was very helpful. I was stumped on that too.

1) Installed cardano-cli from branch release/1.15.x
2) Created skey with password using this command
`cardano-cli keygen --byron-formats --secret byron.skey`
3) Built public key address with 
`cardano-cli signing-key-address --secret byron.skey --byron-formats --mainnet`
4) Sent mainnet funds to generated public key
5) Synhronized a mainnet node. Confirmed on mainnet tip with 
`cardano-cli get-tip --mainnet`
5) Built transaction
`cardano-cli issue-utxo-expenditure --mainnet --byron-formats --tx outtx --wallet-key byron.skey --txin '("211f670a2bbc002fd69da9a408b5641aaa43c32934c5a3aafae23d755ec5a0d1",12)' --txout '("Ae2tdPwwrwYwgzWqEhEmbMdiyxZhcvGvykKYY16FWTLH5mEZkU7z9DaYaxE",999800000)'`

5) Submit-tx
`cardano-cli submit-tx --mainnet --tx outtx`

Nothing happens. No errors or transaction ID. Any suggestions? TIA.

**Comment by intricate** [comment]
Closing this issue. Opened https://github.com/input-output-hk/cardano-node/issues/1661 to track progress on updating the help text for the `--txout` CLI option.

**Comment by intricate** [comment]
Note that @steakandbake's issue mentioned in https://github.com/input-output-hk/cardano-node/issues/1239#issuecomment-663327014 was resolved: https://github.com/input-output-hk/cardano-node/issues/1564
