### ISSUE TITLE
[FR] - Expose cardano-node version in metrics

### ISSUE THREAD

**Issue by Proxiweb** [input-output-hk/cardano-node#1240]
Exernal

**Describe the feature you'd like**
Expose node version in metrics ( prometheus, ekg )

**Additional context / screenshots**
My node version was a wrong one ( 1.12.0 ) so the KES certificate was rejected. I would like to see my the node version in my Grafana dashboard to track down this type of error easily.

**Comment by CodiePP** [comment]
not relevant anymore as newer releases include this information
