### ISSUE TITLE
[BUG] - Malformed record in resolv.conf OR unexistant network interface results in node crashing

### ISSUE THREAD

**Issue by cardanobay** [input-output-hk/cardano-node#1241]
**External**

**Summary**

Having a malformed record in **/etc/resolv.conf** **OR** a well-formed ipv6 record **ending with an non-existent network interface** results in node displaying an error (and looping over this error for the Eternity).

This happened to me inside a Docker Container. The Docker Container inherit the parent /etc/resolv.conf (and the interface eno1), but this interface in NOT present inside the docker (dunno why... but it can happen !, and the network + dns resolution is working inside the container)

**Example /etc/resolv.conf**
```
search pascha.local cardanobay.com
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver fe80::8e59:c3ff:fecf:923b%eno1 
```

**Error**
```
[82f466a5:cardano.node.DnsResolver:Error:59] [2020-06-11 20:48:31.15 UTC] [String "lookup exception
 Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags =
 [AI_ADDRCONFIG,AI_NUMERICHOST,AI_PASSIVE], addrFamily = AF_UNSPEC, addrSocketType = Datagram, addrProtocol = 0, 
 addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just
 \"fe80::8e59:c3ff:fecf:923b%eno1\", service name: Just \"domain\"): does not exist (Name or service not
 known)",String "DnsTrace",String "\"relays-new.ff.dev.cardano.org\""]
```

**Steps to reproduce**

1. Add a non-existent network interface at the end of an ipv6 record
  * fe80::8e59:c3ff:fecf:923b%eno1 (no eno1 interface inside my docker)
2. Add a malformed IP address
   * 8.8.8.X
3. ... ? maybe some other scenarios, I can do more tests if you want

**Expected behavior**
If one resolver works (and the other fails), a warning can be emitted, and the node could continue its operations.

**System info:**
- OS: Tested on Debian 10 / Centos 8
- Version : 10 (buster) / 8
- Node version : cardano-cli 1.13.0 - linux-x86_64 - ghc-8.6

**Additional context**
I can add more information and do more troubleshooting if needed. Thank you.

**Comment by karknu** [comment]
This sounds like a problem with dns package used by ouroboros-network , https://hackage.haskell.org/package/dns .

**Comment by kevinhammond** [comment]
Is there a workaround we can use?

**Comment by coot** [comment]
If we detect an error we could re-try to configure the `dns` library with a predefined dns server using [resolvInfo](https://hackage.haskell.org/package/dns-4.0.1/docs/Network-DNS-Resolver.html#v:resolvInfo).

**Comment by coot** [comment]
The problem is that the `dns` library is using quite naive [parser](https://github.com/kazu-yamamoto/dns/blob/master/internal/Network/DNS/Resolver/Internal.hs#L50) and it does not validate the results.

**Comment by kevinhammond** [comment]
We should document this as a known issue, but we cannot do anything else at this point in time.  We will set up a process for this.

**Comment by coot** [comment]
@kevinhammond where it should be documented?

**Comment by nemo83** [comment]
I'm just hitting this issue. I'm running on arm64, ubuntu 20.04. Any workaround?

Thanks
