### ISSUE TITLE
[FR] - Allow withdrawal of rewards without an extra utxo for fees

### ISSUE THREAD

**Issue by onyxstakepool** [input-output-hk/cardano-node#1243]
**Exernal**

**Withdrawing rewards from a stake address requires an extra utxo for fees**

The transaction to withdraw rewards is more complicated than necessary since an extra utxo as input is mandatory. Building a transaction without a --tx-in gives an error.

A transaction without a --tx-in still makes sense because the --withdrawal stake account provides coins as input for the transaction from which fees can be taken.

**Additional context**
Desired transaction format:
```
cardano-cli shelley transaction build-raw --tx-out $(cat payment.addr)+1841509128 --withdrawal $(cat stake.addr)+1841680701 --ttl 600000 --fee 171573 --tx-body-file tx.raw
```

**Comment by dcoutts** [comment]
It's not about fees, it's about replay attack prevention.

See section 3.4.2 "Certificate Replay Prevention" of the Shelley Delegation Design Specification

https://github.com/input-output-hk/cardano-ledger-specs

Shelley is a UTxO based ledger. We rely on having at least one UTxO input in each transaction for replay protection. So although withdrawals and certificates can contribute positive balance to a transaction (e.g. deregistering certs returning deposits), they do not give replay protection.

This form of replay protection is rather nice and simple as a design. It means we do not need to sign certificates separately and do not need any other replay mechanisms. We just chuck everything into transactions, and transactions have automatic replay protection, and fees (for DoS prevention).

**Comment by MarcelKlammer** [comment]
Had it several times now, that I removed all ADA from an addr and tried to withdraw which obviously  failed. Had to send 1 ADA back to actually have one UTxO on that address again.

In the wallet this needs to be prevented. Or at least warned about. There should always be 1 ADA left to be able to withdraw the fee. Otherwise people will be stuck and don't know what to do to get their rewards.
