### ISSUE TITLE
[BUG] - Adding a Pool with meta info borks querying ledger state

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-node#1244]
**Exernal**

**Summary**

(*PS: Understand that master can break existing release, but raising it since someone trying this can potentially break the network*)

Tested registering a pool with a test metadata (using URL and hash) on a seperate (guild) network. The pool was registered successfully, but querying the ledger using cli (via `cardano-cli shelley query ledger-state`) run from any node causes CLI to hang , using up 100% CPU.

Since this change was committed to master branch, if someone attempts to, this can potentially break the existing public testnet network

(CC: @kevinhammond @intricate )

**Comment by kevinhammond** [comment]
This needs some investigation.  We should make sure that the chain data is clean, also that the node does not fail if bad data is present on the chain
