### ISSUE TITLE
[BUG] - cannot build on ubuntu with cabal

### ISSUE THREAD

**Issue by nilaysaha** [input-output-hk/cardano-node#1251]
**Internal/Exernal**
*External*   otherwise.

**Summary**
Simple cabal v2-build fails to detect OS.

**Steps to reproduce**

cabal v2-build all
Warning: Requested index-state2020-04-01T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2020-03-31T22:47:49Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: Win32-network-0.1.0.0 (user goal)
[__1] next goal: base (dependency of Win32-network)
[__1] rejecting: base-4.14.0.0/installed-4.14.0.0 (conflict: Win32-network =>
base>=4.5 && <4.13)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: Win32-network, base)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, Win32-network

**Expected behavior**
It should detect the os automatically.

**System info (please complete the following information):**
Output of uname -a: 
Linux lkbh-1 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Screenshots and attachments**
- Just git repo master branch of cardano-node

**Comment by erikd** [comment]
> Warning: Requested index-state2020-04-01T00:00:00Z is newer than
> 'hackage.haskell.org'! Falling back to older state (2020-03-31T22:47:49Z).

Run `cabal update`.

**Comment by romever** [comment]
I met the same problem as you.You should use ghc 8.6.5 when building.
`ghcup install 8.6.5
ghcup set 8.6.5
ghc --version`

**Comment by erikd** [comment]
Ok, I have re-produced that here.

**Comment by kaswarh** [comment]
> I met the same problem as you.You should use ghc 8.6.5 when building.
> 
> ghcup install 8.6.5
> ghcup set 8.6.5
> ghc --version

8.6.5 was helpful

**Comment by 7PintsOfCherryGarcia** [comment]
I am encountering the same problem. Switching to 8.6.5 did not help. More explanation here:
https://forum.cardano.org/t/cant-compile-cardano-node-from-source/61225/9

**Comment by coot** [comment]
Building with `ghc-8.6.5` is no longer supported, you'd need to use `ghc-8.10.4`.

**Comment by 34r7h** [comment]
if it's known why docs unupdated? y'all smoking too much

**Comment by jun0tpyrc** [comment]
on haskell:8.10.4-buster still can't build
```
root@ac39fdafec0f:/cardano-node# cabal install cardano-cli --overwrite-policy=always
cabal: Could not resolve dependencies:
[__0] next goal: cardano-crypto-class (user goal)
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
[__0] fail (backjumping, conflict set: cardano-crypto-class)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class
```

**Comment by carleryd** [comment]
I had the same issue when working on the Plutus Pioneer Program and resolved it by using nix-shell in https://github.com/input-output-hk/plutus
then the version changed to `8.10.4.20210212`

Also, I'm on commit `ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4` which may use a different cabal version in nix compared to latest on master.

**Comment by romulogarofalo** [comment]
I got this error
```
cabal: Could not resolve dependencies:
[__0] trying: byron-spec-chain-0.1.0.0 (user goal)
[__1] unknown package: microlens-th (dependency of byron-spec-chain)
[__1] fail (backjumping, conflict set: byron-spec-chain, microlens-th)
```
solved using `cabal install` (maybe u will need to run `cabal update`)
