### ISSUE TITLE
[FR] - 1.13.1 tag for commit c17483d

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#1252]
*External* 

Can we please have a Tag 1.13.1 or similar for the commit c17483d?

![image](https://user-images.githubusercontent.com/47434720/84577808-afeb1780-adbf-11ea-8f43-76e8558bd985.png)

This was a master commit that worked with the HTN genesis and also had the functionality
to claim the rewards. This is currently not possible with the latest master branch.

Thx!!!

**Comment by kevinhammond** [comment]
Tagged as 1.13.0-rewards
