### ISSUE TITLE
[BUG] - Shelley Test Script - tmux: unknown option -- E 

### ISSUE THREAD

**Issue by kilgoretrout** [input-output-hk/cardano-node#1261]
I wonder if you can help with the following, just trying to get a shelley test node up and running, thanks for any help!

**Summary**
Error when running shelley-testnet-live.sh

**Steps to reproduce**
1. Run shelley-testnet-live.sh

**Expected behavior**
Node starts running

**Error**
-- prebuilding the "cardano-node:cardano-node" executable in "cabal" mode..
-- RTS options:
-- cabal v2-run exe:cardano-node -- --help
tmux: unknown option -- E
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]

**System info (please complete the following information):**
- OS: Amazon Linux 2

**Comment by kevinhammond** [comment]
Passed on to the team.  If you follow the step by step instructions rather than using the script, I believe this will work.

**Comment by kilgoretrout** [comment]
Thanks Kevin, I used the following instructions to setup the environment...

https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/build.md

Should I now use the these instructions instead of using the script to configure the connection to the public shelley test net...

https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/start-node-connect-to-testnet.md

Thanks for your help.

**Comment by kevinhammond** [comment]
Yes, the instructions in https://github.com/input-output-hk/cardano-tutorials/tree/master/node-setup should get you moving
