### ISSUE TITLE
[BUG] - minSeverity should not influence the peers list

### ISSUE THREAD

**Issue by bahamasbahamas** [input-output-hk/cardano-node#1262]
*External*   otherwise.

**Summary**
If I set minSeverity to `"Error"` or `"Warning"` peers would show up in the peers list (node gui -LiveMode) but are not counted (peers: 0). 
The node also won't receive any txs with minSeverity = `"Error"` or `"Warning"`. 
If I set minSeverity to Info or Debug it works. 

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Go to config.json
2. change minSeverity to `"Error"` or `"Warning"`
3. start node in LiveMode

**Expected behavior**
The loglevel should not influence the peers list. 

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- 13

**Comment by CodiePP** [comment]
true, this is inconvenient. the minimum severity filter acts globally.
in the configuration under "options:" one can set severity filters on individual namespaces in "mapSeverity:"
