### ISSUE TITLE
[FR] - add cardano-cli docker image

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-node#1268]

**Comment by rhyslbw** [comment]
A feature request has been logged.

**Comment by disassembler** [comment]
What if we add cardano-cli to the cardano-node image and put it in the path?

**Comment by islishude** [comment]
We can use different image tag to distinguish

only node

```
inputoutput/cardano-node:VERSION
```

with tools(includes cardano-cli and cardano-address and so on)

```
inputoutput/cardano-node:VERSION-alltools
```

**Comment by rhyslbw** [comment]
@disassembler I suggest both, as it's a fair companion utility to include by default, but there is a decent use-case for a separate image too.

1. With `cardano-cli` (and also `cardano-node`) available on the path in the existing image, the entrypoint can be provided at runtime to override the default, or drop into the running container and use the tool directly.

2. A use-case for a separate image is to run single-shot commands against the node container, with auto-remove flag passed for cleanup.

```
-> docker run --rm -e CARDANO_NODE_SOCKET_PATH=/ipc/node.socket -v node-ipc:/ipc inputoutput/cardano-cli:1.13.0 shelley query tip --testnet-magic 42

Tip (SlotNo {unSlotNo = 674142}) (ShelleyHash {unShelleyHash = HashHeader {unHashHeader = 109af206e2388bd63e97a5d095ceffa8abc7e928e722640c8ada7e3ff23392b4}}) (BlockNo {unBlockNo = 29636})
```

**Comment by rhyslbw** [comment]
@islishude
> with tools(includes cardano-cli and cardano-address and so on)
This is more in the realm of Adrestia, so best to consider the scope here limited to the foundation.

I added some basic docs to `cardano-addresses` yesterday, highlighting the build option and an example [run command](https://github.com/input-output-hk/cardano-addresses#run). I'll add another to show input via `stdin`, which is a good strategy for chaining behaviour while respecting the service boundaries
