### ISSUE TITLE
[BUG] - DeserialiseFailure errors while syncing a relay node

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#1275]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
A lot of `DeserialiseFailure` messages into logs while syncing a relay node to the public testnet, with a clean state.

```
[ubuntu-4:cardano.node.BlockFetchDecision:Info:54] [2020-06-15 11:03:24.71 UTC] [String "PeersFetch",Array [Object (fromList [("peer",String "ConnectionId {localAddress = 116.203.141.1:40517, remoteAddress = 52.76.171.181:3001}"),("kind",String "FetchDecision declined"),("declined",String "FetchDeclinePeerShutdown")])]]
[ubuntu-4:cardano.node.DnsSubscription:Error:4871] [2020-06-15 11:03:24.71 UTC] [String "Application Exception: 52.76.171.181:3001 DeserialiseFailure 1586 \"expected integer\"",String "SubscriptionTrace",String "\"relays-new.ff.dev.cardano.org\""]
[ubuntu-4:cardano.node.ErrorPolicy:Warning:66] [2020-06-15 11:03:24.71 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (DeserialiseFailure 1586 \"expected integer\"))) 200s 200s",String "ErrorPolicyTrace",String "52.76.171.181:3001"]
```

**Steps to reproduce**
1. start a relay node using the below command and attached files
```
cardano-node run --topology relay/ff-topology.json \
	--database-path relay/db \
	--socket-path relay/db/node.socket \
	--host-addr YOUR_IP_ADDRESS \
	--port 3002 \
	--config relay/ff-config.json
```
2. let the node run for 1 min
3. check the logs

**Expected behavior**
No exception messages should be seen in the logs.

**System info (please complete the following information):**
- OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)
- Node versions
```
# cardano-node version
cardano-node 1.13.0 - linux-x86_64 - ghc-8.6
git rev b41f4de42378b2557011e5f4f8c87e8d878a5ae2

# cardano-cli version
cardano-cli 1.13.0 - linux-x86_64 - ghc-8.6
git rev b41f4de42378b2557011e5f4f8c87e8d878a5ae2
```
```
# git rev-parse --verify HEAD
b41f4de42378b2557011e5f4f8c87e8d878a5ae2
```

**Screenshots and attachments**
- node logs
[relay-20200615105634.log](https://github.com/input-output-hk/cardano-node/files/4779886/relay-20200615105634.log)
[relay-20200615104110.log](https://github.com/input-output-hk/cardano-node/files/4779888/relay-20200615104110.log)

- node files (remove the .txt extension)
[ff-config.json.txt](https://github.com/input-output-hk/cardano-node/files/4779897/ff-config.json.txt)
[ff-genesis.json.txt](https://github.com/input-output-hk/cardano-node/files/4779899/ff-genesis.json.txt)
[ff-topology.json.txt](https://github.com/input-output-hk/cardano-node/files/4779900/ff-topology.json.txt)

**Comment by mrBliss** [comment]
Does this still happen with 1.14.2?

**Comment by mrBliss** [comment]
We're already on 1.15.0. Please reopen when you can reproduce, but I don't think that's very likely.
