### ISSUE TITLE
[BUG] - Function Cardano.API.readSigningKey inconsistent with CLI version

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/cardano-node#1302]
*Internal* 
**Summary**
Cardano.Api export the function `readSigningKey`.
This functions is incompatible with the key-files that are generated by the CLI tool.
`readSigningKey` uses a tagged representation while the cli does not use tags.

https://github.com/input-output-hk/cardano-node/blob/master/cardano-api/src/Cardano/Api/CBOR.hs#L99

https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs#L196

**Comment by dcoutts** [comment]
This was while we were moving from the old API to the new one. The old one is now gone.

If you think there is still a problem please re-open.
