### ISSUE TITLE
[FR] - Cardano-cli - timeout request / selfkill

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-node#1311]
![obrazek](https://user-images.githubusercontent.com/58650764/85195541-c3bcdf00-b2d3-11ea-8bbe-604ee2a5bbc8.png)

**Comment by rdlrt** [comment]
There was a bug (reported in #1244 ) and this is already fixed on master.
You can either apply that fix by manually editing the file, or wait for new genesis (since master is not compatible with FF network).

**Comment by kevinhammond** [comment]
I have closed this issue since it is resolved.
