### ISSUE TITLE
[BUG] - relay node gets stuck after it is freshly started with new DB directory

### ISSUE THREAD

**Issue by nilaysaha** [input-output-hk/cardano-node#1313]
**Internal/Exernal**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Summary**
Cardno-node when started from a fresh db state(new db directory) gets stuck at the following entry:
Jun 20 18:12:32 cardano-relay ff-node-testnet[28919]: [cardano-:cardano.node.ChainDB:Debug:37] [2020-06-20 16:12:32.09 UTC] Performed a garbage collection for 5567
Jun 20 18:21:26 cardano-relay ff-node-testnet[28919]: [cardano-:cardano.node.ChainDB:Debug:33] [2020-06-20 16:21:26.70 UTC] TraceImmDBEvent

**Steps to reproduce**
1. cardano-node run with typical configuration (https://testnets.cardano.org/en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/)

**Expected behavior**
Normally it is not stuck as it happens now.

**System info (please complete the following information):**
output of uname -a: 
Linux cardano-relay 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Screenshots and attachments**

Jun 20 18:12:32 cardano-relay ff-node-testnet[28919]: [cardano-:cardano.node.ChainDB:Debug:37] [2020-06-20 16:12:32.09 UTC] Performed a garbage collection for 5567
Jun 20 18:21:26 cardano-relay ff-node-testnet[28919]: [cardano-:cardano.node.ChainDB:Debug:33] [2020-06-20 16:21:26.70 UTC] TraceImmDBEvent

**Additional context**

**Comment by nilaysaha** [comment]
Solved. Had to update the config files. It is in all probability due to the wrong version of ff-genesis.json file. Works now ...

**Comment by bergr01** [comment]
So you should probably close this issue instead of leaving it Open?

**Comment by nilaysaha** [comment]
solved the problem by updating with the latest config files.

**Comment by nilaysaha** [comment]
Thanks buddy. For pushing me to do things right way. Appreciate it
