### ISSUE TITLE
[BUG] - Blocks I mint keep getting orphaned (& don't appear on ff.pooltool.io)

### ISSUE THREAD

**Issue by podowd** [input-output-hk/cardano-node#1319]
*External*

**Summary**
Blocks I mint keep getting orphaned (& don't appear on ff.pooltool.io) even though my relays have been added to the ff-peers.nix (on the 17th). (Also my block producing node is not processing any Txs, other than ones I create myself). I did ask about this on the Telegram channels, but didn't get a solution.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Had my relays added to ff-peers.nix
https://github.com/input-output-hk/cardano-ops/blob/c88504d264070ae45da193e5931764f5bf948d9c/topologies/ff-peers.nix#L776-L787

2. My relays are reachable from outside, they have 12 and 7 connected peers each at the moment. The topology files for each where created from the download from the getBuddies.sh script from ff.pooltool.io

3. I can see in the console my block producing node is minting blocks (but not processing any outside txs) (And to confirm it is connected to my 2 relays)

4. Would expect the blocks minted in (3) to appear here, but they are not:
https://ff.pooltool.io/pool/19137086e08fee8e27788dfe9670836a23b69b35d141b41ade24f77c133c3d31/blocks
**Expected behavior**
Blocks minted in (3) above, would appear in (4). Also expect to see my block producing node processing external txs.

**System info (please complete the following information):**
- OS: Ubuntu
- Node version: 1.13.0-rewards

**Comment by karknu** [comment]
> Also expect to see my block producing node processing external txs.
Yes. The fact that you don't see any Tx means that your core node is not considered upstream from anyone. If your relays sees Txs it means that they are up stream  some peers which means that the problem is in your relays' topology files. If the relays doesn't see any Tx it means that they have no upstream nodes.

**Comment by podowd** [comment]
Both my relays have no Txs either

**Comment by podowd** [comment]
So is there anything I can do to fix this?

**Comment by karknu** [comment]
You need fix your setup so that peers can and do you use as an upstream peer.

**Comment by podowd** [comment]
Thanks, one last question if that is ok:
But my setup is correct - the issue is no one is using me as an upstream peer (which is out of my control) - correct?

I can even see my relays connected to the network here:
https://ff.pooltool.io/network

**Comment by karknu** [comment]
> Thanks, one last question if that is ok:
> But my setup is correct - the issue is no one is using me as an upstream peer (which is out of my control) - correct?

I don't know if your setup is correct. The reason no one is using you as an upstream peer could for example be that the ip and/or port number you've provided is different than the one your node is really using.

**Comment by podowd** [comment]
ok thanks, I'll rephrase - what I meant is: I have checked my configuration numerous times at this stage and everything seems correct to me. So as far as I can tell its just that no one has added me as an upstream peer.

I have even checked my relay ports from external servers and they are accessible:
```
nc -zv 46.101.64.236 8081
nc: connectx to 46.101.64.236 port 8081 (tcp) failed: Connection refused
```

**Comment by karknu** [comment]
> nc -zv 46.101.64.236 8081
nc: connectx to 46.101.64.236 port 8081 (tcp) failed: Connection refused

That means that there is no application accepting connections on that port. Which is also true for your second relay at port 8082. Are you running `cardano-node` with the correct arguments (`--port 8081`)?

**Comment by podowd** [comment]
I had thought (incorrectly) it was so the relay process was just refusing the connection, but yes this is an issue on my side and the jira can be closed. Thanks again
