### ISSUE TITLE
Issue with the Cardano Node and ufw (Firewall configuration?)

### ISSUE THREAD

**Issue by djalillounis** [input-output-hk/cardano-node#1321]
**IExernal**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Summary**
After building the node on Ubuntu 20(TLS). the Node started and connected to peers.

to add more security I enabled the ufw with the following :
ufw allow 3001/tcp 
ufw allow  ssh 
ufw enable

restart the node log mode LiveView  and my node was not showing any peer on the list and all the stats are in 0

**Steps to reproduce**
1 ) Stop the node (log mode liveView)
2) allow <NodePort>/tcp any
3) restart the node 

Note if you start the node on SimpleView you can see that you node is connected.
 

**Expected behavior**
node showing peers and stats 

**System info (please complete the following information):**
- OS: Ubuntu
- Version . 20.04
- Node version : 10.13.0

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by smaug-group** [comment]
You need to set `TraceBlockFetchDecisions` to `true` in the config for peers to be listed in `LiveView`. 

See https://github.com/input-output-hk/cardano-node/issues/982.

**Comment by djalillounis** [comment]
Hello @smaug-group ,

The TraceBlockFetchDecisions is set to true.
The node was working fine and  displaying  Peers. the Issue started after I enabled the ufw .

After I enable it the Peers were not displayed and even after turning the ufw to disabled the issue was still there.


PS: In simple View I can see that the node is connected to 2 peers.

**Comment by djalillounis** [comment]
I think that I figured out what is the problem.
I need to allow also the port :13788 and 13798 in the UFW.
Can some from IOHK confirm what are the port that has to be allowed ?
Thank you

**Comment by disassembler** [comment]
is ufw blocking localhost traffic? No ports other than 3001 should need opened to the public. Everything else should be internal (or at least only listening on your internal LAN if your customizing the config to expose them).

**Comment by djalillounis** [comment]
@disassembler 
Does the core need inbound connection from the my relay ?
If it is running on port 3000 should I allow inbound from IPs(public) of the relies?

**Comment by karknu** [comment]
> @disassembler
> Does the core need inbound connection from the my relay ?
> If it is running on port 3000 should I allow inbound from IPs(public) of the relies?

You must permit your relay to connect to your core node.

**Comment by kevinhammond** [comment]
I believe we can close this.
