### ISSUE TITLE
[FR] - CLI pool metrics

### ISSUE THREAD

**Issue by Scitz0** [input-output-hk/cardano-node#1322]
**External**

**Describe the feature you'd like**
Currently, a ledger-state dump is needed to check the pool registration status.

For example '.nesEs.esLState._delegationState._pstate._pParams|_fPParams|_retiring' in ledger-state would be very useful to be able to query for a specific pool id without dumping the entire ledger-state. 

They are used in many of the community tools to check the status of a pool registration like CNTools I'm personally involved in. On MainNet dumping the ledger-state(411mb as of epoch 231) and parsing through it is a very heavy operation that could lead to server/node crashes and performance issues due to OOM, high CPU load, or the like. 

There could be other potential areas of the ledger-state that could be useful to dump as well but the above alone would go along way if it was implemented. 

**Describe alternatives you've considered**
Continue to use ledger-state dump even though it could cause high-load issues. Another option is a more advanced setup with db-sync or the like but for a "simple" tool to manage wallets and pools, this seems like overkill.

**Additional context / screenshots**
Partly related to #1052 and other CLI request issues to get more status through cardano-cli.

**Comment by papacarp** [comment]
I'd like to tack onto this FR  to separate ledger state into different sections so we can grab only what we need.  Even if we just broke up the snapshots (MARK, SET, GO) into their own endpoints in addition to the nonmyopic snapshot that would speed everything up drastically.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
