### ISSUE TITLE
[BUG] - node memory usage incorrectly reported in LiveView

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#1338]
cardano-node 1.14.0 - linux-x86_64 - ghc-8.6
git rev 19b8b8dce74287101e0633a5300094aebd407e4c

LiveView is showing node memory as 0, even though the process is clearing using over 100 MBs of RAM, as is also confirmed by the prometheus metrics:

curl http://127.0.0.1:13798/metrics 2>/dev/null | grep -i mem | grep -v -i mempool
cardano_node_metrics_Mem_shared_int 10202
cardano_node_metrics_Mem_data_int 65747
cardano_node_metrics_RTS_maxUsedMemBytes_B 157286400
cardano_node_metrics_Mem_text_int 11625
cardano_node_metrics_Mem_size_int 268663389
cardano_node_metrics_Mem_resident_int 50306
cardano_node_metrics_Mem_data_int 64723
cardano_node_metrics_Mem_resident_int 49110
cardano_node_metrics_Mem_size_int 268663389
cardano_node_metrics_Mem_text_int 11625
cardano_node_metrics_Mem_shared_int 10202

**Comment by mark-stopka** [comment]
Same issue with 1.14.2...

![image](https://user-images.githubusercontent.com/18139116/86052524-6bb27500-ba57-11ea-9235-c0485947463e.png)
