### ISSUE TITLE
[BUG] - --version doesn't have correct revision when doing a non-clean build

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1342]
**Exernal**

**Summary**
Building cardano-cli and cardano-node from a non-clean state shows incorrect revision hash from 
```
cardano-cli --version
```
and
```
cardano-node --version
```

**Steps to reproduce**
1. git checkout 1.14.0
2. cabal clean
3. cabal build all
4. cardano-cli --version
```
cardano-cli 1.14.0 - linux-x86_64 - ghc-8.6
git rev 46f296f8a9f3f497d9bd41e20c8398d2b5730c86
```
5. git checkout 1.14.1
6. cabal build all
7. cardano-cli --version
*Without clean, Incorrect!*
```
cardano-cli 1.14.0 - linux-x86_64 - ghc-8.6
git rev 46f296f8a9f3f497d9bd41e20c8398d2b5730c86
```
8. cabal clean
9. cabal build all
10. cardano-cli --version
*After clean, Correct!*
```
cardano-cli 1.14.0 - linux-x86_64 - ghc-8.6
git rev 46f296f8a9f3f497d9bd41e20c8398d2b5730c86
```
**Expected behavior**
Rebuilding a different revision should update the git rev information in the version.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version 1.14.x

**Comment by mark-stopka** [comment]
I can add that `git rev` is totally broken (all zeros) if using `cabal install` even on clean build...

**Comment by vix-io** [comment]
We are not going to fix this.

**Comment by mark-stopka** [comment]
@mimi1vx, do you have any rough idea what would it take to fix this issues? TL;DR `cabal build` shows correct git devision, `cabal install` shows only zeroes... I'd be wiling to sponsor a fix if the cost would be reasonable as this annoys me a lot.

**Comment by mimi1vx** [comment]
@mark-stopka it suses pretty clever trick with injection of gitRev ( borrowed from Michale Snoyman and stack) during compilation time, so it isn't simple to fix (probadly it needs work on Cabal side).

From another angle with cabal nix-style build ( `cabal new-build | cabal v2-build`) issue isn't reproducible

**Comment by mark-stopka** [comment]
@mimi1vx would that be a minor update to `cabal`, or something major with a budget above let's say 10k CZK?
