### ISSUE TITLE
[FR] - Performance metrics and guarantee of terms in the smart contract

### ISSUE THREAD

**Issue by Willburn** [input-output-hk/cardano-node#1351]
*External*  

Performance metrics and guarantee of terms in the smart contract / on chain itself. 
Due to trust issues indirect calculations might not be accepted by users in certain use cases. As an example imagine a smart contract called "vacation delegation" that you sent ADA to and then through performance metrics delegated automatically to pools. With indirect calculations you would be at the mercy of the contract but with guaranteed on chain metrics you would not. 

A side issue but it would be interesting also if you could guaranteeing that a sum would indeed be returned after X amount of time due to some verification that where run on the smart contract. 

**Describe alternatives you've considered**
Oracle solutions would probably be a preferred method as it would decrease information that needs to be on the chain and could serve as a trusted party.

**Comment by Willburn** [comment]
(Also not sure if this be here in cardano-node or some of the other repositories is the more correct place so apologize in advance if not the correct place.)

**Comment by vix-io** [comment]
We have put this in our backlog.
