### ISSUE TITLE
[BUG] - regular desync of relays since 1.14.0

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/cardano-node#1353]
**Exernal**

**Summary**
Since the start of the new chain my EU relays frequently (1-2 times per day) desync, while the US relays are keeping (more or less) up. Relays are on AWS EC2 (EU: Frankfurt, US: NV). 

The CPU of the desynced relays is maxed out.

Pools (EU), which feed from all the relays are fine.

This did not happen prior to 1.14.0 and the chain switch.

**Steps to reproduce**
Run nodes in EU and US, interconnect them. Leave them running over night.

**Expected behavior**
Relays shouldn't desync with CPU maxed out.

**System info (please complete the following information):**
- OS: Ubuntu 20.04
- Node version: 1.14.1 (git tag, not version)

**Screenshots and attachments**
![desynced_relays](https://user-images.githubusercontent.com/2163046/85917358-d1391280-b859-11ea-8c59-5d044a2b1250.png)

Some logs of r-eu-0 (CPU maxed out), hope it helps.

[logs-200627.zip](https://github.com/input-output-hk/cardano-node/files/4840138/logs-200627.zip)

**Comment by gufmar** [comment]
As the issue is still present here some more details from a monitoring perspective.

this happens on relay nodes. 
never seen on core nodes behind relays
but it happens independently if using one. 10 or 20 remote peers in the topology

this is the CPU graph from a relay node for last 20 days
![image](https://user-images.githubusercontent.com/13198220/87671422-a31c6380-c771-11ea-8d31-5976e80e0206.png)

zooming into last 24 hours
![image](https://user-images.githubusercontent.com/13198220/87671587-e37be180-c771-11ea-8ab7-778e902a19a5.png)

zooming into 10sec scan detail level to visualize the individual core utilization
![image](https://user-images.githubusercontent.com/13198220/87671688-0908eb00-c772-11ea-92a9-96725cb3463a.png)

this corresponds to the 100-200% CPU utilization shown in liveView 

Compared to a 3rd independent relay, this relay continuously lacks behind the tip by 1-10 blocks

**Comment by Scitz0** [comment]
One of my three relays was also affected by this CPU ramp up until it stopped syncing. 
All relays running 1.15.1 tag connected to Shelley TestNet with only each other(2 core and 3 relays) and IOHK nodes in topologies. This particular relay is running in a Proxmox Linux container (Ubuntu 20.04). First time I have seen this issue. 
![image](https://user-images.githubusercontent.com/15903629/87673097-3d7da680-c774-11ea-919c-d831523b143f.png)

While CPU is ramping up it still manages to stay fairly well in sync(but still lags behind) with the chain until it flatlines at 100% CPU. After this, it just stopped syncing but node stays online. This image shows slot tip compared to calculated slot tip, ie how many slots behind the node are compared to calculated tip based on genesis file. Included two relays, one without CPU ramp-up(red), and the green line represents the one with the issue. Taken with roughly the same timeframe. As can be seen, it stays fairly well in sync compared to the healthy node until an hour before it flatlines, after this, it struggles to keep in sync and then just stops.
![image](https://user-images.githubusercontent.com/15903629/87674369-3192e400-c776-11ea-91bb-926c3f2e8072.png)

Zoomed in view last hour before flatline.
![image](https://user-images.githubusercontent.com/15903629/87675398-9dc21780-c777-11ea-9075-c520366997b7.png)

As the last picture, I want to show how slot sync looked before CPU ramp-up and how well both relays match.
![image](https://user-images.githubusercontent.com/15903629/87674874-e88f5f80-c776-11ea-827a-c8c92b379072.png)

Tried to see if I could find anything in logs that would indicate a cause for the issue but was unable to. Lots of errors related to bad tx in mempool `BadInputsUTxO` and `StakeKeyInRewardsDELEG` but these seem "normal"  and show in all relays.

**Comment by angelstakepool** [comment]
I am observing a similar behavior with one of my relays in STN-2
No idea if this might be related to some particular peers causing this (dragging relay down)

![image](https://user-images.githubusercontent.com/60072039/87686864-04810a00-c753-11ea-9ba7-66085f5b9f95.png)

[red arrow indicates restart]

**Comment by MarcelKlammer** [comment]
Last two days on the STN2, with no real load on the network. Relays desynced, I had to restart them.

![system-load-1 15 1-on-stn2](https://user-images.githubusercontent.com/2163046/87775740-dd940800-c826-11ea-9d1c-f40ff98560a2.jpg)

**Comment by angelstakepool** [comment]
I also continue observing exactly the same behavior for 2 of my relays.  (Red arrow indicate restart)

![image](https://user-images.githubusercontent.com/60072039/87812742-a590c300-c82e-11ea-9a3c-57deb6449d45.png)

**Comment by angelstakepool** [comment]
A new update (this happened today and I let it run for several hours in the stuck state to post results here)

![image](https://user-images.githubusercontent.com/60072039/87859329-6a5fc400-c902-11ea-8d63-701072bc3f3a.png)

**Comment by MarcelKlammer** [comment]
In the last three days, my relays were on STN2. All relays were fine except both of my US relays saw a CPU increase slowly going up, resulting in desync (picture).

I also attached logs for the epoch transition depicted below.

![cpu_load_us](https://user-images.githubusercontent.com/2163046/87902891-06044800-ca5b-11ea-8e9d-77000bc7ff9d.jpg)
[logs.zip](https://github.com/input-output-hk/cardano-node/files/4945671/logs.zip)

**Comment by MarcelKlammer** [comment]
You can see how the CPU load drops for the relay that is farthest behind right after its epoch transition.

Wild guess: Once a relay falls behind 1 or more blocks, it's constantly revalidating the incoming blocks, because it's not on tip. Also revalidating the DB like on bootstrapping from more than 2 nodes. This DB optimization that was slowing down bootstrapping from more than 2 peers keeps it busy at 100% CPU and thus creating a negative feedback loop.

**Comment by MarcelKlammer** [comment]
And after the restart of both US relays, they are always 5 seconds ahead of all other (3 days long-running) relays to receive blocks.

**Comment by vix-io** [comment]
hi @MarcelKlammer are you still seeing this issue?

**Comment by MarcelKlammer** [comment]
No, not at all.
