### ISSUE TITLE
[FR] - DNS TXT record support for pool metadata json

### ISSUE THREAD

**Issue by glitch40** [input-output-hk/cardano-node#1354]
Exernal

Support added for Pool metadata from Domain DNS TXT record 

Instead of defined url support in pool registration that is restricted by character length add the ability for the meta data to be pulled directly from DNS TXT records, Instead of unsecured random urls this would enable pools using 3rd party hosts for websites the ability to update and maintain the pool metadata directly on the domain registered for the pool this would add an additional security layer to verify the ownership of the domain and the meta data for pool registration. 

Example anonaf.com 

dig -t txt anonaf.com 

;; ANSWER SECTION:
anonaf.com.             3600    IN      TXT     "{ name: TestPool, description: The pool that tests all the pools, ticker: TEST, homepage: https://teststakepool.com }"

Alternatives would be self hosting meta data on one of the relays. 

Currently hosting sites like Wix or other 3rd party sites have extremely long urls that do not work with the current system of hosting  (64 character limit) the json on a url requiring another work around of a url shortener to resolve this issue or running a web server from one of the relays to host the json.  The url shortners  or third party file upload sites being used to host the metadata could expire in the future leading to even more issues in the future when the meta data can no longer be found where as the DNS TXT record will always be in the same place so long as the domain is registered.

**Comment by gacallea** [comment]
+1 , this would be awesome and less prone to spoofs.

**Comment by moomanchoo** [comment]
+1

**Comment by vix-io** [comment]
Please put this as a suggestion in the CIP: https://github.com/cardano-foundation/CIPs/pull/15

**Comment by glitch40** [comment]
> Please put this as a suggestion in the CIP: [cardano-foundation/CIPs#15](https://github.com/cardano-foundation/CIPs/pull/15)

Hello not sure why this was closed. This is about securely hosting the metadata as an alternative to the current solution  and providing a proof of ownership to the pool  tied to domain not including metadata or extended metadata structure per the CIP referenced.

**Comment by rdlrt** [comment]
@vix-io - I have to agree, Please do not rush through closing issues. The referred CIP is quite different and talks about content of linked JSON - not pulling it from DNS TXT sources

**Comment by dcoutts** [comment]
The point is, you may find that CIP is an adequate solution to the problem, or if not you can either advocate for an alternative mechanism within that CIP, or craft a wholly new CIP.

Either way, the CIP process is going to be the better avenue for this kind of feature request & design review.
