### ISSUE TITLE
[BUG] - Fresh build of 1.14.1 causes Could not resolve dependencies exception

### ISSUE THREAD

**Issue by sionsmith** [input-output-hk/cardano-node#1355]
**Internal/Exernal**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Summary**
A clean install of 1.14.1 causes Could not resolve dependencies exception

**Steps to reproduce**
1. On a branch new AWS Amazon Linux 2: git clone https://github.com/input-output-hk/cardano-node.git
2. git checkout tags/1.14.1
3. cabal install cardano-node cardano-cli --installdir="$HOME/.local/bin"

**Expected behavior**
A fresh build with no errors.

**System info (please complete the following information):**
- OS: Amazon Linux 2
- Version  ami-032598fcc7e9d1c7a
- Node version: 1.14.1

**Screenshots and attachments**
Exception:
```
[root@ip-10-20-1-115 cardano-node]# cabal install cardano-node cardano-cli --installdir="$HOME/.local/bin"
cabal: Could not resolve dependencies:
[__0] next goal: cardano-crypto-class (user goal)
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
[__0] fail (backjumping, conflict set: cardano-crypto-class)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class
```

**Additional context**

**Comment by matiwinnetou** [comment]
Isn't something which is solved by installing additional library, which they mention? Quote:

```
Dependencies:
libsodum
libsodium-dev
For ease of use create a cabal.project.local at the toplevel with:

package cardano-crypto-praos
  flags: -external-libsodium-vrf
There are two choices for building cardano-crypto-praos, selected via a cabal flag external-libsodium-vrf:

+external-libsodium-vrf Which requires a special fork of libsodium with the VRF code to be installed on the system
-external-libsodium-vrf Which uses a bundled version of the VRF C code and uses the vanilla system libsodium The second option is currently only suitable for development -- but not deployment -- because it uses the libsodium C code in an unsupported configuration
```

**Comment by kevinhammond** [comment]
Yes, I found that installing libsodium-dev at the system level resolved this on Ubuntu (try snap on AWS)

**Comment by sionsmith** [comment]
Ok cool, thanks fo the update. Took me a while to collect all the information needed to get the build to succeed. I have updated the documentation for Amazon Linux and created a PR: https://github.com/input-output-hk/cardano-tutorials/pull/221

**Comment by ianoble** [comment]
@sionsmith Even after following the changes you made in the docs, it's still not letting me install v1.14.x. The cardano-crypto-class dependency still exists.

**Comment by banescusebi** [comment]
> @sionsmith Even after following the changes you made in the docs, it's still not letting me install v1.14.x. The cardano-crypto-class dependency still exists.

Same here. I still get the error on AWS after following the tutorial PR: input-output-hk/cardano-tutorials#221

The problem is that when running `sudo yum install libsodium-devel`, I get the error:
```
No package libsodium-dev available.
```

Needed to `libsodium`:
```
git clone https://github.com/input-output-hk/libsodium
cd libsodium
git checkout 66f017f1
./autogen.sh
./configure
make
sudo make install

export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```

Afterwards `cabal install cardano-node cardano-cli` worked

**Comment by ianoble** [comment]
Well that sort of worked. I got another error though:

<command line>: can't load .so/.DLL for: /home/ec2-user/cardano-node/dist-newstyle
/build/x86_64-linux/ghc-8.6.5/cardano-crypto-class-2.0.0/build/libHScardano-crypto
-class-2.0.0-inplace-ghc8.6.5.so (libsodium.so.23: cannot open shared object file:
 No such file or directory)

**Comment by erikd** [comment]
@ianoble Did you `apt install libsodium libsodium-dev` ?

**Comment by sionsmith** [comment]
Hi @ianoble 

As things as changes are still happening to the build / release process its becoming harder and harder to get up to date build instructions. I am using Packer and Ansibe to build and configure my AMI. I have pushed the role here: 
https://github.com/osodevops/ansible-role-cardano-node

Also found on the Ansible Galaxy:
https://galaxy.ansible.com/sionsmith/cardano_node

**Comment by erikd** [comment]
The problem is that this code is still in a state of heavy development and build instructions that work today can be invalidated tomorrow.

**Comment by binaryst4r** [comment]
> > @sionsmith Even after following the changes you made in the docs, it's still not letting me install v1.14.x. The cardano-crypto-class dependency still exists.
> 
> Same here. I still get the error on AWS after following the tutorial PR: [input-output-hk/cardano-tutorials#221](https://github.com/input-output-hk/cardano-tutorials/pull/221)
> 
> The problem is that when running `sudo yum install libsodium-devel`, I get the error:
> 
> ```
> No package libsodium-dev available.
> ```
> 
> Needed to install `libsodium` like so:
> 
> ```
> git clone https://github.com/input-output-hk/libsodium
> cd libsodium
> git checkout 66f017f1
> ./autogen.sh
> ./configure
> make
> sudo make install
> 
> export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
> ```
> 
> Afterwards `cabal install cardano-node cardano-cli` worked

You are a hero and a legend.

**Comment by RemyNtshaykolo** [comment]
> > @sionsmith Even after following the changes you made in the docs, it's still not letting me install v1.14.x. The cardano-crypto-class dependency still exists.
> 
> Same here. I still get the error on AWS after following the tutorial PR: [input-output-hk/cardano-tutorials#221](https://github.com/input-output-hk/cardano-tutorials/pull/221)
> 
> The problem is that when running `sudo yum install libsodium-devel`, I get the error:
> 
> ```
> No package libsodium-dev available.
> ```
> 
> Needed to install `libsodium` like so:
> 
> ```
> git clone https://github.com/input-output-hk/libsodium
> cd libsodium
> git checkout 66f017f1
> ./autogen.sh
> ./configure
> make
> sudo make install
> 
> export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
> ```
> 
> Afterwards `cabal install cardano-node cardano-cli` worked

Thank you
