### ISSUE TITLE
[BUG] - Command Line Argument Help --single-host-pool-relay

### ISSUE THREAD

**Issue by Crypto2099** [input-output-hk/cardano-node#1358]
*External*

**Summary**
In the help text for the cardano-cli shelley stake-pool registration-certificate argument it lists --pool-relay-port coming before --single-host-pool-relay or --multi-host-pool-relay. However, to get the command to work, when using --single-host-pool-relay you must specify the port *after* the --single-host-pool-relay command.

**Steps to reproduce**
1. Run cardano-cli shelley stake-pool registration-certificate to see cli help text
2. Run the command as specified with --pool-relay-port XXXX followed by --single-host-pool-relay, the cli should error requesting either an ipv4 or ipv6 argument.
3. Run the command with --single-host-pool-relay followed by --pool-relay-port XXXX and the command works as expected.

**Expected behavior**
Change CLI documentation to provide correct argument order.

**System info (please complete the following information):**
- OS: cardano-cli
- Node version 1.14.x

**Comment by kevinhammond** [comment]
We need to change the documentation

**Comment by rphair** [comment]
FYI we are hoping on the user forum to get far greater documentation clarity on using the options for this command.  We are relying on assumptions and trial & error testing at this point, e.g. https://forum.cardano.org/t/question-on-pool-registration-certificate-with-multiple-relay-node/38129

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
