### ISSUE TITLE
[BUG] - Node block divergence incident 2020-06-29 - Mempool Txs

### ISSUE THREAD

**Issue by sevanspowell** [input-output-hk/cardano-node#1359]
**Internal**

**Summary**
At about 12:41 UTC on the 29th of July 2020, the devops team was alerted to node block divergence on the shelley testnet. These alerts continued for about 2 hours until the affected nodes were all restarted.

The start of these alerts corresponds to a large spike in Mempool Txs (>150 on the e-a-4 node) (see https://monitoring.shelley-testnet.dev.cardano.org/grafana/d/Oe0reiHef/cardano-application-metrics-v2?panelId=51&fullscreen&orgId=1&from=1593389429249&to=1593397668853). It is suspected that this is related because the Mempool Txs occurred on node e-a-4, which was also the first node to alert about block divergence.

I've attached the logs from about 12:00 UTC onwards on the e-a-4 node in the JIRA ticket linked below

**Screenshots and attachments**
https://jira.iohk.io/browse/CAD-1312

**Comment by craigem** [comment]
We had another single incident today on e-c-1.

Comments, logs, links and images added to [CAD-1312](https://jira.iohk.io/browse/CAD-1312).

**Comment by craigem** [comment]
We had another 2 incidents today on first on `e-c-2` and later on `e-d-23`.

Comments, logs, links and images added to [CAD-1312](https://jira.iohk.io/browse/CAD-1312).

**Comment by craigem** [comment]
`e-c-1` had a repeat of this issue today.

Comments, logs, links and images added to [CAD-1312](https://jira.iohk.io/browse/CAD-1312).

**Comment by craigem** [comment]
`rel-e-11` on `mainnet` had a repeat of this issue today.

Comments, logs, links and images added to [CAD-1312](https://jira.iohk.io/browse/CAD-1312).

**Comment by craigem** [comment]
`e-a-12` and `e-b-1` on `mainnet` had a repeat of this issue today.

Comments, logs, links and images added to [CAD-1312](https://jira.iohk.io/browse/CAD-1312).

**Comment by craigem** [comment]
`rel-e-24` and `e-d-13` on `mainnet` had a repeat of this issue today.

Comments, logs, links and images added to [CAD-1312](https://jira.iohk.io/browse/CAD-1312).

**Comment by sevanspowell** [comment]
`e-b-1` on `mainnet` had a repeat of this issue today.

Comments, logs added to [CAD-1312](https://jira.iohk.io/browse/CAD-1312).

**Comment by Jimbo4350** [comment]
Spoke with @sevanspowell and this can be closed
