### ISSUE TITLE
[FR] - Official support for stakepool logo in meta.json file

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-node#1366]
In some situations would be nice, if operators could add into meta.json file additional (not required) url with pool/company logo (64x64, static, png)

**Comment by mark-stopka** [comment]
64x64 seems rather too small of a resolution in the world of Retina and 4k displays...

**Comment by cardanians** [comment]
> 
> 
> 64x64 seems rather too small of a resolution in the world of Retina and 4k displays...

The goal of the proposal is to have a pool logo and icon for every pool. Not a wallpaper for your mobile.

**Comment by mark-stopka** [comment]
> The goal of the proposal is to have a pool logo and icon for every pool. Not a wallpaper for your mobile.

Get yourself a display with a high DPI resolution and then start talking. It's common knowledge that either real vectors (like SVG) are being used or images are rendered at 2x the showing resolution to look good at high DPI screens.

**Comment by matiwinnetou** [comment]
I agree with @mark-stopka

**Comment by vix-io** [comment]
Please put this as a suggestion in the CIP: https://github.com/cardano-foundation/CIPs/pull/15
