### ISSUE TITLE
[BUG] - The latest release is v1.14.1,not v1.14.0

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-node#1367]
https://github.com/input-output-hk/cardano-node/releases/tag/1.14.1

![屏幕快照 2020-06-30 上午10 17 03](https://user-images.githubusercontent.com/24730006/86075571-dfd23480-baba-11ea-9521-90d8667d1b5f.png)

**Comment by kevinhammond** [comment]
The numbering of release versions is controlled by our release manager: 1.14.1 is just an internal tag.  1.14.2 will be tagged for release this week.
