### ISSUE TITLE
[BUG] - Core connectivity with relays using A records in topology. 

### ISSUE THREAD

**Issue by glitch40** [input-output-hk/cardano-node#1368]
Exernal

Core  block producer loses connectivity to relays then never regains the peers if A record entry is used instead of ipv4 in topology file. The A record being used will eventually after an extended run will lose the peers never to connect to them again until the Core is rebooted. If you use Ip4 addresses directly the Core maintains direct connections to the relays for longer duration. Core will reconnect to ipv4 addresses if relays are cycled as intended but not consistently to the A records if they are in use in the topology. 

**Steps to reproduce**

Load block producer topology file with A name first in topology
Example: 

{
  "Producers": [
    {
      "addr": "relay.domain.com",
      "port": 3333,
      "valency": 2
    },
    {
      "operator": "relay1", 
      "addr": "xxx.xxx.xxx.xxx",
      "port": 3333,
      "valency": 1
    },
    {
      "addr": "xxx.xxx.xxx.xxx",
      "port": 3333,
      "valency": 1
    }

  ]
}

**Expected behavior**
Node should maintain connections to the Relays in peer count and recover if relays are lost or cycled (restarted) it does not. 

**System info (please complete the following information):**
- OS: Ubuntu
- Version 18.04 - 20.04
- Node version 1.14.0

**Additional context**
This was attempted with A records in round-robin valency 2 however the node would not consistently report both relay peers behind the single A record.

**Comment by karknu** [comment]
Please attached logs in the future.
Can you please verify that you're using the correct genesis, https://hydra.iohk.io/build/3246637/download/1/shelley_testnet-genesis.json

**Comment by glitch40** [comment]
> Please attached logs in the future.
> Can you please verify that you're using the correct genesis, https://hydra.iohk.io/build/3246637/download/1/shelley_testnet-genesis.json 
Yes it is the correct genesis.

**Comment by karknu** [comment]
Please attach the logs from your node.

**Comment by glitch40** [comment]
I think it may be related to relays being stressed issue happened again Nodes in live view would no longer respond to shut down and one relay was no longer connected to the core until force killing the cardano-node relays, both would not shut down in live view had to kill the tasks.

Hopefully these are the logs requested. 

https://gofile.io/d/qTvgeC

https://gofile.io/d/f2VjSI

**Comment by vix-io** [comment]
hi @glitch40 can you still reproduce this?
