### ISSUE TITLE
Installation instructions in README in root of cardano-node does not work without understanding of cabal

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-node#1387]
Instructions to build node missing a lot of steps and seems to assume knowledge of cabal unlike https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/000_install.md which makes it easy for people to use. Please update the documentation so it makes it easy for people to build the node.

**Comment by vix-io** [comment]
@dcoutts please have a look when you have a chance

**Comment by kevinhammond** [comment]
I've already tried to update this, but hit a problem with the CI

**Comment by yihuang** [comment]
```
$ cabal build cardano-node
Warning: Requested index-state2020-07-15T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2020-07-14T22:50:55Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: Win32-network-0.1.0.0 (user goal)
[__1] next goal: base (dependency of Win32-network)
[__1] rejecting: base-4.13.0.0/installed-4.13.0.0 (conflict: Win32-network =>
base>=4.5 && <4.13)
[__1] skipping: base-4.14.0.0, base-4.13.0.0 (has the same characteristics
that caused the previous version to fail: excluded by constraint '>=4.5 &&
<4.13' from 'Win32-network')
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: Win32-network, base)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, Win32-network
```

build with cabal directly will fail (cabal 3.2.0.0, ghc 8.8.4).

**Comment by erikd** [comment]
I think this is explained more fully here: https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md

**Comment by mesudip** [comment]
@erikd  Is there any specific reason for installing the `libsodium` and `libsodium-dev` from sources?
I installed it with `apt install libsodium libsodium-dev` and the build is giving me a linker error 
```
nozmcryptozmpraoszm2zi0zi0zm294bf4544e43f919bdc54cf1cecc25c052f6acc9a0e342bf68db580763a0b310_CardanoziCryptoziVRFziPraos_zdwzdcevalVRF_info: error: undefined reference to 'crypto_vrf_proof_to_hash'

```

**Comment by erikd** [comment]
Cardano needs a modified version of libsodium. Those changes have been submitted upstream but may not have been included in a public release yet.

It is possible to use system installed libsodium (I do it this way) but that requires the following two lines in `cabal.project.local` :
```
package cardano-crypto-praos
  flags: -external-libsodium-vrf
```

**Comment by Jimbo4350** [comment]
Closing as we have updated the docs: https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md
