### ISSUE TITLE
[FR] - cardano-cli should accept --socket-path on the cmdline

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1388]
**Exernal**

**Describe the feature you'd like**
Allow `cardano-cli` to accept `--socket-path` on the cmdline similar to `cardano-node`. If not provided, falls back to the environment variable `CARDANO_NODE_SOCKET_PATH`

**Describe alternatives you've considered**
Due to SSH restrictions/limiting of setting environment variables, it becomes not possible to run remote `cardano-cli` commands. This is necessary in automation tools like JorManager (https://bitbucket.org/muamw10/jormanager) that need to send cardano-cli commands to specific nodes on a remote host over an ssh connection.

While it's possible to pre-configure `CARDANO_NODE_SOCKET_PATH` on the remote ssh host, this isn't a good solution if we need to talk to several `cardano-node` instances running on that host. The envvar option for the socket is simply not flexible enough and a commandline option would be better.

**Comment by kevinhammond** [comment]
Thanks, Andrew. Can you work around this in the short term using symbolic links to the socket (so the socket has
a fixed name as far as the CLI is concerned, but this can be linked to different actual sockets on an as-need basis)?

```
rm socket
ln -s /path/to/socket socket
cardano-cli ...

```
This can be done within an `ssh` command

```
ssh remote 'rm socket; ln -s /path/to/socket socket; cardano-cli ..'
```

**Comment by AndrewWestberg** [comment]
I can always work around things, but it's much more difficult to have to tell all my users to have to work around things. I would have to explain to them how to set up the environment variable initially so that it could be repointed by JorManager. This is a difficult ask when what I'm shooting for with the project is a "stakepool for dummies" system.

The work around I'm using right now is having them modify their `/etc/ssh/sshd_config` `AcceptEnv` flag to include `CARDANO_NODE_SOCKET_PATH`. This is also not ideal.

**Comment by erikd** [comment]
@AndrewWestberg Yes I tend to agree that for commands that need it, the socket path should be settable either via the environment variable or via the command line.

**Comment by AndrewWestberg** [comment]
Any updates on this? Having to do this work-around is continuing to trip up JorManager users.

**Comment by AndrewWestberg** [comment]
Updates? I'm still having to have users manually hack on their SSH configurations as described in the prereq's here.

https://bitbucket.org/muamw10/jormanager/src/develop/README.md

**Comment by vix-io** [comment]
We have added this to our backlog.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.

**Comment by AndrewWestberg** [comment]
@vix-io Is this actually in the backlog? I don't have any visibility into this. 

@Jimbo4350 I think this issue is still relevant to remain open until the issue is fixed. Being able to provide node socket path on the command-line instead of environment var is extremely useful.
