### ISSUE TITLE
Staking support in `cardano-cli`

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#139]
We need to support staking-related scenarios in CLI tooling, as per Chapter 4 of https://hydra.iohk.io/build/902246/download/1/delegation_design_spec.pdf

This is part of https://github.com/input-output-hk/cardano-node/issues/30

# The staking scenarios

0. Stake Pool Registration:
   - manipulation of _pool metadata_ and _stake pool registration certificate_.
   - submission to the blockchain
   - status queries
0. Querying of the active stake pools (and of their metadata).
0. Delegation support:
   - _staking key registration_ and _delegation_ certificate manipulation
   - submission
   - querying the delegation status
0. Individual staking, which seems to be a variation of the above procedures.

# Implementation

Continuing with the established trend, `cardano-node` will be acting as a validator and the block chain agent, whereas the `cardano-cli` will deal with forming of the data blobs and generally the UI for the above operations.

The communication between `cardano-node` and `cardano-cli` is expected to be at least partly formulated in terms of generalised transactions, but with extensions, since the extended metadata queries, such as for state of pool/staking key/delegation.

An important parallel development is a sister update system node-to-client protocol, which is expected to share a similar structure (generalised transactions + extended status queries).

# Dependencies

1. We need proper generalised transaction support for transactions beyond just UTxO expenditures.  This is being worked on in https://github.com/input-output-hk/cardano-ledger/pull/623

**Comment by deepfire** [comment]
@Jimbo4350  is working on the implementation.

**Comment by kevinhammond** [comment]
In train for Shelley

**Comment by Jimbo4350** [comment]
Closing as we are currently redefining scope.
