### ISSUE TITLE
[BUG] - cardano-node: thread blocked indefinitely in an MVar operation

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/cardano-node#1392]
**Exernal**

**Summary**
I was updating my `topology.json` and adding new peers (I noticed that I don't receive any transactions into mempool if I use only IOHK relays, not sure if that is the intent...), when I restarted (rather ungracefully by just killing the processes or rather the containers they run in)... now when I start my relay node, I receive following error and can see following in LiveView...

`cardano-node: thread blocked indefinitely in an MVar operation`

![image](https://user-images.githubusercontent.com/18139116/86520842-4c498c80-be49-11ea-8fdd-8b3b18376865.png)
 

**Steps to reproduce**
No clue.

**Expected behavior**

**System info (please complete the following information):**
- OS: CentOS
- Version 8.2
- Node version: 1.14.2

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by mark-stopka** [comment]
I have solved the issues (I deleted the old storage, however I don't think that had an impact) but I noticed a missing comma in this `topology.json`:

```
{
  "Producers": [
    {
      "addr": "relays-new.shelley-testnet.dev.cardano.org",
      "port": 3001,
      "valency": 2
    },
    {
      "addr": "relay2.adanorthpool.com",
      "port": 9011,
      "valency": 1
    },
    {
      "addr": "relay1.digitalfortress.online",
      "port": 3001,
      "valency": 5
    },
    {
      "addr": "relay2.tiliaio.com",
      "port": 7856,
      "valency": 1
    },
    {
      "operator": "ADAfrog",
      "addr": "http://tadpole.adafrog.io",
      "port": 3728,
      "valency": 3
    },
    {
      "operator": "MASTR" #missing , - after adding relay bootstraps fine
      "addr": "relays.masterstake.com",
      "port": 3001,
      "valency": 4
    }
  ]
}
```

I see 2 issues with this:

a) the error message is rather cryptic
b) should the node validate the JSON configuration files at start-up or should that be a part of logic I should implement in my runtime containers, I am fine with either way, just decision and segregation of duties needs to be somewhat "formalized".

**Comment by kevinhammond** [comment]
This looks like an issue with the liveview interface.  We will investigate it.

**Comment by CodiePP** [comment]
apparently the topology could not be parsed which lead to this error.
