### ISSUE TITLE
[FR] - Show in sync status in RTV

### ISSUE THREAD

**Issue by willcbanks** [input-output-hk/cardano-node#1393]
My nodes appear to be working, as the block number is increasing - although really slow. in 24 hours it received only 22495 blocks - still on epoch 22.
The mempool (bytes) is showin nothing - it says '0 max'
here is some of my core node output:

 20s",String "ErrorPolicyTrace",String "127.0.0.1:3002"]                            │  │ Memory usage:                                        200.0 MB  platform:        Linux      │  
[GALAXY:cardano.node.ChainDB:Notice:36] [2020-07-04 11:02:03.77 UTC] Chain extended, new tip: (Point│  │                      0.0 MB / max 0.2 MB                                                   │  
 482520, HashHeader {unHashHeader = f11c8a2eebb5278f1c29e678df8e20419c05634bc8bee8735fe0d9d309260488│  │                                                                uptime:          00:00:20   │  
})                                                                                                  │  │ CPU usage:                                               100%                              │  
[GALAXY:cardano.node.IpSubscription:Error:60] [2020-07-04 11:02:03.79 UTC] [String "Failed to start │  │                             0.0%                               epoch / slot:    22 / 7320  │  
all required subscriptions",String "[127.0.0.1:3001,127.0.0.1:3002]",String "WithIPList Subscription│  │                                                                block number:    22497      │  
Trace",String "LocalAddresses {laIpv4 = Just 0.0.0.0:0, laIpv6 = Just [::]:0, laUnix = Nothing}"]   │  │ Disk R:            14541.4 KB/s   Disk W:           37.2 KB/s  chain density:   5.4 %      │  
[GALAXY:cardano.node.ChainDB:Notice:79] [2020-07-04 11:02:03.83 UTC] before next, messages elided = │  │            3.2 KB/s                        0.6 KB/s                                        │  
1084374859350                                                                                       │  │                                                                blocks minted:   0          │  
[GALAXY:cardano.node.ChainDB:Notice:79] [2020-07-04 11:02:03.83 UTC] Chain extended, new tip: (Point│  │ Network In:           49.4 KB/s   Network Out:      94.5 KB/s  slots lead:      0          │  
 482520, HashHeader {unHashHeader = f11c8a2eebb5278f1c29e678df8e20419c05634bc8bee8735fe0d9d309260488│  │            0.7 KB/s                        3.3 KB/s            slots missed:    0          │  
})                                                                                                  │  │                                                                cannot lead:     0          │  
[GALAXY:cardano.node.IpSubscription:Info:60] [2020-07-04 11:02:04.79 UTC] [String "Restarting Subscr│  │                                                                forks created:   0          │  
iption after 1.052591691s desired valency 2 current valency 1",String "[127.0.0.1:3001,127.0.0.1:300│  │                                                                                            │  
2]",String "WithIPList SubscriptionTrace",String "LocalAddresses {laIpv4 = Just 0.0.0.0:0, laIpv6 = │  │                                                                                            │  
Just [::]:0, laUnix = Nothing}"]                       

                                                                  │  │                                                                uptime:          00:00:29   │  
[GALAXY:cardano.node.IpSubscription:Info:60] [2020-07-04 11:02:13.74 UTC] [String "Trying to connect│  │ CPU usage:                                               100%                              │  
 to 127.0.0.1:3001",String "[127.0.0.1:3001,127.0.0.1:3002]",String "WithIPList SubscriptionTrace",S│  │                             1.0%                               epoch / slot:    22 / 7320  │  
tring "LocalAddresses {laIpv4 = Just 0.0.0.0:0, laIpv6 = Just [::]:0, laUnix = Nothing}"]           │  │                                                                block number:    22497      │  
[GALAXY:cardano.node.IpSubscription:Info:60] [2020-07-04 11:02:13.74 UTC] [String "Skipping peer 127│  │ Disk R:            14541.4 KB/s   Disk W:           37.2 KB/s  chain density:   5.4 %      │  
.0.0.1:3002",String "[127.0.0.1:3001,127.0.0.1:3002]",String "WithIPList SubscriptionTrace",String "│  │            3.2 KB/s                        0.6 KB/s                                        │  
LocalAddresses {laIpv4 = Just 0.0.0.0:0, laIpv6 = Just [::]:0, laUnix = Nothing}"]                  │  │                                                                blocks minted:   0          │  
[GALAXY:cardano.node.IpSubscription:Error:60] [2020-07-04 11:02:13.74 UTC] [String "Failed to start │  │ Network In:           49.4 KB/s   Network Out:      94.5 KB/s  slots lead:      0          │  
all required subscriptions",String "[127.0.0.1:3001,127.0.0.1:3002]",String "WithIPList Subscription│  │            0.7 KB/s                        4.3 KB/s            slots missed:    0          │  
Trace",String "LocalAddresses {laIpv4 = Just 0.0.0.0:0, laIpv6 = Just [::]:0, laUnix = Nothing}"]   │  │                                                                cannot lead:     0          │  
[GALAXY:cardano.node.IpSubscription:Info:60] [2020-07-04 11:02:14.74 UTC] [String "Restarting Subscr│  │                                                                forks created:   0          │  
iption after 1.001346688s desired valency 2 current valency 1",String "[127.0.0.1:3001,127.0.0.1:300│  │                                                                                            │  
2]",String "WithIPList SubscriptionTrace",String "LocalAddresses {laIpv4 = Just 0.0.0.0:0, laIpv6 = │  │                                                                                            │  
Just [::]:0, laUnix = Nothing}"]           

[GALAXY:cardano.node.BlockFetchDecision:Info:46] [2020-07-04 11:05:08.24 UTC] [String "PeersFetch",A│  │                                 Reqs Blocks   Bytes  platform:        Linux                │  
rray [Object (fromList [("peer",String "ConnectionId {localAddress = 127.0.0.1:36239, remoteAddress │  │                                                                                            │  
= 127.0.0.1:3001}"),("kind",String "FetchDecision declined"),("declined",String "FetchDeclineChainNo│  │ 127.0.0.1       ready      ???    0      0       0   uptime:          00:03:37             │  
tPlausible")]),Object (fromList [("length",String "1"),("peer",String "ConnectionId {localAddress = │  │ 18.156.150.209  ready    482720    0      0       0                                        │  
127.0.0.1:35159, remoteAddress = 127.0.0.1:3002}"),("kind",String "FetchDecision results")])]]      │  │ 52.14.223.144   ready    482707    0      0       0  epoch / slot:    22 / 7520            │  
[GALAXY:cardano.node.ChainDB:Notice:36] [2020-07-04 11:05:08.25 UTC] Chain extended, new tip: (Point│  │ 127.0.0.1       ready    482681    0      0       0  block number:    22506                │  
 482707, HashHeader {unHashHeader = d57c9e80f7278cb3dddfd26c440ceb05972bf8e765904221eb81625aeb4c16a3│  │                                                      chain density:   5.3 %                │  
})

**Comment by erikd** [comment]
@willcbanks 18 hours ago you reported a slow down at epoch 22. SThe Shelley testnet is now at epoch 25, and the 6 hour epochs (Shelley testnet specific) 18 hours ago we would have been at epoch 22, so your node we following the tip of the chain an getting blocks as quickly as they were being produced.

**Comment by mrBliss** [comment]
This is not the first time somebody was confused by slow sync speeds because their node was already up-to-date. Maybe the LiveView could somehow indicate that the node is fully synced? cc: @CodiePP

**Comment by kevinhammond** [comment]
As noted, the node is behaving as it should, but liveview is not showing that in a clear way.  For end-users, Daedalus should report sync status properly.  This is really a matter for the liveview monitoring system.

**Comment by denisshevchenko** [comment]
Since `LiveView` is officially deprecated and will be removed from the node very soon, I'm closing this issue. Please check [RTView](https://github.com/input-output-hk/cardano-rt-view/), our new tool for real-time watching for Cardano nodes. You can open an issue [here](https://github.com/input-output-hk/cardano-rt-view/issues).
