### ISSUE TITLE
Shelly testnet block sync suddenly slows down at epoch 22

### ISSUE THREAD

**Issue by willcbanks** [input-output-hk/cardano-node#1394]
any idea what could cause that?
I have reproduced the problem 5 or 6 times. 
Every time the node starts downloading blocks very fast
then at epoch 22 it suddenly slows down.

**Comment by rdlrt** [comment]
@willcbanks sounds like you're confusing somethinf. If you're using STN network we're in epoch 25 and when you raised the issue we'd have been in epoch 22.
So you see blocks as they're made :)

**Comment by kevinhammond** [comment]
From what is said, this is normal behaviour.  Historic blocks will be synced quickly, then new blocks will be recorded as they are created in real time.  When you start the node having run it before, it will use its local database of historic blocks before attaching to the network to obtain the newly created blocks.
