### ISSUE TITLE
[FR] - Store last epoch reward distribution in local state

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/cardano-node#1395]
**External**

**Describe the feature you'd like**
Storing the rewards distribution of the previous epoch in the local state which can be queried using the local state query protocol. Currently, the local state stores the total accumulated rewards for the stake keys. To be able to query previous epoch rewards will be useful for tools and explorers.

**Describe alternatives you've considered**
Storing accumulated rewards every epoch and taking the difference. But this method does not work as the withdrawals reduce the accumulated rewards.

**Additional context / screenshots**
N/A

**Comment by JaredCorduan** [comment]
I think that what would also help @ashisherc would be the ability to see the `ru :: RewardUpdate` from the `NewEpochState` (in figure 57 of the spec).

**Comment by vix-io** [comment]
We have added this to our backlog.

**Comment by ashisherc** [comment]
@Jimbo4350  @vix-io can you please provide a reference PR or commit that moved this card to DONE on the CLI Revision board

**Comment by erikd** [comment]
There are so many problems with this.

* The information @ashisherc wants from the node is only transitory
* Its transitory and after it is gone there is no way to recreate it.
* This information is already available and easily accessible from a db-sync instance
* @ashisherc is the only use case (ie adascan.io which AIUI sits on top of a custom built node written in nodejs) where this information is not easier to get from db-sync.

The obvious and easy answer is to get this information for `db-sync`.

Sorry, i can't currently see how getting this information for you is a good use of developer resources.
