### ISSUE TITLE
Print fee integer value rather than Lovelace value in calculate-min-fee command

### ISSUE THREAD

**Issue by intricate** [input-output-hk/cardano-node#1401]
As of right now, the output for the `shelley transaction calculate-min-fee` command looks something like this:

```
Lovelace 2594002
```

when we'd rather just print the integer value:

```
2594002
```

**Comment by erikd** [comment]
Maybe it should say `2594002 Lovelace` instead.

**Comment by kevinhammond** [comment]
Is there a problem with running the output through e.g. awk?

**Comment by erikd** [comment]
Yes, the problem is that most people do not know `awk`.
