### ISSUE TITLE
[BUG] - cardano-cli misses to show some utxo transactions

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/cardano-node#1421]
**External**

**Summary**
Some transactions I can see from Daedalus are not displayed using cardano-cli command.
I created a new wallet in Daedalus and I transferred some ada twice using cardano-cli. The first transaction for an amount of 1,000 ada and the second one for 1,000,000 ada.
From Daedalus I can see both of them:
tx id: 0ef30491368e9a08e2aaf5130393687b56daf58c7dc440ed0ab5aaee3cd5db52 for the one of 1,000 ada
tx id: 7ee23af59b3cdece2f6b0dda0c9bf29ff853c80ff03f934e662c47f42af7a436 for the one of 1M ada.

When I inquiry the address through cardano-cli I see only the latest one:
cardano-cli shelley query utxo --address 0055d9d2d0470227be40f6ace0686f35f37a8f2fe63023bee318f1a4fc920f36e134a790ce3202f6e18b3e753eb250c8340421dd2bed8e4c12 --testnet-magic 42

                           TxHash                                 TxIx        Lovelace  
---------------------------------------------------------------------------------------- 
7ee23af59b3cdece2f6b0dda0c9bf29ff853c80ff03f934e662c47f42af7a436     0     1000000000000

I noticed the same behavior in cardano-graphql using the preinstalled view utxo_view filtering by the address value. Even if both transactions are present in table tx with tx_id 1536394 and 1536275 the view displays only the first one (same behavior of cardano-cli).

**Expected behavior**
Both transactions should be displayed

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- cardano-node 1.4.2
- cardano-db-sync 2.1.0
- cardano-graphql 1.0.0-rc14

**Comment by kevinhammond** [comment]
We will investigate this

**Comment by kevinhammond** [comment]
Note that the CLI UTxO command gives the current UTxO rather than the history.   What is being shown is consistent with one of the txs output being unspent, and the other already spent.  So we believe there is no problem here, in fact, and the information is being reported correctly.
