### ISSUE TITLE
[FR] - hot swap kes keys

### ISSUE THREAD

**Issue by zenithpool** [input-output-hk/cardano-node#1428]
**External**

**Describe the feature you'd like**
Instead of restarting the block producing node to replace the kes keys. It should be able to detect that the file has changed and updated its kes keys value based on the file update. This way there is no downtime in the time that the node server restarts.

**Comment by SViksha** [comment]
Also instead of loading 3 files for BP node combine all info in one cert file and parse the required data  from that file, this way we don't have to handle three different files. every time kes changes the we need new cert  so what is the point having to load 3 files kes.skey, vrf.skey and cert.

**Comment by zenithpool** [comment]
This is a duplicate of https://github.com/input-output-hk/cardano-node/issues/1044. Closing
