### ISSUE TITLE
[FR] - Validate CBOR TX Metadata in the CLI

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#1432]
**Internal**
Currently CLI *cardano-cli shelley transaction build-raw* is not validating limit on the size of strings in CBOR metadata files.

**Example - JSON with string longer than 64 bytes - correct behavior**
```bash
cardano-cli shelley transaction build-raw \
--tx-in 1a3f2a54067655fe9b7b4f116f4434f770d1f08b93f78a12d99712166bbd2caa#0 \
--tx-out $(cat ../keys/2/payment2.addr)+10000000000 \
--tx-out $(cat ../example/addresses/user1.addr)+90000000000 \
--ttl 267500 \
--fee 0 \
--metadata-json-file metadata.json \
--metadata-json-file metadata2_too_long_string.json \
--metadata-cbor-file metadata3.cbor \
--metadata-cbor-file metadata4.cbor \
--out-file tx001.raw
```

> Error reading metadata at: "metadata.json" Error: JSON string is longer than 64 bytes

**Example - CBOR with string longer than 64 bytes - no validation**

```bash
cardano-cli shelley transaction build-raw \
--tx-in 1a3f2a54067655fe9b7b4f116f4434f770d1f08b93f78a12d99712166bbd2caa#0 \
--tx-out $(cat ../keys/2/payment2.addr)+10000000000 \
--tx-out $(cat ../example/addresses/user1.addr)+90000000000 \
--ttl 267500 \
--fee 0 \
--metadata-json-file metadata.json \
--metadata-json-file metadata2.json \
--metadata-cbor-file metadata3.cbor \
--metadata-cbor-file metadata4_too_long_string.cbor \
--out-file tx001.raw
```
> No CBOR Error informing that string is longer than 64 bytes

The error will appear during TX submission instead:
```bash
cardano-cli shelley transaction submit --tx-file tx001.signed --testnet-magic 42
```
>Error while submitting tx: Failed to submit Shelley transaction: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (MaxTxSizeUTxO 59630 16384)))]

**Describe the feature you'd like**
Add CBOR TX Metadata validation

**Describe alternatives you've considered**
N/A

**Additional context / screenshots**
Related to https://github.com/input-output-hk/cardano-node/pull/1406

**Comment by MarcelKlammer** [comment]
Where can I find the tx metadata scheme?

**Comment by ArturWieczorek** [comment]
@MarcelKlammer - https://hydra.iohk.io/build/3329433/download/1/delegation_design_spec.pdf - **E** Transaction Metadata, **page 53**  (repo: https://github.com/input-output-hk/cardano-ledger-specs)

**Comment by MarcelKlammer** [comment]
@ArturWieczorek Thank you. What would an example json look like then? I tried some things, but got errors every time.

**Comment by ArturWieczorek** [comment]
@MarcelKlammer  

Example:
```json
{
   "1": {
           "Name": "TX Metadata Tests",
           "Project": "Cardano-Node"
      },
   "2": {
          "ComplexValue": {
              "Nested": "True"
          }
      },
   "3": [{"CI":"Buildkite"}, {"Language":"Haskell"}]
}
```

**Comment by MarcelKlammer** [comment]
@ArturWieczorek Very helpful, thank you.
