### ISSUE TITLE
[FR] - Add print-genesis-hash CLI command for shelley

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#1434]
**Internal**

**Describe the feature you'd like**

Add `cardano-cli shelley print-genesis-hash` as `print-genesis-hash` CLI command currently exists only for **byron** and not **shelley**:

```bash
Byron specific commands
  byron                    Byron node operation commands
  genesis                  Create genesis.
  print-genesis-hash       Compute hash of a genesis file.
```

```bash
cardano-cli print-genesis-hash
Usage: cardano-cli print-genesis-hash --genesis-json FILEPATH
  Compute hash of a genesis file.

Available options:
  --genesis-json FILEPATH  Genesis JSON file.
  -h,--help                Show this help text
```

**Describe alternatives you've considered**

If **genesis-hash** is not going to be needed by any configuration files and etc. (`cardano-db-sync`, `cardano-node/CLI`) anymore then this FR can be closed. (I thought that if we have such command for **byron** then we should also have it for **shelley** )

**Additional context / screenshots**

I was trying to create config for `cardano-db-sync` to make it work with **shelley** node and `GenesisHash` is required by that config. Currently empty string can be used:

```yaml
GenesisHash: "" 
```
and it will work with `db-sync` - so there are probably 2 options:

1) `GenesisHash` will be required in the future and such command would be needed,
2) `GenesisHash` won't be needed by  `db-sync` and other cardano components - so it can be removed from config files.

**Comment by intricate** [comment]
Addressed by #1514
