### ISSUE TITLE
[BUG] - LiveView CPU utilization over 100%

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/cardano-node#1441]
**Exernal**

**Summary**
**LiveView** shows over 100% CPU utilisation on a multi-core system...

![image](https://user-images.githubusercontent.com/18139116/87230917-4278d980-c3b3-11ea-9b70-103136146beb.png)

**Steps to reproduce**
Happened during bootstrap of 1.15.1....

**Expected behavior**

**System info (please complete the following information):**
- OS: CentOS
- Version: 8
- Node version: 1.15.1

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by kevinhammond** [comment]
This may be normal behaviour.  We expect around 200% CPU utilisation during initial sync.

**Comment by dcoutts** [comment]
> Happened during bootstrap of 1.15.1....

Any more info? During normal sync or once it was already in sync?

**Comment by mark-stopka** [comment]
@kevinhammond I understand it can use multiple cores, what I am reporting is that the bar is not normalised based on the amount of overall CPU capacity available...

@dcoutts it was a bootstrap after container restart, so validation of existing storage first and fetching new blocks later...

**Comment by kevinhammond** [comment]
So I believe we can close this - normal behaviour?  We'll look into improving performance here later, of course.
