### ISSUE TITLE
[BUG] - cardano_node_Forge_metrics missing after hard fork on 1.15.X with Cardano Protocol

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/cardano-node#1448]
**Internal/Exernal**
Internal

**Summary**
The `cardano_node_Forge_metrics.*` metrics seem to be missing on bft nodes in mainnet_candidate cluster post hard fork on 1.15.0 or 1.15.1 (Cardano protocol).  Similar metrics are still seen on shelley-testnet, both on the new respin at 1.15.1 and prior genesis at 1.14.X (TPraos protocol):

Example:
```
# As seen on shelley_testnet (TPraos protocol), but
# not present in mainnet_candidate (Cardano protocol, post hard fork):
# Both clusters have bft nodes at cardano-node 1.15.1, and virtually identical metrics/logging configuration:

$ curl -s $IP:12798/metrics | grep 'cardano_node_Forge_metrics'
cardano_node_Forge_metrics_currentKESPeriod_int 9
cardano_node_Forge_metrics_operationalCertificateExpiryKESPeriod_int 120
cardano_node_Forge_metrics_operationalCertificateStartKESPeriod_int 0
cardano_node_Forge_metrics_remainingKESPeriods_int 111
```

Comparison metrics and logging configurations between mainnet_candidate and shelley_testnet are [here](https://hydra.iohk.io/build/3425018/download/1/mainnet_candidate-config.json) and [here](https://hydra.iohk.io/build/3425018/download/1/shelley_testnet-config.json).

**Comment by kantp** [comment]
Closed as per #1505
