### ISSUE TITLE
Script documentation & Pruning 

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#145]
I think the scripts in `scripts` could be better documented in the `README.md` or maybe a separate `SCRIPTS.md` file. This will also help in removing scripts we no longer need.

**Comment by intricate** [comment]
Should probably be a `README.md` in the `scripts` directory.

**Comment by Jimbo4350** [comment]
`SCRIPTS.md` was created to enhance the documentation of the scripts.
