### ISSUE TITLE
[BUG] - CLI Parser is traversing same option twice

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-node#1451]
**Internal/Exernal**
*External* 

**Summary**

Relevant code [here](https://github.com/input-output-hk/cardano-node/blob/8c72fc00cb75b7e7a2c9423ba50c639f6236c88b/cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs#L1686-L1719)

CLI Parser is currently traversing options from different protocols (shelley|byron|cardano) , but repeating parameters "epoch-slots" and "security-param" twice in output - once for Byron, and once for Cardano.

**Steps to reproduce**
1. Run `cardano-cli shelley query tip`
2. You see output contains same parameters (`--epoch-slots` and `--security-param`) twice - once for `byron-mode` and once for `cardano-mode`.

**Expected behavior**
The parameters should not be repeated for a given command.

**System info (please complete the following information):**
- OS: *all*
- Version *all*
- Node version: 1.15.1

**Comment by kevinhammond** [comment]
Thank you.  We will deal with this as we review the codebase

**Comment by vix-io** [comment]
hi @Jimbo4350 is this resolved already?

**Comment by intricate** [comment]
@vix-io: This isn't resolved yet.

**Comment by rdlrt** [comment]
Still the case on 1.26.0

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
