### ISSUE TITLE
[BUG] - Liveview leaves the terminal in a bad unusable state

### ISSUE THREAD

**Issue by 2072** [input-output-hk/cardano-node#1454]
*External*

**Summary**
When using the Liveview and the node quits with an exception, or simply when pressing `q` since `1.15.1`, the terminal is left unusable afterwards. One as to type `stty sane` in blind mode to get proper functionality again.

Opening and closing an editor such as `vim` or `nano` further fixes the terminal behavior as the cursor is still broken after `stty sane`.

**Steps to reproduce**
1. Run the node in Liveview mode
2. CTRL-C or q
3. press return or try to type anything
  - The terminal doesn't react as expected (commands are executed but typed characters dont appear on screen)

**Expected behavior**
The terminal should be restored to its previous state just like after quitting `vim` or `less` or any other full screen terminal application.

**System info (please complete the following information):**
- OS: Debian
- Version: Buster
- Node version: 1.15.1

**Comment by CodiePP** [comment]
we should probably add such a terminal reset command in the scripts.
`reset` should also do it.

**Comment by erikd** [comment]
Not everybody runs it via a script. This should be in the Haskell executable, maybe via a `bracket` construct.
