### ISSUE TITLE
[FR] - Convert byron delegation/genesis keys -> shelley delegation/genesis keys

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1467]
**Internal**
We need the ability to convert the delegation and genesis keys. For the genesis keys, we need to be able to convert the vkey embedded in the genesis.json for a byron environment. This is needed as we need the genesis vkey to create update proposals and MIR certificates. For the delegation, we need to convert the secret delegation key to the new style, and we need a way to generate the vkey from the delegation skey.

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by disassembler** [comment]
Speaking with @dcoutts the best way to handle getting the genesis vkey is to take bas64 input on command-line and decode that as an xpub.

**Comment by intricate** [comment]
Addressed by https://github.com/input-output-hk/cardano-node/pull/1486
