### ISSUE TITLE
[BUG] - stake address is not correctly displayed under `stake-address-info`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#1470]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
stake address is not correctly displayed under `stake-address-info`

**Steps to reproduce**
1. start a local cluster using 1.15.1
2. create a stake address and 1 stake pool and delegate the stake address using a certificate
3. run the below command

```
# CARDANO_NODE_SOCKET_PATH=example/node-bft1/node.sock \
> cardano-cli shelley query stake-address-info \
> --address stake_test1upkzyajamfjnjwa33ndy50awhwxeds7f0tw9t7qmxrfv7jq4s6ft6 \
> --testnet-magic 42
{
    "àl\"v]Úe9;±�ÚJ?®»��ÃÉzÜUø\u001b0ÒÏH": {
        "delegation": "d74b33f303bcec753a4cef91c502d1087419c6fe7abf7e86c1905b35",
        "rewardAccountBalance": 0
    }
}
```

**Expected behavior**
- "àl\"v]Úe9;±�ÚJ?®»��ÃÉzÜUø\u001b0ÒÏH"= the stake address with no unsupported characters

**System info (please complete the following information):**
- OS:  Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)
- Node version
```
# cardano-node --version
cardano-node 1.15.1 - linux-x86_64 - ghc-8.6
git rev 712a287602797e8fd889fbf73e56a08c3d8b004a

# cardano-cli --version
cardano-cli 1.15.1 - linux-x86_64 - ghc-8.6
git rev 712a287602797e8fd889fbf73e56a08c3d8b004a
```

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/29144964/87531720-cb855e80-c69a-11ea-8429-fcbab97abd7a.png)

**Comment by kevinhammond** [comment]
This looks like a format conversion error, or possibly displaying the wrong string

**Comment by intricate** [comment]
Going to fix this now. Looks like we just made a slight formatting mistake here while migrating things over to our new API in https://github.com/input-output-hk/cardano-node/pull/1416.
