### ISSUE TITLE
[FR] - Removal of margin Fee advertisements in wallets for a Performance based metric to mitigate "Race to the bottom"

### ISSUE THREAD

**Issue by glitch40** [input-output-hk/cardano-node#1494]
External

 I propose the margin"Fee" section is replaced in the wallet with an actual ROS (return on stake) from the 3rd party sites that track this data such as pooltool (or other trusted 3rd party sites) to be aggregated inside the "SMASH" meta servers the same way data is aggregated for pool registration and this removes the "wallet" advertisement option of a low fee in exchange for one of an actual solid statistic based on pool performance. 

The low numbers advertised seem to be the barrier for most delegates they automatically assume the low  margin fee = high reward. This would allow the wallet rankings and pool choices not to be made on false pretense by assumption a low fee relates to a high return but based on actual returns not the low arbitrary numbers advertised in the wallet. This should have a compounding ripple effect that should combat this race to the bottom by removing the focus from the "low" margin numbers to that of the performance rate on the pool. which actively tracks the pools return. 

 The metrics inside the wallet would then consist of Pledge + ROS + Saturation giving a more accurate view of a pools performance. New pools being added to the network could be exempt from the "ROS" penalty in rankings for a entry period until they have produced sufficient rewards to be calculated and ranked appropriately inside the wallet. example:  If $LIFETIME_ASSIGNED = NULL then exclude ROS rankings and base solely on pledge and saturation factors inside wallet. 

I know there is a small chance this can be implemented in time before launch, however in the interim before these changes can be included i suggest the "margin" advertisements be removed from the wallets until the accurate performance from these changes can be included this should help reduce the race to the bottom on the basis of "subjective low margin" at the start and focus more on the pledge and existing rank factors included as the changes are made. 

**Describe alternatives you've considered**
"minpoolcost"

Minpoolcost has now just made this a race to minimum pool cost vs min margin there needs to be a better solution to keep attracting growth to the network to support it for the long term and reduce the focus on these ultra low subjective "margin fees" and pending race to the bottom.

**Comment by kevinhammond** [comment]
I'll pass this on to Philipp and Lars.  Delegator choices should be made on ranking (i.e. long-term network utility), which is dominated by ROS, pledge and saturation (as well as performance).  Margin and cost have some impact on this.  Even a small pledge will raise the relative ranking, allowing greater margin and cost for

**Comment by kantp** [comment]
The way I read this is that you are asking that wallets should rank pools not based on their cost and margin alone, but instead calculate the expected ROS, and rank by that, is that right? 

If so, I have some good news: that is exactly how pools will be ranked. Ranking in Daedalus will be done based on non-myopic utility, which is just the ROS (in a non-short sighted way, i.e., expecting that everyone else makes informed delegation decisions as well). The non-myopic utility is also exposed via the API, so other tools can use it as well.

@glitch40, can you confirm that that is indeed what you are asking for?

**Comment by mark-stopka** [comment]
@kantp I think he is simplu asking for removal from the UI, TBH I am against, as I think delegates should have as much information available, with that said a `?` icon next to "Pool margin:" with `hover` an explanation could not hurt...

**Comment by glitch40** [comment]
> The way I read this is that you are asking that wallets should rank pools not based on their cost and margin alone, but instead calculate the expected ROS, and rank by that, is that right?
> 
> If so, I have some good news: that is exactly how pools will be ranked. Ranking in Daedalus will be done based on non-myopic utility, which is just the ROS (in a non-short sighted way, i.e., expecting that everyone else makes informed delegation decisions as well). The non-myopic utility is also exposed via the API, so other tools can use it as well.
> 
> @glitch40, can you confirm that that is indeed what you are asking for?

Yes and no,

I already knew about the rank calculation this is more about the psychological games being played on display inside the wallets with the margin fee.  

 There is a lot that has been learned from ITN and the assumptions being made on "ROS" for stake holders they are making choices based on the displayed margin fees advertisements in the wallets which are not telling the true story as far as actual "ROS"  performance of a pool for those stake holders. 

The proposal was to not use the wallet as a billboard advertisement of ultra low fees suggesting a higher return but instead to use the actual return calculations displayed so stake holders can base their choice off of the return (performance of a pool) not the suggested "low margin" because they assume the fee equals a higher return when it has very little to do other than a gimmick and easy advertisement in the wallet which leads to games being played of constantly adjusting fees vs pool performance.

**Comment by Crypto2099** [comment]
It seems like basic game theory here... Wal-Mart does not advertise what their profit margin is when you go to buy shampoo. They advertise that they are going to get you the products you need at a price you can afford. I fully support the idea of removing margin and fees from the wallets in lieu of displaying merely ranking and performance metrics to any investor casual enough to base their decision solely on the wallet alone.

If other pools manage to out-advertise, pledge and/or perform me and get the delegation, so be it. However, the percentages/fees that I'm charging to provide a competitive service should NOT be part of the equation for an investor IMO.

**Comment by vix-io** [comment]
@kantp please can you review this, otherwise we can advise to go down the CIP route

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
