### ISSUE TITLE
[BUG] - cardano-cli get-tip outputs strange hash

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/cardano-node#1500]
**Exernal**

**Summary**
When running `cardano-cli get-tip --testnet-magic 42`, **Block hash** output looks strangely encoded, see below:

```
cardano-cli get-tip --testnet-magic 42


Current tip:
Block hash: "\197K\aS\RS\ETB\235\143\189\215\&4\128\211\143\219?\ETBX\NAKjt\218`\169V\159\217\172\SO\SYN\SI\161"<32b>
Slot: 6907
Block number: 6861
```
**Steps to reproduce**
1. Start and sync `cardano-node` 1.16.0
2. Run `cardano-cli get-tip` 1.16.0
3. Observe the provided output

**Expected behavior**
**Block hash** should be short version of a human readable (hexadecimal) hash like it used to be in 1.15.0 and 1.15.1 I believe, I have not found anything in the ChangeLogs of either `cardano-cli` or `cardano-api` that would explain this change.

**System info (please complete the following information):**
- OS: CentOS
- Version 8
- Node version: 1.16.0

**Screenshots and attachments**
- N/A

**Additional context**
- N/A

**Comment by mrBliss** [comment]
I am to blame for this, I fixed it in https://github.com/input-output-hk/cardano-node/commit/3ea540531e28ba998b10c73baa01ccdfbcf2804e (not part of a release yet)

**Comment by mark-stopka** [comment]
Thanks, for those interested in back-porting into 1.16.0, it's easy to cherry-pick the relevant commit...

```
git cherry-pick -n 3ea540531e28ba998b10c73baa01ccdfbcf2804e
```
