### ISSUE TITLE
[BUG] - Node does not check for existence of symlink before trying to unlink it

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/cardano-node#1501]
**Exernal**

**Summary**
When file logging is configured `cardano-node` is trying to remove (unlink) `node-0.log` without checking if it actually exists...

```
cannot remove symlink: log/node-0.log
exception: log/node-0.log: removeLink: does not exist (No such file or directory)
```

Relevant part of config file

```
  "setupScribes": [
    {
      "scFormat": "ScText",
      "scKind": "FileSK",
      "scName": "log/node-0.log",
      "scRotation": null
    }
```

**Steps to reproduce**
Start a node with file logging enabled while not having any log files (and perhaps already initialised storage, haven't tested it with fresh storage)...

**Expected behavior**
`cardano-node` or `iohk-monitoring-framework` will check if respective logging symlink file exists and tries to unlink it only if it exists.

**System info (please complete the following information):**
- OS: CentOS
- Version 8
- Node version: 1.16.0

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**
This can get picked up by anomaly detection IPS/IDS systems with end-point agents in highly secure environments requiring an exception in a global security policy exception registry which is undesirable.

**Comment by denisshevchenko** [comment]
Fixed in https://github.com/input-output-hk/iohk-monitoring-framework/pull/573
