### ISSUE TITLE
[FR] - There is no way to delegate based on pool_id

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#1528]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Describe the feature you'd like**
For the public stake pools, we have only their pool_ids but for the moment we don't have any way of delegation using the pool_id.

**Describe alternatives you've considered**
There aren't any.

**Additional context / screenshots**
There is a CLI command but it is not implemented yet.

```
cardano-cli shelley stake-address delegate \
    --signing-key-file pool_owner_stake.skey \
    --pool-id 2e78fd03436440cd494dc9445d2a1cb7f174de990935029d0939543e \
    --delegation-fee 200000
runStakeAddressCmd: StakeKeyDelegate (PrivKeyFile "pool_owner_stake.skey") (PoolId "2e78fd03436440cd494dc9445d2a1cb7f174de990935029d0939543e") (Lovelace 200000) (NodeAddress {naHostAddress = Nothing, naPort = 0})
```

**Comment by intricate** [comment]
You should be able to create a stake address delegation certificate using the `cardano-cli shelley stake-address delegation-certificate` command. 

This can accept either a `--cold-verification-key-file` or a `--cold-verification-key-hash` (a stake pool ID).

**Comment by dcoutts** [comment]
Yeah, we can do better on the flag names and help description to make this more obvious. We should also make the poolid flag accept the new bech32 rendering for pool ids.

**Comment by dorin100** [comment]
Interesting. I was able to give a pool_id as value for the `--cold-verification-key-hash` argument but my initial expectation was to see the new delegation into the output of `cardano-cli shelley query stake-address-info` right after the next tip (after the certificate was submitted through a tx), but that was not the case. I am waiting for next epochs...

```
cardano-cli shelley stake-address delegation-certificate \
    --stake-verification-key-file pool_owner_stake.vkey \
    --cold-verification-key-hash ece9c1424344714ef2b9294f56b6dfd655e952f65a28cc39b6814ec4 \
    --out-file stake_delegation_pool_id.cert
```

```
cardano-cli shelley query stake-address-info --testnet-magic 3 --address stake_test1uzep3545macvp0mjafnks5s906qx2rct5d2sajp7g4zn6js7hrekl --cardano-mode
{
    "e0b218d2b4df70c0bf72ea676852057e80650f0ba3550ec83e45453d4a": {
        "delegation": "4fbc00ab9baca6f9847b84ad22df1a85c7e4773e427acceb6bc1199c",
        "rewardAccountBalance": 0
    }
}
```

**Comment by dorin100** [comment]
So even after a new epoch, the delegation value of the stake pool is not updated.
