### ISSUE TITLE
Increased memory usage (2X) for cardano-node when connected to MC3

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#1547]
**Internal**

**Summary**
Increased memory usage (2X) for `cardano-node` when connecting to **MC3**.

**System info :**

- Node version:

```bash
cardano-node 1.17.0 - linux-x86_64 - ghc-8.6
git rev 0191ff56d194b6ac074af0d51e67493c14e08ffa
```
- OS:  Linux Mint 19.2

**Steps to reproduce**

I ran node from `CLI` and also started `Deadalus`. 
Process manager show now usage at ~1GiB, for the past few months it never exceeded over 0,5GiB for me when testing `stage` , `mainnet`.
`cardano-wallet-shelley` has 2,7 GiB 

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/2938515/88406265-b9a96700-cdd0-11ea-9de3-6a9506f953e3.png)

At the moment of creating this ticket both `cardano-node` and `Deadalus` are already running for ~6 Hours.

**Expected behavior**

Not sure if this is a bug or expected behavior when switching to `Shelley` ledger so I marked it as **invalid** which has description "This does not seem right" which better suits this situation/ticket.

Needs to be investigated.

**Additional context**
N/A

**Comment by ArturWieczorek** [comment]
CC: @dcoutts @mrBliss

**Comment by alan-mcnicholas** [comment]
Interesting, it is business as usual for me on Windows; are you only seeing this during initial sync?
![image](https://user-images.githubusercontent.com/38462815/88410890-e8264280-cdce-11ea-8f57-b7673f1e7cc1.png)

**Comment by mrBliss** [comment]
After the transition to Shelley, we will temporarily keep both the Byron and Shelley ledger in memory until we are `k` blocks deep in the Shelley era and no longer need to be able to roll back to the Byron era.

According to https://github.com/input-output-hk/ouroboros-network/issues/1404#issuecomment-663498571, we expect the Byron ledger to be roughly 17 MB and the translated Shelley one 22 MB (not accounting for fragmentation and other heap overhead), so it is strange to see it jump from 500 MB to 1 GB.

Also, how long has your node transitioned, more than `k` blocks?

**Comment by ArturWieczorek** [comment]
@alan-mcnicholas Yes, it is increasing during initial sync, once it is synced it does not grow anymore.
@mrBliss This is the last log message from`cardano-cli shelley  query tip --testnet-magic 42` before I shut it down:

```json
{
    "blockNo": 6707,
    "headerHash": "f3098d8cc7338385606f1fa769987f8ab5c6286d0214f75772e4437070b0a609",
    "slotNo": 79640
}

**Comment by ArturWieczorek** [comment]
I used:

`while true; do ps --pid 20367 -o rss | tail -1 ; sleep 1 ; done | tee memusage`

Description of events and ~memory usage when event happened below.

File (truncated last value `1055916` that was repeating ) :  [memusage-mc3-node_1_17_0.txt](https://github.com/input-output-hk/cardano-node/files/4973527/memusage-mc3-node_1_17_0.txt)


1 A Event:
```
2020-07-24 16:44:35.19 UTC] Chain extended, new tip: (Point 204, "3b860c2ddca906f8b451042a16725d986d423b577c8f45742f5753cf0cb13087")
Event: LedgerUpdate (HardForkUpdateInEra Z (WrapLedgerUpdate {unwrapLedgerUpdate = ByronUpdatedProtocolUpdates [ProtocolUpdate {protocolUpdateVersion = 1.0.0, protocolUpdateState = UpdateConfirmed (SlotNo {unSlotNo = 204})}]}))
```
1 B: Memory Usage: 120104 <->123008

2 A Event:
```
[artur-de:cardano.node.ChainDB:Notice:23] [2020-07-24 16:45:38.43 UTC] Chain extended, new tip: (Point 420, "554a7449d9158f9528cf0732602f40e331ac22460e108ea40c6ba4ef813cb534")
Event: LedgerUpdate (HardForkUpdateInEra Z (WrapLedgerUpdate {unwrapLedgerUpdate = ByronUpdatedProtocolUpdates [ProtocolUpdate {protocolUpdateVersion = 1.0.0, protocolUpdateState = UpdateCandidate (SlotNo {unSlotNo = 420})}]}))
```
2 B: Memory Usage: ~ 268264 

3 A Event:
```
[artur-de:cardano.node.ChainDB:Notice:23] [2020-07-24 16:45:38.89 UTC] Chain extended, new tip: (Point 636, "1a68379784a54785f0beafcc182441cfcaa37a4c42ccd72e0b68a2ccffc44135")
Event: LedgerUpdate (HardForkUpdateInEra Z (WrapLedgerUpdate {unwrapLedgerUpdate = ByronUpdatedProtocolUpdates [ProtocolUpdate {protocolUpdateVersion = 1.0.0, protocolUpdateState = UpdateStableCandidate (EpochNo {unEpochNo = 1})}]})
```

3 B: Memory Usage: ~ 351476

4 A Event:

```
[artur-de:cardano.node.ChainDB:Notice:23] [2020-07-24 16:49:10.87 UTC] Chain extended, new tip: (Point 1408, "2c871d1dd8805d8fbd82538e1795b9a47273a69a0d07a5211ad37f9ed7fe2e96")
Event: LedgerUpdate (HardForkUpdateInEra Z (WrapLedgerUpdate {unwrapLedgerUpdate = ByronUpdatedProtocolUpdates [ProtocolUpdate {protocolUpdateVersion = 2.0.0, protocolUpdateState = UpdateStablyConfirmed (fromList [])}]}))
```
4 B: Memory Usage: ~437592

5 A Event:

```
[artur-de:cardano.node.ChainDB:Notice:23] [2020-07-24 16:51:41.01 UTC] Chain extended, new tip: (Point 2628, "c95d3d989518dbdf7e70ed083e156b38e029c44d6cd1cf6240ae1a291be9c4ad")
[memusage-mc3-node_1_17_0.txt](https://github.com/input-output-hk/cardano-node/files/4973521/memusage-mc3-node_1_17_0.txt)


Event: LedgerUpdate (HardForkUpdateInEra Z (WrapLedgerUpdate {unwrapLedgerUpdate = ByronUpdatedProtocolUpdates [ProtocolUpdate {protocolUpdateVersion = 2.0.0, protocolUpdateState = UpdateStableCandidate (EpochNo {unEpochNo = 3})}]}))
Event: LedgerUpdate (HardForkUpdateTransitionConfirmed <EraIndex Byron> <EraIndex Shelley> (EpochNo {unEpochNo = 3}))
```

5 B: Memory Usage around that time : 439404 <-> 457124

6 A Event:
`Event: LedgerUpdate (HardForkUpdateTransitionDone <EraIndex Byron> <EraIndex Shelley> (EpochNo {unEpochNo = 3}))`

6 B: Memory Usage around that time :  561432 <-> 673416

It ended with repeating memory usage: 1055916

**Comment by ArturWieczorek** [comment]
@mrBliss It looks like it went back to ~500 MB after ~ 24 hours: 
- graph:
![Selection_011](https://user-images.githubusercontent.com/2938515/88466555-e1cac000-cecd-11ea-9b03-a156e985070b.png)
- Data:
[memusage_25H.txt](https://github.com/input-output-hk/cardano-node/files/4976535/memusage_25H.txt)

**Comment by vix-io** [comment]
hi @ArturWieczorek can you reproduce this in any current environment?

**Comment by ArturWieczorek** [comment]
Hi @vix-io , this can be closed.
