### ISSUE TITLE
[BUG] - unreal pledge

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-node#1558]
Is possible create pool certificate with (unlimited) pledge and it works. 
Its not tested with reality.

![obrazek](https://user-images.githubusercontent.com/58650764/88452703-2a985f80-ce61-11ea-8cb7-0b89cf65b81c.png)

**Comment by matiwinnetou** [comment]
I noticed the same by making a mistake in pledge amount.

**Comment by matiwinnetou** [comment]
Expectation: pool registration should fail when there is not enough funds to pledge based on what was declared.

**Comment by rdlrt** [comment]
Duplicate - Check [here](https://github.com/input-output-hk/cardano-ledger-specs/pull/1703)

**Comment by matiwinnetou** [comment]
@rdlrt I don't see how they are related but maybe they are.. ok...

**Comment by oneEdoubleD** [comment]
@matiwinnetou 

> This is not a bug. Stake pool operators are free to make a pledge as large as they want, even ridiculous ones that they cannot possibly meet. Even just pledging 51% of the total supply is absurd, as you are making a promise to have enough stake to control the entire system. The ledger does not attempt to make a value judgement on what is and is not reasonable, instead it gives out no rewards to a pool that does not meet the pledge in a given epoch.

@kevinhammond @darko-mijic  

While this isn't a bug in the ledger, it is confusing from a UX perspective. Could we validate this at the IO layer (Daedalus) with either an error or a warning? For example, if `pledge > available ada of pool` we could say if the pledge isn't met you'll not be rewarded, and if `pledge > global ada` an error saying that it isn't a valid pledge? Or, if this isn't a good idea, just general info about this could be helpful to explain why.

**Comment by dcoutts** [comment]
Daedalus (and the wallet backend API) report pools that do not currently meet their pledge with a zero ranking score. This is sufficient for displaying pools that are not likely to meet their pledge.

There is no need to enforce anything at the ledger level. The ledger already gives pools zero rewards that do not actually meet their pledge.
