### ISSUE TITLE
[BUG] - Incorrect number of elided messages

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/cardano-node#1585]
**Internal**

**Summary**
Strange values for `messages elided`, when syncing with mainnet, I can see the following messages in my log:

```
[desktop:cardano.node.ChainDB:Notice:35] [2020-07-28 08:07:18.07 UTC] Chain extended, new tip: (Point 4483035, "e9bfa9c526801e729a7507fcddc50636aa3ee32157221c583a751547d831fb45")    
[desktop:cardano.node.ChainDB:Info:35] [2020-07-28 08:07:19.14 UTC] before next, messages elided = 474878937726615                                                                    [desktop:cardano.node.ChainDB:Info:35] [2020-07-28 08:07:19.14 UTC] Valid candidate (Point 4483574, "c2df25e41eb7de23b702e2affc7c2d171b53dd9dc824b26a48890f365ab89f3d")
...
desktop:cardano.node.ChainDB:Notice:35] [2020-07-28 08:07:20.39 UTC] Chain extended, new tip: (Point 4484168, "b2c301ea54040e8fec49c03ddea85e844daf7c0de0d46a76e8a010cfe480b523")    
[desktop:cardano.node.ChainDB:Info:39] [2020-07-28 08:07:20.74 UTC] before next, messages elided = 474881255781247                                                                    [desktop:cardano.node.ChainDB:Info:39] [2020-07-28 08:07:20.74 UTC] Valid candidate (Point 4484235, "e1998bb56253fd785d28eeaa201dd1adb9d7a935ca402220aab0c7162e31d3c4") 
```

And on startup:
```
[desktop:cardano.node.ChainDB:Info:5] [2020-07-28 14:00:06.83 UTC] Replaying ledger from snapshot DiskSnapshot 22 at (Point 4481813, "86dc23b4492ffd372bba16f136a47c97e28c3dc7d074ed0b
2929cadd008463d9")
[desktop:cardano.node.ChainDB:Info:5] [2020-07-28 14:00:06.92 UTC] Replayed block: slot SlotNo {unSlotNo = 4481814} of At (SlotNo {unSlotNo = 4483901})
[desktop:cardano.node.ChainDB:Info:5] [2020-07-28 14:00:07.17 UTC] block replay progress (%) = 100.0
[desktop:cardano.node.ChainDB:Info:5] [2020-07-28 14:00:07.40 UTC] block replay progress (%) = 100.0
[desktop:cardano.node.ChainDB:Info:5] [2020-07-28 14:00:07.42 UTC] before next, messages elided = 4481814
[desktop:cardano.node.ChainDB:Info:5] [2020-07-28 14:00:07.42 UTC] Replayed block: slot SlotNo {unSlotNo = 4483901} of At (SlotNo {unSlotNo = 4483901})
```

I would be very surprised if, respectively, 474878937726615, 474881255781247, and 4481814 messages were actually elided. It looks totally wrong. In the last example, `4481814`, it is very suspicious that it matches `Replayed block: slot SlotNo {unSlotNo = 4481814}`. I traced it back to https://github.com/input-output-hk/cardano-node/blob/36ad7b90bfbde8afd41b68ed9b928df3fcab0dbc/cardano-node/src/Cardano/Tracing/Tracers.hs#L230
`startslot` should actually be `count`. (BTW, who calls one method `isEquivalent`, but others `doelide` and `conteliding`? That's quite inconsistent.)

Similarly, for the other two: https://github.com/input-output-hk/cardano-node/blob/36ad7b90bfbde8afd41b68ed9b928df3fcab0dbc/cardano-node/src/Cardano/Tracing/Tracers.hs#L208

the `count` is confused with/abused as `oldt`.

**Steps to reproduce**
Use the mainnet configs from https://hydra.iohk.io/build/3627488/download/1/index.html and sync your node. For example:
```
cabal run cardano-node:exe:cardano-node -- run +RTS -N2 -RTS --config mainnet-config.json --socket-path mainnet.sock --topology mainnet-topology.json --database-path db_mainnet --port 3001
```

**Expected behavior**
Show the actual number of messages that was elided.

**System info (please complete the following information):**
- Node version 1.18.0

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
