### ISSUE TITLE
[FR] - Override entrypoint arguments

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-node#1597]
**External**

![image](https://user-images.githubusercontent.com/22454337/88814380-49c52300-d1ba-11ea-9419-8011ebeba1aa.png)

Is it possible to override --topology from docker compose? I tried passing the topology into `command`, but it was ignored.

Thanks :)

**Comment by chrissound** [comment]
Which docker image / docker configuration are you using? The one from https://hub.docker.com/r/inputoutput/cardano-node?

**Comment by xdzurman** [comment]
@chrissound Yes.

**Comment by chrissound** [comment]
Well you can just pass a command:
```
docker run inputoutput/cardano-node:latest run --help
docker run inputoutput/cardano-node:latest run --topology example
```

**Comment by kevinhammond** [comment]
I think we can close this

**Comment by xdzurman** [comment]
@chrissound I asked about docker compose, what can be done there? Not by docker run.

**Comment by kiahmed** [comment]
> Well you can just pass a command:
> 
> ```
> docker run inputoutput/cardano-node:latest run --help
> docker run inputoutput/cardano-node:latest run --topology example
> ```



> Well you can just pass a command:
> 
> ```
> docker run inputoutput/cardano-node:latest run --help
> docker run inputoutput/cardano-node:latest run --topology example
> ```

this is how I've been tying too but it seems like it ignores all the arguments. Only way to make it work writing a custom run script and executing binary cardano-node from its absolute path then it honors the parameters otherwise just simple ignores it. Any plan addressing it?
