### ISSUE TITLE
[BUG] - cabal build + nix env -i fails on latest master commit

### ISSUE THREAD

**Issue by chrissound** [input-output-hk/cardano-node#1611]
**Internal/Exernal**
*External*   otherwise.

**Summary**
Trying to follow along with https://docs.cardano.org/projects/cardano-node/en/latest/reference/shelley-genesis.html
Which states:

> This assumes that you already have built and installed the executables from this repository. So cardano-cli and cardano-node should be on your $PATH.

So I assume I need to install this library/executable/repo.

**Steps to reproduce**

(The commit referenced is the latest for `master` branch).
```
git@github.com:input-output-hk/cardano-node.git
cd cardano-node && git checkout f616c7d9a994764d3b09e241bc59c3dce95ced5f
nix-env -if default.nix
```

Attempt with `cabal build` (as mentioned on the README):
```
cabal build
HEAD is now at 183a70c0 Merge pull request #1712 from input-output-hk/jc/app-perf-use-active-stake
HEAD is now at ec74d1c46 Merge #2466
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.
```
If I try `cabal bulid all`:
```
cabal build all
Warning: The package list for 'hackage.haskell.org' is 110 days old.
Run 'cabal update' to get the latest list of available packages.
Warning: Requested index-state2020-07-15T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2020-04-11T13:54:36Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: cardano-api-1.18.0 (user goal)
[__1] next goal: bech32 (dependency of cardano-api)
[__1] rejecting: bech32-1.0.2, bech32-1.0.1, bech32-1.0.0 (conflict:
cardano-api => bech32>=1.1.0)
[__1] fail (backjumping, conflict set: bech32, cardano-api)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-api, bech32
```

**Expected behavior**
A successful nix build / nix install.

**System info (please complete the following information):**
- OS: Linux / Nixos
- Version: 20.03.1950.48723f48ab9 (Markhor)
- Node version: ?

----

Possibly the solution is (as mentioned here https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/building-the-node-using-nix.html#building-under-nix):
```
nix-build -A scripts.mainnet.node -o mainnet-node-local
```

However the question then becomes, how do I build/install cardano-cli with nix in that case?

**Comment by kevinhammond** [comment]
You need to include the dependency in the build configuration.  The documentation is missing this.  I believe the following may be what you need

```
$ cat cabal.project.local 
package cardano-crypto-praos
  flags: -external-libsodium-vrf
```

**Comment by chrissound** [comment]
Thanks for the note, I've added that file now however I'm running into a seemingly different error this time (I've pulled through the latest `master` branch):

```
nix build
trace: Using IOHK default nixpkgs
trace: Using index-state: 2020-07-15T00:00:00Z for cardano-node-src
[0.0 MiB DL] querying cardano-node-src-plan-to-nix-pkgs on https://mpickering.cachix[0.0 MiB DL] querying cardano-node-src-plan-to-nix-pkgs on https://komposition.c[0.0 MiB DL] querying ca[1/1/2 built, 0.0 MiB DL[1/1/2 built, 0.0 MiB DLtrace: Using index-state: 2020-07-15T00:00:00Z for cardano-node-src
trace: Using index-state: 2020-05-31T00:00:00Z for hoogle
trace: To make this a fixed-output derivation but not materialized, set `plan-sha256` to the output of /nix/store/ax206k8wgvl3mryz92k7ps445969j90c-calculateSha
trace: To materialize the output entirely, pass a writable path as the `materialized` argument and pass that path to /nix/store/4vq6zhwg0dkp9f15jgjcxyqsp62wbzm6-generateMaterialized
builder for '/nix/store/wcxszrbmx2ixjj79gvs95lam53n9fw64-cardano-cli-test-cardano-cli-test-1.18.0-check.drv' failed with exit code 1; last 10 log lines:
    ✓ 1 succeeded.
  ━━━ Pioneers Example 4 ━━━
    ✓ prop_createStakeAddressRegistrationCertificate passed 1 test.
    ✓ 1 succeeded.
  ━━━ ITN key conversion ━━━
    ✓ prop_convertITNKeys passed 1 test.
    ✓ prop_convertITNBIP32SigningKey passed 1 test.
    ✓ prop_convertITNExtendedSigningKey passed 1 test.
    ✓ golden_bech32Decode passed 1 test.
    ✓ 4 succeeded.
[49 built (1 failed), 102 copied (649.5 MiB), 206.1 MiB DL]
error: build of '/nix/store/wcxszrbmx2ixjj79gvs95lam53n9fw64-cardano-cli-test-cardano-cli-test-1.18.0-check.drv' failed
```

Trying it on the original commit seems to run into the same error. 

----

Strangely, I got this to somewhat work somehow yesterday, but I can't recall what changes I did. Although the nix/cabal bulid failed it still generated bunch of `result-*` directories, which in turn contained the `cardano-cli` derivation / executable.

**Comment by craigem** [comment]
Hi @chrissound - as a fellow NixOS 20.03 user, if I wish to play with the source I'd use the nix shell provided which if I understand what you're trying to do correctly, will drop you into a shell with all the required dependencies in place:

```
$ nix-shell
```

If you're just wanting to build cardano-node, you can run:

```
$ nix-build -A cardano-node
```

This will cleanly build cardano-node for NixOS, ready to run as ./result/bin/cardano-node.

If you wish to build and run a completely pre-configured cardano-node you can try:

```
$ nix build -f . scripts.mainnet.node -o launch-cardano-mainnet 
$ ./launch-cardano-mainnet
```

If you wish to run cardano-node as a service, my personal [cardano-node.nix](https://source.mcwhirter.io/craige/mio-ops/src/branch/master/roles/cardano-node.nix) file may be of use.

As a NixOS user, if you just want to build and run it, the above is the most graceful way.
