### ISSUE TITLE
[BUG] - Shelley genesis walkthrough docs, outdated?

### ISSUE THREAD

**Issue by chrissound** [input-output-hk/cardano-node#1613]
**Internal/Exernal**
*External*   otherwise.

**Summary**
Walkthrough steps do not seem to be correct.  https://docs.cardano.org/projects/cardano-node/en/latest/reference/shelley-genesis.html

**Steps to reproduce**

Following with all steps we end up with a `example` directory with contents:
```
example
├── delegate-keys
│  ├── delegate-opcert1.counter
│  ├── delegate-opcert2.counter
│  ├── delegate1.skey
│  ├── delegate1.vkey
│  ├── delegate2.skey
│  └── delegate2.vkey
├── genesis-keys
│  ├── genesis1.skey
│  ├── genesis1.vkey
│  ├── genesis2.skey
│  └── genesis2.vkey
├── genesis.json
├── genesis.spec.json
└── utxo-keys
   ├── utxo1.skey
   ├── utxo1.vkey
   ├── utxo2.skey
   └── utxo2.vkey
``` 

```
cardano-cli shelley genesis create --genesis-dir example/ --mainnet 
Mismatch between the files found:
Genesis key file indexes:      [1,2]delegate key file indexes:     [1,2]delegate VRF key file indexes: []
```

This seems to be missing the VRF keys, which is documented further down. However to generate those it seems we need to generate something `node1` related (I assume node keys):
```
cardano-cli shelley node key-gen-VRF \
    --verification-key-file example/node1/vrf.vkey \
    --signing-key-file example/node1/vrf.skey
example/node1/vrf.skey: example/node1/vrf.skey: openBinaryFile: does not exist (No such file or directory)
```

However... That section has:
> For now we will ignore stake pools however since we need to get the system bootstrapped with the BFT overlay.

Which makes me think I might be going down a rabbit hole, so possibly these instructions are outdated or incorrect?

**Expected behavior**

Being able to successfully update the genesis files.

---

Also I could mention that all the commands upto now are seem to be missing a `--mainnet` parameter (though this was easy to figure out and just add in).

**Comment by CarlosLopezDeLara** [comment]
This is @dcoutts reference doc. 

@chrissound is this what you are looking for? 
 https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/getConfigFiles_AND_Connect.html

Or what do you mean by update genesis files?

**Comment by chrissound** [comment]
That link seems to be for the configs for the existing testnet / main net. However the previous document/link (https://docs.cardano.org/projects/cardano-node/en/latest/reference/shelley-genesis.html#making-a-shelley-blockchain-from-scratch) relates to creating a new genesis (at least to my understanding).

> Or what do you mean by update genesis files?

I understood that running the `cardano-cli shelley genesis create --genesis-dir example/ --mainnet` command should update the genesis file. But as stated, that command does not successfully run due to the missing VRF keys.

Really, I am just trying to gain familiarity with the project. I saw a link to the guide from https://forum.cardano.org/t/shelley-is-delivered/36502 so thought I'd give it a go.

**Comment by vix-io** [comment]
hi @CarlosLopezDeLara any update on this one?

**Comment by LintCroft** [comment]
I am also stuck at this point when following the steps documented here: https://docs.cardano.org/projects/cardano-node/en/latest/reference/shelley-genesis.html. I got down to the part that says "Let’s regenerate the genesis file".

```
$ cardano-cli shelley genesis create --mainnet --genesis-dir example
Shelley command failed: genesis create  Error: Mismatch between the files found:
Genesis key file indexes:      [1,2]delegate key file indexes:     [1,2]delegate VRF key file indexes: []
```

My example directory is in the same state as @chrissound's report.
