### ISSUE TITLE
[BUG] - cardano-node run, host-addr with a public IP address

### ISSUE THREAD

**Issue by dk8996** [input-output-hk/cardano-node#1618]
**Exernal**

**Summary**
Seems like if host-addr config is set to a public address like the document says the port will not be open for connection.  No error is shown.

**Steps to reproduce**
1. Change the cardano-node run command to have **host-addr** per documentations here (https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/start_your_nodes.html).  This must be a public IP address, not 127.0.0.1.
2. Run `netstat -a` to see what ports are open.  The port set in the run config should be open but it's not.
3. Change the  **host-addr** to 127.0.0.1
4. See that the port is now open.

**Expected behavior**
The expected behavior is that the port should be open, there might be a bigger error, when the public IP is set. Moreover, there should be error thrown.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 18.04
- Node 1.18

**Screenshots and attachments**
You can see the node is running and it's connected to the network.  XXX.XXX.XXX.XXX is the public IP address.
ubuntu    2786 17.0 23.8 1074584832 947664 ?   Sl   05:30   8:59 /home/ubuntu/.local/bin/cardano-node run --topology /home/ubuntu/pool/relay/mainnet-topology.json --database-path /home/ubuntu/pool/relay/db --socket-path /home/ubuntu/pool/relay/db/node.socket --host-addr XXX.XXX.XXX.XXX --port 3001 --config /home/ubuntu/pool/relay/mainnet-config.json

Netstat results show no 3001 port open and in LISTEN state.

tcp        0      0 127.0.0.1:12788         0.0.0.0:*               LISTEN      2786/cardano-node   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      786/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      945/sshd            
tcp        0      0 127.0.0.1:12798         0.0.0.0:*               LISTEN      2786/cardano-node   
tcp6       0      0 :::22                   :::*                    LISTEN      945/sshd      

**Additional context**
Seems like a big bug if people follow the documentation.  Relay node and nodes wont be able to connect to each other.

**Comment by karknu** [comment]
It doesn't have to be a public IP address, anyway looks like it is working.
Running `cardano-node` with `--host-addr 192.168.0.99` shows that the node is listening to the port.

```
netstat -n -a | grep 47776
tcp4       0      0  192.168.0.99.47776     *.*                    LISTEN 
```

Running `cardano-node` without an address show that the node is listening to on the port for all addresses.

```
netstat -n -a | grep 47776
tcp4       0      0  *.47776                *.*                    LISTEN     
tcp6       0      0  *.47776                *.*                    LISTEN
```
