### ISSUE TITLE
[BUG] - cardano-cli: openFile: permission denied

### ISSUE THREAD

**Issue by stakepoolplace** [input-output-hk/cardano-node#1630]
*External*

**Summary**
When i encrypt a Wallet and come back to show the wallet i get : 
cardano-cli: /opt/cardano/cnode/priv/wallet/PlaceWallet/base.addr: openFile: permission denied (Operation not permitted)Select Wallet:

**Steps to reproduce**
0. user cardano (belonging to sudoers)
1. Go to 'cntools.sh > wallet > encrypt'
2. i type a password more than 8 letter length
3. Go back to show

**System info (please complete the following information):**
- OS: Debian 10
- Node version 1.18

**Screenshots and attachments**

**Additional context**
drwxr-xr-x 3 cardano cardano 4096 Jul 30 12:22 ..
-r-------- 1 cardano cardano  189 Jul 30 12:22 payment.vkey
-r-------- 1 cardano cardano  185 Jul 30 12:22 stake.vkey
-r-------- 1 cardano cardano  184 Jul 30 13:58 stake.cert
-r-------- 1 cardano cardano  103 Aug  3 19:17 base.addr
-r-------- 1 cardano cardano   58 Aug  3 19:17 payment.addr
-r-------- 1 cardano cardano   59 Aug  3 19:17 reward.addr
-r-------- 1 cardano cardano  223 Aug  3 19:18 payment.skey.gpg
-r-------- 1 cardano cardano  219 Aug  3 19:18 stake.skey.gpg
drwxr-xr-x 2 cardano cardano 4096 Aug  3 19:18 .

**Comment by Jimbo4350** [comment]
Hello @stakepoolplace, could you outline the commands you used in `cardano-cli`?

**Comment by stakepoolplace** [comment]
Thanks a lot !
