### ISSUE TITLE
[BUG] - setting "TurnOnLogging" to false gives an incorrect message

### ISSUE THREAD

**Issue by willcbanks** [input-output-hk/cardano-node#1635]
*External*   otherwise.

**Summary**
Setting "TurnOnLogging" to false cause cardano-node to give this message:

please turn on the following tracers in the configuration file:
TraceBlockFetchDecisions.
TraceChainDb
TraceForge
TraceMempool

Even when all the tracers above are set to true.

**Steps to reproduce**
1. Go to  config.json
2. set "TurnOnLogging" to false
3. set all above options to true
4. start cardano-node

**Expected behavior**
should not see the message and node should start

**System info (please complete the following information):**

- Node version  1.18.0

**Screenshots and attachments**

<img width="706" alt="Screen Shot 2020-08-04 at 20 40 11" src="https://user-images.githubusercontent.com/67793497/89333208-f1e45b80-d694-11ea-9936-c578135cf40d.png">

**Comment by dcoutts** [comment]
Yes the error message could also mention that logging has to be turned on at all, but I doubt this is really going to confuse anyone. The in-process live view is going to be replaced by an out-of-process rt view, so this will change at that time anyway.
