### ISSUE TITLE
[FR] - Missing transaction check CLI command in Shelley

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#1637]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Describe the feature you'd like**
There's no CLI command for checking transaction in Shelley.

**Describe alternatives you've considered**
None.

**Additional context / screenshots**
There is a CLI command but doesn't seem to be implemented.

```
$ cardano-cli shelley transaction check
runTransactionCmd: TxCheck
```

**Comment by Jimbo4350** [comment]
Closing as this command was removed
