### ISSUE TITLE
How can sign transaction using cardano-cli if transaction has two inputs?

### ISSUE THREAD

**Issue by sjlee1125** [input-output-hk/cardano-node#1647]
[In Cardano Docs](https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/simple_transaction.html#sign-the-transaction)
There is example of signing transaction by payment.skey
This example has one input

if transaction has two inputs, How can sign transaction?

**Comment by intricate** [comment]
You'd sign the transaction in the same way. Just provide two `--tx-in`s when building the transaction:

```
cardano-cli shelley transaction build-raw \
--tx-in txid#txix \
--tx-in txid#txix \
...
```

**Comment by erikd** [comment]
Closing this as resolved. @sjlee1125 if this is not resolved, please re-open.
