### ISSUE TITLE
[BUG] - Documentation example

### ISSUE THREAD

**Issue by ItFlyingStart** [input-output-hk/cardano-node#1653]
**Exernal**

**Summary**
The provided example is incorrect:

--pool-owner-stake-verification-key-file stake.vkey \

should be

--pool-owner-stake-verification-key stake.vkey \

![image](https://user-images.githubusercontent.com/5562995/89663747-4de9f280-d8d6-11ea-9e11-30ebee45aadd.png)

**Comment by intricate** [comment]
@ItFlyingStart: The documentation is correct here. We've renamed the CLI option to `--pool-owner-stake-verification-key-file`, but we still also support `--pool-owner-stake-verification-key`.
