### ISSUE TITLE
[BUG] - Troubles building on NixOs

### ISSUE THREAD

**Issue by diegueins680** [input-output-hk/cardano-node#1654]
**Exernal

**Summary**
Can't build on NixOs

**Steps to reproduce**
On NixOs
1. cd to the directory cloned from this repository. 
2. Issue "cabal build", as per the README instructions, or issue "cabal build all".
3. With cabal build, I get the following message:
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.

If I issue "cabal build all", I get the following output:
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: cardano-api-1.18.0 (user goal)
[__1] next goal: serialise (dependency of cardano-api)
[__1] rejecting: serialise-0.2.3.0/installed-5VK... (package is broken)
[__1] fail (backjumping, conflict set: cardano-api, serialise)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-api, serialise

**Expected behavior**
Cardano node gets built.

**System info (please complete the following information):**
- OS: NixOs
- Version 20.03
- Node version: latest from this repo

**Comment by craigem** [comment]
Hi @diegueins680 - As a NixOS 20.03 user I use the built-in Nix support of `cardano-node` to build it:

* cd to the directory cloned from this repository
* Run (assuming you're on master branch):

```
$ nix-build -A cardano-node
```

This will cleanly build `cardano-node` for NixOS, ready to run as `./result/bin/cardano-node`.

If you wish to build and run a  completely pre-configured `cardano-node` you can try:

```
$ nix build -f . scripts.mainnet.node -o launch-cardano-mainnet 
$ ./launch-cardano-mainnet
```

If you wish to run `cardano-node` as a service, my personal [cardano-node.nix](https://source.mcwhirter.io/craige/mio-ops/src/branch/master/roles/cardano-node.nix) file may be of use.

You may have other reasons for wanting to use cabal but as a NixOS user, if you just want to build and run it, the above is the most graceful way.

**Comment by diegueins680** [comment]
Thanks!
