### ISSUE TITLE
[BUG] - Can't redeem ITN rewards with 12 word recovery phrase

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#1656]
**Internal/External**
*External*   

**Summary**
Using Daedalus 2.1.0 I am unable to redeem my ITN rewards using my 12 word recovery phrase

**Steps to reproduce**
1. Download and install Daedalus 2.1.0 for Linux.
2. Go to the redeem ITN rewards page.
3. Enter 12 word recovery phrase from ITN rewards wallet created by cardano-wallet at the beginning of the ITN.
4. Select Shelley wallet for deposit and fee.
5. Check both "I understand..." checkboxes.
6. See that the Continue button is still disabled and can't continue.

**Expected behavior**
Should be able to click Continue button and finish redemption process.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 18.04
- Daedalus version 2.1.0

**Comment by rdlrt** [comment]
ITN recovery phrase was 15 words (or 21 if using Yoroi paper wallets), not 12.
Please use [support](https://iohk.zendesk.com/hc/en-us/requests/new) if any further queries

**Comment by shawnim** [comment]
Thanks for the reply Priyank but that is not correct.
I created my staking and rewards wallet for my pool on the itn_rewards_v1 ITN network at the beginning of the ITN.
I created the wallet with the commandline cardano-wallet according to the instructions available at the time.
I received delegation rewards and pool fees to that address from epoch 3 until the end of the ITN.
Is there some conversion that needs to be done to go from a 12 word phrase to a 15 word phrase?
Any help with this would be greatly appreciated.

**Comment by rdlrt** [comment]
Your original query was to redeem rewards using 12 word mnemonics, while as per your reply - what you're looking for is to redeem your rewards using ITN private key.

Cardano CLI does have convert-itn-keys option, you can refer to example script [here](https://cardano-community.github.io/guild-operators/#/Scripts/itnrewards) for your reference. Again, something that would be addressed much easier on support or on staking workgroups as multiple hundreds of pool operators were using it and can assist you with any further queries

**Comment by shawnim** [comment]
Thank you!!!
This was very helpful.
I did previously ask on both the Stake Pool telegram and on zendesk support and got no useful answer from either one.

**Comment by intricate** [comment]
Thanks for the assist @rdlrt. 

@shawnim: Is this issue resolved then?

**Comment by shawnim** [comment]
Yes. Thank you!
