### ISSUE TITLE
[FR] Know absolute stake and saturation of pools using LSQ

### ISSUE THREAD

**Issue by Anviking** [input-output-hk/cardano-node#1659]
**Internal**

**Describe the feature you'd like**

LSQ command(s) to directly or indirectly know the following for active stake pools:

1. Stake relative to the _active_ stake (Currently possible with `GetStakeDistribution`)
2. Stake relative to the _total_ stake
3. Stake in absolute ada.

(cf [5.5.1 Relative Stake: Active vs Total](https://hydra.iohk.io/build/3744897/download/1/delegation_design_spec.pdf)).

**Describe alternatives you've considered**

This information could presumably be extracted from `GetCurrentEpochState`, but it is "only for debugging purposes".

The _total_ stake could be hard-coded. Daedalus displays it as 33B. But I believe this may change in the long term?

**Additional context / screenshots**
`cardano-wallet` is interested in providing:
- The controlled stake of each pool in ada (instead as fractional to total active stake)
- To what extent the pool is oversaturated or not (requires comparison to the total stake)

Relates to input-output-hk/cardano-wallet#1980

Perhaps this ticket should be in ouroboros-network instead of cardano-node.

**Comment by darko-mijic** [comment]
> The total stake could be hard-coded. Daedalus displays it as 33B. But I believe this may change in the long term?

This will change. It may have already changed with ITN rewards. @disassembler? At some point, we should have a live number @AlexIOHK @KtorZ  @kevinhammond @dcoutts

**Comment by kevinhammond** [comment]
Yes, live stake will definitely change as rewards are obtained.  This doesn't look difficult to do.

**Comment by Anviking** [comment]
> Yes, live stake will definitely change as rewards are obtained.

Oh, don't _think_ you meant this, but having access the the live (in addition to active) stake would definitely be cool too!

Then cardano-wallet/Daedalus could, if desired, show both just like pooltool.io.

(Separate from the original request in this ticket though)

**Comment by dcoutts** [comment]
Another summary of this could be simply:

Have the stake pool query also return the saturation fraction for each pool, to show to the curious.

**Comment by hodlonaut** [comment]
> Another summary of this could be simply:
> 
> Have the stake pool query also return the saturation fraction for each pool, to show to the curious.

You mean so that cardano-wallet code doesn't have its own saturation calculation code in place? Sure, sounds like that would achieve the same end goal... is calculation of current 'live' delegated total for a given pool and current total supply something that's easily obtainable by the node (as a part of this proposed fraction calculation)?

**Comment by kantp** [comment]
Just talked about this on slack with @KtorZ, and it seems that the easiest thing to do would be for the pool query to return the fraction of total stake _instead_ of the fraction of active stake. That would not require any changes in Adrestia at all.
