### ISSUE TITLE
[PERF] - GetFilteredDelegationsAndRewardAccounts slows down a lot with concurrent requests

### ISSUE THREAD

**Issue by Anviking** [input-output-hk/cardano-node#1674]
**Internal**

**Summary**
When the wallet has ~10 chain-sync connections with the node, and sends many `GetFilteredDelegationsAndRewardAccounts` queries, the `GetFilteredDelegationsAndRewardAccounts` slows down a lot.

**Steps to reproduce**
Using cardano-wallet revision `087b3acdbb67b4a7e558cedd8d6d4467176a405d`

1. Connect cardano-node to mainnet
2. `cardano-wallet serve --node-socket socket --mainnet --database wallet-db | grep "getAccountBalance"`
3. Create wallets like this

```bash
# (this is using fish shell and httpie)
function genXPub; cardano-address recovery-phrase generate --size 15 | cardano-address key from-recovery-phrase --base16 Shelley | cardano-address key public --base16; end
for i in (seq 10); http post localhost:8090/v2/wallets name="w$i" account_public_key=(genXPub); end;
```

4. Observe that `getAccountBalance` seem to increase dramatically with the number of wallets created.

**Expected behavior**

ℹ️ It is an obvious mistake of the **wallet** to query the node this often, instead of say on each epoch-change. ℹ️ 

Still, I didn't expect `GetFilteredDelegationsAndRewardAccounts` to slow down so easily.

**System info (please complete the following information):**
- OS: Mac 
- Version 10.15.5
- Node version 1.18

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

<details>
<summary>2 wallets - e.g. 0.015812s</summary>

```
[cardano-wallet.network:Info:70] [2020-08-12 10:40:52.37 UTC] Query getAccountBalance took 0.014535s
[cardano-wallet.network:Info:55] [2020-08-12 10:40:52.37 UTC] Query getAccountBalance took 0.018979s
[cardano-wallet.network:Info:55] [2020-08-12 10:41:12.72 UTC] Query getAccountBalance took 0.015284s
[cardano-wallet.network:Info:70] [2020-08-12 10:41:12.72 UTC] Query getAccountBalance took 0.019339s
[cardano-wallet.network:Info:70] [2020-08-12 10:41:32.57 UTC] Query getAccountBalance took 0.020223s
[cardano-wallet.network:Info:55] [2020-08-12 10:41:32.58 UTC] Query getAccountBalance took 0.024212s
[cardano-wallet.network:Info:55] [2020-08-12 10:41:53.01 UTC] Query getAccountBalance took 0.012628s
[cardano-wallet.network:Info:70] [2020-08-12 10:41:53.01 UTC] Query getAccountBalance took 0.014309s
[cardano-wallet.network:Info:70] [2020-08-12 10:42:20.61 UTC] Query getAccountBalance took 8.438195s
[cardano-wallet.network:Info:55] [2020-08-12 10:42:20.62 UTC] Query getAccountBalance took 8.439893s
[cardano-wallet.network:Info:70] [2020-08-12 10:42:32.99 UTC] Query getAccountBalance took 0.006871s
[cardano-wallet.network:Info:55] [2020-08-12 10:42:32.99 UTC] Query getAccountBalance took 0.010785s
[cardano-wallet.network:Info:55] [2020-08-12 10:42:52.24 UTC] Query getAccountBalance took 0.015422s
[cardano-wallet.network:Info:70] [2020-08-12 10:42:52.24 UTC] Query getAccountBalance took 0.018407s
[cardano-wallet.network:Info:55] [2020-08-12 10:43:12.41 UTC] Query getAccountBalance took 0.009286s
[cardano-wallet.network:Info:70] [2020-08-12 10:43:12.41 UTC] Query getAccountBalance took 0.012372s
[cardano-wallet.network:Info:55] [2020-08-12 10:43:32.35 UTC] Query getAccountBalance took 0.012464s
[cardano-wallet.network:Info:70] [2020-08-12 10:43:32.35 UTC] Query getAccountBalance took 0.014307s
[cardano-wallet.network:Info:70] [2020-08-12 10:43:52.66 UTC] Query getAccountBalance took 0.025028s
[cardano-wallet.network:Info:55] [2020-08-12 10:43:52.67 UTC] Query getAccountBalance took 0.019376s
[cardano-wallet.network:Info:70] [2020-08-12 10:44:13.10 UTC] Query getAccountBalance took 0.015812s
```
</details>

<details>
<summary>5 wallets - 7s-40s </summary>

```
cardano-wallet.network:Info:115] [2020-08-12 10:38:20.17 UTC] Query getAccountBalance took 7.475021s
[cardano-wallet.network:Info:100] [2020-08-12 10:38:27.49 UTC] Query getAccountBalance took 14.792479s
[cardano-wallet.network:Info:85] [2020-08-12 10:38:35.25 UTC] Query getAccountBalance took 22.557319s
[cardano-wallet.network:Info:70] [2020-08-12 10:38:42.88 UTC] Query getAccountBalance took 30.185679s
[cardano-wallet.network:Info:55] [2020-08-12 10:38:50.82 UTC] Query getAccountBalance took 38.126708s
[cardano-wallet.network:Info:100] [2020-08-12 10:38:50.84 UTC] Query getAccountBalance took 18.207614s
[cardano-wallet.network:Info:115] [2020-08-12 10:38:50.84 UTC] Query getAccountBalance took 18.188614s
[cardano-wallet.network:Info:85] [2020-08-12 10:38:50.86 UTC] Query getAccountBalance took 15.604795s
[cardano-wallet.network:Info:70] [2020-08-12 10:38:50.88 UTC] Query getAccountBalance took 7.993005s
[cardano-wallet.network:Info:55] [2020-08-12 10:38:50.89 UTC] Query getAccountBalance took 0.059782s
[cardano-wallet.network:Info:55] [2020-08-12 10:39:00.40 UTC] Query getAccountBalance took 7.846397s
[cardano-wallet.network:Info:70] [2020-08-12 10:39:08.04 UTC] Query getAccountBalance took 15.482712s
[cardano-wallet.network:Info:115] [2020-08-12 10:39:08.05 UTC] Query getAccountBalance took 15.485739s
[cardano-wallet.network:Info:100] [2020-08-12 10:39:08.06 UTC] Query getAccountBalance took 15.49769s
[cardano-wallet.network:Info:85] [2020-08-12 10:39:08.07 UTC] Query getAccountBalance took 15.47923s
[cardano-wallet.network:Info:115] [2020-08-12 10:39:22.13 UTC] Query getAccountBalance took 7.936665s
[cardano-wallet.network:Info:100] [2020-08-12 10:39:29.94 UTC] Query getAccountBalance took 15.748305s
[cardano-wallet.network:Info:85] [2020-08-12 10:39:37.87 UTC] Query getAccountBalance took 23.673051s
[cardano-wallet.network:Info:70] [2020-08-12 10:39:47.21 UTC] Query getAccountBalance took 33.018883s
[cardano-wallet.network:Info:55] [2020-08-12 10:39:54.64 UTC] Query getAccountBalance took 40.445846s
```
</details>

<details>

<summary>10 wallets - e.g. 54s </summary>

```
[cardano-wallet.network:Info:190] [2020-08-12 11:01:37.67 UTC] Query getAccountBalance took 5.069693s
[cardano-wallet.network:Info:145] [2020-08-12 11:01:42.54 UTC] Query getAccountBalance took 9.934192s
[cardano-wallet.network:Info:130] [2020-08-12 11:01:47.26 UTC] Query getAccountBalance took 14.653831s
[cardano-wallet.network:Info:115] [2020-08-12 11:01:51.94 UTC] Query getAccountBalance took 19.335942s
[cardano-wallet.network:Info:100] [2020-08-12 11:01:56.80 UTC] Query getAccountBalance took 24.191501s
[cardano-wallet.network:Info:85] [2020-08-12 11:02:01.56 UTC] Query getAccountBalance took 28.94668s
[cardano-wallet.network:Info:70] [2020-08-12 11:02:06.34 UTC] Query getAccountBalance took 33.723328s
[cardano-wallet.network:Info:175] [2020-08-12 11:02:11.12 UTC] Query getAccountBalance took 38.500186s
[cardano-wallet.network:Info:55] [2020-08-12 11:02:16.03 UTC] Query getAccountBalance took 43.41285s
[cardano-wallet.network:Info:160] [2020-08-12 11:02:20.94 UTC] Query getAccountBalance took 48.316489s
[cardano-wallet.network:Info:130] [2020-08-12 11:02:25.85 UTC] Query getAccountBalance took 32.918672s
[cardano-wallet.network:Info:145] [2020-08-12 11:02:30.83 UTC] Query getAccountBalance took 37.900493s
[cardano-wallet.network:Info:115] [2020-08-12 11:02:35.88 UTC] Query getAccountBalance took 42.949767s
[cardano-wallet.network:Info:190] [2020-08-12 11:02:40.91 UTC] Query getAccountBalance took 47.980061s
[cardano-wallet.network:Info:100] [2020-08-12 11:02:46.33 UTC] Query getAccountBalance took 49.506753s
[cardano-wallet.network:Info:85] [2020-08-12 11:02:51.32 UTC] Query getAccountBalance took 49.756595s
[cardano-wallet.network:Info:70] [2020-08-12 11:02:56.58 UTC] Query getAccountBalance took 50.240666s
[cardano-wallet.network:Info:175] [2020-08-12 11:03:01.52 UTC] Query getAccountBalance took 50.388006s
[cardano-wallet.network:Info:55] [2020-08-12 11:03:06.56 UTC] Query getAccountBalance took 50.524645s
[cardano-wallet.network:Info:160] [2020-08-12 11:03:11.84 UTC] Query getAccountBalance took 50.887513s
[cardano-wallet.network:Info:130] [2020-08-12 11:03:17.03 UTC] Query getAccountBalance took 51.175731s
[cardano-wallet.network:Info:145] [2020-08-12 11:03:22.08 UTC] Query getAccountBalance took 51.244343s
[cardano-wallet.network:Info:115] [2020-08-12 11:03:27.13 UTC] Query getAccountBalance took 51.241189s
[cardano-wallet.network:Info:190] [2020-08-12 11:03:32.58 UTC] Query getAccountBalance took 51.664463s
[cardano-wallet.network:Info:100] [2020-08-12 11:03:37.82 UTC] Query getAccountBalance took 51.490229s
[cardano-wallet.network:Info:85] [2020-08-12 11:03:43.06 UTC] Query getAccountBalance took 51.730958s
[cardano-wallet.network:Info:70] [2020-08-12 11:03:48.41 UTC] Query getAccountBalance took 51.824369s
[cardano-wallet.network:Info:175] [2020-08-12 11:03:53.74 UTC] Query getAccountBalance took 52.219182s
[cardano-wallet.network:Info:55] [2020-08-12 11:03:59.09 UTC] Query getAccountBalance took 52.51981s
[cardano-wallet.network:Info:160] [2020-08-12 11:04:04.64 UTC] Query getAccountBalance took 52.797638s
[cardano-wallet.network:Info:130] [2020-08-12 11:04:10.94 UTC] Query getAccountBalance took 53.903298s
```
</details>

**Additional context**

`getAccountBalance` uses
```haskell
QueryIfCurrentShelley (Shelley.GetFilteredDelegationsAndRewardAccounts (Set.singleton cred))
```

I think I saw signs of the wallet being stuck on `MsgReAquire`.

**Comment by Anviking** [comment]
Related to input-output-hk/cardano-wallet#2005 and input-output-hk/cardano-wallet#2006

**Comment by mrBliss** [comment]
This is the implementation of [`getFilteredDelegationsAndRewardAccounts`](https://github.com/input-output-hk/ouroboros-network/blob/7454eaca85e3ffc298e973767316ab2eac2bbe7b/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs#L540-L548):

```haskell
getFilteredDelegationsAndRewardAccounts :: SL.ShelleyState c
                                        -> Set (SL.Credential 'SL.Staking c)
                                        -> (Delegations c, SL.RewardAccounts c)
getFilteredDelegationsAndRewardAccounts ss creds =
    (filteredDelegations, filteredRwdAcnts)
  where
    dstate = getDState ss
    filteredDelegations = Map.restrictKeys (SL._delegations dstate) creds
    filteredRwdAcnts = Map.restrictKeys (SL._rewards dstate) creds
```

`getDState`, `SL._delegations`, and `SL._rewards` are just field lookups (guaranteed to be thunk-free).

The only real computation that is happening AFAIK is [`Map.restrictKeys`](https://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Strict.html#v:restrictKeys) with as complexity: O(m*log(n/m + 1)), m <= n.

I'm assuming that *m* refers to the size of the `Set` and not the `Map` (because *n* is everywhere else to refer to the size of the `Map`). Otherwise, `restrictKeys` would not be the right choice, but that would surprise me.

Other potential causes: the `Ord` instance of `SL.Credential`, the en/decoder of the result.

Profiling this would bring clarity, of course.

**Comment by Anviking** [comment]
Oh, some extra information:
IIRC:
- I saw the wallet being stuck on `MsgReAquire` for long times. 
- I set up script at the time with 50 workers polling the stake distribution concurrently. 
    - It did slow down somewhat (each request took 20s-80s)
    - In the wallet, with`GetFilteredDelegationsAndRewardAccounts` , we saw ~50s for 10 workers, and easily multiple minutes with more workers. So seems `GetFilteredDelegationsAndRewardAccounts` is still more prone to slowdown, but it wasn't  an apples-to-apples comparison.

But I wonder if it could be partly more related to state-acquiring than to `GetFilteredDelegationsAndRewardAccounts`.

**Comment by mrBliss** [comment]
> Oh, some extra information:
> IIRC:
> 
>     * I saw the wallet being stuck on `MsgReAquire` for long times.
> 
>     * I set up script at the time with 50 workers polling the stake distribution concurrently.
>       
>       * It did slow down somewhat (each request took 20s-80s)
>       * In the wallet, with`GetFilteredDelegationsAndRewardAccounts` , we saw ~50s for 10 workers, and easily multiple minutes with more workers. So seems `GetFilteredDelegationsAndRewardAccounts` is still more prone to slowdown, but it wasn't  an apples-to-apples comparison.
> 
> 
> But I wonder if it could be partly more related to state-acquiring than to `GetFilteredDelegationsAndRewardAccounts`.

Aha! Indeed, state-acquiring is a much more plausible cause!

When acquiring a ledger state older than the "current" one, we'll have to look at an older snapshot of the ledger state (we keep a snapshot every 100 blocks at the moment) and replay blocks against it to bring it up to the requested state. For example, our current ledger state is at slot 1000 and we have a snapshot at slot 900. If you try to acquire a ledger state for slot 999, we can't use the current ledger state (because we can't *unapply* blocks), but have to use the snapshot of slot 900, and replay 99 blocks against it, which requires reading and revalidating (which was veeeery slow in 1.18, but is muuuuch quicker in 1.19) them. Related issue: https://github.com/input-output-hk/ouroboros-network/issues/1521

So with 1.19, this should already be much better.

Bonus: we have a plan to improve this even further, by keeping snapshots for the last `k` blocks in memory instead of one very 100 blocks. We have measured that the overhead is quite small thanks to sharing. PR for this: https://github.com/input-output-hk/ouroboros-network/pull/2459. After that's done, acquiring will be very cheap and won't require reading blocks from disk or reapplying them.

**Comment by kevinhammond** [comment]
Let's see whether `1.19.0` fixes this issue and close it if so.

**Comment by Anviking** [comment]
Tentatively yes, seems to be very good with `1.19.0`, but will confirm once we are sure.

**Comment by mrBliss** [comment]
> Tentatively yes, seems to be very good with `1.19.0`, but will confirm once we are sure.

Good enough to close this issue?

In 1.19.1, this should be even faster, no reading or replaying of blocks is necessary. In my microbenchmarks (with real `Point`s), the response time will be in the order of microseconds.

**Comment by Anviking** [comment]
👍 Yeah, think so. When I first tested I barely saw a difference between calling once and calling many times in the wallet with 1.19.0. It was slower for Piotr, but it I believe that slowness doesn't come from the local state queries themselves, so likely unrelated.
