### ISSUE TITLE
[BUG] - Potential typo in metrics for Cardano-node 1.18.1

### ISSUE THREAD

**Issue by Willburn** [input-output-hk/cardano-node#1688]
External.

Summary:
"Cardano_node_metrics_Forge_about_to_lead_int" now is named  "Cardano_node_metrics_Forge_forge_about_to_lead_int" I am wondering if this 2nd Forge is a typo and if this would have any other implication than messing up monitoring scripts for users.

Steps to reproduce
localhost:poolip/metrics 

**Expected behavior**
I expected the name change to be documented if it was a proper name change happening.

**System info (please complete the following information):**
Ubuntu 20.04 LTS.
Cardano-node 1.18.1 Commit: a4b6dae

**Comment by dcoutts** [comment]
It's not a typo, it's just part of the hierarchical naming scheme for metrics, and how that gets turned into prometheus names.
