### ISSUE TITLE
[BUG] - logs in master lack dropped slot number

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1691]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
A clear and specific description of what the bug is.

old message with slot:

```
Chain extended, new tip: (Point 5772780, "79b144923e180de76955955a9cc9b3c649f6ceb95cec6763098e420dc32097ad")
```

new message without:

```
Chain extended, new tip: 62292d753b2ee7e903095bc5f10b03cf4209f456ea08f55308e0aaab4350dda4@39920
```

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by intricate** [comment]
Just noting that the slot number is actually still in the log message, `62292d753b2ee7e903095bc5f10b03cf4209f456ea08f55308e0aaab4350dda4@39920` (`39920` is the slot number), but it's a bit difficult to spot, so I've raised a PR that improves log messages that include `Point`s and `RealPoint`s.
