### ISSUE TITLE
[FR] - TLS and Basic Auth options for Prometheus Node Exporter

### ISSUE THREAD

**Issue by Straightpool** [input-output-hk/cardano-node#1695]
**Internal / Exernal**
External 

**Describe the feature you'd like**
A multi-cluster pool with at least one block producer and 2 relays in the minimal recommended configuration typically has one monitoring station based on e.g. Prometheus / Grafana with 3 node-exporters and 3 cardano-node exporters running.

I would like to be able to set parameters in config.json analog to node-exporter (see https://inuits.eu/blog/prometheus-tls/) to add TLS and baisc auth to cardano node exporter.

In general https://prometheus.io/docs/operating/security/ Prometheus is moving to TLS as new best practice, the cardano node-exporter should do likewise.

**Describe alternatives you've considered**
One alternative would be to setup Prometheus on each remote host to capture cardano-node data. The Prometheus connection can then be TLS encrypted with additional Basic Auth.

This feature request to support TLS and Basic Auth in Cardano-node exporter itself would help avoid the overhead of running multiple Prometheus instances on every pool node just for encryption and auth of data streams.

**Additional context / screenshots**
Currently https://docs.cardano.org/projects/cardano-node/en/latest/logging-monitoring/prometheus.html says
"**NOTE: Security configurations you should perform on your monitoring server are out of scope for this tutorial."
is from the first perspectice understandable, so no recommendations need to be given here but at least possible security settings should be described which can be leveraged to implement security best practice without overhead as additional Prometheus instances.

The node-exporter way of TLS and Basic Auth configuration is very straight forward and a best practice to follow IMHO.

**Comment by disassembler** [comment]
Why not listen on localhost and reverse proxy with nginx? My preference is to use a wireguard tunnel myself but I'd you want to expose your Prometheus metrics with TLS this would be my recommendation.

**Comment by kevinhammond** [comment]
@disassembler has given a good suggestion.  I will close this since it's probably sensible to use existing Unix tools where possible rather than extending functionality.

**Comment by Straightpool** [comment]
Quick update on my end:
The idea of using a lightwight Nginx server as a reverse proxy to add TLS and Basic Auth to the Cardano Node metrics is a much better workaround than my initial idea using multiple Prometheus instances. I have implemented the Nginx workaround now and this works flawlessly with little overhead, so it is good enough.
It is still a workaround though, so this issue should still be kept in the backlog IMHO for future improvement.
