### ISSUE TITLE
[BUG] - Node should cleanly exit on SIGTERM

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1697]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
The node only cleanly exits on SIGINT (ctrl-c) and not SIGTERM. This makes the default systemd signal handler stop the node in a way it takes longer to restart. We work around this by changing the signal it gets in the systemd service, but this should probably be fixed in the node.

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by rvl** [comment]
The way we handle this in cardano-wallet is to install a signal handler which translates SIGTERM to SIGINT.

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/launcher/src/Cardano/Startup/POSIX.hs

**Comment by disassembler** [comment]
I'm not sure why this was changed to an enhancement @vix-io. This is absolutely a bug...

**Comment by reqlez** [comment]
> I'm not sure why this was changed to an enhancement @vix-io. This is absolutely a bug...

I don't see any activity for @vix-io in Github... does he still work with IOG?

**Comment by DavidEichmann** [comment]
I've created a GHC MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7681
