### ISSUE TITLE
[BUG] - Bug template text typo

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#1699]
**Internal/Exernal**
*External*   

**Summary**
Bug template has a typo. "External" is misspelled as "Exernal".

**Steps to reproduce**
1. Go to https://github.com/input-output-hk/cardano-node/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+-+
2. Look at the big report template text.

**Expected behavior**
It should say "**Internal/External**".

**Comment by kevinhammond** [comment]
https://github.com/input-output-hk/cardano-node/pull/1763
