### ISSUE TITLE
[FR] - Make the --help option work consistently in all cardano-cli commands

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#1700]
**Internal/Exernal**
*External*

**Describe the feature you'd like**
Add --help option to cardano-cli shelley commands and list available commands in the usage message.

**Additional context / screenshots**

The "--help" option is valid in "cardano-cli shelley --help" and it shows the list of available commands.
Those commands do say "--help" is an invalid option and the usage messages do not list the available commands.

$ cardano-cli --version
cardano-cli 1.18.0 - linux-x86_64 - ghc-8.6
git rev fcdd3bfee23e3f8b2d5a1281f42d13a0e305f17c

$ cardano-cli shelley --help
Usage: cardano-cli shelley COMMAND
  Shelley specific commands

Available options:
  -h,--help                Show this help text

Available commands:
  address                  Shelley payment address commands
  stake-address            Shelley stake address commands
  key                      Shelley key utility commands
  transaction              Shelley transaction commands
  node                     Shelley node operaton commands
  stake-pool               Shelley stake pool commands
  query                    Shelley node query commands. Will query the local
                           node whose Unix domain socket is obtained from the
                           CARDANO_NODE_SOCKET_PATH enviromnent variable.
  block                    Shelley block commands
  system                   Shelley system commands
  genesis                  Shelley genesis block commands
  governance               Shelley governance commands
  text-view                Commands for dealing with Shelley TextView files.
                           Transactions, addresses etc are stored on disk as
                           TextView files.

$ cardano-cli shelley query --help
Invalid option `--help'

Usage: cardano-cli shelley query COMMAND
  Shelley node query commands. Will query the local node whose Unix domain
  socket is obtained from the CARDANO_NODE_SOCKET_PATH enviromnent variable.

$ cardano-cli shelley node --help
Invalid option `--help'

Usage: cardano-cli shelley node COMMAND
  Shelley node operaton commands
ubuntu@ip-172-30-0-223:~$ cardano-cli shelley stake-pool --help
Invalid option `--help'

Usage: cardano-cli shelley stake-pool COMMAND
  Shelley stake pool commands

**Comment by kevinhammond** [comment]
Omitting --help will give you what you're asking for, won't it?

```
$ cardano-cli shelley 
Usage: cardano-cli shelley COMMAND
  Shelley specific commands

Available options:
  -h,--help                Show this help text

Available commands:
  address                  Shelley address commands
  stake-address            Shelley stake address commands
  transaction              Shelley transaction commands
  node                     Shelley node operaton commands
  stake-pool               Shelley stake pool commands
  query                    Shelley node query commands. Will query the local
                           node whose Unix domain socket is obtained from the
                           CARDANO_NODE_SOCKET_PATH enviromnent variable.
  block                    Shelley block commands
  system                   Shelley system commands
  devops                   Shelley devops commands
  genesis                  Shelley genesis block commands
  text-view                Commands for dealing with Shelley TextView files.
                           Transactions, addresses etc are stored on disk as
                           TextView files.
```

```
$ cardano-cli shelley query
Usage: cardano-cli shelley query COMMAND
  Shelley node query commands. Will query the local node whose Unix domain
  socket is obtained from the CARDANO_NODE_SOCKET_PATH enviromnent variable.

Available commands:
  pool-id                  Get the node's pool id
  protocol-parameters      Get the node's current protocol parameters
  tip                      Get the node's current tip (slot no, hash, block no)
  filtered-utxo            Get the node's current UTxO filtered by address
  version                  Get the node version

```

**Comment by dcoutts** [comment]
As Kevin says there's an easy workaround, which is just to run the command with no flags at all. This works for every command consistently.

Yes, for consistency the `--help` flag should work with all subcommands, but this is going to be a very low priority issue to deal with.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
