### ISSUE TITLE
[FR] - Remove quotes from Shelley Genesis block

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1713]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
We should strip quotes when hashing the genesis file so it can be piped to other CLI utilities.

**Steps to reproduce**

```
cardano-cli shelley genesis hash --genesis cardano-lib/shelley_qa-shelley-genesis.json 
"85d1783750753deaa6560158eb85fcb30078ea32a36e12dd8af39168bc053d09"
```

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by kevinhammond** [comment]
This is probably because it has been run through e.g. `show` internally.  It could be filtered in the code to remove the quotes.

In Unix, you can also pipe it through a `sed` stage, of course

`cardano-cli ... | sed -e 's/"//g' | ...`
