### ISSUE TITLE
[DOCS] - Potential issue in docs

### ISSUE THREAD

**Issue by milosmns** [input-output-hk/cardano-node#1722]
**External**

**Summary**

I'm looking at [this page](https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/register_key.md#draft-transaction) and in the section *draft transaction* there is an address `paymentwithstake.addr`.

It's unclear what this refers to. In previous steps we created the following files:

- payment.addr
- payment.skey
- payment.vkey
- stake.addr
- stake.cert
- stake.skey
- stake.vkey

None of them match this name.

--

So what's the address you're referring to?

**Comment by CarlosLopezDeLara** [comment]
Thanks. Fixed. It is being merged now. should go live in a few minutes. it should say:  payment.addr
