### ISSUE TITLE
[BUG] - stake pool registration issue

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-node#1728]
I registered a staking `poolpool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3yI` and got the message that it was successfully registered. But now when I check pooltool.io I can not find my pool there. Also when I check the from cntools to show my pool info it says it is not registered. I also lost the 500 ADA registration fee :(

Can someone please help me with this issue.

I had put in 2000 ADA coins into my wallet. I wanted to  pledge 1000 ADA + 500 ADA registration fee + (500 ADA extra in case I need them) 

**Registration was successful as you can see below** 

<img width="791" alt="Screen Shot 2020-08-18 at 9 41 22 PM" src="https://user-images.githubusercontent.com/2520028/90631404-b26b5280-e1f0-11ea-821f-5c42001e81d2.png">

**>> POOL >> SHOW says that my pool is not registered :( as you can see from the image below**

<img width="890" alt="Screen Shot 2020-08-18 at 9 58 41 PM" src="https://user-images.githubusercontent.com/2520028/90631666-2148ab80-e1f1-11ea-939d-b68664ad0648.png">
 
```
>> POOL >> SHOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Select Pool:

Tanzeel
[Esc] Cancel

Dumping ledger-state from node, can take a while on larger networks...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Tanzeel
ID : pool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3y
Registered : NO
Metadata
Name : Tanzeel Pool
Ticker : RANA
Homepage : http://businessthor.com/
Description : Tanzeel's ADA staking pool :)
URL : http://businessthor.com/tanzeelmeta.json
Hash URL : 054e837de7e5e0879ae09e8297c70a3a6ea02fd9c6ad64534fd68a81be4391bd
Hash Ledger :
Run arguments : --shelley-kes-key /opt/cardano/cnode/priv/pool/Tanzeel/hot.skey \
--shelley-vrf-key /opt/cardano/cnode/priv/pool/Tanzeel/vrf.skey \
--shelley-operational-certificate /opt/cardano/cnode/priv/pool/Tanzeel/op.cert

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Can someone please help me with getting this issue resolved soon please :( 

**My Wallet that I created and sent the 2000 ADA to :** 

*** transaction id : https://explorer.cardano.org/en/transaction.html?id=ca015fdd0971551dedea6734032a0735f7bf4ca3512a83b6af8b727f40fce06b

<img width="1090" alt="Screen Shot 2020-08-18 at 9 24 55 PM" src="https://user-images.githubusercontent.com/2520028/90631788-58b75800-e1f1-11ea-81ed-e1e22df78067.png">

![Screen Shot 2020-08-19 at 7 56 01 AM](https://user-images.githubusercontent.com/2520028/90631868-75ec2680-e1f1-11ea-88bf-f2151f7a61ff.png)

**New balance inc my Wallet is 1497.624602 ADA** 
```
 >> WALLET >> SHOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Select Wallet:

  adaStakeWallet 
  [Esc] Cancel 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Wallet   adaStakeWallet

UTxOs
                           TxHash                                 TxIx        Lovelace
----------------------------------------------------------------------------------------
4561d378d3c34e0109321fc6ea2f95cfe4acaab7b48d89353b04736d8e3b53ce     0        1497624602

Address             : addr1q8sx77tak5xcnf8mk34m9ug5e788eeta59hvgz2zj56swths9d6ylvz93r2nvx2ayyutujttjsctwkz9umtrms2wn65sfm7gd2
Funds               : 1497.624602 ADA
Era                 : shelley
Encoding            : bech32
Enterprise Address  : addr1v8sx77tak5xcnf8mk34m9ug5e788eeta59hvgz2zj56swtsup99z3
Enterprise Funds    : 0.000000 ADA
Rewards             : 0.000000 ADA

Delegated to Tanzeel (pool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3y)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

press any key to return to home menu
```

**When I run List Pool command I see my pool registered**
![Screen Shot 2020-08-19 at 8 22 42 AM](https://user-images.githubusercontent.com/2520028/90634179-4b03d180-e1f5-11ea-91f4-95e93447d207.png)

**But when I run Pool Show command it shows my pool is not registered**
<img width="890" alt="Screen Shot 2020-08-18 at 9 58 41 PM" src="https://user-images.githubusercontent.com/2520028/90634267-6f5fae00-e1f5-11ea-8edf-b2979b5c0df8.png">

**Comment by mark-stopka** [comment]
That's CNTOOL issue, not `cardano-node` issue.

**Comment by tanzeelrana** [comment]
I can't find the cntools repo

**Comment by mark-stopka** [comment]
https://github.com/cardano-community/guild-operators/tree/master/scripts/cnode-helper-scripts

**Comment by rdlrt** [comment]
@tanzeelrana - you might want to close the issue here. As suggested, its important to raise issue at the right place.
