### ISSUE TITLE
[BUG] - stake distribution shows pool ids in hex instead of bech32

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1729]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
minor issue, but causes confusion when you get a pool id, it's hard to compare to the output of query stake-distribution.

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by dorin100** [comment]
pool_id is not displayed correctly either in the output of `query stake-address-info`

'''
# cardano-cli shelley query stake-distribution --testnet-magic 3
                           PoolId                                 Stake frac
------------------------------------------------------------------------------
fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38   5.000e-1
'''

```
# cardano-cli shelley query stake-address-info \
> --testnet-magic 3 \
> --address $(cat addr1_stake.addr)
[
    {
        "address": "stake_test1urxx5h9mhey6v05xrss6ek6uxqgtlkpvteqjqgaleddevpggfggxw",
        "delegation": "pool1ljq292q5xwz8t3ehmaw3c5p9xprv3szwkdnrxd40004ns6dy8v0",
        "rewardAccountBalance": 0
    }
]
```

**Comment by dorin100** [comment]
I also confirm that all the above are fixed into
```
# cardano-cli --version
cardano-cli 1.19.0 - linux-x86_64 - ghc-8.6
git rev 495366939621d4a413d000494ec01a8b0f5edc26

```
