### ISSUE TITLE
[FR] - Improve Tagging of releases

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1731]
**Exernal**

**Summary**
Inexperienced operators are installing and running pre-released versions of cardano-node on mainnet before it has completed testing.

I suggest not tagging with the build number until it's ready to be installed on mainnet. For example, tag with `1.19.0-test` for IOG's internal test release. Then tag with `1.19.0-uat` once you're ready for the community to do user acceptance testing on the testnet. Finally, tag with `1.19.0` once it's ready for mainnet.

**Comment by latheesan-k** [comment]
Make it more obvious `1.19.0-for-the-love-of-god-dont-use-it-on-main-net`

**Comment by Coke-in** [comment]
The "superficial" tagging is also affecting who is simply git-clone the repo and rebuild it maybe using DevOPS tool (so, automatically) that for sure doesn't detect that the 1.19.0 _is_not_for_prime_time

**Comment by mark-stopka** [comment]
> Inexperienced operators are installing and running pre-released versions of cardano-node on mainnet before it has completed testing.

Naming convention is not the problem, lack of change management processes on the side of the inexperienced operators is.

**Comment by kevinhammond** [comment]
The QA process that we are following requires the software to be tagged with the final version before testing.  It's never a good idea to use the latest tagged version unless it has been officially released.

We are planning to include latest stable release version information in separate documentation (this is shown on the node
repo, but may be overlooked), plus compatibility charts for each of the components.  This should help.  The node is moving to a situation where it should be essentially stable, with gradual feature/performance/etc. enhancements.  We will then be able to mark versions as stable, leading edge etc.
