### ISSUE TITLE
[BUG] - Regression, block hash truncated in TraceAdoptedBlock log

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1738]
**Exernal**

**Summary**
We used to get the full block hash in TraceAdoptedBlock. In 1.19.0, it's now truncated. This makes it difficult to link to it in the block explorer. Instead of linking directly, we have to do a search now.

**Steps to reproduce**
1. Watch the logs for TraceAdoptedBlock
2. See the truncated blockHash

**Expected behavior**
Expected to get full block hash so it can easily be saved off or looked up in a 3rd party system.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version 1.19.0

**Screenshots and attachments**
```
{"at":"2020-08-20T13:13:55.01Z","env":"1.19.0:48140","ns":["cardano.node.Forge"],"data":{"blockSize":1803,"kind":"TraceAdoptedBlock","blockHash":"e5c7b24","slot":6362944},"app":[],"msg":"","pid":"701701","loc":null,"host":"papa","sev":"Info","thread":"53"}
```

**Comment by AndrewWestberg** [comment]
The log is now quite useless. You can't even search for the block in the explorer.

![Screenshot from 2020-08-20 08-36-31](https://user-images.githubusercontent.com/245918/90793252-596aef80-e2c0-11ea-8b2f-125cb1d30612.png)

**Comment by CodiePP** [comment]
configuration .JSON might contain: 
`"TracingVerbosity": "NormalVerbosity",`
which will truncate or leave out some information in the logged entries.
try to set this to:
`"TracingVerbosity": "MaximalVerbosity",`
to get everything output in the logs.

**Comment by CodiePP** [comment]
context: https://github.com/input-output-hk/cardano-node/blob/9cac96be5cc9ceb0ca208c4d7b826a1f3505e517/cardano-node/src/Cardano/Tracing/Render.hs#L114
```
renderHeaderHashForVerbosity
  :: ConvertRawHash blk
  => proxy blk
  -> TracingVerbosity
  -> HeaderHash blk
  -> Text
renderHeaderHashForVerbosity p verb =
  trim . renderHeaderHash p
 where
  trim :: Text -> Text
  trim = case verb of
    MinimalVerbosity -> Text.take 7
    NormalVerbosity -> Text.take 7
    MaximalVerbosity -> id
```
this function renders the hashes to text and only with verbosity set to `MaximalVerbosity` will output the complete hash, otherwise it truncates it to seven digits.

**Comment by AndrewWestberg** [comment]
Closing this as there is a more than acceptable work-around.
