### ISSUE TITLE
[FR] - CLI command to truncate chain db from a specific slot

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1745]
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Describe the feature you'd like**
`cardanoc-cli chain truncate --slot-no 3000000` would remove all data after slot 3000000

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by mrBliss** [comment]
I have created https://github.com/input-output-hk/ouroboros-network/issues/2530 for the consensus-related changes.
