### ISSUE TITLE
[BUG] - Build Error 1.19.0 on CentOS 7

### ISSUE THREAD

**Issue by Crypto2099** [input-output-hk/cardano-node#1747]
**External**

**Summary**
cabal build all is failing on tags/1.19.0 on CentOS 7

**Steps to reproduce**
1. Checkout cardano-node tags/1.19.0
2. run cabal clean && cabal update
3. run cabal build all
4. Receive error during build related to cryptonite

**Expected behavior**
Expect node to build binaries for running 1.19.0

**System info (please complete the following information):**
- OS: CentOS
- Version: 7.8.2003
- Node version: 1.19.0

**Screenshots and attachments**
- See attached cryptonite error log dump.

**Additional context**
Double checked that yum update && yum upgrade were performed and that all requisite packages had been installed.
[cardano-node.1.19.0.cryptonite.error.log](https://github.com/input-output-hk/cardano-node/files/5107156/cardano-node.1.19.0.cryptonite.error.log)

**Comment by mrBliss** [comment]
Does your CPU support [AES-NI](https://en.wikipedia.org/wiki/AES_instruction_set) and [SSSE3](https://en.wikipedia.org/wiki/SSSE3)?

If not, we can indicate to `cryptonite` not to use AES-NI: after your step 2, create a `cabal.project.local` file in the root of your `cardano-node` checkout with the following contents:

```
package cryptonite
  flags: -support_aesni
```
Continue with `cabal build all`.

**Comment by mrBliss** [comment]
> Okay, can confirm that following the recommendation from @mark-stopka above the following worked to successfully build on my environment:
> `cabal build all --constraint="cryptonite -support_aesni"`

That should actually have the same effect as what I suggested :thinking:. Anyway, thanks @mark-stopka for suggesting this.

Closing as this is due to a known problem with CentOS 7 and we have found a workaround that works for @Crypto2099.

**Comment by mark-stopka** [comment]
@mrBliss I also though that the mentioned `use_target_attributes` flag would do it, not the one you've mentioned, I suppose he must've apply your suggestion with `cabal.project.local` wrong...

**Comment by oanhsaitec** [comment]
Hi there,
 
I tried to fix with ` cabal build all --constraint="cryptonite -support_aesni"` and then run `$CNODE_HOME/scripts/cabal-build-all.sh -o` but it does not help me fix this issue.

Any clues?
