### ISSUE TITLE
[BUG] -  KES period not displayed in live view 

### ISSUE THREAD

**Issue by glitch40** [input-output-hk/cardano-node#1748]
Exernal
Release notes say KES will now be displayed in live view 
![NoKES](https://user-images.githubusercontent.com/58828847/90859603-253e1000-e34e-11ea-9c2a-9b009abb751f.png)

**System info (please complete the following information):**

Clean fresh build

- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version 1.19.0

**Comment by Crypto2099** [comment]
Can confirm, the KES metrics are not present in live view even whether running as a block producer or not.

**Comment by mrBliss** [comment]
I believe this issue has the same cause as https://github.com/input-output-hk/cardano-node/issues/1742. Closing this one in favour of the older one.
