### ISSUE TITLE
[BUG] - Withdrawing rewards documentation has wrong amount in tx-out

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#1765]
**Internal**

**Summary**
The tx-out amount in https://github.com/input-output-hk/cardano-node/blob/2c74060d02ec03c8b5a92a53447ca58c582d988c/doc/stake-pool-operations/withdraw-rewards.md#build-the-raw-transaction doesn't include the reward amount.

Should be 743882981 (194054070 + 550000000 - 171089) instead of 193882981.

**Comment by vix-io** [comment]
hi @CarlosLopezDeLara please can you have a look at this one

**Comment by CarlosLopezDeLara** [comment]
Thanks, fixed in: 

https://github.com/input-output-hk/cardano-node/pull/1893
