### ISSUE TITLE
[BUG] - chain stopped for more than 4 minutes on producer + relays

### ISSUE THREAD

**Issue by 2072** [input-output-hk/cardano-node#1769]
**Internal/External**

*External* 

**Summary**
The chain tip stopped moving for more than 240s on all of my nodes on different systems.

**Steps to reproduce**

N/A

**Expected behavior**
The chain should probably not stop for so long

**System info (please complete the following information):**
- OS: Debian
- Version [Buster]
- Node version: 1.19.0

**Screenshots and attachments**
The five nodes of my pool (ANFRA) got stuck on the same slot (and were automatically restarted independently as a result):

Block: 4,606,358 - Slot: 6,825,594 - Epoch: 213 - Epoch's slot: 172,794 - TxsProcessed: 24,775 - Uptime: 4d 10h 34' 01" - Mem: 1,722,560,512

Here are the logs of one of my relays:
[chainStuck-slot6825594-ANFRA-relay2.log.zip](https://github.com/input-output-hk/cardano-node/files/5126725/chainStuck-slot6825594-ANFRA-relay2.log.zip)

**Comment by 2072** [comment]
Ok so checking the explorer we can see that this really happened globally :

- [block 4606358](https://explorer.cardano.org/en/block?id=84cd8dc08019642537a15b01b5678d3de469bd8caa4c6a418c67347a00216cce) made on 2020/08/25 21:44:45 UTC
[block 4606359](https://explorer.cardano.org/en/block?id=937554715db9242c7d1693bc668991bec3f1b6d13bd4bf71548731fd14f3a2fe) made on 2020/08/25 21:49:27 UTC

**Comment by johnalotoski** [comment]
Related JIRA ticket: https://jira.iohk.io/browse/CAD-1747

**Comment by cybershaman73** [comment]
This condition was observed again today. It appears to happen exactly 48hrs after each epoch boundary. Took place across all nodes in my pool. Outage lasts for about 2min. During this time chain density metric from Prometheus also shows a steep vertical drop. Sometimes also accompanied by a burst of TX through mempool ~ 25.

**Comment by vix-io** [comment]
We've identified this is a performance problem and the fix should be in the next release (1.20). Please confirm if this is resolved next week (after the release)

**Comment by aaastakepool** [comment]
From what I understand still happening with cardano-node v1.20

**Comment by erikd** [comment]
@aaastakepool Correct!

**Comment by tatyanavych** [comment]
Resolved in 1.21.0
https://github.com/input-output-hk/cardano-ledger-specs/pull/1881

**Comment by Jimbo4350** [comment]
Appears to be resolved in JIRA so I'm closing this issue.
