### ISSUE TITLE
[BUG] - "Making a Shelley blockchain from scratch documentation" Possible issue with issue-op-cert instructions

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#1772]
**Internal**

**Summary**
When following the [Making a Shelley blockchain from scratch](https://docs.cardano.org/projects/cardano-node/en/latest/reference/shelley-genesis.html) documentation exactly using the "Making a genesis file semi-automagically" method, I get the error:

```
/private/var/folders/zh/ln41q4zs52x2fd61rxccmq640000gn/T/chairman-shelley/test-51df8de34042bbee/genesis/delegate-keys/delegate-opcert1.counter: /private/var/folders/zh/ln41q4zs52x2fd61rxccmq640000gn/T/chairman-shelley/test-51df8de34042bbee/genesis/delegate-keys/delegate-opcert1.counter: openBinaryFile: does not exist (No such file or directory)
```

When I use the "Making a genesis file semi-automagically" method, 

**Steps to reproduce**

Follow the documenting, electing the "Making a genesis file semi-automagically" method.

When running the following command:

```bash
cardano-cli shelley node issue-op-cert \
    --hot-kes-verification-key-file example/node1/kes.vkey \
    --cold-signing-key-file example/delegate-keys/delegate1.skey \
    --operational-certificate-issue-counter example/delegate-keys/delegate-opcert1.counter \
    --kes-period 0 \
    --out-file example/node1/cert
```

I get the error:

```
/private/var/folders/zh/ln41q4zs52x2fd61rxccmq640000gn/T/chairman-shelley/test-51df8de34042bbee/genesis/delegate-keys/delegate-opcert1.counter: /private/var/folders/zh/ln41q4zs52x2fd61rxccmq640000gn/T/chairman-shelley/test-51df8de34042bbee/genesis/delegate-keys/delegate-opcert1.counter: openBinaryFile: does not exist (No such file or directory)
```

Earlier in the document, the following convention is mentioned for `counter` files:

```
${genesisdir}/delegate-keys/delegate-opcert${N}.counter
```

So this *should* work.  However, when I look inside the `genesis/delegate-keys` directory, I don't see such files:

```
ls /private/var/folders/zh/ln41q4zs52x2fd61rxccmq640000gn/T/chairman-shelley/test-f9b95b9763c52f6a/genesis/delegate-keys
delegate1.counter  delegate1.vkey     delegate1.vrf.vkey delegate2.skey     delegate2.vrf.skey delegate3.counter  delegate3.vkey     delegate3.vrf.vkey
delegate1.skey     delegate1.vrf.skey delegate2.counter  delegate2.vkey     delegate2.vrf.vkey delegate3.skey     delegate3.vrf.skey
```

Instead I see files of the form:

```
${genesisdir}/delegate-keys/delegate${N}.counter
```

Presumably a filename convention change at some point in the project's history broke the documentation.

**Expected behavior**
I inspect no errors when following the documentation

**System info (please complete the following information):**
- OS: MacOS, Catalina
- Node version: 1.19.0 from `master`

**Screenshots and attachments**
N/A

**Additional context**
N/A

**Comment by vix-io** [comment]
hi @CarlosLopezDeLara any updates on this one?

**Comment by CarlosLopezDeLara** [comment]
Closing in favor of https://github.com/input-output-hk/cardano-node/issues/3047
