### ISSUE TITLE
[FR] - auto delegate to a new pool when pool is retiring and user does not redelegate

### ISSUE THREAD

**Issue by matiwinnetou** [input-output-hk/cardano-node#1785]
Some pools are retiring and it would be good if chain auto-delegates to a random pool (where probability to produce at least one block is in a given epoch is 100%).

Such auto-delegation should be done if user fails to delegate manually e.g. 1 day before end of the epoch (or some number of slots before end of the epoch).

**Comment by rdlrt** [comment]
`auto-delegates to a random pool` - not everyone is happy for wallets to take decision on their behalf 😄 

Besides, this feature request is something you're looking towards Daedalus - instead of `cardano-node` 😉

**Comment by kevinhammond** [comment]
Passed on to @darko-mijic

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
