### ISSUE TITLE
[BUG] - Repeated Block Divergence

### ISSUE THREAD

**Issue by craigem** [input-output-hk/cardano-node#1831]
**Internal**
*Internal*   

**Summary**
One single node is consuming ~20% of RAM and diverging from the block chain. After `cardano-node` is restarted, it diverges again in ~30 minutes. There are 2902 of these errors in the logs for the period of interest:

```
Sep 10 02:58:57 rel-f-1 bkq29mskw06923wqfnlf1554mmg59qhz-unit-script-cardano-node-start[22397]: Error: Switchboard's queue full, dropping log items!
```

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Single node exhibiting the behaviour

**Expected behaviour**
No block divergence.

**System info (please complete the following information):**
- OS: NixOS
- Version: 20.03
- Node version: 1.19.1

**Screenshots and attachments**
- Logs attached

**Additional context**
None.

[rel-f-1-20200910.log.gz](https://github.com/input-output-hk/cardano-node/files/5199034/rel-f-1-20200910.log.gz)

**Comment by CodiePP** [comment]
the log file contains these entries (with counts):

    * BadInputsUTxO 53764
    * ExpiredUTxO 12
    * HardForkApplyTxErrWrongEra 8
    * MeasureTxsTimeStart 637
    * StakeKeyInRewardsDELEG 5105
    * TraceMempoolAddedTx 633
    * TraceMempoolRemoveTxs 336
    * WithdrawalsNotInRewardsDELEGS 4926

something went wrong. Byron txs rejected in Shelley mode. More transactions rejected due to missing inputs. ...
may I ask in which environment this node was running?

**Comment by CodiePP** [comment]
The message "Error: Switchboard's queue full, dropping log items!" is just to signal that too many log items were received and the system is going to drop further ones. This is just a consequence of the bursts of messages it received, or that the log sink was busy and the logging system was not able to output log items.

**Comment by CodiePP** [comment]
the maximum was 87 messages per second. the logging system should be able to handle this load. so I assume the output was blocking and creating the back pressure at some point.

**Comment by craigem** [comment]
> something went wrong. Byron txs rejected in Shelley mode. More transactions rejected due to missing inputs. ...
> may I ask in which environment this node was running?

Mainnet.

**Comment by craigem** [comment]
Probably a duplicate of #1769 - closing.
