### ISSUE TITLE
Update README cardano-cli section

### ISSUE THREAD

**Issue by tatyanavych** [input-output-hk/cardano-node#1837]
Top level [README.rst cardano-cli](https://github.com/input-output-hk/cardano-node/blob/master/README.rst#cardano-cli) has obsolete content. To reduce maintenance of this page replace this obsolete content with link to the [cardano-cli component README.md](https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/README.md) where CLI documentation should be up to date.

**Comment by Jimbo4350** [comment]
This has been resolved in `master`
