### ISSUE TITLE
[FR] - GenTx out of `cardano-api`'s signed transactions

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1853]
**Internal**

**Describe the feature you'd like**

Because the transaction generator runs a TxSubmission protocol peer, it has to use its type language, which includes `GenTx blk`. Internally the generator uses `cardano-api`'s `Tx era` type.

This feature would apparently require two components:

1. A function like `toGenTx :: Mode mode era -> Tx era -> GenTx (BlockOf era)`, that would do term-level conversion.
2. A type family like `BlockOf`, relating the `cardano-api`-level eras to `ouroboros-network` block type (similar to #1859, #1861).

Note that (similarly to #1858, #1859 & #1861) the type of the first argument (the indexed GADT Mode) does not currently exist in cardano-api -- but exists in the generator.

Also, just an as aside, the era types could be strongly kinded, if we defined `cardano-api`'s `Byron` and `Shelley` via `DataKinds`.

This function is currently implemented in the generator as:

```haskell
toGenTx :: Mode mode era -> Tx era -> GenTx (HFCBlockOf mode)
toGenTx ModeShelley{}        (ShelleyTx tx) = inject $ Shelley.mkShelleyTx tx
toGenTx ModeByron{}          (ByronTx tx)   = inject $ normalByronTxToGenTx tx
toGenTx ModeCardanoShelley{} (ShelleyTx tx) = GenTxShelley $ Shelley.mkShelleyTx tx
toGenTx ModeCardanoByron{}   (ByronTx tx)   = GenTxByron   $ normalByronTxToGenTx tx
```

**Describe alternatives you've considered**

The potential alternative would be to somehow just avoid touching `ouroboros-network`-level types -- however, since we implement our `TxSubmissionClient`, we have to speak the protocol type language, which uses `GenTx` and `GenTxId`,
which are, in turn, indexed by the block type.

So, this appears to be unavoidable, at least to a certain degree.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
