### ISSUE TITLE
[FR] - Extend `cardano-api`'s `makeSignedTransaction` to also allow metadata or payload in Byron case

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1854]
**Internal**

**Describe the feature you'd like**

The Byron case in `cardano-api`'s `makeSignedTransaction` has no provisions for metadata at all.

The transaction generator needs to insert arbitrary bytestring payload into transactions, but doesn't really cares much about specifics.

The way the generator currently does this for in Byron case is: https://github.com/input-output-hk/cardano-benchmarking/blob/master/cardano-tx-generator/src/Cardano/Benchmarking/GeneratorTx/Tx.hs#L183-L225

A specific API is intentionally not requested here -- only a requirement that the Byron case is extended to allow arbitrary bytestring payload.

**Describe alternatives you've considered**

The design space for the implementation of this requirement is intentionally left open.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
