### ISSUE TITLE
[FR] - Text -> Address era in `cardano-api`

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1857]
**Internal**

**Describe the feature you'd like**

Era-agnostic address parsing: `parseAddress :: Era era -> Text -> Address era`.

This, again, depends on an indexed GADT for the era, which is currently absent from `cardano-api`, but is used in the generator.

This is currently implemented in the generator as:
```haskell
parseAddress = \case
  EraByron ->
    either (panic . ("Bad Base58 address: " <>) . show) ByronAddress
    . decodeAddressBase58
  EraShelley -> \addr ->
    fromMaybe (panic $ "Bad Shelley address: " <> addr) $
    deserialiseAddress AsShelleyAddress addr
```

**Comment by Jimbo4350** [comment]
@deepfire  does this meet your requirement: https://github.com/input-output-hk/cardano-node/blob/62faef386d83597ccfcac79783fd388d5215ff24/cardano-api/src/Cardano/Api/Address.hs#L110

**Comment by deepfire** [comment]
@Jimbo4350, that should work now -- although we'd have to maintain an internal type-level map of era -> address type.

**Comment by deepfire** [comment]
cc @MarcFontaine
