### ISSUE TITLE
[FR] - Casting `Tx era` to `TxForMode mode`

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1858]
**Internal**

**Describe the feature you'd like**

A `cardano-api` function with a signature similar to: `castTxMode :: Mode mode era -> Tx era -> TxForMode mode`.

Note that (similarly to #1853, #1859, #1861) the type of the first argument (the indexed GADT  `Mode`) does not currently exist in `cardano-api` -- but exists in the generator.

This function is currently implemented in the generator as:

```haskell
castTxMode ModeByron{}          tx@ByronTx{}   = TxForByronMode  tx
castTxMode ModeShelley{}        tx@ShelleyTx{} = TxForShelleyMode tx
castTxMode ModeCardanoByron{}   tx@ByronTx{}   = TxForCardanoMode $ Left tx
castTxMode ModeCardanoShelley{} tx@ShelleyTx{} = TxForCardanoMode $ Right tx
```

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
