### ISSUE TITLE
[FR] - `cardano-cli shelley genesis` subcommand for genesis staking 

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1876]
**Internal**

**Describe the feature you'd like**

Context:  we need to create real-world blockchain states, with the current interest being in:
- large UTxO (millions of entries)
- large number of stake pools (thousands)
- large number of staking keys (hundreds of thousands)

It's impractical to build up this state dynamically (i.e. via blockchain interaction) -- hence we go for an existing static solution -- the genesis-specified staking & delegation.

Now, the current approach the benchmarking team takes to construction of this genesis is iterative buildup in a `bash` script [1].
This clearly wouldn't scale to our new size requirements -- as even the complete genesis JSON file itself is estimated to be near 1GiB -- so we can clearly see the quadratic costs of iterative (read-modify-write) construction being prohibitive.

The proposed solution is to extend `cardano-cli shelley genesis` with a new subcommand (say, `create-staked`) to perform this as a single operation.

This subcommand would:
  - generate credentials for `K` stake pools (KES, VRF, cold keys, reg. certificate)
  - generate credentials for `L` delegators (payment & stake keys)
  - generate the initial funds belonging to the delegators, with `M` lovelace per delegator
  - build the stake pool registration map
  - build the genesis staking map
  - stub out pool metadata
  - generate genesis, extending code that currently implements `cardano-cli shelley genesis create`

It would be parametrised, in particular, by:
  - `--gen-pools K`
  - `--gen-delegators L`
  - `--delegators-stake-share F`, to specify a fraction of total supply to evenly distribute among all delegator keys -- and thus, indirectly specifying the `M` discussed above,
  - `--gen-utxo-keys N`, to specify number of non-delegating genesis UTxO keys to generate -- those will get the rest of supply -- i.e. `(1 - F) * totalSupply)`
  - some usual parameters from `shelley genesis create`, like total supply, start time etc.  

-- 
1. https://github.com/input-output-hk/cardano-benchmarking/blob/master/benchmarks/shelley3pools/prepare_genesis_shelley_staked.sh

**Comment by deepfire** [comment]
The benchmarking team is ready to implement this.

**Comment by deepfire** [comment]
https://github.com/input-output-hk/cardano-node/tree/cad-1878-cli-staked-genesis is WIP implementation.

**Comment by Jimbo4350** [comment]
Closing as this was implemented in #2052
