### ISSUE TITLE
[Validation Query] - In absence of native HA support for core nodes, any risks foreseen due to use of haproxy?

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-node#1883]
**Internal/External**
*External* 

**Background**

Given that `cardano-node` does not provide a native way to perform HA, we're thinking about testing and implementing an external solution based on haproxy, especially given that #1132 has been delayed indefinitely.

(PS: Previous feature request #1273  for native support didnt receive any ack, so assuming that's not on priority list for next few months)

Note that the intention is not to have more availability or reduce maintainance windows , but to have redundancy for core nodes.

We're looking at adding some sample instructions to SPOs in [guild-operators docos](https://cardano-community.github.io/guild-operators) for allowing their relay nodes to point to a local haproxy IP:port bound service, which could map out to active/passive connection to multiple cores.

Sample relevant haproxy frontend/backend would be:
```
frontend app
  bind 127.0.0.1:6000
  default_backend cnode_core
                                
backend cnode_core
  balance source
  server c1 IP1:6000 check
  server c2 IP2:6000 check backup
```

Each of the relay node would connect locally to a ha proxy service and get redirected to active core node to fetch blocks.

The only edge-case/disadvantage we could think of was when if there is a block created right before an outage on active core node, it could potentially result in a temporary fork branch that should be resolved automatically. But the advantage from HA far outweighs a short inconvenience from unintentionally created fork during edge case scenario. The blocks from passive core wouldn't be pulled unless there is really an outage

**Question**

Is this a viable approach? Do the developers foresee any issues with the approach (eg: rollbacks on backup node)?

**Comment by rdlrt** [comment]
Guessing no alarms yet - is as good a response I can expect to proceed , especially having run this for a few days now 😉

**Comment by cyber-russ** [comment]
We are using guild tools, running active-passive clusters 2 x (2 relays + core). Fail over is manual on firewall (NAT rules) also requiring core node config change to block producing on passive cluster (some customisation of the standard scripts). The downtime is sub minute with 1.20 as the passive cluster is fully synced. The positive is that the passive cluster is available to upgrade and patch with zero impact to operations.
Would HA proxy give a significant advantage? Have you just created a new single point of failure?

**Comment by rdlrt** [comment]
@cyber-russ 

> Have you just created a new single point of failure?

No, there is no single point of failure - that's the basic thought process behind issue description. HAProxy is run on *each* relay , and points as same config pointing to two core nodes, only one of which is active at a time.

You doing manual failover sounds like you're talking about maintenance. Failover goes far beyond you knowing the constraints or downtime (eg: host VM having an outage while you're not around to take action)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.

**Comment by rdlrt** [comment]
relevant

**Comment by CLAWSonSTAKE** [comment]
I don't see why this wasn't reopened when the request was given as suggested. Closely related ticket https://github.com/IntersectMBO/cardano-node/issues/1273, I'm still yet to find a good explanation why either wouldn't be a relevant issue to keep open.
