### ISSUE TITLE
[BUG] - Obscure log messages

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1885]
**Internal/External**
*Internal*   if an IOHK staff member.

**Summary**
`cardano.node.ForgeTime` has a bunch of `fromList []` logged that really don't give any useful information. This should be fixed in the next release (either put a message in that makes sense or drop the message).

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by gufmar** [comment]
Might add here, `MaximumVerbosity` does write invalid JSON

`{"at":"2020-09-19T21:41:02.34Z","env":"1.19.1:497af","ns":["cardano.node.ChainDB"],"data":{"kind":"TraceAddBlockEvent.AddedToCurrentChain","newtip":"1ab74bdc202bdda86aecefee805829c3d08ea7a0ed7c2ab898ad6a999f7f3da7@8985371","headers":[{"hash":"HashHeader {unHashHeader = "1ab74bdc202bdda86aecefee805829c3d08ea7a0ed7c2ab898ad6a999f7f3da7"}","kind":"ShelleyBlock","blockNo":"4712349","slotNo":"8985371"}]},"app":[],"msg":"","pid":"969319","loc":null,"host":"ubs32","sev":"Notice","thread":"563"}`

The HashHeader Part seems to need some escaping of the {unHasHeader ... } part.

**Comment by disassembler** [comment]
This hasn't improved with 1.21.1. It's added a few messages between the `fromList` messages but the `fromList` messages still show up in the logs.

**Comment by Jimbo4350** [comment]
> This hasn't improved with 1.21.1. It's added a few messages between the fromList messages but the fromList messages still show up in the logs.
@disassembler  you paste an example of any useful messages `cardano.node.ForgeTime` outputs? Has it ever given any useful output?

**Comment by Scitz0** [comment]
This is still an issue on 1.24.2. Every second you get a block of messages like this:
`{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.LeadershipCheck.metrics"],"data":{"kind":"LogValue","value":{"tag":"PureI","contents":780105},"name":"utxoSize"},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Notice","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.LeadershipCheck.metrics"],"data":{"kind":"LogValue","value":{"tag":"PureI","contents":102012},"name":"delegMapSize"},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Notice","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.LeadershipCheck"],"data":{"credentials":"Cardano","kind":"TraceStartLeadershipCheck","delegMapSize":102012,"slot":16590669,"chainDensity":4.771165e-2,"utxoSize":780105},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Info","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.ForgeTime"],"data":{},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Info","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.ForgeTime"],"data":{},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Info","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.ForgeTime"],"data":{},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Info","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.ForgeTime"],"data":{},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Info","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.Forge"],"data":{"credentials":"Cardano","val":{"kind":"TraceNodeNotLeader","slot":16590669}},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Info","thread":"57"}
{"at":"2020-12-16T22:16:00.00Z","env":"1.24.2:400d1","ns":["cardano.node.ForgeTime"],"data":{},"app":[],"msg":"","pid":"32679","loc":null,"host":"cnode-ma","sev":"Info","thread":"57"}`

**Comment by gitmachtl** [comment]
This Problem still exists in 1.25.1:

![image](https://user-images.githubusercontent.com/47434720/106454314-d7940a80-648a-11eb-9a1a-91413e79b253.png)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
