### ISSUE TITLE
Unable to broadcast transaction

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-node#1887]
The era of the node and the tx do not match. The node is running in the Shelley era, but the transaction is for the Byron era.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by intricate** [comment]
Can you provide the full `cardano-cli` command you're trying to execute?

As the error message states, this error is indicative of one attempting to submit a Byron transaction while in the Shelley era. Once in the Shelley era, you can only submit Shelley transactions.

**Comment by vae520283995** [comment]
> Can you provide the full `cardano-cli` command you're trying to execute?
> 
> As the error message states, this error is indicative of one attempting to submit a Byron transaction while in the Shelley era. Once in the Shelley era, you can only submit Shelley transactions.

Thank you, I did rebuild Byron transactions, but I don't know the specific difference between Byron transactions and Shelley transactions. Is there any relevant code? No need for haskell, I'm not familiar

**Comment by intricate** [comment]
@vae520283995: You should probably look through our [docs](https://docs.cardano.org/projects/cardano-node/en/1.20.0/) to get an idea of how to use `cardano-cli` in the Shelley era.

**Comment by intricate** [comment]
Closing this issue as the presented error message is indicative of `cardano-cli` behaving correctly.

If you run into any problems, feel free to reopen this issue or raise a new one.
