### ISSUE TITLE
[BUG] - Rewards not received on rewards account of multi-owner pool

### ISSUE THREAD

**Issue by GS1973** [input-output-hk/cardano-node#1898]
Internal and External

**Summary**
In epoch 218 the pool (ALLI) minted a block. However, no rewards arrived in the rewards account of the pool in epoch 220, nor in the wallets of the delegators.

**Steps to reproduce**
1. The pool is registered with 24 owners. 
2. The stake addresses of all owners are registered in the blockchain. 
3. Also the rewards account stake address is registered in the blockchain. 
4. Pledge has been met right from the registration of the pool. 
5. The pool has been updated multiple times to add owners to the pool.

**Expected behavior**
Rewards should have been available in the stake address of the rewards account of the pool and delegators should have had rewards.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version: 1.20

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**
POOL ID: e01133b97103bb932f7be0f7896ed1ca1d0ee350e4c8058e101b73d6
POOL Rewards account stake address: stake1u9h4gp39clpznv6vjeu52ykefj48kux3ag0k6l6n4wm7efs0z5mpw

Information in the ledger:

"e01133b97103bb932f7be0f7896ed1ca1d0ee350e4c8058e101b73d6": {
                        "owners": [
                            "038cd6f7c893cd2bccd6d5bdfa272b5e6eee26787d22a1883cfce1f1",
                            "0c693056c60f34f6e650c8c77938ffb51caeeef7f732c2be03837f39",
                            "11f263c31b629b5dbb3228a9fcfce16c43916b5ea7ed42b8bae42c28",
                            "323b17e46d47e9a53c9b7d6b6a5a83ac359f448aa895238b580e69cc",
                            "3fbf919f787fa39ba46f1641d1103473b8d5b707bca860f08d3dd0fd",
                            "45360b5e35b50b373dd06b024c522e2ef370df56a44cabc19af27211",
                            "4f524f0edd0f47343be451479731144a72c78d4966806baba444fcda",
                            "5840f1817de4b11fe1b260f7b49b741ac0de67a923c384c300dff7f8",
                            "677f444c2e9db5aba81842dbb2044bce91f2b3d40c8bdd6e854be79f",
                            "719ede13dd9444fc5414b434a4b6041ff16b67a8db58a2f422cedc9b",
                            "71fbf2ac31f02a4d8c6212edd380ae51cffd3cab7ce67f53cfe827d3",
                            "7ca47b9f859c72f0b3833f669f3caccf2e7d805b4fe44db3098ba034",
                            "81b3c07d48c4ac2f972e0447a5a098ae5f2d69d4eed933d046ddd300",
                            "96ac42b172ab6d0ef122441fe7ebcf253391e94571d609ca2c71d285",
                            "972c45b68d912ba65a86f5927e3b3a5dbcc850a0791370c99a2b4530",
                            "9b3172148899c9d82d4d4be18a118a083e026a5aa220bc20368e5026",
                            "aa20e1f388cd9313c8c9819783dc0d4d06da16075cec4b67c315c38a",
                            "b7318376e7ae90aba2d521bf1b09cdb7e07fe0d139456595512e8f04",
                            "baeabff8c72821d89accfc72de27398477d65ab6840d7f818f963a99",
                            "c7ee8d6d8ce55567c66e19913a818e78ca4468c7965729c2c768b92d",
                            "cb682d6b9a8887392964f54c56d589d89a01907027f6e4feae857d1c",
                            "d02b00b357855fb2046a1d48f92a23a9bfcea36a39e87c356ac643b3",
                            "f2cc6d14086dcaae8712eebfbcd1a0bc1666017a08ac41450736d4ef",
                            "f4e5a8e10928fcb31354a7ce1ba246d4c43c13da3a46282f847a2076"
                        ],
                        "cost": 340000000,
                        "margin": 3.0e-2,
                        "publicKey": "e01133b97103bb932f7be0f7896ed1ca1d0ee350e4c8058e101b73d6",
                        "pledge": 200000000000,
                        "vrf": "26273a618cfc3e7d3193bbee2945baf64242bacbd161d0ce1d69a26d01070bd6",
                        "metadata": {
                            "hash": "bc556b4a7e7e516532eb04d0dc1f5dce60d0f15f0d5883500a09bfcc847cf13b",
                            "url": "https://raw.githubusercontent.com/GS1973/ALLI/master/ALLI.json"
                        },
                        "relays": [
                            {
                                "single host name": {
                                    "dnsName": "alli.alliancestakepools.online",
                                    "port": 3001
                                }
                            },
                            {
                                "single host name": {
                                    "dnsName": "alli.alliancestakepools.online",
                                    "port": 3002
                                }
                            }
                        ],
                        "rewardAccount": {
                            "credential": {
                                "key hash": "6f540625c7c229b34c96794512d94caa7b70d1ea1f6d7f53abb7eca6"
                            },

**Comment by staking4ada** [comment]
Being a co-owner (addr1qyrw8gqse80hd9uqgq0zlkh0rn8gfxcfhr7fux5vsuw0935pk0q86jxy4shewtsyg7j6px9wtukkn48wmyeaq3ka6vqq35uulr, stake1uxqm8srafrz2ctuh9czy0fdqnzh97ttf6nhdjv7sgmwaxqqa7dtcd) I have indeed observed the absence of any delegation or operator rewards. I have checked the pool registration commands and registrations of most owner stake addresses, and could not find any errors.

**Comment by lawale4me** [comment]
as a co-owner we ensured that pledge was met

**Comment by CarlosLopezDeLara** [comment]
From the ledger formal spec: 

Stake pool parameter updates are handled by Equation (13). This rule, which also matches
on the certificate type DCertRegPool, is distinguished from Equation (12) by the requirement that the pool be registered.

Unlike the initial stake pool registrations, the pool parameters will not change until the
next epoch, after stake distribution snapshots are taken. This gives delegators an entire
epoch to respond to changes in stake pool parameters. The staging is achieved by adding
updates to the mapping fPoolParams, which will override poolParam with new values in
the EPOCH transition.

Please see: https://hydra.iohk.io/build/4155328/download/1/ledger-spec.pdf  Figure 25, Rule 13 on page 38.

**Comment by GS1973** [comment]
Eventhough the pledge setting was changed (increased), as far as we can see the ALLI pool met all the requirements all the time for getting rewards for the produced block in epoch 218.

**Comment by MarcelKlammer** [comment]
Owner/Pledge addresses:

https://pooltool.io/address/0c693056c60f34f6e650c8c77938ffb51caeeef7f732c2be03837f39
https://pooltool.io/address/b7318376e7ae90aba2d521bf1b09cdb7e07fe0d139456595512e8f04
https://pooltool.io/address/7ca47b9f859c72f0b3833f669f3caccf2e7d805b4fe44db3098ba034
https://pooltool.io/address/f4e5a8e10928fcb31354a7ce1ba246d4c43c13da3a46282f847a2076
https://pooltool.io/address/81b3c07d48c4ac2f972e0447a5a098ae5f2d69d4eed933d046ddd300
https://pooltool.io/address/9b3172148899c9d82d4d4be18a118a083e026a5aa220bc20368e5026
https://pooltool.io/address/f2cc6d14086dcaae8712eebfbcd1a0bc1666017a08ac41450736d4ef
https://pooltool.io/address/cb682d6b9a8887392964f54c56d589d89a01907027f6e4feae857d1c
https://pooltool.io/address/45360b5e35b50b373dd06b024c522e2ef370df56a44cabc19af27211

Registered pledge: 100k

Snapshot (end of e216): 
30000 (-20000 in e217, thus not meeting pledge at time of block creationg in e218)
10000
10000
10000
10000
10000
10000
10000
10047

New owner/pledge addresses were registered in e218 and are now active in e220. Those addresses were not active in e218.
So the whole thing is an unfortunate timing issue.

**Comment by GS1973** [comment]
Thanks all of you. I think this issue can be closed.
