### ISSUE TITLE
Cannot build `exe:cardano-node` component

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#190]
I am not sure how this slipped through CI, but I get a type error in `cardano-prelude`.  I am building current master (b9ffe10)
```
cabal build exe:cardano-node
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - cardano-prelude-test-0.1.0.0 (lib) (first run)
 - cardano-binary-test-1.3.0 (lib) (configuration changed)
 - cardano-crypto-test-1.3.0 (lib) (configuration changed)
 - cardano-ledger-test-1.3.0 (lib) (configuration changed)
 - ouroboros-consensus-0.1.0.0 (lib) (configuration changed)
 - cardano-node-3.0.1.87 (lib) (configuration changed)
 - cardano-node-3.0.1.87 (exe:cardano-node) (configuration changed)
Preprocessing library for cardano-prelude-test-0.1.0.0..
Building library for cardano-prelude-test-0.1.0.0..
[3 of 9] Compiling Test.Cardano.Prelude.Golden ( Test/Cardano/Prelude/Golden.hs, /home/marcin/r
epos/iohk/cardano-node/dist-newstyle/build/x86_64-linux/ghc-8.6.5/cardano-prelude-test-0.1.0.0/
build/Test/Cardano/Prelude/Golden.o ) [Hedgehog.Internal.TH changed]

Test/Cardano/Prelude/Golden.hs:119:15: error:
    Not in scope: ‘confTrailingNewline’
    |
119 |             , confTrailingNewline = False
    |               ^^^^^^^^^^^^^^^^^^^
cabal: Failed to build cardano-prelude-test-0.1.0.0 (which is required by
exe:cardano-node from cardano-node-3.0.1.87).
```

**Comment by erikd** [comment]
I see this too. This suggests that CI is not building everything or not running all the tests. We really need to fix that.

**Comment by erikd** [comment]
Just tested with `stack` and its fine, so I suspect this is a package versioning issue. Once CI is fixed to catch this, this should be fixed by forcing the use of the latest version in the `stack.yaml` file.

**Comment by deepfire** [comment]
@coot, there has been a couple of updates to the `master` branch, and they both build.

Can you recheck with `cabal new-clean`?

**Comment by erikd** [comment]
That PR will not fix it.

The problem is that for some dependency (I don't know which) Stackage is specifying one version and cabal an incompatible version. IMO the fix is to force `stack` to use the same package version as cabal and fix the code.

**Comment by erikd** [comment]
I can't reproduce this any more. Can we close it?

**Comment by coot** [comment]
It does build now :tada:
