### ISSUE TITLE
[FR] - `cardano-node` to produce ledger state dumps at specified block/slot numbers

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-node#1906]
**Internal**

**Describe the feature you'd like**
The ledger state dumps obtained from the cli, `cardano-cli shelley query ledger-state`, are extremely helpful for diagnosing issues.  There is currently no way, however, to create one from a previous point in time. I would love a way to configure `cardano-node` with a list of block numbers (or slot numbers), so that when the node processes one of these blocks, it automatically produces a ledger state dump for the resulting state (either before or after applying the block). Then to diagnose a problem, one could delete the local database and replay the blocks from genesis. If the block could also be logged that would be even better.  I realize that if people used this to specify blocks in the future, they could end up with a state dump from a block that was rolled back, so there might need to be a warning that blocks need to be stable if the state is to be trusted.

**Comment by dcoutts** [comment]
Alternatively we could try to make this easy enough to do with the cardano-api, by extending it to cover ledger state things.

**Comment by mrBliss** [comment]
@dcoutts Related issue for consensus: https://github.com/input-output-hk/ouroboros-network/issues/2826

**Comment by JaredCorduan** [comment]
We will be doing as @dcoutts suggested above, and it will be quite easy to modify the [demos](https://github.com/input-output-hk/cardano-node/tree/master/cardano-client-demo) to write custom diagnostic tools (using the `foldBlocks` method that will be merged soon). I've already used it, it is wonderful and is everything that I was hoping for. :)
