### ISSUE TITLE
[documentation] Documentation clarification

### ISSUE THREAD

**Issue by MokhFn** [input-output-hk/cardano-node#1917]
Hello,

On the [6. Key Evolving Signature and KES period](https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/KES_period.html) documentation page, there is an example below explaining how to compute the current period.
The example showed a "slotNo": 8520857, the textual explanation however, used another value, 906185.
This is obviously minor, but still might be misleading, or simply not clean.

Happy to contribute, and translate to French if needed.

Thanks,
Mokhtar

**Comment by intricate** [comment]
Thanks for pointing this out. 

It appears that the change from `906185` to `8520857` was introduced by https://github.com/input-output-hk/cardano-node/pull/1843. The author of that PR must have overlooked the remaining `906185` value.
