### ISSUE TITLE
[BUG] - Pool and BFT nodes block propagation delay

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1926]
**Internal/External**
*Internal*   if an IOHK staff member.

**Summary**
CPU usage seems to continuously increase and BFT nodes and pools start getting missed blocks because they take too long to propagate. This is on 1.20 although had issues with 1.19 as well. We've specifically noticed this on IOG managed nodes.

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by vhulchenko-iohk** [comment]
@disassembler, could you please provide us with more details on this?

**Comment by johnalotoski** [comment]
Internal notes added here: https://jira.iohk.io/browse/CAD-2002

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
