### ISSUE TITLE
[BUG] - cardano-api Haddock build failure

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1931]
**Internal**

**Summary**
Haddock fails to parse `src/Cardano/Api/Byron.hs`:

```
src/Cardano/Api/Byron.hs:16:1: error: parse error on input ‘import’
   |
16 | import           Cardano.Api.Protocol.Byron (mkSomeNodeClientProtocolByron)
   | ^^^^^^
```

**Steps to reproduce**
1. Node rev `872447ab61deaf70807d538d03f80ea2c07ffcff`
2. trigger build of haddocks for `cardano-api`

**Comment by mrBliss** [comment]
I believe this is caused by the following Haddock docstring preceding the import instead of the module itself:
https://github.com/input-output-hk/cardano-node/blob/4653b50747a80eba2ab1becd6be22584840ebfae/cardano-api/src/Cardano/Api/Byron.hs#L10-L16
