### ISSUE TITLE
DoS attack is possible if VRF key is known

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#1936]
It is the case that if the VRF key is compromised, the slot leader schedule will be known by the attacker. The VRF key must also be changed after a compromise, but there is some latency involved. The VRF key must be changed by re-registering the stake pool, and this takes a full epoch before it becomes active. In the meantime the attacker knows in which slots the node will be the leader and so can time a DoS attack to be most effective.

As minor mitigation, the VRF key should be readable only to the node process, to protect from unprivileged local users.

We will have the node check the file permissions of the VRF key on startup, requiring that it be readable only to the user account the node runs as.

**Comment by dcoutts** [comment]
To be clear: this is a check to make sure the user has not misconfigured things. We want to fail loudly if the user has messed this up and tell them what they need to fix.

**Comment by mark-stopka** [comment]
When your VRF is compromised, I don't think DoS of a single node, but rather the ability of an attacker to produce his own blocks (for said compromised node) should be the concern...

Adding a check that the file is owned and read-only by the `cardano-node` user should be sufficient, same method is applied in OpenSSH for keys... The problem with this in a `deamonized` environment is that you usually check it only at start-up so if someone messes up during a node runtime, it it usually not detected, but I would not consider that to be a major issue...

**Comment by mark-stopka** [comment]
Back-ported into my **cardano-node** version `1.21.1` in https://github.com/2nd-Layer/docker-hub-cardano-images/commit/df090d333a286bc866a940854fa7d19cafeb9084
