### ISSUE TITLE
[FR] Split lib:cardano-node and lib:cardano-node-config

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#1941]
Currently `lib:cardano-node` and `lib:cardano-node-config` share `hs-source-dir` and some of the modules. Instead, `lib:cardano-node` should depend on `lib:cardano-node-config`.

**Comment by mark-stopka** [comment]
@mimi1vx, this will probably impact our OBS effort?

**Comment by Jimbo4350** [comment]
`cardano-node-config` was removed some time ago so I'm closing this.
