### ISSUE TITLE
[FR] - IP addresses in logfiles

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/cardano-node#2021]
*External* 

**Describe the feature you'd like**
for every in/outgoing data transfer (block or TX) it would be useful to have the remote peers IP-address in the logfiles

Ideally, everything runs smoothly, but in case of unexpected behaviour, potential security problems/attacks, debugging, performance tracking, etc., it is definitely important for the pool operator to know which data comes from which remote station or is sent to which remote station exactly.

**Additional context / screenshots**
Debugging causes and sources of logged badInputUtxO warnings [2020] would be easier when noted together with the remote peers IP

**Comment by disassembler** [comment]
If this is added, I'd want it to be a flag in the config file to toggle on/off defaulted to off.

**Comment by karknu** [comment]
> If this is added, I'd want it to be a flag in the config file to toggle on/off defaulted to off.

Why wouldn't you want it enabled always?

**Comment by gufmar** [comment]
is available now for block propagation
