### ISSUE TITLE
[BUG] - cardano-cli didn't support command shelley block

### ISSUE THREAD

**Issue by jaslin-W** [input-output-hk/cardano-node#2036]
cardano-cli 1.21.2 doesn't support the command `cardano-cli shelley block`
But the doc says it supports
![Screen Shot 2020-10-29 at 18 16 39](https://user-images.githubusercontent.com/65018397/97555320-f2319000-1a12-11eb-8cc7-e4d685513b8e.png)
![Screen Shot 2020-10-29 at 18 18 26](https://user-images.githubusercontent.com/65018397/97555499-273de280-1a13-11eb-9f46-102fde8b6390.png)

**Comment by intricate** [comment]
Thanks for pointing that out. It looks like we were originally planning to have some sub-commands such as `block` and `system`, but they ended up being unnecessary and were removed as part of https://github.com/input-output-hk/cardano-node/commit/4c2c141fc99d38e22011450f78a4e43f9497c85d.

We'll need to update the docs to reflect that.

**Comment by Jimbo4350** [comment]
The docs were updated
