### ISSUE TITLE
[BUG] - Node fails to create socket file in chairman test

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#2045]
**Internal**

**Summary**
Node fails to create socket file in chairman test.  This happens sporadically.

**Steps to reproduce**

Run the chairman test numerous times.  Eventually the chairman tests will fail with something like:

```
              387 ┃     _spocketSystemNameFile <- H.noteShow $ IO.sprocketSystemName sprocket
                  ┃     │ "/home/runner/work/_temp/chairman/test-b1ffca6156adae75/socket/node-praos1"
                  ┃     │ "/home/runner/work/_temp/chairman/test-b1ffca6156adae75/socket/node-praos2"
              388 ┃     H.assertByDeadlineM deadline $ H.doesSprocketExist sprocket
                  ┃     │ 2020-11-02 04:28:12.530441065 UTC
                  ┃     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  ┃     │ Condition not met by deadline
```

This indicates that the chairman tests expects the node to create a socket file, but the socket file was not created within `90` seconds of node start up.

In the above example the socket, the assertion happened after checking `socket/node-praos2`, so it was `socket/node-praos2` that was missing.  In other words, `socket/node-praos1` was found to exist, but `socket/node-praos2` was not.

**Expected behavior**
Every node should create a socket file.

**System info (please complete the following information):**
- OS: All operating systems.
- Version: All versions
- Node version: `1.22.1`

**Screenshots and attachments**
Configuration and logs for the runs can be download from artefacts associated with the build failure.

The following are examples of failure:

* https://github.com/input-output-hk/cardano-node/pull/2042/checks?check_run_id=1340187981
* https://github.com/input-output-hk/cardano-node/pull/2048/checks?check_run_id=1345688998
* https://github.com/input-output-hk/cardano-node/pull/2043/checks?check_run_id=1350360663
* https://github.com/input-output-hk/cardano-node/pull/2048/checks?check_run_id=1377825337

**Additional context**
None.

**Comment by newhoggy** [comment]
It is possible, but not easy, to reproduce this locally.  I attempted this, by putting the test in a loop and it only triggered after the 51st attempt.  For example:

```
for x in {1..100}; do echo "=== $x ===";cabal test cardano-node-chairman; done
```

To speed up the test, I deleted all the code in the `chairmanOver` function because `chairmanOver` happens after the socket file exists assertion.

**Comment by newhoggy** [comment]
Presently the chairman test depends on the socket file test.  Removing the socket file test causes the chairman test to nearly always fail because without it, the chairman process is started too early when the socket file is not created yet which causes the chairman process to fail.

**Comment by erikd** [comment]
Is it possible to wait until the socket is created?

**Comment by newhoggy** [comment]
Yes it is possible.

Currently it polls on the socket file and if it isn't there by the deadline then it raises an assertion. I could not raise the assertion.

However, the chairman will be run after the wait and will fail if the socket file is not there.

**Comment by jbax** [comment]
This is happening to me on a Windows 10 installation I'm running on Virtualbox:

```
cardano-node 1.21.1 - mingw32-x86_64 - ghc-8.6
git rev a819311473563cb2ab3cd91543cf0f63facdf43e
```

The node is fully synced and has been running for 24 hours, but the node.socket file is not being created. I've restarted the node multiple times already to no avail.

This makes it impossible to start a cardano-wallet process. If you guys want it I can upload that virtualbox image somewhere.

**Comment by jbax** [comment]
Just because I reported this, it worked. I restarted Windows 10 and the file was created this time.
