### ISSUE TITLE
[BUG] - Error querying pool list using cardano-wallet from latest master cardano-node

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#2067]
I downloaded latest master build of cardano-wallet for Mac and Linux (e.g. https://hydra.iohk.io/build/4676806), then compiled latest cardano-node (master branch) as of 3 Nov.

./cardano-wallet version
2020.10.13 (git revision: c9690481e35c9d8f422c80ea8bc0293a758eb6ac)

~/.cabal/bin/cardano-node version
cardano-node 1.22.1 - linux-x86_64 - ghc-8.6
git rev 964811db6fb6eb89a44850db3bbea10b196a2295

Once cardano-node was started and in sync:

cardano-cli shelley query tip --mainnet
{
"blockNo": 4900702,
"headerHash": "6305240b33aff2452ca0d64ce74105b8b0875ef69139035852ef75efc6d3e4aa",
"slotNo": 12793240
}

and wallet was also in sync:
[cardano-wallet.pools-engine:Info:36] [2020-11-02 23:25:44.14 UTC] Applying blocks [12793253 ... 12793253]

I attempted to get a pool list via wallet API:

curl http://localhost:8090/v2/stake-pools?stake=100000000000

at which point I received the following response:

{"code":"past_horizon","message":"Tried to convert something that is past the horizon (due to uncertainty about the next hard fork). Wait for the node to finish syncing to the hard fork. Depending on the blockchain, this process can take an unknown amount of time."}

More detail is available at the pastebin location:

https://pastebin.pl/view/4ef66d1d

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
