### ISSUE TITLE
[BUG] - Outdated script paths

### ISSUE THREAD

**Issue by xxsanzxx** [input-output-hk/cardano-node#2074]
Several scripts in the cardano-node/scripts/benchmarking folder are outdated and have old paths. Some of the examples found are:

https://github.com/input-output-hk/cardano-node/blob/master/scripts/benchmarking/common.sh#L7 - Locates lib.sh file at _${__COMMON_SRCROOT}/scripts/lib.sh_ when it should be at _${__COMMON_SRCROOT}/benchmarking/lib.sh_

https://github.com/input-output-hk/cardano-node/blob/master/scripts/benchmarking/lib.sh#L8 - Locates lib-nix.sh at _${__COMMON_SRCROOT}/scripts/lib-nix.sh_ when it should be at _${__COMMON_SRCROOT}/benchmarking/lib-nix.sh_

**Comment by nankeen** [comment]
To add to this I think the extra directory depth caused this to be set to `scripts/` when it probably wants the source root. This line sets it to `cardano-node/scripts`

https://github.com/input-output-hk/cardano-node/blob/62485960494d914f8efd06ed0d8357d41a8f9d26/scripts/benchmarking/common.sh#L6

Which causes this to reference `scripts/scripts`

https://github.com/input-output-hk/cardano-node/blob/62485960494d914f8efd06ed0d8357d41a8f9d26/scripts/benchmarking/common.sh#L122

**Comment by Jimbo4350** [comment]
cc: @deepfire

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
