### ISSUE TITLE
chain-sync for a limited number of slots

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#209]
the node starts afresh and syncs blocks over the network. Once it reaches 60 minutes of CPU time the process is killed and logs analyzed.
we note:
* the time a block is included in the immutable store ("_CopiedBlockToImmDB_")
additionally, we collect counters every 30 seconds:
* network read/write bytes
* I/O read/write bytes
* memory usage
* CPU usage

**Comment by CodiePP** [comment]
@oneEdoubleD might have to look at this from perspective QA
(@alan-mcnicholas )

**Comment by ArturWieczorek** [comment]
@CodiePP Do we have some tool that records all the stats you mentioned ? If so, where we can find it, how to run it for node ?
