### ISSUE TITLE
[BUG] - Rewards are missing

### ISSUE THREAD

**Issue by peteremiljensen** [input-output-hk/cardano-node#2090]
**Summary**
Hi. We're operating the following three pools:

| | |
|------|------|
| ETO1 | [`a3e71398e80739522e907c35b8f652064e5268e62e9b78a9603f6b98`](https://cardanoscan.io/pool/a3e71398e80739522e907c35b8f652064e5268e62e9b78a9603f6b98) |
| ETO2 | [`2bf5a031b46b34c07937a769ff6f82b6a78a25c71022eaaf1f20eec9`](https://cardanoscan.io/pool/2bf5a031b46b34c07937a769ff6f82b6a78a25c71022eaaf1f20eec9) |
| ETO3 | [`32fdb90d73865d16463fe1e092c7814a9f035f781a661d9d43ed7443`](https://cardanoscan.io/pool/32fdb90d73865d16463fe1e092c7814a9f035f781a661d9d43ed7443) |

From their inceptions to epoch 227 they all shared the same owner and reward address ([`6877dcb866858b2a4941351c98cd67202262bfd82a016cbbaa073927`](https://cardanoscan.io/stakeKey/6877dcb866858b2a4941351c98cd67202262bfd82a016cbbaa073927)). This resulted in only receiving rewards from one of the pools and not all three of them. As we assumed something was wrong: We updated the pools so they all have their own reward/owner wallet. Epoch 227 is the first epoch with the update, and we've just received the rewards from that epoch; resulting in three times the amount than before. 

I hope it makes sense.
Best 
Peter Emil Jensen

**Steps to reproduce**
1. Create three pools with the same owner and rewards stake key
2. Wait until rewards are distributed
3. Observe that only one of the pools gives rewards
4. Now update 2 of the pools with their own owner and rewards stake key
5. Observe that you now receive rewards for all of them

**Expected behavior**
I would expect rewards from all three pools to be accumulated, instead of rewards from just one of them being distributed.

**System info:**
- OS: Ubuntu
- Version: 20.04
- Node version: 1.20.0

**Comment by rdlrt** [comment]
Could you clarify what is the unexpected part here?

**Comment by peteremiljensen** [comment]
Okay. I've now executed a test in a private network with 2 pools. The pools are sharing the same rewards address but different owner addresses. I'm still only receiving rewards from one of the pools. As soon as they don't share the rewards address the total received amount of the rewards are doubled. As I view it, it's not related to pledging.

I would expect multiple pools sharing the same rewards address to receive the rewards from all pools. This is how it worked in ITN.

Maybe I'm doing or expecting something wrong?

Thank you very much

**Comment by peteremiljensen** [comment]
The following is an excerpt of the rewards paid out in each epoch:

| EPOCH | Reward Addr 1  | Reward Addr 2  | Shared Reward Addr | Total          |
|-------|----------------|----------------|--------------------|----------------|
| 49    | 138,626.984079 | 169,432.980541 |                    | 308,059.96462  |
| 50    | 184,590.545244 | 129,897.050357 |                    | 314,487.595601 |
| 51    | 154,289.581026 | 130,552.722407 |                    | 284,842.303433 |
| 52    | 132,709.780181 | 127,605.557866 |                    | 260,315.338047 |
| 53    | 127,830.915687 | 58,589.169690  |                    | 186,420.085377 |
| 54    | 110,376.044306 | 115,393.137229 |                    | 225,769.181535 |
| 55    |                |                | 88,703.594680      | 88,703.594680  |
| 56    |                |                | 98,249.913365      | 98,249.913365  |
| 57    |                |                | 77,922.059291      | 77,922.059291  |
| 58    |                |                | 68,425.228861      | 68,425.228861  |
| 59    |                |                | 69,809.739657      | 69,809.739657  |
| 60    |                |                | 70,167.997113      | 70,167.997113  |
| 61    |                |                | 70,415.875564      | 70,415.875564  |

**Comment by gitmachtl** [comment]
i can confirm this, learned it the hard way last epoch on the mainnet. from the protocol standpoint it should be no issue, but i also got only rewards from one pool into the rewards-account instead of from two pools.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
