### ISSUE TITLE
[FR] - Add mechanism for new core node validation

### ISSUE THREAD

**Issue by leslieonline27** [input-output-hk/cardano-node#2095]
**Internal/External**
*External*

**Describe the feature you'd like**
Currently, although the documentation is absolutely clear and unambiguous to assist with their setups, new stake pool operators essentially have to endure the long, hard road to acquiring enough stake in their pools before they may one day be able to actually verify their ability to produce a block.  Delegators who take a chance on pools that have not yet minted are doing so out of blind faith that the pool works, is configured correctly and will eventually produce a block.  There is of course the Testnet to prove out configuration, but environmental differences can impact confidence.  It would increase confidence for SPO's, delegators and for the network as a whole if new joiners were tasked with producing a "validation block" within a set period of time after they first register, which would be published via public pools and themselves.  A single block assigned to the new pool, regardless of stake.  No rewards are received (for fairly obvious reasons) but are returned to the Treasury for future rewards.  Even though this new pool might have a tiny amount of stake, it can immediately advertise its ability to produce as proven by the network

**Describe alternatives you've considered**
- Community tools publishing Testnet performance?
- New pools being validated by bigger, more experienced operators (again probably run by the community)

Both of the above are manual workarounds which might not go far enough to instilling the confidence delegators and SPO's might desire.

**Comment by cardano-community** [comment]
Hi there,

There are a lot of considerations, I believe you might want to use [CIP](https://forum.cardano.org/t/announcement-cardano-improvement-proposals-cip1-transitioning-to-proposed-status/33213) as right target to start such a discussion perhaps?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
