### ISSUE TITLE
Cluster-based tests

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#211]
# Context

We want cluster-based integration tests for the node.

# Current scope (to be extended)

1. Cluster consensus validation: https://github.com/input-output-hk/cardano-node/issues/106
   - status: implementation mostly done
1. Extend to mixed cluster of old and new nodes, in PBFT era/mode, both producing blocks, connected via proxies: https://github.com/input-output-hk/cardano-node/issues/255
   - status: stuck debugging `cardano-sl` cluster startup
1. `cardano-byron-proxy` test:
   1. Basic functionality
   1. Heap profiling
   1. Strictness check using @edsko 's WHNF checker.
1. Cluster Tx submission

# Implementation

NixOS tests that can run a cluster in a VM are a good foundation for many of those.

This basis functionality was merged in https://github.com/input-output-hk/cardano-node/pull/177

**Comment by deepfire** [comment]
After myself trying to make `cardano-byron-proxy` serve a static chain (with no new block announcements), @avieth suggested the following:

> Byron proxy just plays the cardano-sl game: it can't download a chain unless it has the header hash of the tip. If you want it to download from a Byron peer that has a static chain, it can be done without much difficulty. Either:
> 1. you know the hash of the tip that you want, and you can patch byron-proxy to request it in particular or
> 2. patch cardano-sl to announce its tip header periodically even if it does not change

**Comment by deepfire** [comment]
So, the latest status is -- as per latest developments in https://github.com/input-output-hk/iohk-ops/tree/serge/cardano-cluster :

1. The legacy node service definition was modified to provide an instanced systemd service, allowing several legacy nodes to run on a single system -- similar as was done for the new node.
1. A new legacy cluster configuration was created in https://github.com/input-output-hk/cardano-sl/tree/serge/ci-genesis -- its keys will be supplied in https://github.com/input-output-hk/cardano-node/tree/serge/mainnet-ci
1. NTP-to-local-clocks pinning was implemented, in line with @cleverca22's suggestion.
1. The test legacy cluster still doesn't make blocks, despite full connectivity & not being in recovery mode.  There are several suspicions on why that is so.
1. In particular, @dcoutts suggested that we try starting the cluster in OBFT mode (it starts in Byron Classic mode, by default).

So the next piece of work is trying to figure out how to make the legacy cluster start in OBFT, without.

**Comment by deepfire** [comment]
There was a discussion on how to simplify #2 -- the mixed cluster, to try avoiding the issue with `cardano-sl` cluster not starting with multiple nodes sharing a single `localhost` address.

The idea was to use an existing `mainnet` cluster as the source of blocks (which are necessary for the proxy to function, as per above).

Sadly, this breaks on two points (and a half):

1. It just won't allow us simultaneous block creation on both sides of the proxy (since it'll be tied to mainnet).
2. It'll create problems with the relay taking a lot of time to sync (since it'll always be behind when it starts, unless we invent something deviously creative).
3. De-isolation -- allowing NixOS test environment talk to real mainnet -- isn't exactly trivial -- while it's definitely doable, it'll still take some work.

**Comment by deepfire** [comment]
There is a simpler option to try with `cardano-sl` potentially being stuck due to all nodes sharing `localhost` -- we can employ VDE[1] to give distinct nodes distinct, routable IP addresses.

--
1. https://github.com/virtualsquare/vde-2, available on NixOS.

**Comment by deepfire** [comment]
The VDE route almost worked.. except the routing itself became interesting -- the kernel was choosing the same route for all packets, since all `tapX` interfaces are local!

Duh!

So I'm currently playing with source routing policies: https://www.tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.rpdb.simple.html

**Comment by deepfire** [comment]
Cutting out the `network-transport-tcp` address check did the trick -- the nodes agreed to talk to each other.

However, that didn't resolve the problem with the `cardano-sl` nodes not making blocks.

Looking into switching the nodes into OBFT node right from start (they currently start in _Ouroboros Classic_ mode).

**Comment by deepfire** [comment]
Ok, so this check determines whether we're in the OBFT era:

https://github.com/input-output-hk/cardano-sl/blob/master/chain/src/Pos/Chain/Update/BlockVersionData.hs#L148

**Comment by deepfire** [comment]
So, I've made a new genesis with `BlockVersionData`'s `unlockStakeEpoch` field being equal to the magic OBFT value -- and no MPC messages appear in `cardano-sl`'s logs anymore.

No blocks being made, though.

**Comment by deepfire** [comment]
1. Cutting out the `network-transport-tcp` address check did the trick -- the nodes agreed to connect/talk to each other.

However, that didn't resolve the problem with the `cardano-sl` nodes not making blocks.

So I started looking into switching the legacy nodes into OBFT node right from start (they currently start in _Ouroboros Classic_ mode).

2. Found the OBFT era being determined by the `unlockStakeEpoch` field of `BlockVersionData`: https://github.com/input-output-hk/cardano-sl/blob/master/chain/src/Pos/Chain/Update/BlockVersionData.hs#L148

3. Regenerated genesis with `unlockStakeEpoch` being equal to the magic OBFT value -- and no MPC messages appear in cardano-sl's logs anymore, which suggests the change was effective.

No blocks, though..

**Comment by deepfire** [comment]
Ok, I've gone with the supposedly well-oiled AWS setup of `cadano-sl`, however, it somehow manages to fare _even worse_ than a cluster confined to a multi-node-on-single-machine (although, yes, there are other differences -- because the single-machine cluster required systemd service instancing and a lot of fiddling in general).

The errors `cardano-sl` gives at cluster startup is:
```
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.node.slotting:Notice:ThreadId 149] [2019-10-16 16:32:26.00 UTC] New slot has just started: 0th slot of 0th epoch
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.node.slotting:Debug:ThreadId 149] [2019-10-16 16:32:26.00 UTC] Waiting for 19993571mcs before new slot
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.node:Debug:ThreadId 142] [2019-10-16 16:32:26.00 UTC] Our tip header: GenesisBlockHeader:
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]:     hash: 1a28c5b6d7b982396995008f856640cc68fbaf923ddbde42ac232b69d972863c
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]:     previous block: 41a0739cb8cf98a176a990f8a90b2ca616e5413e2377d6c84841c46b5b6026b0
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]:     epoch: #0
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]:     difficulty: 0
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.node:Info:ThreadId 142] [2019-10-16 16:32:26.00 UTC] Difference between current slot and tip slot is: 0
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.node:Debug:ThreadId 138] [2019-10-16 16:32:26.00 UTC] There are no new confirmed update proposals for our application
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.MonadPseudoRandom:Error:ThreadId 148] [2019-10-16 16:32:26.00 UTC] rollbackSsc: most genesis block is passed to rollback
Oct 16 16:32:51 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.consolidate:Error:ThreadId 119] [2019-10-16 16:32:51.27 UTC] DBMalformed "Can't retrieve genesis block, maybe db is not initialized?"
```
Oct 16 16:32:26 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.MonadPseudoRandom:Error:ThreadId 148] [2019-10-16 16:32:26.00 UTC] rollbackSsc: most genesis block is passed to rollback
Oct 16 16:32:51 c-b-1 3n073v230xhgd46jpz4zf1n32xcqzc4c-unit-script-cardano-node-legacy-start[2961]: [cardano-sl.consolidate:Error:ThreadId 119] [2019-10-16 16:32:51.27 UTC] DBMalformed "Can't retrieve genesis block, maybe db is not initialized?"
```

There is a lead, of course.

**Comment by deepfire** [comment]
For the sake of completeness -- the way genesis is generated is via https://github.com/input-output-hk/cardano-sl/blob/master/scripts/prepare-genesis/default.nix

**Comment by Jimbo4350** [comment]
@deepfire can we close this?

**Comment by deepfire** [comment]
@Jimbo4350, I don't think so -- not all of the bullet items are done.

**Comment by CodiePP** [comment]
will be moved to cardano-benchmarking
