### ISSUE TITLE
`cardano_node_metrics_upTime_ns` metric is no longer available through Prometheus in 1.23.0

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2113]
**Internal/External**
*Internal*   if an IOHK staff member.

**Summary**
`cardano_node_metrics_upTime_ns` metric is no longer available through Prometheus in 1.23.0

**Steps to reproduce**
1. Start a node using tag no 1.23.0 
2. get the value of the `cardano_node_metrics_upTime_ns` Prometheus metric

**Expected behavior**
All existing metrics are still available.

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
```
cardano-cli 1.23.0 - linux-x86_64 - ghc-8.6
git rev eed250546fa9acec4c9de557b3e3551c1f682a30
```

**Comment by deepfire** [comment]
https://github.com/input-output-hk/cardano-node/pull/2118 implements the `cardano_node_metrics_nodeStartTime_int` metric, which carries the Unix epoch time of the node startup.
