### ISSUE TITLE
[FR] - move all Errors-messages to one single tracing namespace

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2119]
**Internal/External**
*Internal*   if an IOHK staff member.

**Describe the feature you'd like**
When dealing with node related errors, it would be ideal to have 1 single tracer that would forward all the errors (instead of enabling individual (many) tracers into the node config). 

something like `cardano.node.error.BLABLA`

**Additional context / screenshots**
In order to see in RT-View all the errors generated by the node, we need to enable many tracers into the node config (and we also are not sure we enabled all of them...). Ideally, we would have only 1 setting/tracer in the cardano node that would forward all the errors.

**Comment by denisshevchenko** [comment]
For example, right now, to be able to see DNS-related problems in RTView, this should be added in `mapBackends` section of node's configuration file:

```
      "cardano.node.DnsResolver": [
        "TraceForwarderBK"
      ],
      "cardano.node.DnsSubscription": [
        "TraceForwarderBK"
      ],
```

But of course, there are many other possible errors, and if they will be moved to one single root namespace like `cardano.node.error`, the user will be able to add only this in the configuration:

```
      "cardano.node.error": [
        "TraceForwarderBK"
      ],
```

and _all_ errors will be forwarded to RTView.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
