### ISSUE TITLE
[FR] - Add genesis file consistency checking

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#2140]
*Internal* 

The `scripts/*/mkfiles.sh` scripts generate configuration and genesis files with at least two things that prevent these configs from working in `db-sync` which has more stringent validations.

* `mkfiles.sh` does not generate the `ByronGenesisHash` or the `ShelleyGenesisHash` fields. `db-sync` validates the first but not the second (it needs to be present even if it is all zero).
* `mkfiles.sh` generates system start times in the two genesis files which do not match. Again this has been fixed in the chairman.

**Comment by dcoutts** [comment]
Similarly, the Cardano mode can only work if the Shelley genesis sets the initial major protocol version to 2.x (e.g. 2.0 or 2.1).

**Comment by dcoutts** [comment]
I think there is some existing genesis sanity checking in the consensus code (for the Cardano mode), so that is perhaps the right place to put these checks too.

**Comment by erikd** [comment]
If we supply a hash for the Shelley genesis, it would be nice to actually check that as well.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
