### ISSUE TITLE
[BUG] - ShelleyEncoderUnsupportedQuery (Ledger dump error)

### ISSUE THREAD

**Issue by dannysunrise** [input-output-hk/cardano-node#2143]
*External*   
- SPO 

**Summary**
After upgrading the node from 1.21.1 to 1.23.0, when I run the ledger dump script such as ; 
/opt/cardano/cnode# cardano-cli shelley query ledger-state --mainnet --out-file ledger-state.json

And I got following error message and ledger dump is not working which is not occurred in node 1.21.1 ;
(SomeSecond (GetCBOR DebugNewEpochState)) 

**Steps to reproduce**
1.run script 
/opt/cardano/cnode# cardano-cli shelley query ledger-state --mainnet --out-file ledger-state.json

2. See error
cardano-cli: ShelleyEncoderUnsupportedQuery (SomeSecond (GetCBOR DebugNewEpochState)) ShelleyNodeToClientVersion1

**Expected behavior**
In node 1.21.1, Ledger dump script and Leader log script are working well, not in 1.23.0

**Comment by mrBliss** [comment]
I believe you are using shelley mode (for pure Shelley testnets) instead of cardano mode (for mainnet).

Try:
```
cardano-cli cardano query ledger-state --mainnet --out-file ledger-state.json
```

**Comment by dannysunrise** [comment]
opt/cardano/cnode# cardano-cli cardano query ledger-state --mainnet --out-file ledger-state.json
Invalid argument `cardano
