### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by seriru** [input-output-hk/cardano-node#2151]
**External** SPO running XORN

**Summary**
If cardano-rt-view is restarted, the cardano-node processes won't reconnect. It looses its connection to the rt server, and won't try to reconnect. The issue is resolved by restarting the cardano-node processes.

**Steps to reproduce**
1. Restart cardano-rt-view
2. Go to cardano-rt-view web interface.
3. All cardano-node processes is in Idle state.

**Expected behavior**
The cardano-node processes should try to reconnect.

**System info (please complete the following information):**
- OS: Ubuntu, CentOS 7, and Amazon 2.
- Version Ubuntu 20.04 server LTS
- Node version 1.23.0

**Comment by denisshevchenko** [comment]
Yes, it's a bug. The corresponding issue is already opened: https://github.com/input-output-hk/cardano-rt-view/issues/109

**Comment by intricate** [comment]
Thanks @denisshevchenko. Since https://github.com/input-output-hk/cardano-rt-view/issues/109 is already an open issue, I'll be closing this one in favour of that.
