### ISSUE TITLE
[BUG] - Allegra time locking scripts appear to not be respected

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#2157]
**Internal**
**Summary**
When spending from a script address in the Allegra era, the script appears to not be respected when specifying the ADA to only be spendable after a particular slot.

**Steps to reproduce**
1. Follow instructions within `scripts/shelley-allegra/mkfiles.sh` to create an allegra era node cluster 
2. Send some ADA to a script address as follows:
Example script:
```json
{
    "scripts": [
        {
            "keyHash": "966e394a544f242081e41d1965137b1bb412ac230d40ed5407821c37",
            "type": "sig"
        },
        {
            "slot": 15000,
            "type": "after"
        }
    ],
    "type": "any"
}
```

```
cardano-cli transaction build-raw \
  --fee 0 \
  --allegra-era \
  --tx-in $(VALIDTXIN)#0\
  --tx-out $(SCRIPTADDRESS)+450000000\
  --out-file script_address_tx_body

#create witness
cardano-cli transaction witness \
  --tx-body-file script_address_tx_body \
  --signing-key-file example/addresses/user1.skey \
  --testnet-magic 42 \
  --out-file tx_witness

#assemble
cardano-cli transaction assemble \
  --tx-body-file script_address_tx_body \
  --witness-file tx_witness \
  --out-file send_to_script_address_tx

#submit
cardano-cli transaction submit \
   --cardano-mode \
   --testnet-magic 42 \
   --tx-file send_to_script_address_tx
```

3. Spend from the script address
```
cardano-cli transaction build-raw \
    --allegra-era \
    --fee 0 \
    --tx-in $(VALIDTXIN)#0 \
    --tx-out $(ADDRESS)+450000000\
    --out-file spendScriptTxBody


cardano-cli transaction witness \
  --tx-body-file spendScriptTxBody \
  --signing-key-file $(SCRIPTADDRESSSIGNINGKEYFILE) \
  --testnet-magic 42 \
  --out-file key_witness

cardano-cli transaction witness \
  --tx-body-file spendScriptTxBody \
  --script-file $(SCRIPTFILE) \
  --testnet-magic 42 \
  --out-file script_witness

cardano-cli transaction assemble \
  --tx-body-file spendScriptTxBody \
  --witness-file key_witness \
  --witness-file script_witness \
  --out-file spendMultiSig

cardano-cli transaction submit \
   --cardano-mode \
   --testnet-magic 42 \
   --tx-file spendMultiSig
```
4. The transaction will be accepted into a new block before slot `15000` even though the script specifies spending to only be allowed after slot `15000`

**Expected behavior**
The node should reject the transaction 

**System info (please complete the following information):**
- OS: Ubuntu
- Version: 20.04
- Node version: cardano-node 1.24.0 - linux-x86_64 - ghc-8.10
                         git rev db55a0c4cc94797875edfd416a21453b7a070c90
- Cli version: cardano-cli 1.24.0 - linux-x86_64 - ghc-8.10
                    git rev db55a0c4cc94797875edfd416a21453b7a070c90

**Comment by Jimbo4350** [comment]
The time locking script is also not respected if we timelock before the current slot number. We can spend the UTxO at the script address in this case (when we shouldn't be able to).

**Comment by Jimbo4350** [comment]
Closing for now as `"type": "any"` allows the UTxO to be spent regardless of time locking

**Comment by dcoutts** [comment]
Yep, our mistake. Any vs all mixup.
