### ISSUE TITLE
[BUG] -  The transaction contains inputs that do  not exist in the UTxO set

### ISSUE THREAD

**Issue by ghost** [input-output-hk/cardano-node#2172]
Idk if others who migrated from 1.21 to 1.23 run into this. After restarting the pool with the new version I get:

```
bject (fromList [("numTxs",Number 3.0),("bytes",Number 1374.0)])),("err",Object (fromList
â [("kind",String "BadInputsUTxO"),("error",String "The transaction contains inputs that do
 not exist in the UTxO set."),("consumed",Number 0.0),("badInputs",Array [Array [String "1
]",String "WithIPList SubscriptionTrace",String "LocalAddreâ ,Number 1.0]]),("produced"
```

Ips and others removed. Basically I keep getting these messages over and over on the relay node and the BP doesn't seem to even start up just hanging. I have left it like this for an hour but no change. 

System:

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

If I roll back to the old binaries the pool runs fine again. Do I need to do a full db reset on the 2 relays and the bp?

**Comment by laplasz** [comment]
same here:
```
[dell:cardano.node.Mempool:Info:712] [2021-01-24 08:16:59.77 UTC] fromList [("tx",Object (fromList [("txid",String "txid: TxId {_unTxId = \"1643e9f01df44f7646ec11e51c7eaa3a2ba049ccc2614a2f78afb5f854f12d0c\"}")])),("kind",String "TraceMempoolRejectedTx"),("mempoolSize",Object (fromList [("numTxs",Number 2.0),("bytes",Number 768.0)])),("err",Object (fromList [("kind",String "BadInputsUTxO"),("error",String "The transaction contains inputs that do not exist in the UTxO set."),("consumed",Number 0.0),("badInputs",Array [Array [String "d68c1e8264381ddeaa6e9752b20060cf323e8edeaa4ede9bfc3a91b792ebf93b",Number 0.0],Array [String "d68c1e8264381ddeaa6e9752b20060cf323e8edeaa4ede9bfc3a91b792ebf93b",Number 1.0]]),("produced",Number 1.128737903e9)]))]
```
I am getting a lot of these...after just stated the block producer node.

**Comment by steve-offutt** [comment]
I am seeing a lot of these in 1.25.1. Is this cause for concern?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
