### ISSUE TITLE
[BUG] - cardano_node_metrics_txsProcessedNum_int doesn't count the first transaction - 1.24.1

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2183]
**External**

**Summary**
The prometheus/metrics output of .cardano_node_metrics_txsProcessedNum_int shows 0 transactions after the restart, thats normal. But it also shows 0 transactions after the first transaction thru the node via a local transaction. The second transaction than counts .cardano_node_metrics_txsProcessedNum_int to 1. It goes from "null" to 0, so looks like an indexing/display problem.

**Comment by gitmachtl** [comment]
Hmm, now it worked with an additional test. I will keep an eye on that, maybe false alarm.

**Comment by deepfire** [comment]
So, this happens because https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Tracing/Metrics.hs#L143-L145 underreports the metric, by reporting its old state.

**Comment by deepfire** [comment]
Thank you @gitmachtl!

**Comment by deepfire** [comment]
Fixed in https://github.com/input-output-hk/cardano-node/pull/2192
