### ISSUE TITLE
[BUG] -  cp -p dist-newstyle/ build/x86_64-linux............ no such file or directory

### ISSUE THREAD

**Issue by stakecardano** [input-output-hk/cardano-node#2184]
*External* 

**Summary**
cant install the cardano node

**print from therminal:**
==========>ls
CODEOWNERS    bors.toml                   cardano-node                   doc
LICENSE               cabal.project             cardano-node-chairman   hedgehog-extras
Makefile                  cabal.project.local    ci                                       nix
NOTICE                  cabal.project.local~  ci-shell                              release.nix
README.rst           cardano-api              configuration                    scripts
STYLE.md              cardano-cli               default.nix                         shell.nix
Setup.hs                 cardano-config        dist-newstyle
========>cp -p dist-newstyle/build/x86_64-linux/ghc-8.10.2/cardano-node-1.24.0/x/cardano-node/build/cardano-node/cardano-node ~/.local/bin/
cp: cannot stat 'dist-newstyle/build/x86_64-linux/ghc-8.10.2/cardano-node-1.24.0/x/cardano-node/build/cardano-node/cardano-node': No such file or directory

problem is with the x86_64-linux
i can ls it
but not cd to it

=========>~/cardano-node/dist-newstyle/build$ ls
x86_64-linux
=========> ~/cardano-node/dist-newstyle/build$ cd X86_64-linux
-bash: cd: x86_64-linux: No such file or directory

**Steps to reproduce**
install node from scratch

**System info (please complete the following information):**
- OS: ubuntu
- Version 20.04
- Node version

**Comment by aromatase** [comment]
Did you ever find a fix to this?
