### ISSUE TITLE
[1.24.0] No consistency for the new tx ttl values

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2186]
**Internal/External**
*Internal*   if an IOHK staff member.

**Summary**
currently we have:
- `cardano-cli` - `--upper-bound` and `--lower-bound` 
- `db-sync` - `invalid_before` and `invalid_hereafter`
- `ledger-specs` - `validTo` and `validFrom`

**Steps to reproduce**

**Expected behavior**
We are using the same names in all places. 
The names are meaningful with clear help.

Some options: `validTo` and `validFrom`

**Comment by Jimbo4350** [comment]
The decision is to use `invalidBefore` and `invalidHereafter`
#2190

**Comment by dorin100** [comment]
`--invalid-hereafter SLOT` and `--invalid-before SLOT` were added in `1.24.2`
