### ISSUE TITLE
[1.24.1] - Some Prometheus metrics were changed 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2187]
**Internal/External**
*Internal*   if an IOHK staff member.

**Summary**
`cardano.node.Forge.metrics` and `cardano.node.ChainDB.metrics` are not working. 

EX: blocks is now `cardano_node_metrics_blockNum_int`

**Expected behavior**
All the existing metrics should continue to work OR at least provide clear and meaningful communication/documentation about what is changed. 

**Additional context**
- this might be related to https://github.com/input-output-hk/cardano-node/pull/2158

This has the potential to break the monitoring systems used by SPOs.

**Comment by gitmachtl** [comment]
I would prefer to have a clean naming scheme, having it all in cardano_node_metrics_xxx

**Comment by dcoutts** [comment]
We cannot both not change things and also make everything clean and consistent.

At some point to make the naming scheme sane we need to break and change things. We should do that, but not at the same time as people need to upgrade for a hard fork.

**Comment by disassembler** [comment]
I concur with @dcoutts. We should not break the metrics path for the hard fork and plan on making this change in a future release with a weeks warning at least to the community members that write tools that depend on these metrics.
