### ISSUE TITLE
[1.24.1] - utxo command CLI options

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2191]
**Internal/External**
*Internal*   if an IOHK staff member.

**Summary**
In the output of the `cardano-cli query utxo` command, 1 option is duplicated and many are not relevant anymore;

**Steps to reproduce**

**Expected behavior**
- `--epoch-slots` appears 2 times
- there are multiple parameters for different modes and eras that I don't know if they are relevant anymore
- if we keep `--epoch-slots` for Byron era, shouldn't we have options for the other eras too?

**System info (please complete the following information):**
```
cardano-cli 1.24.1 - linux-x86_64 - ghc-8.10
git rev 196ba716c425a0b7c75741c168f6a6d7edaee1fc
```

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/29144964/101350788-417fa180-3898-11eb-9479-f44fd6f17630.png)

**Comment by CarlosLopezDeLara** [comment]
https://input-output-rnd.slack.com/archives/G011N23CEAE/p1607090600219300?thread_ts=1607082074.211300&cid=G011N23CEAE

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
