### ISSUE TITLE
How to transform my private keys in Byron format to Shelley

### ISSUE THREAD

**Issue by zoowii** [input-output-hk/cardano-node#2198]
I have some ADA coins before Shelley. But I only have the address's keys as format (64bytes extended privatekey, 32bytes publickey, 32bytes chain code), how can I tranform the keys format to Shelley's.

`cardano-cli shelley transaction sign` command only accepts shelley's skey file. 

[https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/keys_and_addresses.html](https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/keys_and_addresses.html)

How to use the legacy skey file to sign the transaction?

**Comment by intricate** [comment]
@zoowii: Apologies for the late response. The `cardano-cli key convert-byron-key` command will allow you to convert your Byron key to a corresponding Shelley-format key.

**Comment by zoowii** [comment]
what's the file format the ` cardano-cli key convert-byron-key` accepts. I only have the raw (64bytes extended privatekey, 32bytes publickey, 32bytes chain code) hex/bytes, I generate them by code. It works in Byron era.

**Comment by Jimbo4350** [comment]
@zoowii the `convert-byron-key` accepts raw bytes.

**Comment by zoowii** [comment]
Thanks. have dealt with this problem
