### ISSUE TITLE
[FR] - Expose block production metrics even if keys missconfigured

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-node#2200]
**Internal**

When a block producing node is miss-configured (eg. invalid keys), the metrics related to block production are not exposed anymore. Thus we cannot detect the error from those metrics (eg. no forged blocks for more tha X hours).
To get proper alerting, we would need that those metrics are still exposed, when possible, as long as as keys are provided as command line arguments and the node still operate in degraded mode.

Concerned metrics `are:`
```
cardano_node_metrics_nodeIsLeaderNum_int
cardano_node_metrics_Forge_forged_int
cardano_node_metrics_operationalCertificateExpiryKESPeriod_int
cardano_node_metrics_Forge_node_is_leader_int
cardano_node_metrics_delegMapSize_int
cardano_node_metrics_blocksForgedNum_int
cardano_node_metrics_currentKESPeriod_int
cardano_node_metrics_Forge_node_not_leader_int
cardano_node_metrics_slotsMissedNum_int
cardano_node_metrics_remainingKESPeriods_int
cardano_node_metrics_operationalCertificateStartKESPeriod_int
cardano_node_metrics_Forge_adopted_int
cardano_node_metrics_utxoSize_int
cardano_node_metrics_Forge_forge_about_to_lead_int
```

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
