### ISSUE TITLE
[BUG] - The return of the epoch + 48 hour rewards calculation freeze

### ISSUE THREAD

**Issue by Straightpool** [input-output-hk/cardano-node#2205]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Stakepool node operation

**Summary**
After epoch start + 48hours when rewards calculation takes place the network slows to a halt for about 2,5 minutes. This was fixed with 1.21.1 but returned with 1.23.0.

**Steps to reproduce**
1. Run pool on 1.23.0
2. Wait on epoch switch + 48 hours 
In the worst case have a slot in this time window + 2,5 mintues as I did:
12  | leader     | -        | 15897752 | 172952   | 2020-12-08 22:47:23 CET  
3. Look at CPU graph and block height graph
In worst case notice missing block, BP will produce it but it will fail to propagate in time and get lost 

**Expected behavior**
A node should sail through reward calculation on 1.23.0 as it did on 1.21.1 without stop of slot production.

**System info (please complete the following information):**
- OS: Ubunto
- Version: 20.04.1 LTS 
- Node version: 
cardano-node 1.23.0 - linux-x86_64 - ghc-8.10
git rev eed250546fa9acec4c9de557b3e3551c1f682a30

**Screenshots and attachments**
Shows bp did wake up, compares non-leader to leader count:
![Screen Shot 2020-12-08 at 23 03 15](https://user-images.githubusercontent.com/42584250/101546893-bf7f9d80-39a9-11eb-9225-4700445f9cd5.png)
CPU spike on all nodes (BPs and Relays)
![Screen Shot 2020-12-08 at 22 58 16](https://user-images.githubusercontent.com/42584250/101546935-d0301380-39a9-11eb-8585-2dc21b8bcf31.png)
Stuck blockchain for 2.5 minutes:
![Screen Shot 2020-12-08 at 22 56 15](https://user-images.githubusercontent.com/42584250/101546956-d7572180-39a9-11eb-8112-ac785518c3ad.png)

**Additional context**
See old issue which was fixed before

**Comment by glitch40** [comment]
Have also noticed loss of incoming peers and pauses in transactions at the 48h mark as we experienced previously. Nodes that have been updated to 1.23 experience increasing instability on relays after updating to 1.23 the longer they run 15h or longer from my experience after this time nodes have started to "lag" and lose incoming connections which continues to increase until they are restarted.

**Comment by AndrewWestberg** [comment]
![Screenshot from 2020-12-08 22-16-20](https://user-images.githubusercontent.com/245918/101548154-40b24280-3960-11eb-8b2c-05275defc165.png)
![Screenshot from 2020-12-08 22-16-51](https://user-images.githubusercontent.com/245918/101548156-414ad900-3960-11eb-939e-be60c3f4e926.png)
![Screenshot from 2020-12-08 22-17-08](https://user-images.githubusercontent.com/245918/101548157-414ad900-3960-11eb-89c9-5dfeb4d5fe59.png)
![Screenshot from 2020-12-08 22-17-21](https://user-images.githubusercontent.com/245918/101548158-414ad900-3960-11eb-8ea3-baa947e0b172.png)
![Screenshot from 2020-12-08 22-17-34](https://user-images.githubusercontent.com/245918/101548160-41e36f80-3960-11eb-90cc-988272bfbc10.png)
![Screenshot from 2020-12-08 22-17-47](https://user-images.githubusercontent.com/245918/101548161-41e36f80-3960-11eb-906f-6d06230e6e69.png)
![Screenshot from 2020-12-08 22-17-56](https://user-images.githubusercontent.com/245918/101548162-41e36f80-3960-11eb-8d84-06cea425728e.png)

**Comment by papacarp** [comment]
About 20% of reporters dropped out (200+ reporters right now)

![image](https://user-images.githubusercontent.com/11194546/101551676-427f0480-3966-11eb-93bb-eca35be488e0.png)

**Comment by papacarp** [comment]
Bug still there in 1.25.1.  If I understand this correctly, its related to reward processing.  Won't this just keep getting worse as we get more wallets staking?  

![image](https://user-images.githubusercontent.com/11194546/107130578-b3b63780-6883-11eb-8861-957a0bc3c7e0.png)

**Comment by gitmachtl** [comment]
This becomes worse, we have to address this asap! 6mins without blocks and 100% usage.

**Comment by MarcelKlammer** [comment]
Yep, could be please do something about this heavy calculation?

**Comment by JaredCorduan** [comment]
Yes, this is almost certainly due to the reward calculation. We are actively testing out some options (such as [this](https://github.com/input-output-hk/cardano-ledger-specs/pull/2125)) so that we can address this soon.

**Comment by AndrewWestberg** [comment]
Hopefully, the epoch cutover calculations can be similarly spread out with the pulse technique.

**Comment by JaredCorduan** [comment]
> Hopefully, the epoch cutover calculations can be similarly spread out with the pulse technique.

indeed, that's on our radar as well (it's the stake distribution calculation needed for the snapshot that is consuming the resources). the pulse technique is certainly one candidate solution.

**Comment by angelstakepool** [comment]
My relays are losing a considerable amount of peers at the 48h time mark. The network behaves really unstable at this time and several SPOs (using decent hardware specs) have reported losing blocks because of this

**Comment by papacarp** [comment]
Red Alert!! 5 minutes without blocks today.  

![image](https://user-images.githubusercontent.com/11194546/109880280-92026300-7c2b-11eb-845e-87a98d9060b3.png)

![image](https://user-images.githubusercontent.com/11194546/109879993-36d07080-7c2b-11eb-826f-c29660f7b3f4.png)

**Comment by JaredCorduan** [comment]
Our fix for this has been merged in the ledger repo (https://github.com/input-output-hk/cardano-ledger-specs/pull/2142), but we are still working on integrating the changes into the node.

**Comment by mmahut** [comment]
Today, we have seen 10+ minutes.

**Comment by Straightpool** [comment]
Fixed with 1.26.1

**Comment by Straightpool** [comment]
Fixed with 1.26.1. With just 22% of nodes upgraded to 1.26.1 the issue was greatly improved on the last run through this:

![image](https://user-images.githubusercontent.com/42584250/114239577-89b5ea00-9986-11eb-8e5e-87924f30d435.png)

This was the epoch before on 1.25.1

![image](https://user-images.githubusercontent.com/42584250/114239656-a0f4d780-9986-11eb-9416-eed43991007c.png)

I consider this thus fixed and close the issue.
