### ISSUE TITLE
[BUG] - EraMismatch error.

### ISSUE THREAD

**Issue by diegueins680** [input-output-hk/cardano-node#2224]
*External*  

**Area**
*Other*   Stake pool creation.

**Summary**
I'm following these instructions to set up a stake pool:
https://www.coincashew.com/coins/overview-ada/guide-how-to-build-a-haskell-stakepool-node#6-configure-the-air-gapped-offline-machine
In step 10, I need to run the following command:
cardano-cli query protocol-parameters \
    --mainnet \
    --out-file params.json

But I get the following error:
Shelley command failed: query protocol-parameters   Error: A query from a certain era was applied to a ledger from a different era: EraMismatch {ledgerEraName = "Allegra", otherEraName = "Shelley"}

**Steps to reproduce**
1. Run the following command:
    cardano-cli query protocol-parameters \
    --mainnet \
    --out-file params.json

2. See error

**Expected behavior**
Obtain a params.json file

**System info (please complete the following information):**
- OS: NixOS
- Version 20.09.2290.647cc06986c (Nightingale)
- Node version cardano-node 1.24.2 - linux-x86_64 - ghc-8.10

**Comment by btbf** [comment]
Since the network has been hard forked, we need to add a flag.
add　--allegra-era

cardano-cli query protocol-parameters
--mainnet
--allegra-era
--out-file params.json

**Comment by diegueins680** [comment]
Great, thanks!
