### ISSUE TITLE
[FR] - Generate and load password-encoded signing keys

### ISSUE THREAD

**Issue by jbax** [input-output-hk/cardano-node#2236]
*External - Other*

**Describe the feature you'd like**
Anyone with access to a `payment.skey` or `stake.skey` file of a stake pool can easily steal the funds of the operator. Even though we know operators should manage these files in a cold environment, every now and then we hear about operators losing their funds.

A very simple and low cost solution would be to optionally ask the operator for a password when such files are generated, and encode the `cborHex` content with that password, so that any attacker who might get access to a copy of these `skey` files would not be able to steal the funds. This would also protect those who might have their backup stolen (say a burglar took a USB stick with the `skey` files in it, or the cold computer that someone uses to manage everything)

Then, every time a transaction is to be signed using these signing files, the user will be asked to provide the password.

**Describe alternatives you've considered**
I heard about Jormanager, which keeps the files encrypted until you need to sign a transaction. My issue with this is that the CLI still depends on an unencrypted file to exist in the filesystem. I think it's safer to have encrypted files all the time instead.

Also, I'd like to avoid using other scripts and third party tools.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
