### ISSUE TITLE
Avoid using `read` to parse SlotNumber

### ISSUE THREAD

**Issue by karknu** [input-output-hk/cardano-node#224]
https://github.com/input-output-hk/cardano-node/blob/5e301e0d9fef58033a0aef10b4930473572b1235/cardano-node/src/Cardano/Tracing/Tracers.hs#L186

Caused https://github.com/input-output-hk/ouroboros-network/pull/1106 when consensus changed slot number format.

**Comment by Jimbo4350** [comment]
Resolved in #225
