### ISSUE TITLE
[BUG] - Relay node may not be able to bind to it's public IP

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2244]
**External**

**Area**

Networking

**Summary**

A Relay node may not be able to bind to it's public IP.

Some VPS providers abstract the public IP for a node instance from the node itself. With Google Compute Engine (GCE) for example you get an "Internal IP" and an "External IP". The external IP can be remapped from one instance to another iwhen needed. By doing so, you can redirect to another node while doing maintenance on the first.

As a consequence, a process cannot bind to that external IP directly. Instead, your relay node will have to bind to all interfaces ...

```
cardano-node --node-addr=0.0.0.0 ...
```

When the node publishes "it's IP", it may well be the internal IP that is useless for external peers. I think this could be the reason why my relay node (running on GCE) has good outbound connections but never gets an inbound connection.

This is alleviate a little by the use of the [topologyUpdater](https://github.com/cardano-community/guild-operators/blob/alpha/scripts/cnode-helper-scripts/topologyUpdater.sh) because there I set the public IP for my Relay explicitly (i.e. via CNODE_HOSTNAME).

In general, it may be necessary to distinguish between `--bind-addr` and `--node-addr`. In that way, I could control the network address that my node binds to (i.e. the internal IP) and the  address that is getting published to the world.

It may perhaps even be harmful for the network when nodes publish (internal) IPs that can never be reached.  would the stake pools still work correctly when this happens? There is an association for `--pool-relay-ipv4` with the stake pool registration certificate

cheers
-- thomas

**Comment by rcmorano** [comment]
@tdiesler `--host-addr` argument is actually just the bind address. This address doesn't get announced to the network in any away, other peers will only try to connect to your node if your address is explicitly set in their topology files; whether it's set through `topologyUpdater`, pooltool.io's `getBuddies` or any other method like parsing peers from the on-chain metadata added while registering the pools (which btw, IOHK do for their nodes and publish [a list of alive peers here](https://explorer.cardano.org/relays/topology.json)), manual cherry-pick from trusted parties, etc.

Using `0.0.0.0` is the default strategy for containers also so you can map the listening port to the outside world.

**Comment by tdiesler** [comment]
Ok, that's fine then. Thanks for looking and providing the insight.
