### ISSUE TITLE
[BUG] - cardano-cli command map is obsolete

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/cardano-node#2245]
**External**

**Area**
*Documentation*

**Summary**
`cardano-cli` command map is obsolete, on [documentation page](https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/cli.html) command `cardano-cli shelley genesis generate-genesis` should exist, as per help, `generate-genesis` has been obsoleted by `create` only...

```
$ docker run 2ndlayer/centos-cardano-node:1.24.2 cardano-cli shelley --help genesis
Genesis file does not exist! cardano-node can NOT start!!!
Usage: cardano-cli shelley genesis COMMAND
  Shelley genesis block commands

Available commands:
  key-gen-genesis          Create a Shelley genesis key pair
  key-gen-delegate         Create a Shelley genesis delegate key pair
  key-gen-utxo             Create a Shelley genesis UTxO key pair
  key-hash                 Print the identifier (hash) of a public key
  get-ver-key              Derive the verification key from a signing key
  initial-addr             Get the address for an initial UTxO based on the
                           verification key
  initial-txin             Get the TxIn for an initial UTxO based on the
                           verification key
  create                   Create a Shelley genesis file from a genesis template
                           and genesis/delegation/spending keys.
  create-staked            Create a staked Shelley genesis file from a genesis
                           template and genesis/delegation/spending keys.
  hash                     Compute the hash of a genesis file
```

**Steps to reproduce**
N/A

**Expected behavior**
Documentation reflects actual state, I would recommend to include relevant **SVG** files in the repo, so contributors can submit fixes directly...

**System info (please complete the following information):**
- OS: N/A
- Version: N/A
- Node version: 1.24.2

**Comment by CarlosLopezDeLara** [comment]
Cli Reference has been moved to https://docs.cardano.org/getting-started/use-cli
And is maintained in https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/cardano-node-cli-reference.md/
