### ISSUE TITLE
Unable to retire stakepool

### ISSUE THREAD

**Issue by simoncrook** [input-output-hk/cardano-node#2247]
I have compiled a cardano-node and cardano-cli using 1.24.2 release and produced new keys etc. 

I wish to retire my stakepool so I can create another one using the keys produce above.  However I cannot retire the stakepool as when I run the command:

cardano-cli transaction submit     --tx-file tx.signed     --mainnet

I get the following error:

Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (DelegsFailure (DelplFailure (PoolFailure (StakePoolNotRegisteredOnKeyPOOL (KeyHash "XXXXXXX")))))]

, where XXXXXXX is the hash value returned.

I managed to return the rewards and pledge for this stakepool to my wallet but now I cannot retire the stakepool and it is just sitting there do nothing... not producing any rewards... as the pledge as not been met.

Overall, my goal is to use the current details used in existing pool ie pledge, fee, margin with another new pool using the keys of the new cardano-node I have built... However I need to retire it first... If I cannot retire it what options left do I have? Will it sit there for ever doing nothing...

Thanks. Any help greatly appreciated.

**Comment by gitmachtl** [comment]
hey simon, please take a look at my scripts:

**Comment by simoncrook** [comment]
![error_retiring_pool](https://user-images.githubusercontent.com/7731239/103470212-5e928c00-4dd4-11eb-9126-14166707d870.png)

I like your scripts by the way. I think there is a slight error in the script 07a_genStakepoolRetireCert.sh. If you do not have a json pool file then it creates one from the script template for you.... I think this template is missing the line :

"poolMetaTicker": "put your ticker name here"

So I ran both 07a_genStakepoolRetireCert.sh and 07b_deregStakepoolCert.sh. I got my original error of:

StakePoolNotRegisteredOnKeyPOOL

As i say, I think this is because i have messed up my node.vkey/skey of this pool. Which begs the question "Can I retire this pool?" If not what happens to it???? Please see the latest attached screenshot.

Any Further Help greatly appreciated.

Thanks,
Simon

**Comment by gitmachtl** [comment]
> I like your scripts by the way. I think there is a slight error in the script 07a_genStakepoolRetireCert.sh. If you do not have a json pool file then it creates one from the script template for you.... I think this template is missing the line :
> 
> "poolMetaTicker": "put your ticker name here"

Hi, thats because you really only need a minimum of informations to retire the stakepool. Normally you have your full json pool file, but it just need the name of the file in it, thats it. So i think you don't use your original key files here, you need the original node.skey for your pool. Without it you can't retire your pool.

Best regards, Martin

**Comment by gitmachtl** [comment]
But what you can do is, you have removed all your funds from your owner pledge account, so the pool would not make any blocks. Also you will not run this pools in a BP-Node, so it will not make any blocks. The delegators on that pool will leave at some point so the amount of stake in that pool will be 0 at some point so it does not affect the chain at all. You can delete your metadata file on your webserver so the wallets will not be able to show that pool anymore. You can than register a new one with the same ticker and start all over again.

**Comment by simoncrook** [comment]
Hi Martin,

Thanks for all your help. I did move out all my pledge from the stake pool, I think there is 340ADA still left in. Not sure I can move that out. I did try and it complained again so I presume that is maybe because it requires a minimum amount to be in there so maybe that is lost (Is that the pool fee cost)?

I registered a new pool with a different ticker but made the mistake of giving it the same meta data url of the original pool (copy and paste error). I released this as I retrieved the new ledger json file and for my new pool address it still had the old pool url and the SMASH server api said there was a mismatch in the pool meta data hashes (which is how I realised there was an issue with the new pool registration. I corrected this, but as I understand it correcting a change to a pool takes 2 epochs to come through. Is that correct?

I will check in a few days time using the SMASH api for the new pool to see if my new pool issue has been resolved? I will also delete my original pool meta data file from my webserver too as you say.

Hoping I can see the new pool soon ?

Thanks,
Simon

**Comment by CarlosLopezDeLara** [comment]
`StakePoolNotRegisteredOnKeyPOOL`

 Error means that the stake pool is not registered.  
 
 https://github.com/input-output-hk/cardano-node/blob/b04be2542c4066f8778386b724eecb8c73485b9c/cardano-node/src/Cardano/Node/Tracing/Era/Shelley.hs#L708-L711
