### ISSUE TITLE
[FR] - Configure log severity per scribe

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2252]
**Internal/External**
*External* 

**Area**
*Logging/Tracing* 

This is part of an [effort](https://github.com/tdiesler/nessus-cardano) to provide the best possible docker image for cardano.

**Describe the feature you'd like**

We can configure scribes and global severity like this ...

```
  "defaultScribes": [
    [
      "StdoutSK",
      "stdout"
    ],
    [
      "FileSK",
      "/opt/cardano/logs/debug.log"
    ]
  ],
  "minSeverity": "Info",
```

Ideally however, I'd like to have Info on stdout and debug for a rotating log file

**Describe alternatives you've considered**

None

**Additional context / screenshots**

CrossRef: https://github.com/tdiesler/nessus-cardano/issues/15

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
