### ISSUE TITLE
[FR] - Add epoch number to ledger state json dump

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#2255]
**Internal/External**
*External*

**Area**
*Ledger State*

**Describe the feature you'd like**
For leaderlogs in cncli we require a ledger state dump. However, I spent way too much time supporting people who invariably use an old ledger state file and thus get incorrect results. I'm supporting several a day with this issue. Can you add the current epoch to the ledger state dump so I can quickly verify in code that they're using the correct file for the epoch they're trying to get leaderlogs for?

**Describe alternatives you've considered**
Alternatively, if you can have a separate `cardano-cli` command that gets the sigma value for a given pool at a set snapshot (mark, set, go), that would also solve the problem.

**Comment by AndrewWestberg** [comment]
Ledger state is getting huge. It will only get HUGER once we have Mary tokens. For tools doing leader logs, we really need a better solution for calculating a pool's sigma value than ledger state dump. The same goes for retrieving the current or upcoming `d` values.

The current approach of dumping ledger state and then calculating these values is like doing surgery with a chainsaw.

**Comment by Crypto2099** [comment]
I would like to see cardano-cli queries refined to provide the subsets of information found and useful from the ledger i.e.
_cardano-cli query sigma --pool-id pool1abc132 --epoch 248_
_cardano-cli query epoch-parameters --epoch 248 --out-file epoch.params.json_

Or, alternatively to help with the bloat and exploding size of the ledger, allow us to query for only a specific subset of the ledger info such as:

_cardano-cli query ledger-state --mainnet --allegra-era --subset **mark** --out-file ledger.248.mark.json_

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
