### ISSUE TITLE
[BUG] - /metrics returns empty response

### ISSUE THREAD

**Issue by bitnado-io** [input-output-hk/cardano-node#2256]
**Internal/External**
*External*

**Area**
*Other*

**Summary**
`cardano-node` 1.24.2 running as a block producer suddenly had it's `/metrics` endpoint start returning an empty response.
Nothing unusual in the logs except the producer seemed to switch forks just before the endpoint stopped working.
The block producer otherwise continued operating normally, but the `/metrics` endpoint never recovered.

**Steps to reproduce**
Steps to reproduce the behavior: Unclear

**Expected behavior**
The `/metrics` endpoint should be working as long as the node is operational.

**System info (please complete the following information):**
- cardano-node official docker image
- Node version 1.24.2

**Screenshots and attachments**
- Curl response:
```
bash-4.4# curl -i -v http://localhost/metrics
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /metrics HTTP/1.1
> Host: localhost
> User-Agent: curl/7.72.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

- Only unusual log lines prior to the endpoint failure:
```
[34m[cardano-:cardano.node.ChainDB:Info:290][0m [2021-01-05 17:18:12.50 UTC] Block fits onto some fork: 5ac6c4bafb41c64c91f3792daac23daa76c157c90c991947a1eddd9ba4d394ef at slot 18300801
[34m[cardano-:cardano.node.ChainDB:Info:290][0m [2021-01-05 17:18:12.50 UTC] Valid candidate 5ac6c4bafb41c64c91f3792daac23daa76c157c90c991947a1eddd9ba4d394ef at slot 18300801
[35m[cardano-:cardano.node.ChainDB:Notice:290][0m [2021-01-05 17:18:12.50 UTC] Switched to a fork, new tip: 5ac6c4bafb41c64c91f3792daac23daa76c157c90c991947a1eddd9ba4d394ef at slot 18300801
```

**Additional context**
This is problematic because `/metrics` is required for monitoring the node. If this endpoint goes down the node needs to be restarted resulting in downtime for the block producer.

**Comment by rdlrt** [comment]
You need to add what in your config points to port 80 , the default port for EKG and Prometheus are 12788 and 12798 respectively

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
