### ISSUE TITLE
[BUG] - topology.json - 'addr' entry is not trimmed - dns request fails

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2260]
*External* 

**Area**
*Other*

**Summary**
If you have a peer in your topology.json with a space infront or afterwards like:
``` json
    {
      "addr": " relays-new.cardano-mainnet.iohk.io",
      "port": 3001,
      "valency": 2
    },
```
or
``` json
    {
      "addr": "relays-new.cardano-mainnet.iohk.io ",
      "port": 3001,
      "valency": 2
    },

```

the dns query within cardano-node fails!

**Expected behavior**
The addr key entry should be checked and trimmed before using them to query dns entries, so a simple space infront or afterwards should not break the FQDN. Even with P2P around the corner. :smiley:

Also if you put in the port as string like:
``` json
    {
      "addr": "relays-new.cardano-mainnet.iohk.io",
      "port": "3001",
      "valency": 2
    },
```
will result in a completely failing topology check. it is correct that the node reports this with:
`fatalErrorMessage = "Cardano.Node.Run.handleSimpleNode.readTopologyFile: Is your topology file formatted correctly? The port and valency fields should be numerical. Error in $: empty"`

but using strings for port and valency should also be handled like they were just numerical entries.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
