### ISSUE TITLE
[FR] - Load discrimination metrics

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/cardano-node#2261]
**Internal**

**Area**
*Other*   (Metrics reporting)

**Describe the feature you'd like**
The following additional metrics would be helpful in load diagnostics:

* [x] Counter, monotonically increasing, number of block headers by chain sync served
* [x] Counter, monotonically increasing, number of block bodies by block fetch served
* [x] Counter, monotonically increasing, number of txs submitted
* [x] Counter, monotonically increasing, number of txs submitted successfully

**Describe alternatives you've considered**
These metrics will help provide:
* Better load discrimination for servers syncing clients requesting chain history vs chain tailing clients
* Better load discrimination for Tx activity

**Comment by newhoggy** [comment]
Done

**Comment by johnalotoski** [comment]
Thank you!
