### ISSUE TITLE
[FR] - Multiple DNS support for topology

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/cardano-node#2262]
**Internal**

**Area**
*Other*   (Configuration/Topology)

**Describe the feature you'd like**
* Node utilization of multiple DNS records for topology to avoid single DNS record limits for round-robin DNS
* If this feature is already supported, just some feedback on this ticket would be great, thanks!
* For the case of a network with X public relays provided by an entity to be added to round-robin DNS, where X > Y, and Y is the record limit per round-robin DNS, multiple DNS names would be required to accommodate all public relays.  In this example, for node to have access to all upstream producers across multiple DNS names, would simply adding a producer for each DNS round-robin pool be suitable (like in the code snippet below)?
```
{
  "Producers": [
    {"addr": "region-1.fqdn","port": 3001,"valency": 1},
    {"addr": "region-2.fqdn","port": 3001,"valency": 1},
    ...
  ]
}
```

**Comment by karknu** [comment]
This is already supported.
Example config:
```
{
  "Producers": [
    {
      "addr": "north-america.relays-new.cardano-mainnet.iohk.io",
      "port": 3001,
      "valency": 2
    },
    {
      "addr": "asia-pacific.relays-new.cardano-mainnet.iohk.io",
      "port": 3001,
      "valency": 2
    },
    {
      "addr": "europe.relays-new.cardano-mainnet.iohk.io",
      "port": 3001,
      "valency": 8
    }
  ]
}
```

**Comment by johnalotoski** [comment]
Thanks @karknu.  Is there any node logic that tries to determine the best DNS producer pool to use from several which may be available, like in your example above, each serving a relay pool from a different region?  Or is that handled already by something like periodic latency measurements and optimizations where producers with lower latency are preferred, which would likely result in the closest regional endpoint relay pool being selected as preferred producers?

**Comment by karknu** [comment]
Currently, in the example above the node will pick the two first nodes to respond in north-america and asia-pacific, and the eight first nodes to respond in europe. With p2p the set of peers we connect to will change based on their performance, but that isn't implemented yet.

**Comment by johnalotoski** [comment]
Thanks!
