### ISSUE TITLE
[FR] - CLI: dump of blocks to JSON

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#2280]
**Internal**

**Area**
*Native Tokens*    Related to Native Tokens (Mary).
*General*    Related to any Cardano blockchain.

**Describe the feature you'd like**
The `cli` should allow me to dump a range of blocks to JSON format for simple parsing and inspection. All available data should be represented: header, body with txs, next block hash, prev. block hash, ...

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
