### ISSUE TITLE
[FR] - KES metrics are not returned if KES is expired

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2305]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Node metrics

**Describe the feature you'd like**
When KES is expired the KES related metrics are not returned (they are not available through Prometheus) 

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
