### ISSUE TITLE
[FR] - submit-api service

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2323]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
Retiring of cardano-rest

**Describe the feature you'd like**
cardano-rest provides a submit-api. This really could be simplified if the node provided a single executable that took a port and a `CARDANO_NODE_SOCKET_PATH` and ran a REST API that took a submission and validated it/sent it to blockchain if valid (and returned error that `cardano-cli transaction submit` does if invalid).

What I would suggest is it take a POST

and the POST contains either json type that is a tx body generated by cardano-cli
a hex string which is the cborHex attribute in the json created by the node
or a raw cbor binary blob which is the hex string converted to cbor.

This would cover every use case for using it that I'm aware of from exchanges.

It may need a `/era` prefix to identify if it's a shelley, allegra or mary txbody, or possibly the node could identify based on the contents.

**Describe alternatives you've considered**
Drop explorer-api but leave submit-api in cardano-rest. This still suffers from having to be updated after every node release.

**Additional context / screenshots**

**Comment by rdlrt** [comment]
100% agree to this, we already have multiple options for `querying` chain (no idea why cardano-rest/cardano-graphql complicates the architecture further, they dont provide as much value for being a query layer to postgres instance).

The only component should really need are `cardano-node` and `cardano-db-sync` (and whichever mode we can/should use as overlay on DB). Currently submit-api is the only component that makes us still track that repo and keep up to date. Would be much more *complete* if this was available, as a node can already submit transaction to chain.

**Comment by newhoggy** [comment]
Will completing this ticket mean `cardano-rest` will no longer be needed?

**Comment by rdlrt** [comment]
@newhoggy - Yes, atleast for quite a few of us, this would mean we dont need to use `cardano-rest` and `cardano-graphql` at all.

**Comment by dcoutts** [comment]
We should preserve exactly the REST API we have no. No endpoint or format changes. No new endpoints. There are existing users of this API and we can and should preserve 100% compatibility.

We just need to move the repo it lives in and simplify the internal code by porting it to use the Cardano API.

**Comment by rdlrt** [comment]
@dcoutts - agreed, apologies - I could have worded it better (I meant having this feature means some of us would not longer need to use `cardano-rest` , did not mean repo should not be preserved 👍🏻 )

**Comment by newhoggy** [comment]
Resolved by https://github.com/input-output-hk/cardano-node/pull/2370
