### ISSUE TITLE
Useful tracing of TraceChainSyncServerEvent

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/cardano-node#233]
The following TODO can be resolved as https://github.com/input-output-hk/ouroboros-network/pull/1032 has been merged: https://github.com/input-output-hk/cardano-node/blob/3276f8b115cd802828cff36f7291cffa3a9f393e/cardano-node/src/Cardano/Tracing/ToObjectOrphans.hs#L663
Now, it just traces `ChainSyncServerEvent`, which is pretty useless :slightly_smiling_face:.

**Comment by Jimbo4350** [comment]
Closing due to #234.
