### ISSUE TITLE
[BUG] - Just cannot fix nosystemD for month and months?

### ISSUE THREAD

**Issue by ghost** [input-output-hk/cardano-node#2332]
Again same old same old I want to compile without systemd preconfiguring the project with:

I run:
./scripts/gen-cabal-nosystemd.sh

It creates:
cabal.nosystemd.project

I run:
cabal configure -O0 -w ghc-8.10.2

It returns:
`cabal: Could not resolve dependencies:
[__0] trying: Win32-network-0.1.0.0 (user goal)
[__1] trying: base-4.14.1.0/installed-4.14.1.0 (dependency of Win32-network)
[__2] trying: lobemo-scribe-systemd-0.1.0.0 (user goal)
[__3] next goal: libsystemd-journal (dependency of lobemo-scribe-systemd)
[__3] rejecting: libsystemd-journal-1.4.5 (conflict: pkg-config package
libsystemd==209 || >209, not found in the pkg-config database)
[__3] rejecting: libsystemd-journal-1.4.4 (conflict:
base==4.14.1.0/installed-4.14.1.0, libsystemd-journal => base>=4.6 && <4.13)
[__3] skipping: libsystemd-journal-1.4.3, libsystemd-journal-1.4.2,
libsystemd-journal-1.4.1, libsystemd-journal-1.4.0, libsystemd-journal-1.3.4,
libsystemd-journal-1.3.3, libsystemd-journal-1.3.1, libsystemd-journal-1.3.0,
libsystemd-journal-1.2.0, libsystemd-journal-1.1.0, libsystemd-journal-1.0.0
(has the same characteristics that caused the previous version to fail:
excludes 'base' version 4.14.1.0)
[__3] fail (backjumping, conflict set: base, libsystemd-journal,
lobemo-scribe-systemd)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, libsystemd-journal,
lobemo-scribe-systemd, Win32-network
Try running with --minimize-conflict-set to improve the error message.

`
Seriously fuck systemd and it's degenerate users and followers. Why can't you fix this god damn thing?!?

**Comment by mark-stopka** [comment]
I have same problem...

```
Step 19/47 : RUN scripts/gen-cabal-nosystemd.sh
 ---> Running in 79567ac754e7
++++ realpath scripts/gen-cabal-nosystemd.sh
+++ dirname /usr/src/cardano-node/scripts/gen-cabal-nosystemd.sh
++ dirname /usr/src/cardano-node/scripts
+ root=/usr/src/cardano-node
+ cd /usr/src/cardano-node
+ sed -e '/plugins\/scribe-systemd/d' cabal.project
+ echo ''
+ echo 'flags: -systemd'
+ '[' -e cabal.project.freeze ']'
```

and then

```
Step 23/47 : RUN cabal install cardano-cli       --project-file=cabal.nosystemd.project       --installdir=/usr/local/bin       --install-method=copy       -f -external-libsodium-vrf
 ---> Running in e98a3ce0488c
cabal: Could not resolve dependencies:
[__0] trying: Win32-network-0.1.0.0 (user goal)
[__1] trying: base-4.14.3.0/installed-4.14.3.0 (dependency of Win32-network)
[__2] trying: cardano-tracer-0.1.0 (user goal)
[__3] next goal: libsystemd-journal (dependency of cardano-tracer)
[__3] rejecting: libsystemd-journal-1.4.5 (conflict: pkg-config package
libsystemd>=209, not found in the pkg-config database)
[__3] rejecting: libsystemd-journal-1.4.4 (conflict:
base==4.14.3.0/installed-4.14.3.0, libsystemd-journal => base>=4.6 && <4.13)
[__3] skipping: libsystemd-journal-1.4.3, libsystemd-journal-1.4.2,
libsystemd-journal-1.4.1, libsystemd-journal-1.4.0, libsystemd-journal-1.3.4,
libsystemd-journal-1.3.3, libsystemd-journal-1.3.1, libsystemd-journal-1.3.0,
libsystemd-journal-1.2.0, libsystemd-journal-1.1.0, libsystemd-journal-1.0.0
(has the same characteristics that caused the previous version to fail:
excludes 'base' version 4.14.3.0)
[__3] fail (backjumping, conflict set: base, cardano-tracer,
libsystemd-journal)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: libsystemd-journal, cardano-tracer,
base, Win32-network
Try running with --minimize-conflict-set to improve the error message.

The command '/bin/sh -c cabal install cardano-cli       --project-file=cabal.nosystemd.project       --installdir=/usr/local/bin       --install-method=copy       -f -external-libsodium-vrf' returned a non-zero code: 1
markstopka@mark-zenbook-s:~/Work/github.com/PERLUR/docker-cardano-images/cardano-node/1.35.0> 
```

with 1.35.0 node version.

**Comment by mark-stopka** [comment]
I can confirm that `RUN zypper install -y systemd-devel` fixes the issue...
