### ISSUE TITLE
[FR] - transaction pretty printer

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2336]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
A TX pretty print command

Suggested output:

```
Transaction: <ID>
Era: Allegra
txins:
  abcdef#0
  abcdef#1
  abcdef#2
txouts:
  addr1abcdef 100000 lovelace (1 Ada)
fee: 170000 lovelace (0.17 Ada)
live-before: 5000000
live-after:4000000
metadata:
  61284: <json metadata pretty printed>
  61285: <json metadata pretty printed>
certificates:
  stake-registration: stake123456
  pool-registration: pool12345678
    rewards: stake123456
    owners:
      stake123456
      stake123457
    metadata:
      <fetched metadata-url json pretty printed if hash matches>
    metadata-hash: 1234567890
    vrf-hash: 1234567890
    margin: 0.5%
    cost: 500000000 lovelace (500 ada)
    pledge: 500000000000000 lovelace (500,000,000 ada)
    relays:
       relays-new.cardano-mainnet.iohk.io:3001
       [::1]:3001
       127.0.0.1:3001
  stake-delegation: stake123456 -> pool12345678
  mir:
    reserves:
      stake12346: 100000000 lovelace (100 Ada)
    treasury:
      stake123457: 200000000 lovelace (200 Ada)
  update-proposal: <epoch>
    decentralization-parameter: 0.2
    num-pools: 1000
    protocol-major: 5
    protocol-minor: 0
```

Something like this would make it much easier to audit a transaction than dumping the cbor and manually identifying the pieces.

**Describe alternatives you've considered**
cbor.me (what I currently use)

**Additional context / screenshots**

**Comment by cblp** [comment]
Implemented (partially) in #2348, now in master. @disassembler, please take a look at how it works. I will close this issue, and if you have any further suggestions, don't hesitate to open more issues.

**Comment by cblp** [comment]
Or, reopen this issue, if you think the "suggested output" snippet is relevant.

**Comment by disassembler** [comment]
"DCertPool (RegPool (PoolParams {_poolId = KeyHash \"35119f1ed0d4b0f91e704b88005ecae58dfb305e11bfb2f168b6aafa\", _poolVrf = \"7ffbaebb8dd0f9f43caf441dcdbfa270c3ce82d90d4f8031a761c16b95b68aab\", _poolPledge = Coin 1000000000000, _poolCost = Coin 500000000, _poolMargin = UnsafeUnitInterval (1 % 1), _poolRAcnt = RewardAcnt {getRwdNetwork = Mainnet, getRwdCred = KeyHashObj (KeyHash \"a6e4b6658776e9025a9c60942d3f36f1dafbf56ce0784ec27ac2566b\")}, _poolOwners = fromList [KeyHash \"e45f2da142b7a2b7e5ef113914401dcb45c5add6386e4f23d6481107\"], _poolRelays = StrictSeq {fromStrict = fromList [SingleHostName (SJust (Port {portToWord16 = 3001})) (DnsName {dnsToText = \"relays-new.cardano-mainnet.iohk.io\"})]}, _poolMD = SJust (PoolMetadata {_poolMDUrl = Url {urlToText = \"https://pools.iohk.io/IOGP.json\"}, _poolMDHash = \"7\\235\\NULL\\r\\216\\162!\\172\\&5\\152\\202\\FSmbW\\251R\\a\\174\\152W\\183\\193c\\174\\SI9%\\157l\\192\"})}))"
That could use a prettier format. Especially metadata hash (that should be printed as hex.
13:11
I'm guessing all certs will suffer the same issue and it's not just pool registration
13:12
another thing would be addresses, those should be in bech32 format, not hex
13:12
e.g.
   "outputs": [
        {
            "address": "016445bb08465c26cf435a4274b8dadff753b3b9a87f4aa8f88479431d4eb646b86f18f6f4266684f37fbcf4027c650747dc45278ab0bf8c8e",
            "amount": 4810000
        }
    ],
13:14
Update proposal has the same issue with not very nice printing:
    "update": "Update (ProposedPPUpdates (fromList [(KeyHash \"162f94554ac8c225383a2248c245659eda870eaa82d0ef25fc7dcd82\",PParams {_minfeeA = SNothing, _minfeeB = SNothing, _maxBBSize = SNothing, _maxTxSize = SNothing, _maxBHSize = SNothing, _keyDeposit = SNothing, _poolDeposit = SNothing, _eMax = SNothing, _nOpt = SNothing, _a0 = SNothing, _rho = SNothing, _tau = SNothing, _d = SJust (UnsafeUnitInterval (7 % 50)), _extraEntropy = SNothing, _protocolVersion = SNothing, _minUTxOValue = SNothing, _minPoolCost = SNothing}),(KeyHash \"2075a095b3c844a29c24317a94a643ab8e22d54a3a3a72a420260af6\",PParams {_minfeeA = SNothing, _minfeeB = SNothing, _maxBBSize = SNothing, _maxTxSize = SNothing, _maxBHSize = SNothing, _keyDeposit = SNothing, _poolDeposit = SNothing, _eMax = SNothing, _nOpt = SNothing, _a0 = SNothing, _rho = SNothing, _tau = SNothing, _d = SJust (UnsafeUnitInterval (7 % 50)), _extraEntropy = SNothing, _protocolVersion = SNothing, _minUTxOValue = SNothing, _minPoolCost = SNothing}),(KeyHash \"268cfc0b89e910ead22e0ade91493d8212f53f3e2164b2e4bef0819b\",PParams {_minfeeA = SNothing, _minfeeB = SNothing, _maxBBSize = SNothing, _maxTxSize = SNothing, _maxBHSize = SNothing, _keyDeposit = SNothing, _poolDeposit = SNothing, _eMax = SNothing, _nOpt = SNothing, _a0 = SNothing, _rho = SNothing, _tau = SNothing, _d = SJust (UnsafeUnitInterval (7 % 50)), _extraEntropy = SNothing, _protocolVersion = SNothing, _minUTxOValue = SNothing, _minPoolCost = SNothing}),(KeyHash \"60baee25cbc90047e83fd01e1e57dc0b06d3d0cb150d0ab40bbfead1\",PParams {_minfeeA = SNothing, _minfeeB = SNothing, _maxBBSize = SNothing, _maxTxSize = SNothing, _maxBHSize = SNothing, _keyDeposit = SNothing, _poolDeposit = SNothing, _eMax = SNothing, _nOpt = SNothing, _a0 = SNothing, _rho = SNothing, _tau = SNothing, _d = SJust (UnsafeUnitInterval (7 % 50)), _extraEntropy = SNothing, _protocolVersion = SNothing, _minUTxOValue = SNothing, _minPoolCost = SNothing}),(KeyHash \"ad5463153dc3d24b9ff133e46136028bdc1edbb897f5a7cf1b37950c\",PParams {_minfeeA = SNothing, _minfeeB = SNothing, _maxBBSize = SNothing, _maxTxSize = SNothing, _maxBHSize = SNothing, _keyDeposit = SNothing, _poolDeposit = SNothing, _eMax = SNothing, _nOpt = SNothing, _a0 = SNothing, _rho = SNothing, _tau = SNothing, _d = SJust (UnsafeUnitInterval (7 % 50)), _extraEntropy = SNothing, _protocolVersion = SNothing, _minUTxOValue = SNothing, _minPoolCost = SNothing}),(KeyHash \"b9547b8a57656539a8d9bc42c008e38d9c8bd9c8adbb1e73ad529497\",PParams {_minfeeA = SNothing, _minfeeB = SNothing, _maxBBSize = SNothing, _maxTxSize = SNothing, _maxBHSize = SNothing, _keyDeposit = SNothing, _poolDeposit = SNothing, _eMax = SNothing, _nOpt = SNothing, _a0 = SNothing, _rho = SNothing, _tau = SNothing, _d = SJust (UnsafeUnitInterval (7 % 50)), _extraEntropy = SNothing, _protocolVersion = SNothing, _minUTxOValue = SNothing, _minPoolCost = SNothing}),(KeyHash \"f7b341c14cd58fca4195a9b278cce1ef402dc0e06deb77e543cd1757\",PParams {_minfeeA = SNothing, _minfeeB = SNothing, _maxBBSize = SNothing, _maxTxSize = SNothing, _maxBHSize = SNothing, _keyDeposit = SNothing, _poolDeposit = SNothing, _eMax = SNothing, _nOpt = SNothing, _a0 = SNothing, _rho = SNothing, _tau = SNothing, _d = SJust (UnsafeUnitInterval (7 % 50)), _extraEntropy = SNothing, _protocolVersion = SNothing, _minUTxOValue = SNothing, _minPoolCost = SNothing})])) (EpochNo 249)",
13:15
probably only showing options that aren't SNothing and make them json instead of showing all the types.

**Comment by disassembler** [comment]
#2385 #2386 and #2387 details bugs with the current implementation. This issue should probably remain open as a meta issue to track the other ones in, since this one has the examples of what we expect to get from the output.

**Comment by disassembler** [comment]
so far I've only looked at an update proposal and pool registration, but in my opinion any case of something that can be pretty printed should be dealt with. Might be good to involve QA in testing all the edge cases. cc @alan-mcnicholas @dorin100

**Comment by dorin100** [comment]
Thank you @disassembler . I will look into this.

**Comment by dorin100** [comment]
+ https://github.com/input-output-hk/cardano-node/issues/2403

**Comment by dorin100** [comment]
I think we can close this ticket and track separately the improvements to the `transaction view` command.
