### ISSUE TITLE
[BUG] - Encoding for assetNames in JSON output is wrong, normal output is ok (cardano-cli)

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2337]
*External*

cardano-cli version 1.25.1

**Area**
*Native Tokens* 

**Summary**
When minting or having NativeTokens on an address with an assetName like `АнтиКойн` in this example. All the minting process goes thru, all good. But when you query the UTXO status again via the JSON output (and like me many are using that in the operator scripts and tools like JorManager&CNTools) is showing a wrong encoded representative. The normal query output is ok, but most of us don't use thats anymore with the more and more complex content. So, you can mint such an assetName, but after that you're locked out because you don't get the assetName back again in the right format.

A normal query shows this:
``` console
./cardano-cli query utxo --mary-era --cardano-mode --address addr_test1vzgh690ut4vvxz67klfjhuqmqlf5fppxecrxynht4r3yz5s674wz7 --testnet-magic 1097911063
```

Output:
```
                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------
504aa6697d41658f5aafb914cc9d4f38289109e0cd6f725d28287a2c1ee939b6     0        9817955 lovelace + 100 34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518.АнтиКойн
```

As you can see, the **output is ok**, but the JSON formatted output **is wrong**, you get this:
``` console
./cardano-cli query utxo --mary-era --cardano-mode --address addr_test1vzgh690ut4vvxz67klfjhuqmqlf5fppxecrxynht4r3yz5s674wz7 --testnet-magic 1097911063 --out-file /dev/stdout
```

Output:
``` json
{
    "504aa6697d41658f5aafb914cc9d4f38289109e0cd6f725d28287a2c1ee939b6#0": {
        "amount": [
            9817955,
            [
                [
                    "34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518",
                    [
                        [
                            "Ð�Ð½Ñ�Ð¸Ð�Ð¾Ð¹Ð½",
                            100
                        ]
                    ]
                ]
            ]
        ],
        "address": "60917d15fc5d58c30b5eb7d32bf01b07d3448426ce06624eeba8e24152"
    }
}
```

**The assetName is not correct here.** It shows `Ð�Ð½Ñ�Ð¸Ð�Ð¾Ð¹Ð½` instead of `АнтиКойн`.
So please update the JSON output to also show the correct representive assetName string.

**Expected behavior**
Both output methods should show the correct assetName `АнтиКойн`

**Comment by gitmachtl** [comment]
I have created a testaddress with the bespoken example assetName, you can query it from the following address:

**Comment by mkoura** [comment]
Can't reproduce that on current master (476db294924e85a34342cb97bac273ae5c63e79c):

```
$ cardano-cli query utxo --testnet-magic 42 --out-file /dev/stdout --address addr_test1vpd40qgra0uasfd3p2p
dx324s6gkzkd9jp8fn3k3vjjtgvgqpr6ms
{
    "b6a57c590a1a6a070764e0b05e4aaca2e41ce3a5c8b211dd13d9eb04b357106e#0": {
        "address": "addr_test1vpd40qgra0uasfd3p2pdx324s6gkzkd9jp8fn3k3vjjtgvgqpr6ms",
        "value": {
            "lovelace": 899811355,
            "6cf58ceb8c4d5fff13b3e7bf784dceebd4a352ed91e5bc70b15544fd": {
                "ěščřžďťňivzh": 5
            }
        }
    }
}```

**Comment by gitmachtl** [comment]
Yes it looks like cli 1.26.1 fixed that isse with the new utxo-query-json format.
