### ISSUE TITLE
[BUG] - EraMismatch ledgerEraName = Byron, otherEraName = Allegra

### ISSUE THREAD

**Issue by mfurgiuele** [input-output-hk/cardano-node#2344]
Hello, 
With the version of cli 1.25.1. I can't create the protocol-parameters  json for allegra.
Thanks for the help

**cardano-cli version**
	cardano-cli 1.25.1 - linux-x86_64 - ghc-8.10
	git rev 9a7331cce5e8bc0ea9c6bfa1c28773f4c5a7000f

**cardano-cli query protocol-parameters --mainnet --allegra-era**
	Shelley command failed: query protocol-parameters   Error: A query from a certain era was applied to a ledger from a different era: EraMismatch {ledgerEraName = "Byron", otherEraName = "Allegra"}

**Comment by erikd** [comment]
In order to do this query, you need both `cardano-cli` and `cardano-node` to be at the same revision. Your CLI seems to tbe the correct version, but what about the node?

Also, the node needs to be fully synced.

The above query works correctly for me (my node is fully synced):
```
> cardano-cli query protocol-parameters --mainnet --allegra-era
{
    "poolDeposit": 500000000,
    "protocolVersion": {
        "minor": 0,
        "major": 3
    },
    "minUTxOValue": 1000000,
    "decentralisationParam": 0.2,
    "maxTxSize": 16384,
    "minPoolCost": 340000000,
    "minFeeA": 44,
    "maxBlockBodySize": 65536,
    "minFeeB": 155381,
    "eMax": 18,
    "extraEntropy": {
        "tag": "NeutralNonce"
    },
    "maxBlockHeaderSize": 1100,
    "keyDeposit": 2000000,
    "nOpt": 500,
    "rho": 3.0e-3,
    "tau": 0.2,
    "a0": 0.3
}
```

**Comment by mfurgiuele** [comment]
hoo ok, I didn't think it had to be full sync.
My node is syncing (7.7%), I'll wait for it to finish.
Thank you and sorry for reporting it as a bug.
I close the thread
