### ISSUE TITLE
[Documentation] - TraceMempool: practical usage for relays

### ISSUE THREAD

**Issue by rphair** [input-output-hk/cardano-node#2350]
This issue has come up with SPOs on the Cardano Forum about a recommendation to categorically set `"TraceMempool": false` on stake pool relays while leaving it on for block producers: https://forum.cardano.org/t/solved-cpu-load-at-maximum-since-1-25-1/46580

As documented in the forum thread, relay node logfiles often show 10 or more duplicate copies of the same transaction, which correlates with an increase in CPU load and diminished relay responsiveness.  The "folk" solution has emerged to turn off `TraceMempool` which prevents incoming transactions from being observed on that relay... but they can be followed through on the block producer to verify a stake pool's overall readiness for block production.

The problem: We don't have nearly enough documentation to judge the implications of doing this.  I was unhappy about turning off Tx tracing and decided to do it one the most affected of our two relays (showing the most duplicates & the highest load average).  Then last epoch our second relay also began showing the floods of duplicate transactions, with the same increase in CPU load.  From watching this for a few months (see forum) I can see that these duplicates are becoming more prevalent in the Cardano network.

During this observation period the number of connected peers has not changed on either of our relays.  We have already blacklisted IP addresses of nodes generating `HardForkEncoderDisabledEra` messages, as have other SPOs responding to the above forum thread.

The enigmatic description of what `TraceMempool` does, from the YAML config schema from Byron (the most recent I could find):

```
# Trace mempool.
TraceMempool: True
```

What we don't know, and what I would like to document here or in some link to the documentation, at least:

- How "normal" is it to see 10 or 12 copies of a transaction?
  - What does the appearance of duplicates in our `node.log` really indicate?
  - Is it a coincidence that the number of duplicates corresponds roughly to the number of connected peers?
- implications of setting `"TraceMempool": false` on:
  - fault tolerance for our stake pool
  - fault tolerance for the Cardano network as a whole
  - our ability to debug after a block production failure
  - our ability to recognise or resist a DoS attack on our stake pool
- How else can the problem we've observed be avoided?
  - Will increased RAM on our relays reduce the CPU burden (load average) in some time-space optimisation?  (not an attractive option for forum participants, and I wouldn't consider it without *some* information sharing from the devs here)
  - Is there a way to find whether individual nodes are propagating transactions multiple times, so these nodes can be avoided somehow?
  - Anything else we can do limit this apparent effect of duplicate Tx, other than "throwing hardware" at it?

At the time of this posting, during a period where transaction frequency has increased a lot recently (currently rising ADA perhaps causing increased buying or exchange activity), the duplicate transactions for a typical node with 10 globally dispersed peers appears enough to limit the availability of a `cardano-node` relay with 2 vCPUs and 4G RAM.

- With these specs and the default `config.json`, system load averages are a greater percentage of `1` than the percentage of 4G RAM used by the node.
- With `TraceMempool` turned off, relay load average is close to `0` and, if load increases linearly with Tx, could sustain a further vast increase in transaction frequency beyond the current level.

Therefore we are at a juncture where the development team has to come forward with enough information for SPO's to make these decisions intelligently.

```
cardano-node 1.25.1 - linux-x86_64 - ghc-8.10
git rev 9a7331cce5e8bc0ea9c6bfa1c28773f4c5a7000f
```

**Comment by HofmannZ** [comment]
Any update on this? Can we at least get a confirmation if this on the radar of the IOHK team?

**Comment by link78** [comment]
Any update on TraceMempool? Does it need to set False on Replay node only or on both core and relay. I also notice of high consumption of CPU.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
