### ISSUE TITLE
[BUG] - IPV6 addresses fail to parse

### ISSUE THREAD

**Issue by kenrestivo** [input-output-hk/cardano-node#2352]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   

**Summary**
Add an IPv6 address as external address. Get an error.

**Steps to reproduce**
I run this:
```
cardano-node run \
   --socket-path /home/cardano/configuration/socket \
   --topology /home/cardano/configuration/mainnet-topology.json \
   --database-path /home/cardano/configuration/db \
   --host-addr  2601:640:8880:375b:2c0:caff:fe47:9d63 \
   --port 3001 \
   --config /home/cardano/configuration/mainnet-config.json
```
Get error
```
option --host-addr: Failed to parse: 2601:640:8880:375b:2c0:caff:fe47:9d63
```
**Expected behavior**
cardano-node should start up and bind to the given address

**System info (please complete the following information):**
- OS: debian 
- Version 10.7
- Node version cardano-node-1.25.0-linux.tar.gz

**Additional context**
Documentation explicitly states that host-addr can be an IPv4 or IPv6 address. 
https://docs.cardano.org/projects/cardano-node/en/latest/
"--host-addr - Optionally specify your node’s IPv4 or IPv6 address."

**Comment by cblp** [comment]
I'm removing IPv6 options and making the host IP address omniversioned.

**Comment by kenrestivo** [comment]
I like the way that you think, Sir, as this is in my opinion the correct answer.

**Comment by cblp** [comment]
Sorry, a better way is completely different: see #2431
