### ISSUE TITLE
[FR] - Provide a multiarch docker image - added support for arm64 

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2361]
**Internal/External**
*External* 

**Area**
*Docker* 

**Describe the feature you'd like**

The current docker image runs on x86_64 only. I'd like to expand the range of supported architectures to arm64 and possibly others as well. Initially this will involve building the binaries for arm64, which currently is only possible through convoluted workarounds AFAIK. 

**Additional context / screenshots**

We already have support for arm64 in [nessusio/cardano-node](https://hub.docker.com/r/nessusio/cardano-node) so it would be a matter of finding a way to do something similar or better for inputoutput/cardano-node.

**Comment by tdiesler** [comment]
This is currently blocked by https://github.com/input-output-hk/cardano-node/issues/2391

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
