### ISSUE TITLE
[FR] - Add topology update functionality to Docker image

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2362]
**Internal/External**
*External* 

**Area**
*Docker* 

**Describe the feature you'd like**

This is part of [#2360] Provide high quality multiarch docker image and k8s support

The image cannot rely on an external process to do topology updates - this has to be done within. Initially we could perhaps use guild-operators for that (to be discussed)

**Additional context / screenshots**

I'd take care of this, if it's ok with you.

**Comment by robinboening** [comment]
@tdiesler I am sorry if my following question is kinda stupid. I am very new to all the cardano tools so there is a steep learning curve.

> The image cannot rely on an external process to do topology updates

What is this external process you're referring to?

**Comment by tdiesler** [comment]
With a bare metal node (i.e. not a docker container) you have a cardano-node process running on your machine. That process has an initial topology configuration, which allows it to discover a few peers and then start downloading the blockchain. That topology needs updating because over time peers come and go. Normally, a node would take care of that and continuously broadcast its address to the network so that others make a connection to it - this is the purpose of a peer-to-peer (p2p) module, which isn't implemented yet in the cardano-node.

As a result, you must start another process, for example a cron job, that does this. Many folks  use the [topologyUpdater](https://cardano-community.github.io/guild-operators/#/Scripts/topologyupdater) from guild-operators to do that. If you run your cardano-node without it, you may end up with no incoming connections and no Tx to process.

In the container world, that would be an absolute no go i.e. a docker container must be able to provide its functionality in a self contained manner and cannot rely on some external thing to do stuff that it should be doing itself. Therefore, we must bake this topology update functionality into the image - which this issue is about.

**Comment by robinboening** [comment]
Thanks for the detailed explanation! It makes sense to me now :)

The topologyUpdater script relies on the api.clio.one/htopology API, do you know if this API is maintained on GitHub? I couldn't find a repo. I expected it to be here: https://github.com/clio-one

**Comment by tdiesler** [comment]
Unfortunately, I wouldn't know about that - perhaps its best to ask the fine folks at guild about [this endpoint](https://github.com/cardano-community/guild-operators/blob/alpha/scripts/cnode-helper-scripts/topologyUpdater.sh#L136). I'd be interested to know more about it as well.

**Comment by robinboening** [comment]
> perhaps its best to ask the fine folks at guild

Thanks for pointing me to the right place.

> I'd be interested too.

Here you go :)
https://github.com/cardano-community/guild-operators/issues/784

**Comment by tdiesler** [comment]
Here is PR #2393

**Comment by tdiesler** [comment]
This is superseded by PR #2428
