### ISSUE TITLE
[FR] - Deployment scripts for Kubernetes

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2363]
**Internal/External**
*External*

**Area**
*Docker*

**Describe the feature you'd like**

This is part of [#2360] Provide high quality multiarch docker image and k8s support

With Kubernetes as the de-facto standard for container deployment, orchestration, monitoring, scaling , etc, it should be as easy as this to integrate a Cardano node ...

```
kubectl apply -f https://raw.githubusercontent.com/input-output-hk/cardano-node/master/cardano-node.yaml
```

**Additional context / screenshots**

I'd take care of this, if it's ok with you.

**Comment by Preskton** [comment]
Howdy, @tdiesler - recently started poking around `cardano-node` and k8s was my preferred place to start. I'm still getting my bearings around the runtime architecture and plan on dropping updates to https://github.com/Preskton/cadrano-node-kube. I'd be super happy to PR here and have it part of the official project, though!

**Comment by tdiesler** [comment]
Here the PR #2428

So far we have ...

* Preserved functionality via -e NETWORK
* Node configuration through env vars, which is later needed for k8s integration
* Deployment scripts for Kubernetes and Docker Compose
* Integrated configurable topology update
* Graceful shutdown on docker stop
* Improved access to the CLI

There is a README about this [here](https://github.com/tdiesler/cardano-node/tree/ghi2363/nix/docker).
