### ISSUE TITLE
[BUG] - Core node goes to loop syncing

### ISSUE THREAD

**Issue by devilus** [input-output-hk/cardano-node#2367]
Hello.

After 2-3 days uptime a core node starts to out of sync from relays.

![telegram-cloud-photo-size-2-5282830566472921386-y](https://user-images.githubusercontent.com/19307892/107927549-34fa8200-6f88-11eb-85c5-78cf858c37e7.jpg)

Restaringt cnode service are not helped, hard server reboot only. 

Cnode version 1.25.1

**Comment by joseiadicicco** [comment]
Hello @devilus ! Did you find where the problem was? I have the same issue. How many peers do you have in your relays? And why you have 1 Peer Out and 2 Peers in? Wouldnt have 2 and 2? Jose

**Comment by erikd** [comment]
What does
 ```
 CARDANO_NODE_SOCKET_PATH=/path/to/node.socket query tip --mainnet
 ```
  say and how does that compare with that live view output?
