### ISSUE TITLE
[FR] - Missing 1.25.1 Linux executable

### ISSUE THREAD

**Issue by andreAmorimF** [input-output-hk/cardano-node#2369]
*External* 

**Area**
*Other*

**Describe the feature you'd like**
Even though the 1.25.1 was made some weeks ago, I couldn't find any Linux executable for this version (such as https://hydra.iohk.io/build/5563812). Any chance for an executable for this version to be provided?

**Describe alternatives you've considered**
Alternative would be just build from sources (I would like to avoid using docker).

**Comment by tdiesler** [comment]
You could extract the binary from an existing docker images or perhaps even use [nessusio/cardano](https://hub.docker.com/repository/docker/nessusio/cardano) for example.

Also please have a look at #2360

**Comment by andreAmorimF** [comment]
I understand that these options are possible using docker, but then what's the point to link out an old executable on the `cardano-node` README? Will publishing these executables be discontinued?

**Comment by tdiesler** [comment]
The link correctly points to the "latest version of cardano-node and cardano-cli" built from master. If you want binaries for the latest tag (i.e. 1.25.1) you may have to build them - at least there isn't a download option that I'm aware of.

**Comment by benapetr** [comment]
https://hydra.iohk.io/build/5446647/download/1/cardano-node-1.25.1-linux.tar.gz

**Comment by CarlosLopezDeLara** [comment]
No longer relevant
