### ISSUE TITLE
[BUG] - cardano-node transaction view shows address in hex

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2385]
**Internal/External**
*Internal*   if an IOHK staff member.

*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
cardano-node view should show any addresses in bech32, not hex.

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by dorin100** [comment]
EX:
```
    "outputs": [
        {
            "address": "003701a14d88032d47926399436b8c65fbb1fed29184591967b0fb8291ba5078dcbfb4a05c36c8ae88334aa1b83553c855433a583e11b9f01f",
            "amount": 999995800000
        }
    ],
```
