### ISSUE TITLE
[BUG] - cardano-node view doesn't format update proposals well

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2387]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Currently, update proposals are a huge dump of types. They aren't easy to glance and and know what's in them. Also, some types are displayed very awkwardly. It also shows every param, even if it doesn't change. It should only show the params that are altered. For example a d param update proposal should only show `d: 0.14`.

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
