### ISSUE TITLE
[BUG] - cardano-node build fails with "Segmentation fault" on aarch64

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2391]
**Internal/External**
*External*   

**Area**
*Nix build*

**Summary**
A clear and specific description of what the bug is.

**Steps to reproduce**

```
$ nix-build -A scripts.mainnet.node -o ~/bin/cardano-node
...
From https://github.com/angerman/old-ghc-nix
 * [new branch]      abstract-ci   -> origin/abstract-ci
 * [new branch]      abstract-ci2  -> origin/abstract-ci2
 * [new branch]      hercules-test -> origin/hercules-test
 * [new branch]      master        -> origin/master
Switched to a new branch 'fetchgit'
removing `.git'...
building '/nix/store/jlb45vs5ak9fkaaaq4sn0h2dpixfk8pp-alex-plan-to-nix-pkgs.drv'...
copying path '/nix/store/1cyla31fc535vqsjw0nd5pk1dz1x44ir-happy-1.19.11.tar.gz' from 'https://cache.nixos.org'...
building '/nix/store/myk6fk95n3fpncajzw1ps4v5sgj424a0-happy-1.19.11-src.drv'...
building '/nix/store/amhvlfl9v4nlclkddg06c6dmxz0aiba9-nix-tools-plan-to-nix-pkgs.drv'...
Segmentation fault (core dumped)
```

**Expected behavior**

**System info (please complete the following information):**
- AWS a1.2xlarge (4 CPU, 16GB)
- OS: CentOS 
- Version 8
- Post 1.25.1 (latest master)

With 8GB of RAM I got an out of memory error

**Additional context**

This has already been reported here: https://github.com/input-output-hk/haskell.nix/issues/1027
and unfortunately blocks #2361

For the record, I suggested a path along these lines to unblock this ...

*How about a branch of haskell.nix with a narrow focus on some selected projects (i.e. cardano-node, wallet, etc). That branch would have just enough functionality to build those projects on x86_64 and aarch64. Over time this branch could becomes the default and support for more & more projects could be added without breaking aarch64 builds. Some projects may choose to stay on the existing haskell.nix branch which only works for x86_64. Waiting for this to get fixed in Nix might not be the only possible option.*

**Comment by hasufell** [comment]
You could try to build cardano-node with cabal. [ghcup](https://www.haskell.org/ghcup/)  now supports aarch64, so you could install ghc and cabal that way.

**Comment by tdiesler** [comment]
@hasufell You mean like [this](https://github.com/tdiesler/nessus-cardano/blob/master/nix/cardano/Dockerfile)? I've had this working for a while. However, I'd like the IOHK default build to also work on arm64 so that I can eventually produce multiarch docker images from the upstream codebase.

**Comment by whosystem** [comment]
I needed about 14GB main memory to build all the cardano packages including plutus, etc...

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
