### ISSUE TITLE
[BUG] - cardano cli should use mary era as default if era not specified.

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/cardano-node#2396]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
cardano cli should use allegra era as default if era not specified.

**Steps to reproduce**
query utxo without specifying era:
```
cardano-cli query utxo --address $(cat payment.addr) --mainnet
Shelley command failed: query utxo Error: A query from a certain era was applied to a ledger from a different era: EraMismatch {ledgerEraName = “Allegra”, otherEraName = “Shelley”}
```
**Expected behavior**
if not specified the default should be used

Version: 1.25.1

**Comment by dorin100** [comment]
this was fixed in the meantime.
