### ISSUE TITLE
Improve the help of the "transaction view" arguments

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2403]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
When executing `cardano-cli transaction view`, it is not clear that:
- `--tx-body-file` expects a tx body (raw\unsigned transaction)
- `--tx-file` expects a signed transaction
- the `JSON` keyword from the description of the arguments could be misleading too as the command expects a tx file (and not a json file)

**Steps to reproduce**
```
# cardano-cli transaction view
Usage: cardano-cli transaction view (--tx-body-file FILE | --tx-file FILE)
  Print a transaction

Available options:
  --tx-body-file FILE      Input filepath of the JSON TxBody.
  --tx-file FILE           Input filepath of the JSON Tx.
  -h,--help                Show this help text
```

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 18.04]
- Node version
```
# cardano-cli --version
cardano-cli 1.25.0 - linux-x86_64 - ghc-8.10
git rev 58c1e06f3618b546627916bd24649d5cecf63ff8

# cardano-node --version
cardano-node 1.25.0 - linux-x86_64 - ghc-8.10
git rev 58c1e06f3618b546627916bd24649d5cecf63ff8
```

**Comment by dorin100** [comment]
The wording of the error messages could also be improved:
```
# cardano-cli transaction view --tx-file tx-mask.body
Command failed: transaction view  Error: tx-mask.body: TextEnvelope type error:  Expected one of: TxSignedByron, TxSignedShelley, Tx AllegraEra, Tx MaryEra Actual: TxBodyMary
```

I think the issue is that I provide a `raw tx` file instead of a signed one but the error is quite misleading. 

Suggestion --> `Expected a TxSigned; Actual: TxBodyMary`

**Comment by rphair** [comment]
If the undocumented convention of `--tx-body-file` for a raw/unsigned transaction and `--tx-file` for a signed transaction is not kept, the error message is also not helpful in determining the real problem:

```
$ cardano-cli transaction view --tx-body-file withdraw.signed
```

`
Command failed: transaction view  Error: withdraw.signed: TextEnvelope type error:  Expected one of: TxUnsignedByron, TxUnsignedShelley, TxBodyAllegra, TxBodyMary Actual: TxSignedShelley
`

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
