### ISSUE TITLE
[BUG] -  cardano-cli: internal error: Unable to commit 1048576 bytes of memory

### ISSUE THREAD

**Issue by ThaiTheo** [input-output-hk/cardano-node#2405]
**External**

**Other**

**Summary**
Querying the Ledger using cardano-cli will result in memory commit error

**Steps to reproduce**
1. Go to node running cardano-node
2. Run command 'cardano-cli query ledger-state --allegra-era --mainnet | grep '"publicKey": "f137e6702bb09babf88cc93c93dffd64379d5d43bdbe3ce870ff5c54"' -A 2' as user cardano with environment variables set properly
3. See error

**Expected behavior**
Entries shown where the publicKey has been found.

**System info (please complete the following information):**
- OS: CentOS
- Version: 8
- Node version: 1.25.1

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/41171413/108927255-3a1e9780-7640-11eb-8dc5-210a89d6d2ef.png)

- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**
Same happens if one tries to make a dump of the ledger in .json format, as used by slot leaders analyst apps

**Comment by r-tde** [comment]
Erros on committing memory just mean that the process run out of memory. Well, more specifically tried to allocate that size (`1048576`) and could - crashed. Increase your memory (or swap, though it doesn't always address the issue).

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.

**Comment by Titan-C** [comment]
I'm experiencing this error but on the cardano-node itself.
cardano-node-1.35.7 on mainnet.
Using hydra binaries for linux
Running on Archlinux
```log
Apr 29 15:28:44 darktitan cardano-node[86767]: [darktita:cardano.node.ChainDB:Notice:2604] [2023-04-29 13:28:44.75 UTC] Chain extended, new tip: 61a286d23574d8988d41d389538bdeeed68a6884422ee410d7523342359ed47b at slot 86484910
Apr 29 15:28:46 darktitan cardano-node[86767]: [darktita:cardano.node.ChainDB:Notice:2604] [2023-04-29 13:28:46.03 UTC] Chain extended, new tip: d88c773279ab750da0896c7925263acff599ed3bef363ac78e3da34a9f265678 at slot 86485257
Apr 29 15:28:47 darktitan cardano-node[86767]: [darktita:cardano.node.ChainDB:Notice:2604] [2023-04-29 13:28:47.28 UTC] Chain extended, new tip: c4ffc72a26f382b4fa8060da2d2116f73f59cacd9f0e60d4086fda98f66157b3 at slot 86485496
Apr 29 15:28:48 darktitan cardano-node[86767]: [darktita:cardano.node.ChainDB:Notice:2604] [2023-04-29 13:28:48.63 UTC] Chain extended, new tip: 1e820582049ae223049cc8c10daa2ea0dd1fc43f62acafe14ee79a937ac0a227 at slot 86485841
Apr 29 15:28:52 darktitan cardano-node[86767]: cardano-node: internal error: Unable to commit 1048576 bytes of memory
Apr 29 15:28:52 darktitan cardano-node[86767]:     (GHC version 8.10.7 for x86_64_unknown_linux)
Apr 29 15:28:52 darktitan cardano-node[86767]:     Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
Apr 29 15:29:54 darktitan systemd[1]: cardano-node-mainnet.service: Main process exited, code=dumped, status=6/ABRT
Apr 29 15:29:54 darktitan systemd[1]: cardano-node-mainnet.service: Failed with result 'core-dump'.
Apr 29 15:29:54 darktitan systemd[1]: cardano-node-mainnet.service: Consumed 44min 46.619s CPU time.
Apr 29 15:30:54 darktitan systemd[1]: cardano-node-mainnet.service: Scheduled restart job, restart counter is at 1.
```
