### ISSUE TITLE
[BUG] - CPU spikes during epoch boundaries and at 48h time mark causing important gaps in block production

### ISSUE THREAD

**Issue by angelstakepool** [input-output-hk/cardano-node#2408]
*External* 

**Area**
*Other:  Interruption in Blocks Production for SPO's pools at epoch transition and 48h time mark*  

**Summary**
Both during epoch transitions and at 48h time mark, most of [ALL] nodes experience a significant CPU spike, causing the network to become stagnant. If we have a slot scheduled during these timeframes, that will most likely be a missed block

My pool was scheduled to mint a block at slot #30 (21:45:21 UTC) into epoch 250 and according to the BP node's log, it did not even attempt to produce the block. All in all, during this transition, 2:30 min elapsed without a block produced by SPO's pools

**Steps to reproduce**
Calculate pool's leaderlogs and then be unlucky to have a slot assignment during these time frames

**Expected behavior**
A smooth epoch transition, and same for 48h mark

**System info (please complete the following information):**
- OS: Ubuntu
- Version: 20.04
- Node version: 1.25.1

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/60072039/109082731-82869580-76d2-11eb-9bde-540bad788b97.png)

**Additional context**
Leaderlogs schedule according to Andrew's cncli leaderlogs

![image](https://user-images.githubusercontent.com/60072039/109083588-33416480-76d4-11eb-9915-f45e58803499.png)

**Comment by btbf** [comment]
This is a serious flaw. It will affect rewards in many pools. It should be fixed as a top priority.

**Comment by CyberCyclone** [comment]
The 48 hour bug is being discussed here: https://github.com/input-output-hk/cardano-node/issues/2205

**Comment by erikd** [comment]
Closing in favor of #2205 .
