### ISSUE TITLE
Set up the testnet, block to 2287371 is stuck out of sync

### ISSUE THREAD

**Issue by bocaigo** [input-output-hk/cardano-node#2411]
It was normal before, but it will not move after newly arriving in this block. The problem of data deletion and up node is still the same
Does the testnet have a block explorer?

Start the docker:NETWORK=testnet docker-compose up
[root@iZwz ada_server]# ./cardano-cli query tip --testnet-magic 1097911063
{
    "blockNo": 2287371,
    "headerHash": "aef965e0a82c1103e78454cfc6153996410126aa826176a3a16bb38d729d9f27",
    "slotNo": 18023833
}
![image](https://user-images.githubusercontent.com/51990336/109117894-8f13f800-777d-11eb-9820-64da01545355.png)

docker log:
[cardano.node.resources:Info:25] [2021-02-25 07:29:02.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94559.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.96908546352e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12794888e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:03.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94559.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.96908546352e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12794888e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:04.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94559.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.96908546352e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12794888e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:05.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94559.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.96908546352e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12794888e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:06.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94559.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.96908546352e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12794888e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:07.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94559.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.96908546352e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12794888e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:08.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94560.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.969116324472e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12715136e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:09.61 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94560.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.969116324472e12),("Threads",Number 16.0),("CentiCpu",Number 389552.0),("Live",Number 2.12715136e8)]
[cardano.node.resources:Info:25] [2021-02-25 07:29:10.62 UTC] fromList [("GcsMajor",Number 332.0),("RSS",Number 6.17910272e8),("kind",String "Resources"),("GcsMinor",Number 94560.0),("CentiBlkIO",Number 32.0),("CentiGC",Number 63920.0),("CentiMut",Number 325609.0),("Alloc",Number 2.969116324472e12),("Threads",Number 16.0),("CentiCpu",Number 389553.0),("Live",Number 2.12715136e8)]

**Comment by bocaigo** [comment]
cardano-rest-3.1.1

**Comment by SomethingUseful** [comment]
I get stuck on the same block. tried three times to clear data directory. same issue. InvalidBlock then does not proceed.
Ubuntu 18.04.5 LTS
Cardano Node 1.26.2

**Comment by SomethingUseful** [comment]
Cant get past this block...
Tried more CPUs. Tried way more RAM 16GB. Tried faster disks. Every time. Stuck.

$ cardano-cli query tip --testnet-magic 1097911063                                                                
{
    "blockNo": 2287371,
    "headerHash": "aef965e0a82c1103e78454cfc6153996410126aa826176a3a16bb38d729d9f27",
    "slotNo": 18023833
}

**Comment by SomethingUseful** [comment]
i think issue is related to 1.26.2. i ran 1.26.1 instead and it seems to be working.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
