### ISSUE TITLE
Drop dependency on pvss package

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-node#242]
The [pvss] package was needed in the old codebase as part of the Ouroboros Classic implementation.

The new codebase does not implement Ouroboros Classic and thus does not use the SCRAPE VSS scheme. We still have a dependency on the `pvss` package however, but this should be dropped.

It is used in two places:

1.  `src/Cardano/CLI/Legacy/Byron.hs` where the `LegacyDelegateKey` contains a `lrkVSSKeyPair :: Scrape.KeyPair`. This key pair appears to be unused (which is good, there's no use for it). The old binary format contained these things, so we still need to be able to decode the old format, but we do not need to store the result. So we do not need the `KeyPair` type imported from `Crypto.SCRAPE`

2. `src/Cardano/CLI/Ops.hs` where the only use is `Scrape.keyPairGenerate` which is used to fill in the `lrkVSSKeyPair` as part of `encodeLegacyDelegateKey`. But if this member is removed then it does not need to be generated. The encoder could use dummy values to keep the same legacy format because they will never be used.

[pvss]: http://hackage.haskell.org/package/pvss

**Comment by Jimbo4350** [comment]
`pvss` removed
