### ISSUE TITLE
[EN] - Docker / Release (bin) for ARMv8 / aarch64 is needed

### ISSUE THREAD

**Issue by rorgaz** [input-output-hk/cardano-node#2420]
**Internal/External**
Both

**Area**
I dont know

**Describe the feature you'd like**
aarch64 / armv8 Docker or release (bin)

**Describe alternatives you've considered**
Compile from code is a nightmare on RPI4 8gb

**Additional context / screenshots**
None

**Comment by ThaiTheo** [comment]
Why don't you cross compile (i.e. compile on another os for armv8)?

**Comment by rgoerwit** [comment]
I've nearly gotten arm7 compiled for Pi 4; stopped dead by a GHC panic:  https://github.com/input-output-hk/cardano-node/issues/2438 (on getting GHC to build in the first place, see https://www.haskell.org/ghc/blog/20200515-ghc-on-arm.html).  I agree that the Pi 4 is a good platform to look at, that embodies a lot of what we're looking for here as a community - it's cheap, efficient and doesn't just put us in one or another vendor's cloud.  Would be nice to be able to leverage it.

**Comment by angerman** [comment]
Armv7 will not work. You’ll at least want to build aarch64. I have been proving fully static pre-built aarch64 builds of cardano-node and cardano-cli. 
There is a telegram support group for this: https://t.me/joinchat/FeKTCBu-pn5OUZUz4joF2w

please understand that there is currently no official support for this.

**Comment by dcoutts** [comment]
Given that there is no official support for this, it's important that you be able to support yourself. Therefore it would be unhelpful for us to make make it deceptively easy. That would lead people into trouble.

**Comment by dcoutts** [comment]
To be clear, we don't want to discourage people, but the early experimenters need to know what they are doing. Many of the developers are also keen to make it work well in the end. I have an RPi4 myself for this purpose and @angerman has been putting in a lot of effort to make it work.

But there's a world of difference between that and declaring it an officially supported platform.

**Comment by DanTup** [comment]
> But there's a world of difference between that and declaring it an officially supported platform.

Is there an appropriate place to request/vote on it being an officially supported platform or is it out of the question?
