### ISSUE TITLE
[FR] - Layered Docker container image

### ISSUE THREAD

**Issue by Preskton** [input-output-hk/cardano-node#2423]
**Internal/External**
External

**Area**
Other - Development Experience & Deployment Runtime

**Describe the feature you'd like**
As a cardano-node developer, when I'm working on code, I'd want to deploy new Docker-based builds of my changes as quickly as possible to reduce the cycle time between a change and observing that change in a local build. To do so, I want the Docker image that is produced by the build to create multiple layers so the underlying container runtime can have a chance at caching frequently used layers. When I get a cache hit, there's less time involved in building, pulling, and starting up a new image.

**Describe alternatives you've considered**
None - will investigate and see if there are other approaches.

**Additional context / screenshots**
This is an optimization of a containerized build, so may be lower in priority if there are other Docker container-related issues in the backlog.

Neat article about optimizing `nix` builds with Docker layering - https://grahamc.com/blog/nix-and-layered-docker-images.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
