### ISSUE TITLE
[BUG] - Content out of date (refers to Shelley) and missing (TODO) on one section

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-node#2425]
**Internal**

**Area**
*Other*   out of date and missing content

**Summary**
https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/shelley-genesis.md
* refers to shelley
* has a TODO at the bottom that needs to be completed

**Steps to reproduce**
Go to https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/shelley-genesis.md
See it says "Shelley" and has a TODO at the bottom

**Expected behavior**
Update the content
Remove era-specific references in future as shows it is dated i.e. don't replace Shelley with Mary

**System info (please complete the following information):**
All

**Screenshots and attachments**
No

**Additional context**
No

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
