### ISSUE TITLE
[FR] - Universal .skey/.vkey signing & verification method for cardano-cli

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2427]
*External* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...)

**Describe the feature you'd like**
Please include additional functions to do basic signing and verification of content via secret/private keys. 
Signing/Verification Featureset like jcli command with https://github.com/input-output-hk/jormungandr

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by gitmachtl** [comment]
Is now available via the tool cardano-signer:
https://github.com/gitmachtl/cardano-signer
