### ISSUE TITLE
[FR] - Improve performance of cardano-cli query ledger-state

### ISSUE THREAD

**Issue by robinboening** [input-output-hk/cardano-node#2451]
**External**

**Area**
`cardano-cli query ledger-state`

**Describe the feature you'd like**
Currently `cardano-cli query ledger-state` consumes a lot of memory, up to the point where the cardano node crashes. It would be great to improve the performance of this command.

**Describe alternatives you've considered**
Disclaimer: I was reading some code, mainly this part here: https://github.com/input-output-hk/cardano-node/blob/91f25c2564c05b23a1356bac37f18fa9fd6ed2ac/cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs#L357-L377 but I am not familiar with Haskell at all.

The little I believe to understand (please correct if wrong) is that the data input is loaded into memory (and in case `mOutFile` is given it'd be dumped into a file) - the bigger the data, the more memory is consumed.

The idea: Instead of loading the entire input, a buffered stream could make this command more stable and performant.

**Comment by snajjar** [comment]
Seconding this. I can't run this command anymore, it eats up all the memory on my local machine (excepted for the ram used by cardano-node itself) then crashes. Happens on my servers too, the ledger is just too big now.

Seems like it's a very inefficient way of dumping big data into a file (or output). It should be written chunk by chunk to a file to save up ram. If the data retrieved by cardano-cli from the blockchain/node itself is not json (the output format), it should be still saved as json, then re-edited and augmented with each chunk as the process go. Unfortunately I don't know Haskell as well :/

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
