### ISSUE TITLE
[FR] - Publish logs for chairman tests run in Hydra

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#2482]
*Internal*   if an IOHK staff member.

**Describe the feature you'd like**
Currently logs are written to files in chairman tests and are no accessible when run in Hydra.  These logs need to be published so that when they fail, we have more information to work with.

See https://input-output-rnd.slack.com/archives/GR599HMFX/p1614905404000600?thread_ts=1614859638.099000&cid=GR599HMFX

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
