### ISSUE TITLE
[BUG] - Core node migration.

### ISSUE THREAD

**Issue by djalillounis** [input-output-hk/cardano-node#2499]
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
I have noticed some high CPU in my node post mary HFC, and I am planing to migrate my pool to a different server.
I would like to ensure that if I copy the needed files (certs and VFR etc...) +(config files) would be enough.

I am not sure if the change on the public IP of the core will have any sort of  issues?

And what if I keep both server running the same pool with the same certs and file only the public IP will be different?

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: Ubuntu
- 20.04
-20.1

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
