### ISSUE TITLE
tracing chain quality

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#250]
definition of chain quality (named `density`):
```
|blocks| / |slots|
```

tracing and monitoring of chain quality:
* threshold?

(request by @disassembler)

**Comment by CodiePP** [comment]
definition of chain quality in CSL: https://github.com/input-output-hk/cardano-sl/blob/develop/db/src/Pos/DB/Block/Logic/Util.hs#L93
(?)

**Comment by mrBliss** [comment]
Some pointers on how to implement this:

The traced event to watch for is [`ChainDB.SwitchedToChain`](https://github.com/input-output-hk/ouroboros-network/blob/6016f49aa11c429df38033e2c0739972eb1ceaa2/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Types.hs#L352), which is part of [`ChainDB.TraceAddBlockEvent`](https://github.com/input-output-hk/ouroboros-network/blob/6016f49aa11c429df38033e2c0739972eb1ceaa2/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Types.hs#L285)

You can use this snippet to calculate the chain density (not quality, which is a different concept in the Ouroboros paper, which we can't measure):
```haskell
import Ouroboros.Network.Point (fromWithOrigin)

chainDensity :: HasHeader blk
             => AnchoredFragment (Header blk) -> Maybe Rational
chainDensity frag
    | slots == 0
    = Nothing
    | otherwise
    = Just $ toRational blocks / toRational slots
  where
    -- Slot of the tip - slot @k@ blocks back. Use 0 as the slot for genesis
    slots  = unSlotNo (fromWithOrigin 0 (AF.headSlot frag))
           - unSlotNo (fromWithOrigin 0 (pointSlot (AF.anchorPoint frag)))
    -- Includes EBBs
    blocks = AF.length frag
```

**Comment by mrBliss** [comment]
Update:
```haskell
import Ouroboros.Network.Point (fromWithOrigin)

chainDensity :: HasHeader blk
             => AnchoredFragment (Header blk) -> Maybe Rational
chainDensity frag
    | slots == 0
    = Nothing
    | otherwise
    = Just $ toRational blocks / toRational slots
  where
    -- Slot of the tip - slot @k@ blocks back. Use 0 as the slot for genesis
    slots  = unSlotNo (fromWithOrigin 0 (AF.headSlot frag))
           - unSlotNo (fromWithOrigin 0 (AF.lastSlot frag))
    blocks = unBlockNo (fromMaybe 0 (AF.headBlockNo frag))
           - unBlockNo (either (const 0) blockNo (AF.last frag))
```
(I did not typecheck this)

**Comment by CodiePP** [comment]
one block still missing:
```
[iohk.cardano.node.CoreId 0.density.ChainDB:Notice:113] [2019-10-23 07:03:12.92 UTC] density = 0.999537251272559
[iohk.cardano.node.CoreId 0.density.ChainDB:Notice:113] [2019-10-23 07:03:12.92 UTC] density based on blocks:2160 slots:2161
```

**Comment by mrBliss** [comment]
My findings:

After three blocks we have the following fragment:
```
block:        E R R
slot number:  0 0 1
block number: 0 1 2
```
where `E` = EBB and `R` = Regular block.

So using the code snippet above: `slots = 1 - 0 = 1`, `blocks = 2 - 0 = 2`, hence chain density = 2 / 1 = 2.0 :confused: 

The reason for this is the genesis EBB with block number 0, which should not contribute to the total number of blocks. Looking at the next EBBs, we see:
```
blocks:       E R R ...     R |     E     R     R ...     R | E         R     R
slot number:  0 0 1 ... 21599 | 21600 21600 21601 ... 43199 | 43200 43200 43201
block number: 0 1 2 ... 21586 | 21586 21587 21588 ... 43175 | 43175 43176 43177
```
So EBBs have the block number of their predecessor, or 0 in case of the genesis EBB, but the slot number of their successor :confounded:. Fortunately, the chain density is only confused by the genesis EBB. So we can *special case the genesis EBB*:

```haskell
    ... -- unchanged
    -- Block numbers start at 1. We ignore the genesis EBB, which has block number 0.
    blocks = unBlockNo (fromMaybe 1 (AF.headBlockNo frag))
           - case unBlockNo . blockNo <$> AF.last frag of
               -- Empty fragment, no blocks. We have that @blocks = 1 - 1 = 0@
               Left _ -> 1
               -- The oldest block is the genesis EBB with block number 0,
               -- don't let it contribute to the number of blocks
               Right 0 -> 1
               Right b -> b
```
(not typechecked)
