### ISSUE TITLE
[BUG] - cardano-node: unknown RTS option: -N2

### ISSUE THREAD

**Issue by woltere** [input-output-hk/cardano-node#2500]
**External**

**Area**
*Other*   cardano-node build

**Summary**

After building using instructions from https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html
Using tag 1.25.1.
Build on ubuntu 20.04
arch riscv64

Starting the cardano-node always gives the output below.

```
cardano-node
cardano-node: unknown RTS option: -N2
cardano-node:
cardano-node: Usage: <prog> <args> [+RTS <rtsopts> | -RTS <args>] ... --RTS <args>
cardano-node:
cardano-node:    +RTS    Indicates run time system options follow
cardano-node:    -RTS    Indicates program arguments follow

--- 8< ----
```

cardano-cli works like expected

**Steps to reproduce**
1. On ubuntu 20.04 on riscv64 build using https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html
2. run cardano-node
3. `cardano-node: unknown RTS option: -N2....`

**Expected behavior**

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04 (riscv64)

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by juampe** [comment]
Try with this patch
PR  in https://github.com/input-output-hk/cardano-node/pull/2690
```
diff --git a/cardano-node/cardano-node.cabal b/cardano-node/cardano-node.cabal
index 28feae4a..18e7e137 100644
--- a/cardano-node/cardano-node.cabal
+++ b/cardano-node/cardano-node.cabal
@@ -156,7 +156,11 @@ executable cardano-node

   if arch(arm)
     ghc-options:        "-with-rtsopts=-T -I0 -A16m -N1 --disable-delayed-os-memory-return"
-  else
+
+  if arch(riscv64)
+    ghc-options:        "-with-rtsopts=-T -I0 -A16m --disable-delayed-os-memory-return"
+
+  if !arch(arm) && !arch(riscv64)
     ghc-options:        "-with-rtsopts=-T -I0 -A16m -N2 --disable-delayed-os-memory-return"

   other-modules:        Paths_cardano_node
```

2e9532ec0f86:/cardano# cardano-cli --version
cardano-cli 1.26.2 - linux-riscv64 - ghc-8.10
git rev 3531289c9f79eab7ac5d3272ce6e6821504fec4c

**Comment by woltere** [comment]
If have build ghc-8.10.4 with the patches for a registred compiler and SMP suppot and it's building tag 1.27.0.

I have also complied a cross compiler with these patches. Some dependencies can't be cross compiled at this moment without changes.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
