### ISSUE TITLE
[FR] - Modify `cardano-cli query tip` to return the current era

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-node#2509]
**Internal/External**
*Internal* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
`cardano-cli query tip` command should additionally return the current era.

**Comment by gitmachtl** [comment]
https://github.com/input-output-hk/cardano-node/pull/2470#issuecomment-801396794

**Comment by gitmachtl** [comment]
Can anyone hook me up with a haskell code snippet for the Query.hs? The current era is available and i think there is now also a toJSON available for it.
