### ISSUE TITLE
1.26.0 - all `rts_gc_` metrics are returning 0

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2515]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
node metrics

**Summary**
All `rts_gc_` node metrics are returning 0 in 1.26.0 tag.

**Steps to reproduce**
1. start a node using tag 1.26.0 and let it sync
2. run:
```
$ curl -s http://127.0.0.1:PROMETHEUS_PORT/metrics | grep rts_gc_
rts_gc_par_tot_bytes_copied 0
rts_gc_num_gcs 0
rts_gc_max_bytes_slop 0
rts_gc_num_bytes_usage_samples 0
rts_gc_wall_ms 0
rts_gc_max_bytes_used 0
rts_gc_init_cpu_ms 0
rts_gc_bytes_copied 0
rts_gc_init_wall_ms 0
rts_gc_peak_megabytes_allocated 0
rts_gc_par_max_bytes_copied 0
rts_gc_current_bytes_slop 0
rts_gc_cpu_ms 0
rts_gc_bytes_allocated 0
rts_gc_current_bytes_used 0
rts_gc_par_avg_bytes_copied 0
rts_gc_mutator_cpu_ms 0
rts_gc_gc_wall_ms 0
rts_gc_mutator_wall_ms 0
rts_gc_gc_cpu_ms 0
rts_gc_cumulative_bytes_used 0
```

**Expected behavior**
All the above metrics should have correct non-zero values

**System info (please complete the following information):**
- OS: Ubuntu 20.04

**Comment by gitmachtl** [comment]
was solved by starting the node with the RTS flags: `--disable-delayed-os-memory-return -T -I0 -A16m`

**Comment by r-tde** [comment]
Any clear documentation to the RTS related flags and their impact? (not from official Haskell docs that is)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
