### ISSUE TITLE
[FR] - Prevent Nodes from connecting to themselves

### ISSUE THREAD

**Issue by bruceharrison1984** [input-output-hk/cardano-node#2517]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
Currently, a relay can open a connection back to itself if it is referenced in its own tolopogy.json file. 

This can easily occur if you have multiple relays behind a SRV record, and reference the SRV record from the relay with the correct tenancy.

This seems like a perfectly valid configuration in situations where you want all of your relays to be aware of their immediate peers, such as in the case of an internal SRV record within a private network. 

```js
{
  "Producers": [
    {
      "addr": "relays-new.cardano-mainnet.iohk.io",
      "port": 3001,
      "valency": 1
    },
    {
      "addr": "block-producer.domain.svc.cluster.local",
      "port": 3001,
      "valency": 1
    },
    {
      "addr": "internal-relays.domain.svc.cluster.local", //this represents an internal SRV record that contains all local relays
      "port": 3001,
      "valency": 3
    }
  ]
}
```

This currently results in the relay opening a connection back to itself, the consequences of which I am not sure.

Current mitigation requires generating a list of local relays, and excluding the relay that will be initiating the connection before generating the topology.json. This is cumbersome and potentially error prone.

**Describe alternatives you've considered**
A simple check to see if the destination IP matches the current IP, and if it does, then disregard that connection. 

I realize that in cases where nodes are exposed to the internet, this check could be ineffective due to internal/external relay IPs not matching, but this solution solves cases when all relays live within the same private network, without breaking current behavior.

**Comment by gitmachtl** [comment]
Just as an info: As far as i know, SRV records are not officially supported yet.

**Comment by bruceharrison1984** [comment]
I'm my case I was using an SRV record. It seems to work fine, and all servers are properly discovered through the record. I believe that the current setup supports this just fine, which is what the valency parameter is for, but I digress.

The actual method for the servers being recognized seems inconsequential to the ask, which is that the server probably shouldn't open connections back to itself.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
