### ISSUE TITLE
[BUG] - CNTools failed to load common env file

### ISSUE THREAD

**Issue by Craftoncu** [input-output-hk/cardano-node#2520]
*External*  

**Area**
Setup

**Summary**
CNTools failed to load common env file

**Steps to reproduce**
1. clean install following https://cardano-community.github.io/guild-operators/#/Build/node-cli
2. enter scripts dir in cnode_home
3. execute ./cntools 

**Expected behavior**
CNTools in online mode

**System info
- OS: Ubuntu
- Version 20.04
- Node version 1.26.0
- CLI version 1.26.0

**Comment by rdlrt** [comment]
CNTools is not maintained by IOG - thus, it's not fair to raise issues against cardano-node repo, given the lack of details, best to use [telegram workgroup](https://t.me/CardanoStakePoolWorkgroup) for issues initially.

**Comment by Craftoncu** [comment]
Fix: Do nothing! Node has to be fully synced.
