### ISSUE TITLE
[BUG] - dropping era param support on 1.26.0 query command causes failures in 3rd-party tools and tutorials

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2523]
**External**

**Area**
cardano-cli commandline

**Summary**
The drop of the command line parameter for the era like `--mary-era, --allegra-era, --shelley-era` in the query commands is causing many 3rd party tools and also tutorials to fail. Please make this at least an optional parameter for the next releases, but don't make the cardano-cli fail if you provide it for the right current era. Many tools are currently using it because 1.25.1 needs it, this is a bit of a harsh breaking change. Currently the tools are also using this method to figure out the current era by letting the cli exit with an error code if the era is wrong. Which would result in --byron-era right now with the implementation. 

This also relates to: https://github.com/input-output-hk/cardano-node/issues/2509

**Expected behavior**
Cardano-CLI 1.26.* should not exit and fail with an error code if the current era parameter is provided via the command line. It can be a hidden parameter and not listed in the normal help output, but the cli should support this for the next major releases to make it a smoother transition.

**Comment by Jimbo4350** [comment]
@gitmachtl from now on I can leave CLI deprecated params as a no op for a specified amount of time. What's a reasonable time to you?

**Comment by gitmachtl** [comment]
> @gitmachtl from now on I can leave CLI deprecated params as a no op for a specified amount of time. What's a reasonable time to you?

2 Releases?

**Comment by benapetr** [comment]
proper setup would be for them to emit a visible warning, there is no need to remove them after 2 releases, just keep them in the codebase as long as it doesn't really cause any real problems.

**Comment by robinboening** [comment]
> proper setup would be for them to emit a visible warning, there is no need to remove them after 2 releases, just keep them in the codebase as long as it doesn't really cause any real problems.

I like clean code bases, hence my suggestion to eventually remove deprecated code after some time. It needs to be communicated well and people need to be given some time to prepare for the change. Hence, I suggest printing a deprecation notice telling you the future version the feature will be removed (e.g. with the next major version bump).

**Comment by robinboening** [comment]
The most important thing is to agree on a process defining how deprecations should be handled. Not case by case, but always.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
