### ISSUE TITLE
[BUG] - Relay node  cli command : Query utxo \ --address  not updating current balance after mining token.

### ISSUE THREAD

**Issue by XFaramirX** [input-output-hk/cardano-node#2524]
**External**

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Summary**
When using the command "query utxo \ --address" to fech balance doesnt display the current/real balance after minting a token on the mainnet.

**Steps to reproduce**
1. Go to relay node and use command to query balance:

cardano-cli query utxo \
--address addr1q9q9n45d3x28u8xaccu8qgzky0kgp07whvp3tma9suva6m5wrudjuqt377e76d28r2z7v8t8r2qn72lyzdgzpldy0nhsl0mhqe \
--mainnet

2. Now go to explorer and check same address: 
https://explorer.cardano.org/en/address?address=addr1q9q9n45d3x28u8xaccu8qgzky0kgp07whvp3tma9suva6m5wrudjuqt377e76d28r2z7v8t8r2qn72lyzdgzpldy0nhsl0mhqe 

3. Compare UTXO and balance on current address dont match

**Expected behavior**
Relay node CLI command should update the address balance to 0 as shown on the explorer. 

- OS: Mint
- Version 20.01
- 1.26

**Screenshots and attachments**

RELAY CLI: 
![image](https://user-images.githubusercontent.com/59751331/111912298-f6e4f800-8a36-11eb-8a25-70b79708b6a9.png)

EXPLORER: 
![image](https://user-images.githubusercontent.com/59751331/111912282-e5035500-8a36-11eb-8082-6b589fd7807d.png)

**Additional context**
It seems to be caused when minting a token and send it to another address with normal transactions seems to work.

**Comment by XFaramirX** [comment]
Seems to be related to this bug as well: https://github.com/input-output-hk/cardano-node/issues/2509

**Comment by gitmachtl** [comment]
Just minted Assets on 1.26.0 like normal.

**Comment by Jimbo4350** [comment]
@XFaramirX I think your local node was not synced far enough:
```
cardano-cli query tip --mainnet                 
{
    "blockNo": 5486354,
    "headerHash": "77e2422279214964eb71a5cd819e3baea17043200565d47ca420440b8f924d94",
    "slotNo": 24705895
}
cabal exec cardano-cli -- query utxo --address addr1q9q9n45d3x28u8xaccu8qgzky0kgp07whvp3tma9suva6m5wrudjuqt377e76d28r2z7v8t8r2qn72lyzdgzpldy0nhsl0mhqe --mainnet
                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------
```

**Comment by XFaramirX** [comment]
Relay node is synced but still shows same balance even tho i spend it already.
![image](https://user-images.githubusercontent.com/59751331/112143685-3b42d600-8ba6-11eb-90ad-0c7415e43326.png)

**Comment by gitmachtl** [comment]
Hmm... we're in Epoch 255, not 254.

**Comment by XFaramirX** [comment]
Working now !  Sorry about that.
