### ISSUE TITLE
[FR] - Cross-compiler support

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/cardano-node#2525]
**External**

**Area**
*Other*   Compilation.

**Describe the feature you'd like**
I've been trying to compile `cardano-cli` only for my Raspberry Pi 3B for a week. I know with only 1GB ram this board is not enough to serve as a node. My purpose is to make it an air-gapped device for KES key renewal which should require `cardano-cli` only. However, package `unix-bytestring` depended by `cardano-cli` seems not able to work in cross-compilation.

```
Warning: unix-bytestring.cabal:58:40: version operators used. To use version
operators the package needs to specify at least 'cabal-version: >= 1.8'.
Configuring unix-bytestring-0.3.7.3...
Preprocessing library for unix-bytestring-0.3.7.3..
clang-9: warning: -Wl,-z,noexecstack: 'linker' input unused [-Wunused-command-line-argument]
clang-9: warning: argument unused during compilation: '-fuse-ld=gold' [-Wunused-command-line-argument]
clang-9: warning: -Wl,-z,noexecstack: 'linker' input unused [-Wunused-command-line-argument]
clang-9: warning: argument unused during compilation: '-fuse-ld=gold' [-Wunused-command-line-argument]
Iovec.hsc:67:9: warning: 'hsc_alignment' macro redefined [-Wmacro-redefined]
#define hsc_alignment(t ) hsc_printf (     "%lu", (unsigned long) offsetof(struct {char x__; t (y__); }, y__));
        ^
/Volumes/cardano-pi-sdk/prebuilt/lib/arm-linux-gnueabihf-ghc-8.10.4/template-hsc.h:98:9: note: previous definition is here
#define hsc_alignment(x...)                                           \
        ^
1 warning generated.
src/System/Posix/Types/Iovec.hsc:67 directive let cannot be handled in cross-compilation mode
```

That is kind of a deal-breaker for cross-compiler. Is it possible to work around this package? I also tried to build it on Raspberry Pi. With 1GB RAM and 2GB swap, it always gets stucked during the build stage.

**Comment by erikd** [comment]
RPI 3 is 32 bit right? This code base does not compile for 32 bit systems, and making it do so, would likely be a lot of work.

**Comment by siegfried** [comment]
RPI 3 is 64-bit capable while Raspbian is 32-bit. I think I can change the OS.

**Comment by erikd** [comment]
Using the Nix build infrastructure, we already cross-compile from 64 bit Linux to 64 bit Windows, so cross compiling is certainly possible.

**Comment by siegfried** [comment]
A manual of how you cross-compile it with Nix would be a great help. I couldn't find it with Google.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
