### ISSUE TITLE
The producer nodes are displaying `missed slots`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2526]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
- node

**Summary**
The producer node is displaying missed slots (less in 1.25.1 and more in 1.26.0) --> `cardano_node_metrics_slotsMissedNum_int`

**Steps to reproduce**
1. start a producer node
2. let it run 24 hours
3. check the values of the `cardano_node_metrics_slotsMissedNum_int` metric

**Expected behavior**
There should not be any missed slots - the producer node should know if it was the leader or not of each slot.

**System info (please complete the following information):**
- OS: Ubuntu
- node 1.26.0

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/29144964/111975804-ae4a3f00-8b09-11eb-9a88-f67758d3a7c3.png)

**Additional context**

**Comment by dorin100** [comment]
In 1.25.1, the missed slots are displayed only at epoch boundry.

**Comment by leslieonline27** [comment]
This is happening after around 12 hours of a restart of the block producer.  I'm not able to confirm whether it happened as much in 1.25.1, but there is definitely too many missed slots in this version.  Definitely does not appear to be a resource issue

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
