### ISSUE TITLE
[BUG] - Clock skew can go undetected due to unfortunate combination of systemd and ntpd packaging bugs

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#2529]
**Internal**

**Node operation**

**Summary**
As is well-known, clock skew causes the node to suspend its peers, because the blocks downloaded from them are "in the future" (see the error message in the next section).

Once all peers are suspended, the node chain degrades, and after a while it obtaining the ledger state.

The node periodically attempts reconnecting to its peers, so it does see the transaction and block traffic (although blocks are rejected), which can make the appearances confusing.

Normally, clock skew is prevented by a functioning NTP daemon -- however, due to an unfortunate interaction of software bugs and packaging, it turns out this can go undetected.

Basically, recent `libc` versions are aliasing the `open` syscall to `openat`, and the latter has been absent from syscall whitelists for `ntpd`, thereby killing it.  Normally `systemd` would detect the situation as service failure -- which would make it detectable in the logs -- however, due to a bug it might not notice it, reporting its status as green.

Solution:  ensure that `ntpd` is operating well -- either via upgrade of `ntpd` or `systemd`, or, alternatively, by disabling syscall whitelisting.

**Initial `InFutureExceedsClockSkew` error**
The initial error looks like this:
```Application Exception: 54.66.194.65:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 49, blockPointHash = ce15954211df0f4f40555770f05efdeb15f8e9414cc4c85d821eaf130aae70a8})) (InFutureExceedsClockSkew (RealPoint (SlotNo 49) ce15954211df0f4f40555770f05efdeb15f8e9414cc4c85d821eaf130aae70a8))"},"sev":"Error","env":"1.26.0:7de9c","msg":"","app":[],"host":"node-1","pid":"15290","ns":["cardano.node.DnsSubscription"],"at":"2021-03-20T00:04:59.19Z"}
{"thread":"103","loc":null,"data":{"address":"54.66.194.65:3001","kind":"ErrorPolicyTrace","event":"ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 49, blockPointHash = ce15954211df0f4f40555770f05efdeb15f8e9414cc4c85d821eaf130aae70a8})) (InFutureExceedsClockSkew (RealPoint (SlotNo 49) ce15954211df0f4f40555770f05efdeb15f8e9414cc4c85d821eaf130aae70a8))))) 200s 200s
```

**Acknowledgements**

Thanks to @cleverca22 for recognising the duplicitous `ntpd` status reporting and the `openat` syscall whitelisting issue.

**Comment by dcoutts** [comment]
Things to consider:

 * could the node notice that it consistently receives blocks too late, and its blocks never make it into the chain
 * run an extra ntp client just to detect and warn (not to correct)

**Comment by dcoutts** [comment]
Another way to notice this easily:

```
InvalidBlock
  (At
    (Block {
      blockPointSlot = SlotNo 40,
      blockPointHash = 4cf76b8...}))
   (InFutureExceedsClockSkew (RealPoint (SlotNo 40) 4cf76b8...)))
```

Seeing _lots_ of invalid blocks that are invalid due to `InFutureExceedsClockSkew` is a very clear and very strong indicator of our own node's clock being off.

**Comment by deepfire** [comment]
I guess one question is -- is there an error state that we can detect?

Points that seem relevant:
  1. if the clock skew error appears for blocks coming from a single peer, then it's likely that this particular peer is bonkers.
  2. if the clock skew error appears for blocks coming from all peers, then it's likely that we are bonkers.
  3. A single clock skew error for blocks from a peer is likely to repeat for that peer
  
If we accept this logic, we can build a state machine on top of this foundation..
￼￼
So, currently that exception is logged at `Warning` level.

As an isolated event from a single peer, that's indeed a `Warning`, as per the above logic.
And for a concerted event as laid above, it's a `Critical` situation, indeed.
So we can't even pick a proper severity level without a state machine..

Maybe as a compromise, we could log them all at Error severity, which would make them stand out (f.e. in RTView, which would show them in its errors tab).

So, we have two options:
  1. Log as Error
  2. Make a state machine and:
    - either terminate the node, or
    - log at `Critical` level?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
