### ISSUE TITLE
[BUG] - cardano-node/scripts/byron-to-mary/ unable to transition to shelley

### ISSUE THREAD

**Issue by lmbruder** [input-output-hk/cardano-node#2538]
**Internal/External**
*External*

**Area**
*Setting Up A Private Cardano Blockchain*

**Summary**
I am unable to manually transition to Shelley with update-1.sh after executing mkfiles.sh because i get these errors:
```
[cardano1:cardano.node.Forge:Error:33] [2021-03-19 17:31:31.00 UTC] fromList [("credentials",String "Cardano"),("val",Object (fromList [("kind",String "TraceNodeCannotForge"),("reason",Object (fromList [("kind",String "PBftCannotForgeThresholdExceeded"),("numForged",Number 7.0)])),("slot",Number 31.0)]))]
[cardano1:cardano.node.Forge:Error:33] [2021-03-19 17:31:32.00 UTC] fromList [("credentials",String "Cardano"),("val",Object (fromList [("kind",String "TraceNoLedgerView"),("slot",Number 32.0)]))]
```
After that I only get this `[cardano.node.resources:Info:18]` on every node log.

And the block production stops before the update/epoch is done. (Same problem when trying to transition completely manually.)
The transition works when uncommenting `echo "TestShelleyHardForkAtEpoch: 1" >> ${ROOT}/configuration.yaml` but then I have problems using the funds from the initial utxo.

**Steps to reproduce**
1. clone the "byron-to-mary" scripts, change ip addresses and ports and uncomment `echo "TestShelleyHardForkAtVersion: 1"  >> ${ROOT}/configuration.yaml`
2. execute mkfiles.sh and copy the directory to two other vms.
3. start one node on each vm

**Expected behavior**
I would expect the chain to transition to Shelley without a problem after executing the update-1.sh script.

**System info:**
- OS: Ubuntu
- Version 20.04
- Node version: 1.25.1

**Comment by yihuang** [comment]
try this out: https://github.com/yihuang/cardano-devnet

**Comment by lmbruder** [comment]
> try this out: https://github.com/yihuang/cardano-devnet

I did! I also tried using the minting script but it does not work for me. I have problems spending the initial utxo, maybe you have a tip there. Also I had to modify your mkfiles.sh because "byron-formats" does not work on the current cardano-cli.

I would also like to do the transitions manually, if possible.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
