### ISSUE TITLE
[FR] - Please remove dependency on libsodium branch version.  Causes no end of issues with ld library paths and complicates builds.  And the second a security issue comes up with that branch we are hosed and have to go back and fix our branch.  The fix here might be as simple as taking the time to work with the main branch and its maintainers.

### ISSUE THREAD

**Issue by rgoerwit** [input-output-hk/cardano-node#2544]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by mark-stopka** [comment]
The upstream maintainer currently has no intention of supporting VRFs...

https://github.com/jedisct1/libsodium/issues/975

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
