### ISSUE TITLE
[BUG] - Pool reward cancelled for no apparent reason

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2545]
**Internal/External**
*External*   otherwise.

**Area**
*Pool Reward*

**Summary**

- Happened with 1.25.1
- Pool config reported as ok
- Blocks minted
- Rewards zero

Switched pool reward/owner stake address to Ledger HW wallet in E252 (09-Mar).
Minted 2 blocks in 254. Got 0 reward in 256

Recent pool updates for [pool1n6qqnvjfzskcq9zdld5pnp8q3ktd28pqsh5tkmvarqcayr76puv](https://adastat.net/pools/9e8009b249142d80144dfb681984e08d96d51c2085e8bb6d9d1831d2) look like this ...

```
 id   | epoch | meta_id |    pledge    | margin |                         reward_addr                         |                         owner_addr                          
-------+-------+---------+--------------+--------+-------------------------------------------------------------+-------------------------------------------------------------
 13541 |   255 |    7221 |  35000000000 |   0.01 | stake1u8z5quq2tr09fzrluxkdtndsphk3c3kyspuaggf99tldpyqfmjs4a | stake1u8z5quq2tr09fzrluxkdtndsphk3c3kyspuaggf99tldpyqfmjs4a
 12969 |   254 |    5075 |  35000000000 |   0.01 | stake1u8z5quq2tr09fzrluxkdtndsphk3c3kyspuaggf99tldpyqfmjs4a | stake1u8z5quq2tr09fzrluxkdtndsphk3c3kyspuaggf99tldpyqfmjs4a
 12649 |   253 |    5075 |  35000000000 |   0.01 | stake1u8z0dkadelc7sfqqzxndtuya67memkvnp3z3lvcgr4ak0xsnu63xr | stake1u8z0dkadelc7sfqqzxndtuya67memkvnp3z3lvcgr4ak0xsnu63xr
 12607 |   253 |    5075 |  10000000000 |   0.01 | stake1u8z0dkadelc7sfqqzxndtuya67memkvnp3z3lvcgr4ak0xsnu63xr | stake1u8z0dkadelc7sfqqzxndtuya67memkvnp3z3lvcgr4ak0xsnu63xr
 11812 |   252 |    5075 |  10000000000 |   0.01 | stake1u8z0dkadelc7sfqqzxndtuya67memkvnp3z3lvcgr4ak0xsnu63xr | stake1u8z0dkadelc7sfqqzxndtuya67memkvnp3z3lvcgr4ak0xsnu63xr
```

In db-sync, there are no orphaned rewards. Pledge was always met. This looks like a bug to me and I would appreciate if we could get to the bottom of this so that it doesn't bite again.

Do we already have reporting when rewards are getting cancelled?
Perhaps there is an unreported error condition the causes this behavior.

PS: I payed out manually because I didn't want my folks to be affected by this (see [Tx metadata](https://adastat.net/transactions/7efbfa2c49ee9fbdd9bc7899767316a46d1446779b3d31d78ff5afae9e1319cd))

**Comment by gitmachtl** [comment]
Look like you moved too fast. You registered pledge was not met. When you raise the value in a wallet (owner or normal delegator) you have a delay. You can't switch the owner and raise the registered pledge at the same time. So when you move the funds from the old owner to the new owner you also have the normal staking delegation delay. You should have registered two owners, let it sink it via an epoch transition (i prefer two), after that move the funds to the new owner, lets it again sink in, after that, raise the registered pledge on the pool. A new owner is like a new delegated address to the pool, and as you know, it takes some epochs before the amount is active.

**Comment by gitmachtl** [comment]
Why did you de-register your old rewards account in e253? Thats maybe the reason you don't see rewards. It takes 4 epochs for the new rewards account to kick in.

**Comment by tdiesler** [comment]
Thanks a million, for looking into this. I'll take it as an answer and close for now.

**Comment by gitmachtl** [comment]
As far as all we have seen until now on the chain there are just two scenarios:

* No rewards, but blocks made and node in topology of others: Reason -> Pledge not met.
* No blocks made, and node in topology of others: Reason -> KES Period expired

**Comment by tdiesler** [comment]
BTW, where did you see that the pledge was not met?
