### ISSUE TITLE
[FR] - Please implement Bech32 encoding for assets in the API

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#2548]
**Internal**

**Area**
*Native Tokens*

**Describe the feature you'd like**
Please implement Bech32 encoding for assets as specified in https://github.com/cardano-foundation/CIPs/pull/64 .

**Describe alternatives you've considered**
n/a

**Additional context / screenshots**
n/a

**Comment by gitmachtl** [comment]
Duplicate of https://github.com/input-output-hk/cardano-node/issues/2426 but not limited to Native Assets

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
