### ISSUE TITLE
[FR] -  Prevent block-producer node to start with Invalid KES (InvalidKesSignatureOCERT)

### ISSUE THREAD

**Issue by LuckySlam** [input-output-hk/cardano-node#2551]
**Internal/External**

**Area**
cardano-node

**Describe the feature you'd like**
Curently a block-producer node can start with an invalid KES signature. The only way to know if the KES signature is valid is to make a block.

**Describe alternatives you've considered**
Cradano-node simply should not start with invalid KES signature.

This will avoid missing block caused by _OcertFailure (InvalidKesSignatureOCERT 192 189 3 "Reject"))_

**Comment by bemnet4u** [comment]
+1 on this issue. It causes small pool operators to miss blocks. If it can be detected on startup it will be great to add this validation.

**Comment by rdlrt** [comment]
This would need your node to be in sync (atleast to a point where previous block created by your node is in DB), not something you can assume when you start the node. Instead, the alternate solutions could be using this information from public / private hosted dbsync *when* you actually rotate the key.

**Comment by bemnet4u** [comment]
@rdlrt Ya I read that thread and commented. It looks like what happened to us is we missed updated the kes file but updated the node.cert. Its not just us it looks like this was also documented here https://www.tiredpixel.com/2020/10/06/crab-cardano-stake-pool-botched-kes-key-rotation-incident-report/

Do we know how we can decode the `Op Cert` column in the Blocks table? I see that our block has this Op Cert value and I would like to decode it to see the counter to validate if this is the issue. I got this data from caradno-sycn-db. 

```Id	Hash	Epoch No	Slot No	Epoch Slot No	Block No	Previous Id	Merkle Root	Slot Leader Id	Size	Time	Tx Count	Proto Major	Proto Minor	Vrf Key	Op Cert
5721125	d2eb97f83fed36a42a4893992bcb57533fd13891815a106873b24a3a699572eb	265	29,512,883	396,083	5,720,948	5721124	Null	5721125	7,884	5/15/2021 11:46:14 AM	18	4	0	vrf_vk12553zj6px5lklma89sxatl9w82a28u6e84zgnufckpy5a9jvrqvsudg0f9	3724b02d0e5775c65e199eb33f278b95fb23f03616e60f9cad368f1022b42788```

**Comment by rdlrt** [comment]
> Do we know how we can decode the Op Cert column in the Blocks table?

It is only available in dbsync post [this commit](https://github.com/input-output-hk/cardano-db-sync/commit/f300c630a89c08ed70a746676043e8f466cf5c5c), and available as an integer
![image](https://user-images.githubusercontent.com/3169068/123211789-455ad480-d507-11eb-811f-d476b5b1dd4a.png)
