### ISSUE TITLE
[FR] - Better startup logging for block producers

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2552]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**

*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
Display data in logs about a block producers. This way at startup, a user can quickly identify if the node is running with the correct secrets without having to manually debug on CLI.

I'd suggest something like this:
```
***RUNNING AS BLOCK PRODUCER***
Pool ID: pool1g54czd7p9nqe4eg6wdy8el443dzx0qeujl5gpt95x3t0kyzg0xs
VRF key hash: 133db71026dc748ab9e666597fb68c8c0d50c8df6ae1f25e1eb802609325b8de
KES remaining periods: 52
Current opcert counter: 3
Last known Opcert counter used as of slot 22610638: 2
Active Stake (Epoch 256): 5000000000000
*WARNING* Forge metrics are disabled in configuration file. This is not recommended for block producers.
```

**Describe alternatives you've considered**
Manually run a bunch of commands to debug if secrets are correct.

**Additional context / screenshots**

**Comment by disassembler** [comment]
If it's simpler, this could be a CLI command instead of logging that queries the local node socket and outputs the information.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
