### ISSUE TITLE
[BUG] - cardano-cli work have a problem to consider when minting maximum amount of Assets.

### ISSUE THREAD

**Issue by WhitemanE0** [input-output-hk/cardano-node#2555]
**Internal/External**
*External*

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Summary**
When I've tried to mint really huge amount of tockens with cardano-cli, i've got meaningless error message:

```
unexpected " "
expecting quantity (word64)
expecting word64, but the number exceeds the max bound: MyHugeNumber
```

**A. This looks more like an exception then useful error message.** Not everybody knows what is word64.

word64 can carry 2^64 in Decimal, which is 18446744073709551616, so I've tried to issue this amount of tokens and got:

unexpected " "
expecting quantity (word64)
expecting word64, but the number exceeds the max bound: 18446744073709551616
But 18446744073709551615 was just fine as expected - 2^64 - 1.

But when trying to sign this transaction i've got the following:

`Command failed: transaction sign Error: matx.raw: TextEnvelope decode error: DecoderErrorDeserialiseFailure "Shelley TxBody" (DeserialiseFailure 209 "overflow when decoding mint field. min value: -9223372036854775808 max value: 9223372036854775807 got: 18446744073709551615")
`

**B. cardano-cli should not allow to build raw transaction it will be unable to sign.**

I've repeated the steps with the 9,223,372,036,854,775,807 tokens to mint and succesfully sign and submit the transaction.

**Steps to reproduce**
1. Try to mint 18446744073709551616 of any Native Tockens with cardano-cli.
2. See **A** and **B** issues.

**Expected behavior**
cardano-cli at the submitting raw transaction of any Native Token shoud give an Error Message stating "Expected quantity is no more than _9,223,372,036,854,775,807"_ or so.

**System info (please complete the following information):**
- OS: MacOS Big Sur
- Version 11.2.1
- cardano-node 1.25.0 - darwin-x86_64 - ghc-8.10

**Screenshots and attachments**
See error messages quoted above.

**Additional context**
I used cardano-node 1.25.0 because 1.26.0 is unable to start a node at all. But it's out of the scope of current tiket.

**Comment by saratomaz** [comment]
This issue persists on babbage cardano-node latest master, when we try to build a transaction with the maximum amount of ada 2^64 we got:
```
unexpected end of input
expecting multi-asset value expression
expecting word64, but the number exceeds the max bound: 18446744073709551616
```

Than, if we lower the value to  2^64 - 1  it's possible to build the transaction and sign the transaction  (_max value is really 2^64-1, not 2^64 as it is reported_) but on the submit we got meaningless error message :

`cardano-cli: DecoderFailure (LocalTxSubmission (GenTx (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyMAEra 'Mary StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) ('[] *))))))))) (HardForkApplyTxErr (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyMAEra 'Mary StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) ('[] *))))))))) ServerAgency TokBusy) (DeserialiseFailure 19 "Value: expected array or int, got TypeInteger")`

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
