### ISSUE TITLE
[FR] - The node should notice and warn if the op cert or the VRF key do not match.

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2558]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
Node logging

**Describe the feature you'd like**
The node should notice and warn if the op cert or the VRF key does not match.

Ideally, the node should inform about any misconfiguration related to keys, certs, etc.

**Comment by frog357** [comment]
I think this might have been closed prematurely - we recently faced a situation where the vrf key was mismatched and we did not have any indication until I noticed the scheduled block was missed.
