### ISSUE TITLE
[BUG] - node synchronization stuck at 23.11% forever with ErrorPolicySuspendPeer errors

### ISSUE THREAD

**Issue by andrejpodzimek** [input-output-hk/cardano-node#2559]
**Internal/External**
*External*

**Area**
*Other*

**Summary**
`cardano-node` is stuck syncing for hours at 23.11%, as calculated [by this script](https://forum.cardano.org/t/check-sync-status-of-node/36500/12) (adjusted for version `1.26.1` to ask for `.slot` instead of `.slotNo`, but otherwise unmodified). Surprisingly enough, both the numerator and the denominator keep growing steadily (e.g. `slot 25543697/110496501 23.11%`), but the overall ratio hasn’t changed for a number of hours.

**Steps to reproduce**
Start `cardano-node` `1.25.1` or `1.26.1` like this:
```
cardano-node run \
    --database-path /var/lib/cardano-node/db \
    --socket-path /run/cardano-node/socket \
    --host-ipv6-addr :: \
    --host-addr 0.0.0.0 \
    --port 3000 \
    --config /var/lib/cardano-node/config/mainnet-config.json  \
    --topology /var/lib/cardano-node/config/mainnet-topology.json
```

**Expected behavior**
It should make steady progress to a full sync.

**System info (please complete the following information):**
- OS: ArchLinux
- Version: up-to-date
- Node version: `1.26.1`, based on [this package](https://aur.archlinux.org/packages/cardano-node/)

**Screenshots and attachments**
Error messages usually come in groups of 3 per peer IP address:
```
[charon:cardano.node.ErrorPolicy:Warning:283] [2021-03-30 13:03:37.64 UTC] IP xxx.xxx.xxx.xxx:45102 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 68> closed when reading data, waiting on next header True"))) 20s 20s
[charon:cardano.node.ErrorPolicy:Warning:283] [2021-03-30 13:03:38.70 UTC] IP xxx.xxx.xxx.xxx:52084 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 71> closed when reading data, waiting on next header False"))) 20s 20s
[charon:cardano.node.ErrorPolicy:Warning:283] [2021-03-30 13:03:40.73 UTC] IP xxx.xxx.xxx.xxx:59960 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 71> closed when reading data, waiting on next header False"))) 20s 20s
```
However, there *is* some communication with the network, because there are `Chain extended` messages every now and then.
```
[charon:cardano.node.ChainDB:Notice:257] [2021-03-30 13:09:13.73 UTC] Chain extended, new tip: 9c57345badcf8fc267f7df530ff80fd55b1c6a934c2dd36cea25ced8f7e73175 at slot 25543462
```

**Additional context**

0. Initially the synchronization started normally and progressed up to the 23.11% just fine (in a few hours). Then something got stuck for no apparent reason. The problem showed up already with `1.25.1`. (The only reason why I upgraded was to double-check if the problem would disappear.)
0. It looks like the node is listening normally (according to `netstat -atpn`):
   ```
   Proto  Recv-Q  Send-Q  Local Address  Foreign Address  State   PID/Program name
   tcp6        0       0  :::3000        :::*             LISTEN  1151036/cardano-node
   tcp         0       0  0.0.0.0:3000   0.0.0.0:*        LISTEN  1151036/cardano-node
   ```
0. Port 3000 is allowed in `nftables`, so incoming TCP connections should work as well. DNS resolution works fine (as the machine happens to be also a caching + authoritative DNS server), both the legacy way (`nameserver ::1` in `/etc/resolv.conf`) as well as the modern way (`systemd-resolve --status` looks sane with `::1` everywhere).

I spotted #1124, #2016 or #2269, but upon a closer look those issues seem unrelated. However, #2452 *might* be somewhat related.

**Comment by andrejpodzimek** [comment]
Forgot to mention: Unlike #2452,
* restarting `cardano-node` doesn’t help at all.
* this is not (yet) a relay + validator setup; only the relay is running at this point.

**Comment by andrejpodzimek** [comment]
And 3 hours later it “progressed” to 23.1**2**%. :tired_face:

**Comment by andrejpodzimek** [comment]
Further context:
* [This](https://forum.cardano.org/t/error-issuing-query-commands-with-cardano-cli-ver-1-15-1-in-mainnet-candidate/35915/3) looks related, but I’m using `1.26.1`, not the old versions mentioned there&hellip;
* [This](https://www.reddit.com/r/CardanoDevelopers/comments/ljs1gv/no_peers_log_file_warning/) has been asked on Reddit.

**Comment by andrejpodzimek** [comment]
What I’ve tried thus far (to no avail):
* remove `--host-addr`
* remove `--host-ipv6-addr`
* set both `--host-addr` and `--host-ipv6-addr` to an address on the external interface instead of the zero wildcard
* switch to port `3001` instead of `3000` (with corresponding `nftables` adjustment)
* delete the entire `db` directory and start over

After the database deletion I’m seeing way fewer of `...closed when reading data...` errors, but it seems to be getting stuck nonetheless. It hasn’t reached 20% after ~10 hours and progress is slowing down steadily.

**Comment by erikd** [comment]
@andrejpodzimek That script looks a little dodgy to me (testnet etc). What does the following command say? :
```
CARDANO_NODE_SOCKET_PATH=/path/to/node/socket cardano-cli query tip --mainnet 
```
Obviously, replacing `path/to/node/socket` with whatever is correct for your system.

**Comment by andrejpodzimek** [comment]
```
$ CARDANO_NODE_SOCKET_PATH=/run/cardano-node/socket cardano-cli query tip --mainnet
{
    "epoch": 257,
    "hash": "28c2e905f111b1da0330ac8a854c31cafe77b591b14b6dde49a4de880f69d21a",
    "slot": 25866123,
    "block": 5543047
}
```

**Comment by erikd** [comment]
That is ad the tip of the chain. What does the script say?

**Comment by erikd** [comment]
I have raised a [feature request](https://github.com/input-output-hk/cardano-node/issues/2569).

**Comment by andrejpodzimek** [comment]
> That is at the tip of the chain. What does the script say?

```
slot 25866533/110819360 23.34%
```

**Comment by erikd** [comment]
Your node is fully synced, but the script says it is not. The script is wrong. 

If you agree, please close this ticket.

**Comment by andrejpodzimek** [comment]
That’s awesome! I just couldn’t wrap my head around what the script was saying.

Yet another source of confusion was that Cardano’s data has ~8 GB on my machine, whereas `openethereum` has 430 GB and `bitcoin-qt` has 364 GB. This, combined with the script’s strange output, made me think: Heck, Cardano can’t be in sync with so little data! :grin:

**Comment by erikd** [comment]
The BTC and ETH chains have been running since 2009 and 2013 respectively. The Cardano chain started in 2017 so its is not surprising it has much less data.
