### ISSUE TITLE
[FR] - Improve cardano-node startup time / variability

### ISSUE THREAD

**Issue by Scalextrix** [input-output-hk/cardano-node#2564]
**External**

*Other*

**Describe the feature you'd like**
Improved load time for the immutable ledger when starting cardano-node.  Observed on both Linux containers and a Windows host. After connecting to peers, there can be 4-5 minute wait for the immutable ledger to complete loading.  In the node log below see how the peers are loaded at 15:10:17.86 UTC and the immutable ledger load then only completes at 15:14:56.16 UTC.  However sometimes the loading is very fast, there seems to be a lot of variability in the load time.

**Describe alternatives you've considered**
The only work around is to not use cardano-node (for example Yoroi).

**Additional context / screenshots**
>[35m[DESKTOP-:cardano.node.addresses:Notice:3][0m [2021-03-31 15:10:17.86 UTC] [SocketInfo 0.0.0.0:55411,SocketInfo [::]:55411]
[35m[DESKTOP-:cardano.node.diffusion-mode:Notice:3][0m [2021-03-31 15:10:17.86 UTC] InitiatorAndResponderDiffusionMode
[35m[DESKTOP-:cardano.node.dns-producers:Notice:3][0m [2021-03-31 15:10:17.86 UTC] []
[35m[DESKTOP-:cardano.node.ip-producers:Notice:3][0m [2021-03-31 15:10:17.86 UTC] IPSubscriptionTarget {ispIps = [192.168.111.120:3001,192.168.111.104:3002], ispValency = 2}
[34m[DESKTOP-:cardano.node.ChainDB:Info:18][0m [2021-03-31 15:14:56.16 UTC] Opened imm db with immutable tip at 145d1390793b9ae31559e3dbcb2a483696cc76d43e97bc4fdbf0f16a097e6c9a at slot 25580820 and chunk 1184

**Comment by 2072** [comment]
From my observations, the startup time depends of how the node exited, it needs to be shutdown cleanly to startup fast, If you stop it using a SIGINT on Linux it will start in about 10 seconds. SIGTERM is not stopping the node properly.

What would be interesting is to have more logs from the imm db when it's recovering from an unclean shutdown.

**Comment by Scalextrix** [comment]
Interesting, the Daedalus wallet does silently crash fairly often.  Unplugging a USB device can make it crash, for example.

**Comment by rdlrt** [comment]
> What would be interesting is to have more logs from the imm db when it's recovering from an unclean shutdown.

@2072 - You can increase logging level / verbosity in your node config to see status for ledger replay

**Comment by 2072** [comment]
There seems to be a new problem with 1.26.1, even after a proper `kill -SIGINT` it takes much more longer to start, several minutes instead of a few seconds...

**Comment by Scalextrix** [comment]
Yes, I observed my relays took a long time to start after upgrading to 1.26.1

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
