### ISSUE TITLE
[BUG] - In Byron era query tip command returns null for epoch

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#2568]
**Internal**

**Area**
CLI query commands

**Summary**
In the Shelley and related eras:
```
$ cardano-cli query tip --mainnet
{
    "epoch": 230,
    "hash": "db86e32262234bdf855c2ebdb432b0002296aa2a6cb80536d76e41a641f678a5",
    "slot": 14322326,
    "block": 4975732
}
```
whereas in the Byrin era:
```
$ cardano-cli query tip --mainnet
{
    "epoch": null,
    "hash": "21ed5ab96607d4ed452887e416e4ba6840faa809300bec6749d0496d76a882f7",
    "slot": 4195953,
    "block": 4193845
}
```

It would be incredibly useful it the correct epoch number was returned for Byron as well.

**Comment by erikd** [comment]
Related to #2569. The two could/should be done at the same time.

**Comment by dcoutts** [comment]
This one should become easy based on the work that @DavidEichmann is doing. We'll be adding a era query to the generic consensus query stuff, rather than relying on the Shelley-era-specific queries.
