### ISSUE TITLE
[BUG] - Ledger corruption of testnet blockchain after retiring and re-registering pool

### ISSUE THREAD

**Issue by benapetr** [input-output-hk/cardano-node#2570]
**External**
**Other**
**Summary**
Since I retired and re-registered a pool on testnet, unexplainable bug occured on ledger which leads to absolutely broken calculation of pledge wallet balance in ledger dump as well as all tools that work with it (pooltool.io, cncli etc.)

It's described in details here: https://github.com/AndrewWestberg/cncli/issues/47

Basically what happened - after retiring a pool, I re-registered it (I could see 500 balance in rewards in Daedalus, the returned deposit), but ever since I re-registered the pool, the calculated active pledge from ledger is showing absolutely wrong numbers that make no sense (not only they are different from the actual balance, they are different from any balance ever on that wallet).

Right now, the wallet has about 2M ADA, but according to ledger there is 22.1k balance (I don't even think there ever was that amount of ADA) - there was 10M since 17. 3. (I sent 8M away right after that), so that's like 4 epochs already, yet ledger is showing balance about 22.1k (where is that number even coming from)? These numbers just don't make any sense.

The pool is otherwise normally operating and producing blocks (but probably no rewards, since registering it again, I raised the pledge to 2M (there was > 2M balance in pool wallet even before re-registering the pool), but it was instantly marked as not-adhering to pledge everywhere as ledger is showing balance only 22.1k, so probably no rewards will be created in upcoming epochs. Currently it's impossible to increase the pledge on that pool, any amount of ADA I send to that pool wallet, even after waiting 2 epochs doesn't get reflected by ledger and has no effect on active pledge (raising it when re-registering pool just invalidates any rewards as pledge is not "adhered to")

Pool ID is b264b05a99fdebb8c15c9a5eac3646f808c0cb57c0b9751566594089

**Steps to reproduce**
I don't know how to reproduce it, this is what I did:

1. Create a wallet with balance X (using mnemonic method in my case)
2. Register staking address for that wallet
3. Register a new pool using that wallet with pledge < X
4. Operate it for an epoch or two
5. Retire it
6. Register it again
7. Now increase balance X
8. Wait few epochs - ledger will show nonsense

**Expected behavior**
I would expect ledger to show numbers that correspond to reality - eg. when your pool wallet has balance over 2M for more than 4 epochs, ledger should not be showing some random number (22.1k) as active balance of that same wallet

**System info (please complete the following information):**
- OS: debian
- Version 10
- Node version 1.25.1

**Additional context**
See this thread https://github.com/AndrewWestberg/cncli/issues/47

**Comment by benapetr** [comment]
Also - another part of this bug - there are 2 wallets registered in this pool (for over 4 epochs), total balance of both of them is > 10M, but active stake for this pool is calculated as ~8M

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/1560121/113474538-d1adac00-9470-11eb-9685-81c1bce77e36.png">

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/1560121/113474576-fb66d300-9470-11eb-970b-90c104a6f745.png">

**Comment by benapetr** [comment]
interesting update, despite the ledger is showing stake of 8M and pledge (that was set to 2M) as NOT MET, I received rewards for that epoch where pledge wasn't met. So it really looks like perhaps the data in blockchain are correct, but nonsense data are generated in ledger dump?

note there are 2 wallets delegated, pool wallet with 2M and other wallet with 8M, the pledge was set to 2M, but according to everything it was not met (even daedalus was showing the pool red with star, until I decreased pledge to 20k) but rewards for that epoch were paid anyway

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
