### ISSUE TITLE
[FR] - Add a Cardano-CLI function to expose the calcMinimumDeposit calculation for NativeAssets

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2571]
**External**

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Describe the feature you'd like**
We need a function to calculate the right minDeposit (minAda) for a --tx-out transaction build-raw with cardano-cli that includes NativeAssets. In a perfect world we would provide the cardano-cli the same --tx-out string that we will use in the build-raw command and get back the minDeposit (minAda) amount for that --tx-out. 

Like:
`cardano-cli transaction calculate-min-deposit --tx-out TX-OUT --protocol-params-file FILE [--out-file FILE]`

Currently its just guessing or in the solution for my StakePoolOperator-Scripts, Jormanager and CNTools its just minUTXOvalue (1 ADA) + 1 ADA per asset in the output. That works, but is way to much. So we need a workable method to get the right value to send out NativeAssets with the minimum needed Deposit.

Related:
https://github.com/input-output-hk/cardano-node/pull/2325
https://github.com/input-output-hk/cardano-node/issues/2298
@Jimbo4350

**Comment by gitmachtl** [comment]
I have now written a working bash-function for that. It takes the JSON of the protocol-parameters and also the tx-out string you wanna use. It returns the minAda needed to do that. Ok, so currently no rush on that cardano-cli function i guess, but if you find the time to integrate it, would be nice.

**Comment by newhoggy** [comment]
Maybe something like this?

```
$ CARDANO_NODE_SOCKET_PATH=mainnet.socket cardano-cli transaction calculate-min-value --mainnet --multi-asset "5 00000000000000000000000000000000000000000000000000000000.couttscoin + 6 00000000000000000000000000000000000000000000000000000001.jimbocoin"
Result Lovelace 1703702
```

**Comment by newhoggy** [comment]
Done
