### ISSUE TITLE
[FR] - Sensible, step-by-step install and config documentation 

### ISSUE THREAD

**Issue by 34r7h** [input-output-hk/cardano-node#2572]
After attempts on mac and ubuntu and running into errors at every step, I humbly ask you to produce a document with clear steps to install and run a node.

I.e. what's a genesis file, config.yaml, cabal vs nix, /.state db blah blah i'm frustrated 

**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Please specifically describe the errors you are running in to.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
