### ISSUE TITLE
Transaction hash taking too long

### ISSUE THREAD

**Issue by francisco-olea** [input-output-hk/cardano-node#2574]
I am currently creating a [Simple Transaction](https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/simple_transaction.md) where I am not getting the Transaction Hash even though I am at the tip of the chain.

    cardano-cli query tip --mainnet
    {
        "epoch": 257,
        "hash": "89f891be238a504891eada5119b4b235ecde97b4b138d0757e9433abd76eeda3"
        "slot": 26016554,
        "block": 5550324
    }

Got the [Protocol Parameters](https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/simple_transaction.md#get-protocol-parameters) and I have been waiting around 4+ hours now. I would expect maybe 30 min but I think at this point there is something wrong.

    cardano-cli query utxo --address $(cat payment.addr) --mainnet

                            TxHash                                 TxIx        Amount
    --------------------------------------------------------------------------------------------

**Comment by erikd** [comment]
I just tried this with a couple of address (one with two entries and the other with about a dozen) and both queries took under a second.

Are you willing to share which address you are using? Have you tried more than one address?

**Comment by francisco-olea** [comment]
Yes, I already tried other addresses and they work.

i.e. from adapools
`addr1q8eudmpp6pwz4sn8sr8mwuxzeyt0jk5lzpr23mdqsffd6w55tvv668lv5lk0cf8qu9h6fqkcum6puerqkt6tvpw98l7sq3amy6`

     root@relay-node:~/Wallet/Keys# cardano-cli query utxo --address addr1q8eudmpp6pwz4sn8sr8mwuxzeyt0jk5lzpr23mdqsffd6w55tvv668lv5lk0cf8qu9h6fqkcum6puerqkt6tvpw98l7sq3amy6 --mainnet
                           TxHash                                 TxIx        Amount
    --------------------------------------------------------------------------------------
    027e62ef01ed1143a2a07b835a127421387fc048bcf01e030510d8eb99d51295     0        10000000 lovelace + 250000000 bb034f986a145377d4767a2dbbadaaa630bb76c741c8efc6479dbb9e.Schmeckle
    059494a6babd9a9f038a317212cd88d25c4ded0204540662cd5d3ba14066f626     0        1000000000 lovelace
    091cb4a1c863c8f94f2699c7772f8e755a90faaa39e76c3e54591a54ee7447de     0        50000000 lovelace
    1d6b4779f105b728d520146bee0b7c199c324793bb2d10543e03c462d9a87518     0        500000000 lovelace
    494f1c1576f0600638a48b82afb82d221d056a437a9c27ba1c9c9d02d8cfb86e     0        10000000 lovelace
    77f39c89520e9bed3b04e619dfd65277dc93638ce4f2290c4ca681b5d7667fdf     2        4954000 lovelace
    a774109a363998e07b1cf852899d86e427f89951a3bedafc1485279562c41852     0        2000000 lovelace
    d234c3687973dc4cedbf5c2aafe8143eff8020e52b63e7ee37324d6008848eb2     0        6000000 lovelace
    e3ffa47c099d3014d8056e5a0796077f96c6579f18427bfa809d62ec3514da07     0        1481480 lovelace + 100000 d894897411707efa755a76deb66d26dfd50593f2e70863e1661e98a0.spacecoins
    e5e6b850eeb2ef4768a09a23dac95f08574b5514e7ac8e10bb044df41641e696     0        1000000 lovelace
    f1b9ef54150bb65de36ef18ee5b738ecc3d7e83ce9e59284b63fcaaa86aa93fa     0        423382659 lovelace


Current:
`addr1q8qx9jh8vkm5kx2xvxxtwdggxt7fzmq4n68y227nqexjznayeq6eaqfyrmdccjjhplklgnfpu687gfzyg3g0negjtxtq4jmjf5`

    root@relay-node:~/Wallet/Keys# cardano-cli query utxo --address $(cat payment.addr) --mainnet
                           TxHash                                 TxIx        Amount
    --------------------------------------------------------------------------------------

**Comment by rdlrt** [comment]
What exactly are you expecting against that address when you have 0 transactions against it?

**Comment by francisco-olea** [comment]
> What exactly are you expecting against that address when you have 0 transactions against it?

True, I did a mistake on the transaction. I got it now.
