### ISSUE TITLE
[FR] - Missing release notes for 1.26.x

### ISSUE THREAD

**Issue by r-tde** [input-output-hk/cardano-node#2575]
**External**

**Area - Other**

**Describe the feature you'd like**
Two recent releases - 1.26 & 1.26.1 have no release notes and it's unclear if they're "production" ready and/or should we upgrade to them.

**Describe alternatives you've considered**
Reviewed some of the commits however there isn't sufficient clarity.

**Additional context / screenshots**
Expectation would be to have "standard" release notes as with previous ones.

**Comment by gitmachtl** [comment]
1.26.0 was never released

**Comment by rdlrt** [comment]
@r-tde - Look at the highlighted "Latest release":
![image](https://user-images.githubusercontent.com/3169068/113642529-63acf300-96c3-11eb-8ba5-aff8327f8069.png)
