### ISSUE TITLE
[BUG] - cardano-node 1.26.1:62f38 keeps running after a start with a misconfigured topology.json

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2577]
*External* 

**Area**
*Cardano-Node*

**Summary**
Cardano-Node 1.26.1:62f38 keeps running and is not exiting when a misconfigured (not valid) json is loaded as topology.json.
Metrics interface reports data, times are ticking up, node is in a non responsive phase.

**Expected behavior**
Cardano-Node should exit with an error message on any misconfigured config-files

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
