### ISSUE TITLE
[FR] - Run node/tools images as non-root user

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2584]
**External**

**Area**
- Docker  

@PyurOfHeart says on #2456 ...

> Containers are a great way to isolate workloads from each other, but a lot of those benefits are put at risk when they run as root, because being root inside the container allows one to become root on the underlying hosts. This opens up the cluster itself to vulnerabilities via malware originating from the workloads running within them.

> The best-practice way to solve this is to run containers as non-root users, and to set up pod security policies in kubernetes that prevent privileged containers from running and specifying run-as users for each pod. This way, if you happen to have a single compromised container, the blast radius is most likely limited to that container. This can have additional benefits, such as making all binaries read/execute-only for the container user so that malicious software on the host can not alter the binaries.

CrossRef: https://github.com/tdiesler/nessus-cardano/issues/33

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
