### ISSUE TITLE
How to use cardano-submit-api when cardano-rest is deprecated

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-node#2588]
https://github.com/input-output-hk/cardano-rest/commit/c86475153ab32fd7952dcdb844083e2e8236d6e8
According to this commit, I know that cardano-submit-api has migrated from cardano-rest to cardano-node,I used cardano-rest through docker-compose before, now how do I use cardano-submit-api through cardano-node
`cardano-submit-api:
    image: inputoutput/cardano-submit-api:${CARDANO_SUBMIT_API_VERSION:-3.1.2}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    depends_on:
      - cardano-node
    volumes:
      - node-ipc:/node-ipc
    ports:
      - 8090:8090
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"`

**Comment by Jimbo4350** [comment]
Have you read: https://github.com/input-output-hk/cardano-node/blob/master/cardano-submit-api/testing-tx-submit.md

**Comment by vae520283995** [comment]
> Have you read: https://github.com/input-output-hk/cardano-node/blob/master/cardano-submit-api/testing-tx-submit.md

I have read it, but I want to start it through docker, similar to cardano-rest to submit transactions

**Comment by dcoutts** [comment]
To be clear, is what you're asking for a docker file?

Since otherwise the answer is that the submit api service works in exactly the same way it did before. We've just move the repo it lives in, and updated its internals to be easier to maintain. The way you start and use it should be the same as before.

**Comment by vae520283995** [comment]
> To be clear, is what you're asking for a docker file?
Yes, I need docker, but I don’t know which new docker is

**Comment by vae520283995** [comment]
I used cardano-graphql
