### ISSUE TITLE
[FR] - Releases ChangeLogs

### ISSUE THREAD

**Issue by psychomb** [input-output-hk/cardano-node#2590]
**Internal/External**

*External*

**Area**

*Other*

**Describe the feature you'd like**

The release changelogs could have additional fields, namely the versioning of `cabal` and `ghc` that are compatible for those who compile the software. 

**Describe alternatives you've considered**
Scanning through the commits for relevant hints is likely doable, but not convenient.

**Additional context / screenshots**
none

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
