### ISSUE TITLE
[BUG] - CRITICAL cardano-cli script hashing and cardano-serialisation-lib script hashing does not match

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/cardano-node#2593]
**External**

**Expectation - IOHK provides spec for script hashing so the serialisation-lib can be updated**

CRITICAL - this impacts the support for timelocking scripts support for Catalyst in Yoroi. The issue is supposed to be created here itself, considering the lake of spec for hashing scripts. The serialization lib is doing the expected blake2b 28byte hash of the script CBOR, same as to hash pubkey to get keyhash.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Native Scripts

**Summary**
cardano-serialisation-lib produces a script hash that does not match with the cardano-cli

**Steps to reproduce**
generate a script using cardano-serialisation-lib

eg. 

*build cardano-serialization-lib from master*

```
const slib = require("@emurgo/cardano-serialization-lib-nodejs");

const hash = slib.Ed25519KeyHash.from_bytes(Buffer.from('8fb4ba5ddf2af3075162567d61456e3482f3f462f60d21d480a88828', 'hex'));
const pubKeyScript = slib.NativeScript.new_script_pubkey(
  slib.ScriptPubkey.new(hash));

const scriptHash = slib.ScriptHash.from_bytes(pubKeyScript.hash().to_bytes())


console.log(Buffer.from(scriptHash.to_bytes()).toString('hex'));

```
The output hash - d2fc93e9ef58d5679d512c7f2971196a33bfa90cc270530d53333685

**Expected behavior**
cardano-cli produces (correct) hash - 187b8d3ddcb24013097c003da0b8d8f7ddcf937119d8f59dccd05a0f
for the same script
```
{
  "keyHash": "8fb4ba5ddf2af3075162567d61456e3482f3f462f60d21d480a88828",
  "type": "sig"
 }
```

*Additional info*

The CBOR produced by the serialisation lib for hashing,

`8200581c8fb4ba5ddf2af3075162567d61456e3482f3f462f60d21d480a88828`

**System info (please complete the following information):**
- OS: Ubuntu
- 20.04
- 1.26.1

**Comment by JaredCorduan** [comment]
Are you including the `scriptPrefixTag` ?

https://github.com/input-output-hk/cardano-ledger-specs/blob/daba661cde93b1ae7743deafec12b9ba2b3ce6bc/cardano-ledger-core/src/Cardano/Ledger/Era.hs#L85-L91

for example, the multisig and the timelocks use:

https://github.com/input-output-hk/cardano-ledger-specs/blob/daba661cde93b1ae7743deafec12b9ba2b3ce6bc/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA.hs#L176

**Comment by ashisherc** [comment]
@JaredCorduan thank you for the response even during your vacation. 

I would like to see the document or any spec that defines this `scriptPrefixTag` for different scripts. I'm also confused to figure out in case when we have nested scripts.

eg. `ScriptAll (Script MultiSig, Script TimeLock, ScriptTimeLock)`

To get the correct hash of the above script, does it mean that, we need to add prefixes per script inside the whole CBOR??

eg. preTagScriptAll+ScripAllCBORStart(preTagScriptMultiSig, preTagScriptMultiSig, preTagScriptTimeLock) ScriptAllCBOREnd

I can see that adding preTags per script inside CBOR will make the whole CBOR invalid. 

Do we only add preTag to final outer script? This seems doable as far as I can think unless I know why the script tags are used before hashing.

**Comment by JaredCorduan** [comment]
@ashisherc np!

> Do we only add preTag to final outer script?

That is correct. In other words, the script hash of a multisig/timelock script is the hash of `"\x00" + script-cbor`

**Comment by ashisherc** [comment]
Awesome!! 🙌
