### ISSUE TITLE
[BUG] - `cardano-cli shelley address build ..`creates byron era addresses

### ISSUE THREAD

**Issue by johnmathews** [input-output-hk/cardano-node#2596]
*External*

**Area**

*Other*  - cardano-cli

**Summary**
When building a shelley address using a payment verification key a byron address is generated. 

**Steps to reproduce**
```
cardano-cli shelley address build \
  --payment-verification-key addr_xvk18359zklg0x68ru6yhxyvsv3slt6wscs00mzsc45jrv9840dfutj5uxg6z6rp4w2pany4kjgg5tly8s5xv7fuyq5tf8kw9ehr7cy4lzcenyhck \
  -- testnet-magic 1097911063
```
output:
```
{
    "address": "2cWKMJemoBahHcDQTp8zQDC55wguyn3YqLfddhGtEMdUdbAxJumX8z5cSQXiXKCDn4ifX",
    "era": "byron",
    "encoding": "base58",
    "type": "payment",
    "base16": "82d818582883581c09801d53d8ec28bf2711018fcc9962981e7460dde5be9b6fbdeaa438a102451a4170cb17001a91dbcb06"
}
```

**Expected behavior**
A shelley era address.

**System info (please complete the following information):**
Debian 10
cardano-cli 1.26.1 - linux-x86_64 - ghc-8.10
git rev 476db294924e85a34342cb97bac273ae5c63e79c

**Comment by rdlrt** [comment]
Invalid..

You're supplying address instead of vkey to build an address

**Comment by newhoggy** [comment]
How are you getting this output?  I'm getting:

```
$ cardano-cli address build --payment-verification-key addr_xvk18359zklg0x68ru6yhxyvsv3slt6wscs00mzsc45jrv9840dfutj5uxg6z6rp4w2pany4kjgg5tly8s5xv7fuyq5tf8kw9ehr7cy4lzcenyhck --testnet-magic 1097911063
2cWKMJemoBahHcDQTp8zQDC55wguyn3YqLfddhGtEMdUdbAxJumX8z5cSQXiXKCDn4ifX
```

**Comment by Jimbo4350** [comment]
> How are you getting this output? I'm getting:
> 
> ```
> $ cardano-cli address build --payment-verification-key addr_xvk18359zklg0x68ru6yhxyvsv3slt6wscs00mzsc45jrv9840dfutj5uxg6z6rp4w2pany4kjgg5tly8s5xv7fuyq5tf8kw9ehr7cy4lzcenyhck --testnet-magic 1097911063
> 2cWKMJemoBahHcDQTp8zQDC55wguyn3YqLfddhGtEMdUdbAxJumX8z5cSQXiXKCDn4ifX
> ```

 @johnmathews I get the same as @newhoggy. Check out the latest `master`, run `cabal build` & try the command via `cabal exec`.

**Comment by johnmathews** [comment]
@Jimbo4350  @newhoggy we are all getting the same byron era output. `2cWKMJemoBahHcDQTp8zQDC55wguyn3YqLfddhGtEMdUdbAxJumX8z5cSQXiXKCDn4ifX` is a byron address.

I simply used the `info` option to show more details about the address.

**Comment by newhoggy** [comment]
Please confirm the above PR fixes the problem for you.
