### ISSUE TITLE
[BUG] - Daedalus mainnet 4.04 does not start on ubuntu 18.04

### ISSUE THREAD

**Issue by pentadotddot** [input-output-hk/cardano-node#2601]
Hi!

I have installed several versions of the Daedalus mainnet wallet to my ubuntu 18.04 system, and all worked fine...
Until I updated to 3.3.2 after a while it just did not start.
Therefore I moved to the Flight version, which works fine.
Now I updated to Daedalus mainnet 4.0.4 version, and it does not even start to load, I click on the icon, or just start it from terminal, and nothing happens, even if I wait a lot, it is just does not launch.
I also tried reinstalling as it was documented on iohk website, but same, it just does not even tries to run...

Does anybody has the same issue, or similiar?

Im confused.

I also voted for fund3 and I do not see the reward on the flight version...

Maybe an update will fix it idk.

**Comment by newhoggy** [comment]
Please submit a request to https://support.iohk.io/
