### ISSUE TITLE
[BUG] - Network stuck at epoch boundary

### ISSUE THREAD

**Issue by LaurenceIO** [input-output-hk/cardano-node#2616]
Internal

Node

At the epoch boundary of epochs 259 and 260 on Thursday 15th April block production stopped for over 20 minutes

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by matiwinnetou** [comment]
This is clear, team is very aware of this.

I suggest to subscribe on telegram to SPO announcements.


```
...rlier today, you will likely have noticed a pause in block production of c.25m mins after the recent epoch boundary.

Some spike in CPU usage and network pause is to be expected, and this delay was well within modeled bounds. However, this pause was significantly longer than usual. 

The network is functioning normally. However, over the next 24 hours, our engineers will profile the performance of the node to determine the cause, along with additional testing so we can mitigate and optimize as needed. 

We’ll be sure to share our findings with you once we have determined next steps.

QUICK UPDATE: Last night we reported on the unexpectedly long pause at the epoch boundary.

After investigation today, the node team has now identified the likely root cause. This was due to the node repeating a computation that should have been done just once at the epoch boundary, due to the way the leaders slots are computed in the consensus rules.

We’ve seen positive results from initial tests on the node, and the team has now determined an update that should alleviate the issue at the next epoch boundary. 

We’re continuing to test and will next move the update into QA for final testing. We’ll bring you a further update as soon as we have determined a timeframe for release. Thanks for your cooperation.
```

**Comment by chimaeraa** [comment]
![image](https://user-images.githubusercontent.com/49210365/116011204-03adca80-a639-11eb-85cb-5accd06e76d1.png)
![image](https://user-images.githubusercontent.com/49210365/116011244-35269600-a639-11eb-8042-96126162f931.png)
At the epoch boundary of epochs 261 and 262. for 10 min relay connection lost and miss 235 block. it happen every epoch boundary 
**System info :** 
Ubuntu 20.04
Node version :1.26.2
system config : 6x3GHz cpu + 10GB ram

**Comment by erikd** [comment]
This was definitely an issue with `1.26.1` but should have been fixed by `1.26.2`.

Are you sure you are actually running the version you think you are running? What does `cardano-node --version` say?

**Comment by chimaeraa** [comment]
Yes, I'm sure. I made it from source code. The same thing happened for this epoch and the previous one.
![image](https://user-images.githubusercontent.com/49210365/116044618-6083a200-a686-11eb-8ae0-75c0f4c1fda8.png)

![image](https://user-images.githubusercontent.com/49210365/116045156-01725d00-a687-11eb-90e3-6318e8eff0e7.png)
as you can see it happen for two last epoch.

**Comment by seriru** [comment]
We have the same issue at XORN.

**Comment by kevinhammond** [comment]
Thanks for the report.  `1.26.2` significantly reduces execution costs at the epoch boundary, which has a major positive impact on both block producers and relay nodes.

Relays do behave differently from block producers - the epoch boundary load for relays is based on the number of connected peers.  We're investigating this specifically and will get back to you when we have some information to share.  You may find that reducing the number of connected peers (even just over the boundary) gives a smoother transition.

**Comment by chimaeraa** [comment]
thank you. i have 5 relay . 3 for BP. 2 for other reason. those 2 relays have 15 peer connections but they have same problem. 
in every epoch boundary my relays lost their connection to other relays.

**Comment by seriru** [comment]
At the epoch boundary we see a 25-30% drop in peer connections from our relays to other relays.

**Comment by gabacode** [comment]
Same thing here, it gets stuck around epoch 259. The `socket` file also disappears, and the only solution to make it reappear seems to be to delete the db folder, and start all over again. I been doing that for the last week, would be nice to find a fix!
On `cardano-node 1.26.2` `linux-x86_64` `ghc-8.10` relay.

![screencapture-206-189-55-193-3000-d-K4z3N37w0rk-monitor-cardano-node-2021-05-06-22_05_14](https://user-images.githubusercontent.com/38985346/117359114-3ff1ee00-aeb7-11eb-8e3c-2661566386e2.png)

**Comment by AlterX76** [comment]
Same problem here...stuck on 130 for 5 days....
Btw why do you not provide a bootstrap DB for a fast sync?

**Comment by kingli-crypto** [comment]
We are experiencing similar issue with our relay nodes. Normally see node out of sync with network for 20minutes

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
