### ISSUE TITLE
[FR] - Release the binaries please

### ISSUE THREAD

**Issue by jbarros35** [input-output-hk/cardano-node#2620]
The new release 1.26.2 hasn't binary distributed yet.
As suggestion and to make the SPO job easier to upgrade, you could always release the binary together. We just download it and put to run.
Compiling this thing from scratch is equivalent to having download AdobePhotoshop source code and compiling in order to run, its unnecessary and leads to more mistakes and complications. I'm sure that you have more resources to do that than us.
thank you

**Comment by disassembler** [comment]
This has been in my teams backlog for a while, we just haven't had time to get it done. All the binaries are currently built by hydra already, it's just wrapping it into a GH action to grab the right one and publish with the release notes. FYI I do share links to the hydra build in the telegram channels, but something more official requires time for my team to focus on it.

**Comment by disassembler** [comment]
FYI, in the short term, if you want to find them, go to https://github.com/input-output-hk/cardano-node/commits/<tag> and the CI checks are listed on the commit. Find the hydra required build, and click constituents. You'll see static builds for linux, mac and windows there.

**Comment by r-tde** [comment]
To save folks the 30 seconds of browsing - [here](https://hydra.iohk.io/build/6092531). Don't be alarmed by failing CI checks/tests, just verify which ones they are first :-)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
