### ISSUE TITLE
[BUG] - Invalid snapshot DiskSnapshot: Size mismatch when decoding LedgerState ShelleyBlock

### ISSUE THREAD

**Issue by DanTup** [input-output-hk/cardano-node#2621]
*External*
*Other*

**Summary**
Errors in node logs after upgrading to 1.26.2:

> [cardano-:cardano.node.ChainDB:Error:5] [2021-04-18 12:00:02.85 UTC] Invalid snapshot DiskSnapshot {dsNumber = 24704429, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 128 "Size mismatch when decoding LedgerState ShelleyBlock.\nExpected 3, but found 2."))
> [cardano-:cardano.node.ChainDB:Error:5] [2021-04-18 12:00:02.85 UTC] Invalid snapshot DiskSnapshot {dsNumber = 24699997, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 128 "Size mismatch when decoding LedgerState ShelleyBlock.\nExpected 3, but found 2."))

**Steps to reproduce**
I don't know if this is reproducible, but after restarting my node to run 1.26.2, I see the above errors in the logs. I noticed them because another SPO saw them and asked if it was just him.

**Expected behavior**
No errors reading disk snapshot.

**System info (please complete the following information):**
- OS: cardano-node docker image running on microk8s on Ubuntu Server
- OS Version: 20.04
- Node version: 1.26.2

**Additional context**
I don't know if it's normal, but since it's written as an error and other issues that seem similar to this have been described as bugs, I thought it was worth raising. Feel free to close if this is expected/known.

> danny@k8snode1:~$ microk8s.kubectl logs statefulset.apps/cardano-mainnet-producer-deployment | grep InitFailureRead
> 
> [cardano-:cardano.node.ChainDB:Error:5] [2021-04-18 12:00:02.85 UTC] Invalid snapshot DiskSnapshot {dsNumber = 24704429, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 128 "Size mismatch when decoding LedgerState ShelleyBlock.\nExpected 3, but found 2."))
> [cardano-:cardano.node.ChainDB:Error:5] [2021-04-18 12:00:02.85 UTC] Invalid snapshot DiskSnapshot {dsNumber = 24699997, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 128 "Size mismatch when decoding LedgerState ShelleyBlock.\nExpected 3, but found 2."))

**Comment by sum-blockchain** [comment]
Quick point to note. This error happens only @ MAINNET. The upgrade @ TESTNET looks to be functioning as expected.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
