### ISSUE TITLE
[BUG] - binary of latest release has a wrong package name

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/cardano-node#2628]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
binary of latest release  - 1.26.1 not available 

**Steps to reproduce**
1. Go to https://hydra.iohk.io/job/Cardano/cardano-node/cardano-node-linux/latest-finished
2. revision is 09077b0484dff56a6287d2ead026a3fb5f591854 and the naming of the binary contains 1.26.1

**Expected behavior**
That commit is indeed the latest commit on master - but that means that 1.26.2 should be 
**System info (please complete the following information):**
- OS: [e.g. Ubuntu]

**Comment by r-tde** [comment]
Are you sure that commit is part of the 1.26.2 tag? the latest commit there is `3531289c9f79eab7ac5d3272ce6e6821504fec4c`.

[Build 6092531](https://hydra.iohk.io/build/6092531) has the right package name for example.

**Comment by r-tde** [comment]
If you take a look at the GitHub commit (/PR), you can see the checks that were run against it (automated naturally).

<img width="394" alt="image" src="https://user-images.githubusercontent.com/79268775/115376024-40576d00-a1c6-11eb-9913-59859de85532.png">

Look for the _ci/hydra-build:required_, that's the link to the relevant build based on the PR. It contains all the built packages and within those, the artifacts.

**Comment by laplasz** [comment]
thanks, now I found these artifacts! - so do you know why https://hydra.iohk.io/job/Cardano/cardano-node/cardano-node-linux/latest-finished not pointing to https://hydra.iohk.io/build/6092531 ?

**Comment by r-tde** [comment]
I can only assume so will wait for one of the owners/builders to comment, sorry :|

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
