### ISSUE TITLE
[FR] - Active core node setup validation

### ISSUE THREAD

**Issue by VledicFranco** [input-output-hk/cardano-node#2640]
*External* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
I am a new SPO, and after completing the setup at the docs https://docs.cardano.org/projects/cardano-node/en/latest/ and finding my pool in pooltool.io and finding my relay on the topology file from the IOHK server I really wonder if my block producing node is actually going to actively try to process transactions and mint blocks. I tried to look for documentation on checking for the status of the node to EXPLICITLY see that the node is properly configured to try to mint blocks.

It would be great if we have a simple command that responds simply if the node will even attempt to mint blocks (not a passive node) and preferably reflect that the configuration is valid and that it is an active Pool. This right now feels implicit, in the sense that the ultimate proof comes from waiting for my pool to be so lucky to mint a block.

If there is a way currently I am sorry for wasting your time and I would appreciate a link to the related documentation :)

All the best! and thank you so much for your work and dedication!

**Describe alternatives you've considered**
searching documentation, and using https://pool.vet/#DRDR

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
