### ISSUE TITLE
[FR] - Indicate graceful shutdown with a log message

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2648]
**Internal/External**
*External*

**Area**
*Cardano Node*

**Describe the feature you'd like**

Currently, there is no indication in the log of graceful shutdown. i.e. you cannot tell whether the process was killed and will take > 15min to restart (because of block data re-validation) or gracefully shut down with no additional restart time

**Describe alternatives you've considered**

None. IMHO, it'd be a simple/useful addition

**Additional context / screenshots**

More context about this is given in #2608 and #2627

**Comment by jbgi** [comment]
Just checked and actually there is a log:
```
Shutting down..
```
when killed with `SIGINT`. The log is absent when killed with `SIGTERM`.

**Comment by tdiesler** [comment]
Yes, this is out of date
