### ISSUE TITLE
[FR] - cli query for reserve and treasury

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/cardano-node#2651]
**Internal/External**
*External*

**Area**

*cardano-cli*

**Describe the feature you'd like**
Add a query to cardano-cli to query reserve and treasury pot

**Describe alternatives you've considered**
the account state (reserve and treasury) are available as part of the ledger state dump. The dump has grown big in size on mainnet and is difficult to query these 2 values from it

**Comment by kevinhammond** [comment]
What are you using these for?   That will help prioritisation.

Meanwhile, you can use `grep -m1 reserves f ` or `grep -m1 treasury f` to extract values from the JSON file if you have a full ledger state dump.  You still need to dump the file (about 2.5GB now in plaintext and about 3.5 mins on my system).

I also keep track of the values here (manually updated from a daily cron job, which I store locally).  I don't guarantee to update them immediately, of course (this is just to keep an eye on the ledger operation), but this may be useful to you.

https://docs.google.com/spreadsheets/d/1xny1W7HhHANLNeQcnbr8El5rakJ80VIM7fgDwJ-uqys/edit#gid=0

**Comment by ashisherc** [comment]
I need these values for rewards calculation, so getting them using CLI would be a good integration to have

**Comment by kevinhammond** [comment]
I think your best bet for now is to use command line tools

`cardano-cli query ledger-state --mainnet | grep -m1 reserves`

`cardano-cli query ledger-state --mainnet | grep -m1 treasury`

This runs in 40s on my system and uses no disk space

**Comment by ashisherc** [comment]
Considering there is no quick way to query the account state (there is no specific mini protocol to query reserve and treasury), the CLI would also need to query the full dump and only parse and return the account state. Hence the command suggested by @kevinhammond is what maximum possible and does the same implementation even if CLI provides a specific command. I'm closing this issue here. Might be a good issue for the ledger spec repo to provide more local state protocol queries. cc @JaredCorduan

**Comment by JaredCorduan** [comment]
> Might be a good issue for the ledger spec repo to provide more local state protocol queries.

Those actually live in the consensus layer.
