### ISSUE TITLE
[BUG] - starting the node ends up in "Killed" state

### ISSUE THREAD

**Issue by geantas** [input-output-hk/cardano-node#2653]
*External* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Working on mainnet. Following the instruction on official documentation to install & run the cardano node. When I start the node, leave it few hours to synchronise, I come up to see the status "Killed" in the synchronisation process output.

**Steps to reproduce**
1. Get & install latest versions of cabal, ghc
2. Install libsodium
3. Download source of cardano-node
4. Build the node 
5. Download latest configuration files
6. Start cardano-node in `tmux`
7. Wait for few hours to synchronize
8. See "Killed" on `tmux` screen.

During step 7, I can track the current epoch & block with `cardano-cli query tip --mainnet`.
When the synchronisation is killed, the above command will give me output of:
```
cardano-cli: Network.Socket.connect: <socket: 11>: does not exist (Connection refused)
```

**Expected behavior**
Synchronization runs 24/7 and never gets killed for some unknown reason.

**System info (please complete the following information):**
- OS: Ubuntu
- Version: 20.04
- Node version: 
```
cardano-node 1.26.2 - linux-x86_64 - ghc-8.10
git rev 3531289c9f79eab7ac5d3272ce6e6821504fec4c
```

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/34267171/115960182-327c5180-a510-11eb-9036-30a7f2c41c44.png)
![image](https://user-images.githubusercontent.com/34267171/115960150-fd6fff00-a50f-11eb-8bc8-93ad14ac8c28.png)

**Additional context**
I can re-run the the node and it will continue from the last block. However, after ~5minutes of synchronisation, it will again fail and show the "Killed" message.
No other messages are being shown.
This happens on both the relay and producer blocks.

**Comment by ashisherc** [comment]
@geantas you are running out of RAM (memory). Increase the RAM to about 16 GB and you should be good.

**Comment by architechnique** [comment]
Did increasing the RAM fix the issue? im running into the same problem. I manage to sync up to around 96% until 'Killed' message appears

**Comment by geantas** [comment]
@architechnique yes, I've doubled the RAM and everything started to run smooth.

**Comment by arunwebber** [comment]
I got this error my ram size is 24 gb
