### ISSUE TITLE
[BUG] - 'Ignoring block already in DB' happens too frequently

### ISSUE THREAD

**Issue by rphair** [input-output-hk/cardano-node#2654]
*External* - *Other*
**Summary**

We're not claiming this is a bug, though the term fits more than "feature request."  We suspect this is environmental based on our choice of peers, but have no way to investigate, or to even know what kind of problem this might represent (or _if_ it is a problem), without developer assistance.

At nearly half the slots (1.36 slots per minute on average) one of our stake pool relays gets the common message:

`Ignoring block already in DB: 0x... at slot nnnnnnnn`

Considering there are only 3 total slots per minute on average, I am concerned this suggests an improperly forking peer, or upstream peer, with a race condition as to whether the "good" or "bad" block arrives first each time.

We see this much more on our Asian relay with longer ping times to reliable hosts and not so much on our North American relay, having the same number of peers... 0.46 slots per minute, on average (only ⅓ as much).

We've not posted this enquiry on the Cardano Forum because the question would only be answered only by SPOs who are lacking the same detailed documentation we lack & would have to respond on empirical observation & guesswork just like us.  I know the basics of consensus but not how to determine whether this is a problem and/or how to tell exactly which peer(s) in our immediate topology might be causing it.

So if this question isn't documented anywhere, we hope a node developer can give practical suggestions here & invite the consensus team to give us all some insight.

**Steps to reproduce**

Measured number & frequency of messages on 2 relays (SGP (Asia = problem?) and NYC (North America = OK?)) over last full day of GMT:

```
relay-sgp1$ grep 'Ignoring block already in DB:' node.log | grep ' .2021-04-24' | wc -l
1969
relay-sgp1$ echo '1969 / 24 / 60' | bc -l
1.36736111111111111111
```
```
relay-nyc1$ grep 'Ignoring block already in DB:' node.log | grep ' .2021-04-24' | wc -l
666
relay-nyc1$ echo '666 / 24 / 60' | bc -l
.46250000000000000000
```

**Expected behavior**

Whatever probability the network has of multiple block creation in a slot based on uncertain VRF leadership should be a constant, and therefore the number of rejected blocks above should be the same on two nodes having the same number of peers, unless there is some antagonistic behaviour that is reaching the SGP relay more often than the NYC relay.

**System info**
Ubuntu 20.04
cardano-node 1.26.2 - linux-x86_64 - ghc-8.10
git rev 3531289c9f79eab7ac5d3272ce6e6821504fec4c

**Comment by nfrisby** [comment]
@rphair That message occurs when some block is downloaded more than once, ie from multiple peers. There's only one block involved, not a pair of "good" and "bad".

We will always attempt to download the block from the peer that first sent us the corresponding header. Whether we then also attempt to download it from other peers while waiting for the block depends on various circumstances, including the values of the config variables `MaxConcurrencyBulkSync` and `MaxConcurrencyDeadline`.

I don't have the details paged into my head, but I believe various latency/throughput asymmetries between your two relays' peers could explain why this happens more on one than the other.

Does that assuage your concerns and/or give you some knobs to experiment with?

**Comment by dcoutts** [comment]
@rphair In particular, it'd be interesting to know what values you're using for the `MaxConcurrency*` config entries.

**Comment by rphair** [comment]
Thanks @nfrisby - that does assuage my concerns because it means the asymmetry in our network topology would be enough to account for this difference & that what we've observed doesn't suggest a consensus problem for our distal relay.

After these several weeks the number of `block already in DB` messages on the proximal & distal relays still shows a big difference, but less than before probably from `topology.json` changes.  With the P2P governor expected out soon I've dropped these messages from our attention anyway. 😎

Thanks @dcoutts - we have this set on both relays, according to a suggestion here which @karknu confirmed to me in a Telegram discussion back in January:

`"MaxConcurrencyDeadline": 4,`

We don't have `MaxConcurrencyBulkSync` set on any node since we haven't seen it appear here yet & have no documentation about this set of parameters other than the suggestion above:

https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/index.html

**Comment by rphair** [comment]
p.s. @dcoutts I should have mentioned we also have `MaxConcurrencyDeadline` set on our block producer (connected to both relays) as well, although it's only set to `2`.  From the conversation referenced above I've understood the default is `1`.

**Comment by karknu** [comment]
>  With the P2P governor expected out soon I've dropped these messages from our attention anyway. 😎

The p2p governor will not change this. That is if you set `MaxConcurrencyDeadline > 1`  a p2p-node may still fetch the same block from multiple nodes. We expect that SPOs will be willing to trade speed for efficiency and therefor run with `MaxConcurrencyDeadline > 1`.

The default value for `MaxConcurrencyBulkSync` and `MaxConcurrencyDeadline` is 1.

**Comment by rphair** [comment]
Okay, I assume it is most important to maintain speed, even if it's at the expense of efficiency by processing an incoming block more than once... please correct if I've misunderstood.

If the developers can advise how we might set `MaxConcurrencyBulkSync` then please post here.  Otherwise we're just going along with the popular suggestion of setting `MaxConcurrencyDeadline` to 2 on block producer and 3 or 4 on relays.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
