### ISSUE TITLE
[BUG] - Docker container ignores /etc/hosts entries

### ISSUE THREAD

**Issue by seriru** [input-output-hk/cardano-node#2660]
*External*  

**Area**
*Other*  cardano-node docker container issue

**Summary**
If I put an entry in the /etc/hosts file, it's not resolved correctly in the official docker container.

**Steps to reproduce**
1. create an entry in /etc/hosts
2. start the docker container
3. open a bash shell in the container - docker exec  -it cardano-node /bin/bash
4. confirm the host entry is in the /etc/hosts file
4. ping host created in 1. The result is "Name or service not known"

**Expected behavior**
Host resolution order should start with /etc/hosts and it should be possible to resolve an entry in /etc/hosts.

**System info (please complete the following information):**
- OS: CentOS
- Version 8 
- Node version 1.26.2

**Comment by tdiesler** [comment]
I don't think that this is a valid request. The docker container would not see whatever you put in /etc/hosts. Its own /etc/hosts content is controlled by the Docker runtime

```
$ docker exec relay cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.28.0.3      relay
```

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
