### ISSUE TITLE
[FR] - add metrics for `cold.counter` values

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#2662]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
`node monitoring`

**Describe the feature you'd like**
Add 2 different metrics tracking:
- on-chain value of `cold.counter`
- value of `cold.counter` used for starting the node

**Describe alternatives you've considered**
If the current value of the counter < the on-chain value, the pool will not be able to create blocks, so it would be very useful to be able to track this situation through monitoring.

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
