### ISSUE TITLE
[BUG] - Cabal build failing with 'could not resolve dependencies'

### ISSUE THREAD

**Issue by tyleratracey** [input-output-hk/cardano-node#2670]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
I am installing a fresh build of cardano-node on AWS Linux 2 instance build 1.26.2 and when running 'cabal build all' it is failing with the below error.

Warning: Requested index-state2021-03-15T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-03-14T23:47:09Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: cardano-crypto-class (user goal)
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
[__0] fail (backjumping, conflict set: cardano-crypto-class)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class

I have followed the steps found in this documentation: https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

I have tried adding the below to my cabal.project.local file but no success. This error is also being produced when running a cabal configure command.

**Steps to reproduce**

git clone https://github.com/input-output-hk/cardano-node.git
cd cardano-node
git fetch --all --tags
git tag
git checkout tags/1.26.2

cabal configure --with-compiler=ghc-8.10.2

echo "package cardano-crypto-praos" >>  cabal.project.local
echo "  flags: -external-libsodium-vrf" >>  cabal.project.local

cabal build all

**Expected behavior**
I expect it to build successfully.

**System info (please complete the following information):**
- OS: Amazon Linux
- Version 2
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
