### ISSUE TITLE
[BUG] - CNTools failed to load common env file

### ISSUE THREAD

**Issue by GoldenArchitect** [input-output-hk/cardano-node#2679]
**Internal/External**
External

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
After launching my node and trying to sync it, I am receiving several errors. The first begins with the following output:  Stopped Cardano Node.
May 06 17:13:16 block-producer systemd[1]: Started Cardano Node.
May 06 17:13:18 block-producer cnode[78309]: Listening on http://127.0.0.1:12798

to which I use ./gLiveView to check if it is syncing and I receive the following output: Looks like cardano-node is running with socket-path as /opt/cardano/cnode/sockets/node0.socket, but the actual socket file does not exist.
This could occur if the node hasnt completed startup or if a second instance of node startup was attempted!
If this does not resolve automatically in a few minutes, you might want to restart your node and try again.

ERROR: CNTools failed to load common env file
Please verify set values in 'User Variables' section in env file or log an issue on GitHub

**Expected behavior**
After using .gLiveView I was expecting to see the status of my node successfully syncing. However, it seems there is a deep issue. 

**System info (please complete the following information):**
- OS:Ubuntu 
- Version: 20.04
- Node version: 1.26.2

**Additional context**
When I used the command **sudo journalctl -n 30 -u cnode.service** I received the following: ]: /opt/cardano/cnode/scripts/cnode.sh: line 57: 78309 Killed                  cardano-node "${CPU_RUNTIME[@]}" run --topology "${TOPOLOGY}" --config "${CONFIG}" --database-path "${DB_DIR}" --socket-path "${CARDANO_NODE_SOCKET_PATH}" --port ${CNODE_PORT} "${host_addr[@]}"
May 06 17:21:37 block-producer systemd[1]: cnode.service: Main process exited, code=exited, status=137/n/a
May 06 17:21:37 block-producer systemd[1]: cnode.service: Failed with result 'exit-code'.
May 06 17:21:42 block-producer systemd[1]: cnode.service: Scheduled restart job, restart counter is at 503.
May 06 17:21:42 block-producer systemd[1]: Stopped Cardano Node.
May 06 17:21:42 block-producer systemd[1]: Started Cardano Node.
May 06 17:21:45 block-producer cnode[78602]: Listening on http://127.0.0.1:12798

I set my CNODE Port in the env file, so that doesn't seem to be the issue either.

**Comment by ClecknerT** [comment]
Same issue.
System info:
OS:Ubuntu
Version: 20.04
Node version: 1.26.2

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
