### ISSUE TITLE
Is there any bootstrap DB for the nodes?

### ISSUE THREAD

**Issue by AlterX76** [input-output-hk/cardano-node#2684]
Do you provide or consider to provide a bootstrap DB for nodes?
It takes just ages to sync the blockchain!

**Comment by erikd** [comment]
What do you mean by "ages"? Is "ages" 30 minutes or a year?

**Comment by AlterX76** [comment]
I don't know...I started the sync and at epoch 131 it got stuck there without going anywhere for days, then I stopped it because it was not going anywhere.
Anyway whatever is "ages", is there any bootstrap for the old data? I have created a relay node on raspberry and it took 3 days to sync the blockchain; although acceptable time, why lose 3 days waiting for something that in 4 hours can be achieved?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
