### ISSUE TITLE
/v2/stake-pools is generating 100+ seconds

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-node#2696]
Is valid that api call /stake-pools takes about 100-150s? In past it was in a few seconds done. Other tested calls are instant.

[cardano-wallet.api-server:Info:65] [2021-05-12 08:35:00.86 UTC] [RequestId 0] [GET] /v2/stake-pools?stake=0
[cardano-wallet.network:Info:65] [2021-05-12 08:35:00.86 UTC] Will query non-myopic rewards using the stake 0.000000
[cardano-wallet.network:Notice:65] [2021-05-12 08:36:56.00 UTC] Query stakePoolsSummary took 115.142201748s (too slow)
[cardano-wallet.network:Info:65] [2021-05-12 08:36:56.00 UTC] Fetched pool data from node tip using LSQ. Got 2577 pools in the stake distribution, and 2623 pools in the non-myopic member reward map.
[cardano-wallet.api-server:Error:65] [2021-05-12 08:36:58.46 UTC] [RequestId 0] GET /v2/stake-pools 200 OK in 117.603697449s

Latest x64 version. Tried a few times, same results.

**Comment by KtorZ** [comment]
cc @dcoutts @nc6

**Comment by chrispy1174** [comment]
addr1qy5luhyvx73jpnvfl3eh6plxrga8rceysyphkzkzjfd0plhxe9l5puz3337y26550adjjuf7sl59895wwfjczrepzp8sjqz5gn
[cardano-brand-assets.zip](https://github.com/input-output-hk/cardano-node/files/6605195/cardano-brand-assets.zip)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by KtorZ** [comment]
I don't think anything was done to address this particular issue though.
