### ISSUE TITLE
[BUG] - CABAL 3.4.0.0 installation problem with GHC

### ISSUE THREAD

**Issue by dominican23** [input-output-hk/cardano-node#2714]
**Internal/External**
*External*

**Area**.
*Other*  Installation

**Summary**
An error is displayed at step "cabal configure --with-compiler=ghc-8.10.2"

I tried with GHC 8.6.5, with different error :
"Warning: cannot determine version of /usr/local/bin/ghc-8.6.5 :
""
cabal: The program 'ghc' version >=7.0.1 is required but the version of
/usr/local/bin/ghc-8.6.5 could not be determined."

**Steps to reproduce**
1. follow the documentation https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html
2. At action "cabal configure --with-compiler=ghc-8.10.2"
3. An error is displayed
"Warning: Unknown/unsupported 'ghc' version detected (Cabal 2.4.0.1 supports
'ghc' version < 8.7): /usr/local/bin/ghc-8.10.2 is version 8.10.2
cabal: No cabal file found."

**Expected behavior**
Compilation without error

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04.2
- Node version 3.4.0.0
- VM : VirtualBox running on mac intel

**Comment by rdlrt** [comment]
The [instructions](https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html#downloading-unpacking-installing-and-updating-cabal) also look for cabal-3.4.0 , your output suggests the version of cabal you're using is 2.4

**Comment by dominican23** [comment]
Yes that's the problem. I took Cabal 3.4.0.0 and the console gives the error for a 2.4.0.1

If I do a cabal --version, here is the result : 

~/src$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 

What is wrong ?

**Comment by erikd** [comment]
@dominican23 Do you have `ghc-8.10.4` installed?

**Comment by dominican23** [comment]
At the time of the message it was 8.10.2. Now it works after doing it again from scratch with updated packages.

Thanks
