### ISSUE TITLE
stake-snapshot crashes cardano-node

### ISSUE THREAD

**Issue by seriru** [input-output-hk/cardano-node#2717]
When I run `docker exec  -e CARDANO_NODE_SOCKET_PATH=/cardano/node.sock cardano-node cardano-cli query stake-snapshot --stake-pool-id 6a37c771eb33798edea1cc2b95759fc30a7765bbfc63668bdc92c633 --mainnet` it sometimes crashes the cardano-node process on my 8GB RAM machines. This is not the case with a machine running 16GB RAM. 

Could you advise which +RTS flags I can use to minimise the memory used for this operation, please? 

Best Regards,

Richard

**Comment by woltere** [comment]
I have seen the same happen on a machine with 16GB of RAM. The cardano-node get OOM kill. The reason being that the `cardano-cli query stake-snapshot`  seems to require several GBs of RAM.

Running the cli with max 3GB of Heap can't run to completion
```
cardano-cli +RTS -M3G -RTS  query stake-snapshot --stake-pool-id xxxxxxx --mainnet

cardano-cli: Heap exhausted;
cardano-cli: Current maximum heap size is 3221225472 bytes (3072 MB).
cardano-cli: Use `+RTS -M<size>' to increase it.
```

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
