### ISSUE TITLE
Chain density assumptions

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#272]
the calculation of chain density (#250) makes the assumption that the length of an epoch depends on the parameter _k_ = 2160 (10x in Byron). In case of Praos, epochs will likely be shorter.

TODO in cardano-node/src/Cardano/Tracing/Tracers.hs#L186

This is a ***reminder*** that this will not be the case in _Shelley_ and so the code needs to be adapted.

**Comment by deepfire** [comment]
`fragmentChainDensity` is now k-agnostic, this issue is no longer relevant.
