### ISSUE TITLE
[FR] - 

### ISSUE THREAD

**Issue by fede-org** [input-output-hk/cardano-node#2729]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by nc6** [comment]
Closing since there's nothing actually described here
