### ISSUE TITLE
Transaction generator: send transactions to multiple nodes

### ISSUE THREAD

**Issue by denisshevchenko** [input-output-hk/cardano-node#273]
Currently tx generator is able to connect to _one single_ node (of the cluster) and send transactions to this node only. It would be useful to be able to send transactions to multiple nodes in the cluster (because it's more real-life case).

There are two possible ways how to do it. For example, if we have a cluster from 3 nodes (`a1`, `b1` and `c1`), we could:

1. run _one_ instance of tx generator with an ability to connect to `a1`, `b1` and `c1` and send transactions to all three nodes (sequentially or randomly). 
2. run _multiple_ instances of tx generator, for example `tx_gen_a1`, `tx_gen_b1` and `tx_gen_c1`, so `tx_gen_a1` will send transactions to `a1`, `tx_gen_b1` - to `b1` and `tx_gen_c1` - to `c1`.

AFAIU, the first way is assuming some changes in the tx generator's code. The second way is assuming some changes in cluster's configuration.

**Comment by mrBliss** [comment]
Note that a node will already send incoming transactions to other nodes via the tx-submission protocol.

Will clients in practice also send their transactions to multiple nodes?

**Comment by denisshevchenko** [comment]
> node will already send incoming transactions to other nodes via the tx-submission protocol.

Of course! Currently _one_ node receives all transactions and just share them with other nodes, but we want to be able to test situation when _different_ nodes receive transactions and share them with other nodes. It's more real-life case (transactions are sending to the different nodes of the cluster, not to the _same_ node).

> Will clients in practice also send their transactions to multiple nodes?

I don't know. :-)

**Comment by mrBliss** [comment]
> > node will already send incoming transactions to other nodes via the tx-submission protocol.
> 
> Of course! Currently _one_ node receives all transactions and just share them with other nodes, but we want to be able to test situation when _different_ nodes receive transactions and share them with other nodes. It's more real-life case (transactions are sending to the different nodes of the cluster, not to the _same_ node).

Ah, I misread. That makes sense indeed.

**Comment by CodiePP** [comment]
first step:

* accept list of target nodes from command line argument (by name/IP address)
* demonstrate on local setup that multiple nodes are receiving txs from the tx generator through "node2node" protocol via TCP/IP

second step:

* install the above changes on the cluster
* demonstrate that the tx generator is sending txs to multiple nodes

**Comment by denisshevchenko** [comment]
> accept list of target nodes from command line argument (by name/IP address)

Not by IP address, but by node ids (as `--node-id 0`). Corresponding IP addresses and ports will be taken from topology file.

**Comment by denisshevchenko** [comment]
https://github.com/input-output-hk/cardano-node/pull/293
