### ISSUE TITLE
[BUG] - Block producer fails to check leadership when doing ledger snapshot

### ISSUE THREAD

**Issue by rene84** [input-output-hk/cardano-node#2731]
**Internal/External**
*External*   SECUR stakepool operator.

**Area**
*Block minting* 

**Summary**
In normal operations of a stakepool, the block producing node is consistently missing a few seconds whenever it is logging TraceLedgerEvent.TookSnapshot

**Steps to reproduce**
1. Normal block producing operations
2. Search for TookSnapshot in the logs
3. Inspect log statements before and after it

**Expected behavior**
A continued stream of TraceStartLeadershipCheck log statements of one per slot (second) 

**System info (please complete the following information):**
- OS: AWS2 (ECS optimized AMI
- Version: amzn2-ami-ecs-hvm-2.0.20210514-x86_64-ebs
- Node version: 1.27.0 but noticed it on 1.26.2 as well
- Running on AWS r5.large instance
- Ledger files are backed by EFS

**Screenshots and attachments**
- screenshot of logs and CPU/Mem at corresponding timestamp

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/7099469/119249123-9426ee80-bb96-11eb-96d2-3c3f4d487ed6.png">
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/7099469/119249157-b02a9000-bb96-11eb-8065-f420fdda0de5.png">

**Comment by rene84** [comment]
I'm going to get more granular cpu stats to see if it maxes out.

**Comment by rene84** [comment]
This is a custom metric counting the number of leadership check log statements per minute for four BP pools over the past three hours. Count of 60 is expected. You can see that there are dips to 53, meaning a blackout of 7 seconds in the minute.

Note that an r5.large has 2 CPU with a boost of 3.1Ghz and 16GB of memory. Will also be trying with an image with more CPU to check if that resolves the issue

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/7099469/119271494-1ac4e580-bc02-11eb-8f7a-e3d1a4df2812.png">

**Comment by gitmachtl** [comment]
Yes we started to notice such "blackouts" a while ago and it should be fixed ASAP.

**Comment by gitmachtl** [comment]
I did a test here on my machine in a QEMU-VM (not docker) now for a day, i don't see any leaderSlotCheck failures at all.
![image](https://user-images.githubusercontent.com/47434720/119495496-c08f6600-bd62-11eb-8277-032b039b297d.png)

There would be an errorline if there is a step greater than 1 on the slotNumber. So i guess it has something to do with your r5.large instance?

**Comment by rene84** [comment]
This is second-level CPU statistics on a relay that is resource-starved (running on t3.small), but has 2 CPUs available, during the moment when the relay is making a snapshot (as found in the log file).

We can see that the CPU I/O wait time is at 100% meaning that there is CPU available, but the process is waiting for I/O. Translating this to the issue at hand, it looks like the Forge thread is waiting for the thread that is making the snapshot. Can this be the case? And if so, why does this need to be the case?

https://veithen.io/2013/11/18/iowait-linux.html
![WhatsApp Image 2021-05-27 at 08 11 49 (1)](https://user-images.githubusercontent.com/7099469/119775494-f6982b80-bec3-11eb-8c1c-a893b22c7240.jpeg)
![WhatsApp Image 2021-05-27 at 08 12 11](https://user-images.githubusercontent.com/7099469/119775502-fb5cdf80-bec3-11eb-917e-185eeeb10829.jpeg)

**Comment by rene84** [comment]
I managed to work around this issue by provisioning an EBS based SSD disk instead of network attached storage (EFS). The snapshots are now not causing io_wait anymore so the slot leadership check occurs on time.

**Comment by btbf** [comment]
Are there any other solutions to this problem?
My Server is not AWS, but it has 6Core 16GB specs, but I am getting CPU spikes when TraceLedgerEvent.TookSnapshot log is generated, and at the same time slotMissedNum is increasing.[
![missednum](https://user-images.githubusercontent.com/37224549/130496433-00930a66-693c-4e8f-955a-5c0019559858.png)
](url)

**Comment by woltere** [comment]
> Are there any other solutions to this problem? My Server is not AWS, but it has 6Core 16GB specs, but I am getting CPU spikes when TraceLedgerEvent.TookSnapshot log is generated, and at the same time slotMissedNum is increasing.[ ![missednum](https://user-images.githubusercontent.com/37224549/130496433-00930a66-693c-4e8f-955a-5c0019559858.png) ](url)

Maybe you can check the memory usage/GC status arround the time of snapshot. I suspect you'll see an increase in memory usage and some major GC's during/after he snapshot.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
