### ISSUE TITLE
[BUG] - IPv6 addresses in mainnet-toplogy.json do not work

### ISSUE THREAD

**Issue by weebl2000** [input-output-hk/cardano-node#2732]
**Internal/External**
*External*

**Area**
*Other*  

**Summary**
If one is to place an IPv6 address in Producers section of topology.json, this does not work. 

**Steps to reproduce**
1. Configure your topology.json that you start cardano-node with
2. Add IPv6 address like so:

```
{
  "Producers": [
    {
      "addr": "2001:984:5a5:1:aaaa:aada:f00d:cafe",
      "port": 3001,
      "valency": 1
    }
  ]
}
```

3. Start cardano-node
4. See error in logs

```
cardano.node.IpSubscription:Error:621
Unsupported remote target address [2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001
```

You can see that it parses it as an IPv6 address, hence the [] block tags. But still it does not connect. This machine is fully IPv6 connected.

**Expected behavior**
I expect IPv6 to work, future of the internet.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version 1.27.0

**Screenshots and attachments**
- Seems clear enough

**Additional context**

telnet works fine:

```
$ telnet -6 2001:984:5a5:1:aaaa:aada:f00d:cafe 3001
Trying 2001:984:5a5:1:aaaa:aada:f00d:cafe...
Connected to 2001:984:5a5:1:aaaa:aada:f00d:cafe.
Escape character is '^]'.
```

**Comment by jbgi** [comment]
are you providing a `--host-ipv6-addr` ? If not, do you get a different result if you do?

**Comment by weebl2000** [comment]
> are you providing a `--host-ipv6-addr` ? If not, do you get a different result if you do?

Currently not running with any host specified. Just a port. I can try specifying a --host-ipv6-addr and let you know if behavior changes.

**Comment by weebl2000** [comment]
> are you providing a `--host-ipv6-addr` ? If not, do you get a different result if you do?

Just around to testing, same behavior if I specify an IPv6 address.

I would like to help debugging this issue. I know Haskell, but it has been 8~ years since I've last used it. So I'll have to dive into what IDE to use etc.

**Comment by weebl2000** [comment]
@jbgi What's the best channel for getting help when starting cardano-node development? I've got my local IDE setup - but if I have questions where can I best reach out?

**Comment by weebl2000** [comment]
Just tried on my local machine, it works there. I will try to debug from the node that is displaying this issue:

```
*Main> :set args run --topology /home/weebl/cardano/mainnet-topology.json --database-path /home/weebl/cardano/db --socket-path /home/weebl/cardano/db/node.socket --port 3001 --config /home/weebl/cardano/mainnet-config.json
*Main> main
Listening on http://127.0.0.1:12798
[tpw540:cardano.node.networkMagic:Notice:72] [2021-06-01 13:30:38.98 UTC] NetworkMagic 764824073
[tpw540:cardano.node.basicInfo.protocol:Notice:72] [2021-06-01 13:30:38.98 UTC] Byron; Shelley
[tpw540:cardano.node.basicInfo.version:Notice:72] [2021-06-01 13:30:38.98 UTC] 1.27.0
[tpw540:cardano.node.basicInfo.commit:Notice:72] [2021-06-01 13:30:38.98 UTC] 8fe46140a52810b6ca456be01d652ca08fe730bf
<snip>
[tpw540:cardano.node.IpSubscription:Info:123] [2021-06-01 13:30:41.71 UTC] IPs: 0.0.0.0:0 [::]:0 [[2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001] Trying to connect to [2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001
[tpw540:cardano.node.IpSubscription:Info:135] [2021-06-01 13:30:41.72 UTC] IPs: 0.0.0.0:0 [::]:0 [[2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001] Connection Attempt Start, destination [2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001
[tpw540:cardano.node.IpSubscription:Notice:123] [2021-06-01 13:30:41.72 UTC] IPs: 0.0.0.0:0 [::]:0 [[2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001] Waiting 0.025s before attempting a new connection
[tpw540:cardano.node.ChainDB:Info:109] [2021-06-01 13:30:41.72 UTC] Took ledger snapshot DiskSnapshot {dsNumber = 26218, dsSuffix = Nothing} at cc1337911e1594a3944dd58d56784f86efb372b89ca46786910bc4bf62f83803 at slot 26218
[tpw540:cardano.node.IpSubscription:Notice:135] [2021-06-01 13:30:41.73 UTC] IPs: 0.0.0.0:0 [::]:0 [[2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001] Connection Attempt End, destination [2001:984:5a5:1:aaaa:aada:f00d:cafe]:3001 outcome: ConnectSuccessLast

```

**Comment by weebl2000** [comment]
Mysteriously enough, after restarting the node (without changing anything), it seems to be able to connect just fine.

I will try a few more things later this week to see if I can reproduce it in any way.

**Comment by weebl2000** [comment]
Actually, problem was. If one of IPv4 / IPv6 is configured - it ignores the other one. Not sure if this is by design, but I've created a PR that should silently try the other protocol if it's not been tried.

**Comment by 2072** [comment]
Usually when one specifies an IP address for a service to use, it means that one wants to bind the listening port to a specific interface on purpose so that only this interface is used for the service's traffic. The convention is that if you want to listen on every interface you do not provide any binding address, just a listening port. If I understand your prosed change it would prevent people from using a specific interface.

**Comment by weebl2000** [comment]
> Usually when one specifies an IP address for a service to use, it means that one wants to bind the listening port to a specific interface on purpose so that only this interface is used for the service's traffic. The convention is that if you want to listen on every interface you do not provide any binding address, just a listening port. If I understand your proposed change correctly it would prevent people from using a specific interface.

Hi 2072, no my proposed change will still allow anyone to specify an interface. But if only IPv4 interface is defined, it will still be able to use the IPv6 socket for outbound connections.

**Comment by coot** [comment]
It's better to be explicit, if one wants to use ipv6 then you can enable it through `--host-ipv6-addr`.  There are real life scenarios in which one does not want to use `ipv6` on a `ipv6` capable host, which we need to support too.

**Comment by weebl2000** [comment]
> It's better to be explicit, if one wants to use ipv6 then you can enable it through `--host-ipv6-addr`. There are real life scenarios in which one does not want to use `ipv6` on a `ipv6` capable host, which we need to support too.

Agreed. I think there should be a differentiation between opening a port to listen on, versus sockets available to make outbound connections though. 

imho this is a great fallacy to not be able to connect over IPv6 without specifying a host listen address for IPv6. IPv6 is the future of the internet and I feel it should be easier to connect to IPv6 relays.

**Comment by weebl2000** [comment]
> It's better to be explicit, if one wants to use ipv6 then you can enable it through `--host-ipv6-addr`. There are real life scenarios in which one does not want to use `ipv6` on a `ipv6` capable host, which we need to support too.

Agreed. I think there should be a differentiation between opening a port to listen on, versus sockets available to make outbound connections though. 

imho this is a great fallacy to not be able to connect over IPv6 without specifying a host listen address for IPv6. IPv6 is the future of the internet and I feel it should be easier to connect to IPv6 relays.

**Comment by weebl2000** [comment]
> It's better to be explicit, if one wants to use ipv6 then you can enable it through `--host-ipv6-addr`. There are real life scenarios in which one does not want to use `ipv6` on a `ipv6` capable host, which we need to support too.

Agreed. I think there should be a differentiation between opening a port to listen on, versus sockets available to make outbound connections though. 

imho this is a great fallacy to not be able to connect over IPv6 without specifying a host listen address for IPv6. IPv6 is the future of the internet and I feel it should be easier to connect to IPv6 relays.

**Comment by andrejpodzimek** [comment]
I can actually imagine scenarios where an IPv4-enabled host wants to disable IPv4 (and I personally do that on my IPv6-only networks). Future-proof software should consider IPv6 the default and perhaps attempt to automatically disable IPv4 whenever reasonable. After all, decentralization and IPv4 will never work together properly.

**Comment by weebl2000** [comment]
> I can actually imagine scenarios where an IPv4-enabled host wants to disable IPv4 (and I personally do that on my IPv6-only networks). Future-proof software should consider IPv6 the default and perhaps attempt to automatically disable IPv4 whenever reasonable. After all, decentralization and IPv4 will never work together properly.

I agree it should be able to disable. But currently configuring only one address implicitly disables the other protocol. I would prefer a solution that makes disabling a protocol more explicit.
