### ISSUE TITLE
[BUG] - Sync error when runnning on testnet

### ISSUE THREAD

**Issue by profd2004** [input-output-hk/cardano-node#2734]
**External**

**Area**
SPO

**Summary**
Is the testnet busted? I keep getting ChainTransitionError. If there are working nodes out there that's not busted, how do a list for my topology?

**Steps to reproduce**
1. delete and rsync testnet db 
2. It fails to sync when it transitions to shelley:
`[2021-05-23 17:44:21.60 UTC] IP 195.154.69.26:3003 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 1598400, blockPointHash = 02b1c561715da9e540411123a6135ee319b02f60b9a11a603d3305556c04329f})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFKeyBadNonce (Nonce "81e47a19e6b29b0a65b9591762ce5143ed30d0261e5d24a3201752506b20f15c") (SlotNo 1598400) (Nonce "74a0665cf3990f72fea801a670dfddb9efa4815d13bc0779bab26f15e42fcf46") (CertifiedVRF {certifiedOutput = OutputVRF {getOutputVRFBytes = "t\231\145\196\165ZhA\137S\209{Z<1\194\225]Yq\235\&7#!\161:\147\129Q\236x\207\195z\170\155\182mw\141\182\135\249\209\178\134\&3_:\167b\135\204\&4\205Z\172\230\163\226\EM\DC2\226\182"}, certifiedProof = CertPraosVRF "!\202\180:L)*\DC2\250\SOH\141V \240Z\EOT\n\183\245\141\SUB\191\ETXQ\"\EOT\155A\SOH'\160LD\253\204Z\249\129/i\178\237p\155\140\240\142\183)LG\137q\248\DLE\DC1\130W\183\162\149\DEL6=[5\225/18\154\192=\242\255\181\f\190\190\t"}))]})))) (Tip (SlotNo 1598339) c24fa5ebf4d88a653a6762773278b05e68a9da08fdcabac0f58abafdeedd049d (BlockNo 1597072)) (Tip (SlotNo 27422626) fc0213330f879136967b77a56c2694810ec4cf58925e9e6cfafdd61aa53690c7 (BlockNo 2608001))))) 200s 200s
`

**Expected behavior**
Node should sully sync up and starts validating txs.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version: 1.27.0

**Additional context**
When I take the same docker image and running on the mainnet it syncs and starts validating txs with no issues. The problem seems to only be affecting the testnet. I've rotated out a lot of nodes in my topology to no avail.

I am getting my config config files from https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/index.html, which was pointing to hydra build # [6426791](https://hydra.iohk.io/build/6426791/download/1/index.html) at the time of my last attempt. 

I've also tried (re)syncing with config files from build # [6198010](https://hydra.iohk.io/build/6198010/download/1/index.html) which had the same issue as well.

**Comment by erikd** [comment]
You should specify exactly where you are getting the config files.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
