### ISSUE TITLE
How to fetch details of single transaction ?

### ISSUE THREAD

**Issue by rajqumar** [input-output-hk/cardano-node#2742]
I want to fetch details of a single transaction only through the hash / id of the transaction. I need details like sender address, fee amount, no of confirmations and timestamp ? Please help.

**Comment by mmahut** [comment]
You need something that keeps the history of the state of the blockchain, have a look at [cardano-db-sync](https://github.com/input-output-hk/cardano-db-sync/), [ogmios](https://github.com/KtorZ/cardano-ogmios) or if you are looking for a hosted solution [blockfrost.io](https://blockfrost.io).

**Comment by rajqumar** [comment]
> You need something that keeps the history of the state of the blockchain, have a look at [cardano-db-sync](https://github.com/input-output-hk/cardano-db-sync/), [ogmios](https://github.com/KtorZ/cardano-ogmios) or if you are looking for a hosted solution [blockfrost.io](https://blockfrost.io).

I tried most of the stuff.

While building cardano-db-sync, I am getting a number of errors like DNSSubscriptionError, MuxError. 
I tried running the postgrest in cardano-rosetta docker, but that too is failing.
cardano-rosetta has /search/transaction indexer API, which is still not implemented.
cardano-wallet provides individual transaction information, for that you need to provide wallet-id. Which we do not have if the transaction is from external sources.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
