### ISSUE TITLE
[BUG] - Permission checks on secret keys too restrictive

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2744]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**

*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The node when started as a block producing node fails to start up if privileges are given at group level. This is overly restrictive and encourages users to work around sane POSIX permissions.

The main drawback here is if a user wants to allow only the node to have read permissions but have another admin user on the machine that administers have write. In this case, the user needs to make that admin user the same user that runs the node, which leads to an insecure configuration, or sudo to the node service to make any changes (another not ideal situation), or they keep a shadow copy of the secrets and copy them somewhere for the node to use and set permissions that way, which creates an extra step to making changes that could be missed for example when rotating opcert or replacing a compromised VRF skey. Another undesirable work-around is do all maintenance as root.

Another use case for this would be deployment tooling, that does automated tasks such as rotate the KES key needs to sudo to the node user (or root) when doing maintenance tasks.

The negative side to doing this is if a user shares a machine with other users and they're all in a default group, that other user can read the secret keys. However; I would argue that this is a system configuration issue to remedy and not the domain of the node to try to prevent.

**Steps to reproduce**
chmod g+r vrf.skey
restart node

**Expected behavior**
Node would start with group read permissions on a key file

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]
- Node version (output of `cardano-node --version`)
- CLI version  (output of `cardano-cli --version`)

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by rvl** [comment]
As an example, OpenSSH requires mode 0600 for its private key files, but then again, there's no such thing as automatic key rotation for ssh.

It could be configured with an option like `cardano-node run --disallowed-skey-modes=MASK` where mask is an octal number. The default is 77, allow group readable key files is 37, permit anything is 0. Perhaps this is too complicated though. :nerd_face:

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
