### ISSUE TITLE
Merging logging configuration into node's configuration

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#275]
logging configuration has been kept in its own Yaml file.
now, we want to integrate this configuration into the node's configuration file (also Yaml format). 

the key `logging-config` (valid name?) shall contain the logging configuration.

the _iohk-monitoring_ framework has read the Yaml into an internediary representation: https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/iohk-monitoring/src/Cardano/BM/Data/Configuration.lhs#L41
and starting from this, built up configuration: https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs

**Comment by Jimbo4350** [comment]
1) #278
