### ISSUE TITLE
[BUG] - Install the newly built node and CLI commands to the ~/.local/bin directory:

### ISSUE THREAD

**Issue by dwaynemcgordon** [input-output-hk/cardano-node#2761]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Cannot get past this step without the error

**Steps to reproduce**
1. Go to 'Step - Building and installing the node'
2. Run Command = cp -p "$(./scripts/bin-path.sh cardano-node)" ~/.local/bin/
3. See error:  -bash: ./scripts/bin-path.sh: No such file or directory cp: cannot stat '': No such file or directory

**Expected behavior**
should be able to proceed to the next part of the install

**System info (please complete the following information):**
- OS Name:  Ubuntu
- OS Version [e.g. 20.06]
- Node version (output of `cardano-node --version = 3.4.0.0.0

- CLI version  (output of `cardano-cli --version`)

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
![Screenshot 2021-05-28 220453](https://user-images.githubusercontent.com/85006386/120058654-56e0b780-c001-11eb-9f14-ffc6b91a6630.png)

**Additional context**

**Comment by rdlrt** [comment]
You need to be in the cardano-node repository folder (it is copying to ~/.local/bin, not from) to execute this command

**Comment by dwaynemcgordon** [comment]
> You need to be in the cardano-node repository folder (it is copying to ~/.local/bin, not from - and relative path is from git repo) to execute this command

 Thank you for that, I started a new build out and i am getting the same error as before

![cardano-node 2021-05-29 162856](https://user-images.githubusercontent.com/85006386/120087230-0b7ae780-c09b-11eb-97ca-f9f35d21dfc6.png)

**Comment by 34r7h** [comment]
there's no bin-path.sh

**Comment by dwaynemcgordon** [comment]
This is from the instructions from your main GitHub site.

cardano-node/install.md at master · input-output-hk/cardano-node (github.com)<https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md>

Under “Building and installing the node” , “install the newly built node and CLI commands to the ~/.local/bin directory:”

Please advise on next steps.
Thank You!



Dwayne Mc Gordon
Chief Executive Officer
Email: ***@***.******@***.***>
Cell: (623) 297-5884
Office: 888-511-1179

**Comment by CantTouchDis** [comment]
which version of the node did you checkout? I think the `bin-path.sh` script was added not that long ago (2 Months)

you don't need that script tho, you could also use `cabal install` as far as I know.

the last time I build the node I checked out 

`git checkout tags/1.27.0`

```
~/cardanoSourceDir/cardano-node$ git status
HEAD detached at 1.27.0
```

```
~/cardanoSourceDir/cardano-node$ ls scripts/ | grep bin-path
bin-path.sh
```

any version older than `1.26.2 ` wont have that script

**Comment by dwaynemcgordon** [comment]
My checkout is:  git checkout tags/1.9.3
I am also using Ubuntu 20.04



Dwayne Mc Gordon
Chief Executive Officer
Email: ***@***.******@***.***>
Cell: (623) 297-5884
Office: 888-511-1179

**Comment by rdlrt** [comment]
> My checkout is: git checkout tags/1.9.3

Not sure which doco are you using , but that tag's ancient, as software versioning standard is usually semantic (so 1.9 is smaller than 1.10). The current [latest release](https://github.com/input-output-hk/cardano-node/releases/latest)  is 1.27.0 as indicated above

**Comment by CantTouchDis** [comment]
@dwaynemcgordon  could you explain how you checked out that tag, maybe other people also made that mistake. (Especially @34r7h with all the issues he created.)

**Comment by dwaynemcgordon** [comment]
Here is what I see after running these commands from the walk through.

***@***.***D75ABF.D02BBE20]

***@***.***D75ABF.D02BBE20]
***@***.***D75ABF.D02BBE20]




Dwayne Mc Gordon
Chief Executive Officer
Email: ***@***.******@***.***>
Cell: (623) 297-5884
Office: 888-511-1179

**Comment by dwaynemcgordon** [comment]
After a new build with git checkout tags/1.27.0
I have new error and also same error with Building and Installing node: please see screen shots below.

***@***.***D75AC8.66E54720]


I path my way to the folder and file. The file is there as you stated. When running the command from the ~/src/cardano-node path still wont run properly. Please see screen shots below.

***@***.***D75AC8.66E54720]



Dwayne Mc Gordon
Chief Executive Officer
Email: ***@***.******@***.***>
Cell: (623) 297-5884
Office: 888-511-1179

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
