### ISSUE TITLE
[FR] - Speed up cardano-node verification of *.chunk (and associated files)

### ISSUE THREAD

**Issue by chuacw** [input-output-hk/cardano-node#2764]
*External*  

**Describe the feature you'd like**
When starting up cardano-node, if it has been run before, it appears to verify the on-disk blockchain files, reading through all *.chunk files.  I would like cardano-node to be able to speed up this process, by reading the last verified *.chunk (and associated files) instead.

**Describe alternatives you've considered**
Is it possible to speed up the verification process, such that it starts from the last verified *.chunk (and other associated files) before it shuts down the previous time?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
