### ISSUE TITLE
> You need to be in the cardano-node repository folder (it is copying to ~/.local/bin, not from - and relative path is from git repo) to execute this command

### ISSUE THREAD

**Issue by dwaynemcgordon** [input-output-hk/cardano-node#2767]
> You need to be in the cardano-node repository folder (it is copying to ~/.local/bin, not from - and relative path is from git repo) to execute this command

 Thank you for that, I started a new build out and i am getting the same error as before

![cardano-node 2021-05-29 162856](https://user-images.githubusercontent.com/85006386/120087230-0b7ae780-c09b-11eb-97ca-f9f35d21dfc6.png)

_Originally posted by @dwaynemcgordon in https://github.com/input-output-hk/cardano-node/issues/2761#issuecomment-850913554_

**Comment by 34r7h** [comment]
this should be fixed

**Comment by 34r7h** [comment]
broke either way..

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
