### ISSUE TITLE
[FR] - start syncing the blockchain from both ends so we can create/sign txs befgore waiting 3 days for mainnet sync

### ISSUE THREAD

**Issue by 34r7h** [input-output-hk/cardano-node#2788]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by rdlrt** [comment]
You dont need a node in sync to create/sign/submit tx, they can be done offline as long as parameters are known. Please put some efforts into creating issues with descriptions and which doco you're following (and against which branch) , multiple one liner headings  with no content in issues is not really helpful to allow others help you

**Comment by 34r7h** [comment]
how is it possible to get a wallet's addressees with balances before the node syncs? i completely understand your point about more effort for issues but also don't care after the experiences dealing with this repo's senseless amalgamation of incorrect instructions and the obvious lack of caring about developer expereience. tit for tat imo
