### ISSUE TITLE
[FR] - Include Type information with Prometheus metrics

### ISSUE THREAD

**Issue by bruceharrison1984** [input-output-hk/cardano-node#2790]
**Internal/External**
*External* 

**Area**
*Monitoring*

**Describe the feature you'd like**
I'd like to see the Prometheus metrics include a full exposition format for easy porting to other aggregation platforms (DataDog, Cloudwatch, etc). The current format omits type information from the /metrics endpoint, rendering some integrations impossible.

**Describe alternatives you've considered**
If your integration doesn't support reading Prometheus metrics without TYPE information, you are cannot use that integration.

**Additional context / screenshots**
The full exposition format is as follows:
```sh
# HELP http_requests_total The total number of HTTP requests.
# TYPE http_requests_total counter
http_requests_total{method="post",code="200"} 1027 1395066363000
http_requests_total{method="post",code="400"}    3 1395066363000
```
https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-example

**Comment by evmin** [comment]
+1

Without proper typing Open Telemetry Collector fails as:

```
{2021-08-29 07:24:12.171364116 +0000 UTC m=+190.348808759, Level:info, Caller:go.opentelemetry.io/collector@v0.29.1-0.20210630003519-14d917479ef3/receiver/prometheusreceiver/internal/metrics_adjuster.go:302, Message:Adjust - skipping unexpected point, Stack:}
```

**Comment by renesecur** [comment]
We would also love to have this

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
