### ISSUE TITLE
[FR] - My cardnode is 1.21.1, but It doesn't sync afer 16585145

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-node#2793]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by rdlrt** [comment]
It is not supposed to - as network has been through forks since that the previous codebase will not be aware of, please upgrade to the latest release

**Comment by malingzhao** [comment]
Thankyou so rosetta and the graphql  what is the best way to get the rest blockInfo

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
