### ISSUE TITLE
[DOCS] - Documentation unclear in creating transaction

### ISSUE THREAD

**Issue by justin-vanwinkle** [input-output-hk/cardano-node#2794]
**External**

**Summary**
Documentation is unclear when creating a transaction. In the line `--tx-out $(cat payment2.addr)+0`, it is unclear where `payment2.addr` came from and what address the file contains.

Here's the page/section: https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/simple_transaction.html#draft-the-transaction

Here's the full block:

```
cardano-cli transaction build-raw \
--tx-in 4e3a6e7fdcb0d0efa17bf79c13aed2b4cb9baf37fb1aa2e39553d5bd720c5c99#4 \
--tx-out $(cat payment2.addr)+0 \
--tx-out $(cat payment.addr)+0 \
--invalid-hereafter 0 \
--fee 0 \
--out-file tx.draft
```

**Update**
This is explained further down on the page. It's just very unclear at the time that you reach the section referenced above.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
