### ISSUE TITLE
[FR] - Allow chained transactions within a block

### ISSUE THREAD

**Issue by oskin1** [input-output-hk/cardano-node#2820]
**Internal/External**
*External*

**Area**
*Transactions processing*

**Describe the feature you'd like**
Node should support processing of transactions referencing outputs of previous transactions within a single block.  

**Additional context / screenshots**
This feature is required for DeFi dApps building on top of Cardano to achieve good performance. As far as I know this feature doesn't require any changes in the protocol. 

Same feature in Ergo Reference Client: https://github.com/ergoplatform/ergo/issues/279

**Comment by timsahabutdinov** [comment]
Go go go 💯

**Comment by Voyager90** [comment]
🔥👍

**Comment by BullwinkleDev** [comment]
Cool!

**Comment by hamdERGler** [comment]
please, if this addresses the transaction volume challenge, we're golden.

**Comment by matiwinnetou** [comment]
I would put +1 but only if this is not at the expense of users and security. There have been some voices that this feature brings back issues known in Ethereum.

**Comment by oskin1** [comment]
> I would put +1 but only if this is not at the expense of users and security. There have been some voices that this feature brings back issues known in Ethereum.

Can you elaborate on potential security threats?

**Comment by matiwinnetou** [comment]
@oskin1 perhaps security is a wrong word actually, we should avoid MEV and front - running transactions. I think Cardano takes conservative approach, feature is ready when it is ready, they are not rushed.

You probably know way more about this feature than I do.

**Comment by oskin1** [comment]
> @oskin1 perhaps security is a wrong word actually, we should avoid MEV and front - running transactions. I think Cardano takes conservative approach, feature is ready when it is ready, they are not rushed.
> 
> You probably know way more about this feature than I do.

I guess MEV and front-running are not really relevant to this feature. Also, I believe in UTXO, MEV is not such a critical issue (as it is in Ethereum) because of determinism of the model. And with the introduction of the proposed feature we don't lose this determinism.

**Comment by AndrewWestberg** [comment]
Transactions can already be chained within a block. Unless I'm misunderstanding and the requirement is to guarantee that a chain of transactions will all be processed in the same block. That's the part that isn't currently guaranteed.
