### ISSUE TITLE
[BUG] - Cardano Node becomes "stuck" during synchronisation without outbound connectivity

### ISSUE THREAD

**Issue by NASEC-Alex** [input-output-hk/cardano-node#2835]
**External**

**Area**
*Other*   Cardano node Block synchronisation

**Summary**
A clear and specific description of what the bug is.
Cardano Nodes will become "stuck" and their chain will fail to proceed to the next block after entering this state. The cause appears to be a lack of outbound DNS which is not specified as a requirement within the documentation (unless I have missed it). 

**Steps to reproduce**
1. Create a Cardano node [1] without outbound connectivity (default route) available.
2. Add another local Cardano node [2] to its topology file through which it will update using a private network address. Cardano Node [2] has outbound connectivity allowing it to synchronise its chain publicly.
3. Provide no NAT for Cardano node [1]
4. The Cardano node [1] will become "stuck" when syncing to certain blocks in the block chain. Restarting the node will resolve the issue ?sometimes?

Below is an example of a mainnet block which such a node became "stuck" on.
{
    "epoch": 270,
    "hash": "59b1aa123731e727a028a1feedd68ff7193fbe78c6095c02c4b073185941e796",
    "slot": 31657148,
    "block": 5827657,
    "era": "Mary"
}

**Expected behavior**
The node should be able to receive blocks from it's local Relay and should not require DNS to function.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version cardano-node 1.27.0 - linux-x86_64 - ghc-8.10 git rev 8fe46140a52810b6ca456be01d652ca08fe730bf
- CLI version  cardano-cli 1.27.0 - linux-x86_64 - ghc-8.10 git rev 8fe46140a52810b6ca456be01d652ca08fe730bf

**Screenshots and attachments**
- Just leave the node running for a time, after it becomes stuck reproduce by just running "cardano-cli query tip --mainnet" multiple times.

**Additional context**
The typical application / reason for this configuration is a Cardano Node runs as a producer with a default DENY policy on its output chain with an ACCEPT to only the Cardano Relay and addresses for management.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
