### ISSUE TITLE
[BUG] - Link to build instructions broken

### ISSUE THREAD

**Issue by brunjlar** [input-output-hk/cardano-node#2845]
**Internal/External**
*Internal*

**Area**.
*Other*

**Summary**
The link to build instructions for the node in the main README is broken.

**Steps to reproduce**
1. Click on "here" in "Documentation for building the node can be found here."
2. Encounter broken link.

**Expected behavior**
The link should lead to build instructions.

**System info (please complete the following information):**
- Arch Linux
- Git revision f3f5fe1dde64e483c382a5eccce591fee6627ad5

**Comment by Jimbo4350** [comment]
Thanks, this has been resolved.
