### ISSUE TITLE
[FR] - Add help and type information to metrics export

### ISSUE THREAD

**Issue by sunshinekitty** [input-output-hk/cardano-node#2846]
**External**

**Area**
*Other*

**Describe the feature you'd like**
Please add HELP and TYPE information to exported metrics.

Eg..
```
$ curl -s localhost:12798/metrics | grep "cardano_node_metrics_epoch"
cardano_node_metrics_epoch_int 268
```

Should instead be
```
$ curl -s localhost:12798/metrics | grep "cardano_node_metrics_epoch"
# HELP cardano_node_metrics_epoch_int Whichever help text explaining metric.
# TYPE cardano_node_metrics_epoch_int gauge
cardano_node_metrics_epoch_int 268
```

**Describe alternatives you've considered**
n/a

**Additional context / screenshots**
Depending on your tsdb this type information is helpful in storing metrics properly.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
