### ISSUE TITLE
[FR] - Improve cli build-raw validation when provided options are in incorrect order

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#2859]
**Internal/External**
*Internal*

**Area**
*Other* (Plutus Script Validation - Alonzo)

**Describe the feature you'd like**
input-output-hk/Alonzo-testnet#5 - This was raised by an Alonzo-Blue SPO and has caught a few people out, including myself. There is currently no validation for when an option that is applied to a previous option is provided without that previous option. For example, using `--tx-out-datum-hash` without a preceding `--tx-out`.

**Describe alternatives you've considered**
https://github.com/input-output-hk/Alonzo-testnet/issues/5#issuecomment-864112984 - A suggestion was made here to investigate whether [optparse-applicative](https://hackage.haskell.org/package/optparse-applicative) can be configured to help guide the user if they provide an option at the incorrect position. Failing that we would need to implement our own validation to improve the UX here.

**Additional context / screenshots**
N/A

**Comment by newhoggy** [comment]
Trying to think outside the box.

I was wondering if it would help if there was a flag like `--dry-run` that if supplied would cause the CLI to not do anything, but print out what it would do including display structure of the transaction it would put into the transaction file had it not been a dry run?

**Comment by newhoggy** [comment]
It's not clear if the library we use `optparse-applicative` can be coaxed into doing this sort of validation.

I have raised a ticket asking about it https://github.com/pcapriotti/optparse-applicative/issues/432

If it is not possible, we may need to look at other options.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
