### ISSUE TITLE
[FR] - cardano-cli key command to create vkey from string

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2868]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**

*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**

Currently convert-cardano-address-key only supports converting signing keys. This would add ability to convert verification keys (both with and without chain code)

`cardano-cli key convert-cardano-address-key --shelley-payment-key --verification-key-file payment.xpub --out-file payment.vkey-ext

While this change is being done, it always would be nice to add `--signing-key` and `--verification-key` params to not have to write the key to a file first.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
