### ISSUE TITLE
[BUG] - transaction calc-min-value calculates bytes and thus fees incorrectly for double-byte character sets.

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#2877]
**Internal/External**
*External*

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Summary**
The fees aren't enough to cover the actual number of bytes. My guess is that we're using a "string length" instead of actual byte length to calculate the fees.

![Screenshot from 2021-06-29 03-35-18](https://user-images.githubusercontent.com/245918/123733664-6c106680-d88b-11eb-8bc3-d3dfb740c890.png)

**Steps to reproduce**
1. run calc-min-value with a token name that uses double-byte characters like АнтиКойн
2. Notice that the fees are lower than they should be

**Expected behavior**
I expect the fees to be calculated based on the bytes of the token name, not the number of characters in the token name.

**System info (please complete the following information):**
- OS Name:Ubuntu
- OS Version 20.04
- Node version 1.27.0
- CLI version  1.27.0

**Additional context**
```
$ cardano-cli transaction calculate-min-value --protocol-params-file /tmp/protocol-parameters.json --multi-asset '100 34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518.АнтиКойн' 
Lovelace 1481480

$ cardano-cli transaction calculate-min-value --protocol-params-file /tmp/protocol-parameters.json --multi-asset '100 34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518.123456789'
Lovelace 1481480

$ echo АнтиКойн | xxd -p
d090d0bdd182d0b8d09ad0bed0b9d0bd0a

$ echo 123456789 | xxd -p
3132333435363738390a
```

**Comment by dcoutts** [comment]
This is actually correct.

* "123456789" is 9 characters and 9 bytes.
* "АнтиКойн" is 8 characters and 16 bytes.

The min value formula rounds the bytes up to the nearest 8 (corresponding to a 64bit word in memory). So both of these examples round up to 16 bytes. That is why they give the same result.
