### ISSUE TITLE
[BUG] - `query tip` doesn't work without `TestEnableDevelopmentNetworkProtocols`

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#2878]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
On current master, `cardano-cli query tip` fails, e.g. on Mary
```
$ cardano-cli query tip  --testnet-magic 42

cardano-cli: QueryEncoderUnsupportedQuery Query GetSystemStart TopLevelQueryDisabled
```
It works when there's
```
"TestEnableDevelopmentNetworkProtocols": true
```
in the node config files.

**System info (please complete the following information):**
- OS Name: Fedora 34
- Node version & CLI version
```
$ cardano-node --version
cardano-node 1.27.0 - linux-x86_64 - ghc-8.10
git rev 19962306ddb299f75ac7f1ef77c2f6722bdb5646
```

**Comment by newhoggy** [comment]
Fixed.
