### ISSUE TITLE
Make `cardano-node` slot length derived from genesis

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#288]
Subtask of #255

Slot length is currently hard-coded in `ourobboros-network` to 20s [1], which is counterproductive for short CI runs, that would benefit from 1s slots.

--
1. https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L188

**Comment by Jimbo4350** [comment]
@deepfire  I'm currently taking care of this in branch `jordan/replace-cardano-configuration`

**Comment by dcoutts** [comment]
The slot length is already specified in the genesis file. It should be taken from there, not hard coded. But it should not be a config file or CLI item. It's critical for consensus that everyone agree on the slot length, so it is right that it comes from the genesis.

**Comment by deepfire** [comment]
Issue moved to [input-output-hk/ouroboros-network #1344](https://github.com/input-output-hk/ouroboros-network/issues/1344) via [**ZenHub**](https://www.zenhub.com/)
