### ISSUE TITLE
[BUG] - Slots Missed - During ChainSyncClientEvents a block producer can fail to check for slot leadership

### ISSUE THREAD

**Issue by Straightpool** [input-output-hk/cardano-node#2890]
**Internal/External**
*External*   otherwise.

**Area**
*Other*  Block production

**Summary**
During ChainSyncClientEvents a block producer can fail to check for slot leaderships and thus miss blocks.

**Steps to reproduce**
1. Mint blocks during a time of low I/O usage
2. Trace cardano_node_metrics_slotsMissedNum_int metric and notice spike correlating with an actually missed block (this can take a while, as it is very rare from my observations, once in about 1500 blocks)
3. Check all other pool metrics around that time, notice maybe a minor CPU spike, everything else is on point
4. Look at block producer log, take down times between TraceLeaderShip Events, notice a gap due to the processing of ChainSyncClientEvents

Notice TraceNodeNotLeader at 33489227:

{"thread":"88","loc":null,"data":{"val":{"kind":"TraceNodeNotLeader","slot":**33489227**},"credentials":"Cardano"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.Forge"],"at":"2021-06-30T12:18:38.00Z"}

Notice TraceStartLeadershipCheck is starting for the next slot 33489228, take down the time:

{"thread":"88","loc":null,"data":{"kind":"TraceStartLeadershipCheck","chainDensity":4.9384695e-2,"slot":**33489228**,"delegMapSize":668306,"utxoSize":2747492,"credentials":"Cardano"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.LeadershipCheck"],"at":"**2021-06-30T12:18:39.00Z**"}

Now we have the block production disrupting ChainSyncClientEvents on the block producer, notice the execution end times, start time is not logged apparently:

{"thread":"491745","loc":null,"data":{"kind":"**ChainSyncClientEvent**.TraceDownloadedHeader","peer":"ConnectionId {localAddress = <bp ip>:43639, remoteAddress = 128.199.77.60:3611}","block":{"kind":"BlockPoint","headerHash":"107146778a1a5ea8042e7eb57b9ed54c0af998d9e15a40e85f13aa6e9502c516","slot":33489231}},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.ChainSyncClient"],"at":"2021-06-30T**12:18:44.87Z**"}
{"thread":"491682","loc":null,"data":{"kind":"ChainSyncClientEvent.TraceDownloadedHeader","peer":"ConnectionId {localAddress = <bp ip>:44151, remoteAddress = 116.203.114.229:7421}","block":{"kind":"BlockPoint","headerHash":"107146778a1a5ea8042e7eb57b9ed54c0af998d9e15a40e85f13aa6e9502c516","slot":33489231}},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.ChainSyncClient"],"at":"2021-06-30T12:18:44.88Z"}
{"thread":"90","loc":null,"data":{"peers":[{"kind":"**FetchDecision declined**","declined":"**FetchDeclineChainNotPlausible**","peer":"ConnectionId {localAddress = <bp ip>:43639, remoteAddress = 128.199.77.60:3611}"},{"length":"1","kind":"FetchDecision results","peer":"ConnectionId {localAddress = <bp ip>:44151, remoteAddress = 116.203.114.229:7421}"}],"kind":"PeersFetch"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.BlockFetchDecision"],"at":"**2021-06-30T12:18:44.88Z**"}
{"thread":"90","loc":null,"data":{"kind":"AddedFetchRequest","peer":"ConnectionId {localAddress = <bp ip>:44151, remoteAddress = 116.203.114.229:7421}"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.BlockFetchClient"],"at":"2021-06-30T12:18:44.88Z"}
{"thread":"491680","loc":null,"data":{"kind":"AcknowledgedFetchRequest","peer":"ConnectionId {localAddress = <bp ip>:44151, remoteAddress = 116.203.114.229:7421}"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.BlockFetchClient"],"at":"2021-06-30T12:18:44.88Z"}
{"thread":"90","loc":null,"data":{"peers":[{"kind":"**FetchDecision declined**","declined":"**FetchDeclineInFlightThisPeer**","peer":"ConnectionId {localAddress = <bp ip>:44151, remoteAddress = 116.203.114.229:7421}"},{"length":"1","kind":"FetchDecision results","peer":"ConnectionId {localAddress = <bp ip>:43639, remoteAddress = 128.199.77.60:3611}"}],"kind":"PeersFetch"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.BlockFetchDecision"],"at":"2021-06-30T12:18:44.89Z"}
{"thread":"90","loc":null,"data":{"kind":"AddedFetchRequest","peer":"ConnectionId {localAddress = <bp ip>:43639, remoteAddress = 128.199.77.60:3611}"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.BlockFetchClient"],"at":"2021-06-30T12:18:44.89Z"}
{"thread":"491747","loc":null,"data":{"kind":"AcknowledgedFetchRequest","peer":"ConnectionId {localAddress = <bp ip>:43639, remoteAddress = 128.199.77.60:3611}"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.BlockFetchClient"],"at":"**2021-06-30T12:18:44.89Z**"}

**Notice the end of the TraceNodeNotLeader for 33489228 took about 5 seconds !**

{"thread":"88","loc":null,"data":{"val":{"kind":"TraceNodeNotLeader","slot":**33489228**},"credentials":"Cardano"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.Forge"],"at":"**2021-06-30T12:18:44.89Z**"}

Notice the next LeadershipCheck continuing at 33489233 now again in sync, effectively missing the Leadership check for the slots 33489228 in time, 33489229, 33489230, 33489231, 33489232

STR8 pool had an assigned leadership slot at height **33489230**, epoch 275 slot 52430 at 2021-06-30 12:18:41 UTC which was **missed**, due to this bug.

{"thread":"88","loc":null,"data":{"kind":"TraceStartLeadershipCheck","chainDensity":4.9384695e-2,"slot":**33489233**,"delegMapSize":668306,"utxoSize":2747492,"credentials":"Cardano"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.LeadershipCheck"],"at":"**2021-06-30T12:18:44.89Z**"}
{"thread":"88","loc":null,"data":{"val":{"kind":"TraceNodeNotLeader","slot":**33489233**},"credentials":"Cardano"},"sev":"Info","env":"1.27.0:8fe46","msg":"","app":[],"host":"ub20cn","pid":"8129","ns":["cardano.node.Forge"],"at":"**2021-06-30T12:18:44.89Z**"}

**Expected behavior**
A block producer should not miss LeadershipChecks due to blocking ChainSyncClientEvents when the block producer is on tip. The LeadershipCheck thread and block production threads should have higher priority than ChainSyncClientEvent threads.

**System info:**
- OS Name: Ubunto
- OS Version:  20.04.1 LTS
- Node version: 
```
cardano-node 1.27.0 - linux-x86_64 - ghc-8.10
git rev 8fe46140a52810b6ca456be01d652ca08fe730bf
```
- CLI version:
```
cardano-cli 1.27.0 - linux-x86_64 - ghc-8.10
git rev 8fe46140a52810b6ca456be01d652ca08fe730bf
```

**Screenshots and attachments**
Note: Grafana times are in CEST, so 2021-06-30 12:18:41 UTC is here 2021-06-30 14:18:41 CEST, server log is in UTC.

Slotsmissed metric in Grafana:
![image](https://user-images.githubusercontent.com/42584250/124174762-08fe1a00-daad-11eb-94df-dc4868c6a9a1.png)

50% CPU spike most likely due to the ChainSyncEvents:
![image](https://user-images.githubusercontent.com/42584250/124174868-27fcac00-daad-11eb-9cfd-eb85d71a13ee.png)

CPU monitoring on node_exporter normal:
![image](https://user-images.githubusercontent.com/42584250/124174914-35199b00-daad-11eb-88ae-597816d3357f.png)

Nothing out of the ordinary on the block height tracking:
![image](https://user-images.githubusercontent.com/42584250/124175511-fcc68c80-daad-11eb-961b-e2fc8281a42a.png)

Nothing out of the ordinary on the peer tracking:
![image](https://user-images.githubusercontent.com/42584250/124175586-123bb680-daae-11eb-8874-a75285b54e18.png)

Nothing out of the ordinary on the memory tracking:
![image](https://user-images.githubusercontent.com/42584250/124175661-2b446780-daae-11eb-89b4-4bbae93a48d6.png)

Time drift is fine:
![image](https://user-images.githubusercontent.com/42584250/124176023-a148ce80-daae-11eb-98b6-5c8792b9478f.png)

The BP has no recollection of a missed block:
![image](https://user-images.githubusercontent.com/42584250/124174962-45317a80-daad-11eb-93c0-d97aeafb9235.png)

There is not one line of entry in the log on the missed slot
![image](https://user-images.githubusercontent.com/42584250/124175011-54b0c380-daad-11eb-97ab-af55bd028131.png)

This is not related to high IO usage as in https://github.com/input-output-hk/cardano-node/issues/2731
IO usage is minimal:

![image](https://user-images.githubusercontent.com/42584250/124185315-1c17e680-dabb-11eb-993f-f1decf2dfe29.png)

![image](https://user-images.githubusercontent.com/42584250/124185361-2afe9900-dabb-11eb-8784-b61aadbabd8e.png)

![image](https://user-images.githubusercontent.com/42584250/124185403-3a7de200-dabb-11eb-9429-50f38a354500.png)

Network traffic is low as well
![image](https://user-images.githubusercontent.com/42584250/124185911-dad40680-dabb-11eb-9e3b-445d10369079.png)

**Additional context**
Maybe related issues: https://github.com/input-output-hk/cardano-node/issues/2573 and https://github.com/input-output-hk/cardano-node/issues/2526

**Comment by cloudstake** [comment]
I have noticed this as well.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
