### ISSUE TITLE
[FR] - Transaction broadcasting via API

### ISSUE THREAD

**Issue by alexqrid** [input-output-hk/cardano-node#2901]
**External**
**Area**
*Transactions*

**Describe the feature you'd like**
In many other cryptos it's possible to generate your transaction on a local machine and submit it to the network via third party node operator. However I could find neither a service allowing to do this nor the node API to do it. So it will be great to broadcast transaction via the API instead of using cli tools

**Comment by rdlrt** [comment]
You can submit transactions remotely (see [submit-api](https://github.com/input-output-hk/cardano-node/blob/master/cardano-submit-api/testing-tx-submit.md) for reference), there is also [serialisation-lib](https://github.com/Emurgo/cardano-serialization-lib/tree/master/doc/getting-started) available. As far as services go, you can use [BlockFrost](https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1tx~1submit/post) or [Dandelion](https://gimbalabs.com/dandelionapis/submit-api)
