### ISSUE TITLE
[FR] - Allow rotation of stake pool keys

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2903]
*External*   otherwise.

**Area**
*Staking Pool*   

**Describe the feature you'd like**

Now that we can setup a stake pool secured entirely by a HW wallet, it would be nice to have a migration path for existing pools and perhaps also be able to migrate from one HW device to another (with a different private key)

```
cardano-hw-cli node key-gen \
--path 1853H/1815H/0H/0H \
--hw-signing-file cold.hwsfile \
--cold-verification-key-file cold.vkey \
--operational-certificate-issue-counter-file cold.counter
```

https://github.com/vacuumlabs/cardano-hw-cli

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
