### ISSUE TITLE
[BUG] - Support for RTS options in docker run limited to -e NETWORK

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2908]
*External* 

**Area**
*Docker*

**Summary**

A docker container started with NETWORK ...

```
docker run --rm -it \
  -e NETWORK=mainnet \
  inputoutput/cardano-node:dev
```

... gets default RTS options appended to the command line. 

```
+RTS
-N2
-A16m
-qg
-qb
--disable-delayed-os-memory-return
-RTS
```

This isn't the case when started without -e NETWORK.

**Additional context**

I would take a look at this.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
