### ISSUE TITLE
[BUG] - pricing-related update proposals don't work with fractional pricing

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#2920]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The protocol parameters changed with introduction of fractional pricing and now look like
```
    "executionUnitPrices": {
        "priceSteps": {
            "numerator": 11,
            "denominator": 10
        },
        "priceMemory": {
            "numerator": 11,
            "denominator": 10
        }
    }
```

It seems the `create-update-proposal` command haven't reflected the change:
```
$ cardano-cli governance create-update-proposal
...
  --price-execution-steps LOVELACE
                           Step price of execution units for script languages
                           that use them (from Alonzo era).
  --price-execution-memory LOVELACE
                           Memory price of execution units for script languages
                           that use them (from Alonzo era).
```
When passing decimal value as a parameter, the update proposal can be created and submitted, however it has no effect. When trying to pass tuple representing the numerator and denominator, the `create-update-proposal` command fails:
```
cardano-cli governance create-update-proposal  --price-execution-steps (120,100) ...`: option --price-execution-steps: Failed reading: takeWhile1
...
```

**System info (please complete the following information):**
- OS Name: Fedora
- OS Version 34
- Node version 7cf540dafa0ca496526e0614fa3ef6262e85c70d
- CLI version 7cf540dafa0ca496526e0614fa3ef6262e85c70d

**Comment by newhoggy** [comment]
Fixed
