### ISSUE TITLE
When will Alonzo be activated on the mainnet?

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-node#2926]
I am a wallet provider, please tell me the time to upgrade, so I can update the node in time

**Comment by erikd** [comment]
Alonzo will be activated when it is ready. At least a week (probably more) before that a new version of the `node` will be released that contains support for Alonzo.

**Comment by vae520283995** [comment]
> Alonzo will be activated when it is ready. At least a week (probably more) before that a new version of the `node` will be released that contains support for Alonzo.

thanks
