### ISSUE TITLE
[BUG] - Script output not spent, node silently consumes 100 ADA collateral 

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2929]
*External*   otherwise.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**

PaymentAddr: 100 ADA
ScriptAddr: addr_test1wzpu87f5k52qvua9wn6gncg0m6hle4w86w5c4m9ryk6dxmsrw7evr (AlwaysSucceeds.plutus)

LockedByScript: 10 ADA (DatumValue=0, DatumHash=03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314) 

I try to retrieve the 10 ADA locked by the script like this ...

```
# Query Payment UTOX
cardano-cli query utxo \
  --address $PAYMENT_ADDR \
  --testnet-magic 7

TX_IN1="9ef8cd1f2ac078987895c8c0bbeb7918ca1b837436780a9d60bcbd7876f27e0d#0"
UTOX_LVC1="100000000"

# Query Script UTOX
cardano-cli query utxo \
  --address $SCRIPT_ADDR \
  --testnet-magic 7

TX_SCRIPT_IN1="8193f58c5e187843d6c7dce874803233c5dc4a0fee0c929151edf096d736d187#0"
SCRIPT_LVC1="10000000"

TO_ADDR=${PAYMENT_ADDR}

# Calculate the change to send back to PAYMENT_ADDR
FEES_LVC=5000000
SEND_LVC=$(($SCRIPT_LVC1 - $FEES_LVC))
echo "$SEND_LVC Lovelace"

# Build the transaction
cardano-cli transaction build-raw \
  --alonzo-era \
  --tx-in $TX_SCRIPT_IN1 \
  --tx-in-script-file /var/cardano/local/scripts/AlwaysSucceeds.plutus \
  --tx-in-redeemer-value 0 \
  --tx-in-datum-value 0 \
  --tx-in-execution-units "(2000000,2000000)" \
  --tx-in-collateral $TX_IN1 \
  --tx-out $TO_ADDR+$SEND_LVC \
  --fee $FEES_LVC \
  --protocol-params-file /var/cardano/local/scratch/protocol.json \
  --out-file /var/cardano/local/scratch/tx.raw

# Sign the transaction
cardano-cli transaction sign \
  --tx-body-file /var/cardano/local/scratch/tx.raw \
  --signing-key-file /var/cardano/local/keys/alonzo/$OWNER/payment.skey \
  --out-file /var/cardano/local/scratch/tx.signed

# Submit the transaction
cardano-cli transaction submit \
  --tx-file /var/cardano/local/scratch/tx.signed \
  --testnet-magic 7
```

* The network accepts the Tx
* The script value is not spent
* The 100 ADA collateral is gone
* Happens repeatedly, no error in relay/bprod log

**Comment by tdiesler** [comment]
The above may have to do with the value of fees and execution units. Is the collateral always consumed as a whole when something goes wrong i.e. is it the responsibility of the client to only offer the minimum required collateral?

**Comment by tdiesler** [comment]
How about this as a possible explanation ...

--tx-in-execution-units "(2000000,2000000)" is too small to even validate AlwaysSucceeds. The script would fail because of that and as a consequence the collateral is consumed as a whole

How do I find the appropriate value for these units?

**Comment by james-iohk** [comment]
@tdiesler. Hi Tom, is this now resolved with the reserialised script?

**Comment by tdiesler** [comment]
Yes, we can instead have a different/general issue about collateral silently removed without feedback

**Comment by tdiesler** [comment]
See https://github.com/input-output-hk/cardano-node/issues/2942
