### ISSUE TITLE
[BUG] - Collateral silently removed without feedback

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2942]
**Internal/External**
*External*   otherwise.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**

There are various reasons that lead to the silent removal of the collateral. Here are some that I came across ...

* Too few execution units in --tx-in-execution-units
* Redeemer cannot be parsed into target type
* Datum cannot be parsed into target type
* Validator failure

It'd be good to see meaningful indications in the log to why the Tx failed and the collateral got removed.

**Comment by Jimbo4350** [comment]
Yep this is a pain. This is in the pipeline of things to come but I can't give an estimate yet as to when this will be available.

**Comment by james-iohk** [comment]
Progress is being made: https://github.com/input-output-hk/cardano-ledger-specs/pull/2386

**Comment by james-iohk** [comment]
@tdiesler fyi PR https://github.com/input-output-hk/cardano-node/pull/2921 includes a change so that txs with failing scripts are rejected, rather than accepted and the collateral is consumed

**Comment by tdiesler** [comment]
Lovely, thanks

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
