### ISSUE TITLE
Function to Rebalance Inbound Connections

### ISSUE THREAD

**Issue by michaeljfazio** [input-output-hk/cardano-node#2959]
Inbound TCP connections to cardano-node are "long-lived" in nature. This produces a problematic situation for load balancing inbound peer connections.

Consider a pool that runs two relays and one block producer. Assume the initial state is such that inbound peer connections are evenly distributed amongst relays (50% to relay one, 50% to relay 2). The SPO takes down relay 2 for maintenance. All peer connections to relay 2 are dropped and promptly re-connect to relay 1 (assuming valency 1). Relay 1 now services 100% of inbound connections. Maintenance on relay 2 concludes and the node is brought back online. However, all inbound peer connections remain connected to relay 1 (they are persistent and long-lived).

How might one solve this issue?

1. Use a forward load-balancer that supports TCP rebalancing by injecting RST packets to force clients to rebalance.
2. Run a script to forcefully disconnect peers randomly (may not be possible or practical for a number of reasons depending on the pool setup).
3. Run a sufficiently large enough pool of relays and periodically reset one member of the pool (doesn't offer a solution for pools that only run 2 relays and also won't result in ideal load balancing characteristics). It should be noted that this is indeed what many larger pools seem to do.
4. Introduce a function to cardano-node that periodically selects one or more connections based on some criteria to be "cycled". This might mean simply forcing the closure on the nodes socket, or better still introducing a protocol-level instruction that allows the server to instruct the client to perform a graceful cycling of its connection.

I believe that there is a good case for option four. Providing it is implemented in such a way that is not easily mis-configured so as to create too much connection churn.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
