### ISSUE TITLE
[FR] - Can a docker compose be added for submit-api in the Node repo

### ISSUE THREAD

**Issue by LaurenceIO** [input-output-hk/cardano-node#2964]
Internal

**Area**
*Other*   submit-api

**Describe the feature you'd like**
Can a docker compose file be added to the submit-api component that is now in the Node repo please?

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-node/pull/3128

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
