### ISSUE TITLE
[BUG] - failed to submit transaction: transaction

### ISSUE THREAD

**Issue by benjamintshi** [input-output-hk/cardano-node#2965]
i used cardano-submit-tx with this raw hex get error, but i used carnano-cli this raw hex is successed.

code:

const CardanoWasm = require("@emurgo/cardano-serialization-lib-nodejs");
const base58 = require("./crypto/base58");
const txBuilder = CardanoWasm.TransactionBuilder.new(
  CardanoWasm.LinearFee.new(
    CardanoWasm.BigNum.from_str("44"), // txFeePerByte
    CardanoWasm.BigNum.from_str("155381") // txFeeFixed
  ),
  CardanoWasm.BigNum.from_str("1000000"), // minUTxOValue
  CardanoWasm.BigNum.from_str("500000000"), // stakePoolDeposit
  CardanoWasm.BigNum.from_str("2000000") // stakeAddressDeposit
);
const privatekey = CardanoWasm.PrivateKey.from_normal_bytes(
  Uint8Array.from(
    Buffer.from(
      "71edec1e10ee0bd908efb98a4f5f710af598938d0c8c0ca1a332fe949ec8387b",
      "hex"
    )
  )
);
const outputAddress = CardanoWasm.Address.from_bech32(
  "addr_test1vq396n3etrqqffpmfarkphj4sswhspt6lnr7un6chsm9fkgwh6j8c"
);
const changeAddress = CardanoWasm.Address.from_bech32(
  "addr_test1vzkduuu652559dnqvlekdhe3vj96jtglg4vpmk3033p8lcgj4m93c"
);
const txid = CardanoWasm.TransactionHash.from_bytes(
  Uint8Array.from(
    Buffer.from(
      "feebd5620bda7bd35a976fdf33d7685be0b6fd01870b678603c5f14d65f0f4f9",
      "hex"
    )
  )
);
const feeInput = txBuilder.fee_for_input(
  outputAddress,
  CardanoWasm.TransactionInput.new(txid, 0),
  CardanoWasm.Value.new(CardanoWasm.BigNum.from_str("1000000000"))
);
const feeOutput = txBuilder.fee_for_output(
  CardanoWasm.TransactionOutput.new(
    outputAddress,
    CardanoWasm.Value.new(CardanoWasm.BigNum.from_str("999835819"))
  )
);

txBuilder.add_key_input(
  privatekey.to_public().hash(),
  CardanoWasm.TransactionInput.new(txid, 0),
  CardanoWasm.Value.new(CardanoWasm.BigNum.from_str("1000000000"))
);
txBuilder.add_output(
  CardanoWasm.TransactionOutput.new(
    outputAddress,
    CardanoWasm.Value.new(CardanoWasm.BigNum.from_str("999835819"))
  )
);
txBuilder.set_ttl(32917509);

txBuilder.add_change_if_needed(changeAddress);

try {
  const txBody = txBuilder.build();
  const txBodyHash = CardanoWasm.hash_transaction(txBody);
  const vKeyNesses = CardanoWasm.Vkeywitnesses.new();
  vKeyNesses.add(CardanoWasm.make_vkey_witness(txBodyHash, privatekey));
  const witnesses = CardanoWasm.TransactionWitnessSet.new();
  witnesses.set_vkeys(vKeyNesses);
  const txRaw = CardanoWasm.Transaction.new(txBody, witnesses, undefined);
  console.log("txRaw:", Buffer.from(txRaw.to_bytes()).toString("hex"));
} catch (error) {
  console.log(error);
}

 curl --header "Content-Type: application/cbor" -X POST http://localhost:8090/api/submit/tx --data-binary "83a40081825820feebd5620bda7bd35a976fdf33d7685be0b6fd01870b678603c5f14d65f0f4f900018182581d60225d4e3958c004a43b4f4760de55841d78057afcc7ee4f58bc3654d91a3b9848ab021a00028155031a01f64805a1008182582071beb9469381fe6df7aa97abd4c87e9b8d5391a3e4ea3c76cd36d8fccffa36a45840e4711e2c0867e83d6a0b5faaa096f16204903a0ed6f9142d4e70320260438e6ec28c8370f33f4e9ebc383e03535b7f4daae1564efbe738dd5591953595c14f01f6"

result:

txSubmitPost: failed to submit transaction: transaction read error RawCborDecodeError [DecoderErrorDeserialiseFailure "Byron Tx" (DeserialiseFailure 0 "expected list len"),DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 0 "expected list len or indef"),DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 0 "expected list len or indef"),DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 0 "expected list len or indef")]

could you tell me how to fix this pro.

**Comment by benjamintshi** [comment]
curl -X POST --header "Content-Type:application/cbor" --data-binary @tx.signed.cbor http://localhost:8090/api/submit/tx

**Comment by benjamintshi** [comment]
txSubmitPost: successfully submitted transaction 5c9c1d79f47bc46b

**Comment by benjamintshi** [comment]
how to use this in postman.

**Comment by fei-z** [comment]
> curl -X POST --header "Content-Type:application/cbor" --data-binary @tx.signed.cbor http://localhost:8090/api/submit/tx

How much is your WeChat or email address, I need to ask you some questions

**Comment by walidzohair** [comment]
yes updated the path


---------------------------
Walid Mohammed
00201119666010

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
