### ISSUE TITLE
[BUG] - 72 minute CPU spike cycle: reason, and way to spread it out?

### ISSUE THREAD

**Issue by rphair** [input-output-hk/cardano-node#2970]
**Internal/External** - *External*
**Area** - *Other*

**Summary**

I assume this performance anomaly is well known and perhaps even by design.  Therefore this is not a "bug" report but a "help" request asking:

1. what is the cause of a 72-minute cycle of "spiking" CPU use we & others have seen on servers running `cardano-node` on which real memory might be considered scarce;
2. whether any configuration or compilation settings can be changed in `cardano-node` to spread this "spike" of kernel CPU (apparently from virtual memory processing) out over a longer period, instead of overwhelming the CPU for 1 or 2 minutes out of every 72 minutes.

**Steps to reproduce**

Our BP and both relays have almost entirely default configurations (we have only increased `MaxConcurrencyDeadline` and turned off `TraceMempool`) on unremarkable VPS hosting, each with dual CPUs and 4 GB RAM.  These have always had spikes in CPU load every 72 minutes, which for a peak minute or so of each 72 minute cycle delays the responsiveness of the affected node enough to show connection timeout errors in the `cardano-node` log files on our other stake pool nodes.

The period of CPU spiking never deviates from exactly 72 minutes, although the problem does not appear in the few hours after rebooting while the amount of RAM + the amount of swap used on the system approaches a total of 8 GB... after which the 72 minute spike cycle begins:

![Screenshot from 2021-07-26 23-34-02](https://user-images.githubusercontent.com/2572798/127039921-932ef683-308b-4c9b-8ea8-8717bc5f0b2a.png)

**Expected behaviour** and attempted workarounds

An integration of the curves above would show we're using, in total, at most 5% of the CPU.  From this point of view the servers are UNDERutilitised and this is not a capacity deficiency but rather an efficiency problem that we hope is correctable.

Based on looking through Ubuntu, Linux kernel, UNIX VM, and our cloud hosting provider's documentation, I cannot find anything with a period of 72 minutes so have to assume this period is established by `cardano-node` at least in our operating environment.

Rebooting the server reduces the amount of `cardano-node` pages that are apparently also being kept in swap space.  In trying to find SPO empirical observations & solutions to the problem I posted this, with the only response suggesting it was an inefficient use of swap space which needed to be cleaned up every so often: https://forum.cardano.org/t/pool-nodes-spike-cpu-every-72-minutes-normal-common-correctable/67230

In accordance with this parameter set by the IOHK Nix CI environment we ALSO tried setting `vm.swappiness` to `0` to eliminate that redundancy, which had very little effect: https://github.com/input-output-hk/ci-ops/blob/master/modules/common.nix

**Additional context**

As it says in our help request part (2), we would like to wait for a developer response before we "throw money at the problem" by migrating to server configurations with either double or quadruple the amount of RAM.  In fact, without an answer to part (1), we'd have no assurance this problem would not occur on `cardano-node` servers of any RAM size.

Therefore I would like to please hear some tentative answers to (1) before simply being told that our stake pool node RAM allocation is lower than others, or lower than any particular recommendation.  We are expecting to increase the capacity of our servers regardless, but we would prefer to go about this as engineers would.

**System info**
```
Ubuntu 20.04 - 2 vCPU - 4GB RAM (host: DigitalOcean)
cardano-node 1.27.0 - linux-x86_64 - ghc-8.10 - git rev 8fe46140a52810b6ca456be01d652ca08fe730bf
```

**Comment by erikd** [comment]
> Ubuntu 20.04 - 2 vCPU - 4GB RAM (host: DigitalOcean)

Pretty sure the system requirements suggest a minimum of 8GB RAM.

https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md

**Comment by rphair** [comment]
That last comment is of the kind we explicitly said in our OP that we are **not** looking for.

**Comment by rphair** [comment]
I would like to add that when a node in this "spike" period receives `SIGINT` it does not shut down cleanly (i.e. with a ledger than can be read almost immediately after the node restarts).  Therefore this is not only a resource allocation issue, but also a devops issue.

**Comment by rphair** [comment]
Now can someone please, at least generally for now, answer the question about the node is doing every 72 minutes?

**Comment by rphair** [comment]
Though we haven't tested anything on a 4GB RAM environment in a while, the last node version `1.29.0` has a less dramatic CPU spike at the 72 minute interval, as well as (because of?) a higher steady state CPU use.  This leads to a much more workable configuration for us **but** we still need to find out the reason for the 72 minute cycle as before.

**Comment by karknu** [comment]
The CPU spike at 72 minute interval comes from the default ledger snapshot interval (`DefaultSnapshotInterval`) . It is configurable with `SnapshotInterval` in seconds.

**Comment by rphair** [comment]
Thank you @karknu!
