### ISSUE TITLE
[BUG] - UTXO error when hard forking between the era's during a Byron to Alonzo private network build

### ISSUE THREAD

**Issue by stackBlock** [input-output-hk/cardano-node#2971]
External
Other:   private testnet scripts

Summary:
I was using the scripts in 'byron-to-alonzo' in order to build a private network and when i tried to run 'update-3.sh' i was getting this error:

 `Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraShelley (ApplyTxError [UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Coin 10018000000) (Coin 10000000000)))])`

1) built the system with the `TestShelleyHardForkAtVersion` option enabled.
2) started nodes
3) ran update-1.sh
4) restarted the nodes.
5) ran update-3.sh ( I didn't have to run the second update because choosing option `TestShelleyHardForkAtVersion` allowed me to bypass update-2.sh) 
This is when the error occurred 

**Expected behavior**

None - I managed to fix the error but I do not know completely why it worked... The error is a utxo discrepancy so I changed the code in `update-3.sh` so the amount of the utxo would be the same (it was really a shot in the dark, I didn't know what i was doing). 

This is what I changed:

Line #25 
Originally read:
`COINS_IN_INPUT=10000000000`
I changed it to:
`COINS_IN_INPUT=10018000000`

The code worked after the change - I didn't want to submit a pull request because I do not completely understand why it worked - I understand the concept but not how the utxo's were transferred to the `user.addr` from byron transaction id. 

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version cardano-node version 1.27.0
- CLI version  cardano-cli version 1.27.0

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by stackBlock** [comment]
FYI: I just had to do the EXACT same thing on `update-4.sh`:

changed `1000000000` to `10018000000` and it worked

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
