### ISSUE TITLE
[BUG] - Not able to complete the roll-out from Byron to Alonzo on private network.

### ISSUE THREAD

**Issue by stackBlock** [input-output-hk/cardano-node#2972]
External:
Other:   trying to build private testnet

**Summary**
I was building a private testnet with the scripts from `byron-to-alonzo` and it failed in the last process going from Mary to Alonzo.

** please look at issue ( https://github.com/input-output-hk/cardano-node/issues/2971 ) for a different error I managed to get working if you need other information **

1) built the system with the `TestShelleyHardForkAtVersion` option enabled.
2) started nodes
3) ran update-1.sh
4) restarted the nodes.
5) ran update-3.sh ( I didn't have to run the second update because choosing option TestShelleyHardForkAtVersion allowed me to bypass update-2.sh)
6) restarted the node
7) ran `update-4.sh`
8) restarted the node
9) ran `update-5.sh` 
10) restarted node

**Expected behavior**
the expected behavior is a private network running on the alonzo chain. 

issue: 
1) there was a command in `update-5.sh` that is looking for a file that is not present / was not created during the build process: 
`cardano-cli transaction submit --cardano-mode --testnet-magic 42 --tx-file mary.tx` 
because there is no `mary.tx` file, i received the error: 
`Command failed: transaction submit  Error: mary.tx: mary.tx: openBinaryFile: does not exist (No such file or directory)` 

2) upon re-start of the nodes there was the error: 
`[ip-172-3:cardano.node.Forge:Error:34] [2021-07-27 00:21:49.80 UTC] fromList [("val",Object (fromList [("kind",String "TraceNoLedgerView"),("slot",Number 40924.0)])),("credentials",String "Cardano")]`

the node stopped making blocks at the Mary era:
```{
    "epoch": 25,
    "hash": "6ff5f8a1e66cb745edf5d94cf90886ec4d5093e498ae77f23c0edbafc97f928f",
    "slot": 36190,
    "block": 3736,
    "era": "Mary"
}```

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version cardano-node version 1.27.0
- CLI version  cardano-cli version 1.27.0


**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**
Add any other context about the problem here.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
