### ISSUE TITLE
[BUG] - Some genesis file names are different to the protocol parameter names

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#2981]
**Internal**

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
The genesis file names are different to the protocol parameter names.  This could lead to configuration issues.

**Steps to reproduce**

Sample genesis file

```
{
    "lovelacePerUTxOWord": 34482,
    "executionPrices": {
        "prSteps":
		{ "numerator" : 1,
		  "denominator" : 100
		},
        "prMem":
		{ "numerator" : 5,
		  "denominator" : 1000
		}
    },
    "maxTxExUnits": {
        "exUnitsMem": 11000000000,
        "exUnitsSteps": 11000000000
    },
    "maxBlockExUnits": {
        "exUnitsMem": 110000000000,
        "exUnitsSteps": 110000000000
    },
    "maxValueSize": 5000,
    "collateralPercentage": 150,
    "maxCollateralInputs": 6
}
```

Sample protocol-parameter output
 ```
 cardano-cli query protocol-parameters
{
    ...
    "utxoCostPerWord": 0,
    ...
   "maxTxExecutionUnits": {
        "memory": 1,
        "steps": 1
    },
...
    "executionUnitPrices": {
        "priceSteps": 1,
        "priceMemory": 1
    }
}
```

**Expected behavior**
Identical parameter names.

**System info (please complete the following information):**
All operating systems.

```
git branch -v
* master b70b348c5 Merge #2979
```

**Comment by dcoutts** [comment]
The API wraps the protocol parameters, but does not wrap the Shelley or Alonzo genesis types. Thus the JSON serialisation for the genesis comes from the ledger lib, not the API.

If we want to make these the same we will have to extend the API to wrap at least the Alonzo genesis type.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
