### ISSUE TITLE
[FR] - Add input utxo validation to transaction build cmd

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#2996]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
The new `transaction build` cmd doesn't validate whether `--tx-in` utxo exists, it just says (where I was using a non-existing utxo and trying to send 5ada and it thought fee was 0.163785ada)
`"The net balance of the transaction is negative: Lovelace (-5163785) lovelace."`
So, it treats the utxo as value 0 instead of explicitly saying what's up. It may not be so obvious with complex transactions, or if the utxo gets spent it'd be good to know.

**Describe alternatives you've considered**
Would be good to error with list of all the `--tx-in` utxos that don't exist.

**Additional context / screenshots**
n/a

**Comment by newhoggy** [comment]
The balance check is done in the following places:

* https://github.com/input-output-hk/cardano-node/blob/aab244a42ab9a1e79f82c34a8e8f11faf1fa8a57/cardano-api/src/Cardano/Api/Fees.hs#L816
* https://github.com/input-output-hk/cardano-node/blob/aab244a42ab9a1e79f82c34a8e8f11faf1fa8a57/cardano-api/src/Cardano/Api/Fees.hs#L820

**Comment by dorin100** [comment]
the correct validation is done for the `--tx-out`

**Comment by james-iohk** [comment]
Proven #3151 fixes this. Additional validation may error like:
```
Command failed: transaction build  Error: The following tx input(s) were not present in the UTxO: fac4b496fc50d0fc15cc9dd60ae1f0e411154311144d020334dfaa0522fef92a#1
fac4b496fc50d0fc15cc9dd60ae1f0e411154311144d020334dfaa0522fef92a#2
```
