### ISSUE TITLE
CLI tooling: Byron, Shelley and onward

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#30]
# Context

We need means to manipulate secrets/certificates/genesis files (henceforth referred to as _key material_).

# General scope

0. Generation/derivation of all sorts of necessary key material.
0. Support for all necessary iterations of the system -- _Byron_ and _Shelley_ for now, the former in both the _Legacy_ and _PBFT_ variants.
0. Support for migration of key material between iterations of the system.
0. Transaction manipulation and submission.
0. Update system support.
0. Support for delegation & staking.

# Terminology: Legacy vs. PBFT

- **_delegator_** :: Genesis keys. Referred to as _delegation issuer_ keys in Legacy.
- **_delegate_** :: Operational keys of core nodes used for block minting and proposal signing. Referred to as _richmen_ keys in Legacy.
- **_VSS_** :: Publicly Verifiable Secret Sharing Scheme algorithm used in Ouroboros Classic/Byron Legacy.

# Future work

0. More transaction-related things: creation, pretty-printing.
0. Update system:
   - stimuli (proposals and votes): creation, pretty-printing, submission.
   - querying the node for the update system state.
0. Staking (https://github.com/input-output-hk/cardano-node/issues/139):
   - stake pool lifecycle
   - lightweight delegation

# History of implementation

## https://github.com/input-output-hk/cardano-node/pull/28

0. Generation of key material (genesis, keys) for new Byron Legacy clusters.
0. Generation of key material (genesis, keys) for new Byron PBFT clusters.
0. Migration of Byron Legacy key material (genesis, keys) to the Byron PBFT iteration. So far this appears to consist of:
   - Deserialisation of the delegate keys in the old format, as defined by the `Bi` instance for the legacy `UserSecret` data type
   - Reserialisation of the delegate keys in a new format, which, while not yet decided, has a candidate format of just a CBOR serialisation of `SigningKey`.
   - ~~Cutting VSS out of the genesis file:~~
      - ~~`vssCerts` from the top level,~~
      - ~~`vssMaxTTL` and `vssMinTTL` from the `protocolConsts` section~~
0. Pretty-printing of the key material.

## https://github.com/input-output-hk/cardano-node/pull/95
0. Separate, non-genesis keypair generation for Byron/PBFT.
0. Non-HD address printing for a given keypair.
0. Genesis hash printing.
0. Byron genesis delegation: generating delegation certificates for a given pair of genesis/delegate keys.

## https://github.com/input-output-hk/cardano-node/pull/135 & https://github.com/input-output-hk/cardano-node/pull/147
0. Raw TX submission over local node submission protocol.
0. Genesis UTxO expenditure.

# Notes

- `DELEGATE-SECRETS-INCOMPATIBLE-BYRON-LEGACY-PBFT`: as @dcoutts mentioned 
  > VSS, the Ouroboros classic randomness MPC algorithm, is not used after the PBFT hard fork.

  Therefore, the delegate secrets will no longer contain the VSS keypair, which makes them incompatible between the Legacy and PBFT iterations of Byron. This needs to be accounted for with regards to both the generation and migration aspects.
  - The compatibility was implemented in the new codebase.
- `SECRET-SERIALISATION-INCOMPATIBLE-BYRON-LEGACY-PBFT`: Byron _Legacy_ is using `cardano-binary` for secret serialisation, whereas Byron _PBFT_ uses `CBOR`. This needs to be accounted for with regards to both the generation and migration aspects.
  - ~~This does no longer appear to be a problem, since the underlying encoding that `cardano-binary` uses in the `Bi` typeclass is CBOR, which means there's only a thin compatibility layer that needs to be reimplemented.~~ The thin compatibility layer for Byron Legacy delegate key roundtripping was reimplemented.
- `GENESIS-INCOMPATIBLE-BYRON-LEGACY-PBFT`: Byron _Legacy_ carries the VSS certificates, which aren't generated by the Byron _PBFT_ genesis generator.

**Comment by disassembler** [comment]
Short term requirements look like what we need from my end.

**Comment by kevinhammond** [comment]
Still open?

**Comment by Jimbo4350** [comment]
Closing as we are currently redefining scope
