### ISSUE TITLE
Have --log-config be an optional argument when building cardano-node with nix

### ISSUE THREAD

**Issue by oneEdoubleD** [input-output-hk/cardano-node#301]
To build `cardano-node` with logging, we currently need to change the `--log-config` path in the `cardano-node` script generated from `nix-build`. It'd make programmatically building clusters/automated testing easier if we could set this path during the `nix-build` step as an optional `customConfig` argument. 

I've explained my build steps here [1] which shows you what I'm currently doing. 

[1] https://github.com/input-output-hk/cardano-ops/issues/11

**Comment by Jimbo4350** [comment]
This was resolved according to @oneEdoubleD
