### ISSUE TITLE
[FR] - return the transaction fee when executing `transaction build` command

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#3024]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
When the `transaction build` command is executed, the transactions is balanced and validated so we know the tx fee. For better transparency, it would be useful that the `transaction build` to return the transaction fee.

**Describe alternatives you've considered**
in order to find the tx fee, we need to do some math at this moment.

**Additional context / screenshots**

**Comment by james-iohk** [comment]
For development work, it would be useful to get the execution units too. It might be something we always want to print.

**Comment by dcoutts** [comment]
@james-iohk for the latter it's probably more helpful to extend the tx inspection commands rather than this build command. I'd file that as a separate FR.

**Comment by dcoutts** [comment]
Actually, why can't this whole feature be done using the existing `cardano-cli transaction view`?

**Comment by dorin100** [comment]
yeap, it might be included in `transaction view` when fixing https://github.com/input-output-hk/cardano-node/issues/3039
