### ISSUE TITLE
[BUG] - Test<Era>HardForkAtEpoch does not bump protocolVersion above 2. 

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-node#3028]
**Internal/External**
*Internal* 

**Summary**
Test networks that fork using `Test<Era>HardForkAtEpoch` don't see the `protocolVersion` be updated accordingly (it stay at `2` until there is manual update proposal to increase major version).

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
