### ISSUE TITLE
[BUG] - `transaction view` does not work for Alonzo era transactions

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#3039]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
```
$ cardano-cli transaction view --tx-body-file tx1.body

cardano-cli: FatalError {fatalErrorMessage = "friendlyTxBody: Alonzo not implemented yet"}
```

**Steps to reproduce**
1. create a tx in Alonzo era
2. use `transaction view` to see its details

**Expected behavior**

**System info (please complete the following information):**
- OS Name: Ubuntu
```
$ cardano-cli --version
cardano-cli 1.28.0 - linux-x86_64 - ghc-8.10
git rev cb11587d767af2cb6762fe65ea5f8d8898b09320

$ cardano-node --version
cardano-node 1.28.0 - linux-x86_64 - ghc-8.10
git rev cb11587d767af2cb6762fe65ea5f8d8898b09320
```

**Comment by james-iohk** [comment]
A good time to add any missing details such as exunit, fee, collateral?

**Comment by cblp** [comment]
Now master version partly works for Alonzo txs. It shows common fields and some Alonzo-introduced. The work is continuing.

**Comment by cblp** [comment]
In version 1.33, `transaction view` supports Alonzo transactions. For bugs and feature requests, please open new issues.
