### ISSUE TITLE
[BUG] - UtxosFailure (ValidationTagMismatch (IsValid True)) when tx-in-execution-units too low

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#3043]
**Internal/External**
*External*   otherwise.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**

For the AlwaysSucceeds, I can construct a script unlock Tx like this 

```
# Calculate the change to send back to PAYMENT_ADDR
ExCPU=1390000
ExMem=100
ExFct=20
UNITS="($(($ExFct*$ExCPU)),$(($ExFct*$ExMem)))"
FEES_LVC=$(($ExFct * ($ExCPU + $ExMem) + 500000))
SEND_LVC=$(($TX_IN1_LVC + $TX_SCRIPT_LVC - $FEES_LVC))
echo "Send=$SEND_LVC, Fees=$FEES_LVC, Units=$UNITS"

# Build, sign and submit the transaction
cardano-cli transaction build-raw \
  --alonzo-era \
  --fee $FEES_LVC \
  --tx-in $TX_IN1 \
  --tx-in $TX_SCRIPT \
  --tx-in-script-file /var/cardano/local/scripts/AlwaysSucceeds.plutus \
  --tx-in-redeemer-value 0 \
  --tx-in-datum-value $DATUM_VALUE \
  --tx-in-execution-units "$UNITS" \
  --tx-in-collateral $TX_COL \
  --tx-out $PAYMENT_ADDR1+$SEND_LVC \
  --protocol-params-file /var/cardano/local/scratch/protocol.json \
  --out-file /var/cardano/local/scratch/tx.raw \
&& cardano-cli transaction sign \
  --tx-body-file /var/cardano/local/scratch/tx.raw \
  --signing-key-file /var/cardano/local/keys/alonzo/acc1/payment.skey \
  --out-file /var/cardano/local/scratch/tx.signed \
&& cardano-cli transaction submit \
  --tx-file /var/cardano/local/scratch/tx.signed \
  --testnet-magic 8
```

Notice, the factor that multiplies the execution units from the compile stage is ExFct=20. This factor was found to work with alonzo-white. When I know reduce this factor to ExFct=1, I get ...

```
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (ValidationTagMismatch (IsValid True)))))])
```

This error message is confusing because the script does in fact always succeed

**Comment by tdiesler** [comment]
The lowest value that I found to work is ExFct=2

**Comment by dorin100** [comment]
Try to use `transaction build`. This should automatically balance your tx (you need to provide `--change-address` parameter).

**Comment by james-iohk** [comment]
The error message is saying there's a mismatch between expected and actual. You are submitting tx with `IsValid True` but the validation fails so this value is actually `IsValid False`.

**Comment by james-iohk** [comment]
As Dorin says, use `transaction build` where the UX is vastly improved and no need to worry about calculating exunit values. Script validation is also performed at the same time and any error is reported.

**Comment by tdiesler** [comment]
I guess, this out of date now
