### ISSUE TITLE
[BUG] - No pool rewards with alonzo-purple-1.0.1

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#3044]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**

Block producer makes plenty of blocks, but I don't see any rewards after two epochs. AFICS, I followed the same steps as in white - by now twice already. Do you see pool rewards? If so, is there a way to find out what went wrong?

```
[
    {
        "address": "stake_test1uzfer83nh7jkrfhqmtvhmct7dzfmalafp0dwmyprer3awlgvhme55",
        "rewardAccountBalance": 0,
        "delegation": "pool10axw3h2ccydacaynlw7c23yvt02jzfw0l8zt50rl8gz6szmem23"
    }
]
```

I have good connectivity between Relay & BP. the relay has eight incoming connections from others.

**Comment by dorin100** [comment]
what network are you connected to?

**Comment by tdiesler** [comment]
alonzo-purple, networkMagic=8

**Comment by dorin100** [comment]
I confirm that other pools are generating rewards on `alonzo-purple` so if your pool does not generate them, it most probable is something from the pool configuration. (like pledge not met)

**Comment by tdiesler** [comment]
This got silently fixed at the IOG network level.
