### ISSUE TITLE
[BUG] - Outdated instructions for configuring a test chain; unhelpful error message "conditional on negotiating v8 of the node-to-client protocol"

### ISSUE THREAD

**Issue by HeinrichApfelmus** [input-output-hk/cardano-node#3047]
**Internal/External**
*Internal*

**Area**
*Testing*, *blockchain genesis*, *cardano-cli*

**Summary**
To better understand and test the ecosystems, developers and stake pool operators find it helpful to be able to create and run a test blockchain locally from scratch. Unfortunately, the current instructions in `doc/reference/shelley-genesis.md` seem to be out of date and no longer work as described.

Specifically, while the description on how to set up two nodes still works and gives helpful insights on configuration, the section "Querying the node" is no longer accurate; instead, the `cardano-cli` client produces the following error message:

```
$ CARDANO_NODE_SOCKET_PATH=example/node1/node.sock \
     cardano-cli query tip --testnet-magic 42 \
     --shelley-mode

cardano-cli: encodeFailure: local state query: using acquire without a Point must be conditional on negotiating v8 of the node-to-client protocol
CallStack (from HasCallStack):
  error, called at src/Ouroboros/Network/Protocol/LocalStateQuery/Codec.hs:79:7 in ouroboros-network-0.1.0.0-KO0frQ8Zv9tFr7JpJUW12H:Ouroboros.Network.Protocol.LocalStateQuery.Codec
```

Apparently, the network is configured in a way that `cardano-cli` does not quite know how to talk to, and the `--shelley-mode` flag does not provide sufficient or even the wrong context.

**Workaround**

The script `scripts/byron-to-alonzo/mkfiles.sh` correctly configures a local test network that performs a series of hardforks. It can be queried with `cardano-cli` using the `--cardano-mode` flag.

**Steps to reproduce**
1. Follow the instructions in `doc/reference/shelley-genesis.md` to configure a local test network.
2. Start two nodes as described
3. Query the network using `cardano-cli query tip` as described.
```
cardano-cli: encodeFailure: local state query: using acquire without a Point must be conditional on negotiating v8 of the node-to-client protocol
CallStack (from HasCallStack):
  error, called at src/Ouroboros/Network/Protocol/LocalStateQuery/Codec.hs:79:7 in ouroboros-network-0.1.0.0-KO0frQ8Zv9tFr7JpJUW12H:Ouroboros.Network.Protocol.LocalStateQuery.Codec
```

**Expected behavior**

* The instructions in `doc/reference/shelley-genesis.md` should yield a local test network that works as described. (The `cardano-testnet` executable described in `doc/getting-started/launching-a-testnet` is useful, but does not help with understanding the internals of configuring a blockchain network.)
* It would beneficial if error messages for `cardano-cli query` could be improved. For example, diagnostic information on the network (e.g. whether `--shelley-mode` or `--cardano-mode` is appropriate) would be helpful.

**System info (please complete the following information):**
- OS Name: macOS Catalina
- OS Version: 10.15.7
- Node version:
```
cardano-node 1.28.0 - darwin-x86_64 - ghc-8.10
git rev 3be20df5d95896c2e585d277b7699a2891e147db
```
- CLI version
```
cardano-node 1.28.0 - darwin-x86_64 - ghc-8.10
git rev 3be20df5d95896c2e585d277b7699a2891e147db
```

**Additional context**
This problem has also been encountered in various forms elsewhere:
* https://forum.cardano.org/t/error-when-executing-cardano-cli-over-node-socket/62015
* #2720

**Comment by marijanp** [comment]
I'm also interested in an updated instruction or a script generating those files.

**Comment by mateusap1** [comment]
Any solutions? I'm receiving the same error when following the [cardano-tesnet guide](https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/launching-a-testnet.md)

**Comment by marijanp** [comment]
There is a script under scripts/byron-to-alonzo/mkfiles.sh which gennerates proper genesis files. Using them I was able to start the nodes wihout any errors.

**Comment by mateusap1** [comment]
My problem was similar I was using `cabal run cardano-testnet shelley` instead of `cabal run cardano-testnet cardano`, since the issue has to do with node synchronization, I think most people get it when they setup the testnet in different eras.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
