### ISSUE TITLE
[FR] - Add `FromJSON` instances for all types in `cardano-api` that have a `ToJSON` instance

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/cardano-node#3051]
**Internal/External**
*Internal*

**Area**
*Other*   

**Describe the feature you'd like**

Add `FromJSON` instances for all types in `cardano-api` that have a `ToJSON` instance. Example: [`TxIn`](https://input-output-hk.github.io/cardano-node/cardano-api/Cardano-Api.html#t:TxIn)

**Describe alternatives you've considered**

Users of `cardano-api` could write the instances themselves. That's not a good idea because the code would be duplicated in a number of different places and hard to maintain. It just makes sense to define `FromJSON` in the same place where `ToJSON` is defined,

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
