### ISSUE TITLE
[BUG] - Unhandled error "the impossible happened: RedeemerNotNeeded"

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#3066]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
When `--tx-in-script-file` is applied to a non-script input we get the following exception:
```
cardano-cli: evaluateTransactionExecutionUnits: the impossible happened: RedeemerNotNeeded ScriptWitnessIndexTxIn 0
CallStack (from HasCallStack):
  error, called at src/Cardano/Api/Fees.hs:529:25 in cardano-api-1.28.0-CdKYZmszYHCPvjSsEYlNu:Cardano.Api.Fees
```
It is easy to make this mistake when there are multiple `--tx-in` (e.g. one from payment address and one from script address). It can also occur when an input has already been spent.

**Steps to reproduce**
Apply `--tx-in-script-file` to an input that isn't guarded by a script, or one that no-longer or has never existed. E.g. on alonzo-purple:
```
cardano-cli transaction build --alonzo-era \
--tx-in b2cf437085d433e75b273adc4efe62fffcdc7fa3d3c821d3994814301df911b0#1066 \
--tx-in-script-file AlwaysSucceeds.plutus \
--tx-in-datum-value 1 \
--tx-in-redeemer-value 2 \
--tx-in-collateral b2cf437085d433e75b273adc4efe62fffcdc7fa3d3c821d3994814301df911b0#1066 \
--tx-out $(<acct.addr)+3000000 \
--change-address addr_test1vpdvkurqk92detyluym8s6pg3gkf5nlah834rag4rntylzs9p3d0g \
--protocol-params-file pparams.json \
--testnet-magic 8 \
--out-file txbody

```

**Expected behavior**
Handle error and print something like: "Script file has been applied to an input that has no script."

**System info (please complete the following information):**
- OS Name: Mint
- OS Version: 20.2 (Uma)
- Node version: cardano-node 1.28.0 - linux-x86_64 - ghc-8.10 git rev 708de685d49ec6af4b2d8b3cbfa0eca0e9e43edf
- CLI version: cardano-cli 1.28.0 - linux-x86_64 - ghc-8.10 git rev 708de685d49ec6af4b2d8b3cbfa0eca0e9e43edf

**Comment by dorin100** [comment]
this might be a duplicate on - https://github.com/input-output-hk/cardano-node/issues/3018
