### ISSUE TITLE
Turn on `chain-db-tracer` by default 

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#308]
`ChainDB.InvalidBlock` is not in the logs by default when it should be.

**Comment by CodiePP** [comment]
such an event will be logged as an 'Error':
https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Tracing/ToObjectOrphans.hs#L200
so it should pass the minimum severity filters which are 'Info' or in some setups 'Notice'.

**Comment by Jimbo4350** [comment]
This has been rectified.
