### ISSUE TITLE
Daedalus Wallet crashing on startup

### ISSUE THREAD

**Issue by Tangax337** [input-output-hk/cardano-node#3081]
Hi,

Recently installed Daedalus with PGP and checksum to move my ADA from coinbase, tested 5 ADA and worked fine, but now no way of accessing daedalus wallet because it just either crashes, sticks on connecting or says “Cadano node crashed” I only managed to work it once on startup and synced when I moved the first 5 over.

I want to start pooling but this really doesn’t give me confidence over coinbase, but you cant pool there.

Any help much appreciated.

Not sure if ive posted in the correct place but saw a similar issue posted on this website.

**Comment by mrbrinker** [comment]
You should seek help with Daedalus [https://iohk.zendesk.com/hc/en-us/categories/360000877653-Daedalus-wallet-mainnet](support) team
