### ISSUE TITLE
[BUG] - Transaction's valid time range is not passed correctly to ScriptContext

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#3090]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
It doesn't seem possible to check whether transaction's valid range meets a condition using a plutus validator script. Every attempt I've made results in script throwing error (we have no trace logging yet to add more helpful details).

Here is one example script: https://github.com/james-iohk/Alonzo-testnet/blob/dd94ec647c99193e55d3a640b893182a4580e19a/resources/plutus-sources/plutus-deadline/src/Cardano/PlutusExample/Deadline.hs#L31-L42
The condition defines that the interval up to my deadline (15th Oct) must contain the transaction's valid range, however:
1. `transaction build` throws `Plutus code called 'error'` even though I am using a valid range that is well within interval.
2. A transaction built with `transaction build-raw` that satisfies the condition fails on submit with `ValidationTagMismatch (IsValid True)`

I have performed a sanity check in that the script passes if my condition is `True`, so it is definitely ```(to dl) `contains` range ``` failing.

**Steps to reproduce**
1. Serialise the script for correct plutus version (I can provide)
2. Deposit funds at script's address with some datumhash
3. Use `transaction build` to create txbody to unlock funds (where current slot is 1058640):
```
cardano-cli transaction build --alonzo-era \
--tx-in $SCRIPT_UTXO \
--tx-in-script-file deadline.plutus \
--invalid-before 1050000 \
--invalid-hereafter 1060000 \
--tx-in-datum-value 666 \
--tx-in-redeemer-value 1 \
--tx-in-collateral $COLLATERAL_UTXO \
--tx-out $(<acct.addr)+2000000 \
--change-address $(<acct.addr) \
--protocol-params-file pparams.json \
--testnet-magic $(<node/db/protocolMagicId) \
--out-file txbody
Command failed: transaction build  Error: The following scripts have execution failures:
the script for transaction input 0 (in the order of the TxIds) failed with The Plutus script evaluation failed: An error has occurred:  User error:
The provided Plutus code called 'error'.
```

**Expected behavior**
It should be possible to build and submit a transaction that performs conditional check on transaction's valid range.
This means the `txInfoValidRange` from `TxInfo` is a correct `POSIXTimeRange`. I can only assume at the moment that no valid range is passed at all. (I think that in the absence of valid range negative infinity to positive infinity is used, but this is to be proved).

**System info (please complete the following information):**
- OS Name: Mint
- OS Version: 20.2 (Uma)
I have tried this on both: alonzo-purple using node/cli 708de68 and alonzo-qa using node/cli c6cb954 with same outcome.

**Comment by Jimbo4350** [comment]
@james-iohk has confirmed the correct validity interval is passed to the plutus script and I have also updated the script context test to confirm this.

**Comment by tdiesler** [comment]
Is this supposed to already work on testnet?

**Comment by nhenin** [comment]
Hi, I'm trying to implement the Vesting Contract from `plutus-use-cases` via `cardano-cli` and I believe txInfoValidRange isn't behave as expected as well...
Regarding the slot number, I'm using this logic for making conversion into posixtime when I need to :  
![image](https://user-images.githubusercontent.com/471741/137732453-5a4d77b9-a7eb-486c-b327-24e6e34e78b6.png)

**Comment by nhenin** [comment]
UPDATE : It works on my side....

**Comment by tdiesler** [comment]
@rdlrt Is there a specific epoch when the Shelley era started? Unfortunately, slot data does not seem to be available from Blockfrost. I must somehow be able to establish a baseline for time/slot.

**Comment by tdiesler** [comment]
https://discord.com/channels/@me/865286678464561252/899961500834357248

**Comment by james-iohk** [comment]
Fyi we recently discussed the topic of time/slots in Discord here: https://discord.com/channels/@me/865286678464561252/899961500834357248

The start of Shelley era is different for each network. I've not got a way to query for that but at least it's constant.

**Comment by tdiesler** [comment]
@james-iohk Do you happen to know how many preShelleyEpochs there are on mainnet?

**Comment by nhenin** [comment]
Hi guys, my team and I are testing now the Vesting Contract (`plutus-use-cases`) on mainnet (the testnet is working fine...) and we discovered that the hard coded value 1000000000000 is still there only on mainnet : 
```json
txInfoValidRange = Interval
        { ivFrom = LowerBound
            ( Finite
                ( POSIXTime
                    { getPOSIXTime = 1000000000000 }
                )
            ) True
        , ivTo = UpperBound
            ( Finite
                ( POSIXTime
                    { getPOSIXTime = 1000000000000 }
                )
            ) False
        }
```

**Comment by a-osiecki** [comment]
I'm getting this failure when checking a transaction's valid range. I'm on tag **73f9a746362695dc2cb63ba757fbcabb81733d23** of cardano-node.

**Comment by james-iohk** [comment]
> I'm getting this failure when checking a transaction's valid range. I'm on tag **[73f9a74](https://github.com/input-output-hk/cardano-node/commit/73f9a746362695dc2cb63ba757fbcabb81733d23)** of cardano-node.

Hey @a-osiecki. This particular issue is resolved but perhaps you're hitting something related. Could you provide more details (steps taken, error produced etc), ideally in a new issue, tag me and I'll take a look.

**Comment by a-osiecki** [comment]
Hi @james-iohk! I'm getting this error when testing a contract in a private testnet. Where should I post the issue?

**Comment by james-iohk** [comment]
@a-osiecki This is a generic validation error so you'll need to provide more context. If you believe you've hit a bug then raise a new issue in this repo with as much detail as possible. For guidence, we have tests for this issue before and after protocol upgrade using the emulator [here](https://github.com/input-output-hk/plutus-apps/blob/main/plutus-contract/test/Spec/TimeValidity.hs). You can also ask for specific support in the Cardano Stack Exchange.
