### ISSUE TITLE
Make genesis file more resilient to bad `NetworkMagic`

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-node#310]
@edsko has just spent day trying to debug a validation failure in the new node which resulted from the following chain of events:

1. The `RequiresMagic` was set incorrectly for mainnet.
2. When interpreting the AVVM addresses, `makeRedeemAddress` (Which lives in `cardano-ledger`) uses the network magic to construct the address. Thus it was incorporating the incorrect network magic.
3. When we got to the first transactions, they failed to lookup inputs correctly because of the differently encoded address. This happened before the network magic in their own outputs was checked and found not to conform.

There are a couple of ways we could improve this situation:
1. Rather than having the `RequiresNetworkMagic` as a separate configuration item, encode it directly as a flag in the config file. To preserve the integrity of the mainnet hash, the absence of this should be interpreted as `RequiresNoMagic`. Any other genesis file would be required to have this field present and set to a value.

2. AVVM addresses in the genesis file could be considered to have the network magic pre-encoded. This approach will work if the format in the genesis file is equal to the on-chain format with no network magic. All new files would need to have the network magic pre-encoded (and we would need to check that it was the same for each address)

**Comment by mhuesch** [comment]
> Rather than having the RequiresNetworkMagic as a separate configuration item, encode it directly as a flag in the config file. To preserve the integrity of the mainnet hash, the absence of this should be interpreted as RequiresNoMagic. Any other genesis file would be required to have this field present and set to a value.

To clarify, is the suggested change here allowing the `RequiresNetworkMagic:` key in the `.yaml` config file to be absent? Currently I see, for example:

```
...
NumCoreNodes: 1
RequiresNetworkMagic: RequiresNoMagic
PBftSignatureThreshold: 0.7
...
```

are we proposing that we allow 

```
...
NumCoreNodes: 1
PBftSignatureThreshold: 0.7
...
```

and have it be behaviorally equivalent (`RequiresNoMagic`)?

***

> AVVM addresses in the genesis file could be considered to have the network magic pre-encoded. This approach will work if the format in the genesis file is equal to the on-chain format with no network magic. All new files would need to have the network magic pre-encoded (and we would need to check that it was the same for each address)

Does this equate to decoding the addresses as though they include a NetworkMagic? For mainnet addresses, if we do that, we will get out a `NetworkMainOrStage`. It's then suggested (I think) that we check all `NetworkMagic` values of these AVVM addresses for equality, which seems like a good idea.

**Comment by nc6** [comment]
I assumed the value was already optional, since it's presumably not present in the original mainnet genesis file?

**Comment by mhuesch** [comment]
Posting this from Slack discussion, now that I better understand the proposal:

> Me:
> proposal (1) is to drop one of these two non-independent things - the `RequiresNetworkMagic` key in the `.yaml` config. we then just look for either (a) the absence of a key which indicates mainnet/staging or (b) the presence of a key which indicates a testnet.
> proposal (2) is to do the same thing, in effect, but have the AVVM addresses either (a) all contain `NetworkMainOrStage` (which encodes down to nothing in binary) or (b) all contain the same `NetworkTestnet n` where all identifiers `n` are equal

Doing both of these, as proposed above, should make it difficult/impossible(?) to trigger the above nasty failure mode.

**Comment by edsko** [comment]
> Doing both of these, as proposed above, should make it difficult/impossible(?) to trigger the above nasty failure mode.

Yup. Indeed, would be good to test that :) Could do (2) first, run with the wrong value, and make sure that the check fails.

**Comment by Jimbo4350** [comment]
Proposal (1) was implemented in #472: https://github.com/input-output-hk/cardano-node/pull/472/files#diff-6d4bac60785d853d7cad2d30b5f25b94R171

**Comment by kevinhammond** [comment]
Is this still an issue?

**Comment by Jimbo4350** [comment]
@kevinhammond Yes this is still an issue. 
```
AVVM addresses in the genesis file could be considered to have the network magic pre-encoded. This approach will work if the format in the genesis file is equal to the on-chain format with no network magic. All new files would need to have the network magic pre-encoded (and we would need to check that it was the same for each address)
```
The above still needs to be implemented in `cardano-ledger` which I will work on next.

**Comment by kevinhammond** [comment]
OK. Do we need this for the Shelley testnet?

**Comment by nc6** [comment]
@Jimbo4350 Did we switch to this format? Regardless, it's now too late to change if we didn't, so closing this issue!
