### ISSUE TITLE
[BUG] - cardano-cli passing empty set of pools to makeTransactionBodyAutoBalance

### ISSUE THREAD

**Issue by brunjlar** [input-output-hk/cardano-node#3101]
**Internal**

**Area**
*Other*

**Summary**
When calling `makeTransactionBodyAutoBalance` during `cardano-cli transaction build`, the empty set of pools is passed as an argument.

**Steps to reproduce**
N/A

**Expected behavior**
The actual set of registered stake pools should be passed as argument.

**System info (please complete the following information):**
- Arch-Linux
- `cardano-node` commit `64068a70828e16c8310f439f54a44bee7c23c80e`

**Comment by dcoutts** [comment]
Almost certainly the cause of bug #3040

**Comment by Jimbo4350** [comment]
Fixed in: https://github.com/input-output-hk/cardano-node/pull/3176
