### ISSUE TITLE
[FR] - Reject non-key-locked collateral inputs

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-node#3112]
**Internal/External**
*Internal*

**Area**
*Alonzo*

**Describe the feature you'd like**
It would be helpful if the `transaction build` command on the CLI rejected using collateral inputs which are not key locked. The ledger rejects them.

In order to do this, we will need to lookup the collateral inputs in the UTxO, and inspect the addresses. If the cardano-api doesn't already have a function for determining if an address is key-locked, we can use this one:

https://github.com/input-output-hk/cardano-ledger-specs/blob/91e1c199c31ad3d93e4ac4715b3e7bb8526e97cd/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L224-L227

**Comment by james-iohk** [comment]
Proven that #3151 fixes this by throwing error like:
`Command failed: transaction build  Error: Expected key witnessed tx inputs but got script witnessed tx inputs: 
49e462b220ddfe932447c32fd75f47d57b5e4392e37d13b3b8e2b3fe030b4ac5#1`
