### ISSUE TITLE
[BUG] - relay node stuck on starting

### ISSUE THREAD

**Issue by BillyTheCowBoy** [input-output-hk/cardano-node#3113]
**Internal/External**
External otherwise.

**Area**
Other Any other topic (Delegation, Ranking, ...).

**Summary**
relay node stuck on starting .

**Steps to reproduce**
1. run 'journalctl --unit=cardano-node --follow'
2  startRelayNodel.sh was forced to killed.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version : cardano-node 1.27.0 - linux-x86_64 - ghc-8.10
- CLI version : cardano-cli 1.27.0 - linux-x86_64 - ghc-8.10

**Screenshots and attachments**
Aug 22 17:21:19 relay1 cardano-node[225763]: [relay1:cardano.node.ChainDB:Info:5] [2021-08-22 17:21:19.57 UTC] before next, messages elided = 27108039
Aug 22 17:21:19 relay1 cardano-node[225763]: [relay1:cardano.node.ChainDB:Info:5] [2021-08-22 17:21:19.57 UTC] Replayed block: slot SlotNo 27129561 of At (SlotNo 27136407)
Aug 22 17:21:19 relay1 cardano-node[225763]: [relay1:cardano.node.ChainDB:Info:5] [2021-08-22 17:21:19.57 UTC] Replayed block: slot SlotNo 27129582 of At (SlotNo 27136407)
Aug 22 17:21:20 relay1 cardano-node[225763]: [relay1:cardano.node.ChainDB:Info:5] [2021-08-22 17:21:20.23 UTC] before next, messages elided = 27129626
Aug 22 17:21:20 relay1 cardano-node[225763]: [relay1:cardano.node.ChainDB:Info:5] [2021-08-22 17:21:20.23 UTC] Replayed block: slot SlotNo 27136407 of At (SlotNo 27136407)
Aug 22 17:21:20 relay1 cardano-node[225763]: [relay1:cardano.node.ChainDB:Info:5] [2021-08-22 17:21:20.23 UTC] Opened lgr db
Aug 22 17:23:48 relay1 cardano-node[225754]: /home/billy/cardano-my-node/startRelayNode1.sh: line 9: 225763 Killed                  /usr/local/bin/cardano-node run --topology ${TOPOLOGY} --database-path ${DB_PATH} --socket-path ${SOCKET_PATH} --host-addr ${HOSTADDR} --port ${PORT} --config ${CONFIG}
Aug 22 17:23:56 relay1 cardano-node[226063]: Listening on http://127.0.0.1:12798
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.networkMagic:Notice:5] [2021-08-22 17:23:56.40 UTC] NetworkMagic 764824073
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.basicInfo.protocol:Notice:5] [2021-08-22 17:23:56.40 UTC] Byron; Shelley
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.basicInfo.version:Notice:5] [2021-08-22 17:23:56.40 UTC] 1.27.0
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.basicInfo.commit:Notice:5] [2021-08-22 17:23:56.40 UTC] 8fe46140a52810b6ca456be01d652ca08fe730bf
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.basicInfo.nodeStartTime:Notice:5] [2021-08-22 17:23:56.40 UTC] 2021-08-22 17:23:56.403663557 UTC
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.basicInfo.systemStartTime:Notice:5] [2021-08-22 17:23:56.40 UTC] 2017-09-23 21:44:51 UTC
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.basicInfo.slotLengthByron:Notice:5] [2021-08-22 17:23:56.40 UTC] 20s
Aug 22 17:23:57 relay1 cardano-node[226063]: [relay1:cardano.node.basicInfo.epochLengthByron:Notice:5] [2021-08-22 17:23:56.40 UTC] 21600

**Comment by btbf** [comment]
Does your server have 16GB of system memory?

**Comment by BillyTheCowBoy** [comment]
Thanks btbf . 4 GB. i will upgrade to 16 GB and try again.
