### ISSUE TITLE
[FR] - `cardano-cli` support non-UTF8 TokenName

### ISSUE THREAD

**Issue by longngn** [input-output-hk/cardano-node#3114]
**Internal/External**
*External* 

**Area**
*Alonzo*

**Describe the feature you'd like**
Currently, `cardano-cli` doesn't support non-UTF8 TokenName as an arg input in its syntax, as well as displaying non-UTF8 TokenName (see: https://github.com/input-output-hk/cardano-node/issues/2999)
With Alonzo coming soon, encoding information in TokenName in raw bytes will become popular, so I think it's a good idea to support building/displaying it with `cardano-cli` as hex-encoded ByteString.
My idea is to prefix TokenName with 0x, something like `policyId.0x.tokenName` to tell that the tokenName is hex-encoded.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by gitmachtl** [comment]
was resolved with https://github.com/input-output-hk/cardano-node/pull/3211
