### ISSUE TITLE
[BUG] - Spelling Mistake causing nix build to fail

### ISSUE THREAD

**Issue by jonathanfishbein1** [input-output-hk/cardano-node#3119]
in haskell.nix file

        enableLibraryProfiling = true;
        packages.cardano-node.components.exes.cardano-node.enableExecutableProfiling = true;
        packages.tx-generator.components.exes.tx-generator.enableExecutableProfiling = true;
        packages.locli.components.exes.locli.enableExecutableProfilig = true;

enableExecutableProfilig missing an 'n'

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
