### ISSUE TITLE
Purge the code base of the RequireNetworkMagic type

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#312]
This type is defined in `cardano-config/src/Cardano/Config/Types.hs` as:
```
data RequireNetworkMagic
    = RequireNetworkMagic
    | NoRequireNetworkMagic
    deriving (Eq, Show)
```
but is close to identical to this from `cardano-ledger`:
```
data RequiresNetworkMagic
  = RequiresNoMagic
  | RequiresMagic
  deriving (Show, Eq, Generic, NFData, NoUnexpectedThunks)
```
Its a huge pain in the neck have two type that are completely isomorphic.

`RequireNetworkMagic` has to die and be replaced by the one from `ledger`

**Comment by erikd** [comment]
Probably also worth checking if there are any other types like this that mirror types lower in the dependency stack and kill them at the same time.

**Comment by erikd** [comment]
Not a priority for this weeks' snapshot but should do it early next week.

**Comment by Jimbo4350** [comment]
Removed in #326
