### ISSUE TITLE
[BUG] - CLI [transaction build] calculates number of witnesses incorrectly in the case include a withdrawal

### ISSUE THREAD

**Issue by btbf** [input-output-hk/cardano-node#3132]
**Internal/External**
*External*   otherwise.

**Area**
cardano-cli

**Steps to reproduce**

**If you create a reward withdrawal transaction file like the following**
```
cardano-cli transaction build \
    --tx-in e969e77dbe7d0c25f522c0e90d6369f070b99fe4c44283c3324a59c98f6891a7#0 \
    --tx-out $(cat payment.addr) + 1500000000 \
    --change-address $(cat payment.addr) \
    --invalid-hereafter $(( 592817 + 10000)) \
    --withdrawal $(cat stake.addr) + 1500000000 \
    --testnet-magic 8 \
    --alonzo-era \
    --out-file tx.raw
```
**The following error occurs and the transaction transmission fails.**
`Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (FeeTooSmallUTxO (Coin 170033) (Coin 165589))))])`

**How to fix**
Need to specify the exact witness-override.
```
cardano-cli transaction build \
    --witness-override 2 \
    --tx-in e969e77dbe7d0c25f522c0e90d6369f070b99fe4c44283c3324a59c98f6891a7#0 \
    --tx-out $(cat payment.addr) + 1500000000 \
    --change-address $(cat payment.addr) \
    --invalid-hereafter $(( 592817 + 10000)) \
    --withdrawal $(cat stake.addr) + 1500000000 \
    --testnet-magic 8 \
    --alonzo-era \
    --out-file tx.raw
```

**System info (please complete the following information):**
- OS Name:Ubuntu
- OS Version 20.04
- 
cardano-node 1.29.0 - linux-x86_64 - ghc-8.10
git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2

cardano-cli 1.29.0 - linux-x86_64 - ghc-8.10
git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2

**Comment by dorin100** [comment]
this is fixed in release 1.31.0. please reopen it if it is still reproducible, thank you.
