### ISSUE TITLE
[BUG] - Withdraw as many times as you want by executing reward withdrawal in [transaction build]

### ISSUE THREAD

**Issue by btbf** [input-output-hk/cardano-node#3133]
**Internal/External**
*External*   otherwise.

**Area**
cardano-cli

**Steps to reproduce**

The ADA does not decrease from the reward address when the transaction build is specified and the reward withdrawal is executed.

```
cardano-cli transaction build \
    --witness-override 2 \
    --tx-in e969e77dbe7d0c25f522c0e90d6369f070b99fe4c44283c3324a59c98f6891a7#0 \
    --tx-out $(cat payment.addr) + 1500000000 \
    --change-address $(cat payment.addr) \
    --invalid-hereafter $(( 592817 + 10000)) \
    --withdrawal $(cat stake.addr) + 1500000000 \
    --testnet-magic 8 \
    --alonzo-era \
    --out-file tx.raw
```
```
cardano-cli transaction sign \
    --tx-body-file tx.raw \
    --signing-key-file payment.skey \
    --signing-key-file stake.skey \
    --testnet-magic 8 \
    --out-file tx.signed
```
```
cardano-cli transaction submit \
    --tx-file tx.signed \
    --testnet-magic 8
```
```
cardano-cli query stake-address-info \
    --testnet-magic 8 \
    --address $(cat stake.addr)
```
The reward has not been reduced from stake.addr.
receive it by submitting the reward withdrawal transaction again.

**System info (please complete the following information):**
- OS Name:Ubuntu
- OS Version 20.04
- 
cardano-node 1.29.0 - linux-x86_64 - ghc-8.10
git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2

cardano-cli 1.29.0 - linux-x86_64 - ghc-8.10
git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2

**Comment by dorin100** [comment]
closing as duplicate
