### ISSUE TITLE
[FR] - Signature (notary, cosign) of the official cardano-node Docker images

### ISSUE THREAD

**Issue by regel** [input-output-hk/cardano-node#3136]
**Internal/External**
*External*

**Area**
*Other*   : Docker security

**Describe the feature you'd like**

Currently, the official docker images at `inputoutput/cardano-node` versions ..., 1.28, 1.29, are unsigned.

To let users verify the signature of images can you please consider signing them either using notary (docker content trust), or `cosign` which seems a popular option and the one used at Google to publish signed [distroless](https://github.com/GoogleContainerTools/distroless) images.

**Describe alternatives you've considered**

Alternative: copy the image to a personal registry in Azure ACR, and sign it using own cosign keys, and push the signed images to own repository in order to operate a pool with _trusted_ images. Several CaaS clusters have admission hooks that support signature verification before running containers. Unsigned containers will not run in this setup.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
