### ISSUE TITLE
NodeId should not be part of the configuration file.

### ISSUE THREAD

**Issue by karknu** [input-output-hk/cardano-node#314]
The NodeId should be a command line argument like port number.
With the current scheme one is forced to have one node configuration file per node in a topology file.

**Comment by deepfire** [comment]
@karknu, I think the node Id should be inferred from the PBFT leader credentials, not specified at all.

**Comment by edsko** [comment]
PBFT indeed doesn't need it anymore (https://github.com/input-output-hk/ouroboros-network/pull/1192).

**Comment by dcoutts** [comment]
If we need anything like this at all, it's only to allow sharing a network configuration description between multiple nodes. It has no connection whatsoever to any notion of node id from consensus (since there is no such notion).

**Comment by deepfire** [comment]
The topology part of de-`NodeId`-ification is being handled in https://github.com/input-output-hk/cardano-node/pull/318
