### ISSUE TITLE
[FR] - Document Docker container

### ISSUE THREAD

**Issue by seriru** [input-output-hk/cardano-node#3144]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Other*  Docker documentation

**Describe the feature you'd like**
I would like to see documentation about the Docker images. For example, I start the node with very specific RTS flags. When I upgraded from 1.27.0 to 1.29.0 I didn't realise that you must supply environment variable CARDANO_BLOCK_PRODUCER=true for the node to operate as a block producer, even though the parameters to the cardano-node had --shelley-kes-key, --shelley-vrf-key and --shelley-operational-certificate there. One can argue that this issue is a bug.

**Comment by tdiesler** [comment]
I can look into this

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
