### ISSUE TITLE
[BUG] - Node periodically stalls block sync then restarts

### ISSUE THREAD

**Issue by cyber-russ** [input-output-hk/cardano-node#3166]
**External**

**Area**
*Other* 
Cardano-Node networking

**Summary**
Since upgrade to 1.29.0 we see periodic spikes (see attached screenshot for example) in block sync speed as stalled node restarts. We only see this on warm standby nodes with a couple of connections to local relays.

**Steps to reproduce**
1. Upgrade to 1.29.0

**Expected behavior**
No stalls

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 1.29.0
- CLI version  1.29.0

**Screenshots and attachments**
- Screenshot of grafana monitoring
<img width="847" alt="Screenshot 2021-09-04 at 07 45 10" src="https://user-images.githubusercontent.com/8545577/132085674-d8aa5dcb-fb56-47c7-9d5c-da818b3bc903.png">

**Additional context**
No other network changes have been made, base OS and configuration remains the same

**Comment by cyber-russ** [comment]
Now seeing this on main relays as well.

**Comment by cyber-russ** [comment]
Seems to have reduced as more nodes have converted to Alonzo spec...nodes have not been rebooted, no other changes

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
