### ISSUE TITLE
Add documentation to cardano config files

### ISSUE THREAD

**Issue by DavidEichmann** [input-output-hk/cardano-node#3172]
We should add documentation to the fields of the cardano config files (and convert to yaml). We must also update the script from #3145 such that it does not overwrite this documentation.

**Comment by DavidEichmann** [comment]
I wonder if the complications as noted in the description of #3173 can be avoided simply by putting this documentation in a separate example/documentation files and keeping the mainnet config files untouched.

**Comment by newhoggy** [comment]
Your idea has merit.  I'll think on it.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
