### ISSUE TITLE
[BUG] - aarch64 compile ghc 8.10.7 raspberry pi 4

### ISSUE THREAD

**Issue by BETOXL** [input-output-hk/cardano-node#3184]
**Internal/External**
*External*   otherwise.

**Area** 

*Other*   build cardano node.

**Summary**
aarch64 Raspberry pi 4
When trying to compile with cabal build cardano-node cardano-cli be cautious except perhaps to import instances from ‘Data.Semigroup’ error

**Steps to reproduce**
1.  cabal-install version 3.4.0.0
2. The Glorious Glasgow Haskell Compilation System, version 8.10.7
3. git clone https://github.com/input-output-hk/cardano-node.git cardano-node
4. cd $HOME/git/cardano-node
5. git fetch --all --recurse-submodules --tags
6. git checkout $(curl -s https://api.github.com/repos/input-output-hk/cardano-node/releases/latest | jq -r .tag_name)
7. cabal configure -O0 -w ghc-8.10.7
8. echo -e "package cardano-crypto-praos\n flags: -external-libsodium-vrf" > cabal.project.local
9. cabal build cardano-node cardano-cli
10. `Failed to build exe:alex from alex-3.2.6.
Build log (
/root/.cabal/logs/ghc-8.10.7/alex-3.2.6-e-alex-838d55093d70a7c6050e230234a6584e9da9744f8aea4177bb18e5634fc907dc.log
):
Configuring executable 'alex' for alex-3.2.6..
Preprocessing executable 'alex' for alex-3.2.6..
Building executable 'alex' for alex-3.2.6..
[ 1 of 22] Compiling Data.Ranged.Boundaries ( src/Data/Ranged/Boundaries.hs, dist/build/alex/alex-tmp/Data/Ranged/Boundaries.o )
[ 2 of 22] Compiling Data.Ranged.Ranges ( src/Data/Ranged/Ranges.hs, dist/build/alex/alex-tmp/Data/Ranged/Ranges.o )
[ 3 of 22] Compiling Data.Ranged.RangedSet ( src/Data/Ranged/RangedSet.hs, dist/build/alex/alex-tmp/Data/Ranged/RangedSet.o )

src/Data/Ranged/RangedSet.hs:31:1: warning: [-Wunused-imports]
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
   |
31 | import Data.Semigroup
   | ^^^^^^^^^^^^^^^^^^^^^
[ 4 of 22] Compiling Data.Ranged      ( src/Data/Ranged.hs, dist/build/alex/alex-tmp/Data/Ranged.o )
[ 5 of 22] Compiling Map              ( src/Map.hs, dist/build/alex/alex-tmp/Map.o )
[ 6 of 22] Compiling Paths_alex       ( dist/build/alex/autogen/Paths_alex.hs, dist/build/alex/alex-tmp/Paths_alex.o )
[ 7 of 22] Compiling Set              ( src/Set.hs, dist/build/alex/alex-tmp/Set.o )
[ 8 of 22] Compiling DFS              ( src/DFS.hs, dist/build/alex/alex-tmp/DFS.o )
[ 9 of 22] Compiling Sort             ( src/Sort.hs, dist/build/alex/alex-tmp/Sort.o )
[10 of 22] Compiling UTF8             ( src/UTF8.hs, dist/build/alex/alex-tmp/UTF8.o )
[11 of 22] Compiling CharSet          ( src/CharSet.hs, dist/build/alex/alex-tmp/CharSet.o )
[12 of 22] Compiling Util             ( src/Util.hs, dist/build/alex/alex-tmp/Util.o )
[13 of 22] Compiling AbsSyn           ( src/AbsSyn.hs, dist/build/alex/alex-tmp/AbsSyn.o )
[14 of 22] Compiling ParseMonad       ( src/ParseMonad.hs, dist/build/alex/alex-tmp/ParseMonad.o )
[15 of 22] Compiling Scan             ( src/Scan.hs, dist/build/alex/alex-tmp/Scan.o )
[16 of 22] Compiling Parser           ( src/Parser.hs, dist/build/alex/alex-tmp/Parser.o )
[17 of 22] Compiling Output           ( src/Output.hs, dist/build/alex/alex-tmp/Output.o )
[18 of 22] Compiling NFA              ( src/NFA.hs, dist/build/alex/alex-tmp/NFA.o )
[19 of 22] Compiling Info             ( src/Info.hs, dist/build/alex/alex-tmp/Info.o )
[20 of 22] Compiling DFAMin           ( src/DFAMin.hs, dist/build/alex/alex-tmp/DFAMin.o )
[21 of 22] Compiling DFA              ( src/DFA.hs, dist/build/alex/alex-tmp/DFA.o )
[22 of 22] Compiling Main             ( src/Main.hs, dist/build/alex/alex-tmp/Main.o )
Linking dist/build/alex/alex ...
/usr/bin/ld.gold: error: cannot find -lnuma

rts/posix/OSMem.c:370:0: error:
     error: undefined reference to 'mbind'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSMem.c:758:0: error:
     error: undefined reference to 'numa_get_mems_allowed'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSMem.c:763:0: error:
     error: undefined reference to 'numa_bitmask_free'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build exe:alex from alex-3.2.6 (which is required by
test:cardano-node-test from cardano-node-1.29.0, exe:cardano-node from
cardano-node-1.29.0 and others). See the build log above for details.`

**Expected behavior**
successful compilation

**System info (please complete the following information):**
- OS Name: [Ubuntu 20.10 (GNU/Linux 5.8.0-1032-raspi aarch64)]
- OS Version [20.10]
- Node version (no)
- CLI version  (no)

**Additional context**
no

**Comment by coot** [comment]
Try to run `cabal build --ghc-option -Wno-error ...`

**Comment by angerman** [comment]
You are failing to build `alex`, which for some reason wants the `numa` library, which it can't find. This is *not* a cardano-node bug. You might need to install numa on your build machine.
```
sudo apt-get install -y libnuma-dev
```
might be what you need, but that's just a guess.

**Comment by igolfs** [comment]
FYI, apparently even an 8GB RPi 4 doesn't have enough memory to compile from source.
Seems like the people behind these Docker images compiled on an AWS ARM instance:
https://hub.docker.com/r/nessusio/cardano-node/tags?name=arm64

**Comment by orpheus-antpool** [comment]
Not true, even a RPI with 4GB can compile successfully. Just activate zram (compressed swap space in RAM) and install llvm.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
