### ISSUE TITLE
[BUG] - `nix-build -A scripts.testnet.node` broken between 1.27.0 and 1.29.0

### ISSUE THREAD

**Issue by runeksvendsen** [input-output-hk/cardano-node#3185]
**Internal/External**
*External*

**Area**
*Other* deployment script or [this guide](https://iohk.zendesk.com/hc/en-us/articles/900000672303-How-to-build-and-run-cardano-wallet-using-Nix) (depending on how you look at it)

**Summary**
The article/guide [How to build and run cardano-wallet using Nix](https://iohk.zendesk.com/hc/en-us/articles/900000672303-How-to-build-and-run-cardano-wallet-using-Nix) says to issue the following command to build and run cardano-node.

```
nix-build -A scripts.testnet.node -o testnet-node-local && ./testnet-node-local
```

On 1.27.0 it works as expected: `testnet-node-local` is a BASH script that runs the built `cardano-node` with the expected arguments. On 1.29.0, however, the same target is a *folder* which contains the script to run, thus breaking the above article/guide:

```
$ ls -R testnet-node-local
bin

testnet-node-local/bin:
cardano-node-testnet
```

**Steps to reproduce**
1. Go to https://iohk.zendesk.com/hc/en-us/articles/900000672303-How-to-build-and-run-cardano-wallet-using-Nix
2. Perform step 2
3. Run: `git checkout 1.29.0`
4. Perform step 3

**Expected behavior**
`cardano-node` is started 

**Actual behavior**
The shell `cd`s into the `testnet-node-local` folder

**System info (please complete the following information):**
- OS Name: macOS
- OS Version: 11.5.2
- Node version:
```
cardano-node 1.29.0 - darwin-x86_64 - ghc-8.10
git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2
```

- CLI version: N/A

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
