### ISSUE TITLE
[FR] - make Alonzo-era transactions default

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3201]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
Mary-era transactions are now default, i.e. when `--alonzo-era` is not specified when building a transaction. Since Alonzo is now on mainnet, it would make sense to make Alonzo-era transactions the default.

**Comment by Jimbo4350** [comment]
Fixed here: https://github.com/input-output-hk/cardano-node/pull/3339
