### ISSUE TITLE
[QUESTION] Protocol parameters

### ISSUE THREAD

**Issue by theprobugmaker** [input-output-hk/cardano-node#3209]
Hi there guys. How often does the protocol parameters change? For example: ` cardano-cli query protocol-parameters`. I want to know if I need to get the protocol parameters every time I need to calculate transaction fee or it doesn't change much often and I'm good querying only once.

Thank you.

I tried to ask somewhere else but nobody answered so that is why I'm opening an issue.

**Comment by gitmachtl** [comment]
You should query it everytime before a bunch of transactions. The values in there can be changed dynamically. Yes they stay the same most of the time, but always using the latest version is a good advise. 😄

**Comment by Jimbo4350** [comment]
IOG will announce in advance on Twitter, Discord and the SPO TG when they plan to update the protocol parameters.
