### ISSUE TITLE
[BUG] - Transaction Metadata JSON Examples are showing decimal numbers, which are not allowed

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#3220]
*External* 

**Area**
Metadata

**Summary**
The examples on the Metadata Reference Documention (https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/tx-metadata.md) are showing decimalnumbers, but only
integers and 64 byte strings are allowed to be included as metadata JSON structure via the CLI.

So this Reference Documentation should be updated IMO.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
