### ISSUE TITLE
Clarification - are keys needed to run cardano-submit-api

### ISSUE THREAD

**Issue by magick93** [input-output-hk/cardano-node#3229]
Hello

On https://github.com/input-output-hk/cardano-node/tree/master/cardano-submit-api it says:

> You will need some a cardano network with payment address and keys. 

I'm assuming that this is required to construct a tx and then send contructed tx to the `submit-api`, but not actually required to run the api. Can someone please confirm, or correct me on this assumption?

I'm a little concerned that I may need to have sensitive info (keys) on a server if I wish to run the `cardano-submit-api`.

# Remote sending of transactions

The examples given on the `README.md` all use the cli, and therefore assume the transaction is constructed locally.

- Do you have any examples sending a transaction over Http?
- Does the `cardani-submit-api` need to be explicity installed, or is it part of the cardano node?
- Is there an official Cardano or IOHK docker image that has the `cardani-submit-api` installed?

**Comment by rdlrt** [comment]
> I'm assuming that this is required to construct a tx and then send contructed tx to the submit-api, but not actually required to run the api. 

Yes, that's correct - submit API simply accepts tx sent via POST requests and submits it to node , running submit-api does not need key itself. That is only needed on your local machine where you're constructing the transaction.

> Do you have any examples sending a transaction over Http?

Transaction can be created on local machine, and submitted to submit API using curl command shown in example (for production, you'd ofcourse want to secure the endpoint with https atleast).

> Does the cardani-submit-api need to be explicity installed, or is it part of the cardano node?

Part of node (if using cabal install/build commands)

> Is there an official Cardano or IOHK docker image that has the cardani-submit-api installed?

The current docker might be outdated, see PR [here](https://github.com/input-output-hk/cardano-node/pull/3128)

**Comment by magick93** [comment]
Ok, this is very helpful, and really appreciate the prompt reply.

One more question. What is the difference between the `cardanio-submit-api `and `cardano-wallet-api`?

**Comment by rdlrt** [comment]
[wallet](https://input-output-hk.github.io/cardano-wallet/api/edge/) is to query a full node wallet (eg: daedalus, or a custodial service) where keys are held locally on the server. IMO - it has very limited use cases for developer/builders

submit-api allows you to submit constructed transactions (eg: via CLI or serialisation-lib ) remotely, in this case transaction could even be created offline.

**Comment by magick93** [comment]
Thank you again.

It should like `submit-api ` is what I am looking for. 

Thank you.
