### ISSUE TITLE
[FR] - Dockerfile and dockerimage with config files that do not have random names

### ISSUE THREAD

**Issue by magick93** [input-output-hk/cardano-node#3238]
**Internal/External**
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**

Summary of issue
* There is a chain of dependencies with the config files They need to be in the same directory. Or need to know the location of dependent config files
* One is too big to be added as a config map
* It is possible to point to files that are already in the image, but this requires knowing their location, which appears to be random.

Currently the docker image, eg, `inputoutput/cardano-node:1.29.0` contains config files with randomly generated names, eg `dwbw1jxncda6kfm1wj5qa9bqbm4iy52s-config-0-0.json`.

If the filenames do not contain random strings, then they can easily be replaced when mounting a configmap. 

**Describe alternatives you've considered**

If I would like to, for example, change the following in `mainnet-config.json`

```json
  "hasPrometheus": [
    "0.0.0.0",
    12798
  ],
```

I now need to create and maintain a new dockerfile (where is the original one?), build and push. And also modify this config, and create a configMap (for using in kubernetes) to mount this specific config file. 

# Related

https://github.com/input-output-hk/cardano-node/issues/1751

**Comment by regel** [comment]
#3135

**Comment by regel** [comment]
hi @magick93 I solved this issue and will release in a couple days

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
