### ISSUE TITLE
[FR] - dockerfile for cardano-node

### ISSUE THREAD

**Issue by magick93** [input-output-hk/cardano-node#3239]
**Internal/External**
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**

It would be good to see the dockerfile so that I can see:

- what environment variables are available
- what `CMD` or `Entrypoint` is used, and how best to customize this
- where various files are stored
- what the base image is.  Running `cat /etc/os-release ` does not work in the container unfortunately.

**Describe alternatives you've considered**

Unfortunately this is also no help - https://hub.docker.com/layers/inputoutput/cardano-node/1.29.1/images/sha256-344789b94d0e58a1a9113ffeb314dad6c9fcddee3553bf527244a962eb9f54be?context=explore - this would usually display useful data but is blank in this case.

Running `docker inspect <image_id>` also did not yeild any useful results, eg:

```json
...
"ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        }
 ...
```

May need to use a tool such as https://github.com/wagoodman/dive

# Other similar requests

- https://github.com/input-output-hk/cardano-node/issues/1133
- https://github.com/input-output-hk/cardano-node/issues/3249
>  I couldn't find any Dockerfile to see what the command actually is (e.g. the entrypoint command).

**Comment by yurigba** [comment]
There is a need for transparent Dockerfile and updated build instructions. Even the build instructions provided at https://developers.cardano.org/docs/get-started/installing-cardano-node does not work without many workarounds.

**Comment by magick93** [comment]
Whats worse is the official IOHK docker image for the cardano-node ships with a gcc compiler. So if a bad actor managed to access the image they could, in theory, compile a replacement cardano-node and steal keys.

**Comment by yurigba** [comment]
I understand that [having the Dockerfile in docker hub is not always possible](https://forums.docker.com/t/how-can-i-view-the-dockerfile-in-an-image/5687/2), however I don't want to trust an image that we can't see the Dockerfile (and I am not the only one thinking this way). 

I have built my own podman containers and I am far more comfortable operating wallets in there (even if I am not a good container developer) than a container that I can't see the instructions to build. In the future I will share the Containerfile, but first I will change them to multi-stage containers to address the issue of having GCC inside them as cited by @magick93. In the meantime I can help if someone is having trouble compiling cardano-node or cardano-wallet.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
