### ISSUE TITLE
[BUG] - Cardano-cli query utxo getting error "unexpected key"

### ISSUE THREAD

**Issue by SergeySagan** [input-output-hk/cardano-node#3241]
**External**

**Area**: *Other*

**Summary**
I’ve followed the Cardano guide to run my own node in Windows 10, and though the node seems to be running well (my “db” is now close to 15GB) whenever I try to query it, I get the error: "unexpected key"

**Steps to reproduce**
My Command Prompt is:

```
cardano-cli query utxo ^
     --address addr1myaddress --mainnet
```

I am getting the error:

```
cardano-cli: DecoderFailure (Handshake) ServerAgency TokConfirm) (DeserialiseFailure 2 "codecHandshake.Confirm: unexpected key")---
```
Obviously addr1myaddress is my full Cardano address that I created with the CLI, which created the files: `pay.skey, pay.vkey, and pay.addr`

I have downloaded the latest configs from:
https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/index.html

**System info:**
- OS Name: Windows 10 Pro
- OS Version: 21H1
- Node version (output of `cardano-node --version`):
```
cardano-node 1.29.0 - mingw32-x86_64 - ghc-8.10
git rev 71135f5f6aa979843a1753e8cd6c06e085d07444
```
- CLI version  (output of `cardano-cli --version`):
```
cardano-cli 1.29.0 - mingw32-x86_64 - ghc-8.10
git rev 71135f5f6aa979843a1753e8cd6c06e085d07444
```

**Screenshots and attachments**
- n/a

**Additional context**
I've also posted this bug, without resolution here:
https://forum.cardano.org/t/cardano-cli-query-utxo-getting-error-unexpected-key/75652/3

**Comment by gitmachtl** [comment]
have you set the `CARDANO_NODE_SOCKET_PATH` env variable?

**Comment by SergeySagan** [comment]
Yes:
![image](https://user-images.githubusercontent.com/3606218/134777983-177b6e80-798d-4e6f-9101-7c66b8d29ab4.png)

**Comment by SergeySagan** [comment]
On https://cardanoscan.io/ it all looks good:
![image](https://user-images.githubusercontent.com/3606218/137583692-a2c1a998-3a10-4699-992d-8baf2102b233.png)

Having trouble finding links for Windows binaries of 1.30.1, can you link them in this thread?

**Comment by ZzAntares** [comment]
ah yes, I see no windows builds for newer versions 😞 ; just to be clear does this happen with any address? or only with that specific address? if so could you share the address you're using?

I'm not too familiar in how `cardano-cli` is meant to be used in windows, but what's the `^` doing in your `query utxo` command? is it a typo?

**Comment by gitmachtl** [comment]
and you run the cardano-cli command also from within that directory? otherwise the path would be wrong. you can try to set an absolute path, not a relative one.

**Comment by SergeySagan** [comment]
Running node with different socket ("\\\\.\\pipe\\cardano-node-socket"):
![image](https://user-images.githubusercontent.com/3606218/137819189-210e25f2-a33c-431e-9206-b4eca12110a8.png)

When trying to get address balance I get a new error:
![image](https://user-images.githubusercontent.com/3606218/137819375-93003810-9bb0-4f5b-a4ea-aa87beffaffd.png)

I have also tried setting the socket path in these variations, both Environment and start node command:

> "\\\\.\\pipe\\cardano-node-socket"
> \\\\.\\pipe\\cardano-node-socket
> "\\.\pipe\cardano-node-socket"
> \\.\pipe\cardano-node-socket
> "\\\\.\\pipe\\cardano-node-mainnet"
> \\\\.\\pipe\\cardano-node-mainnet

What seemed to make the most sense was setting the node command to `--socket-path "\\\\.\\pipe\\cardano-node-socket"` (with quotes) and the Environment variable `CARDANO_NODE_SOCKET_PATH` to `\\.\pipe\cardano-node-socket` (without the quotes)... but still error:
![image](https://user-images.githubusercontent.com/3606218/137820966-7a0d62da-ca33-4e65-8392-66ce7bcc8072.png)

**Comment by 39riffat** [comment]
Hi
Did anyone get the solution of this issue?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
