### ISSUE TITLE
[BUG] - DOCKER - Cannot override config, topology files when passing -e NETWORK=testnet

### ISSUE THREAD

**Issue by knicholes** [input-output-hk/cardano-node#3249]
**Internal/External**
*Internal*  

**Area**
*other* - Docker

**Summary**
When following the documentation at [dockerhub](https://hub.docker.com/r/inputoutput/cardano-node), we're shown how to override --topology, --config, --database-path.  When running the command found in the [cardano docs](https://docs.cardano.org/getting-started/installing-the-cardano-node), the command ```docker run -v cardano-node-ipc:/ipc -v cardano-node-data:/data inputoutput/cardano-node run --help``` works.  But if you add in the -e NETWORK=testnet param, the container fails to start correctly saying "Invalid argument `run'"

**Steps to reproduce**
1. Install docker
2. Create your ipc and cardano-node-data volumes
3. Run `docker run -v cardano-node-ipc:/ipc -v cardano-node-data:/data inputoutput/cardano-node run --help` and see that it works.
4. Run `docker run -eNETWORK=testnet -v cardano-node-ipc:/ipc -v cardano-node-data:/data inputoutput/cardano-node run --help` and see that it fails with the message "Invalid argument `run'"

**Expected behavior**
I expect following the steps in the documentation to work for both testnet and mainnet so as to be able to be able to test my topology in the testnet before I move to mainnet.

**System info (please complete the following information):**
- OS Name: Amazon Linux 2
- OS Version 2
- Node version (output of `cardano-node --version`): cardano-node 1.29.0 - linux-x86_64 - ghc-8.10
git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2
- CLI version  (output of `cardano-cli --version`): cardano-cli 1.29.0 - linux-x86_64 - ghc-8.10

**Screenshots and attachments**
n/a

**Additional context**
I couldn't find any Dockerfile to see what the command actually is (e.g. the entrypoint command).

**Comment by knicholes** [comment]
Perhaps I was mistaken.  Upon reading the [README ](https://github.com/input-output-hk/cardano-node#configuration-yaml-files)again, I'm seeing this

Configuration .yaml files
The --config flag points to a .yaml file that is responsible to configuring the logging & other important settings for the node. E.g. see the Byron mainnet configuration in this configuration.yaml. Some of the more important settings are as follows:

Protocol: RealPBFT -- Protocol the node will execute
RequiresNetworkMagic: RequiresNoMagic -- Used to distinguish between mainnet (RequiresNoMagic) and testnets (RequiresMagic)

Maybe I need to try using this --config flag and pointing to a a modified file to point to the testnet.

**Comment by knicholes** [comment]
Actually, just passing `-e NETWORK=testnet` worked.  If I look at the logs in the startup, it says that it's using the testnet and gives the testnet-magic param correctly in the logs.  I'm not sure what my problem was earlier!

**Comment by knicholes** [comment]
Closing, as my use case was user error, but others agree that a transparent dockerfile would be huge.

**Comment by knicholes** [comment]
Oops, nope.  I was able to do the -e NETWORK=testnet, but when I tried to add in the params, that's where the error occurred.  Sorry for the confusion.  Still an issue.

**Comment by knicholes** [comment]
Maybe it was because I was using the command `run` instead of just passing the params.  Now I have this command that is giving the error "Invalid option '--topology'"

docker run -e NETWORK=testnet --name=cardano-node -v cardano-node-ipc:/ipc -v cardano-node-data:/data inputoutput/cardano-node --topology /data/testnet-topology.json --shelley-kes-key /data/kes.skey --shelley-vrf-key /data/vrf.skey --shelley-operational-certificate /data/node.cert --topology /data/testnet-topology.json

**Comment by regel** [comment]
#3134

**Comment by magick93** [comment]
See also https://github.com/input-output-hk/cardano-node/issues/3256

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
