### ISSUE TITLE
Fix `./scripts/shelley-testnet.sh`

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#325]
Node 0 returns an error:
```
cardano-node: NoDbMarkerAndNotEmpty "./db-0/protocolMagicId"
```
even when there's no `db-0` on startup.

**Comment by Jimbo4350** [comment]
@coot this is strange, `./scripts/shelley-testnet.sh` works locally for me. We really need to get all the scripts in CI.

**Comment by deepfire** [comment]
@coot, I'd be interested if you could reproduce this with #396 (which will probably by merged by the time you'll return).

**Comment by coot** [comment]
It does not crash any more.  The nodes report that they are connected to `0` peers, chain density is around `30%` - which is strange.  But the `chairman` shows that they agree on the chain, so we can close this issue.

@CodiePP are you know why the number of connected nodes is `0`?

There used to be the current tip hash - I found it useful.

**Comment by CodiePP** [comment]
> are you know why the number of connected nodes is `0`?

this count is from a traced message: the list of connected peers. I suppose that the tracer is muted or the message filtered out by its severity. This could be changed in the configuration.

**Comment by CodiePP** [comment]
> chain density is around `30%` - which is strange

indeed, this is strange and merits some investigation.

**Comment by coot** [comment]
@CodiePP please open issues for these two things, so they are not forgotten.

**Comment by CodiePP** [comment]
reopened so we can further investigate:
* why the number of connected peers stays 0
* why the chain density is low (~ 30%)

**Comment by oneEdoubleD** [comment]
This is no longer an issue.
