### ISSUE TITLE
[BUG] TraceChainSyncHeaderServer config value is ignored

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/cardano-node#3251]
*External* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
some config file tracer settings seems not having any effect on the logged lines.
this results in a huge amount of two tracers logged 

```
66851 "ChainSyncServerEvent.TraceChainSyncRollForward"
66768 "ChainSyncServerEvent.TraceChainSyncServerRead.AddBlock"
   234 null
   234 "TraceStartLeadershipCheck"
    84 "ChainSyncServerEvent.TraceChainSyncServerReadBlocked.AddBlock"
    34 "ErrorPolicyTrace"
    14 "ChainSyncServerEvent.TraceChainSyncServerRead.RollBack"
    12 "TraceMempoolRejectedTx"
     8 "TraceAddBlockEvent.AddedToCurrentChain"
     4 "TraceMempoolAddedTx"
     3 "TraceMempoolRemoveTxs"
     3 "TraceLedgerEvent.TookSnapshot"
     1 "LogValue"
```

**Steps to reproduce**
1. set `TraceChainSyncHeaderServer` and/or `TraceChainSyncBlockServer` to false
2. restart the node
3. watch out for `ChainSyncServerEvent.TraceChainSyncRollForward` and `ChainSyncServerEvent.TraceChainSyncServerRead.AddBlock` log lines

**Expected behavior**
allow tracer settings resulting in small focused log files, without thousands of repetitive debug-level content

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 
`cardano-node 1.30.0 - linux-x86_64 - ghc-8.10
git rev 55a30aba3afbfda9576e22c00a95c7106861e458`

**Comment by karknu** [comment]
The config value `TraceChainSyncHeaderServer` should be checked at https://github.com/input-output-hk/cardano-node/blob/ed7fdbf65f40f8e194850b87dd8c631fe26154e6/cardano-node/src/Cardano/Tracing/Tracers.hs#L539-L542
