### ISSUE TITLE
[BUG] - NETWORK=mainnet  not working as expected

### ISSUE THREAD

**Issue by magick93** [input-output-hk/cardano-node#3256]
*External*   otherwise.

*Other*   Docker image

**Summary**

Docker image takes an environment variable of `NETWORK=mainnet `.
As the name would suggest, I expected this would set the network.

Actually, it determines what config file will be used. This config file does set the network, but also many other things. For example, I want to be able to have an externally hosted prometheus call the cardano node. This requires tweaking the config file. I do not expect that setting which network effect this setting. Eventually I discovered the network environment variable is a hardcoding of which embedded config file to use. 

I expected I could specify my own, customized, config file, and the specific network value would be overrided by the environment variable `Network`.

**Steps to reproduce**
The following is for deploying into Kubernetes

1. create a statefulset that runs the `cardano-node` image, and the following specifies the config

```yaml
            - name: config-volume
              mountPath: /opt/cardano/config/mainnet-config.json
              subPath: mainnet-config.json

```

2. Also include the environment variable of NETWORK=`mainnet`

The result is, this config is completely ignored due to the use of the environment file. 

**Expected behavior**

- Expect environment variable of `Network` to set the network, not the config file.
- Expect I can specify my own config file, without having to spend time figuring out what bizarrely named config files are in use - see https://github.com/input-output-hk/cardano-node/issues/3238 - currently this requires spinning up the container and navigating through the file system, reading scripts and eventually locating what config file are used, for example, `/nix/store/6f4w82cdkdxvs35pljplyd7hv61b5hdf-cardano-node-mainnet/bin/cardano-node-mainnet`. 
- I'm assuming, because this file path is so random, it will likely change every time a new image is built, which will mean it will make any kind of automated overriding of files near impossible.

***Additional context**

I also tried to add all config files into the container as configmaps. This would have likely solved the problem, but `mainnet-byron-genesis.json` is 1.1mb, and this resulted in:

`Error: create: failed to create: Secret "sh.helm.release.v1.cardano-submit-api.v1" is invalid: data: Too long: must have at most 1048576 bytes`

I also tried to `kubectl cp` files into the container, but as the container doesnt have `tar` this also doesnt work.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
