### ISSUE TITLE
The updater file is missing! ubuntu 20.04 server install 4.3.1 issues

### ISSUE THREAD

**Issue by mahalamobile** [input-output-hk/cardano-node#3259]
The updater file is missing!

i have the following bin 
daedalus-4.3.1-mainnet-18992.bin

i then change the rights
 chmod +x ./daedalus-4.3.1-mainnet-18992.bin

when i run 

[launcher:Error:9] [2021-09-28 13:40:43.54 UTC] The updater file is missing!
[launcher:Notice:9] [2021-09-28 13:40:43.54 UTC] Starting the wallet with arguments: WalletArguments {getWalletArguments = []}
/nix/store/kl6lr3czkbnr6m5crcy8ffwfzbj8a22i-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
/nix/store/kl6lr3czkbnr6m5crcy8ffwfzbj8a22i-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>

(electron:71837): Gtk-WARNING **: 13:40:44.910: cannot open display:
[launcher:Notice:9] [2021-09-28 13:40:45.29 UTC] Wallet exited with exitcode: ExitFailure 1
[launcher:Notice:9] [2021-09-28 13:40:45.29 UTC] Daedalus exited with ExitFailure 1, will shutdown cardano-launcher

any help?
thanks

**Comment by Jimbo4350** [comment]
Please move this issue to https://github.com/input-output-hk/daedalus
