### ISSUE TITLE
[BUG] - No logging during initial block store validation

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#3281]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Initial startup logging

**Summary**

During initial block store validation (e.g. after non-graceful shutdown) there is a prolonged period of no log messages. This may last for > 30min during which the user is left wondering what the node is doing and whether it is ever going to start up.

Here we see 50min of no messages...

```
[bprod:cardano.node.ip-producers:Notice:7] [2021-10-08 15:00:25.12 UTC] IPSubscriptionTarget {ispIps = [], ispValency = 0}
[bprod:cardano.node.ChainDB:Info:7] [2021-10-08 15:50:25.99 UTC] Opened imm db with immutable tip at 77679f4f693bffb342c81aefbe22d8654dcf6d5c0ffb02addf3e57890f62a799 at slot 42094911 and chunk 1948
[bprod:cardano.node.ChainDB:Info:7] [2021-10-08 15:50:34.92 UTC] Opened vol db
```

**Steps to reproduce**

Kill the process and start it again, which AFAIU forces full block store validation.

**Expected behavior**

Some progress messages during that period.

**System info (please complete the following information):**

1.30.1

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
