### ISSUE TITLE
[BUG] - cardano-cli / Inconsistencies with datum and redeemer serialization/hashes between `xxxx-file`  and `xxxx-value` options

### ISSUE THREAD

**Issue by nhenin** [input-output-hk/cardano-node#3289]
**Internal/External**
*External* f: I'm working at smart-chain .

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).
*Cardano-cli* 

**Summary**
Context : I'm trying to run the vesting contract (from plutus-uses-cases) using directly cardano-cli/api while waiting for the PAB to come.... redeemer and datum in that contract are `()` and I realised the validator was failing when trying to deserialized the datum and the redeemer I provided....

Observation : Using `cardano-cli` for a same value passed via `xxx-value` or `xxx-file` we obtain different hash results. I'll provide the steps to reproduce below

**Steps to reproduce**

```shell

nhenin@ubuntu ~/.tokenomia-cli> cat emptyValue.json 
{"constructor":0,"fields":[]}

nhenin@ubuntu ~/.tokenomia-cli [1]> cardano-cli transaction hash-script-data --script-data-file emptyValue.json 
923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec

nhenin@ubuntu ~/.tokenomia-cli> cardano-cli transaction hash-script-data --script-data-value "{\"constructor\":0,\"fields\":[]}"
e91e9c37cad5a5215f210776134143165a4c438a46cc0d82e5111611805c3864

nhenin@ubuntu ~/.tokenomia-cli> cardano-cli transaction hash-script-data --script-data-value '{"constructor":0,"fields":[]}'
e91e9c37cad5a5215f210776134143165a4c438a46cc0d82e5111611805c3864
```
**Expected behavior**
Hashes should be the same and the right one... I believe the behaviour from `--script-data-value ` is not the one expected/used around the validator.... I can unspent my utxos by using `xxx-file` but not using `xxxx-value`
I believe also it's the same issue when using `cardano-cli transaction build` with the options  `--tx-in-redeemer-value` and `--tx-in-datum-value` 

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version :  20.04
- Node version (output of `cardano-node --version`)
cardano-node 1.30.0 - linux-x86_64 - ghc-8.10
git rev e0fd8158d1c9b93fa1a74e869a45f9baf7b0e45a
- CLI version  (output of `cardano-cli --version`)
cardano-cli 1.30.0 - linux-x86_64 - ghc-8.10
git rev e0fd8158d1c9b93fa1a74e869a45f9baf7b0e45a

**Comment by james-iohk** [comment]
@nhenin These two cli options serve different purposes and interpret the values provided differently too. The `file` option is the only way to invoke data constructor. The `value` option is good for simple values like an integer, or for defining script data like you would a record type in haskell code.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
