### ISSUE TITLE
[BUG] - Provide more helpful error messages

### ISSUE THREAD

**Issue by arielelkin** [input-output-hk/cardano-node#3293]
## Internal/External
*External*  

## Area
*Other*  

## Summary
This is some sample output of cardano-node:
```
[cardano-:cardano.node.DnsSubscription:Warning:63] [2021-10-13 03:09:08.20 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions
[cardano-:cardano.node.DnsSubscription:Error:569] [2021-10-13 03:09:08.85 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 18.132.238.21:3001 HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))
[cardano-:cardano.node.ErrorPolicy:Warning:61] [2021-10-13 03:09:08.85 UTC] IP 18.132.238.21:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))))) 200s 200s
[cardano-:cardano.node.DnsSubscription:Notice:588] [2021-10-13 03:09:17.99 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 18.132.238.21:3001
[cardano-:cardano.node.DnsSubscription:Notice:588] [2021-10-13 03:09:18.13 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt End, destination 18.132.238.21:3001 outcome: ConnectSuccess
[cardano-:cardano.node.DnsSubscription:Warning:63] [2021-10-13 03:09:18.13 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions
[cardano-:cardano.node.DnsSubscription:Error:588] [2021-10-13 03:09:18.81 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 18.132.238.21:3001 HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))
[cardano-:cardano.node.ErrorPolicy:Warning:61] [2021-10-13 03:09:18.81 UTC] IP 18.132.238.21:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))))) 200s 200s
[cardano-:cardano.node.DnsSubscription:Warning:63] [2021-10-13 03:09:27.99 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions
```

This particular series of error messages were due to a hard fork of the testnet. The only way to resolve them was to update one's version of cardano-node. However, it's hardly possible to infer that from cardano-node's output, because its error messages are currently:

### Very hard to read 
* Each error message has up to 680 characters and 60 words _per line_. 
* Very confusing punctuation. e.g. `(HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) `

### Ambiguous
The root cause of the issue was using an outdated version of cardano-node, yet we read:
* `DnsSubscription:Error` seems to imply DNS settings are incorrect
* `ObsoleteNodeCHAIN` seems to imply that the node downloaded something obsolete
* `HardForkEnvelopeErrFromEra` seems to imply there was a "hard fork envelope error from an era", which is anyone's guess

### Undocumented
*NONE* of the key words in the error messages are documented: https://input-output-hk.github.io/cardano-node/

As such, they tend to confuse the user, thereby thwarting debugging efforts. This GitHub issue illustrates the problem: https://github.com/input-output-hk/cardano-node/issues/3291

## Expected behaviour
cardano-node's error messages should be designed to be read, and understood by a user. As such, they should be readable, informative, concise, and documented. 

Some [best practices](https://apiguide.readthedocs.io/en/latest/principles/errors.html) for an API's error messages are as follows:

* Error messages should provide a human-readable error message that is designed to be read and understood by the user.
* Error messages should include a diagnostic message that contains technical details for use by the developers/maintainers of the application that consumes the API.
* Diagnostic messages may include links to documentation and other ‘hints’ that might assist developers resolve issues that may have resulted in the error condition.

## System info:
- OS Name: macOS
- OS Version 11.6
- Node version 
cardano-node 1.30.1 - darwin-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

- CLI version  (output of `cardano-cli --version`)
cardano-cli 1.30.1 - darwin-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

**Comment by RobertLucian** [comment]
@danbigthink so it's interesting: The release's directory name was `cardano-node-1.29.0-macos`, but when I'd check the binary's version, it would be:
```
cardano-node 1.30.1 - darwin-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f
```

Afterwards, I went here https://hydra.iohk.io/build/8031734, downloaded this version and this time it worked. Also, the release's directory name matched the binary's version this time. Just very odd. Maybe something bad happened during the release cycle of 1.29.0 that it ended up reporting as 1.30.1.

I confirm that I haven't changed a thing inside the directory and also verified with `which cardano-node` to make sure that it was really picking that binary.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
