### ISSUE TITLE
[BUG] - cardano-node doesn't resolve entries in /etc/hosts

### ISSUE THREAD

**Issue by seriru** [input-output-hk/cardano-node#3296]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   resolver

**Summary**
Using cardano-node version 1.30.1. I have put my BP node as an entry in /etc/hosts file on all the relays. On aarch64 the node successfully resolves this entry to an IP address. However, the other relays running on x86_64 (CentOS 8) are ignoring the entries in the hosts file. It looks like the x86_64 relays are using libresolv (or similar) directly instead of gethostbyname.

I get errors like `{"thread":"149","loc":null,"data":{"kind":"SubscriptionTrace","domain":"\"bp-node.xor-nand.io\"","event":"Failed to start all required subscriptions"},"sev":"Warning","env":"1.30.1:0fb43","msg":"","app":[],"host":"relay1","pid":"2079134","ns":["cardano.node.DnsSubscription"],"at":"2021-10-14T16:48:41.67Z"}`

From /etc/nsswitch.conf:
hosts:      files dns myhostname

so the resolver should look at the /etc/hosts file before resolving hostnames via DNS.

**Expected behavior**
The cardano-node process should resolve entries in /etc/hosts.

**System info (please complete the following information):**
- OS Name: [Centos]
- OS Version [8]
- Node version cardano-node 1.30.1 - linux-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

Compiled with ghc 8.10.7 and cabal 3.6.0.0. The cardano-node process is running under systemd.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
