### ISSUE TITLE
[BUG] - creating ledger snapshot uses substantial amount of memory and requires a few major garbage collects.

### ISSUE THREAD

**Issue by woltere** [input-output-hk/cardano-node#3299]
**External**

**Area**
*Other*   Ledger DB snapshot performance

**Summary**
Memory spike during writing of the ledger snapshot.

**Steps to reproduce**
Let the cardano-node run on mainnet until a ledger snapshot is created.
Look at the  `rts_gc_current_bytes_used` and `cardano_node_metrics_RTS_gcMajorNum_int`
rts_gc_current_bytes_used spikes 3 times:
   2 x ~ 1GB
   1  x ~500MB.
3 Major GC are required during save of the snapshot, and an additional 4th major GC later.

**Expected behavior**
When looking at the code `writeSnapshot` it is encoding the ledger snapshot while writing to file, I would expect very little garbage to be created.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 21.04
- Node version (output of `cardano-node --version`)

```
cardano-node 1.30.1 - linux-riscv64 - ghc-8.10
git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2
```

**Screenshots and attachments**

The memory required by the snapshot and released by major GC
![image](https://user-images.githubusercontent.com/1155513/137695096-99df09d4-f746-4dd9-9613-eaa98684d135.png)
![image](https://user-images.githubusercontent.com/1155513/137695105-b4905787-5102-4c67-ba6f-978642f0bee3.png)

**Additional context**
We can expect the ledjer snapshots to increase over time and the saving of the snapshot using up more memory/CPU resources.

**Comment by 34r7h** [comment]
https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032/37

**Comment by woltere** [comment]
> Not sure if these settings can help the same GC problem you're facing but these cardano-node flags should be tested and implemented by default for the node.
> `-T -I0 -A16m -N2 --disable-delayed-os-memory-return`
> https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032/37

My GC settings are more or less the same. The issue I am raising is not the GC settings but the fact that so many garbage is generated during the snapshot save.
When encoding the ledger into CBOR format and writing it out to disk a fixed buffer could be used. The GC pauses are the symptom here not the cause.

**Comment by soyfrien** [comment]
> Not sure if these settings can help the same GC problem you're facing but these cardano-node flags should be tested and implemented by default for the node. `-T -I0 -A16m -N2 --disable-delayed-os-memory-return` https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032/37

I think the `-N2` will actually double the threads, once too many times. It seems to use the appropriate number of threads without having that fed in. I think it has something to do with the build settings.  Check it out when you get a chance. Or Maybe I'll return when I can demonstrate the behavior.

**Comment by orpheus-antpool** [comment]
You can reduce the number of major collections by using a large pre-allocated heap (e.g. -H6g), which will reduce the frequency of GC promotions. However, according to my observations, there is also CPU intensive activity during the spikes. Therefore, if you are concerned about missed slot leader checks, major collections may not be the only cause.

**Comment by woltere** [comment]
> You can reduce the number of major collections by using a large pre-allocated heap (e.g. -H6g), which will reduce the frequency of GC promotions. However, according to my observations, there is also CPU intensive activity during the spikes. Therefore, if you are concerned about missed slot leader checks, major collections may not be the only cause.

I'm running with an even higher value. The problem is that writing snapshot produces about 2 times the snapshot size of garbage. A snapshot size varies somewhere between 900MB and 2GB.

I've got the producer down to 49 major GC pauses in 5d 20h  (it takes ~ 18 major GC's to start the node).
The point of this issue is: why the encoding and writing to file produces so much garbage.
Writes happen in blocks sized little over 32KB. I would think you could fill (CBOR encode) and write out the buffer very memory efficient.

**Comment by orpheus-antpool** [comment]
I did not have a look at the code but, well, it's Haskell, so if there are any intermediate transformations during the encoding they will produce garbage.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
