### ISSUE TITLE
[BUG] - [CardanoApi] Missing transaction signatures when evaluating Tx execution units

### ISSUE THREAD

**Issue by mesudip** [input-output-hk/cardano-node#3307]
*External (Plutus Partners)* 

**Area**
*Other*   Cardano API (Plutus related)

API function `evaluateTransactionExecutionUnits` of CardanoApi will give error `The provided Plutus code called 'error'` for scripts  that validate by checking signatures in transaction
 

**Summary**

I checked  the code. The `txbody` passed  as param is used to  created signed transaction with empty signatures, and then the plutus script is executed. Won't the script fail if it's expecting a  signature for validation? 

**Current Code** (master, 1.30.1)

```haskell
evaluateTransactionExecutionUnits
  :: forall era mode.
     EraInMode era mode
  -> SystemStart
  -> EraHistory mode
  -> ProtocolParameters
  -> UTxO era
  -> TxBody era
  -> Either TransactionValidityIntervalError
            (Map ScriptWitnessIndex (Either ScriptExecutionError ExecutionUnits))
evaluateTransactionExecutionUnits _eraInMode systemstart history pparams utxo txbody =
    case makeSignedTransaction [] txbody of --LIST OF SIGNATURES IS EMPTY ARRAY
      ByronTx {}                 -> evalPreAlonzo
      ShelleyTx era tx' ->
        case era of
          ShelleyBasedEraShelley -> evalPreAlonzo
          ShelleyBasedEraAllegra -> evalPreAlonzo
          ShelleyBasedEraMary    -> evalPreAlonzo
          ShelleyBasedEraAlonzo  -> evalAlonzo era tx'
     where 
     ...
```

**Suggestion**

 Instead of taking `TxBody` as parameter, it should accept `Tx` as parameter so that the upper layer can set the signatures.

**Comment by mikekeke** [comment]
Hi @mesudip !
Can you provide some details on how you build transaction that caused that error?
Are you using `evaluateTransactionExecutionUnits` directly?

**Comment by mesudip** [comment]
It was a while ago. 
The usecase was a withdraw transaction (withdraw from a sale contract).
Basically the withdraw was allowed by checking operator address signature. The operator just signs the tranasction without  include their utxo in the transaction.

**Comment by mikekeke** [comment]
@mesudip , another question: what do you mean by "checking signatures in transaction"? Things like [txSignedBy](https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/src/Plutus.V1.Ledger.Contexts.html#txSignedBy) and other checks involving `txInfoSignatories` of [TxInfo](https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/Plutus-V1-Ledger-Api.html#t:TxInfo)?
