### ISSUE TITLE
[BUG] - No way to inspect transaction metadata via cardano-cli.

### ISSUE THREAD

**Issue by robertwb** [input-output-hk/cardano-node#3313]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
No way to retrieve metadata via cardano-cli.

**Expected behavior**
One should be able to query the metadata (and, indeed, all other information) associated with a transaction. 

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]
- Node version (output of `cardano-node --version`)
- CLI version  (output of `cardano-cli --version`)

cardano-node 1.30.0 - darwin-x86_64 - ghc-8.10
git rev 2124712b360b37b5d590279a4674d504dd32eda5

cardano-cli 1.30.0 - darwin-x86_64 - ghc-8.10
git rev 2124712b360b37b5d590279a4674d504dd32eda5

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
