### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Pornprasert** [input-output-hk/cardano-node#3328]
Hi 

__Originally posted by @Pornprasert in https://github.com/Gizm000/Extracting-Voice-Over-Audio-from-Witcher-3/issues/4#issuecomment-955698753__

**Comment by Pornprasert** [comment]
Hi

**Comment by arthurlewisbrown** [comment]
Yes

**Comment by erikd** [comment]
Please do not waste our time.

**Comment by arthurlewisbrown** [comment]
Never waste time ... Explain issue pls ... No 😲 you just wasted something
even more valuable friend... Data... Start by looking over the code... It's
there friend, why don't you show us your way

**Comment by arthurlewisbrown** [comment]
Do not waste my mind😳

**Comment by Pornprasert** [comment]
Hi

**Comment by Pornprasert** [comment]
Hi

**Comment by Pornprasert** [comment]
Hi

**Comment by erikd** [comment]
@Pornprasert Please do not post again on this project **unless** you have a question relevant to this project.
