### ISSUE TITLE
[FR] - Documentation for using NixOS module

### ISSUE THREAD

**Issue by L-as** [input-output-hk/cardano-node#3336]
**Internal/External**
*External*

**Area**
*Other*

**Describe the feature you'd like**
Some basic documentation for importing and using the NixOS
module in a NixOS configuration.
Perhaps a section in the README or wiki.

**Describe alternatives you've considered**
Looking through the files and figuring it out myself.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
