### ISSUE TITLE
[FR] - transaction build cmd required-signer to accept keyhash

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#3338]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
Currently, the `transaction build` cmd's `--required-signer` option takes signing key file. It would be good to also allow keyhash to be used so that keys are not always exposed to the cli, e.g. for multisig.

Note: This option exists on tags 1.30.0 and 1.31.0 (not 1.30.1)

**Comment by waalge** [comment]
Is there a reason to why this wouldn't only except the pkh rather than the skey?
(ie why would I ever want to supply the skey?)

**Comment by robertwb** [comment]
I just ran into this as well; it seems for transaction building one should be able to assert what expected signatures exist, not require the signing keys (which may be performed by a separate entity).

**Comment by BlakeBrown** [comment]
+1 for this enhancement

We're currently running a dApp (www.jpg.store) where our customers use Nami wallet to sign transactions. It's impossible to get someone's signing key to construct an identical transaction in the CLI. Even if it was possible, requiring a signing key to be passed around is a huge security risk.

**Comment by jfischoff** [comment]
I have a branch that implements this implements this here: https://github.com/Canonical-LLC/cardano-node/pull/1
