### ISSUE TITLE
[BUG] - Fix and re-enable script testing in CI for Windows

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#3340]
**Area**
Plutus/Testing

**Summary**
Fix and re-enable script testing in CI for Windows.  Currently works in local VM but not in CI.

For example: https://github.com/input-output-hk/cardano-node/pull/3334#discussion_r741960924

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
