### ISSUE TITLE
[BUG] - queryTip breaks with MuxError (writev/recv) failure still exists in 1.30.1

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#3341]
The issue that was marked as solved is not solved in 1.30.1, please reopen
https://github.com/input-output-hk/cardano-node/issues/3042

We still see broken mux/pipe errors with the latest release 1.30.1 here.

**Comment by dorin100** [comment]
this should be fixed in the next release - `1.31.0` - https://github.com/input-output-hk/cardano-node/issues/3042#issuecomment-960553159

**Comment by gitmachtl** [comment]
yes, looking promising: https://github.com/input-output-hk/cardano-node/issues/3042#issuecomment-960562013

**Comment by dorin100** [comment]
can we close this ticket?

**Comment by gitmachtl** [comment]
> can we close this ticket?

yes.
