### ISSUE TITLE
[BUG] - Error compiling node v1.31.0 on Raspberry pi4B 8Gb

### ISSUE THREAD

**Issue by johnnuy** [input-output-hk/cardano-node#3344]
**Area**
Building the node

**Summary**
I am getting an error during the build for teh trace-dispatcher when building node 1.31.0 for my raspberry pi relay nodes.  

[ 9 of 14] Compiling Cardano.Logging.Tracer.Standard ( src/Cardano/Logging/Tracer/Standard.hs, /home/ubuntu/src/cardano-node/dist-newstyle/build/aarch64-linux/ghc-8.10.7/trace-dispatcher-1.29.0/build/Cardano/Logging/Tracer/Standard.o, /home/ubuntu/src/cardano-node/dist-newstyle/build/aarch64-linux/ghc-8.10.7/trace-dispatcher-1.29.0/build/Cardano/Logging/Tracer/Standard.dyn_o )

src/Cardano/Logging/Tracer/Standard.hs:9:1: error: [-Wdeprecations, -Werror=deprecations]
    Module ‘Control.Concurrent.Chan.Unagi.Bounded’:
      This library is unlikely to perform well on architectures without a fetch-and-add instruction
  |
9 | import           Control.Concurrent.Chan.Unagi.Bounded
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Cardano/Logging/Tracer/Standard.hs:73:26: error: [-Wdeprecations, -Werror=deprecations]
    In the use of ‘newChan’
    (imported from Control.Concurrent.Chan.Unagi.Bounded):
    "This library is unlikely to perform well on architectures without a fetch-and-add instruction"
   |
73 |     (inChan, outChan) <- newChan 2048
   |                          ^^^^^^^
cabal: Failed to build trace-dispatcher-1.29.0 (which is required by
test:trace-dispatcher-test from trace-dispatcher-1.29.0 and
exe:trace-dispatcher-examples from trace-dispatcher-1.29.0).

**Steps to reproduce**
1) Check out the 1.31.1 tag
2) Configure build as normal
3) run cabal build all  (or simply cabal build trace-dispatcher)

**Expected behavior**
This should compile and produce binaries.

**System info (please complete the following information):**
- OS Name: Ubuntu on Raspberry pi 4B 8Gb
- OS Version 20.04
- Node version 1.31.0

**Additional context**
I understand that raspberry pi4 architecture is not officially supported, but I also understand like myself there is a large number of SPO's running on raspberry pi4, so if this is indeed a breaking change that requires hardware upgrades this needs to be effectively communicated to anyone who is currently running pi4.

**Comment by angerman** [comment]
For some reason `unagi-chan` has
```
  if !arch(i386) && !arch(x86_64)
    cpp-options: -DNOT_x86
 ```
 in the cabal file, and then various code snippets like the following:
 ```
 #ifdef NOT_x86
    {-# WARNING "This library is unlikely to perform well on architectures without a fetch-and-add instruction" #-}
#endif
```
I can't find actual code doing fetch-and-add instructions directly in unagi-chan, and have to assume this is due to the `atomic-primop` package, which also doesn't seem to really restrict itself to x86 only either. It has some C code which it claims is only necessary for some fairly old GHC versions, yet keeps including that code for windows.

The whole primop logic (and yes we have fences and cmpxch instructions) feels fairly odd. It appears as if this should be safe to just strip unagi-chan of the warnings and the odd cabal logic.

**Comment by johnnuy** [comment]
Updated the ghc-options for the trace-dispatcher to -Wwarn and it compiled, I'm running the new node now on testnet for both relay and core, will see if there's any negative performance

**Comment by angerman** [comment]
I'm fairly certain this is a bug in unagi-chan.
See https://github.com/jberryman/unagi-chan/issues/42

**Comment by LindenMikus** [comment]
I'm not sure why this is closed? It does appear that its a bug in the unagi-chan library but there was no PR opened for them in relation to running on pi
