### ISSUE TITLE
[FR] - Make `cardano-cli build` automatically balance non-Ada assets - or add a cmdline option to make that happen

### ISSUE THREAD

**Issue by kieransimkin** [input-output-hk/cardano-node#3364]
See this thread:
https://github.com/input-output-hk/cardano-node/issues/3030

Cardano-cli only automatically balances Ada, and throws an error if you use it on a UTXO containing non-Ada tokens.

I don't really understand why this is deliberate - I would expect it to either balance everything or nothing - balancing just the Ada seems like a bug to me. Even if we weren't dealing with non-Ada tokens, I'd still expect to be able to take Ada from a UTXO containing other tokens and have those tokens balanced back into the change address - not doing that is just broken IMHO. 

I understand you may not want to change existing behaviour, but can we at least have an additional command-line flag to enable balancing the non-Ada tokens as well?

**Comment by dorin100** [comment]
we are tracking it here - https://github.com/input-output-hk/cardano-node/issues/3068

**Comment by james-iohk** [comment]
closing as duplicate
