### ISSUE TITLE
[FR] - Allow outbound producer connections over SOCKS5

### ISSUE THREAD

**Issue by weebl2000** [input-output-hk/cardano-node#3368]
**Internal/External**
*External*

**Area**
*Other*   Networking

**Describe the feature you'd like**
Currently, when running cardano-node with a DNS Subscription for peers, it will resolve the IP addresses and then try to connect. It would be cool if it's also possible to configure a SOCKS5 proxy to use for connecting to remote hosts. The use case for this is connecting to a cardano-node producer over for example Tor's onion network. This would make Cardano very censorship resistant for fully paranoid or those who want to stay truly anonymous.

**Describe alternatives you've considered**
There is none, it requires code changes to connect to .onion addresses.

**Additional context / screenshots**
Just wondering if there is any interest for this. I'd be able to work on it - but better to gauge the interest for this feature first.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by weebl2000** [comment]
> Closing this. If this is still relevant please reopen.

I don't have rights to reopen issues. Would be cool if people share their thoughts on this. It would support running cardano-node over for example Tor proxies.

**Comment by Jimbo4350** [comment]
cc: @coot

**Comment by njd42** [comment]
This has two aspects:

### Performance

Tor is dramatically less performant that direct connections; it would not be suitable for connecting SPO's relays or block producing nodes to the rest of the network as the additional delay would dramatically increase the produced blocks exposure to timing races ('height battles').

From a performance perspective, a user wallet node (e.g. Daedalus) could be connected this way, however:

### Anonymity

Note this is not privacy - once 'the user' of an (wallet) address is known it is possible to track how the funds moved. Also note that staking addresses are per wallet; 
The best that can be hoped for is to not identify a given transaction with a given source IP address. 

Tor only gives potentially some level of anonymity (see http://www.cs.lewisu.edu/mathcs/msisprojects/papers/Tor_DavidGingerich.pdf for discussion, https://apps.dtic.mil/sti/citations/ADA465464 for more details). 

Pattern analysis is also possible https://mice.cs.columbia.edu/getTechreport.php?format=pdf&techreportID=1545 - there they claim 81% effectiveness at anonymisation based on flow records.

It should be noted that the traffic patterns of Cardano are (compared to other network traffic) very infrequent, very bursty and submitted txs would have characteristic sizes (e.g see TOR encrypted packet leaving user - look to ledger to see what size of tx that corresponds to in blocks). This means that there is not a lot of 'entropy' to hide behind, get a good match means (see above) any pre-existing privacy will be gone.

Using TOR would not seem to give any (long term) protection against de-anonymisation; it may well be a very good way of ensuring that interest is taken by various authorities (https://phys.org/news/2014-07-tor-cops.html)

Causing the wallet to use `.onion` addresses is already possible by editing the configuration file - so it doesn't need any code changes - but it would not seem to gain people much, except attention.

Does this help? I'm going to close this for the moment - comment if you want it reopened, but there is not much more to say.

**Comment by weebl2000** [comment]
> 

Thanks for weighing in. I will re-test if onion addresses work in the topology files. When I opened this issue it did not work because it tries to resolve the addresses before connecting.
