### ISSUE TITLE
[FR] - expose running node version

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/cardano-node#3371]
**External**

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

EKG currently returns data like 

```
{
  "iohk-monitoring version": {
    "val": "0.1.10.1",
    "type": "l"
  },
  "cardano": {
    "node": {
      "metrics": { ...
   }
}
```

would it be possible to include a `cardano.node.running.version` to this EKG data?

and/or a cli command like `cardano-cli node runningversion` or `cardano-cli query nodeversion`

Third party tools using data exposed by the node could use theversion number to ensure they are compatible.

**Comment by 2072** [comment]
It is already there: `cardano.node.basicInfo.version` (I've been using it since quite some time):

![image](https://user-images.githubusercontent.com/22638/144024653-115be4e8-63e0-4816-a540-8605eb183dbf.png)

**Comment by gufmar** [comment]
> It is already there: `cardano.node.basicInfo.version` (I've been using it since quite some time):

interesting. I can't see .cardano.node.basicInfo on any of my nodes. 
I also tried to restart a node with all possible Trace... options set to true.

**Comment by CarlosLopezDeLara** [comment]
Fixed by https://github.com/input-output-hk/cardano-node/pull/3676
Included in https://github.com/input-output-hk/cardano-node/releases/tag/1.34.1
