### ISSUE TITLE
[BUG] - RAM usage increases steadily

### ISSUE THREAD

**Issue by CherryDT** [input-output-hk/cardano-node#3376]
**Internal/External**
*External*.

**Area**
*Other*

**Summary**
See https://github.com/input-output-hk/daedalus/issues/2734 for how I discovered this.

I have a ThinkPad T14s 1st Gen laptop with 32 GB RAM and Windows 10. I'm experiencing this problem when using Daedalus, but it seems it's an issue in the node itself, that's why I'm opening this issue here.

I discovered two issues with the release of Daedalus 4.5.0:

* After a while the node would crash with `heap exhausted`. After patching `-M6553M` to `-M10000M` that seemed solved at first.
* At random intervals, RAM usage increases by 1 GB.

Several  different configuration options were helpfully suggested in the other thread, but none of these solved it (some seemed to have slowed it down or converted jumps to ramps, but still):

* `-I0 -w`
* `+RTS -N2 -w -A128m -n1m -I0.3 -Iw300 -O3500m -I0 -RTS`
* `+RTS -N2 -w -A64m -n1m -I0.3 -Iw600 --disable-delayed-os-memory-return -RTS`

**Steps to reproduce**
1. Have a similar system configuration to mine, I guess
2. Start Daedalus and wait
3. Monitor cardano-node.exe's RAM usage

**Expected behavior**
No ever-increasing RAM usage

**System info (please complete the following information):**
- OS Name: Windows
- OS Version 10.19043.1288
- Node version cardano-node 1.30.1 - mingw32-x86_64 - ghc-8.10
- CLI version  cardano-cli 1.30.1 - mingw32-x86_64 - ghc-8.10

**Screenshots and attachments**

* `-H4G -M6553M -c70` (the default):
```
[CHE-T14S:cardano.node.DnsSubscription:Error:72] [2021-11-19 12:09:19.48 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.159.46.171:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = "SubscriptionWorker exiting", seStack = []}
[CHE-T14S:cardano.node.DiffusionInitializationTracer:Info:18] [2021-11-19 12:09:19.85 UTC] DiffusionErrored AsyncCancelled
cardano-node: Heap exhausted;
cardano-node: Current maximum heap size is 6871318528 bytes (6553 MB).
cardano-node: Use `+RTS -M<size>' to increase it.
```

* `-H4G -M10000M -c70` after ~15 minutes:
![image](https://user-images.githubusercontent.com/6010463/142640192-2838e199-9de3-4fe0-b04d-5c374062c744.png)
(immediately after this screenshot it went further and reached 9 GB, and at 10 GB it crashed)

* `-I0 -w` after ~12 minutes:
![image](https://user-images.githubusercontent.com/6010463/142640514-20736763-9ef3-4350-8c5a-9f8c6f22a751.png)

* `-N2 -w -A128m -n1m -I0.3 -Iw300 -O3500m -I0` after ~18 minutes:
![image](https://user-images.githubusercontent.com/6010463/142640706-8d6ed8d6-5630-4478-a1c3-1e125085684c.png)

* `-N2 -w -A64m -n1m -I0.3 -Iw600 --disable-delayed-os-memory-return` after ~32 minutes:
![image](https://user-images.githubusercontent.com/6010463/142643337-b5d1a1a6-5c93-4b47-8440-58fd86ec0678.png)
...and after 50 minutes...:
![image](https://user-images.githubusercontent.com/6010463/142648944-013a9df6-2f89-42dc-a987-8b549deab800.png)

Most of the memory seems to be not actively used, it can be paged out (only ~3 GB are immediately paged back in), but it's still a problem because my virtual memory isn't infinite either, and of course with the default settings (that any user not tweaking things in transpiled JS code would get) it crashes entirely.

**Comment by orpheus-antpool** [comment]
GHC 9.2.1 introduces several RTS optimizations, in particular with respect to parallel garbage collection and the ability release unused heap back to the OS. Perhaps a lot of these issues can be mitigated by simply refactoring the code to compile with GHC 9.2.1 (the language changes don't look that disruptive).

**Comment by dorin100** [comment]
Hi @CherryDT. Is this issue still relevant on the latest release - 1.35.3?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
