### ISSUE TITLE
[FR] - Implement a Posix signal to trigger a major Garbage Collection from the outside

### ISSUE THREAD

**Issue by 2072** [input-output-hk/cardano-node#3394]
**External**

**Area**
*Other*   Any other topic (memory management).

**Describe the feature you'd like**
Implement a Posix signal to trigger a major garbage collection (`performMajorGC`) from an outside process.
Similarly to the topology configuration update with the `SIGHUP` signal (as explained in [master/doc understanding-config-files.md](https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/understanding-config-files.md#understanding-your-configuration-files-and-how-to-use-them) but apparently not working on 1.33.0).

Currently there is no internal call to PerformGC leaving garbage collection to the RTS which can possibly trigger when a block is due causing the block to be missed if the major garbage collection takes longer than 1s.

[I have found that using the `-O` RTS flag](https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032/72?u=_2072) we can delay the garbage collection until a certain limit of live data is reached but then the recurring snapshot occurring after 11 or 13 hours of uptime will generate about 2.5GB of garbage each 72 minutes causing this limit to be reached randomly which will eventually cause a major GC at the wrong time.

**Describe alternatives you've considered**
The optimum alternative would be for the node to take control of its garbage collection:
- Know, at least one minute ahead of time that a block is to be produced
- Call performMajorGC when it's safe (no block is due in the next minute)
- Delay a snapshot if a block is due

In the node management software I've been building since more than a year now, I've introduce the notion of 'Near Sensitive Slot' which is a flag that is set automatically when a block is to be produced. When this flag is set (1 hour before the slot until 15 minutes after), automatic node restarts in the cluster are prevented for example. I think that you could implement a similar thing to prevent cardano-node doing maintenance tasks (such as the snapshot, or garbage collection) at the wrong time.
But for now, implementing a signal to collect the garbage would be a very nice simple alternative...

**Additional context / screenshots**

I'm doing many experiments with the RTS settings that I'm documenting in [this thread](https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/) on the Cardano forum:

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
