### ISSUE TITLE
[BUG] - Can no longer build cardano-node on arm64

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#3395]
**Internal/External**
*External*   otherwise.

**Area**
*Build/Compile*  

**Summary**

We used to be able to build the cardano node on arm64 with ...

* cabal-3.4.0.0
* ghc-8.10.4

Now, we are seeing this build failure ...

```
[ 9 of 14] Compiling Cardano.Logging.Tracer.Standard ( src/Cardano/Logging/Tracer/Standard.hs, /src/cardano-node/dist-newstyle/build/aarch64-linux/ghc-8.10.4/trace-dispatcher-1.29.0/build/Cardano/Logging/Tracer/Standard.o, /src/cardano-node/dist-newstyle/build/aarch64-linux/ghc-8.10.4/trace-dispatcher-1.29.0/build/Cardano/Logging/Tracer/Standard.dyn_o )
src/Cardano/Logging/Tracer/Standard.hs:9:1: error: [-Wdeprecations, -Werror=deprecations]
    Module `Control.Concurrent.Chan.Unagi.Bounded':
      This library is unlikely to perform well on architectures without a fetch-and-add instruction
  |
9 | import           Control.Concurrent.Chan.Unagi.Bounded
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Cardano/Logging/Tracer/Standard.hs:73:26: error: [-Wdeprecations, -Werror=deprecations]
    In the use of `newChan'
    (imported from Control.Concurrent.Chan.Unagi.Bounded):
    "This library is unlikely to perform well on architectures without a fetch-and-add instruction"
   |
73 |     (inChan, outChan) <- newChan 2048
   |                          ^^^^^^^
```

**Comment by tdiesler** [comment]
Kudos to @pascallapointe fixed like this ...

https://github.com/tdiesler/nessus-cardano/blob/main/nix/cardano/Dockerfile#L96

![image](https://user-images.githubusercontent.com/244946/143827062-9762f50e-2d93-48f6-86f2-0c2964f65a1e.png)

Please close when this is a valid fix/workaround

**Comment by newhoggy** [comment]
What instructions are you following to build `cardano-node`?  I'll make sure to update them.

**Comment by newhoggy** [comment]
I can confirm @tdiesler's suggestion works on my M1.

**Comment by newhoggy** [comment]
Properly fixing the bug requires patching up upstream dependency: https://github.com/jberryman/unagi-chan/pull/43

**Comment by newhoggy** [comment]
I've verified the work around is no longer required on `master`.

Closing.
