### ISSUE TITLE
[FR] - Show percentage of blocks synchronised

### ISSUE THREAD

**Issue by L-as** [input-output-hk/cardano-node#3396]
**Internal/External**
*External*

**Area**
*Other*

**Describe the feature you'd like**
It would be nice if the node would tell you how many % are synchronised, or in some other way tell you how much is left to synchronised.

**Comment by dorin100** [comment]
this functionality is already available --> `syncProgress`:
```
$ cardano-cli query tip \
>     --testnet-magic $MAGIC
{
    "epoch": 171,
    "hash": "1c8efe7a7be2ddefe01e08cd18d107f9e086ae414db0b675e984d404267da54a",
    "slot": 43804574,
    "block": 3111880,
    "era": "Alonzo",
    "syncProgress": "100.00"
}
```

**Comment by L-as** [comment]
So I tried to use this, but my node isn't even producing a socket at the socket path. Perhaps it's because it's still in some initialisation phase?

**Comment by L-as** [comment]
Indeed, the socket has appeared now.

I think we should display this information along with the usual information logged by the node when synchronising.

**Comment by dorin100** [comment]
>I think we should display this information along with the usual information logged by the node when synchronising.

please open a separate feature request for this.
