### ISSUE TITLE
[BUG] - Initialisation is extremely slow

### ISSUE THREAD

**Issue by L-as** [input-output-hk/cardano-node#3401]
**Internal/External**
*External*

**Area**
*Other*

**Summary**
After running `cardano-node` using the default configuration from 5b5310988c7c0500897bacb5555f3334d89f4aa1, there is a **very** long period before `cardano-cli` becomes usable. It seems to be about an hour. I'm using AMD Ryzen 5 1600 with 16 GB of memory.

**Expected behavior**
Initialisation should take much less time.

**System info (please complete the following information):**
- OS Name: NixOS
- OS Version: https://github.com/NixOS/nixpkgs/tree/fbd3124b92cc7ba1b354261c9aba092d2f2b3c20
- Node version: `cardano-node 1.31.0 - linux-x86_64 - ghc-8.10 \n git rev 5b5310988c7c0500897bacb5555f3334d89f4aa1`
- CLI version: the same

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
