### ISSUE TITLE
[BUG] - About +1GB live data when started after 2.5 days in the epoch

### ISSUE THREAD

**Issue by 2072** [input-output-hk/cardano-node#3403]
**Internal/External**
*External* 

**Area**
*Other*  (Performance: memory usage and start up time).

**Summary**
When the node is (re)started around +2 days in the epoch or 2.5 days (not sure) it will take at least twice the usual time to start and will use about 1 more GB of RAM than a node started outside of this window. This usage difference will disappear near the end of the epoch (I think it is related to reward computations but I'm not sure)

**Steps to reproduce**
- Start 2 cardano-node at the same time during the first or last day of an epoch, watch their live data after a full GC
- Restart (using a clean stop with `SIGINT`) one of them after 2.5 days in the epoch, check its live data after a full GC, notice the +1GB difference compared to the first node (that is still running and use much less live data - about 1GB in my observations)

**Expected behavior**
The start time of a node should not influence its memory requirements nor its startup time and should match those of a node already running.

**System info (please complete the following information):**
- OS Name: Debian
- OS Version: 10
- Node version: `cardano-node 1.31.0 - linux-x86_64 - ghc-8.10 git rev 2cbe363874d0261bc62f52185cf23ed492cf4859`
- CLI version: `cardano-cli 1.31.0 - linux-x86_64 - ghc-8.10 git rev 2cbe363874d0261bc62f52185cf23ed492cf4859`

**Additional context**

**Comment by dorin100** [comment]
Hi @2072; Is this issue reproducible with the latest node release - 1.35.3?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
