### ISSUE TITLE
Configuration files use non-existing key for TraceChainDB

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#3408]
The key should be `TraceChainDB` rather than `TraceChainDb`.  See
[ref](https://github.com/input-output-hk/cardano-node/blob/master/configuration/cardano/mainnet-config.yaml#L152).

**Comment by newhoggy** [comment]
This will require the actual mainnet change first because `mainnet-config.yaml` tracks that configuration.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by coot** [comment]
This ought to be fixed in a backward compatible way, but since new tracing system will not relay on these config values we can leave it as is.
