### ISSUE TITLE
[BUG] - Plutus script cannot unlock funds with no attached datum

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#3414]
**Internal/External**
*External*   otherwise.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**

A delegator sent some [Astor](https://astorpool.net/) tokens to our Plutus contract directly in Tx [64718…02513](https://cardanoscan.io/transaction/64718d583eefea766dda6787a844eee52d9c3e4301c39fd6eeef3ddb73402513). 

The normal/documented procedure is to send these tokens to a proxy service, which then constructs/submits the non-trivial Plutus Tx

AFAIK, these 80 ADA are now lost, because Plutus cannot release funds that have no datum hash associated with the given UTxO

```
[03-12-2021 10:41:43] INFO Query UTxO for Script
  64718d583eefea766dda6787a844eee52d9c3e4301c39fd6eeef3ddb73402513#0 value {lovelace 1444443 3f997b68b1f491c7c2f10af4e2bf9566c5d25bd61df0343065d4fe1c.Astor302 80} datum TxOutDatumNone
  ba35d7e12f80988f6f2dd36bdb7ced58501711c5b84f8e0968d7d1b2e0be686d#1 value {lovelace 168000000 3f997b68b1f491c7c2f10af4e2bf9566c5d25bd61df0343065d4fe1c.Astor296 804} datum d8a95d4a0b1cd3185fc571eb4ad1c293cdee44fbdf45400616058662b817b827
  312d07fbe8290cc541feaed2e4b030237092a55fd570c2eecaa1969e281e6e96#1 value {lovelace 901700000 3f997b68b1f491c7c2f10af4e2bf9566c5d25bd61df0343065d4fe1c.Astor302 716} datum e31b52bb6cf0017e24cfc13ede621e913565e68b364254c009335b470cfff870
```

I would assume that this is a common enough user error, which may cause lots of frustration. Can we please fix this, for example by providing a known datum value that maps to `TxOutDatumNone` - (possibly empty byte string)?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
