### ISSUE TITLE
[BUG] - Missing protocol parameters file cause submit failure with an embedded datum

### ISSUE THREAD

**Issue by gege251** [input-output-hk/cardano-node#3423]
**External**
*External*

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
When creating a tx with an embedded datum, but the protocol-params file is not applied to the `transaction build` command, the CLI builds an incorrect tx. Trying to submit this tx will fail without a helpful error message.

**Steps to reproduce**
1. Create a tx with the cli, spending to a validator address and using a datum value, but without the `--protocol-params-file` option. This step succeeds:
```
cardano-cli transaction build --alonzo-era \
  --tx-in 665b9713bd96d934b8c2a144ff27ce595ab6ddde0fd9d28e76793e76224cab26#0 \
  --tx-out $(cat script.addr)+1400000 \
  --tx-out-datum-embed-value 11 \
  --testnet-magic $TM \
  --change-address $(cat user1.addr) \
  --out-file tx.raw
```
2. Sign and submit
3. Submission fails with the following error:
```
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (PPViewHashesDontMatch SNothing (SJust (SafeHash "efa4458830e13cd801c25955c834745e07f9c0b6a0b6e5fc330b7ed7824dc834")))])
```

**Expected behavior**
Tx build step should fail with an instructive error message.

**System info (please complete the following information):**
- OS Name: [darwin x86_64]
- OS Version [2.0.1]
- Node version (output of `cardano-node --version`)
```
cardano-node 1.31.0 - darwin-x86_64 - ghc-8.10
git rev be12344d84bc5bf47e716bc697adb65eac642c65
```
- CLI version  (output of `cardano-cli --version`)
```
cardano-cli 1.31.0 - darwin-x86_64 - ghc-8.10
git rev be12344d84bc5bf47e716bc697adb65eac642c65
```

**Comment by james-iohk** [comment]
Not sure if protocol params or collateral are relevant here, they are needed when building tx with script input.
Have you tried including datum hash for the datum you are embedding? `--tx-out-datum-hash`

**Comment by gege251** [comment]
I think you're right about the collateral, that was my mistake. However, even without the collaterals, this fails when submitted nonetheless.  I also tried creating a tx with exactly the same arguments as above, but with `--tx-out-datum-hash`, and in that case it builds and submits just fine, with or without pparams.

**Comment by gege251** [comment]
@james-iohk To add a bit more information I created a tx with and without pparams. I saw some differences in the CBOR file:
Without pparams:
```
[ { 0: [[h'6521E5632A035E12CCA045C9B57FFCB3456347D50AF227DA1F427BD513259DF7', 1]]
  , 13: []
  , 1: [[h'005FEB72668E5A4EFFD3B34088AA56E7D558F75AFE4798B8364A739673700E4B6993CBC5E612F8770AA531243B3D888A81C0A46DE5FA5F6A70', 888094477], [h'7067F33146617A5E61936081DB3B2117CBF59BD2123748F58AC9678656', 1400000, h'A2B621CDC65DA2D327D7BFC80C3854BA053A962A2E0D79DC7D554587E03D8294']]
  , 2: 168889
  , 14: []
  },
  { 0: [[h'096092B8515D75C2A2F75D6AA7C5191996755840E81DEAA403DBA5B690F091B6', h'72024A84296758C71441DA19ED71B9F8893A0BE76054E080254164C6A793CD351121BFAC8FAF62FED20C112A8BF064368F41117F45C8E15E6DECCDEAA69D0109']]
  , 4: [[1988, 10, 26]]}
  , true
  , null
]
```

With pparams:
```
[ { 0: [[h'6521E5632A035E12CCA045C9B57FFCB3456347D50AF227DA1F427BD513259DF7', 1]]
  , 1: [[h'005FEB72668E5A4EFFD3B34088AA56E7D558F75AFE4798B8364A739673700E4B6993CBC5E612F8770AA531243B3D888A81C0A46DE5FA5F6A70', 888086909], [h'7067F33146617A5E61936081DB3B2117CBF59BD2123748F58AC9678656', 1400000, h'A2B621CDC65DA2D327D7BFC80C3854BA053A962A2E0D79DC7D554587E03D8294']]
  , 2: 176457
  , 11: h'B67C5661624A341DD6FD8B4D91230A680698A26251699981C53AC232E5AB67EC'
  , 13: [[h'6521E5632A035E12CCA045C9B57FFCB3456347D50AF227DA1F427BD513259DF7', 0]]
  , 14: []
  }
, { 0: [[h'6EB805B5C0F9CC2490AFCC0BA58CF7698B0B9EF9DD768BC3B141B6AC5FF362CD', h'27750CA25740E535B5D018E73F03BE1A729D3A9F4ED21D20244DEF4429D1E87EEC00A966FF1742F04253EB87AC49E14F668AD4521500038A73DE81F41FF1A809']]
  , 4: [[1988, 10, 26]]}
  , true
  , null
]
```

In the latter one, the 11 field is preset (`script_data_hash`), but it is different from the datum_hash (`A2B621CDC65DA2D327D7BFC80C3854BA053A962A2E0D79DC7D554587E03D8294`)

**Comment by james-iohk** [comment]
The ScriptIntegrityHash (11) is a hash of a few things, so it being different to a single output's datum is expected.
Your second example includes collateral (13) too, was pparams definiately the only difference between the two build cmds?

**Comment by gege251** [comment]
I removed the collaterals from both txs, but I still run into the same problem. 

I still don't understand why the first variant (with pparams) has an integrity hash, while the second (w/o pparams) doesn't.
I get the same error `(PPViewHashesDontMatch SNothing (SJust (SafeHash "b67c5661624a341dd6fd8b4d91230a680698a26251699981c53ac232e5ab67ec"))` which leads me to the conclusion, that the missing script integrity hash is the problem.

**Comment by james-iohk** [comment]
> I also tried creating a tx with exactly the same arguments as above, but with `--tx-out-datum-hash`, and in that case it builds and submits just fine, with or without pparams.

I thought it submitted fine with or without pparams. Now you have this error again, what's changed?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
