### ISSUE TITLE
[BUG] query stake-distribution omits pools with no delegates

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/cardano-node#3428]
**Internal/External**
*External* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
It looks like the stake-distribution query shows only pools that have at least one delegate.

**Steps to reproduce**
1. Go to testnet `cardano-cli query stake-distribution  --testnet-magic 1097911063`
2. Pools that have no stake showed fine:
```
pool176d8dj0pg06nlqjxyqkuxr2d47sq9h5th53lqapkrfj7u9h5aec   0.000e0
```
3. However, the pools such as `pool1z75ktne7h48an926p69dp0e9ysxkaddz7qs8kvhmtyc96kf2acq` which has 0 delegators are not shown.

**Expected behavior**
Show all registered pools.

**System info (please complete the following information):**
```
 cardano-cli 1.31.0 - darwin-x86_64 - ghc-8.10
git rev 5939f8084cfdf5ec017542034d981bb75879fed6

cardano-node 1.31.0 - darwin-x86_64 - ghc-8.10
git rev 5939f8084cfdf5ec017542034d981bb75879fed6
```

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
