### ISSUE TITLE
[BUG] - Error Messages should make more sense, and only be info if info

### ISSUE THREAD

**Issue by danbigthink** [input-output-hk/cardano-node#3437]
While running a cardano relay node version 1.30.1, I started to get this error:

[cardano-:cardano.node.LocalErrorPolicy:Error:1099] [2021-12-13 17:57:39.14 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 49> closed when reading data, waiting on next header True")

This error seems to imply that my local IP address of "" closed when reading data.
This was working just fine since the release of 1.30.1. This error message is happening a lot

My configuration in pretty simply, running a relay from inputoutput/cardano-node:1.30.1

Can anybody tell me why these error messages are so obtuse, my IP LocalAddress certainly isn't ""?
I'd guess the error means that an open socket to another node closed, and if that's true how is this an error, this would happen all of the time as nodes register and unregister themselves.

Please make error messages actual error if they are, info if they're only info based errors.

**Comment by coot** [comment]
In the current implementation this error can be ignored, when the new network stack will be rolled out this will not happen unless a non-clean shutdown happens.

As of `""` local address, the qestion is on which OS are you running on?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
