### ISSUE TITLE
[BUG] - cardano-node 1.30.1 release notes technical specifications incorrect disk space

### ISSUE THREAD

**Issue by danbigthink** [input-output-hk/cardano-node#3442]
Minimum system requirements states minimum 20GB free storage.
I don't agree, my current setup is using 23GB of disk space for the db directory as of today.

I'd suggest increasing this by a bit just so it covers off the simple bits such as binaries, os, and current chain size + more than 2 weeks of transaction writes.

A slightly higher number would be safer than having someone believe 25GB is enough.
Maybe 30GB is a better minimum?
Thanks

**Comment by rdlrt** [comment]
The requirements for software is different to sizing based on network you connect to (based on it's history and type of objects).
If at all this has to change, the wordings could perhaps include a baseline for software, and a high level generic guideline for sizing. The requirements for mainnet have been gradually increasing (and will likely see a bump further soon). At the moment - the requirements map to mainnet requirements (prolly) based on what DevOps experience at the time of release for mainnet, which is more of a point-in-time requirement.

The extract on [developers.cardano.org](https://developers.cardano.org/docs/get-started/installing-cardano-node#prerequisites) uses very safe limits - as small fresh networks can prolly get away with 2GB for months

![image](https://user-images.githubusercontent.com/3169068/146279288-e7bff997-9612-4996-bb43-a0dfd1243e00.png)

**Comment by danbigthink** [comment]
> 

Thanks for this. Personally I feel this should be real world based, I run several mainnet nodes and they all take more than 20GB of storage as of last week when I checked. The greatest number of nodes are run in mainnet, correct? The note disclaimer you provided doesn't provide anything concrete. What are the typical requirements on mainnet?

Shouldn't the documentation lean towards the most common use case and not some less common possibility?

I'm finding that the documentation on anything Cardano related changes often and seems to miss the most common use case. I'm hoping the cardano projects could just become consistent so users of them know where to look for what information. Why is it like this? Isn't there a team that focuses on communication and documentation standards? 

For example, the db-sync github doesn't have hardware requirements labelled in the same way on a per release basis. How can you see what the history of it is? How do you know what performance testing has occurred?

We need Cardano and iohk to provide consistent documentation!

**Comment by dorin100** [comment]
Thank you @danbigthink; This was fixed in the last release notes.
