### ISSUE TITLE
[BUG] - If the ipv6 is disabled on the system, the node crashes on boot

### ISSUE THREAD

**Issue by danielmain** [input-output-hk/cardano-node#3449]
*Internal* 

**Steps to reproduce**
1. Disable ipv6 on Linux 
2. Start Daedalus 4.6.0
3. See the logs
4. Cardano node crashes

`[nixos:cardano.node.error:Notice:5][0m [2021-12-17 10:53:31.73 UTC] Failure while getting address information for the public listening address: Just ::1 Just 41509 : Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE,AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: Just "::1", service name: Just "41509"): does not exist (Address family for hostname not supported)
GetAddrInfoError (Just ::1) (Just 41509) Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE,AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: Just "::1", service name: Just "41509"): does not exist (Address family for hostname not supported)

cardano-node: Failure while getting address information for the public listening address: Just ::1 Just 41509 : Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE,AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: Just "::1", service name: Just "41509"): does not exist (Address family for hostname not supported)[35m[nixos:cardano.node.networkMagic:Notice:5][0m [2021-12-17 10:53:33.84 UTC] NetworkMagic 764824073`

**System info (please complete the following information):**
- OS Name: NixOS or any linux
- OS Version 21.05
- Node version: 1.30.1 - linux-x86_64 - ghc-8.10

**Comment by Julescs0** [comment]
I have discovered this error also is triggered (for same reasons) when NordVPN is installed (enabled or not) on Linix Opensuse leap 15.2 at least. Uninstalling the vpn (unfortunately) is the workaround right now! I have raised the issue with IOHK also via support but came across this finally (as had finally a hit on google for this error!). I have informed support and am updating the same solution here.

**Comment by pauljgardner** [comment]
Seeing the same problem with Ubuntu 20.04, and uninstalling NordVPN does not resolve the issue in my case.

**Comment by dorin100** [comment]
I was not able to reproduce this on Winodows 10. I disabled IPv6 and started Daedalus 4.6.0 and it started normally. I also have NordVPN installed on the same machine (it was disabled during the test).

**Comment by dorin100** [comment]
The node from this issue was started using the `--host-addr 127.0.0.1 --host-ipv6-addr ::1` parameters. If IPv6 is disabled, the node will try to validate the address provided with `--host-ipv6-addr` and it will fail.

If the node is not part of a stake pool, you can start it without the `--host-addr` and `--host-ipv6-addr` parameters. In that cases the node will use the defaults --> `node addresses:  0.0.0.0:0, [::]:0`

**Comment by igelineau** [comment]
How do you remove the ipv6 argument when using Daedalus ?

**Comment by danielmain** [comment]
This Issue will be resolved in the scope of [ADP-1334](https://input-output.atlassian.net/browse/ADP-1334)

**Comment by danielmain** [comment]
@igelineau you can try removing `--node-ipv6-listen=::1` from the cardano-launcher arguments and building Daedalus and cardano-launcher from scratch, but I would recommend you to wait until this is officially fixed

**Comment by danielmain** [comment]
Daedalus solves this here: https://github.com/input-output-hk/daedalus/pull/2839

**Comment by cihilt** [comment]
I get the same issue, 
cardano-node: Network.Socket.bind: unsupported operation (Cannot assign requested address)Node configuration: NodeConfiguration {ncNodeIPv4Addr = Just [127.0.0.1](http://127.0.0.1/?fbclid=IwAR3dE35uMgjq76uo_tLGhIQW6q-_--MxHCkV9Cz4DHclmQevi-2heazj9po), ncNodeIPv6Addr = Just ::1, ncNodePortNumber = Just 34421, ncConfigFile = "/nix/store/r75kiywk62hird8ab6xjp2mlvv339q9s-node-cfg-files/config.yaml",

How to execute daedalus-mainnet --host-addr="0.0.0.0"
when i run it, it still defaults to 127.0.0.1

**Comment by pauljgardner** [comment]
I'm using Ubuntu 20.04, first experienced the with 4.6.0, upgraded to 4.7.0 and now 4.80 and still seeing the same. Which version of Daedalus has this fix, or is there something else I should be doing?

**Comment by Titan-C** [comment]
I don't use Daedalus just the node. I'm on the Preview network with P2P enabled. If ipv6 is disabled, the node does not work. 
As explained in the comment https://github.com/input-output-hk/daedalus/pull/2839#issuecomment-1103853066
if ipv6 is disabled, the node does sync. In my case it doesn't work.
