### ISSUE TITLE
[BUG] - scriptDataFromJsonDetailedSchema doesn't include String (cardano-cli transaction hash-script-data fails for strings)

### ISSUE THREAD

**Issue by eduardoaguacate** [input-output-hk/cardano-node#3455]
**Internal/External**
*Internal*   if an IOHK staff member.
External

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).
Plutus

**Summary**
A clear and specific description of what the bug is.

`cardano-cli transaction hash-script-data --script-data-file data.json`, where `data.json` is:

```
{
  "constructor": 1,
  "fields": [
    {
      "bytes": "616263"
    },
    {
      "int": 123
    },
    {
      "string": "lol"
    }
  ]
}
```

cardano-cli fails with: 
```
Expected a single field named "int", "bytes", "string", "list" or "map".
Unexpected object field(s): {"string":"lol"}
```

**Steps to reproduce**
See summary

**Expected behavior**
It should not fail

**System info (please complete the following information):**
cardano-cli 1.30.1 - linux-x86_64 - ghc-8.10

Additional context:
https://forum.cardano.org/t/cardano-cli-script-data-file-format/89304

**Comment by ejserna** [comment]
The current workaround requires to manually convert the string to a `[Word8]` and then encoding that list to an array of `int`s for it to work

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
