### ISSUE TITLE
[BUG] - Node 1.33.0 in P2P mode does not proceed after peer selection with host-addr 127.0.0.1

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#3465]
*External* 

**Area**
Cardano-Node Peer 2 Peer 

**Summary**
Running node 1.33.0 in P2P mode and a set host-addr (listen-addr) to 127.0.0.1 does not proceed after the initial peer selection from the ledger. It just hangs - waiting.

**Steps to reproduce**
- Enable/Set all the P2P configs
- Start the node with the parameter `--host-addr 127.0.0.1` 

**Expected behavior**
The node should continue to establish connections to ledger peers also when the local host address is set to 127.0.0.1. This can be used just for a passive node, or a node that is only doing transactions, not a relay-node.

**Comment by karknu** [comment]
If you are giving the host address 127.0.0.1 it will not be able to connect to any peers in the ledger because they are not reachable over the loopback interface.

**Comment by gitmachtl** [comment]
Makes total sense yes, thx for the reply!

**Comment by andrejpodzimek** [comment]
Not to mention that the `127.0.0.1` nonsense [hurts the Internet](https://docs.google.com/document/d/1YgiM5K16mlRWwqf6DNKU3--IkmtEViyN72MADgTPcZs/preview) and is better avoided. The `localhost` address is `::1`.

**Comment by gitmachtl** [comment]
It doesn't hurt my local lan behind my firewall/router/nat. 😄
