### ISSUE TITLE
[BUG] - Link broken on DockerHub

### ISSUE THREAD

**Issue by danger89** [input-output-hk/cardano-node#3467]
**Summary**
The link to GitHub is broken in the README on DockerHub: https://hub.docker.com/r/inputoutput/cardano-node

The link goes to: https://github.com/input-output-hk/cardano-node/blob/master/nix/docker.nix (broken link)

**Expected behavior**
Well, no broken links 👍🏽 .

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
