### ISSUE TITLE
[FR] - Mention the Docker-compose file in the README

### ISSUE THREAD

**Issue by danger89** [input-output-hk/cardano-node#3468]
**Describe the feature you'd like**

Mention the docker-compose file in the [GitHub Readme](https://github.com/input-output-hk/cardano-node/blob/master/README.rst).

**Describe alternatives you've considered**
I was searching for such a file, but you just have it in your repo. However, it wasn't explain in the "Docker image" section in the readme.

**Additional context / screenshots**
![image](https://user-images.githubusercontent.com/628926/147415295-b789a90e-58ab-4200-9473-0faab2578c83.png)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
