### ISSUE TITLE
MUX SDU Timeout

### ISSUE THREAD

**Issue by akshitv1** [input-output-hk/cardano-node#3469]
*External* / *Internal*

**cardano-node**

**Summary**
While running the cardano node, i am facing this error as shown in the attachment. 
Please let me know if you need further assistance.

**Steps to reproduce**
Install Ubuntu 20.04, cardano node version 1.32.1

**Expected behavior**
I was expecting no errors while running. 

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version [e.g. 20.04]
- Node version: 1.32.1
- Hardware: 8GB Ram, aws node

**Screenshots and attachments**
![image_2021_12_22T08_27_34_657Z](https://user-images.githubusercontent.com/96408289/147473523-6aee590e-9634-4a52-8144-7abc2c0a5eeb.png)

**Comment by dorin100** [comment]
Hi @akshitv1; Is this error reproducible with the latest release - 1.35.3?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
