### ISSUE TITLE
[FR] - new flag for the CLI: --tx-in-datum-serialized

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-node#3472]
**Internal/External**
*Internal*

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
A new flag for the cardano-cli `transaction build` command, similar to `--tx-in-datum-file` and `--tx-in-datum-value`, which lets the user input a datum as CBOR. This would make it possible to spend an eUTxO from the CLI in the situation that the datum was serialized differently than the CLI. It would probably also make sense to add this flag to `transaction build-raw`, and also to create corresponding flags for transaction outputs (which would enable the ability to create eUTxOs with an alternative but valid encoding).

**Describe alternatives you've considered**
None

**Additional context / screenshots**
The [cardano-serialization-lib](https://github.com/Emurgo/cardano-serialization-lib) serializes datums differently than the CLI. There are developers who wish to use this library to create eUTxO, but who also want to use the CLI to spend the eUTxO. In general, this FR would make the CLI much better equipped to interoperate with community tools.

**Comment by newhoggy** [comment]
This is the relevant command line parser: https://github.com/input-output-hk/cardano-node/blob/1602f2b52709159a86bfb5dfe6976f6ca0959b2b/cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs#L284

**Comment by JaredCorduan** [comment]
closed by #3483 

thanks again for this awesome feature @newhoggy !
