### ISSUE TITLE
[BUG] - Error building katip-0.8.7.0

### ISSUE THREAD

**Issue by bennyguk** [input-output-hk/cardano-node#3473]
**External**

**Area**
*Other*

**Summary**
While following the instructions for installing a Cardano node from [here](https://cardano-foundation.gitbook.io/stake-pool-course/stake-pool-guide/getting-started/install-node#build-and-install-the-node) I get an error during the `cabal build all` command:

> Failed to build katip-0.8.7.0.
> Build log (
> /home/cadadmin/.cabal/logs/ghc-8.10.2/katip-0.8.7.0-865092c2dd14fc7ac7dbf6a48ebf744479503085538644917d3cb1df42c03f61.log
> ):
> Configuring library for katip-0.8.7.0..
> Preprocessing library for katip-0.8.7.0..
> Building library for katip-0.8.7.0..
> [1 of 5] Compiling Katip.Core       ( src/Katip/Core.hs, dist/build/Katip/Core.o, dist/build/Katip/Core.dyn_o )
> 
> src/Katip/Core.hs:114:74: error:
>     • No instance for (TH.Lift Text)
>         arising from the first field of ‘Namespace’ (type ‘[Text]’)
>       Possible fix:
>         use a standalone 'deriving instance' declaration,
>           so you can specify the instance context yourself
>     • When deriving the instance for (TH.Lift Namespace)
>     |
> 114 |   deriving (Eq,Show,Read,Ord,Generic,ToJSON,FromJSON,SG.Semigroup,Monoid,TH.Lift)
>     |                                                                          ^^^^^^^
> cabal: Failed to build katip-0.8.7.0 (which is required by exe:tx-generator
> from tx-generator-1.32, test:cardano-testnet-tests from cardano-testnet-1.33.0
> and others). See the build log above for details.

*(The log file contains the same details)*

**Steps to reproduce**
1. Follow the instructions to install dependencies.
2. Download, unpack, install and update Cabal.
3. Download and install GHC.
4. Install Libsodium.
5. Download the source code for cardano-node.
6. Run `cabal clean`, `cabal update` and `cabal build all`.

**System info:**
- OS Name: Ubuntu
- OS Version: 20.04.3 LTS
- Node version: N/A
- CLI version: N/A
- Cabal version: 3.2.0.0
- GHC version: 8.10.2

Thank you for your help in advance.

**Comment by bennyguk** [comment]
I'm not sure what the exact cause of this error was, but I have managed to work around the issue by adding a constraint for katip in the _cabal.project_ file:
```
constraints:
    hedgehog >= 1.0
  , bimap >= 0.4.0
  , libsystemd-journal >= 1.4.4
  , systemd >= 2.3.0
    -- systemd-2.3.0 requires at least network 3.1.1.0 but it doesn't declare
    -- that dependency
  , network >= 3.1.1.0
  , katip <= 0.8.4.0
```

Hopefully this will be useful to others.

**Comment by jon-BOBA** [comment]
@bennyguk I also ran into this issue and it was resolved by updating ghc from version 8.10.2 to version 8.10.7.

**Comment by nilscodes** [comment]
I ran the build on two different nodes and can confirm it was successful on the GHC 8.10.4 version but failed on my GHC 8.10.2 node. Will be updating GHC now :)

**Comment by bennyguk** [comment]
@jon-BOBA @nilscodes, thanks for letting me know. I will update to 8.10.2.

**Comment by pbwebdev** [comment]
Thanks for posting and all those that answered too. Ran into the same issue on one of our nodes.

**Comment by SkiLov3** [comment]
I still ran into this issue declaring cabal to use ghc 8.10.7. I will give the workaround a try.

**Comment by RJ-ADApt** [comment]
Hello there. If anyone could please provide some clarity as to the steps for the process following the edited cabal file.

**Comment by bennyguk** [comment]
Since writing about this issue I've built several more nodes and moved from the method of installing Cabal and GHC via wget as per the stake pool course instructions, to installing these components with GHCup. Much easier!

I would suggest you give GHCup a try first before editing the cabal.project file.

I hope that helps.
