### ISSUE TITLE
[FR] - Documentation: Making an Alonzo-era blockchain from scratch

### ISSUE THREAD

**Issue by NorfairKing** [input-output-hk/cardano-node#3479]
**External**

**Area**
*Other* 

**Describe the feature you'd like**
We to implement our own end-to-end testing on a private alonzo-era testnet.                      
                                                                                                     
There is a nice document for a Shelley-era blockchain here:                                      
https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/shelley-genesis.
We were hoping for a similar one for the Alonzo era.       
    
**Describe alternatives you've considered**
To figure it out ourselves.

**Additional context / screenshots**
cc @MatthewCroughan who has done a lot of digging on this topic

**Comment by rdlrt** [comment]
You can already do that now, there are already a few private networks around. See [scripts](https://github.com/input-output-hk/cardano-node/tree/master/scripts) folder for your reference

**Comment by NorfairKing** [comment]
There are a lot of scripts to choose from, and they all do a lot.
This issue is about documentation, similar to the `shelley-genesis.md` document.
It tells you how to bootstrap a network from scratch using English.
We would prefer to not have to reverse engineer large scripts and instead would like to know only what is necessary to bootstrap a minimal network.

**Comment by NorfairKing** [comment]
@rdlrt Any chance that this could be added to the roadmap? Being able to set up a private testnet is crucial for developing daps.

**Comment by rdlrt** [comment]
I use custom scripts created using mkscript as input that's fit for purpose. For any changes/inclusions on IO on their roadmaps, that's up to IO teams

**Comment by MatthewCroughan** [comment]
I've found too that the the mkfiles.sh script is the only thing worth looking at for this purpose. It is worth noting that there is a bad practice of keeping code that is not useful anymore archived in production. The main branches of the IOHK repos often contain code that is not intended to be used by anyone anymore, which means that anyone new to developing with Cardano has to spend months down rabbit holes sifting through the code, to discover what code is still useful vs what is obsolete.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
