### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by adrem1** [input-output-hk/cardano-node#3481]
*External*   otherwise.

**Area**

*Other*   node 1.33.0 building

**Summary**
I am updating node software for a stake pool operation. The cabal build ends with the following error:

Configuring library for katip-0.8.7.0..
Preprocessing library for katip-0.8.7.0..
Building library for katip-0.8.7.0..
[1 of 5] Compiling Katip.Core       ( src/Katip/Core.hs, dist/build/Katip/Core.o, dist/build/Katip/Core.dyn_o )

src/Katip/Core.hs:114:74: error:
    • No instance for (TH.Lift Text)
        arising from the first field of ‘Namespace’ (type ‘[Text]’)
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (TH.Lift Namespace)
    |
114 |   deriving (Eq,Show,Read,Ord,Generic,ToJSON,FromJSON,SG.Semigroup,Monoid,TH.Lift)
    |                                                                          ^^^^^^^
cabal: Failed to build katip-0.8.7.0 (which is required by exe:tx-generator
from tx-generator-1.32, test:cardano-testnet-tests from cardano-testnet-1.33.0
and others). See the build log above for details.

**Steps to reproduce**
1. I am running node version 1.32.1 on all relays and BP
2. compiling with ghc 8.10.2
3. cabal update
4. cabal build all

**Expected behavior**
I have never had the build fail in well over a year of updating/upgrading nodes to new releases. Could it be that I need a newer version of GHC?

**System info (please complete the following information):**
- Ubuntu
- 20.04
- currently running 1.32.1, attempting to build and update to 1.33.0 following new release
- as above

Thank you, Stef (SPO RABIT)

**Comment by rdlrt** [comment]
You're using old ghc, use 8.10.4/7 instead

**Comment by adrem1** [comment]
thank you, I am trying. Will post result here and close issue when resolved.

**Comment by adrem1** [comment]
@rdlrt,

I have tried several combinations of GHC/CABAL and the build works with the following:

-GHC 8.10.4 / CABAL 3.2.0
-GHC 8.10.7 / CABAL 3.2.0
-GHC 8.10.7 / CABAL 3.4.0

Thus far I can confirm a slight performance increase on the RAM side of things (approximately 2.5GiB less), but the boot time (after the initial replay from genesis) is still way slower than it used to be before 1.32.1 (roughly 5 minutes).

Is there a way to explicitly force the usage of multiple threads on startup?


Thank you for your time and help,

S
