### ISSUE TITLE
[BUG] - cabal: Could not resolve dependencies when installing 1.33.0 from source

### ISSUE THREAD

**Issue by AvgustinKastelic** [input-output-hk/cardano-node#3484]
**Internal/External**
*External* 

**Area**
*Installing from source*  

**Summary**
Error when installing 1.33.0 from source.

**Steps to reproduce**
1. Follow https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md/ tutorial for 1.33.0
2. Error after executing: cabal configure --with-compiler=ghc-8.10.7
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: trace-dispatcher-1.29.0 (user goal)
[__1] next goal: unagi-chan (dependency of trace-dispatcher)
[__1] rejecting: unagi-chan-0.4.1.3 (conflict: trace-dispatcher =>
unagi-chan>=0.4.1.4)
[__1] skipping: unagi-chan-0.4.1.2, unagi-chan-0.4.1.1, unagi-chan-0.4.1.0,
unagi-chan-0.4.0.0, unagi-chan-0.3.0.2, unagi-chan-0.3.0.1,
unagi-chan-0.3.0.0, unagi-chan-0.2.0.1, unagi-chan-0.2.0.0,
unagi-chan-0.1.1.0, unagi-chan-0.1.0.2, unagi-chan-0.1.0.1, unagi-chan-0.1.0.0
(has the same characteristics that caused the previous version to fail:
excluded by constraint '>=0.4.1.4' from 'trace-dispatcher')
[__1] fail (backjumping, conflict set: trace-dispatcher, unagi-chan)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: trace-dispatcher, unagi-chan

**System info:**
- OS Name: Ubuntu
- OS Version 20.04.3
- Node version 1.33.0
- CLI version  1.33.0

The tutorial probably needs to be updated.

**Comment by EtherealStakePool** [comment]
Did you try updating cabal to 3.6.2? I had (I believe) almost the exact same error as you and that seemed to work for me.

**Comment by avenepool** [comment]
> 

This helped, no issues with cabal 3.6.0.0.

**Comment by AvgustinKastelic** [comment]
I tried updating Cabal to version 3.6.2.0 using the following commands:
```
ghcup install cabal 3.6.2.0
ghcup set cabal 3.6.2.0
[ Info  ] Cabal 3.6.2.0 successfully set as default version
```

I still get the same dependency error.

**Comment by AvgustinKastelic** [comment]
I tried it again on a different machine using ghc 8.10.7 and cabal 3.6.0.0 and it worked.
Can the intended ghc and cabal versions be added to every release so we don't have to guess the versions we are meant to be using when building from source?
