### ISSUE TITLE
[BUG] - cardano-cli query utxo crashes with "cardano-cli: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)" when address has native tokens

### ISSUE THREAD

**Issue by ejserna** [input-output-hk/cardano-node#3487]
**Internal/External**
External
**Area**
CLI

**Summary**
A clear and specific description of what the bug is.
```$CLI query utxo --address addr_test1qqfjskjn04wn6c9fp8hefhfflg7gmup4pfhgcgx4qfqagc3wqygk6farr5kq4v0h69mjtqey9zv5wqctdjgczl5jd3pszws9vx  --testnet-magic 1097911063```

returns with 
cardano-cli: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character) 
**Steps to reproduce**
```$CLI query utxo --address addr_test1qqfjskjn04wn6c9fp8hefhfflg7gmup4pfhgcgx4qfqagc3wqygk6farr5kq4v0h69mjtqey9zv5wqctdjgczl5jd3pszws9vx  --testnet-magic 1097911063```

**Expected behavior**
It shouldn't crash and it should show all UTXOs.

**System info (please complete the following information):**

Ubuntu 20.04
cardano-node 1.30.1 - linux-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

cardano-cli 1.30.1 - linux-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

**Comment by frog357** [comment]
I tested with v1.33 and it does not crash for me. Possible this has been resolved in the most recent version.

**Comment by ejserna** [comment]
I'll try it! Thanks for that

**Comment by ejserna** [comment]
Can confirm v1.33 solved this issue.
