### ISSUE TITLE
[BUG] - Wrong epoch stake's value for some accounts

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/cardano-node#3491]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
I found an abnormal stake address `stake1ux7pt9adw8z46tgqn2f8fvurrhk325gcm4mf75mkmmxpx6gae9mzv` in mainnet with utxo/rewards balance that differs from the epoch stake's amount. Firstly I thought that the dbsync shows incorrect data. But after a more thorough check, I found that the cardano-cli (ledger state) shows the same data. If we check ledger state (current 313 epoch) we'll see that the _pstakeMark_ for this address is `103,133.667002`, _pstakeSet_ is `103,064.763712`. Both the ledger and the dbsync (epoch_stake table) show the same data. The latest transaction for this account was at the epoch 311, there are no txs for epoch 312 and 313, so pstakeMark should be equals to live stake. But all the explorers (adastat, cardanoscan, etc) show live stake as `103,083.667002`, what is equal to all the utxos + reward amount (and again both the ledger and the dbsync in this case show the same data). The difference is exactly 50 ada came out of nowhere. I continued to dig deeper and found that this happened 2 times - 25 ada in the epoch 301 (epoch stake is `102,481.802143` but if we take the previous stake `102,401.311281` and add to it the utxos input/output and reward/withdraw amount `55.490862` we'll get `102,456.802143`) and the second 25 ada in the epoch 309 (epoch stake is `102,974.948833`, the previous stake is `102,894.086595`, utxos input/output and reward/withdraw amount is `55.862238`, epoch stake must be `102,949.948833`)

**Steps to reproduce**

**_Method 1: DB Sync_**

Run this query, and see error: for epoch 301 and 309 (you ca change it in the 1st subquery) stake_different is not 0

```
WITH
_epoch AS (
    SELECT 301 AS no
),
_tx_data AS (
    SELECT MIN(tx.id) AS min_tx_id, MAX(tx.id) AS max_tx_id
    FROM tx 
    WHERE tx.block_id IN (
        SELECT id
        FROM block
        WHERE epoch_no = (SELECT no FROM _epoch)
    )
),
_stake_addr AS (
    SELECT id
    FROM stake_address
    WHERE view = 'stake1ux7pt9adw8z46tgqn2f8fvurrhk325gcm4mf75mkmmxpx6gae9mzv'
),
_utxo_reward AS (
    SELECT SUM(t.amount) AS amount
    FROM (
        (
            SELECT -tx_out.value AS amount
            FROM tx_in
            LEFT JOIN tx_out ON (tx_out.tx_id = tx_in.tx_out_id AND tx_out.index = tx_in.tx_out_index)
            WHERE tx_in.tx_in_id >= (SELECT min_tx_id FROM _tx_data) AND tx_in.tx_in_id <= (SELECT max_tx_id FROM _tx_data) AND tx_out.stake_address_id = (SELECT id FROM _stake_addr)
        )
        UNION ALL
        (
            SELECT tx_out.value AS amount
            FROM tx_out
            WHERE tx_out.tx_id >= (SELECT min_tx_id FROM _tx_data) AND tx_out.tx_id <= (SELECT max_tx_id FROM _tx_data) AND tx_out.stake_address_id = (SELECT id FROM _stake_addr)
        )
        UNION ALL
        (
            SELECT -withdrawal.amount AS amount
            FROM withdrawal
            WHERE withdrawal.tx_id >= (SELECT min_tx_id FROM _tx_data) AND withdrawal.tx_id <= (SELECT max_tx_id FROM _tx_data) AND withdrawal.addr_id = (SELECT id FROM _stake_addr)
        )
        UNION ALL
        (
            SELECT reward.amount AS amount
            FROM reward
            WHERE reward.addr_id = (SELECT id FROM _stake_addr) AND reward.spendable_epoch = (SELECT no FROM _epoch)+1
        )
    ) AS t
),
_epoch_stake AS (
    SELECT es2.amount - es1.amount AS amount
    FROM stake_address 
    LEFT JOIN epoch_stake AS es1 ON es1.addr_id = stake_address.id AND es1.epoch_no = (SELECT no FROM _epoch)+1
    LEFT JOIN epoch_stake AS es2 ON es2.addr_id = es1.addr_id AND es2.epoch_no = es1.epoch_no+1
    WHERE stake_address.id = (SELECT id FROM _stake_addr)
)
SELECT _utxo_reward.amount AS utxo_reward_change, _epoch_stake.amount AS epoch_stake_change, _epoch_stake.amount - _utxo_reward.amount AS stake_different
FROM _utxo_reward, _epoch_stake;
```

**_Method 2: Ledger State_**

1. Dump the epoch 313 ledger state `cardano-cli query ledger-state --mainnet > ledger.state.313.json && cat ledger.state.313.json | grep -A3 -B3 bc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369`
2. Check first matching (pstakeMark) - 103133667002
3. Check reward - 2135000059
4. Check utxos
```
 "b004a84f4cb564d854fafa1556cab365767c414a0f7e69a4ba9154181ce75c31#0": {
                        "datahash": null,
                        "address": "013c17b240e3a6d422b63ac211353d7e50ba663bdd962556e5262f5c1ebc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369",
                        "value": {
                            "policies": {},
                            "lovelace": 2417000
--
                    },
                    "d3dddc745c5ed27efd8d35c80e472e66c5d00bc273477f2ce9b39225228db6cf#0": {
                        "datahash": null,
                        "address": "01fbfce15acccb420982704c9e591f83ab3315c3314a18ecf65346e085bc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369",
                        "value": {
                            "policies": {},
                            "lovelace": 1000000000
--
                    },
                    "e0b2da4b408a06fa356307bd305b6d67901aa7e51f63876929a249909892dd33#1": {
                        "datahash": null,
                        "address": "015655db1c4db6747c98a9cde9ef571a11062877bff557b345c1e49e5abc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369",
                        "value": {
                            "policies": {},
                            "lovelace": 16383583011
--
                    },
                    "b004a84f4cb564d854fafa1556cab365767c414a0f7e69a4ba9154181ce75c31#1": {
                        "datahash": null,
                        "address": "010e4293274ecb1883492a285336f1e124d4a66a360dbeb7b580cb628bbc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369",
                        "value": {
                            "policies": {},
                            "lovelace": 38711735285
--
                    },
                    "e15bd364aac9607c537451f6855d54bd36ca460ae02f5316b0958d71e30dd984#1": {
                        "datahash": null,
                        "address": "01500a207aad822838329289ad4735ae110fd3b88fa87f1074e7537404bc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369",
                        "value": {
                            "policies": {},
                            "lovelace": 44834931647
--
                    },
                    "bbe3c55cec27d7296b39b0d5b44f1d91f5f2f8c41c893e56d67e3b2c0f6ac215#0": {
                        "datahash": null,
                        "address": "01fbfce15acccb420982704c9e591f83ab3315c3314a18ecf65346e085bc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369",
                        "value": {
                            "policies": {},
                            "lovelace": 16000000
```
4. Add up all the utxos amount and reward amount - `expr 2135000059 + 2417000 + 1000000000 + 16383583011 + 38711735285 + 44834931647 + 16000000`
5. Check pstakeMark and value from step 4 - they are different, the difference is 50 ada `expr 103133667002 - 103083667002`

**Expected behavior**
Since there are no any txs/withdraw for the epoch 312 and 313 for this account, pstakeMark and all utxos/reward sum must be equal to each other

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]
- Node version (cardano-node 1.33.0 - linux-x86_64 - ghc-8.10, git rev 814df2c146f5d56f8c35a681fe75e85b905aed5d)
- CLI version  (cardano-cli 1.33.0 - linux-x86_64 - ghc-8.10, git rev 814df2c146f5d56f8c35a681fe75e85b905aed5d)
- DB Sync version (cardano-db-sync-extended 12.0.0 - linux-x86_64 - ghc-8.10 git revision 9d0180571482ee4c6acb6fbc6bf55b5a4e2ee833)

P.S. cardano-node 1.30.1 / db-sync 11.0.4 are also affected by this issue. Also I'm pretty sure it's not related to rewards. Reward looks good, both db-sync and cardano-cli query stake-address-info show the same result, etc...

**Comment by JaredCorduan** [comment]
Could this stake address be from a retired stake pool? I am wondering if the 50 ADA is the returned deposit from the stake pool registration.

**Comment by dmitrystas** [comment]
Do you probably meant 500 ada? In any case - nope, this address has never been specified as the reward address for any pool

**Comment by JaredCorduan** [comment]
I was mistaken about the deposit, sorry. thanks for checking anyway.

**Comment by JaredCorduan** [comment]
I ran my [stake credential history tool](https://github.com/input-output-hk/cardano-node/blob/master/cardano-client-demo/Stake-Credential-History.md) to try to understand what is happening.

First some notes about how to read the logs.
* The `BALANCE` event records the stake address balance at the beginning of the epoch, before any transaction is processed. This corresponds to the stake in the `mark` snapshot contained in the stake address.
* The `REWARD-START` event records the total live stake in the `go`  snapshot for the given epoch.
* The `REWARD-END` event records the rewards the stake address will get on the next epoch boundary.

I'll look at the examples from epoch 301 and 309. The one from 313 would require me to either modify my tool or wait 5 days to analyze. Note that this stake address had no reward withdrawals after epoch 284. Therefore the only information missing from my logs that are relevant is movement of UTxO. What would be really helpful is if someone could get me every transaction in epochs 300 and 308 which involved an address whose staking credential is the one in the stake address mentioned in this ticket. The hex hash of the staking public key is `bc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369` if that helps.

---

### Epoch 301

From the logs of the tool:

```
BALANCE ----------- EpochNo 300, SlotNo 44237054, balance: Lovelace 1338743205
REWARD-START ------ EpochNo 300, SlotNo 44582430, stake: Lovelace 101223171110
REWARD-END -------- EpochNo 300, SlotNo 44582430, MemberReward-b62ecc8ce7e46c4443b63b91fffaeb19f869d191a7d2381087aaa768-Lovelace 61734505
BALANCE ----------- EpochNo 301, SlotNo 44668896, balance: Lovelace 1400477710
DELEGATION -------- SlotNo 44712273, PoolID 0f292fcaa02b8b2f9b3c8f9fd8e0bb21abedb692a6d5058df3ef2735
REWARD-START ------ EpochNo 301, SlotNo 45014415, stake: Lovelace 101285858525
REWARD-END -------- EpochNo 301, SlotNo 45014415, MemberReward-b62ecc8ce7e46c4443b63b91fffaeb19f869d191a7d2381087aaa768-Lovelace 55663799
BALANCE ----------- EpochNo 302, SlotNo 45100921, balance: Lovelace 1456141509
REWARD-START ------ EpochNo 302, SlotNo 45446505, stake: Lovelace 101339576776
ND -------- EpochNo 302, SlotNo 45446505, MemberReward-b62ecc8ce7e46c4443b63b91fffaeb19f869d191a7d2381087aaa768-Lovelace 67519720
BALANCE ----------- EpochNo 303, SlotNo 45532814, balance: Lovelace 1523661229
REWARD-START ------ EpochNo 303, SlotNo 45878411, stake: Lovelace 102401311281
```

First we think about epoch 300:
* the live stake from rewards in the `mark` snapshot for this stake address contains 1,338.743205 ada.
* the total live stake in the `mark` snapshot for this stake address (which we obtain by considering the `REWARD-START` event from epoch 302) is 101,339.576776 ada.
* therefore the live stake from UTxO in the `mark` snapshot is 100,000.833571 ada.
* The rewards given to this address on at the end of epoch 300 are 61.734505 ada.

Now we think about epoch 301:
* the live stake from rewards in the `mark` snapshot for this stake address contains 1,400.477710 ada.
* the total live stake in the `mark` snapshot for this stake address (which we obtain by considering the `REWARD-START` event from epoch 303) is 102,401.311281 ada.
* therefore the live stake from UTxO in the `mark` snapshot is 101,000.833571 ada.

Given that there were no reward withdrawals, everything adds up **provided** exactly 1,000 ada were net lost from addresses whose stake credential was `bc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369`. Which is not the number `55.490862` which is mention in the original post for this epoch.

The original post said:
> epoch stake is 102,481.802143 but if we take the previous stake 102,401.311281

The "previous stake" number aligns with my what I discovered, but the tool found the "epoch stake" to be 102,401.311281.

---

### Epoch 309

From the logs of the tool:

```
BALANCE ----------- EpochNo 308, SlotNo 47692859, balance: Lovelace 1826015765
REWARD-START ------ EpochNo 308, SlotNo 48038407, stake: Lovelace 102707047970
REWARD-END -------- EpochNo 308, SlotNo 48038407, MemberReward-0f292fcaa02b8b2f9b3c8f9fd8e0bb21abedb692a6d5058df3ef2735-Lovelace 42578645
BALANCE ----------- EpochNo 309, SlotNo 48124855, balance: Lovelace 1868594410
REWARD-START ------ EpochNo 309, SlotNo 48470418, stake: Lovelace 102801963851
REWARD-END -------- EpochNo 309, SlotNo 48470418, MemberReward-0f292fcaa02b8b2f9b3c8f9fd8e0bb21abedb692a6d5058df3ef2735-Lovelace 55862238
BALANCE ----------- EpochNo 310, SlotNo 48556875, balance: Lovelace 1924456648
REWARD-START ------ EpochNo 310, SlotNo 48902431, stake: Lovelace 102851507950
REWARD-END -------- EpochNo 310, SlotNo 48902431, MemberReward-0f292fcaa02b8b2f9b3c8f9fd8e0bb21abedb692a6d5058df3ef2735-Lovelace 79168205
BALANCE ----------- EpochNo 311, SlotNo 48988809, balance: Lovelace 2003624853
REWARD-START ------ EpochNo 311, SlotNo 49334492, stake: Lovelace 102894086595
```

First we think about epoch 308:
* live stake in `mark` for rewards: 1,826.015765
* live stake total in `mark`: 102,851.507950
* thus live stake for UTxO in `mark`: 101.025.492185
* rewards at end of 308: 42.578645

Now 309:
* live stake in `mark` for rewards: 1,868.594410
* live stake total in `mark`: 102,894.086595
* thus live stake for UTxO in `mark`: 101.025.492185

Given that there were no reward withdrawals, everything adds up **provided** exactly zero ada were net lost from addresses whose stake credential was `bc1597ad71c55d2d009a9274b3831ded155118dd769f5376decc1369`. Which is not the number `55.862238` which is mention in the original post for this epoch.

The original post said:
> epoch stake is 102,974.948833, the previous stake is 102,894.086595

The "previous stake" number aligns with my epoch 309 number.

---

I'll go over this again tomorrow with a clear head. :)

---

I don't myself know the easiest way to get all transactions involving a given stake credential.  I could probably modify the stake credential history tool to include that data, but perhaps there is an easier way that is pretty trustworthy.

**Comment by dmitrystas** [comment]
Full UTXO history from DB Sync

```
WITH
_stake_addr AS (
	SELECT id
	FROM stake_address
	WHERE view = 'stake1ux7pt9adw8z46tgqn2f8fvurrhk325gcm4mf75mkmmxpx6gae9mzv'
)
SELECT ENCODE(t.hash::bytea, 'hex') AS tx_hash, t.epoch_no, t.address, t.amount
FROM (
	(
		SELECT tx.id, tx.hash, block.epoch_no, tx_out.address, -tx_out.value AS amount
		FROM tx_in
		LEFT JOIN tx_out ON (tx_out.tx_id = tx_in.tx_out_id AND tx_out.index = tx_in.tx_out_index)
		LEFT JOIN tx ON tx.id = tx_in.tx_in_id
		LEFT JOIN block ON block.id = tx.block_id
		WHERE tx_out.stake_address_id = (SELECT id FROM _stake_addr)
	)
	UNION ALL
	(
		SELECT tx.id, tx.hash, block.epoch_no, tx_out.address, tx_out.value AS amount
		FROM tx_out
		LEFT JOIN tx ON tx.id = tx_out.tx_id
		LEFT JOIN block ON block.id = tx.block_id
		WHERE tx_out.stake_address_id = (SELECT id FROM _stake_addr)
	)
) AS t
ORDER BY t.id ASC;
```

```
                             tx_hash                              | epoch_no |                                                 address                                                 |    amount
------------------------------------------------------------------+----------+---------------------------------------------------------------------------------------------------------+--------------
 fd99d84f9bb8db7be0f05344c930d3d1b2d5123179ee5d58e66f73d362966134 |      208 | addr1q802wxt6cg6aw0nl0vdzfxavu65rxu3yzhvgayw7chfxymduzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5st4f9xu |  68547810343
 fd99d84f9bb8db7be0f05344c930d3d1b2d5123179ee5d58e66f73d362966134 |      208 | addr1qyst9crkl8mhs3vhyv5a4v5eyujw2vqsn2u0vga27zdpc94uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5ss78f90 |  41806141400
 fd99d84f9bb8db7be0f05344c930d3d1b2d5123179ee5d58e66f73d362966134 |      208 | addr1q92vskyludvqgnujl8xavyfgh48tkesqhsz2hem6w6507f9uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sgpeq2m |   8098944000
 705e920db5336e33369d0935a0e2d0353638b6f6580d26357f90c77d56f980d8 |      208 | addr1q83lg0mmhxgt86jnrvqnxezgp4cpn0ad57ln5neuun208mauzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s24m8kw |   8096769567
 705e920db5336e33369d0935a0e2d0353638b6f6580d26357f90c77d56f980d8 |      208 | addr1q92vskyludvqgnujl8xavyfgh48tkesqhsz2hem6w6507f9uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sgpeq2m |  -8098944000
 7be6b8a53cdde5e83981fd9a16f872720aea009dcc79847a79a7f22516d013ec |      209 | addr1qyst9crkl8mhs3vhyv5a4v5eyujw2vqsn2u0vga27zdpc94uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5ss78f90 | -41806141400
 7be6b8a53cdde5e83981fd9a16f872720aea009dcc79847a79a7f22516d013ec |      209 | addr1qy97tagys30yrq9amvt43krzyl0js3zq9md4qz92qgj4xs9uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sk8yuvw |  41805968463
 d728466c0d8b8c2a01e73dd39eecedebb1aa8dedfc95e7658d5e6a518a378eba |      219 | addr1q932e2zpu4favd0jemfkwkn2v8wx9w7caj8467jy4a3ps49uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s9wdqjk |  42282000000
 61752bc6d746bb20cda182f6fd847daca31b1a600774f517d52dd112be4f3fc7 |      243 | addr1q83lg0mmhxgt86jnrvqnxezgp4cpn0ad57ln5neuun208mauzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s24m8kw |  -8096769567
 61752bc6d746bb20cda182f6fd847daca31b1a600774f517d52dd112be4f3fc7 |      243 | addr1q932e2zpu4favd0jemfkwkn2v8wx9w7caj8467jy4a3ps49uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s9wdqjk | -42282000000
 61752bc6d746bb20cda182f6fd847daca31b1a600774f517d52dd112be4f3fc7 |      243 | addr1qy3n9x7szwwwkrnugkwlxra63an9ve2jf0m537q5mmsfvvauzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5st4u5xc |  39714488567
 8e5b7e9081798df8eae5fe0b0e7d069ac9002f76e2ea5ace0d8e9eed129849b3 |      255 | addr1q802wxt6cg6aw0nl0vdzfxavu65rxu3yzhvgayw7chfxymduzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5st4f9xu | -68547810343
 8e5b7e9081798df8eae5fe0b0e7d069ac9002f76e2ea5ace0d8e9eed129849b3 |      255 | addr1qx3hsx99vh236rpemdhn9x8wa9tzuwrz0fxukaxrn2t4vc9uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sghxlcx |  69933918237
 3308b7e94b12b45d03b3c87726d669a53af3db21f9de6932643e327018c1fd59 |      255 | addr1q802wxt6cg6aw0nl0vdzfxavu65rxu3yzhvgayw7chfxymduzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5st4f9xu |      1500000
 bbe3c55cec27d7296b39b0d5b44f1d91f5f2f8c41c893e56d67e3b2c0f6ac215 |      260 | addr1q8alec26en95yzvzwpxfukglsw4nx9wrx99p3m8k2drwppduzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sc9rzyn |     16000000
 b58c2134a5da3c3016e3978112eb358750f04bcdf7dba8d44cf801ddaf3a02de |      284 | addr1qy97tagys30yrq9amvt43krzyl0js3zq9md4qz92qgj4xs9uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sk8yuvw | -41805968463
 b58c2134a5da3c3016e3978112eb358750f04bcdf7dba8d44cf801ddaf3a02de |      284 | addr1q8lvrhxfe63fh467sn6fgthx3fmf02tw3x0hcfsvskrj04auzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sr9lq9q |  44835262609
 c1ae4a6b4131cbcf35e3d6a80c6fe0d1a69f647f0ba4d1410481b094a2fba892 |      284 | addr1qy3n9x7szwwwkrnugkwlxra63an9ve2jf0m537q5mmsfvvauzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5st4u5xc | -39714488567
 c1ae4a6b4131cbcf35e3d6a80c6fe0d1a69f647f0ba4d1410481b094a2fba892 |      284 | addr1q9pa8s40d069g4slyqc9juf3rexuczqsnwgl7mgkd84wx54uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s4n4rwa |  38714320734
 4d86b9fdc620895d9ca37a28631a3bbc70d1debc84a9f468fb96e91fb52fd65c |      293 | addr1qx3hsx99vh236rpemdhn9x8wa9tzuwrz0fxukaxrn2t4vc9uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sghxlcx | -69933918237
 4d86b9fdc620895d9ca37a28631a3bbc70d1debc84a9f468fb96e91fb52fd65c |      293 | addr1q8tdrzprgeatscf9q5rp6el3zcmkg5n6fwqu57nj0vufpw4uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s3hrp2l |  16433750228
 d3dddc745c5ed27efd8d35c80e472e66c5d00bc273477f2ce9b39225228db6cf |      300 | addr1q8alec26en95yzvzwpxfukglsw4nx9wrx99p3m8k2drwppduzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sc9rzyn |   1000000000
 af61b0be15c40984e841f611ed51fe91bb0d955a6e3a15b35825e9f4c4d7b147 |      301 | addr1q9ygkfywyh37k268gtgsr200zgsy8r7q95nfkam20n8cnaauzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5snq0hcj |  44835089672
 af61b0be15c40984e841f611ed51fe91bb0d955a6e3a15b35825e9f4c4d7b147 |      301 | addr1q8lvrhxfe63fh467sn6fgthx3fmf02tw3x0hcfsvskrj04auzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sr9lq9q | -44835262609
 b004a84f4cb564d854fafa1556cab365767c414a0f7e69a4ba9154181ce75c31 |      302 | addr1qy7p0vjquwndgg4k8tppzdfa0egt5e3mmktz24h9ych4c84uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sagksre |      2417000
 b004a84f4cb564d854fafa1556cab365767c414a0f7e69a4ba9154181ce75c31 |      302 | addr1qy8y9ye8fm933q6f9g59xdh3uyjdffn2xcxmada4sr9k9zauzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sgn2y7a |  38711735285
 b004a84f4cb564d854fafa1556cab365767c414a0f7e69a4ba9154181ce75c31 |      302 | addr1q9pa8s40d069g4slyqc9juf3rexuczqsnwgl7mgkd84wx54uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s4n4rwa | -38714320734
 e0b2da4b408a06fa356307bd305b6d67901aa7e51f63876929a249909892dd33 |      311 | addr1q8tdrzprgeatscf9q5rp6el3zcmkg5n6fwqu57nj0vufpw4uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s3hrp2l | -16433750228
 e0b2da4b408a06fa356307bd305b6d67901aa7e51f63876929a249909892dd33 |      311 | addr1q9t9tkcufkm8glyc48x7nm6hrggsv2rhhl640v69c8jfuk4uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5sqau44w |  16383583011
 e15bd364aac9607c537451f6855d54bd36ca460ae02f5316b0958d71e30dd984 |      311 | addr1q802wxt6cg6aw0nl0vdzfxavu65rxu3yzhvgayw7chfxymduzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5st4f9xu |     -1500000
 e15bd364aac9607c537451f6855d54bd36ca460ae02f5316b0958d71e30dd984 |      311 | addr1q9ygkfywyh37k268gtgsr200zgsy8r7q95nfkam20n8cnaauzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5snq0hcj | -44835089672
 e15bd364aac9607c537451f6855d54bd36ca460ae02f5316b0958d71e30dd984 |      311 | addr1q9gq5gr64kpzswpjj2y663e44cgsl5ac37587yr5uafhgp9uzkt66uw9t5kspx5jwjecx80dz4g33htknafhdhkvzd5s5h7g67 |  44834931647
```

Please let me know if you need more/other data or format

**Comment by dmitrystas** [comment]
And I apologize for not being quite clear, by "epoch 301" I meant the transition between 301/302, not 300/301. So, for the epoch 301 we have -44835262609 (utxo input) + 44835089672 (utxo output) + 55663799 (reward) = 55.490862 ada difference between previuos stake and live stake

**Comment by JaredCorduan** [comment]
ah, gotcha, let me redo the analysis for 301/302 and 309/310 :)

**Comment by JaredCorduan** [comment]
also thank you for the db-sync query, that's exactly what I needed

**Comment by JaredCorduan** [comment]
random thought: pointer addresses would explain what we are seeing, but those are very rarely used...

**Comment by dmitrystas** [comment]
You are genius, Jared! I think I've found it addr1g8alec26en95yzvzwpxfukglsw4nx9wrx99p3m8k2drwppvzj2enszcqyu9ps2 / 41fbfce15acccb420982704c9e591f83ab3315c3314a18ecf65346e0858292b3380b00 - https://adastat.net/addresses/addr1g8alec26en95yzvzwpxfukglsw4nx9wrx99p3m8k2drwppvzj2enszcqyu9ps2

It remains to figure out how to link it to the stake address for display the balance correctly...

**Comment by JaredCorduan** [comment]
:joy: fantastic. I've been working on trying to get my stake cred tool to confirm this as well. maybe you know this already, but the pointer is a triple corresponding to the stake key registration: slot number, index in the tx, index in the certificates. the ledger state tracks it, but I don't know of an easy way to query for it (maybe some else such as @erikd does).

**Comment by dmitrystas** [comment]
Yes, thanks a lot Jared! And I'm sorry I had to waste your time. I think we can close the issue.

**Comment by JaredCorduan** [comment]
No worries, happy to help!
