### ISSUE TITLE
[FR] - Allow building transactions without storing files on the filesystem

### ISSUE THREAD

**Issue by robinboening** [input-output-hk/cardano-node#3507]
**External**

**Area**
Building Transactions

**Describe the feature you'd like**
I'd like to be able to build a transaction without the need to store the output from commands on the filesystem. Instead, I'd like to be able to have this optional and be able to store the output of such commands in memory for use in a later command.

example

```
draft_tx = cardano-cli transaction build-raw ...
signed_tx = cardano-cli transaction sign --tx-body $draft_tx ...
```

or how about using pipes?

```
cardano-cli transaction build-raw ... | cardano-cli transaction sign ...
```

**Additional context / screenshots**
Currently, cardano-cli requires to use `--out-file` / `--tx-body-file` when building a transaction / calculating the fees.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
