### ISSUE TITLE
benchmarking:  RTS tweaking for block propagation

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3516]
There are some signs that increasing RTS-level parallelism can positively impact block propagation.
There are also some signs that this parallelism increase might require allocation area tuning, to avoid cache thrashing.

Therefore the following extra RTS options might be worth trying out:, to build an understanding of the cache footprint:

- `-A4m -N4`
- `-A4m`
- `-A2m -N4`
- `-A2m`
- `-A1m -N4`
- `-A1m`

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
