### ISSUE TITLE
[BUG] - Multisignatures documentation is outdated

### ISSUE THREAD

**Issue by edwint88** [input-output-hk/cardano-node#3536]
*External*  

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
In the [Multisignature Docs](https://github.com/input-output-hk/cardano-node/blob/c6b574229f76627a058a7e559599d2fc3f40575d/doc/reference/simple-scripts.md#step-2---construct-required-witnesses) there is this code:
`cardano-cli shelley transaction witness \
  --tx-body-file spendScriptTxBody \
  --script-file allMultiSigScript \
  --testnet-magic 42 \
  --out-file scriptWitness`

that in the cardano-cli cannot be executed anymore.

checking the command: 
`cardano-cli shelley transaction witnessUsage: cardano-cli shelley transaction witness --tx-body-file FILE
            --signing-key-file FILE
            [--address STRING]
            [--mainnet | --testnet-magic NATURAL]
            --out-file FILE

  Create a transaction witness

Available options:
  --tx-body-file FILE      Input filepath of the JSON TxBody.
  --signing-key-file FILE  Filepath of the signing key to be used in witness
                           construction.
  --address STRING         Byron address (Base58-encoded).
  --mainnet                Use the mainnet magic id.
  --testnet-magic NATURAL  Specify a testnet magic id.
  --out-file FILE          The output file.
  -h,--help                Show this help text`

there is no `--script-file` anymore

**Steps to reproduce**
1. Go to documentation
2. Follow the steps
3. Run the command

**Expected behavior**
A clear and concise description of how the multisig should work

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 1.33.0
- CLI version  1.33.0

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
