### ISSUE TITLE
Encrypted connection to Cardano Testnet

### ISSUE THREAD

**Issue by Nayanabvreddy** [input-output-hk/cardano-node#3547]
Hello Team,

Facing an issue to access relays-new.cardano-testnet.iohkdev.io:3001 with encrypted connection.

when I try the curl command with https getting the below error.

curl https://relays-new.cardano-testnet.iohkdev.io:3001/
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to relays-new.cardano-testnet.iohkdev.io:3001

Could you please let me know how to make a secure connection to relays-new.cardano-testnet.iohkdev.io on cardano testnet.

**Comment by newhoggy** [comment]
Hi @Nayanabvreddy,

Thanks for your question.

Connecting to a relay via TLS/SSL is supported, so you will not be able to curl the relay in this manner.
