### ISSUE TITLE
[BUG] - cardano-cli fails with `MuxError` when p2p is enabled

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3568]
*Internal*

**Area**
*Other*   p2p

**Summary**
On local network where p2p is enabled, all cardano-cli commands fail:
```
$ cardano-cli query tip --testnet-magic 42
MuxError (MuxIOException writev: resource vanished (Broken pipe)) "(sendAll errored)"

cardano-cli: MuxIOException writev: resource vanished (Broken pipe) "(sendAll errored)"
```

`cardano-node` processes are running, there are no errors in log files. The issue is present in latest master, first it was observed in nightly job that ran with rev 40cf9b428f4bd6156cc8d2aef01ac9475f5a62c5
The issue is not present when p2p is disabled and legacy topology files are used.

**Steps to reproduce**
1. start local cardano network with p2p enabled
2. run any `cardano-cli` command

**System info (please complete the following information):**
- OS Name: Linux
- Node version: 40cf9b428f4bd6156cc8d2aef01ac9475f5a62c5
- CLI version: 40cf9b428f4bd6156cc8d2aef01ac9475f5a62c5

**Comment by cardano-apexpool** [comment]
This bug is still present in 1.34.0, actually even worse. Every query fails. 

        $ cardano-cli query tip --testnet-magic 1097911063 
        MuxError (MuxIOException writev: resource vanished (Broken pipe)) "(sendAll errored)"
        
        cardano-cli: MuxIOException writev: resource vanished (Broken pipe) "(sendAll errored)"

I was trying to check if #3659 was resolved in 1.34.0, but it is not, probably because of this one.
