### ISSUE TITLE
[BUG] - Node 1.33+ dropping Mempool transactions without broadcast

### ISSUE THREAD

**Issue by stefanofranz** [input-output-hk/cardano-node#3574]
**External**

**Area**

*Other*   

**Summary**
Transactions submitted to the Node from Cardano-Wallet are accepted into Mempool, then removed from mempool without broadcast of TX occurring. Such as these logs 

``` 
[cardano-:cardano.node.Mempool:Info:456] [2022-02-05 21:04:23.28 UTC] fromList [("tx",Object (fromList [("txid",String "dd26fa65")])),("kind",String "TraceMempoolAddedTx"),("mempoolSize",Object (fromList [("bytes",Number 599.0),("numTxs",Number 2.0)]))]
[cardano-:cardano.node.ChainDB:Notice:365] [2022-02-05 21:04:28.25 UTC] Chain extended, new tip: 3dc716b6f8276216da1ad7a546c1
6ee1eba46ded76e9bb6f1899aca6c9cadc90 at slot 52528776
[cardano-:cardano.node.ChainDB:Notice:365] [2022-02-05 21:04:37.36 UTC] Chain extended, new tip: d6c17c549026844e06391f6982ef
c480e74affa7bf46077cd2e983e024f77417 at slot 52528785
[cardano-:cardano.node.ChainDB:Notice:365] [2022-02-05 21:04:39.79 UTC] Chain extended, new tip: 99e5fa1b7ec924f960ee0d12c791
bb68bf9c424a8317103113298b2c6a341184 at slot 52528787
[cardano-:cardano.node.ChainDB:Notice:365] [2022-02-05 21:05:47.93 UTC] Chain extended, new tip: 151b3c73ae416daa7e8c340c4f1b
86642066cbf30611048b282163513f9812f6 at slot 52528856
[cardano-:cardano.node.Mempool:Info:373] [2022-02-05 21:05:47.93 UTC] fromList [("kind",String "TraceMempoolRemoveTxs"),("txs
",Array [Object (fromList [("txid",String "dd26fa65")])]),("mempoolSize",Object (fromList [("bytes",Number 283.0),("numTxs",Number 1
.0)]))]
```  

id: `dd26fa65` corresponds to txId: `dd26fa65bb5fa2e2376b07f92eef56b2e5876d1a082637a2a2682b1309fd4c5e` which has never been broadcast to the network.

This behaviour never occurred before node 1.33 - could someone explain if this is acceptable behavior, or if there is a configuration issue. 

**Steps to reproduce**
1. Submit transaction from cardano-wallet
2. wait for transaction to be accepted by node
3. Observe that transaction is never broadcast to network

**Expected behavior**
Transactions in Mempool are only removed from Mempool after broadcast to network. 

**System info (please complete the following information):**
- official docker 1.33.1 node image.

**Comment by Godspeed-exe** [comment]
@stefanofranz Did you configure a time_to_live when building the transaction? If you didn't the wallet defaults to 7200 - which is about 2 hours. This SHOULD be enough... but it seems advisable to increase this about 6 hours.

Source: https://github.com/input-output-hk/cardano-wallet/blob/8bc24b710091b2fecaa4f99207acc689a78e284d/lib/core/src/Cardano/Wallet.hs#L2104

**Comment by stefanofranz** [comment]
the TTL was set to 45minutes manually - we've checked and the network tip was correctly detected. 

The thing is the transaction was evicted from the after just over a minute, which is very odd. Absolutely the slot number had not been reached when it was evicted. Seems to be a similar situation as https://github.com/input-output-hk/cardano-node/issues/3524

**Comment by stefanofranz** [comment]
This was evicted within 1minute.

We run multiple other nodes, none of these other nodes received this transaction in a block, and as per the logs - there was no rollbacks / chain forks during the time between it being submitted and evicted or afterwards.

2 Other transactions which were submitted _before_ this transaction, were evicted _after_ this transaction.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
