### ISSUE TITLE
DevEx: IFD caching investigation

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3576]
All components in the `cardano-node` stack (plutus, ledger, consensus, the node itself etc) are expressed within the `haskell.nix` Haskell build infrastructure.

`haskell.nix` stretches the limits of what Nix itself provides, and so relies heavily on the input-from-derivation technique (IFD).

The IFD technique, while crucial for implementing the features necessary for `haskell.nix`, has an unfortunate property of causing un-cacheable builds on each developer's machine, each time a significant change in dependencies happens.

Sometimes these un-cacheable builds are massive.

This sometimes makes the developer experience very sluggish.

We have avenues of investigation into the key deficiency of IFD -- the lack of caching.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
