### ISSUE TITLE
tx-generator: the troublesome implicitness of inputs and outputs -- design

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3579]

**Comment by MarcFontaine** [comment]
The tx-generator is extended to use multiple/named wallets.
A dedicated wallet can be used for each Set of UTxOs that is used in a specific way,
for example in a specific benchmarking run or a specific splitting phase.

https://github.com/input-output-hk/cardano-node/pull/3638

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
