### ISSUE TITLE
tx-generator: too many value-producing streaming abstractions

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3580]

**Comment by mgmeier** [comment]
- Now using reformulated streaming types on top of a common streaming abstraction from package `streaming`
- Removed custom streaming type(s) `WalletScript` / `WalletStep`
- Implemented in PR https://github.com/input-output-hk/cardano-node/pull/4412

**Comment by mgmeier** [comment]
above PR has been merged to `master`
