### ISSUE TITLE
tx-generator: design for a well-defined, declarative workload spec language

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3581]

**Comment by deepfire** [comment]
We've decided with @MarcFontaine that the first step would be an initial reconnaissance in the form of moving the current Nix-level implementation of the user-oriented language into Haskell.

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/3615

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
