### ISSUE TITLE
Banish unsafePerformIO in Cardano.CLI.Tx.Generation

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-node#359]
There are a few uses of `unsafePerformIO` in the `Cardano.CLI.Tx.Generation` module.

Remember our rules is that there's no such thing as "global" or "top level" variables and `unsafePerformIO` is never legitimate in application code. There are always alternative solutions, and they're inevitable better.

**Comment by denisshevchenko** [comment]
Agree. But how can I remove `unsafePerformIO`, for example, from here? https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/CLI/Tx/Generation.hs#L981. I see in the documentation (https://www.stackage.org/haddock/lts-14.16/base-4.12.0.0/GHC-Conc.html#v:newTVarIO):

> `IO` version of `newTVar`. This is useful for creating top-level `TVars` using `unsafePerformIO`, because using `atomically` inside `unsafePerformIO` isn't possible.

**Comment by denisshevchenko** [comment]
https://github.com/input-output-hk/cardano-node/pull/400

**Comment by CodiePP** [comment]
the tx gen program works on a set of UTxO and progresses through different phases:
1. extract values from genesis and fill in initial UTxO set
2. phase1: create txs to split genesis funds into larger UTxO set
3. phase2: continuously make txs from UTxO set and create new UTxO

the set of UTxO could be kept in a structure like for example: https://hackage.haskell.org/package/stm-chans-3.0.0.4/docs/Control-Concurrent-STM-TBMQueue.html
(which has the interesting property that newly created UTxO are not reused too fast)
