### ISSUE TITLE
[BUG] shelley-from-scratch creates alonzo transaction.

### ISSUE THREAD

**Issue by phadej** [input-output-hk/cardano-node#3602]
`cardano-cli transaction build-raw` probably should include `--shelley-era`.  Otherwise I get invalid era error.

**Comment by newhoggy** [comment]
Hi @phadej,

Are you reporting that documentation needs updated?

**Comment by dorin100** [comment]
@phadej can you please provide more details?

**Comment by phadej** [comment]
I don't remember the details anymore. We moved away from using those scripts.
