### ISSUE TITLE
[FR] - Docker image for arm arch

### ISSUE THREAD

**Issue by mahnunchik** [input-output-hk/cardano-node#3609]
**External**

*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**

It would be helpful to have `arm64` build of docker image for `cordano-node`.

**Additional context / screenshots**

It is impossible to launch official [`inputoutput/cardano-node`](https://hub.docker.com/r/inputoutput/cardano-node) docker image on Mac M1.

```bash
% docker run --platform=linux/amd64 -e NETWORK=testnet inputoutput/cardano-node 
Starting: /nix/store/aginrkjcnlzbxsvla5bd8lnx73a475yi-cardano-node-exe-cardano-node-1.33.0/bin/cardano-node run
--config /nix/store/5b6pry15w93fv0r0x9rc3r1ii5871lvr-config-0-0.json
--database-path /data/db
--topology /nix/store/dpajyi2vaychwps1x7d20c2ddls4kf62-topology.yaml
--host-addr 0.0.0.0
--port 3001
--socket-path /ipc/node.socket





+RTS
-N2
-I0
-A16m
-qg
-qb
--disable-delayed-os-memory-return
-RTS
..or, once again, in a single line:
/nix/store/aginrkjcnlzbxsvla5bd8lnx73a475yi-cardano-node-exe-cardano-node-1.33.0/bin/cardano-node run --config /nix/store/5b6pry15w93fv0r0x9rc3r1ii5871lvr-config-0-0.json --database-path /data/db --topology /nix/store/dpajyi2vaychwps1x7d20c2ddls4kf62-topology.yaml --host-addr 0.0.0.0 --port 3001 --socket-path /ipc/node.socket      +RTS -N2 -I0 -A16m -qg -qb --disable-delayed-os-memory-return -RTS

% docker ps -a
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS                        PORTS                      NAMES
3f1c311ac88d   inputoutput/cardano-node   "entrypoint"             34 seconds ago   Exited (137) 31 seconds ago                              ecstatic_keldysh
```

**Comment by mckania0** [comment]
Hello,

is it somehow planned in the roadmap? I see many people started receiving their M1s (including myslef) so this would be beneficial to have.

**Comment by cedcardano** [comment]
Would be nice to have with Docker for sure. For now, the instructions in https://developers.cardano.org/docs/get-started/installing-cardano-node/ are sufficient to build darwin/arm64 native binaries with cabal from source.

If you really must run it with Docker, you can look into options like [](https://hub.docker.com/r/nessusio/cardano-node/tags). This way Docker can run the linux/arm64 image with only a slight decrease in performance as far as I'm aware. Or you can cross-compile the node from source to linux/arm64, then run that in Docker without any issues.

**Comment by koolwithk** [comment]
As https://hub.docker.com/r/nessusio/cardano-node/tags does not have the latest node I created Dockerfile to build the `arm64` image directly on the system[M1 or Rpi4 or any arm64].

here are the steps to build your own `arm64` docker image - 
https://github.com/koolwithk/cardano-node-build#build-arm64-cardano-node-docker-image

Or you can use the already build cardano-node docker image.
```
docker run -it -e NETWORK=testnet koolwithk/cardano-node:1.35.5-arm64
```

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
