### ISSUE TITLE
 TxScriptValiditySupportedInAlonzoEra for Alonzo transactions

### ISSUE THREAD

**Issue by ntfreem** [input-output-hk/cardano-node#3618]
What does TxScriptValidatity stand for? https://github.com/input-output-hk/cardano-node/blob/333c701ca9be38e5d955c9d3ee0fab391e85e4f4/cardano-api/src/Cardano/Api/TxBody.hs#L275

Should it always be TxScriptValidity TxScriptValiditySupportedInAlonzoEra for Alonzo transactions?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
