### ISSUE TITLE
Investigate why https://github.com/input-output-hk/cardano-node/pull/352 fixed the issue

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-node#362]
After the PR - https://github.com/input-output-hk/cardano-node/pull/348
We noticed that the PR actually failed in the node with:
```
cardano-node: user error ((line 1, column 1):
unexpected end of input
expecting white space or JSON value)
```

This fixed it - https://github.com/input-output-hk/cardano-node/pull/352

The question was - why is that fixing the actual issue with the CI?

**Comment by ksaric** [comment]
I thought that was because of the `ToLogObject IO` instance:
```
instance ToLogObject IO where
    toLogObject :: (MonadIO m, ToObject a, Transformable a m b)
                => Tracer m (LogObject a) -> Tracer m b
    toLogObject tr = trTransformer StructuredLogging NormalVerbosity tr
    toLogObject' :: (MonadIO m, ToObject a, Transformable a m b)
                 => TracingFormatting -> TracingVerbosity -> Tracer m (LogObject a) -> Tracer m b
    toLogObject' hint verb tr = trTransformer hint verb tr
```

Since the transformer definition was not complete (well, it was complete, but not exhaustive I guess), I presumed that was causing it.
Notice how it was defined before - https://github.com/input-output-hk/cardano-node/pull/352/files#diff-d1ea55d7138fc8b6df9635128887767aL353-L354

My assumption was that `trStructured` was called on `TextualRepresentation` where the default implementation was:
```
trStructured :: (ToObject b, MonadIO m, DefinePrivacyAnnotation b, DefineSeverity b)
             => TracingVerbosity -> Tracer m (LogObject a) -> Tracer m b
trStructured verb tr = Tracer $ \arg ->
        let obj = toObject verb arg
            tracer = if obj == emptyObject then nullTracer else tr
        in
        traceWith tracer =<<
            LogObject <$> pure mempty
                      <*> (mkLOMeta (defineSeverity arg) (definePrivacyAnnotation arg))
                      <*> pure (LogStructured $ encode $ obj)
```

Where the default mechanism is:
```
class ToObject a where
    toObject :: TracingVerbosity -> a -> Object
    default toObject :: ToJSON a => TracingVerbosity -> a -> Object
    toObject _ v = case toJSON v of
        Object o     -> o
        s@(String _) -> HM.singleton "string" s
        _            -> mempty
```
So it tries to convert `v` to JSON.

That's why I figured the error was appearing:
```
cardano-node: user error ((line 1, column 1):
unexpected end of input
expecting white space or JSON value)
```

But since we have a custom instance - https://github.com/input-output-hk/cardano-node/pull/348/files#diff-d1ea55d7138fc8b6df9635128887767aR788-R816

**Comment by ksaric** [comment]
After playing around in ghci, trying to find the cause, I noticed something quite disturbing:
```
import Data.Aeson
import Ouroboros.Network.Block

$> toJSON . unSlotNo $ SlotNo 3
Number 3.0

import Ouroboros.Consensus.Node.Tracers

let forgeEvent = TraceForgeEvent (SlotNo 5) (10 :: Int)

$> :t forgeEvent
forgeEvent :: TraceForgeEvent Int
```
All good, `TraceForgeEvent` is abstract and has a `show` instance - https://github.com/input-output-hk/ouroboros-network/blob/def91de3eb6259c18fbde98ae9071415d61aa7af/ouroboros-consensus/src/Ouroboros/Consensus/Node/Tracers.hs#L100

Let's show him (pun intended):
```
$> show forgeEvent 

<interactive>:30:1: error:
    • Could not deduce (Ouroboros.Consensus.Ledger.Abstract.ProtocolLedgerView
                          Int)
        arising from a use of ‘show’
      from the context: StringConv String b
        bound by the inferred type of it :: StringConv String b => b
        at <interactive>:30:1-15
    • In the expression: show forgeEvent
      In an equation for ‘it’: it = show forgeEvent
```

Where is this `ProtocolLedgerView` constraint jumping in from? Is it just me or is this confusing as hell?

**Comment by ksaric** [comment]
Ah, here we go - https://github.com/input-output-hk/ouroboros-network/blob/def91de3eb6259c18fbde98ae9071415d61aa7af/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/API.hs#L434-L444

**Comment by ksaric** [comment]
So this PR - https://github.com/input-output-hk/cardano-node/pull/368 shows that the issue wasn't in the `Transformable` instance but in the "silent logging" issue.

@CodiePP @deepfire Can you expand on this like in this morning discussion so I can close this?

**Comment by deepfire** [comment]
We're using `cardano-cli` for various operations in the mixed cluster setup, such as:
- extracting public keys from private
- migrating public keys

These operations rely on the standard output of `cardano-cli` to supply the results -- but if the logging infrastructure causes messages to be emitted during `cardano-cli` runs, those interfere with the output.

As explained in https://github.com/input-output-hk/cardano-node/pull/357:
> The root of the problem is the impossibility to completely disable logging in `cardano-node` -- we used to have this mechanism, but at some point it was removed, making any usage of `cardano-cli`'s standard output more fragile.

Now, this is slightly incorrect -- it is indeed not possible to completely disable logging using CLI, without resorting to configuration files.

So, in the end the issue is roughly about the configuration turmoil that we are going through.

**Comment by deepfire** [comment]
cc @dcoutts

**Comment by CodiePP** [comment]
let's hope that turning off logging to stdout will prevent the mangling of the output of the various scripts. It sounds logical at least.

**Comment by ksaric** [comment]
Closing since this is resolved.
