### ISSUE TITLE
Update tx-generator-service.nix and Nix infrastructure to new location of Plutus scripts.

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/cardano-node#3620]
The tx-generator relies on a dedicated `loop.plutus` script for its Plutus transactions.
There are two options:
1) Properly compile the `loop.plutus` and add it to the nix-infrastructure
2) Check-in a pre-compiled binary.
The current version of `loop.plutus` (just as any other Plutus script on mainnet) is supposed to work eternally, so 2) is not totally unreasonable.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
