### ISSUE TITLE
[FR] - `cardano-cli genesis create-staked` -- switching to ephemeral, in-memory storage of delegation keys

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3642]
**Internal**

**Area**
*`cardano-cli` genesis tooling*

**Problem description**

Short version: `cardano-cli genesis create-staked` takes around 20 minutes on a modern machine, for the typical benchmarking genesis -- and it's only going to get worse, as our workloads increase.

Details:

The `cardano-cli genesis create-staked` is only ever used by benchmarking to enable instantaneous loading of a large internal state into `cardano-node`:
1. UTxO
2. delegation map

All the keys backing the UTxO entries and the delegation map are not needed by benchmarking -- we only care about their representation in the resulting Shelley genesis JSON file.

However, as it stands, the `genesis create-staked` functions as follows:
1. creates all the delegation keys and stores them on disk
2. loads them back

For a million of key credentials sets that's a lot of disk IO, and also a lot of CPU time spent dealing with serialisation/deserialisation.

The effect is, as mentioned, ~20 minutes of genesis creation time.

**Proposal**

We could cut the unnecessary to-disk/from-disk phase -- and the accompanying serialisations/deserialisation, and keep all credentials in memory.

The estimation is should speed up the process tremendously.

Additionally it's worth mentioning, that for the credentials of the pools themselves, and for the separate UTxO keys (we need funds for benchmarks too) we do actually care about the physical files.

The top-level portion of code is here: https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/src/Cardano/CLI/Shelley/Run/Genesis.hs#L401-L439

**Comment by Jimbo4350** [comment]
v
