### ISSUE TITLE
[BUG] - Cardano-cli envelope type mismatch

### ISSUE THREAD

**Issue by davidmisiak** [input-output-hk/cardano-node#3645]
**External**

**Area**
*Other* - cardano-cli file formats

**Summary**
When cardano-cli creates an unwitnessed Shelley tx file in cddl format, it provides different envelope type strings than it expects when assembling a signed transaction (and maybe elsewhere, too?). Compare e.g. https://github.com/input-output-hk/cardano-node/blob/edbfdc06f52c7098d1db36e3f3a001efeb004347/cardano-api/src/Cardano/Api/SerialiseLedgerCddl.hs#L291-L292 and https://github.com/input-output-hk/cardano-node/blob/600f5d2ec55db7c59ea248b027b9a805f07a7c51/cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs#L1624-L1625

Edit: An analogous issue seems to be present for witnessed tx files and witness files.

**Steps to reproduce**
1. `cardano-cli transaction build-raw --shelley-era --tx-in "123...abc#0" --tx-out "addr1...abc"+0 --fee 0 --ttl 0 --out-file tx --cddl-format`
2. `cardano-cli transaction assemble --tx-body-file tx --out-file tx.signed --witness-file my.witness`
3. Observe the error:
> Command failed: transaction sign-witness  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: cddl-shelley: TextEnvelope type error:  Expected one of: TxUnsignedByron, TxUnsignedShelley, TxBodyAllegra, TxBodyMary, TxBodyAlonzo Actual: Unwitnessed Tx ShelleyEra
> TextEnvelopeCddl error: cddl-shelley: TextEnvelopeCddl type error:  Expected one of: Witnessed Tx Byron, Witnessed Tx Shelley, Witnessed Tx AllegraEra, Witnessed Tx MaryEra, Witnessed Tx AlonzoEra, Unwitnessed Tx Byron, Unwitnessed Tx Shelley, Unwitnessed Tx AllegraEra, Unwitnessed Tx MaryEra, Unwitnessed Tx AlonzoEra Actual: Unwitnessed Tx ShelleyEra

**Expected behavior**
Assembling the signed transaction without an error.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 21.10
- Node version: `cardano-node 1.31.0 - linux-x86_64 - ghc-8.10 git rev 5b5310988c7c0500897bacb5555f3334d89f4aa1`
- CLI version: `cardano-cli 1.33.0 - linux-x86_64 - ghc-8.10 git rev 17bc0c54e5581df6a2e986f18e2e0266a4b12138`

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by mkk1985** [comment]
please reopen this as i can see in the above code changes Era names for Shelley an Byron are not uniform.. I am getting the below error:

 

Command failed: transaction sign  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: tx.raw: TextEnvelope type error:  Expected one of: TxUnsignedByron, TxUnsignedShelley, TxBodyAllegra, TxBodyMary, TxBodyAlonzo Actual: Unwitnessed Tx BabbageEra

TextEnvelopeCddl error: tx.raw: TextEnvelopeCddl type error:  Expected one of: Witnessed Tx Byron, Witnessed Tx Shelley, Witnessed Tx AllegraEra, Witnessed Tx MaryEra, Witnessed Tx AlonzoEra, Unwitnessed Tx Byron, Unwitnessed Tx Shelley, Unwitnessed Tx AllegraEra, Unwitnessed Tx MaryEra, Unwitnessed Tx AlonzoEra Actual: Unwitnessed Tx BabbageEra

root@AZUSWVLNX00578:/cardano_bp/cardano_bpn/key# vi tx.raw

root@AZUSWVLNX00578:/cardano_bp/cardano_bpn/key# cardano-cli transaction sign     --tx-body-file tx.raw     --signing-key-file payment.skey     --signing-key-file stake.skey     --testnet-magic 1     --out-file tx.signed

Command failed: transaction sign  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: tx.raw: TextEnvelope type error:  Expected one of: TxUnsignedByron, TxUnsignedShelley, TxBodyAllegra, TxBodyMary, TxBodyAlonzo Actual: Unwitnessed Tx Shelley

TextEnvelopeCddl error: tx.raw: Unknown TextEnvelopeCddl type:Unwitnessed Tx Shelley

 

if you observe the above changes in the file: https://github.com/input-output-hk/cardano-node/blob/600f5d2ec55db7c59ea248b027b9a805f07a7c51/cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs#L1624-L1625

 

All are having Era as suffix except for Shelley and Byron.. I believe that has to be fixed.. please correct it if its the fix or guide me to eradicate my current error.

**Comment by Jimbo4350** [comment]
What version of the cli are you using

**Comment by andrejpodzimek** [comment]
I’ve already commented on #3899, but then realized that _this_ might be the most recently updated one of [the `Unwitnessed` bugs](https://github.com/input-output-hk/cardano-node/issues?q=unwitnessed) (albeit filed much earlier).

`cardano-cli` `1.35.4` won’t help, because this recently started happening with `cardano-cli` `1.35.5`. [More details are here.](https://forum.cardano.org/t/unwitnessed-tx-babbageera-while-signing-transaction/114616/4?u=andrejpodzimek)
