### ISSUE TITLE
[BUG] - Unable to configure cardano-node with latest documentation on Digital Ocean w/ Rocky Linux 8.5

### ISSUE THREAD

**Issue by SysEngDan** [input-output-hk/cardano-node#3653]
**External**

**Summary**
After deploying a clean, new VM with Digital Ocean for Rocky Linux 8.5, following the installation instructions located [here ](https://developers.cardano.org/docs/get-started/installing-cardano-node#linux)result in the following, very reproducible failure during the configure stage of cardano-node with ghc 8.10.7 and similarly with 8.6.5:

```
Cloning into '/root/cardano-src/cardano-node/dist-newstyle/src/plutus-3b55de0732f6b166'...
remote: Enumerating objects: 117608, done.
remote: Counting objects: 100% (4367/4367), done.
remote: Compressing objects: 100% (1934/1934), done.
remote: Total 117608 (delta 2477), reused 3855 (delta 2175), pack-reused 113241
Receiving objects: 100% (117608/117608), 123.57 MiB | 20.92 MiB/s, done.
Resolving deltas: 100% (73909/73909), done.
HEAD is now at 1efbb276e SCP-2750: Removed types and functions in Ledger.Tx that were integrated in cardano-api instead. Updated cardano                 -node commit hash. (#4012)
Warning: Requested index-state 2021-12-07T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-12-06T23:34:30Z).
Resolving dependencies...

Killed
```

**Steps to reproduce**
1. Go to 'https://developers.cardano.org/docs/get-started/installing-cardano-node#linux'
2. Follow instructions for the RedHat version
3. Get to the command 'cabal configure --with-compiler=ghc-8.10.7'
4. See error pasted above

**Expected behavior**
I expected for the configure stage to complete successfully and without error.  

**System info (please complete the following information):**
- OS Name: Rocky Linux
- OS Version: 8.5
- Node version: Latest version that would be installed from the documentation [here](https://developers.cardano.org/docs/get-started/installing-cardano-node#linux)
- CLI version  Latest version that would be installed from the documentation [here](https://developers.cardano.org/docs/get-started/installing-cardano-node#linux)

**Comment by disassembler** [comment]
You ran out of memory most likely. I'd recommend either using the provided binaries or compiling on a larger machine and moving your binaries to your running node.

**Comment by SysEngDan** [comment]
> You ran out of memory most likely. I'd recommend either using the provided binaries or compiling on a larger machine and moving your binaries to your running node.

I'll give you the benefit of the doubt and retry after increasing the memory. Here's why I'm doubtful though: I created a VM in my infrastructure the same amount of RAM and vCPUs running RockyLinux 8.5. I didn’t have any issue with the deployment. It seems isolated to the Digital Ocean VMs, which I think should be of concern to the cardano-node team.
