### ISSUE TITLE
More metrics on Prometheus interface

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#366]
@disassembler wants all LiveView metrics on Prometheus and a few more:

pull requests:
 - https://github.com/input-output-hk/cardano-node/pull/395

# Tentative TODO

- [ ] Deal with mempool metrics (cc @ksaric) 
- [ ] Move transformers to `tracer-transformers` (another repo) & consider tests (maybe the transformers are too obvious to need any, though)
- [ ] Consider frequency reduction, for non-counter metrics
   - determine the high-frequency ones:
     - mempool
     - connected peers

# Current overview

 - [ ] mempool metrics (wait time, modify time) => "time-to-block" from benchmarking
    - [ ] moment when tx is added into the mempool (stm atomically commits)
      - `TraceMempoolAddTxs`      mempoolSize accepted time
    - [ ] moment tx is removed from mempool
      - `TraceMempoolRemoveTxs`   mempoolSize (map fst removed) time
    - [ ] when tx is downloaded via the protocol (before attempting to add it to the mempool)
      - `TraceTxSubmissionInbound` -- not implemented yet
    - [ ] when we attempt to add it to the mempool (ie before we do the blocking stm transaction to try doing so)
      - ??? (cc @ksaric)
- [x] mempool size (number of tx) => LiveView metrics
  - `TraceEventMempool`
    - AddTxs + RejectedTxs + RemoveTxs + ManuallyRemovedTxs
      - track additions & removals (custom transformer) -> result
      - as `cardano_node_metrics_txsInMempool_int`
- [x] a counter of the transactions that this node processed (since startup)
  - `TraceEventMempool`
    - `AddTxs` + `RejectedTxs` + `RemoveTxs` + `ManuallyRemovedTxs`
      - directly available
      - as `cardano_node_metrics_txsProcessed_int`
- [x] a counter of how many blocks this node created since startup
  - `Node.Tracers.TraceForgeEvent`
    - `ForgeEvent` at slot
      - `counting` transformer gets the result
    - also has: `CouldNotForge` + `AdoptedBlock` + `DidntAdoptBlock` + `ForgedInvalidBlock`
    - as `cardano_node_metrics_Forge_*`
- [x] chain density, epoch, slot, block in epoch number
  - `ChainDB.TraceAddBlockEvent` -> `ChainDB.SwitchedToChain`
    - `density`, `slotNum`, `blockNum`, `slotInEpoch`, `epoch` -- a la carte
    - as `cardano_node_metrics_ChainDB_*`
- [x] all of the LiveView metrics
  - [x] Mem.resident, IO.rchar, IO.wchar, Stat.utime, Net.IpExt:InOctets, Net.IpExt:OutOctets
    - already collected through the metrics collector, just needs proper configuration
    - as `cardano_node_metrics_{IO,Net}_*`
  - [x] connectedPeers
    - `[TraceLabelPeer peer BlockFetch.Decision.FetchDecision]`
      - `length` is the result
      - as `# TYPE cardano_node_peers_BlockFetchDecision_connectedPeers_int gauge`

**Comment by deepfire** [comment]
So, https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Node/TUI/LiveView.hs#L101 has all of what was listed, except for two elements:

> - [ ] a counter of how many blocks this node created since startup       
> - [ ] mempool metrcis (wait time, modify time) => "time-to-block" from benchmarking

**Comment by CodiePP** [comment]
OK, then these values need to be also forwarded to the EKG/Prometheus backend.

**Comment by deepfire** [comment]
It looks increasingly likely, that we should be able to avoid the need for a new backend -- by:

1. turning existing consensus tracers into metrics
2. creative use of tracer transfomers

**Comment by deepfire** [comment]
Regarding mempool metrics @dcoutts said so:
> I think we're interested in a few things, in roughly descending order of importance:
> 1. moment when tx is added into the mempool (stm atomically comits)
> 2. moment tx is removed from mempool
> 3. when tx is downloaded via the protocol (before attempting to add it to the mempool)
> 4. when we attempt to add it to the mempool (ie before we do the blocking stm transaction to try doing so)
> The closest thing to wait time is the time from point 4 to point 1. Usually that'll be small, but under back pressure it'll be long.
>
> And there are some others in the tx protocol, not directly related to the mempool.

**Comment by deepfire** [comment]
Current overview:
- mempool metrcis (wait time, modify time) => "time-to-block" from benchmarking
  - moment when tx is added into the mempool (stm atomically commits)
    - TraceMempoolAddTxs      mempoolSize accepted time
  - moment tx is removed from mempool
    - TraceMempoolRemoveTxs   mempoolSize (map fst removed) time
  - when tx is downloaded via the protocol (before attempting to add it to the mempool)
    - TraceTxSubmissionInbound -- not implemented yet
  - when we attempt to add it to the mempool (ie before we do the blocking stm transaction to try doing so)
    - TraceEventMempool
- mempool size (number of tx) => LiveView metrics
  - Mempool.API.TraceEventMempool
    - AddTxs + RejectedTxs + RemoveTxs + ManuallyRemovedTxs
      - ??? -> result
- a counter of the transactions that this node processed (since startup)
  - Mempool.API.TraceEventMempool
    - AddTxs + RejectedTxs + RemoveTxs + ManuallyRemovedTxs
      - accumulate lengths & values -> result
- a counter of how many blocks this node created since startup
  - Node.Tracers.TraceForgeEvent
    - ForgeEvent @slot
      - `counting` transformer gets the result
    - also has: CouldNotForge + AdoptedBlock + DidntAdoptBlock + ForgedInvalidBlock
- chain density, epoch, slot, block in epoch number
  - ChainDB.TraceAddBlockEvent -> ChainDB.SwitchedToChain
    - density, slotNum, blockNum, slotInEpoch, epoch -- a la carte
- all of the LiveView metrics
  - Mem.resident, IO.rchar, IO.wchar, Stat.utime, Net.IpExt:InOctets, Net.IpExt:OutOctets
    - already collected through the metrics collector, just needs proper configuration
  - connectedPeers
    - [TraceLabelPeer peer BlockFetch.Decision.FetchDecision]
      - `length` is the result

**Comment by deepfire** [comment]
Ok, initial implementation done, for all, except mempool metrics.

**Comment by CodiePP** [comment]
remaining work will be done in next sprint.
