### ISSUE TITLE
[BUG] - TraceMempool (and perhaps others?) config setting is ignored

### ISSUE THREAD

**Issue by weebl2000** [input-output-hk/cardano-node#3663]
**Internal/External**
*External* 

**Area**
*Other*  cardano-node tracing config

**Summary**
It seems TraceMempool configuration is ignored in cardano-node 1.34.0

**Steps to reproduce**
1. Upgrade to 1.34.0
2. Set TraceMepool to false in config

**Expected behavior**
I do not see mempool trace logging

**System info (please complete the following information):**
Ubuntu 20.04 x64, cardano-node 1.34.0 built from source

**Additional context**
I see a lot of changes regarding tracing. Should we configure this differently? Anyway, this seems to be a regression for 1.34.0 vs 1.33.0 at least.

**Comment by weebl2000** [comment]
https://github.com/input-output-hk/cardano-node/blob/master/configuration/cardano/mainnet-config-new-tracing.yaml relevant? Should we list this is in the changelog maybe? Seems like a heavy change if everyone needs to edit config to alter tracing.

**Comment by rdlrt** [comment]
The release notes (or QA process - maybe it does not include testing EKG metrics against configuration for hydra builds) are a bit rushed.

The new tracing infra is summarised with a reference to a PR in changelogs, the hydra config templates referred in release notes are not updated either🙁

**Comment by weebl2000** [comment]
> The release notes (or QA process - maybe it does not include testing comparison of EKG metrics against previous version given configuration for hydra builds) are a bit rushed.
> 
> The [new tracing infra](https://github.com/input-output-hk/cardano-node/blob/master/doc/New%20Tracing%20Quickstart.md) is summarised with a reference to a PR in changelogs, the hydra config templates referred in release notes are not updated eitherslightly_frowning_face

Quite a steep learning curve to understand how to configure tracing again. :( I'll try to figure out how to disable most of the trace logging which is pretty useless for day-to-day operation.

**Comment by weebl2000** [comment]
This should be fixed by #3668

**Comment by Jimbo4350** [comment]
Resolved in #3668
