### ISSUE TITLE
[BUG] - cardano-node on Windows hangs on start up if topology file is missing

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#3666]
External

**Area**
Start up

**Summary**
When I try to start up `cardano-node` on Windows as a relay and the topology file is missing, the node hangs without printing any error to give any hint as to the cause of the problem.

On MacOS and Linux if I do the same, I get the following helpful error:

```
cardano-node: FatalError {fatalErrorMessage = "Cardano.Node.Run.handleSimpleNodeNonP2P.readTopologyFile: Cardano.Node.Configuration.Topology.readTopologyFile: staging-topology.json: openBinaryFile: does not exist (No such file or directory)"}%
```

**Steps to reproduce**
On Windows, download and extract the following file and `cd` into the directory:

[staging.tar.gz](https://github.com/input-output-hk/cardano-node/files/8160233/staging.tar.gz)

Run `cardano-node`:

```
cardano-node run --topology staging-topology.json --database-path db --socket-path "\\\\.\\pipe\\cardano-node" --host-addr 0.0.0.0 --port 3000 --config testnet-config.json
```

`cardano-node` will hang after printing node-to-node versions:

```
node-to-node versions:
NodeToNodeV_6   HardForkNodeToNodeEnabled HardForkSpecificNodeToNodeVersion1 (EraNodeToNodeEnabled ByronNodeToNodeVersion2 :* EraNodeToNodeEnabled ShelleyNodeToNodeVersion1 :* EraNodeToNodeEnabled ShelleyNodeToNodeVersion1 :* EraNodeToNodeEnabled ShelleyNodeToNodeVersion1 :* EraNodeToNodeDisabled :* Nil)
...
NodeToClientV_12        HardForkNodeToClientEnabled HardForkSpecificNodeToClientVersion2 (EraNodeToClientEnabled ByronNodeToClientVersion1 :* EraNodeToClientEnabled ShelleyNodeToClientVersion5 :* EraNodeToClientEnabled ShelleyNodeToClientVersion5 :* EraNodeToClientEnabled ShelleyNodeToClientVersion5 :* EraNodeToClientEnabled ShelleyNodeToClientVersion5 :* Nil)
```

If this is run first:

```
mv staging-topology.json.bak staging-topology.json
```

Then the node starts properly.

**System info (please complete the following information):**
- OS Name: Windows
- OS Version: 10 Pro
- Node version: `1.34`

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
