### ISSUE TITLE
[FR] - Output leadership logs to json file

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-node#3678]
**Internal/External**
*External* 

**Area**
*Leadership Logs*  

**Describe the feature you'd like**
Add an option to write the result of the leadership logs to a file as a json object.

**Describe alternatives you've considered**
The current format is in table format which is not easy to consume in an application

**Context**
I'm wanting to use the built in leadership-logs that will be used in an application to automatically determine if a block was produced on schedule or if it was lost to another pool. Third party leadership-tools use a json output which is perfect for this use case.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
