### ISSUE TITLE
[BUG] - The value of kes-period-info is wrong.

### ISSUE THREAD

**Issue by btbf** [input-output-hk/cardano-node#3689]
**Internal/External**
*External*  

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
KES start, KES end, and KES Expiry date values are incorrect even after updating KES file and operational certificates.

**Steps to reproduce**
1. Generate KES file
```
cardano-cli node key-gen-KES \
    --verification-key-file kes.vkey \
    --signing-key-file kes.skey
```
2. Generate operational certificates
```
cardano-cli node issue-op-cert \
    --kes-verification-key-file kes.vkey \
    --cold-signing-key-file node.skey \
    --operational-certificate-issue-counter node.counter \
    --kes-period 403 \
    --out-file node.cert
```
3. Restart the node
4. Execute kes-period-info query
```
cardano-cli query kes-period-info \
  --testnet-magic 1097911063  \
  --op-cert-file node.cert
```

5. return value
```
✓ The operational certificate counter agrees with the node protocol state counter
✓ Operational certificate's kes period is within the correct KES period interval
{
    "qKesNodeStateOperationalCertificateNumber": 4,
    "qKesCurrentKesPeriod": 403,
    "qKesOnDiskOperationalCertificateNumber": 6,
    "qKesRemainingSlotsInKesPeriod": 3948705,
    "qKesMaxKESEvolutions": 62,
    "qKesKesKeyExpiry": "2022-04-22T08:20:16Z",
    "qKesEndKesInterval": 434,
    "qKesStartKesInterval": 372,
    "qKesSlotsPerKesPeriod": 129600
}
```

No matter how many times I update the KES file, the same values are displayed
    "qKesKesKeyExpiry": "2022-04-22T08:20:16Z",
    "qKesEndKesInterval": 434,
    "qKesStartKesInterval": 372,

By the way, the values of the metrics are as follows
```
curl localhost:12798/metrics | grep KES
```
cardano_node_metrics_operationalCertificateExpiryKESPeriod_int 465
cardano_node_metrics_currentKESPeriod_int 403
cardano_node_metrics_remainingKESPeriods_int 62
cardano_node_metrics_operationalCertificateStartKESPeriod_int 403

**Expected behavior**
return value is...
```
✓ The operational certificate counter agrees with the node protocol state counter
✓ Operational certificate's kes period is within the correct KES period interval
{
    "qKesNodeStateOperationalCertificateNumber": 4,
    "qKesCurrentKesPeriod": 403,
    "qKesOnDiskOperationalCertificateNumber": 6,
    "qKesRemainingSlotsInKesPeriod": 3948705,
    "qKesMaxKESEvolutions": 62,
    "qKesKesKeyExpiry": "2022-06-07 22:20:16Z",
    "qKesEndKesInterval": 465,
    "qKesStartKesInterval": 403,
    "qKesSlotsPerKesPeriod": 129600
}
```

**System info (please complete the following information):**
- OS Name:  Ubuntu
- OS Version 20.04
- Node version (output of `cardano-node --version`)
cardano-node 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23

- CLI version  (output of `cardano-cli --version`)
cardano-cli 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23

**Comment by rphair** [comment]
I can verify  this.  Here is the command that produced our operational certificate:

```
cardano-cli node issue-op-cert \
--kes-verification-key-file low/kes.06.vkey \
--cold-signing-key-file high/cold.skey \
--operational-certificate-issue-counter low/cold.06.counter \
--kes-period 402 \
--out-file high/node.06.cert
```

And here is the command output for that same operational certificate:

```
core$ cardano-cli query kes-period-info --mainnet --op-cert-file node.06.cert
✓ The operational certificate counter agrees with the node protocol state counter
✓ Operational certificate's kes period is within the correct KES period interval
{
    "qKesNodeStateOperationalCertificateNumber": 5,
    "qKesCurrentKesPeriod": 426,
    "qKesOnDiskOperationalCertificateNumber": 6,
    "qKesRemainingSlotsInKesPeriod": 1025362,
    "qKesMaxKESEvolutions": 62,
    "qKesKesKeyExpiry": "2022-03-20T21:44:51Z",
    "qKesEndKesInterval": 434,
    "qKesStartKesInterval": 372,
    "qKesSlotsPerKesPeriod": 129600
}
```

Note the KES period in which we were issued our op cert (402) is much later than the one reported as `qKesStartKesInterval` (372).  This leads to a significantly lower value for `qKesEndKesInterval` and a much earlier date for `qKesKesKeyExpiry` than expected (as if our key renewal is only valid for 48 days instead of the usual 93): 
```
core$ TZ=UTC; ls -l node.06.cert
-rw------- 1 spo spo 367 2022-02-01 03:15 node.06.cert
```

The figures from Prometheus metrics appear correct.  According to `cardano-cli query kes-period-info` we have only 8 KES periods remaining, while metrics report we have a full 38 KES periods to go, as expected:

```
core$ curl -s 127.0.0.1:12798/metrics | grep KES
cardano_node_metrics_operationalCertificateExpiryKESPeriod_int 464
cardano_node_metrics_currentKESPeriod_int 426
cardano_node_metrics_remainingKESPeriods_int 38
cardano_node_metrics_operationalCertificateStartKESPeriod_int 402
```

**Comment by adrem1** [comment]
Hi all,
I can confirm the above as well. Doing:
`cardano-cli query kes-period-info --mainnet --op-cert-file node.cert`

Results in:
`{
    "qKesNodeStateOperationalCertificateNumber": 1,
    "qKesCurrentKesPeriod": 430,
    "qKesOnDiskOperationalCertificateNumber": 1,
    "qKesRemainingSlotsInKesPeriod": 431027,
    "qKesMaxKESEvolutions": 62,
    "qKesKesKeyExpiry": "2022-03-20T21:44:51Z",
    "qKesEndKesInterval": 434,
    "qKesStartKesInterval": 372,
    "qKesSlotsPerKesPeriod": 129600
}`

Which is incorrect, as verifiable through prometheus metrics:
`cardano_node_metrics_operationalCertificateExpiryKESPeriod_int 491
cardano_node_metrics_currentKESPeriod_int 430
cardano_node_metrics_remainingKESPeriods_int 61
cardano_node_metrics_operationalCertificateStartKESPeriod_int 429`

**Comment by wutzebaer** [comment]
I have the same problem, after rotating the key the old values are still shown, but cardano_node_metrics_remainingKESPeriods_int shows the new value

**Comment by CarlosLopezDeLara** [comment]
fixed by https://github.com/input-output-hk/cardano-node/pull/3718
