### ISSUE TITLE
Weird KVM opcode issues when running the chairman

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-node#369]
When running the chairman using something like `nix-build -A nixosTests.chairmansCluster --show-trace --arg interactive false` or running the script `./scripts/cluster-test.sh`, I start getting weird errors back while the chairman is running:
```
machine# [   94.587073] traps: cardano-node[933] trap invalid opcode ip:f4f519 sp:7fffe3bb81c8 error:0
machine# [   94.592891] traps: cardano-node[941] trap invalid opcode ip:f4f519 sp:7ffc484625f8 error:0
machine# [   94.600043] traps: cardano-node[942] trap invalid opcode ip:f4f519 sp:7fff98fdeea8 error:0
```

The (short) log from the run can be found here - [kvm_opcode_issue.log](https://github.com/input-output-hk/cardano-node/files/3915880/kvm_opcode_issue.log)

The branch can be found here - https://github.com/input-output-hk/cardano-node/tree/ksaric/weird-kvm-opcode-issue

@deepfire categorized the issue as being "really weird", and "should not be happening", so I presume the issue is something to be looked at.

Not really happy sharing system info, but if it helps somebody - https://termbin.com/5yua

**Comment by deepfire** [comment]
Note that I wouldn't say it's necessarily KVM-related -- there is no evidence for that.

But one possibility, yes, is a KVM bug on Kristijan's machine (and indeed, his i7-8750H CPU is sufficiently featureful for having all the necessary opcodes).

**Comment by kevinhammond** [comment]
Still an issue?

**Comment by ksaric** [comment]
Running the latest version of the project, I still get:
```
machine# [  230.990375] traps: cardano-node-si[749] trap invalid opcode ip:1425319 sp:7ffc24dcae58 error:0 in cardano-node-simple[400000+14a3000]
machine# [  231.502010] systemd[1]: Started Process Core Dump (PID 1119/UID 0).
machine# [  231.663903] traps: cardano-node-si[752] trap invalid opcode ip:1425319 sp:7fff5da35f58 error:0 in cardano-node-simple[400000+14a3000]
machine# [  232.142757] systemd[1]: Started Process Core Dump (PID 1121/UID 0).
machine# [  232.431404] traps: cardano-node-si[751] trap invalid opcode ip:1425319 sp:7ffd1c699398 error:0 in cardano-node-simple[400000+14a3000]
machine# [  233.008351] traps: cardano-node-si[750] trap invalid opcode ip:1425319 sp:7fffb26eabd8 error:0 in cardano-node-simple[400000+14a3000]
machine# [  233.086422] traps: cardano-node-si[753] trap invalid opcode ip:1425319 sp:7ffcda2e9df8 error:0 in cardano-node-simple[400000+14a3000]
machine# [  234.019272] systemd[1]: Started Process Core Dump (PID 1123/UID 0).
machine# [  234.274743] systemd[1]: Started Process Core Dump (PID 1125/UID 0).
machine# [  234.358875] systemd[1]: Started Process Core Dump (PID 1124/UID 0).
machine# [  253.049689] traps: cardano-byron-p[1113] trap invalid opcode ip:fe72c9 sp:7ffe71e54428 error:0 in cardano-byron-proxy[400000+1091000]
machine# [  253.569545] systemd[1]: Started Process Core Dump (PID 1129/UID 0).
```

Whether this is an actual issue or just abnormality on my machine is unclear to me.

**Comment by Jimbo4350** [comment]
I'm closing this because the chairman has been rewritten in Haskell :smile:
