### ISSUE TITLE
Integrating with hardware signing devices

### ISSUE THREAD

**Issue by prutz1311** [input-output-hk/cardano-node#3690]
Is it possible to offload signing of Cardano transactions onto a hardware device holding the keypair like YubiHSM? To be able to do that, I assume, we need to know what is the bytestring that the signing algorithm gets applied to, that is, the way the transaction was serialized. We've tried looking into cardano-cli code and didn't find a lot of clues.

Running a command `cardano-cli transaction build ...` produces
a json file with `cborHex` field in it. That transaction can be
signed by running
`./cardano-cli transaction sign --tx-body-file txs/tx1.raw --signing-key-file data/payment.skey --testnet-magic 1097911063 --out-file txs/tx1.signed`.

To reproduce: the transaction and the keys

`txs/tx1.raw`
```
{
    "type": "TxBodyAlonzo",
    "description": "",
    "cborHex": "86a50081825820c19a35908da555b1e12c47adc5fa78a8be6bc48b9da36c22fa757002923cebe4000d80018282581d60c358d58360929e03646b0e0b5ae15504d300ecb79a9bea93ecceaec81a3b88fb97825839000743d16cfe3c4fcc0c11c2403bbc10dbc7ecdd4477e053481a368e7a06e2ae44dff6770dc0f4ada3cf4cf2605008e27aecdb332ad349fda71a000f4240021a00028c290e809fff8080f5f6"
}
```

`data/payment.skey`
```
{
    "type": "PaymentSigningKeyShelley_ed25519",
    "description": "Payment Signing Key",
    "cborHex": "5820e5ffc3d23eb982311f1afb1a062f12323888ba5b7816f10f0ed59c9923f59543"
}
```

`data/payment.vkey`
```
{
    "type": "PaymentVerificationKeyShelley_ed25519",
    "description": "Payment Verification Key",
    "cborHex": "58208e72e92ce08d4506b56fda19c08cc64322590f621131b43b9826e3493f8031ae"
}
```

We were not able to figure out
how the bytestring to sign gets obtained from the data structure
encoded in that CBOR string. Also we assumed that the signing algorithm
is the same as in `ed25519` Haskell package and `Crypto.PubKey.Ed25519`
module of `cryptonite` package and would like to confirm that.

The code at
https://github.com/input-output-hk/cardano-node/blob/bf8b0e1cebe9decfa6ca0b98c7513e8dd64b8333/cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs#L1012
https://github.com/input-output-hk/cardano-node/blob/bf8b0e1cebe9decfa6ca0b98c7513e8dd64b8333/cardano-api/src/Cardano/Api/Tx.hs#L543
does not appear to involve any signing at all,
just adding witnesses and applying data constructors.

**Comment by SebastienGllmt** [comment]
You may, depending on your coding experience, find it easier to read through the [Rust SDK](https://github.com/Emurgo/cardano-serialization-lib/pulls) instead

**Comment by gabrielKerekes** [comment]
Few other resources which might be helpful:
1. The CDDL spec for the transaction format ([Babbage CDDL](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl#L49))
2. [Trezor HW wallet cardano docs/code](https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/cardano/README.md#serialization-format).
3. [Ledger Cardano app](https://github.com/vacuumlabs/ledger-app-cardano-shelley)
4. An example of parsing cardano-cli output may be found in [cardano-hw-interop-lib](https://github.com/vacuumlabs/cardano-hw-interop-lib).

**Comment by janmazak** [comment]
I'm adding https://github.com/vacuumlabs/cardano-hw-cli as an example of a tool that facilitates signing txs on a HW wallet (Trezor or Ledger) and more-or-less seamlessly integrates with cardano-cli.
(Parsing serialized txs has been moved to [cardano-hw-interop-lib](https://github.com/vacuumlabs/cardano-hw-interop-lib) mentioned above.)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
