### ISSUE TITLE
[FR] - Node Version In Prometheus Metrics

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-node#3693]
**Internal/External**
*External*

**Area**
*Other*  - Prometheus Metrics

**Describe the feature you'd like**
The prometheus metrics is lacking the cardano-node version. While it's easy for small operators to keep track of their relays, it starts to become unmanageable when running half a dozen + node along with testnet nodes. Being able to monitor the node version through tools like Grafana would make keeping track easier to manage.

**Describe alternatives you've considered**
There is currently no alternative other than manually tracking node version.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by BrockCruess** [comment]
I would also love to see a node version metric added
