### ISSUE TITLE
[BUG] - flake follows non-existent input haskellNix/nixpkgs-2105

### ISSUE THREAD

**Issue by solomon-b** [input-output-hk/cardano-node#3703]
**Internal/External**
*External* 

**Area**
*Other*

**Summary**
I am using the nix flake as an input to build a nixos system. When I run `nix flake update`, I get an error about a non-existent input to `cardano-node`:

```
➜ nix flake update             
warning: Git tree '/home/solomon/Development/Nix/nixos-config' is dirty
error: input 'cardano-node/membench/cardano-node-snapshot/membench/cardano-node-snapshot/nixpkgs' follows a non-existent input 'haskellNix/nixpkgs-2105'
(use '--show-trace' to show detailed location information)
```

**Steps to reproduce**
1. Add the cardano-node flake as an input:
```
    cardano-node = {
      url = github:input-output-hk/cardano-node;
    };
```
2. Add the cardano-node module to your nixosSystem modules:
```
        myMachine = nixpkgs.lib.nixosSystem {
          inherit pkgs system;
          modules = [
            ./config/machines/sower
            nixpkgs.nixosModules.notDetected
            home-manager.nixosModules.home-manager
            cardano-node.nixosModules.cardano-node
          ];
          specialArgs = {
            inherit inputs;
          };
        };
```
3. Run `nix flake update`

**Expected behavior**
I would expect my flake lock to update successfully.

**System info (please complete the following information):**
- OS Name: Nixos
- OS Version 21.11
- Node version (output of `cardano-node --version`)
- CLI version  (output of `cardano-cli --version`)

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by L-as** [comment]
Update your version of Nix. This isn't an issue with cardano-node.

**Comment by solomon-b** [comment]
I'm on nixpkgs-21.11 using nix 2.5. Are you saying that cardano-node requires running nixpkgs-unstable?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
