### ISSUE TITLE
Create a cli flag specific to key formats

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#371]
Currently we use `Protocol` to talk about key formats: https://github.com/input-output-hk/cardano-node/blob/321622eab73438e5e2580d76cf4a414112e900f8/cardano-node/src/Cardano/CLI/Ops.hs#L40

We should have a flag specifically for key format that maps to an enumeration that's not the same as `Protocol`.

**Comment by kevinhammond** [comment]
Can we clear this one?

**Comment by Jimbo4350** [comment]
This has been resolved
