### ISSUE TITLE
Integration-level benchmark for the transaction generator

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/cardano-node#3713]
Benchmark the user time for generating 4000 transactions in stand-alone-mode

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/3726

**Comment by MarcFontaine** [comment]
This is the first benchmark.
More benchmarks are to be addes

**Comment by mgmeier** [comment]
Integrated and merged via PR #4467
