### ISSUE TITLE
[FR] - Add withdrawal to ScriptContextChecker.hs test

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#3720]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
Add withdrawal to ScriptContextChecker.hs test. Currently, [MyCustomRedeemer](https://github.com/input-output-hk/cardano-node/blob/master/plutus-example/src/Cardano/PlutusExample/ScriptContextChecker.hs#L74-L85) included all V1 TxInfo except for withdrawal.

**Describe alternatives you've considered**
N/A

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
