### ISSUE TITLE
[BUG] - Wrong transition from Shelley to Allegra

### ISSUE THREAD

**Issue by miguelaeh** [input-output-hk/cardano-node#3729]
**Internal/External**
*External*

**Area**
*devnet*

**Summary**

Following the scripts in this same repository, everything goes well from Byron (protocol version major 0) to Shelley (protocol version major 2) but when moving to Allegra (protocol version major 3) even though the ledger-state changes and the ledger is properly updated, the era continues being Shelly instead of Allegra.

**Steps to reproduce**

I followed the steps [here](https://github.com/input-output-hk/cardano-node/tree/master/scripts/byron-to-alonzo).

After submitting the update proposal I set `LastKnownBlockVersion-Major = 3` and reboot the nodes.

**Expected behavior**

I expect to see `Allegra` when executing `cardano-cli query tip`, but instead I continue getting `Shelley` no matter the protocol version.

From the query tip command:
```
{
    "era": "Shelley",
    "syncProgress": "100.00",
    "hash": "2c455892f9696e6e599ebf3ec012aa662f4d1eaff2e25ef3ac0aeb687b6748c2",
    "epoch": 21,
    "slot": 25190,
    "block": 24045
}
```

From the ledger-state:

```
...
        "esPrevPp": {
            "poolDeposit": 300000000,
            "extraEntropy": {
                "tag": "NeutralNonce"
            },
            "minUTxOValue": 1000000,
            "minPoolCost": 100000000,
            "nOpt": 150,
            "keyDeposit": 2000000,
            "maxBlockHeaderSize": 1100,
            "minFeeB": 1000,
            "a0": 0.2,
            "rho": 0.0,
            "tau": 0.0,
            "protocolVersion": {
                "minor": 0,
                "major": 3                                 <- Note this is the Allegra version, but cardano-cli returns Shelley
            },
            "eMax": 18,
            "decentralisationParam": 1.0,
            "maxTxSize": 16384,
            "minFeeA": 3,
            "maxBlockBodySize": 65536
        }
...
```

**System info (please complete the following information):**
- OS Name: Debian
- OS Version: 10 (Buster)
- Node version (output of `cardano-node --version`): 1.34.1, I also tested 1.32 and obtained the same behaviour
- CLI version  (output of `cardano-cli --version`): 1.34.1, I also tested 1.32 and obtained the same behaviour

**Screenshots and attachments**

**Additional context**

**Comment by miguelaeh** [comment]
Adding a bit more information, if instead of doing the process by voting, I use the `TestAllegraHardForkAtEpoch` option, it works fine.
So looks like when doing it by voting the hard fork event for Allegra is not launched when the ledger is updated to version 3.

**Comment by Jimbo4350** [comment]
> After submitting the update proposal 

Which update proposal script? Please be specific. How many epochs have you waited after you submitted the update proposal?

**Comment by miguelaeh** [comment]
> Which update proposal script?

The third script. I.e [this](https://github.com/input-output-hk/cardano-node/blob/master/scripts/byron-to-alonzo/update-3.sh).
In any case, I don't think the used script matters as far as submitting a protocol update that exclusively changes the version major from `2` to `3` should produce the same behavior.

The steps are:
1. Submitting the update.
2. Update `LastKnownBlockVersion-Major` and set it to `3`.
3. Reboot BFT nodes.
4. Wait for the next epoch.

I have tested also waiting for the next epoch before rebooting the nodes, then rebooting the nodes and waiting another epoch, but I get the same result.

> How many epochs have you waited after you submitted the update proposal?

Around 10-15, but `cardano-cli` never shows the new era, even though the ledger state reflects version `3`.

**Comment by miguelaeh** [comment]
The issue is not resolved yet, could you please re-open it?

**Comment by miguelaeh** [comment]
I found the problem. Looks like it is due to the `securityParameter`. It turns out that if I decrease that parameter the upgrade will be fine. After some testing, I found a relationship between this parameter and the `epochLength` and `activeSlotCoeff`.
Setting the `securityParameter` to a value lower than the average blocks on an epoch worked fine in all the scenarios I tested, so looks like that was the issue.
@Jimbo4350 could you confirm that is correct?
