### ISSUE TITLE
Fix ProtocolMagicIdMismatch in shelley-testnet.sh script

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#373]
When running: 

`./scripts/shelley-testnet.sh `

I got an error for node 0: 

`cardano-node: ProtocolMagicIdMismatch "/home/artur/tasks/test-node-instructions/cardano-node/db-0/protocolMagicId" (ProtocolMagicId {unProtocolMagicId = 764824073}) (ProtocolMagicId {unProtocolMagicId = 459045235})`

Steps to reproduce:

I followed instructions from here (Section: Shelley Testnet > Startup testnet): https://github.com/input-output-hk/cardano-node/tree/master/cardano-node

protocolMagicId file for node 1 and node 2 have inside of it the same value 459045235. For node 0 it is 764824073.

**Comment by mrBliss** [comment]
You'll get this error when there's already a database on disk with a different `ProtocolMagicId` (so from a different *net).

Solution: delete or rename the `db-0` folder.
