### ISSUE TITLE
[FR] - Export TxIns type synonym

### ISSUE THREAD

**Issue by phadej** [input-output-hk/cardano-node#3732]

**Comment by CarlosLopezDeLara** [comment]
@phadej Would you like to add some additional information? Why should this feature exist?

**Comment by phadej** [comment]
Because now I have to write `... -> (Api.TxIn, Api.BuildTxWith Api.BuildTx (Api.Witness Api.WitCtxTxIn Api.AlonzoEra))` as the handy type synonym is not exported.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
