### ISSUE TITLE
jormungandr 0.8.0-rc5-cecea4d got stuck on synchronisation

### ISSUE THREAD

**Issue by bohenicus** [input-output-hk/cardano-node#374]
I've registered problem with node stopping synchronisation in other topic:
[(https://github.com/input-output-hk/jormungandr/issues/1273)]

but maybe here is better place for issues related to nodes.

**Comment by mrBliss** [comment]
> [..]
> 
> but maybe here is better place for issues related to nodes.

No, I believe the jormungandr repository is the right place for issues related to jormungandr. This repository is for the node written in Haskell.
