### ISSUE TITLE
[BUG] - cardano-node fails without an error message when reading badly formated JSON (topology.json)

### ISSUE THREAD

**Issue by kiriakos** [input-output-hk/cardano-node#3743]
**Internal/External**
*External* 

**Area**
*Other:*  Node Operations

**Summary**
The 1.34.1 `cardano-node` executable fails with exit code 1 and no indication for the reason when the file passed to the `--topology` argument is badly formated JSON. (eg: erroneous or missing comma in the `Producers` array).

**Steps to reproduce**
Use this topology.json:
```json
{
  "Producers": [
    {
      "addr": "cnwr-2.services.kindstudios.gr",
      "port": 25437,
      "valency": 1
    }
    {
      "addr": "cnwr-3.services.kindstudios.gr",
      "port": 25437,
      "valency": 1
    }
  ]
}
```

**Expected behavior**
A clear and concise description of what failed in the cardano-node log. Since usage of programmatically generated topology files it widespread I think it could be helpful for Operators to know what's going on a bit earlier. Toubleshooting startup problems can be cumbersome.

**System info (please complete the following information):**
- OS Name: Deb, Nix, Arch
- OS Version multiple
- Node version 1.34.1

**Comment by LudvikGalois** [comment]
When attempting to reproduce on master, I get

```
cardano-node: FatalError {fatalErrorMessage = "Cardano.Node.Run.handleSimpleNodeNonP2P.readTopologyFile: Is your topology file formatted correctly? Expecting Non-P2P Topology file format. The port and valency fields should be numerical. If you specified the correct topology file make sure that you correctly setup EnableP2P configuration flag. Error in $: Failed reading: satisfy. Expecting object value at '{'"}
```

so I believe this has already been fixed.
