### ISSUE TITLE
membench: per-commit benchmarks fo the new tracing system

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3748]
We ought to enable comparative per-commit benchmarks of the new tracing system vs. the legacy one.

**Comment by deepfire** [comment]
This is mostly done, even functional, except that it turned out that we need to revisit the CI implementation -- because of the flake circularity issues described in  https://github.com/input-output-hk/cardano-node/issues/3749

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
