### ISSUE TITLE
RTView: Stake/Delegators/Rewards details

### ISSUE THREAD

**Issue by denisshevchenko** [input-output-hk/cardano-node#3760]
_Corresponds to previous issue CAD-2481_.

In order to be 1 place for getting all the details about a stake pool, it would be nice to have different tabs for displaying:

1. number of delegators and their stake (per epoch)
2. active and live stake for the stake pool (per epoch)
3. rewards received by the stake pool (per epoch)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
