### ISSUE TITLE
[BUG] - cardano-node tries to resolve and connect to AAAA DNS records even if only IPv4 host listen address is configured

### ISSUE THREAD

**Issue by weebl2000** [input-output-hk/cardano-node#3781]
**Internal/External**
*External* 

**Area**
*Other*   Node connectivity

**Summary**
cardano-node tries to resolve/connect over IPv6 AAAA DNS records even if IPv6 is explicitly disabled.

**Steps to reproduce**
1. Have an IPv6 enabled machine
2. Add a producer by hostname which has an AAAA record.

**Expected behavior**
cardano-node should either:

- not resolve the AAAA records of the DNS name if it is IPv6 capable but only IPv4 host address is configured, and vice versa.
- **BUT IDEALLY** cardano-node should be able to have an IPv4 listen address only, but still be able to make IPv6 outbound connections!

**Screenshots and attachments**
It was reported in this thread: 

https://forum.cardano.org/t/domain-relays-new-cardano-testnet-iohkdev-io-unsupported-remote-target-address-2a0532100-3-3001/99231/1

**Additional context**

Unfortunately I kind of saw this problem arise a year ago when I saw that cardano-node will not be IPv6 capable if only IPv4 host listen address is configured. That's why I submitted this PR https://github.com/input-output-hk/cardano-node/pull/2773 a year go, but it was not deemed necessary. 

Imho the solution is that we should make the cardano-node be able to connect over both IPv4 and IPv6 outbound, without having to specify a listen address for both IPv4 and IPv6.

**Comment by Uli999** [comment]
Any new on this item? Is there a workaround? I'm on Linux-server with IPV6 enabled and looks like I have the same problem.
[startnode.log](https://github.com/input-output-hk/cardano-node/files/9188004/startnode.log)

**Comment by Uli999** [comment]
Upgraded from 1.35.1 to 1.35.2 and it seems to work now.

**Comment by Jimbo4350** [comment]
@weebl2000 please move this to https://github.com/input-output-hk/ouroboros-network

**Comment by weebl2000** [comment]
> @weebl2000 please move this to https://github.com/input-output-hk/ouroboros-network. Any issues networking related should be opened there.

https://github.com/input-output-hk/ouroboros-network/issues/4130
done
