### ISSUE TITLE
tx-generator: make node configuration file a CLI argument

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/cardano-node#3784]

**Comment by MarcFontaine** [comment]
At the moment the tx-generator reads all its configuration parameters from a single JSON configuration file.
This includes the file path of the node configuration file.
On request of users of the tx-generator the path of the node-configuration file should become an explicit CLI argument.
(For some reason.)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
