### ISSUE TITLE
RTView: gathering requirements

### ISSUE THREAD

**Issue by denisshevchenko** [input-output-hk/cardano-node#3801]
This issue is a place where we can collect all the requirements for the brand new RTView.

**Comment by denisshevchenko** [comment]
1. Show basic information about connected nodes.
2. Show sync progress for nodes.
3. Show blockchain information (epoch, slot, block forging, chain density).
4. Show KES information.
5. Show nodes' peers.
6. Show nodes' errors.
7. Show transactions information.
8. Show different metrics charts (like CPU and memory).
9. Ability to compose metrics charts: show metric values from few nodes on the same chart (like Grafana does).
10. Stake/Delegators/Rewards information.
11. Notifications about particular events/problems.
12. UI dark/light theme.

**Comment by denisshevchenko** [comment]
The comment from Dorin Solomon:

as a small SPO, besides the above ones, I would be interested to see:
the below metrics as time series (on X axis having the time in UTC) with option to zoom in/out on specific time intervals (from minutes to days):
x_over_time(cardano_node_metrics_epoch_int[$__interval])
cardano_node_metrics_blockNum_int
cardano_node_metrics_slotInEpoch_int
node uptimes
time() - cardano_node_metrics_nodeStartTime_int
KES info as:
kes current
op cert start kes
kes expiry
remaining kes
days until opcert expiries
counter value from the opcert
counter value from chain
time until current epoch ends
432000 - cardano_node_metrics_slotInEpoch_int
tx processed by the node - time series
mempool transactions - time series
leadership stats for the producer
blocks forked, not-valid, etc
leadership check
not being leader
missed slots
leadership schedule for the current and for the next epoch
Maybe in a second iteration, it would be nice to have features like:
the posibility to add node metrics, select the graph type you want and display those selected metrics (even more, the metrics could be selected from a drill down - from the list of available ones)
the posibility to change the layout - as in Grafana - to move each section/graph where you want
the posibility to hide/show specific visuals

**Comment by denisshevchenko** [comment]
![spo2](https://user-images.githubusercontent.com/5082435/163825691-68b5da6b-d3b6-40cb-bfe2-d0bc7c216d9c.jpeg)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
