### ISSUE TITLE
tracing: comparative profiling and benchmarkig of the tracing systems

### ISSUE THREAD

**Issue by jutaro** [input-output-hk/cardano-node#3806]
We currently have micro-benchmarks, which tests the performance of some functionality. And we have benchmarks, that tests the general performance of the whole system. What is missing is a way to benchmark a well defined run in a complete node, and to get some comparable timing for a relative small time period. This will enable us to use profiling to optimize the runtime and test the result with comparing between runs. As we will use this first for optimizing the new tracing system, we believe this approach will be helpfull in different contexts to optimize performance.

**Comment by Jimbo4350** [comment]
Closing. Please re-open if still relevant.
