### ISSUE TITLE
[BUG] - 'cabal build all' fails on latest master

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#3844]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Build node using Cabal

**Summary**
Building the node with cabal fails with the bellow error:
```
cabal: Could not resolve dependencies:
[__0] trying: cardano-crypto-class-2.0.0 (user goal)
[__1] rejecting: cardano-crypto-class:+secp256k1-support (conflict: pkg-config
package libsecp256k1-any, not found in the pkg-config database)
[__1] rejecting: cardano-crypto-class:-secp256k1-support (manual flag can only
be changed explicitly)
[__1] fail (backjumping, conflict set: cardano-crypto-class,
cardano-crypto-class:secp256k1-support)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class,
cardano-crypto-class:secp256k1-support
```

**Steps to reproduce**
```
cd cardano-node
git checkout master
git pull origin master
cabal clean
cabal update
cabal build all
```

**Expected behavior**
Following the official instructions/docs, it should be possible to successfully build with cabal.

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]
- Node version (output of `cardano-node --version`)
- CLI version  (output of `cardano-cli --version`)

**Comment by nc6** [comment]
Are you running this inside a nix shell? (Using `nix develop`?)

**Comment by mesudip** [comment]
you are required to install this secp251k1 library for the latest version

https://github.com/bitcoin-core/secp256k1

**Comment by HenryAeon** [comment]
I received this same error. Libsodium was installed in the wrong folder. Try reinstalling it in the one directory above the cardano code and same user.

**Comment by dorin100** [comment]
duplicate on https://github.com/input-output-hk/cardano-node/issues/3846

**Comment by rchak007** [comment]
> you are required to install this secp251k1 library for the latest version
> 
> https://github.com/bitcoin-core/secp256k1

I installed from the link - 
https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md
the "Download and install libsecp256k1:" part.
then I was able to proceed further from this issue.
