### ISSUE TITLE
Document build steps for pure cabal setups

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#3846]
Building with `cabal` on `linux` requires a non trivial setup.  One needs to:

* install `libsecp256k1` with correct configuration flags
* install `libsodium` from the right branch or using the right cabal flags
* install `libsystemd`

A good starting point are instructions from this [README.md](https://github.com/input-output-hk/cardano-haskell#system-setup=).

**Comment by CarlosLopezDeLara** [comment]
This PR solves this https://github.com/input-output-hk/cardano-node/pull/3796
