### ISSUE TITLE
How we get Policyscript from a CBOR HEX format ? 

### ISSUE THREAD

**Issue by rajeevbbqq** [input-output-hk/cardano-node#3856]
**Internal**
*External*   otherwise.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
How do we get Policyscript from a CBOR HEX format? We created CBOR hex from the CLI, now we are checking how to retrieve the policy script which is the required parameter to pass from dapp while burning/minting tokens along with policy id.

Plutuscript we have.
`{
    "type": "PlutusScriptV1",
    "description": "",
    "cborHex": "590b71590b6e010000333323322332233322232323233322233322233333333222222223322333332222233332222333222332233223322333222332233223322332233223232332232323232323232323232323322323232323232323232323232323232323232323232323232323232323232322223355032350040142232323233030333502e02d35502c50010065335304c3302b35502a50014800041384cc0c0cc0854008020cc0c0cc085400801cccd40bc0b402001c54cd4d41a8cd540d80c4c0c140044c00858884d4d5540d80088894cd4d41bc0104cd541d4008004884c024584c0d80088d41992401206578706563746564206f6e6c79206f6e65206d696e74696e6720706f6c69637900122223005330033004002300600125335304300110661350603530653357389201025064000664988c8c8c8c8c8c8cccd5cd19b8735573aa00a90001280112803a4c26606aa002a0042600c6ae8540084c050d5d09aba25001135573ca00226ea80084d417d262323232323232323232323232323232323232323232323333573466e1cd55cea80aa40004a0044a02e93099999999998232800a8012801a8022802a8032803a8042804a805099a81080b1aba15012133502001635742a0202666aa032eb94060d5d0a8070999aa80c3ae501735742a018266a03a0426ae8540284cd4070cd54078085d69aba15008133501675a6ae8540184cd4069d71aba150041335019335501b75c0346ae8540084c080d5d09aba25001135744a00226ae8940044d5d1280089aba25001135744a00226ae8940044d5d1280089aba25001135573ca00226ea80084d41792623232323232323333573466e1cd55cea802a40004a0044a00e9309981ba800a8010980b9aba1500213005357426ae8940044d55cf280089baa00213505d4988c8c8c8c8c8c8c8c8cccd5cd19b8735573aa00e90001280112804a4c2666074a002a004a006260106ae8540104ccd54029d728049aba15002133500775c6ae84d5d1280089aba25001135573ca00226ea80084d41712623232323232323333573466e1cd55cea802a40004a0044a00e9309981ca800a8010980a1aba150021335005012357426ae8940044d55cf280089baa00213505b498488c8c8c8c8c8c8cccd5cd19b8750044800094008940112613503c500113006357426aae79400c4cccd5cd19b87500148008940e89401126135573aa00226ea80084d416d261335500175ceb444888c8c8c004dd58019a80090008918009aa832111919191919191999aab9f0075506425002069133506550025001130063574400a266aa0d0a002a004260106aae7540084c018d55cf280089aba10011223232323232323333573466e1cd55cea802a40004a0044a00e93099a81da800a801099a8038031aba150021335007005357426ae8940044d55cf280089baa002135058498488c8c8c8c8c8c8cccd5cd19b8735573aa00a90001280112803a4c266a07ca002a004266a01000c6ae8540084c020d5d09aba25001135573ca00226ea80084d415d261223232323232323333573466e1cd55cea802a40004a0044a00e93099a81da800a801099a8038031aba1500213007357426ae8940044d55cf280089baa002135056498488c8c8c8c8c8c8c8cccd5cd19b8750054801094110940092613333573466e1d4011200225002250044984d410d40044c018d5d09aab9e500313333573466e1d4005200025041250044984d55cea80089baa0021350554988c8c8c8cccd5cd19b8750024800880f0940092613333573466e1d40052000203a250034984d55ce9baa002135053498488c8c8c004dd60019a80090008918009aa82e911999aab9f0012505b233505a30063574200460066ae88008170800444888c8c8c8c8c8c8cccd5cd19b8735573aa00a90001280112803a4c266aa0bea002a0042600e6ae8540084c014d5d09aba25001135573ca00226ea80084d414926232323232323232323232323232323333573466e1d4029200625002250044984c12940044c038d5d09aab9e500b13333573466e1d401d200425002250044984c11540044c030d5d09aab9e500813333573466e1d4011200225002250044984c10540044c02cd5d09aab9e500513333573466e1d4005200025003250064984d55cea8018981fa80089bae357426aae7940044dd500109a827a4c4646464646464646464646464646464646464646464646464646666ae68cdc3a80aa401840b84a0049309999ab9a3370ea0289005102e1280124c26666ae68cdc3a809a40104a0044a00c9309982b2800a80109bae35742a00426eb4d5d09aba25001135573ca02426666ae68cdc3a8072400c4a0044a00c930998292800a80109bae35742a00426eb8d5d09aba25001135573ca01a26666ae68cdc3a804a40084a0044a00c93099828a800a801098069aba150021375c6ae84d5d1280089aab9e500813333573466e1d4011200225002250044984c13540044c020d5d09aab9e500513333573466e1d4005200025003250064984d55cea80189823a800898021aba135573ca00226ea80084d41392623232323232323232323232323333573466e1d4021200225002250084984ccc14940054009400c4dd69aba150041375a6ae8540084dd69aba135744a00226ae8940044d55cf280289999ab9a3370ea0029000128019280324c26aae75400c4c12d40044c010d5d09aab9e50011375400426a09a93119191919191919191999ab9a3370ea0089001128011280224c260a0a00226eb8d5d09aab9e500513333573466e1d4005200025003250064984d55cea80189826a80089bae357426aae7940044dd500109a82624c46464646464646666ae68cdc39aab9d500548000940089401d26133040500150021300635742a00426eb4d5d09aba25001135573ca00226ea80084d412d2623232323333573466e1cd55cea801240004a0044a0089309bae357426aae7940044dd500109a82524c446a60380044444444444a66a6a05c666aa601e24002a01a4a66a6070666ae68cdc780600081d01c89a8188008a8180019081d081c099a803a800a811091299a9a8110011080188009a80090008918009aa827110891911299a9a82680089a80400211099a8029802001199aa98040900080300200089a803000891a9a80180091000891a9a801000910010910919800801801090008891a9aa8238009100091199ab9a3371000400204a0482246a6aa08a0024400444666ae68cdc7801000811811090008911299a9810198018010008810881111299a980f0010800880f91a9805800911111111100391a801091199aa802911a9aa82180111199aa804911a9aa82380111299a9812999ab9a3370e00290000138130801899805199aaa8078030010008018018008008018919a800a81d281d889119190009a80090008918009aa82091299a9a81e00088021109980380118020008889110919980080200180108890008891180100091a9801000910011109198008018011000911111111109199999999980080580500480400380300280200180110009109198008018011000911091998008020018011000910919800801801100089091180100188910008900089109198008018010900089109198008018010900089109198008018010900089100109100090008909111801802089110010891100089000909111180200290911118018029091111801002909111180080290009109198008018011000909111111180380411091111111980300480410911111118028040911111100209111111001910911111119801004804110911111119800804804100090911801001911091199800802802001900090911801001909118008019000891a8011a980399ab9c00100849849844940104488008488488cc00401000c48004480048004448848cc00400c008448004448c8c00400488cc00cc00800800522011c1487b3f5a9b762f1777c6215a98d811949964268d66a22cfc6c589c60048811ca51a75a81478e38bfb9a847be8c0f9314a74cc66e4ddad416dbf918f00488104414749580001"
}`

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]
- CLI version  1.33.0

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
