### ISSUE TITLE
[FR] - Show slotInEpoch in cardano-cli query tip

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#3878]
Internal

Area
Other CLI

Describe the feature you'd like
Show slotInEpoch in cardano-cli query tip output so that one can easily know beforehand (and automate) if is still within the window for submitting transactions like Update proposals and MIR.

Additional context / screenshots

https://input-output-rnd.slack.com/archives/G011N23CEAE/p1652967091248049

_______
### Acceptance Criteria 

Slot in epoch is the slot number within a given epoch, as opposed to the absolute slot number. 

When the user queries the tip of the chain:

-  query tip returns     "slotInEpoch": 

{
    "era": "Alonzo",
    "syncProgress":
    "hash": 
    "epoch": 
    "slot":
    "block":
    "slotInEpoch": 
}

- slotinEpoch restarts properly at every epoch transition
- slotinEpoch can never be greater than EpochLength

**Comment by Jimbo4350** [comment]
So this involves changing the JSON output of the `query tip` to include the current slot in the current epoch. This is different to what is already reported, the absolute slot value. This will be a little tricky as the epoch size changes as we move from Byron -> Shelley:
```
defaultByronEpochSlots :: Word64
defaultByronEpochSlots = 21600
```
and in the mainnet shelley genesis file 
```
  ...
  "networkMagic": 764824073,
  "epochLength": 432000,
  "systemStart": "2017-09-23T21:44:51Z",
  ...
```
We should be able to take the result of `slotToEpoch` and subtract one from the other `SlotsInEpoch` - `SlotsToEpochEnd` to get the current slot in epoch.
