### ISSUE TITLE
[BUG] - vasil-testnet-v1 - CLI queries "kes-period-info", "protocol-state" and "leadership-schedule" are broken

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3883]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
In Alonzo era, with the `vasil-testnet-v1` tag, the CLI queries `kes-period-info`, `protocol-state` and `leadership-schedule` fail with

```
FatalError {fatalErrorMessage = ... currentlyBroken ...
```

E.g.

```
$ cardano-cli query kes-period-info --op-cert-file pool2_invalid_opcert_file.opcert --testnet-magic 42 --cardano-mode
cardano-cli: FatalError {fatalErrorMessage = "runQueryKesPeriodInfo: currentlyBroken - opCertOnDiskAndStateCounters ptclState opCert"}

$ cardano-cli query protocol-state --testnet-magic 42 --cardano-mode
cardano-cli: FatalError {fatalErrorMessage = "currentlyBroken: runQueryProtocolState writeProtocolState mOutFile result"}

$ cardano-cli query leadership-schedule --genesis ...
cardano-cli: FatalError {fatalErrorMessage = "runQueryLeadershipSchedule: currently broken"}'
```

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: `vasil-testnet-v1`
________________________________________________________

TASKS: 
- [x] kes-period (https://github.com/input-output-hk/cardano-node/pull/3945)
- [x] protocol-state https://github.com/input-output-hk/cardano-node/pull/4102
- [x] leadership schedule in Babbage  https://github.com/input-output-hk/cardano-node/pull/4106

**Comment by Jimbo4350** [comment]
A solution was merged by the consensus team: https://github.com/input-output-hk/ouroboros-network/pull/3758#issuecomment-1133037072
I'll link my PR here when it's ready

**Comment by CarlosLopezDeLara** [comment]
- [x] kes-period (https://github.com/input-output-hk/cardano-node/pull/3945)
- [ ] protocol-state
- [ ] leadership schedule

**Comment by newhoggy** [comment]
There is a separate issue tracking the `leadership-schedule` command.

**Comment by CarlosLopezDeLara** [comment]
Resolved in https://github.com/input-output-hk/cardano-node/pull/4106
