### ISSUE TITLE
[BUG] - PlutusScriptV1 is not supported in Babbage

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3886]
*Internal*

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
Building babbage-era transaction with Plutus script in Babbage era fails with

```
Command failed: transaction build  Error: The script language PlutusScriptLanguage PlutusScriptV1 is not supported in the Babbage era.
```

~~Building alonzo-era transaction with Plutus script in Babbage era fails ...~~ - replaced by https://github.com/input-output-hk/cardano-node/issues/3897

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: `vasil-testnet-v1`

**Additional context**
According to @ch1bo it is fixed by https://github.com/input-output-hk/cardano-node/pull/3882

**Comment by ch1bo** [comment]
The `The script language PlutusScriptLanguage PlutusScriptV1 is not supported in the Babbage era.` is likely expected by the fact that `PlutusScriptV1` was not listed in `scriptLanguageSupportedInEra` over [here](https://github.com/input-output-hk/cardano-node/pull/3882/files#diff-d2926b61bd606dc6c5e96c7607110c554a255cf353852708e0ecbbcc3ccbc4f0R628-R629).

At least that part should be fixed by PR #3882. Not sure about the second part about `Decentralization value required in Alonzo era`

**Comment by ch1bo** [comment]
> Similar error for SimpleScriptV1
And likely also SimpleScriptV2 ;)

**Comment by mkoura** [comment]
@ch1bo Exactly :-)
```
Command failed: transaction build-raw  Error: The script language SimpleScriptLanguage SimpleScriptV2 is not supported in the Babbage era.
```

**Comment by dorin100** [comment]
the same error is shown also when minting multi assets without Plutus scripts:
```
mkdir -p policy
cardano-cli address key-gen \
    --verification-key-file policy/policy.vkey \
    --signing-key-file policy/policy.skey

KEYHASH=$(cardano-cli address key-hash --payment-verification-key-file policy/policy.vkey)

SCRIPT=policy/policy.script
rm -f $SCRIPT
echo "{" >> $SCRIPT
echo "  \"keyHash\": \"${KEYHASH}\"," >> $SCRIPT
echo "  \"type\": \"sig\"" >> $SCRIPT
echo "}" >> $SCRIPT

cardano-cli transaction policyid --script-file policy/policy.script > policy/policyID
policyid=$(cat policy/policyID)
tokenname=$(echo -n "test_token_babbage" | xxd -b -ps -c 80 | tr -d '\n')

cardano-cli transaction build \
    --babbage-era \
    --testnet-magic $MAGIC \
    --tx-in 4749dd0dfffb4eb6594b5cb1e0a7bbcdc741fed79a1a80fa70d49f191d02e8de#0 \
    --change-address $(cat addr/addr1.addr) \
    --tx-out "$(cat addr/addr1.addr)+100000000+500 $policyid.$tokenname" \
    --mint="500 $policyid.$tokenname" \
    --minting-script-file $SCRIPT \
    --witness-override 2 \
    --out-file tx1_ma.txbody 

Command failed: transaction build  Error: The script language SimpleScriptLanguage SimpleScriptV1 is not supported in the Babbage era.
```

**Comment by Jimbo4350** [comment]
Closed with permission of @mkoura
