### ISSUE TITLE
[BUG] - `MuxError MuxBearerClosed` for `PastHorizon` error

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3895]
*Internal*

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
In Babbage era, when Plutus transaction is submitted with ttl (`invalid_hereafter`) too far in the future, submit fails with
```
MuxError MuxBearerClosed "<socket: 11> closed when reading data, waiting on next header True
```
This is not indicative of what is the actual issue. In node log files there's following error:

> [toolbox:cardano.node.LocalErrorPolicy:Error:64] [2022-05-24 10:01:27.93 UTC] IP LocalAddress "./state-cluster0/bft1.socket@700" ErrorPolicyUnhandledApplicationException (EpochErr "PastHorizon {pastHorizonCallStack = [(\"runQuery\",SrcLoc {srcLocPackage = \"ouroboros-consensus-0.1.0.0-3WJNO431PEsEUwRPtCeeUr\", srcLocModule = \"Ouroboros.Consensus.HardFork.History.Qry\", srcLocFile = \"src/Ouroboros/Consensus/HardFork/History/Qry.hs\", srcLocStartLine = 430, srcLocStartCol = 44, srcLocEndLine = 430, srcLocEndCol = 64}),(\"interpretQuery\",SrcLoc {srcLocPackage = \"ouroboros-consensus-0.1.0.0-3WJNO431PEsEUwRPtCeeUr\", srcLocModule = \"Ouroboros.Consensus.HardFork.History.EpochInfo\", srcLocFile = \"src/Ouroboros/Consensus/HardFork/History/EpochInfo.hs\", srcLocStartLine = 45, srcLocStartCol = 50, srcLocEndLine = 45, srcLocEndCol = 68}),(\"interpretQuery'\",SrcLoc {srcLocPackage = \"ouroboros-consensus-0.1.0.0-3WJNO431PEsEUwRPtCeeUr\", srcLocModule = \"Ouroboros.Consensus.HardFork.History.EpochInfo\", srcLocFile = \"src/Ouroboros/Consensus/HardFork/History/EpochInfo.hs\", srcLocStartLine = 39, srcLocStartCol = 9, srcLocEndLine = 39, srcLocEndCol = 52}),(\"epochInfoSlotToRelativeTime_\",SrcLoc {srcLocPackage = \"cardano-slotting-0.1.0.0-6VyoKllhKMr9HEkTJGSq3p\", srcLocModule = \"Cardano.Slotting.EpochInfo.API\", srcLocFile = \"src/Cardano/Slotting/EpochInfo/API.hs\", srcLocStartLine = 62, srcLocStartCol = 9, srcLocEndLine = 62, srcLocEndCol = 37}),(\"epochInfoSlotToRelativeTime\",SrcLoc {srcLocPackage = \"cardano-slotting-0.1.0.0-6VyoKllhKMr9HEkTJGSq3p\", srcLocModule = \"Cardano.Slotting.EpochInfo.API\", srcLocFile = \"src/Cardano/Slotting/EpochInfo/API.hs\", srcLocStartLine = 125, srcLocStartCol = 40, srcLocEndLine = 125, srcLocEndCol = 70}),(\"epochInfoSlotToRelativeTime_\",SrcLoc {srcLocPackage = \"cardano-slotting-0.1.0.0-6VyoKllhKMr9HEkTJGSq3p\", srcLocModule = \"Cardano.Slotting.EpochInfo.API\", srcLocFile = \"src/Cardano/Slotting/EpochInfo/API.hs\", srcLocStartLine = 62, srcLocStartCol = 9, srcLocEndLine = 62, srcLocEndCol = 37}),(\"epochInfoSlotToRelativeTime\",SrcLoc {srcLocPackage = \"cardano-slotting-0.1.0.0-6VyoKllhKMr9HEkTJGSq3p\", srcLocModule = \"Cardano.Slotting.EpochInfo.API\", srcLocFile = \"src/Cardano/Slotting/EpochInfo/API.hs\", srcLocStartLine = 125, srcLocStartCol = 40, srcLocEndLine = 125, srcLocEndCol = 70}),(\"epochInfoSlotToRelativeTime_\",SrcLoc {srcLocPackage = \"cardano-slotting-0.1.0.0-6VyoKllhKMr9HEkTJGSq3p\", srcLocModule = \"Cardano.Slotting.EpochInfo.API\", srcLocFile = \"src/Cardano/Slotting/EpochInfo/API.hs\", srcLocStartLine = 62, srcLocStartCol = 9, srcLocEndLine = 62, srcLocEndCol = 37}),(\"epochInfoSlotToRelativeTime\",SrcLoc {srcLocPackage = \"cardano-slotting-0.1.0.0-6VyoKllhKMr9HEkTJGSq3p\", srcLocModule = \"Cardano.Slotting.EpochInfo.API\", srcLocFile = \"src/Cardano/Slotting/EpochInfo/API.hs\", srcLocStartLine = 91, srcLocStartCol = 30, srcLocEndLine = 91, srcLocEndCol = 63}),(\"epochInfoSlotToUTCTime\",SrcLoc {srcLocPackage = \"cardano-ledger-alonzo-0.1.0.0-LRtxo54eOGQF6sHY5o0360\", srcLocModule = \"Cardano.Ledger.Alonzo.TxInfo\", srcLocFile = \"src/Cardano/Ledger/Alonzo/TxInfo.hs\", srcLocStartLine = 194, srcLocStartCol = 9, srcLocEndLine = 194, srcLocEndCol = 41})], pastHorizonExpression = Some (EPair (ERelToAbsTime (ERelSlotToTime (EAbsToRelSlot (ELit (SlotNo 37582))))) (ESlotLength (ELit (SlotNo 37582)))), pastHorizonSummary = [EraSummary {eraStart = Bound {boundTime = RelativeTime 0s, boundSlot = SlotNo 0, boundEpoch = EpochNo 0}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 200s, boundSlot = SlotNo 100, boundEpoch = EpochNo 1}), eraParams = EraParams {eraEpochSize = EpochSize 100, eraSlotLength = SlotLength 2s, eraSafeZone = StandardSafeZone 20}},EraSummary {eraStart = Bound {boundTime = RelativeTime 200s, boundSlot = SlotNo 100, boundEpoch = EpochNo 1}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 400s, boundSlot = SlotNo 1100, boundEpoch = EpochNo 2}), eraParams = EraParams {eraEpochSize = EpochSize 1000, eraSlotLength = SlotLength 0.2s, eraSafeZone = StandardSafeZone 300}},EraSummary {eraStart = Bound {boundTime = RelativeTime 400s, boundSlot = SlotNo 1100, boundEpoch = EpochNo 2}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 600s, boundSlot = SlotNo 2100, boundEpoch = EpochNo 3}), eraParams = EraParams {eraEpochSize = EpochSize 1000, eraSlotLength = SlotLength 0.2s, eraSafeZone = StandardSafeZone 300}},EraSummary {eraStart = Bound {boundTime = RelativeTime 600s, boundSlot = SlotNo 2100, boundEpoch = EpochNo 3}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 800s, boundSlot = SlotNo 3100, boundEpoch = EpochNo 4}), eraParams = EraParams {eraEpochSize = EpochSize 1000, eraSlotLength = SlotLength 0.2s, eraSafeZone = StandardSafeZone 300}},EraSummary {eraStart = Bound {boundTime = RelativeTime 800s, boundSlot = SlotNo 3100, boundEpoch = EpochNo 4}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 1200s, boundSlot = SlotNo 5100, boundEpoch = EpochNo 6}), eraParams = EraParams {eraEpochSize = EpochSize 1000, eraSlotLength = SlotLength 0.2s, eraSafeZone = StandardSafeZone 300}},EraSummary {eraStart = Bound {boundTime = RelativeTime 1200s, boundSlot = SlotNo 5100, boundEpoch = EpochNo 6}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 7600s, boundSlot = SlotNo 37100, boundEpoch = EpochNo 38}), eraParams = EraParams {eraEpochSize = EpochSize 1000, eraSlotLength = SlotLength 0.2s, eraSafeZone = StandardSafeZone 300}}]}")

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: https://github.com/input-output-hk/cardano-node/pull/3882

**Comment by nc6** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/3770 and https://github.com/input-output-hk/cardano-ledger/pull/2818 both address the unhandled error, and will hopefully make it easier to dig into the details of this.

**Comment by kevinhammond** [comment]
Obviously something we want to fix, but not an absolute blocker for the hard fork, I think @nc6 ?   As I understand it, it's about poor error reporting?

**Comment by nc6** [comment]
Well, there are two things here. The first is bad error reporting, and that's handled by the above PRs. But there's also an issue with inconsistent TTL validation, which is absolutely a blocker, and the bad error reporting makes it difficult to diagnose what's happening.

**Comment by nfrisby** [comment]
I wrote here that -- as of a couple hours ago -- we think the "inconsistent TTL validation" is better understood now and there is no bug there. https://input-output-rnd.slack.com/archives/C02CHLB0BU4/p1653578190455719?thread_ts=1653388323.364879&cid=C02CHLB0BU4

So: @kevinhammond 's

> Obviously something we want to fix, but not an absolute blocker for the hard fork, I think @nc6 ? As I understand it, it's about poor error reporting?

is now true, to my knowledge.

**Comment by nfrisby** [comment]
The PRs that Clarke mentioned: input-output-hk/ouroboros-network#3770 and input-output-hk/cardano-ledger#2818 are both merged upstream.

The PR #3924 includes them. So as soon as #3924 merges, I think we can close this, since the error will be properly reported instead of via `error` and hence `Muxerror MuxBearerClosed`.

I believe it is the case that the error was happening at all (regardless of how it manifested in the logs/exit status/etc) for reasons we now understand, as explained near the end of this Slack thread https://input-output-rnd.slack.com/archives/C02CHLB0BU4/p1653388323364879

@mkoura do you agree with the above? IE can we close this issue once #3924 since it'll fix the unhelpful reporting?

**Comment by mkoura** [comment]
@nfrisby I agree, we can close this since https://github.com/input-output-hk/cardano-node/pull/3924 is merged.

**Comment by abashai** [comment]
I'm getting the error when I attempt to query the slot leader calculations
