### ISSUE TITLE
[BUG] - Cannot build Alonzo-era transaction with Plutus script in Babbage era

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3897]
*Internal*

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
Building alonzo-era transaction with Plutus script in Babbage era fails with

```
$ cardano-cli transaction build-raw  --alonzo-era --mint-script-file ...

cardano-cli: toAlonzoPParams: Decentralization value required in Alonzo era
CallStack (from HasCallStack):
  error, called at src/Cardano/Api/ProtocolParameters.hs:1418:45 in cardano-api-1.33.0-G5f0eGKxspf1AYjSZoxnBV:Cardano.Api.ProtocolParameters
```

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: `vasil-testnet-v1`

**Comment by Jimbo4350** [comment]
I wrongly thought we could build Alonzo transactions with `build-raw`. We ought to fix this before the hardfork to test backwards compatibility. It's not essential that the `transaction build` command is also fixed before the HF.

**Comment by CarlosLopezDeLara** [comment]
See details https://input-output.atlassian.net/wiki/spaces/SPS/pages/3467313194/Vasil+H+F+Issue+Assessment
