### ISSUE TITLE
[BUG] - CDDL format of tx body not working in Babbage

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3899]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
It is not possible to sign (or `calculate-min-fee`) CDDL tx body in Babbage era.

```
$ cardano-cli transaction sign --tx-body-file test_shelley_cddl_ci0_bxu_tx.body --testnet-magic 42 --signing-key-file addr_shelley_cddl_ci0_1.skey --out-file test_shelley_cddl_ci0_bxu_tx.signed

Command failed: transaction sign  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: test_shelley_cddl_ci0_bxu_tx.body: TextEnvelope type error:  Expected one of: TxUnsignedByron, TxUnsignedShelley, TxBodyAllegra, TxBodyMary, TxBodyAlonzo, TxBodyBabbage Actual: Unwitnessed Tx BabbageEra
TextEnvelopeCddl error: test_shelley_cddl_ci0_bxu_tx.body: Unknown TextEnvelopeCddl type:Unwitnessed Tx BabbageEra
```

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: https://github.com/input-output-hk/cardano-node/pull/3882

**Comment by andrejpodzimek** [comment]
[A similar problem recently appeared](https://forum.cardano.org/t/unwitnessed-tx-babbageera-while-signing-transaction/114616/4?u=andrejpodzimek) with `1.35.5` `cardano-cli`. Can it be related or is it something different / new?

**Comment by mkoura** [comment]
@andrejpodzimek Your issue looks like https://github.com/input-output-hk/cardano-node/issues/4235
