### ISSUE TITLE
[BUG] - Alonzo-era transaction is default in Babbage era - `transaction build` doesn't work

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3900]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The default transaction era in Babbage is Alonzo. That means when babbage transaction era is not specified with `--babbage-era`, `transaction build` tries to build Alonzo-era transaction and fails like

```
$ cardano-cli transaction build --tx-in f0dad162f79edb76a109c5e41e99dd4f2385489dc24df455036c114d38be77fc#1 --tx-out addr_test1wz942jq5unpush8xgxh7cnms2enuh3rkzrc7zylxyu3ca0sncgaav+4500000 --change-address addr_test1vqnk8n56p9r6krwhkkympp9scealff5x5rx9rft9sjdv7lsfqwglj --witness-override 1 --out-file test_incremental_signing_ci0_nem_True_witnessed_to_tx.body --testnet-magic 42
Command failed: transaction build  Error: The era of the node and the tx do not match. The node is running in the Babbage era, but the transaction is for the Alonzo era.
```

**Expected behavior**
In Babbage era the Babbage-era transaction is used by default and doesn't need to be specified on command line.

The `transaction build` command works only when transaction era is the same as network era. It cannot build e.g. Mary-era transaction on Babbage-era network. In that sense the `--babbage-era`, `--alonzo-era`, etc. options are redundant. The `transaction build` should figure out what the network era is and build same era transaction.

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: `ec84a301e2a6d2cdff1f0dad4e7d080cdb3d37b7`

**Comment by dorin100** [comment]
In order to not break the tools built on Cardano exactly after the Babbage HF, the default era when building transactions will be kept as Alonzo (like on the previous HFs). It will be changed to Babbage in the next release after the HF.

**Comment by dorin100** [comment]
The problem here is that you are not allowed anymore to submit Alonzo transactions immediately after the HF.

**Comment by rdlrt** [comment]
> The problem here is that you are not allowed anymore to submit Alonzo transactions immediately after the HF.

The original issue description does not clarify if using `--babbage-era ` solves the issue

**Comment by dorin100** [comment]
> > The problem here is that you are not allowed anymore to submit Alonzo transactions immediately after the HF.
> 
> Minor detail: The original issue description does not clarify if using `--babbage-era ` solves the issue

Yes, while in Babbage era, now you can send transactions using `transaction build` + `--babbage-era`

**Comment by mkoura** [comment]
Related to https://github.com/input-output-hk/cardano-node/issues/3909

**Comment by CarlosLopezDeLara** [comment]
Decision:  https://input-output.atlassian.net/browse/CAD-4445?focusedCommentId=94990

"The cli build commnad will need an explicit --babbage-era flag once the Babbage HF happens, up until we switch the default CLI era (to Babbage). Note that this is consistent with other commands: they explicitly need an era flag to use a new era, until the default is changed later."

**Comment by gitmachtl** [comment]
> The desired behavior is for `transaction build` to always build transaction with the same transaction era as is the current network era, it cannot do it any other way anyway.
> It doesn't even make sense to have these `--babbage-era`, `--alonzo-era`, etc. options available for `transaction build`.

There are reasons you wanna build for example a AlonzoStyleTx even in the Babbage Era. Not all tools and transactions need all the BabbageTxFeatures and some cannot deal with it. For example atm, the cardano-hw-cli and cardano-app for the HW-Ledgers cannot deal with Babbage transactions. So even we are in the Babbage Era on some chains, there is a need to build Alonzo Era Transactions. The build-raw command is doing this and is working fine.

**Comment by mkoura** [comment]
Babbage-era transactions are already default in Babbage era.
