### ISSUE TITLE
Step 1 of the max-TPS benchmarking plan

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3903]
A saturation TPS benchmark with 1MB block size, 30 million UTxO and ~0 (zero) delegations, and see where it lands us in terms of propagation times -- in a standard distributed setting.

The remainder of the plan
>If the 1MB benchmark fails us in some way, then we'll begin "negotiating" with the system:
> - make the system local (first -- single region, second -- single AZ (data center)
> - wait for the "unreasonable block forging time" fix to be found and implemented in consensus
> - in parallel -- investigate the bottleneck

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
