### ISSUE TITLE
[BUG] - `transaction build` command can build transactions only for current era

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3909]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The `transaction build` command cannot build transactions for different era than is the current network era.
Let's say network era is Babbage. When trying to build tx for Alonzo era with `cardano-cli transaction build --alonzo-era ...`, the command fails with

```
Command failed: transaction build  Error: The era of the node and the tx do not match. The node is running in the Babbage era, but the transaction is for the Alonzo era.
```

According to @dcoutts ([IOG intenal link](https://input-output-rnd.slack.com/archives/C02CHLB0BU4/p1653478644665299?thread_ts=1653469732.745079&cid=C02CHLB0BU4)), the command should use current network era for queries, not the specified tx era.

**System info (please complete the following information):**
- OS Name: Fedora 35
- OS Version [e.g. 20.04]
- Node version: `ec84a301e2a6d2cdff1f0dad4e7d080cdb3d37b7`

**Comment by dcoutts** [comment]
Yes, we think this probably can be made to work for making txs in the format of old eras, even when the current era is later.

**Comment by dorin100** [comment]
Ideally, `transaction build` should default to the `current era`

**Comment by newhoggy** [comment]
This reproduces the problem:

```
$ CARDANO_NODE_SOCKET_PATH=example/main.sock \
cardano-cli transaction build \
  --testnet-magic 42 \
  --change-address 'addr_test1vr0fk9rx0vaegjw06we4kwhc3vhsqhzemeazvf96reya28sf0tf2q' \
  --tx-in '5d369322b343f4e87bb1dc35c8e2bfb73e45e7d07161af014ac1c32c0edcd512#0' \
  --tx-out 'addr_test1vr0fk9rx0vaegjw06we4kwhc3vhsqhzemeazvf96reya28sf0tf2q+1000000' \
  --out-file tx.body

Command failed: transaction build  Error: The era of the node and the tx do not match. The node is running in the Babbage era, but the transaction is for the Alonzo era.
$ CARDANO_NODE_SOCKET_PATH=example/main.sock \
cardano-cli transaction build \
  --babbage-era \
  --testnet-magic 42 \
  --change-address 'addr_test1vr0fk9rx0vaegjw06we4kwhc3vhsqhzemeazvf96reya28sf0tf2q' \
  --tx-in '5d369322b343f4e87bb1dc35c8e2bfb73e45e7d07161af014ac1c32c0edcd512#0' \
  --tx-out 'addr_test1vr0fk9rx0vaegjw06we4kwhc3vhsqhzemeazvf96reya28sf0tf2q+1000000' \
  --out-file tx.body

Estimated transaction fee: Lovelace 165721
```

**Comment by newhoggy** [comment]
It turns out that this query fails in the Alonzo era:

https://github.com/input-output-hk/cardano-node/blob/42809ad3d420f0695eb147d4c66b90573d27cafd/cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs#L528-L530

**Comment by newhoggy** [comment]
There is also an issue with Mary/Alonzo and Mary/Babbage compabitility:

```
$(./scripts/bin-path.sh cardano-cli) query utxo \
  --testnet-magic 42 \
  --address $( \
    cardano-cli address build \
      --testnet-magic 42 \
      --payment-verification-key-file \
      example/utxo-keys/utxo1.vkey
  ) \
  --out-file utxo.json


user1_utxo="$(cat utxo.json | jq -r 'to_entries[0].key')"
user1_addr="$(cat utxo.json | jq -r 'to_entries[0].value.address')"

CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) transaction build \
  --mary-era \
  --testnet-magic 42 \
  --change-address "${user1_addr}" \
  --tx-in "${user1_utxo}" \
  --tx-out "${user1_addr}+1000000" \
  --out-file tx.body

Command failed: transaction build  Error: "minUtxoValue" field not present in protocol parameters when trying to calculate minimum UTxO value.
```

**Comment by jfruiz11375** [comment]
You need to set to the --babbage-era
