### ISSUE TITLE
[BUG] - Minimum utxo value is too low

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#3913]
**Internal/External**
*Internal*   if an IOHK staff member.

**Summary**
There is no 1ada minimum for outputs. It is possible to produce an output with value as low as `168129`

**Steps to reproduce**
1. Build a simple transaction like
```bash
cardano-cli transaction build \
--tx-in d1127485a5a245b97d8544e4b87dab313bd9d5d034b744a8a2841155d4b2936b#1 \
--tx-out $(< acct.addr)+168129 \
--change-address $(< acct.addr) \
--testnet-magic $(< db/protocolMagicId) \
--babbage-era \
--out-file txbody
```
2. Sign and submit

**Actual result**
Transaction succeeds

**Expected behavior**
Ledger error like `BabbageOutputTooSmallUTxO` preventing output with less than 1ada

**System info (please complete the following information):**
- Node version d0b0fa10ac83dc1d0d40aaf294cfded1b455a0a4 [vasil-testnet-v1](https://github.com/input-output-hk/cardano-node/releases/tag/vasil-testnet-v1)

**Comment by mkoura** [comment]
I tested that https://github.com/input-output-hk/cardano-ledger/pull/2821 resolves this issue. The `transaction calculate-min-required-utxo` reports correct number in node master (2b2d5dd4e2c349c6075f8abb338bce1911d09fe0)

**Comment by kevinhammond** [comment]
Based on Martin's comment, I will close this issue
