### ISSUE TITLE
workbench:  investigate Dish-sized local cluster performance

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3925]
A very quick estimate of Dish-relevant performance could be obtained from a local cluster model.

Adding a corresponding profile to the workbench shouldn't be hard.

**Comment by deepfire** [comment]
This is part of https://github.com/input-output-hk/cardano-node/pull/3824

**Comment by deepfire** [comment]
The genesis creation command is taking 42+GiB RSS:
`cardano-cli -- genesis create-staked --genesis-dir /home/deepfire/.cache/cardano-workbench/genesis/k3-0kD-30000kU-b11cf13 --supply 10000000000000 --gen-utxo-keys 1 --gen-genesis-keys 0 --supply-delegated 3000000000000000 --gen-pools 3 --gen-stake-delegs 3 --testnet-magic 42 --num-stuffed-utxo 30000000`

**Comment by deepfire** [comment]
The genesis creation command is taking 42+GiB RSS:
`cardano-cli -- genesis create-staked --genesis-dir /path-to-genesis/k3-0kD-30000kU-b11cf13 --supply 10000000000000 --gen-utxo-keys 1 --gen-genesis-keys 0 --supply-delegated 3000000000000000 --gen-pools 3 --gen-stake-delegs 3 --testnet-magic 42 --num-stuffed-utxo 30000000`

**Comment by deepfire** [comment]
https://github.com/input-output-hk/cardano-node/issues/3938 is a dependency for the 30M benchmark

**Comment by Jimbo4350** [comment]
Closing. Please re-open if still relevant.
