### ISSUE TITLE
bug tx-generator: empty data in log entries

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3957]
1. `make ci-test-plutus-autonix`
2. generator logs have:
```
{"app":[],"at":"2022-06-01T02:22:58.72Z","data":{},"env":"<unknown>:00000","host":"","loc":null,"msg":"","ns":["cardano.cli.generate-txs.submitN2N"],"pid":"1870553","sev":"Debug","thread":"2495"}
```
..which have empty `data` field

**Comment by MarcFontaine** [comment]
This normal behavior for the tracer that uses minimal verbosity.
https://github.com/input-output-hk/cardano-node/pull/3952/commits/1291cfb613ec5de47ce612a3f8faa3016f0dee54
switches the tracer to maximal verbosity.

https://github.com/input-output-hk/cardano-node/blob/9a177fdd6ff48649c38f88dad060a14d437abbbd/bench/tx-generator/src/Cardano/Benchmarking/Tracer.hs#L116-L120

The `llSubmit` and `submitN2N` tracers had been set to minimal verbosity for at least a year.
But looking at it I see that `llSubmit` is not even used anywhere in the code.
