### ISSUE TITLE
new deployment infra:  OCI for workbench constituents

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3969]
## Further readings

1. [Nix + Docker, a match made in heaven](https://www.youtube.com/watch?v=WP_oAmV6C2U)
2. [Arion: fast NixOS on Docker Compose (NixCon 2019)](https://www.youtube.com/watch?v=rQ9p45r-dn0)
3. [Functional programming and Nix for reproducible, immutable infrastructure](https://www.youtube.com/watch?v=mKXLAbrKrno)

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
