### ISSUE TITLE
Put `scripts/shelley-testnet2.sh` into CI

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#397]
Changes to `cardano-node` regularly breaks the `shelley-testnet` script and they still get merged. This results in lost time figuring out who & what caused the breakage. 

Condition for success: 
- The cluster starts without error and blocks are being propagated in the cluster.
- The `chairman` successfully finds common prefixes for the chains. (`scripts/chairman.sh`)

**Comment by kevinhammond** [comment]
Has this been cleared?

**Comment by Jimbo4350** [comment]
Closing as I will maintain scripts separate from the benchmarking team
