### ISSUE TITLE
[BUG] - Can't build standalone cardano-node with Nix

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-node#3980]
**External**

**Area**
*Other*:   Documentation / Manual build.

**Summary**
New build instructions for Nix are here https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md and only allow to build pre-packaged versions of the node with default options filled in. Following these build instructions, it seems that I can't get a standalone cardano-node binary to which I can provide my own options (for example, another database location).

I use to simply be able to do:

```console
$ nix-build -A haskellPackages.cardano-node.components.exes
```

but `haskellPackages` is no longer in scope of the default.nix and at this point, I don't know where to look.

**Steps to reproduce**

Try running the nix build instructions. You end up with a single pre-packaged binary:

```
testnet-node-local
└── bin
    └── cardano-node-testnet
```

which accepts no options or commands and is pre-configured for testnet. 

**Expected behavior**

1. I can only build once, and get a cardano-node executable working for mainnet, testnet and actually custom private clusters.
2. The manual build spits back a statically linked executable that I can run with custom options, as before. 

**System info (please complete the following information):**
- OS Name: N/A
- OS Version [e.g. 20.04]: N/A
- Node version (output of `cardano-node --version`): can't run that command anymore.
- CLI version  (output of `cardano-cli --version`): N/A

Currently building out of `1.35.0-rc1`.

**Comment by disassembler** [comment]
`nix build .#cardano-node`

**Comment by deepfire** [comment]
@KtorZ, doesn't https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md cover this?

This link is mentioned in the top-level `CONTRIBUTING.rst`.

**Comment by deepfire** [comment]
@KtorZ, can you suggest a change to https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md that would express the purpose you find unfulfilled?

Asking you to do it, because only you know the proper formulation for the question that's unanswered there.

**Comment by KtorZ** [comment]
I thought my question was pretty clear already, at least @disassembler answered it.

I was interested in building a standalone executable for the node, not a bundle tied with a configuration (`.#mainnet/node`) as the documentation highlight.

So the ask here is to simply document the magic incantation that Sam provided above.
