### ISSUE TITLE
node: the gnaving uncertainty of Babbage

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#3990]
*Problem*

We configure the `1.35.0-rc1` (actually latest `master`) node to start in the Alonzo era, but how do we know if it started in Alonzo?

The run in question is `2022-05-23-12.34.1.35.0-rc1.8206.k51-5ep-360kTx-4000kU-1000kD-64kbs`.

The node config file has these relevant bits:
```
  "TestAllegraHardForkAtEpoch": 0,
  "TestAlonzoHardForkAtEpoch": 0,
  "TestEnableDevelopmentHardForkEras": true,
  "TestEnableDevelopmentNetworkProtocols": true,
  "TestMaryHardForkAtEpoch": 0,
  "TestShelleyHardForkAtEpoch": 0,
```
..and does not have `TestBabbageHardForkAtEpoch` set at all.

The node startup log contains this line in stdout:

`May 23 12:34:15 node-1 cardano-node-start[662128]: Node configuration: NodeConfiguration {ncSocketConfig = SocketConfig {ncNodeIPv4Addr = Last {getLast = Nothing}, ncNodeIPv6Addr = Last {getLast = Nothing}, ncNodePortNumber = Last {getLast = Just 0}, ncSocketPath = Last {getLast = Nothing}}, ncConfigFile = "/nix/store/b8r8qskmy12qspfl2yp5dlpk3p387vay-config-1-0.json", ncTopologyFile = "/nix/store/sb8gn8wb4s8m7a4pmkb6hvlr4fhy5vn2-topology.yaml", ncDatabaseFile = "/var/lib/cardano-node/db-bench-dense-k51-5ep-360kTx-4000kU-1000kD-64kbs", ncProtocolFiles = ProtocolFilepaths {byronCertFile = Just "/var/lib/keys/cardano-node-delegation-cert", byronKeyFile = Just "/var/lib/keys/cardano-node-signing", shelleyKESFile = Just "/var/lib/keys/cardano-node-kes-signing", shelleyVRFFile = Just "/var/lib/keys/cardano-node-vrf-signing", shelleyCertFile = Just "/var/lib/keys/cardano-node-operational-cert", shelleyBulkCredsFile = Nothing}, ncValidateDB = False, ncShutdownConfig = ShutdownConfig {scIPC = Nothing, scOnSlotSynced = Just NoMaxSlotNo}, ncProtocolConfig = NodeProtocolConfigurationCardano (NodeByronProtocolConfiguration {npcByronGenesisFile = "/nix/store/yc2h8f7g5v8hgxdsgfq9wp125n1yg0bi-genesis.json", npcByronGenesisFileHash = Just "2620eb630e88d7af320081aab4ea0e73f00e4d0bbc3fa15c0478176511bc20d1", npcByronReqNetworkMagic = RequiresMagic, npcByronPbftSignatureThresh = Nothing, npcByronApplicationName = ApplicationName {unApplicationName = "cardano-sl"}, npcByronApplicationVersion = 0, npcByronSupportedProtocolVersionMajor = 3, npcByronSupportedProtocolVersionMinor = 0, npcByronSupportedProtocolVersionAlt = 0}) (NodeShelleyProtocolConfiguration {npcShelleyGenesisFile = "/nix/store/nv241pydfgzsln0igdibrq0y0j0vqqcb-genesis.json", npcShelleyGenesisFileHash = Just "6e943598cd17f89f03836177472e2886e381fe5dede77d9946117197f0d7cf3f"}) (NodeAlonzoProtocolConfiguration {npcAlonzoGenesisFile = "/nix/store/1jcfb7vpk81srdxqv8yhzkarnz3znkgh-alonzo-genesis.json", npcAlonzoGenesisFileHash = Nothing}) (NodeHardForkProtocolConfiguration {npcTestEnableDevelopmentHardForkEras = True, npcTestShelleyHardForkAtEpoch = Just (EpochNo 0), npcTestShelleyHardForkAtVersion = Nothing, npcTestAllegraHardForkAtEpoch = Just (EpochNo 0), npcTestAllegraHardForkAtVersion = Nothing, npcTestMaryHardForkAtEpoch = Just (EpochNo 0), npcTestMaryHardForkAtVersion = Nothing, npcTestAlonzoHardForkAtEpoch = Just (EpochNo 0), npcTestAlonzoHardForkAtVersion = Nothing, npcTestBabbageHardForkAtEpoch = Nothing, npcTestBabbageHardForkAtVersion = Nothing}), ncDiffusionMode = InitiatorAndResponderDiffusionMode, ncSnapshotInterval = DefaultSnapshotInterval, ncTestEnableDevelopmentNetworkProtocols = True, ncMaxConcurrencyBulkSync = Nothing, ncMaxConcurrencyDeadline = Just 4, ncLoggingSwitch = True, ncLogMetrics = True, ncTraceConfig = TracingOnLegacy (TraceSelection {traceVerbosity = NormalVerbosity, traceAcceptPolicy = OnOff {isOn = True}, traceBlockFetchClient = OnOff {isOn = True}, traceBlockFetchDecisions = OnOff {isOn = False}, traceBlockFetchProtocol = OnOff {isOn = False}, traceBlockFetchProtocolSerialised = OnOff {isOn = False}, traceBlockFetchServer = OnOff {isOn = True}, traceBlockchainTime = OnOff {isOn = False}, traceChainDB = OnOff {isOn = True}, traceChainSyncBlockServer = OnOff {isOn = False}, traceChainSyncClient = OnOff {isOn = True}, traceChainSyncHeaderServer = OnOff {isOn = True}, traceChainSyncProtocol = OnOff {isOn = False}, traceConnectionManager = OnOff {isOn = True}, traceConnectionManagerCounters = OnOff {isOn = True}, traceConnectionManagerTransitions = OnOff {isOn = False}, traceDebugPeerSelectionInitiatorTracer = OnOff {isOn = False}, traceDebugPeerSelectionInitiatorResponderTracer = OnOff {isOn = False}, traceDiffusionInitialization = OnOff {isOn = True}, traceDnsResolver = OnOff {isOn = False}, traceDnsSubscription = OnOff {isOn = True}, traceErrorPolicy = OnOff {isOn = True}, traceForge = OnOff {isOn = True}, traceForgeStateInfo = OnOff {isOn = True}, traceHandshake = OnOff {isOn = False}, traceInboundGovernor = OnOff {isOn = True}, traceInboundGovernorCounters = OnOff {isOn = True}, traceInboundGovernorTransitions = OnOff {isOn = True}, traceIpSubscription = OnOff {isOn = True}, traceKeepAliveClient = OnOff {isOn = False}, traceLedgerPeers = OnOff {isOn = True}, traceLocalChainSyncProtocol = OnOff {isOn = False}, traceLocalConnectionManager = OnOff {isOn = False}, traceLocalErrorPolicy = OnOff {isOn = True}, traceLocalHandshake = OnOff {isOn = False}, traceLocalInboundGovernor = OnOff {isOn = False}, traceLocalMux = OnOff {isOn = False}, traceLocalRootPeers = OnOff {isOn = True}, traceLocalServer = OnOff {isOn = False}, traceLocalStateQueryProtocol = OnOff {isOn = False}, traceLocalTxMonitorProtocol = OnOff {isOn = False}, traceLocalTxSubmissionProtocol = OnOff {isOn = False}, traceLocalTxSubmissionServer = OnOff {isOn = False}, traceMempool = OnOff {isOn = True}, traceMux = OnOff {isOn = False}, tracePeerSelection = OnOff {isOn = True}, tracePeerSelectionCounters = OnOff {isOn = True}, tracePeerSelectionActions = OnOff {isOn = True}, tracePublicRootPeers = OnOff {isOn = True}, traceServer = OnOff {isOn = True}, traceTxInbound = OnOff {isOn = True}, traceTxOutbound = OnOff {isOn = False}, traceTxSubmissionProtocol = OnOff {isOn = False}, traceTxSubmission2Protocol = OnOff {isOn = False}}), ncMaybeMempoolCapacityOverride = Nothing, ncProtocolIdleTimeout = 5s, ncTimeWaitTimeout = 60s, ncAcceptedConnectionsLimit = AcceptedConnectionsLimit {acceptedConnectionsHardLimit = 512, acceptedConnectionsSoftLimit = 384, acceptedConnectionsDelay = 5s}, ncTargetNumberOfRootPeers = 100, ncTargetNumberOfKnownPeers = 100, ncTargetNumberOfEstablishedPeers = 50, ncTargetNumberOfActivePeers = 20, ncEnableP2P = DisabledP2PMode}`

The node log has the following entries:

```
May 23 12:34:34 node-1 cardano-node-start[662128]: {"app":[],"at":"2022-05-23T12:34:33.99Z","data":{"epochLength":"8000","era":"Shelley","kind":"BasicInfoShelleyBased","slotLength":"1s","slot
sPerKESPeriod":"129600","systemStartTime":"2022-05-23 12:23:03 UTC"},"env":"1.33.0:82067","host":"node-1","loc":null,"msg":"","ns":["cardano.node.startup"],"pid":"662128","sev":"Info","thread
":"5"}
May 23 12:34:34 node-1 cardano-node-start[662128]: {"app":[],"at":"2022-05-23T12:34:33.99Z","data":{"epochLength":"8000","era":"Allegra","kind":"BasicInfoShelleyBased","slotLength":"1s","slot
sPerKESPeriod":"129600","systemStartTime":"2022-05-23 12:23:03 UTC"},"env":"1.33.0:82067","host":"node-1","loc":null,"msg":"","ns":["cardano.node.startup"],"pid":"662128","sev":"Info","thread
":"5"}
May 23 12:34:34 node-1 cardano-node-start[662128]: {"app":[],"at":"2022-05-23T12:34:33.99Z","data":{"epochLength":"8000","era":"Mary","kind":"BasicInfoShelleyBased","slotLength":"1s","slotsPe
rKESPeriod":"129600","systemStartTime":"2022-05-23 12:23:03 UTC"},"env":"1.33.0:82067","host":"node-1","loc":null,"msg":"","ns":["cardano.node.startup"],"pid":"662128","sev":"Info","thread":"
5"}
May 23 12:34:34 node-1 cardano-node-start[662128]: {"app":[],"at":"2022-05-23T12:34:33.99Z","data":{"epochLength":"8000","era":"Alonzo","kind":"BasicInfoShelleyBased","slotLength":"1s","slots
PerKESPeriod":"129600","systemStartTime":"2022-05-23 12:23:03 UTC"},"env":"1.33.0:82067","host":"node-1","loc":null,"msg":"","ns":["cardano.node.startup"],"pid":"662128","sev":"Info","thread"
:"5"}
May 23 12:34:34 node-1 cardano-node-start[662128]: {"app":[],"at":"2022-05-23T12:34:33.99Z","data":{"epochLength":"8000","era":"Babbage","kind":"BasicInfoShelleyBased","slotLength":"1s","slot
sPerKESPeriod":"129600","systemStartTime":"2022-05-23 12:23:03 UTC"},"env":"1.33.0:82067","host":"node-1","loc":null,"msg":"","ns":["cardano.node.startup"],"pid":"662128","sev":"Info","thread
":"5"}
```
..but also:
```
{"app":[],"at":"2022-05-23T12:35:26.13Z","data":{"kind":"LogMessage","message":"TraceLabelCreds \"Cardano\" (CurrentEraForgeStateUpdated S (S (S (S (Z (WrapForgeStateInfo {unwrapForgeStateInfo = KESInfo {kesStartPeriod = KESPeriod 0, kesEndPeriod = KESPeriod 60, kesEvolution = 0}}))))))"},"env":"1.33.0:82067","host":"node-1","loc":null,"msg":"","ns":["cardano.node.Forge"],"pid":"662128","sev":"Debug","thread":"111"}
```

..where `S (S (S (S Z ...)))` supposedly means:
`Byron + 1 + 1 + 1 + 1` = `Shelley + 1 + 1 + 1` = `Allegra + 1 + 1` = `Mary + 1` = `Alonzo`
?

Is that right?

**Comment by nfrisby** [comment]
On Slack, Jared suggested using the NTC queries for this. You (understandbly) replied that that's heavierweight than you're hoping for. Unfortunately, I don't think we've anticipated the need for a lighterweight answer to your question.

* Skipping initial eras has never been a primary feature, just a "power user" thing eg for testnets etc.
* We took the queries for granted for as the expects way to answer this kind of question.

> We configure the [...snip...] node to start in the Alonzo era, but how do we know if it started in Alonzo?

I think you're concerned about what era _the chain_ started in, since you're concerned about scenarios involving skipping initial eras. You asked about what era the node started in, but (I'm guessing) specifically when the nodes are started for the first time. IE what era the chain started in.

And that should be equal to the era of the `pInfoInitLedger` that is ultimately passed by `exe:cardano-node` code to the Consensus layer -- ie the era of the genesis ledger state.

https://github.com/input-output-hk/ouroboros-network/blob/d2ce868248f5b6a4279fe369adb4d428a16c0351/ouroboros-consensus/src/Ouroboros/Consensus/Node/ProtocolInfo.hs#L38-L42

```
data ProtocolInfo m b = ProtocolInfo {
        pInfoConfig       :: TopLevelConfig b
      , pInfoInitLedger   :: ExtLedgerState b -- ^ At genesis
      , pInfoBlockForging :: m [BlockForging m b]
      }
```

So I think we should interpret this issue as a feature request do make the era of `pInfoInitLedger` more obvious in the logs. I have hope that can be done in `cardano-node` without any upstream changes necessary in `ouroboros-consensus`, but I'm not certain. Maybe Consensus could help determine which HFC functions are already available for use in implementing that.

Would it be acceptable for the node to print that explicitly in a log message, instead of you trying to find it in a `Tracer` event emitted from the Consensus layer?

**Comment by nfrisby** [comment]
Also, do we need a separate Issue to add a `TestBabbageHardForkAtEpoch` field to the node's config file? I also _think_ that'd be a `cardano-node` only change, with nothing new needed upstream.

**Comment by nfrisby** [comment]
To answer your direct question -- as opposed to suggesting a PR to make the log messages easier to interpret directly -- I think that your interpretation of the `CurrentEraForgeStateUpdated` message is correct. The forge thread calls `checkShouldForge` every slot (including the first slot during which the node is initialized, ie hopefully slot `0`), and that function calls `updateForgeState` which emits a tracer event summarizing the update, which for the Hard Fork Combinator will involve `CurrentEraForgeStateUpdated` (if it has forging credentials for the node's current ledger tip's era).

So if you're seeing that event "immediately" in the logs of a node that is starting from with no pre-existing chain, then I think that does imply the chain's genesis ledger state is in the era identified by the Church numeral. HTH.

**Comment by deepfire** [comment]
Thank you @nfrisby!
