### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by nftizate** [input-output-hk/cardano-node#3994]
**Version**
* cardano-cli 1.33.0 - linux-x86_64 - ghc-8.10
* git rev b97e5fad59753c49e2725edbdc6e3b30926c266a

I have minted several NFT following this guide:
https://developers.cardano.org/docs/native-tokens/minting-nfts/

See this example:
- Wallet address: addr1q9frc9xuthxu0ae4jgcw9wmg7szw54ejjkjwx2hjmr68hc045arxxky6yue87eul3p9tz6cmz4x003rt6z8c7nqx7resz8umze
- asset1c74gqdxjmshqg8906gkzgtexz8p0c8z6qw8v6v
- The transaction run smoothly without any errors

When I explore the metadata of the NFT minted:
 - [explorer.cardano.org](https://explorer.cardano.org/en/address?address=addr1q9frc9xuthxu0ae4jgcw9wmg7szw54ejjkjwx2hjmr68hc045arxxky6yue87eul3p9tz6cmz4x003rt6z8c7nqx7resz8umze)
 - [pool.pm](https://pool.pm/test/metadata?metadata=%257B%25226058d7a8320faa2c8553feed20d36e53e029c7bec9842c824cc1df92%2522%253A%257B%25224e6674697a61746520677265656e207c204031%2522%253A%257B%2522collection%2522%253A%2522DEMO%25201%2522%252C%2522description%2522%253A%2522Serie%2520demo%2520para%2520nftizate.es.%2520Green%2522%252C%2522files%2522%253A%255B%257B%2522mediaType%2522%253A%2522image%252Fpng%2522%252C%2522name%2522%253A%2522Nftizate%2520green%2520%257C%2520%25401%2522%252C%2522src%2522%253A%2522ipfs%253A%252F%252FQmVcmipyiNDnHqcXyZjrpEg8UbAMRbEV5jj7yi1ahMdcRV%2522%257D%255D%252C%2522image%2522%253A%255B%2522https%253A%252F%252Fbafybeidmemd4s62547fcwoztsbrvlc7i4iyullt%2522%252C%2522wp3ab3wq77njcu32uta.ipfs.nftstorage.link%252F%2522%255D%252C%2522mediaType%2522%253A%2522image%252Fpng%2522%252C%2522name%2522%253A%2522Nftizate%2520green%2520%257C%2520%25401%2522%252C%2522sha256%2522%253A%2522a550b95bdfe3dc61ba24816bc0566434d3b8a8837a24c6487533df349c8581d7%2522%252C%2522website%2522%253A%2522https%253A%252F%252Fnftizate.es%2522%257D%257D%257D)

The "721" field is missing => [see error in pool.pm](https://pool.pm/test/metadata?metadata=%257B%25226058d7a8320faa2c8553feed20d36e53e029c7bec9842c824cc1df92%2522%253A%257B%25224e6674697a61746520677265656e207c204031%2522%253A%257B%2522collection%2522%253A%2522DEMO%25201%2522%252C%2522description%2522%253A%2522Serie%2520demo%2520para%2520nftizate.es.%2520Green%2522%252C%2522files%2522%253A%255B%257B%2522mediaType%2522%253A%2522image%252Fpng%2522%252C%2522name%2522%253A%2522Nftizate%2520green%2520%257C%2520%25401%2522%252C%2522src%2522%253A%2522ipfs%253A%252F%252FQmVcmipyiNDnHqcXyZjrpEg8UbAMRbEV5jj7yi1ahMdcRV%2522%257D%255D%252C%2522image%2522%253A%255B%2522https%253A%252F%252Fbafybeidmemd4s62547fcwoztsbrvlc7i4iyullt%2522%252C%2522wp3ab3wq77njcu32uta.ipfs.nftstorage.link%252F%2522%255D%252C%2522mediaType%2522%253A%2522image%252Fpng%2522%252C%2522name%2522%253A%2522Nftizate%2520green%2520%257C%2520%25401%2522%252C%2522sha256%2522%253A%2522a550b95bdfe3dc61ba24816bc0566434d3b8a8837a24c6487533df349c8581d7%2522%252C%2522website%2522%253A%2522https%253A%252F%252Fnftizate.es%2522%257D%257D%257D)

The metadata stored in the field used for the transaction:

_{
    "721": {
        "6058d7a8320faa2c8553feed20d36e53e029c7bec9842c824cc1df92": {
            "4e6674697a61746520677265656e207c204031": {
                "collection": "DEMO 1",
                "description": "Serie demo para nftizate.es. Green",
                "files": [
                    {
                        "mediaType": "image/png",
                        "name": "Nftizate green | @1",
                        "src": "ipfs://QmVcmipyiNDnHqcXyZjrpEg8UbAMRbEV5jj7yi1ahMdcRV"
                    }
                ],
                "image": [
                    "https://bafybeidmemd4s62547fcwoztsbrvlc7i4iyullt",
                    "wp3ab3wq77njcu32uta.ipfs.nftstorage.link/"
                ],
                "mediaType": "image/png",
                "name": "Nftizate green | @1",
                "sha256": "a550b95bdfe3dc61ba24816bc0566434d3b8a8837a24c6487533df349c8581d7",
                "website": "https://nftizate.es"
            }
        }
    }
}

Is there something I'm missing?

Regards

Javier

**Comment by CarlosLopezDeLara** [comment]
Try using the the asset name in UTF8 instead of hex.

**Comment by nftizate** [comment]
Hello,

I've tried with the asset name in UTF-8 in the testnet but the "721" field doesn't show up.

You can check the minted metadata: [transaction in the testnet](https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=9b2a0e44645cfae9129f602b34d22fbab59e5da961909f69a50d949ce155d627)

My metadata file content:
{
    "721": {
        "0b39d9f6094104ee1626e8c2bc73fbf9aa248cdb12abc51f3a9d8550": {
            "**nftizategreen|@1**": {
                "collection": "DEMO 1",
                "description": "Serie demo para nftizate.es. Green #2",
                "files": [
                    {
                        "mediaType": "image/png",
                        "name": "Nftizate green | @1",
                        "src": "ipfs://QmVcmipyiNDnHqcXyZjrpEg8UbAMRbEV5jj7yi1ahMdcRV"
                    }
                ],
                "image": [
                    "https://bafybeidmemd4s62547fcwoztsbrvlc7i4iyullt",
                    "wp3ab3wq77njcu32uta.ipfs.nftstorage.link/"
                ],
                "mediaType": "image/png",
                "name": "Nftizate green | @1",
                "sha256": "a550b95bdfe3dc61ba24816bc0566434d3b8a8837a24c6487533df349c8581d7",
                "website": "https://nftizate.es"
            }
        }
    }
}

**Comment by nftizate** [comment]
Hello again, I forgot the version field and tried again including it. The result is the same. You can check it with this [link](https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=35497b03df69502cc18ac35107805b32f3ae57239915793ef34d10eb3d017474).

Thanks for the help.

Javier

**Comment by CarlosLopezDeLara** [comment]
I'm not sure if the 721 field is supposed to be displayed on cardano explorer, perhaps @rhyslbw has a better idea. 

However, this metadata on your last message looks good @nftizate. Testing that version of the metadata on pool.pm shows it is correct. 

![Screen Shot 2022-06-07 at 11 46 22](https://user-images.githubusercontent.com/64222734/172440131-b7daf287-b0f2-4e7a-9052-dbdf82f21fd2.png)

Look at this example as reference:

* Metadata on the explorer:  https://explorer.cardano.org/en/transaction?id=ddfdd824ffa0c07635aae94903d15d4606577237218670a8e5f41cd6516fb732

* That asset displays correctly on pool.pm https://pool.pm/asset14euk63r8njdfzqgs7ypx3n88p7qm7uxtzck42m

* https://cardanoscan.io/transaction/ddfdd824ffa0c07635aae94903d15d4606577237218670a8e5f41cd6516fb732?tab=metadata

**Comment by nftizate** [comment]
Sorry for the delay answering.

As you said, changing the asset name to UTF-8 solved the issue:

[pool.pm](https://pool.pm/asset1u2cmr9w2f5a86gdq95j5ymqdk6km90eg27fd7e)
[metadata ok!](https://pool.pm/test/metadata?metadata=%257B%2522721%2522%253A%257B%2522705c688d9050fa9de314a34a19c2f59a102bb00a50e12f3b84b4826d%2522%253A%257B%2522nftizatev2green%257C%25401%2522%253A%257B%2522collection%2522%253A%2522DEMO%25201%2522%252C%2522description%2522%253A%2522Serie%2520demo%2520para%2520nftizate.es.%2520Green%2522%252C%2522files%2522%253A%255B%257B%2522mediaType%2522%253A%2522image%252Fpng%2522%252C%2522name%2522%253A%2522Nftizate%2520v2%2520green%2520%257C%2520%25401%2522%252C%2522src%2522%253A%2522ipfs%253A%252F%252FQmVcmipyiNDnHqcXyZjrpEg8UbAMRbEV5jj7yi1ahMdcRV%2522%257D%255D%252C%2522image%2522%253A%255B%2522https%253A%252F%252Fbafybeidmemd4s62547fcwoztsbrvlc7i4iyullt%2522%252C%2522wp3ab3wq77njcu32uta.ipfs.nftstorage.link%252F%2522%255D%252C%2522mediaType%2522%253A%2522image%252Fpng%2522%252C%2522name%2522%253A%2522Nftizate%2520v2%2520green%2520%257C%2520%25401%2522%252C%2522sha256%2522%253A%2522a550b95bdfe3dc61ba24816bc0566434d3b8a8837a24c6487533df349c8581d7%2522%252C%2522website%2522%253A%2522https%253A%252F%252Fnftizate.es%2522%257D%257D%257D%257D)

Thanks for your help!
