### ISSUE TITLE
CAD-390 profiling chain-sync

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-node#401]
a memory leak has been observed.
the chain-sync benchmark runs for one hour; should be done with profiling.

**Comment by karknu** [comment]
The memory leak seems to have been introduced with https://github.com/input-output-hk/ouroboros-network/commit/f2a050ba9ada3bf3ee2421f5e610947619d28337

**Comment by mrBliss** [comment]
Fixed in https://github.com/input-output-hk/ouroboros-network/pull/1357

**Comment by CodiePP** [comment]
needs to be reevaluated on new integration.
