### ISSUE TITLE
Make build-raw and build commands able to create alonzo-era tx in Babbage (d=0 in Alonzo d=deprecated in Babbage)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#4033]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
Make `decentralisationParam=0` in the returned values of `query protocol-parameters` cli command in Babbage era

**Expected behavior**
Alonzo-era Plutus transactions should work as default after hard-forking to Babbage. 

**Additional context**
At this moment because the output of the `query protocol-parameters` cli command returns `decentralisationParam=null` in the Babbage era, the Alonzo-era Plutus transactions do not work in the Bababbage era. 

A simple and fast solution could be to set `decentralisationParam=0` (instead of null) in the output of the `query protocol-parameters` cli command

**Comment by CarlosLopezDeLara** [comment]
Further improvements are tracked in https://github.com/input-output-hk/cardano-node/issues/4054
