### ISSUE TITLE
[FR] - cli to allow use of reference script at tx-in being spent

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#4040]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
Currently, when spending an output locked by a spending script the cli enforces either a reference input (`--tx-in-reference`) or script attached to transaction (`--tx-in-script-file`) to satisfy script witness requirement but it should also allow for using the reference script at the tx-in being spent. 

**Describe alternatives you've considered**
We could add a `--tx-in-reference-script-present`. Also consider renaming `--tx-in-reference` to `tx-in-reference-script` to be clear that the reference input aims to satisfy script witness requirement.

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
> but it should also allow for using the reference script at the tx-in being spent.

Hey @james-iohk can you clarify what you mean? I don't understand

**Comment by CarlosLopezDeLara** [comment]
@Jimbo4350 https://input-output-rnd.slack.com/archives/CCRB7BU8Y/p1655126247539009?thread_ts=1654798518.319819&cid=CCRB7BU8Y

**Comment by james-iohk** [comment]
@Jimbo4350 We know that the ledger considers reference scripts at regular inputs to witness spending scripts. This means there can be scenarios where there's no need to explicitly reference the same output using `--spending-tx-in-reference`. I'm proposing we add a new `--tx-in-reference-script-present` option to cover this scenario.

It is an edge case, and if this doesn't even save space in the txbody it is very low priority.

**Comment by Jimbo4350** [comment]
> If a regular input is locked by the same script it has attached as a reference script

I take this to mean an input at a _script address_. The _script address_ corresponds to a reference script. Is this the scenario you are describing:
A tx input at a script address. The corresponding reference script exists at the same input. As I understand it, you're saying you want to be able to spend this input without specifying `--spending-tx-in-reference`? It's currently spending if you do specify  `--spending-tx-in-reference` right?

**Comment by james-iohk** [comment]
> you're saying you want to be able to spend this input without specifying --spending-tx-in-reference?
I was suggesting that

> Is it currently spendable if you do specify --spending-tx-in-reference?
Yes

I agree that it probably isn't worth it if there's no improvement in tx size. Closing.
