### ISSUE TITLE
rename TestEnableDevelopmentHardForkEras to TestEnableAdvertiseDevelopmentProtVer

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/cardano-node#4043]
Currently, setting `TestEnableDevelopmentHardForkEras: true` in the node's config file sets this flag in the code:

https://github.com/input-output-hk/cardano-node/blob/d0b0fa10ac83dc1d0d40aaf294cfded1b455a0a4/cardano-node/src/Cardano/Node/Types.hs#L176-L191

As that comment says, this flag controls what the node "advertises". We just had some Slack conversations about whether we should set this flag, and there was plenty of confusion about what it actually does.

For example, at the moment (since we're preparing a Babbage-able release candidate), its direct effect looks like this on the `master` branch:

https://github.com/input-output-hk/cardano-node/blob/d0b0fa10ac83dc1d0d40aaf294cfded1b455a0a4/cardano-node/src/Cardano/Node/Protocol/Cardano.hs#L205-L216

And if you chase through the code a bit, you see that its ultimate effect is the value of `shelleyProtocolVersion`.

https://github.com/input-output-hk/ouroboros-network/blob/0a3a61ae80244dde943843fd39ef17cd85260980/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Ledger/Config.hs#L44-L47

```
data instance BlockConfig (ShelleyBlock proto era) = ShelleyConfig {
      -- | The highest protocol version this node supports. It will be stored
      -- the headers of produced blocks.
      shelleyProtocolVersion  :: !SL.ProtVer
```

So that's what "advertise" means, concretely, for the Shelley ledgers.

This Issue is to rename the flag to something more indicative of its purpose. I think that's low-hanging fruit to make such confusion less likely in the future. (Happy to see bikeshedding here, my `TestEnableAdvertiseDevelopmentProtVer` is just a conversation starter.)

**Comment by LudvikGalois** [comment]
I'll make a PR which renames this, but in current master, this field is unused
