### ISSUE TITLE
[BUG] - user-unfriendly error message when PlutusV2 cost model is not available

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#4050]
*Internal*

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
When PlutusV2 cost model is not available (the situation after Babbage HF), the error message from `transaction build` command when trying to build a Tx with PlutusV2 script is

> cardano-cli: (Array.!): undefined array element

The message could be more helpful, like the one reported by `transaction submit`:

> Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (UtxosFailure (CollectErrors [NoCostModel PlutusV2]))))])

**System info:**
- OS Name: Fedora 35
- Node version: 07053e4952c7ba50b0fa7b10caaa554e4da9d6a6

**Comment by Jimbo4350** [comment]
@mkoura can you confirm if this still is a problem? I believe it was fixed.

**Comment by mkoura** [comment]
@Jimbo4350 It is fixed:
```
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (UtxosFailure (CollectErrors [NoCostModel PlutusV2]))))])
```

**Comment by CarlosLopezDeLara** [comment]
PR https://github.com/input-output-hk/cardano-ledger/pull/2852
