### ISSUE TITLE
[BUG] - Not possible to spend output with plutus reference script attached from vkey address

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#4057]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
It is not possible to spend an output at a key witness address if it has a plutus reference script attached. This problem exists for both PlutusV1 and PlutusV2 reference scripts. There is no problem with spending a simple script in this scenario.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Create an output at your own key witness address (not a script address) that has a plutus reference script attached
2. Create a transaction to spend the output using your signing key as witness (no plutus-related cli flags required)

**Actual result((
```
The following error is seen on submit:
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch SNothing (SJust (SafeHash "8ee004f99373941d6cbee99aab615d0c7fbab451faa9f115ef4587d66d0a77b5"))))])
```

**Expected behavior**
Output can be spent and the reference script is removed from ledger state.

**System info (please complete the following information):**
- OS Name: 20.04.4 LTS (Focal Fossa)
- Node/Cli version: 6471c31

**Comment by james-iohk** [comment]
**Another scenario** that produces `PPViewHashesDontMatch SNothing (SJust (SafeHash "8ee004f99373941d6cbee99aab615d0c7fbab451faa9f115ef4587d66d0a77b5"))` is when attempting to spend an output at vkey address that has no reference script or inline datum attached but also referencing an output that has a PlutusV2 reference script attached.

Basically, a normal spend but using `--read-only-tx-in-reference` on output that has a PlutusV2 reference script.

**Comment by CarlosLopezDeLara** [comment]
fixed by https://github.com/input-output-hk/cardano-ledger/pull/2878
