### ISSUE TITLE
[BUG] - cli build cmd requires protocol params to be provided in order to embed datum in transaction

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#4058]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
When using `build` `--tx-out-datum-embed-*` flag to embed datum in the transaction whilst attaching its hash to the output, an error is seen on submit if `--protocol-params-file` is not provided. If protocol params are required then `build` should complain that it is missing.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. `build` a transaction using `--tx-out-datum-embed-value` without providing `--protocol-params-file`
2. `sign` and `submit` that transaction

**Actual behaviour**
No error is displayed on `build` but the following error is seen on `submit`:
```
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch SNothing (SJust (SafeHash "9c365c30b7badac0e2efb11828f011ed4566496145d3f0cef93dff8b13d7c932"))))])
```

**Expected behavior**
Either protocol-params are not necessary and it should just work, or, the `build` cmd should complain it is missing like it does for plutus script execution: 
```
Command failed: transaction build  Error: Transaction uses Plutus scripts but does not provide the protocol parameters to hash
```

**System info (please complete the following information):**
- OS Name: 20.04.4 LTS (Focal Fossa)
- Node/Cli version: 6471c31

____
### Acceptance Criteria 

Given I'm a user using `build` command to build a transaction body: 
 
- Build command does not require pparams.json to build a valid transaction. 
- the flag --protocol-params-file is removed from the command help/usage 
- If the user provides the flag --protocol-params-file the cli prints out a warning of deprecation and ignores the provided pparams file. So that we don't break existing tooling.

**Comment by james-iohk** [comment]
This also exists in Alonzo era so leaving the `Vasil` label off

**Comment by Jimbo4350** [comment]
We can totally eliminate this in the `build` command by not requiring the user to specify the protocol params to begin with. We already query the [protocol params here](https://github.com/input-output-hk/cardano-node/blob/45b0c587edba6f40e35ee63e46db22809e74d056/cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs#L539). We can query the node first and then replace `<*> validateProtocolParameters  era mpparams` with `<*> return (BuildTxWith $ Just pparams)`.

**Comment by dorin100** [comment]
@CarlosLopezDeLara I think this ticket needs Acceptance Criteria too.
