### ISSUE TITLE
cardano-node cannot start

### ISSUE THREAD

**Issue by jaykeatlas** [input-output-hk/cardano-node#4067]
version 1.34.1
./cardano-node run --config ./block-producing/mainnet-config.json --topology ./block-producing/mainet-topology.json --database-path ./data --socket-path /ipc/node.socket --host-addr 0.0.0.0 --port 3001
AesonException "Error in $: key \"AlonzoGenesisFile\" not found"

cardano-node: Aeson exception:
Error in $: key "AlonzoGenesisFile" not found

config like this
Setting up the configuration files
Use the same [mainnet-shelley-genesis.json](https://hydra.iohk.io/build/3670619/download/1/mainnet-shelley-genesis.json) files for both nodes.
Use even the same [mainnet-config.json](https://hydra.iohk.io/build/3670619/download/1/mainnet-config.json) files for both nodes or change it as you need.
Use different [mainnet-topology.json](https://hydra.iohk.io/build/3670619/download/1/mainnet-topology.json) files for each node.

**Comment by reqlez** [comment]
You need the Alonzo genesis file as well, here is an example for testnet:
https://developers.cardano.org/docs/stake-pool-course/handbook/run-cardano-node-handbook/

**Comment by CarlosLopezDeLara** [comment]
Config files can be found at https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/index.html  For mainnet you need:

- [ ] mainnet-byron-genesis.json
- [ ] mainnet-shelley-genesis.json
- [ ] mainnet-alonzo-genesis.json
- [ ] mainnet-topology.json
