### ISSUE TITLE
[FR] - build cmd to check whether read-only reference input is in ledger state

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#4073]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
When using `build` cmd's `--read-only-tx-in-reference` with a utxo that is not in the ledger state there is no error until `submit` when you see something like:
```
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (BadInputsUTxO (fromList [TxIn (TxId {_unTxId = SafeHash "bbfd5c6666f7ed3491d9533be796dc1bd3e165d99eb35fbcf908efee3e8edc04"}) (TxIx 666)]))))])
```

**Describe alternatives you've considered**
It would be good to provide earlier feedback, ideally with a new message.

**Additional context / screenshots**
Node/Cli version: 43393ac88faa99986ecaa0be409e8b6353f5e9fe

**Comment by james-iohk** [comment]
Related to #4012

**Comment by CarlosLopezDeLara** [comment]
Makes sense. `build`  is already checking  utxos that go on `tx-in ` so perhaps it could also check for `--read-only-tx-in-reference` at the same time, and show a similar error if the utxo does not exist. 

```
Command failed: transaction build  Error: The following tx input(s) were not present in the UTxO:
ed1603d3437792fe0b18d3474fd2e7ec930f24cc852f10f49f6e8584b91850de#2
```

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by james-iohk** [comment]
It does now do something like this for reference spending inputs:
```
Command failed: transaction build  Error: The following tx input(s) were not present in the UTxO: 
47d275448e60594f08863462bb6756a64e4418e2f0f2e8cea961ec25c97c6475#666
47d275448e60594f08863462bb6756a64e4418e2f0f2e8cea961ec25c97c6475#777
```
All good.
