### ISSUE TITLE
All balance in --tx-in-collateral is taken. Change should go to --change-address (build command)

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4075]
**Summary**

When phase 2 validation fails and NO --tx-out-return-collateral is given, only exact amount of collateral should be used and change should be sent to `--change-address` specified in (`cardano-cli transaction build`) 

**Current behaviour is that it falls back to Alonzo-style of taking all collateral.**

**Steps to reproduce**

1. Create a plutus script transaction that should fail phase2 validation 
2. Give a ` --tx-in-collateral` with more ADA than needed to cover the collateral
3. Do not give a `--tx-out-return-collateral`
4. Sign and submit the transaction
5. All the balance in `-tx-in-collateral` is taken

**Expected behavior**
Only the exact amount of collateral should be taken and change should be sent to `--change-address` when no `--tx-out-return-collateral` is given by the user.

**Related GH issues**
- #3939
____
**Acceptance Criteria**

- [ ] GIVEN that I'm a Dapp developer
WHEN I submit a plutus script that fails phase 2 validation
AND my transaction does not specify `--tx-out-return-collateral`
THEN Only the exact collateral is taken from ` --tx-in-collateral`
AND the excess is sent to `--change-address`

**Definition of Done**

- [ ]  Code peer-reviewed
- [ ]  Builds successfully on CI
- [ ]  Includes documentation and/or examples for the functionality
- [ ]  Log/record changes on Vnext (or similar depending on what we adopt)
- [ ]  Acceptance Criteria met
- [ ]  The new functionality is covered by dev/unit/property tests
- [ ]  Merged to master
- [ ]  Test Engineering Sign-off + E2E automated tests
- [ ]  Released

**Comment by CarlosLopezDeLara** [comment]
Ledger to provide a helper function.

**Comment by Jimbo4350** [comment]
This is not a bug. We are getting too trigger happy with labeling things bugs when they are feature requests!

**Comment by Jimbo4350** [comment]
One caveat is you also need to not provide the `--tx-total-collateral` flag in order to benefit from automatically calculating the return collateral. Specifying either `--tx-total-collateral` or `--tx-total-collateral` will not result in the build command automatically returning the "excess" collateral to your change address.
