### ISSUE TITLE
[FR] - build cmd to check for MissingScriptWitnessesUTXOW

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#4081]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
When attempting to perform an action that requires a script wintess then we see the following error on submit:
```
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (WrappedShelleyEraFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash "9deece47fe39df6fe10edcfc6c1de9954a06ef75edacfb59fc3b57ef"]))))])
```
It would be better to catch this at `build` stage.

To recreate you can try to spend a script-protected output whilst referencing a utxo that doesn't have the correct reference script as witness.

**Additional context / screenshots**
Node/CLI Version: 43393ac88faa99986ecaa0be409e8b6353f5e9fe

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
