### ISSUE TITLE
workbench & locli:  differential run analysis

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4091]
We need means for automated differential analysis & reporting between runs.

**Comment by deepfire** [comment]
A trial version is currently implemented in `bench-master`.

The first runs that undergone this procedure were:
- https://github.com/input-output-hk/cardano-node/issues/4066
- https://github.com/input-output-hk/cardano-node/issues/4065

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
