### ISSUE TITLE
[FR] - TxTotalAndReturnCollateralSupportedInEra(..) is not exposed to cardano-api making it unusable in types outside cardano-api.

### ISSUE THREAD

**Issue by nabinpkl** [input-output-hk/cardano-node#4092]
**Internal/External**
*External*   otherwise.

**Area**
*Cardano API*    Babbage Era

**Describe the feature you'd like**
`TxTotalAndReturnCollateralSupportedInEra(..)` needs to be exposed in Cardano.API too so it can be used outside cardano-api. Currenlty it is used internally in TxBody.hs but working outside cardano-api it is not possible to define types using TxTotalAndReturnCollateralSupportedInEra like as we were doing in other data structures like `MultiAssetSupportInBabbageEra` etc.

**Describe alternatives you've considered**
- Not to define types.
- Using explicitly `totalAndReturnCollateralSupportedInEra BabbageEra`  which is unnecessary workaround if am sure of using `TxTotalAndReturnCollateralInBabbageEra` when working in Babbage Era.

**Comment by CarlosLopezDeLara** [comment]
@Jimbo4350 can you give it a look, please.
