### ISSUE TITLE
build cmd's calculate-plutus-script-cost doesn't include script hash for reference scripts

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node#4094]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
When using `build` cmd's `--calculate-plutus-script-cost` to produce an output of each plutus script's resource requirement and cost the `scriptHash` field is null for reference scripts. It is correctly populated for attached scrtips. See comparison of two transactions using the same script as reference and as attached:

```bash
$ cat ref_cost attached_cost
[
    {
        "executionUnits": {
            "memory": 663882,
            "steps": 205620764
        },
        "lovelaceCost": 53132,
        "scriptHash": null
    }
][
    {
        "executionUnits": {
            "memory": 570992,
            "steps": 176055294
        },
        "lovelaceCost": 45640,
        "scriptHash": "505755e49f9873b02258f1e6fdcc6c81446ab560a0e78180c600d9bd"
    }
]
```

**Steps to reproduce**
1. Use cli's `build` cmd to construct a transaction using a plutus reference script, use `--calculate-plutus-script-cost` flag to produce an output file
2. Read the output file

**Expected behavior**
`scriptHash` is always populated

**System info (please complete the following information):**
Node/CLI Version: 43393ac88faa99986ecaa0be409e8b6353f5e9fe

**Comment by CarlosLopezDeLara** [comment]
https://github.com/input-output-hk/cardano-node/pull/4089
