### ISSUE TITLE
[BUG] - cardano-cli transaction build does not consider Babbage as default era after testnet hardfork

### ISSUE THREAD

**Issue by pgwadapool** [input-output-hk/cardano-node#4124]
**Internal/External**
*External*   otherwise.

**Area**

*Other*   cardano-cli

**Summary**
If transaction build option is used in cardano-cli after hardfork, it chooses Alonzo era to build transaction. The default era should be Babbage after hardfork. This is the error reported

Command failed: transaction build  Error: The era of the node and the tx do not match. The node is running in the Babbage era, but the transaction is for the Alonzo era.

Currently I need to use --babbage-era to overcome this problem.
However the transaction build-raw works without any additional era option

**Steps to reproduce**
Build a transaction using 

cardano-cli transaction build 

**Expected behavior**
The expected behavior is that by default transactions should be built with babbage era

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 1.35.0
- CLI version  1.35.0

**Comment by rdlrt** [comment]
Duplicate #3900

**Comment by dorin100** [comment]
keeping only #3900
