### ISSUE TITLE
[BUG] - VASIL cardano-cli query leadership-schedule Error

### ISSUE THREAD

**Issue by IRF160** [input-output-hk/cardano-node#4128]
External

**Summary**
When running the leadership schedule on a block producing node in VASIL on testnet it will error out and not complete

**Steps to reproduce**
1. on a block producing node in testnet running  cardano-cli 1.35.0
2. run the cardano-cli query leadership-schedule --testnet-magic 1097911063 ... --current
3. See error
4. Error: Failed to successfully decode the current epoch state: DecoderErrorDeserialiseFailure "EpochState (BabbageEra StandardCrypto)" (DeserialiseFailure 31063970 "Decoding TxIx: too many bytes.")

**Expected behavior**
Leadership schedule for block production for the current Epoch

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 20.04.4 LTS
- Node version: 
cardano-node 1.35.0 - linux-x86_64 - ghc-8.10
git rev 9f1d7dc163ee66410d912e48509d6a2300cfa68a
- CLI version: 
cardano-cli 1.35.0 - linux-x86_64 - ghc-8.10
git rev 9f1d7dc163ee66410d912e48509d6a2300cfa68a

**Comment by IRF160** [comment]
on Testnet ALTZ PO confirmed same issue on CentOS 7.x

**Comment by reqlez** [comment]
cardano-cli query stake-snapshot --testnet-magic 1097911063 --stake-pool-id xxxxxx    has similar issue on Testnet as well. Runs out of memory, or if you have the 60GB ram or so that it needs, some errors start showing as well.

**Comment by reqlez** [comment]
And to add, somebody just mentioned they had a problem with ledger when restarting a node, similar message:
"cardano.node.ChainDB:Error:5] [2022-07-04 20:26:44.93 UTC] Invalid snapshot DiskSnapshot {dsNumber = 62523736, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 31045716 "Decoding TxIx: too many bytes."))"

**Comment by weebl2000** [comment]
Same problem.

`Command failed: query leadership-schedule  Error: Failed to successfully decode the current epoch state: DecoderErrorDeserialiseFailure "EpochState (BabbageEra StandardCrypto)" (DeserialiseFailure 31553459 "Decoding TxIx: too many bytes.")`

**Comment by CarlosLopezDeLara** [comment]
> 62523736

This one will fix leadership-schedule for babbage era

https://github.com/input-output-hk/cardano-node/pull/4106

**Comment by CarlosLopezDeLara** [comment]
Resolved in https://github.com/input-output-hk/cardano-node/pull/4106
