### ISSUE TITLE
[FR] - leadership-schedule output in JSON and Local timezone

### ISSUE THREAD

**Issue by everestada** [input-output-hk/cardano-node#4139]
**Internal/External**
*External* 

**Area**
*Other*   cardano-cli query leadership-schedule 

**Describe the feature you'd like**
Allow cardano-cli query leadership-schedule to output result in json format and also have option to show time of block schedule in local time.

**Comment by monkey-jsun** [comment]
great idea.  I ended up writing some post-processing script today.  Just FYI, https://forum.cardano.org/t/very-large-slot-number-for-cardano-cli-query-leadership-schedule-why/103127/6

**Comment by everestada** [comment]
--out-file option
