### ISSUE TITLE
High memory usage when running query stake-snapshot and others.

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4140]
Investigate. There might be some way to reduce this by returning results more eagerly. High memory usage when running 

- [x] query stake-snapshot --> https://github.com/input-output-hk/cardano-node/pull/4179
- [x] query leadership-schedule --> Merge https://github.com/input-output-hk/ouroboros-network/pull/3932 before --> https://github.com/input-output-hk/cardano-node/pull/4250 
Waiting for (link to PR) to be merged first 
- [x] query pool-params  --> https://github.com/input-output-hk/cardano-node/pull/4170
- [x] query ledger-state --> https://github.com/input-output-hk/cardano-node/pull/4205
____
Reference issues:

https://github.com/input-output-hk/cardano-node/issues/2717
https://github.com/input-output-hk/cardano-node/issues/4128
____
Additional information

![Screenshot_20220705_191852](https://user-images.githubusercontent.com/64222734/177438312-06343b1a-4c43-4f27-b401-fb1b38f49dd4.png)
![Screenshot_20220705_192055](https://user-images.githubusercontent.com/64222734/177438313-3a642ce5-ff7f-4f50-86a0-28402469bcc0.png)

_____

### Acceptance Criteria 

AC stake snapshot
- Return the total active stake on the system and  the pool stake for the last three stake snapshots
- Do not download the entire ledger state to obtain the stake snapshots
- Command takes less than 5s to return results on a machine that meets the required specs 
- Uses less than 12G of RAM

AC leadership schedule
- Leadership schedule returns valid JSON to stdout and cbor to file
- Running leadership-schedule takes less than 30 seconds 
- Uses less than 12G of RAM

AC pool-state
- This command obsoletes pool-params query
- Pool-params executes pool-state with a notification to the user about the new command 
- Pool-state returns a JSON of futurePoolParams, poolParams, and retiring
- Runs in less than 5 seconds
- Uses less than 12 GB

AC Ledger state
- Keeps returning JSON to stdout
- Uses less than 16 GB

**Comment by dorin100** [comment]
When we say in the Acceptance Criteria "uses less than X GB", I suppose this refers to the recommended specs, right? We are interested to make clear to the users what are the min specs they need in order to have these functionalities working.

"pool-state" is a new cli command?

**Comment by CarlosLopezDeLara** [comment]
Resolved by 

https://github.com/input-output-hk/cardano-node/pull/4179
https://github.com/input-output-hk/ouroboros-network/pull/3932 
https://github.com/input-output-hk/cardano-node/pull/4250
https://github.com/input-output-hk/cardano-node/pull/4170
https://github.com/input-output-hk/cardano-node/pull/4205
