### ISSUE TITLE
bench: UTxO HD in-memory

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4145]
AWS benchmarks for the UTxO HD in-memory backend.

**Comment by deepfire** [comment]
We need details on:

- node version
- node configuration

**Comment by dnadales** [comment]
- Node version: consensus/feature/utxo-hd, currently at 702e87e2f99853bf4d4ce917178e91664eb46ab5
- Node configuration: the default configuration should work (it was updated with the UTxO HD configuration).

**Comment by deepfire** [comment]
We have premature termination, with chain quality progessively falling off the cliff after several hours of run time.

**Comment by deepfire** [comment]
The findings have spurred some PRs:

- https://github.com/input-output-hk/ouroboros-network/pull/3951
- https://github.com/input-output-hk/ouroboros-network/pull/3955
- https://github.com/input-output-hk/ouroboros-network/pull/3882

Once these are merged, @Jasagredo thinks we might have another go.

**Comment by deepfire** [comment]
Quoting @Jasagredo :

> short summary: the In-Memory implementation now should be "almost as fast as pre-utxo-hd" (modulo oddities when a node is forging blocks etc), there should be no more deadlocks when receiving a block and the lmdb implementation will probably become much faster with the last one of those

**Comment by dnadales** [comment]
Blocked on https://github.com/input-output-hk/ouroboros-network/issues/4044

**Comment by Jasagredo** [comment]
Blocked on https://github.com/orgs/input-output-hk/projects/49/views/19

**Comment by Jasagredo** [comment]
Blocked (transitively) on input-output-hk/ouroboros-network#4206

**Comment by Jasagredo** [comment]
We have a rebase on a recent commit and we are going to conduct some basic benchmarks ourselves. However I think it should be ready to be used in your benchmarks @deepfire if it was not because Nix support is not guaranteed and I only succeeded to build `exe:cardano-node`. Could you please specify:

- Do you need `nix` to build the node properly? What exactly should I make sure builds?
- Do you need all components on the `cardano-node` repo to build properly?

**Comment by Jasagredo** [comment]
Blocked by input-output-hk/ouroboros-network#3954. The backing store tests will probably alter the backing store behavior and therefore it is more sensible to wait until those are merged.
