### ISSUE TITLE
Make Babbage Era de new Default after the Vasil HF

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4151]
## What - The user facing feature being implemented

Currently Alonzo is the Default era. 

After the Vasil HF, Babbage needs to  default era so that you don't need the `babbage-era` flag any more. 

## Why

This is consistent with what we have done in the past to default to an era after a HF

- [x] cardano-cli transaction build
- [x] cardano-cli transaction build-raw
- [x] cardano-cli transaction calculate-min-required-utxo

Context: https://input-output.atlassian.net/browse/CAD-4445?focusedCommentId=94990
_"The cli build commnad will need an explicit --babbage-era flag once the Babbage HF happens, up until we switch the default CLI era (to Babbage). Note that this is consistent with other commands: they explicitly need an era flag to use a new era, until the default is changed later."_

## Related GH issues: 
- #3900  
____
**Acceptance Criteria**

- [x] GIVEN that the network is in Babbage, 
WHEN I `build` a transaction 
AND I **do not** provide any era flag 
THEN `build` generates a valid transaction body. 
- [x] GIVEN that the network is in Babbage, 
WHEN I `build` a transaction 
AND I provide the "--babbage-era" 
THEN `build` generates a valid transaction body.
- [x] GIVEN that the network is in Babbage, 
WHEN I `build-raw` a transaction 
AND I **do not** provide any era flag 
THEN `build` generates a valid transaction body. 
- [x] GIVEN that the network is in Babbage, 
WHEN I `build-raw` a transaction 
AND I provide the "--babbage-era" 
THEN `build` generates a valid transaction body.
- [x] GIVEN that the network is in Babbage, 
WHEN I `calculate-min-required-utxo` for a transaction 
AND I **do not** provide any era flag 
THEN `calculate-min-required-utxo` calculates the minimum required value for the transaction output. 

## Definition of done

- [ ] Code review
- [ ] Builds successfully on CI
- [ ] Includes documentation and/or examples for the functionality
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number included in PR description
- [ ] The new functionality is covered by dev/unit/property tests
- [ ] Acceptance Criteria met
- [ ] Test Engineering Sign-off + E2E automated tests

## Sign-off

- [ ] Dev
- [ ] Test Engineering

# Related PR

1.  PR # here --> https://github.com/input-output-hk/cardano-node/pull/4485

**Comment by danger89** [comment]
This make sense

**Comment by newhoggy** [comment]
```
mkdir example/work

CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) query utxo \
  --testnet-magic 42 \
  --address $( \
    cardano-cli address build \
      --testnet-magic 42 \
      --payment-verification-key-file \
      example/utxo-keys/utxo1.vkey
  ) \
  --out-file example/work/utxo.json


user1_utxo="$(cat example/work/utxo.json | jq -r 'to_entries[0].key')"
user1_addr="$(cat example/work/utxo.json | jq -r 'to_entries[0].value.address')"
user1_fund="$(cat example/work/utxo.json | jq -r 'to_entries[0].value.value.lovelace')"

fee=550152

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli query protocol-parameters --testnet-magic 42 > example/work/params.json

cardano-cli transaction build-raw \
  --babbage-era \
  --fee "$fee" \
  --out-file example/tx.body \
  --protocol-params-file example/work/params.json \
  --tx-in "$user1_utxo" \
  --tx-out "$user1_addr+$(($user1_fund - $fee"))"

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction sign --tx-body-file example/tx.body --signing-key-file example/utxo-keys/utxo1.skey --out-file example/tx.body.signed

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction submit --tx-file example/tx.body.signed --testnet-magic 42
