### ISSUE TITLE
tx-generator: reusable API and library

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/cardano-node#4174]

**Comment by mgmeier** [comment]
First step: we use a new namespace `Cardano.TxGenerator` inside the existing project for implementing a minimal functioning example of isolated Tx generation.

**Comment by MarcFontaine** [comment]
This needs to be updated and rebased on https://github.com/input-output-hk/cardano-node/pull/4231

**Comment by mgmeier** [comment]
Branch `tx-generator/pure-example` has been incorporated into #4231 and merged to `master`.
Work on this issue will be tracked on branch `tx-generator/4174-reusable-api-and-library` from now on.

**Comment by mgmeier** [comment]
Continued in PR #4460

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.
