### ISSUE TITLE
The UTxO HD consensus branch breaks tx-generator

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4182]
1. The UTxO HD consensus feature branch in node (`consensus/feature/utxo-hd`, commit `1ecf0e8694fe19bdc22f3021bee6b7c5b45dbbd8`)
2. `make ci-test-autostay` 

..leads to the generator failing with:
```
 tx-generator: user error (TxValidationErrorInMode (ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (ValueNotConservedUTxO (Value 0 (fromList [])) (Value 9000000000000 (fromList []))))),UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (BadInputsUTxO (fromList [TxIn (TxId {_unTxId = SafeHash "7c0f91c9a889e16fcf19713efea5aa0e7145b9d9f5cef1e6fa4150d0ef1259ad"}) (TxIx 0)]))))])) BabbageEraInCardanoMode)
```

**Comment by MarcFontaine** [comment]
After discussion with @deepfire , @dnadales and @Jasagredo it looks like consensus does no longer properly deal with `sgsInitialFunds`.
`sgsInitialFunds` is a feature that is used for testing (and benchmarking) but not on mainnet.
Consensus is investigating the problem.

**Comment by deepfire** [comment]
@MarcFontaine, thank you for the summary of the discussion I had with @Jasagredo.

**Comment by deepfire** [comment]
@Jasagredo bumped consensus to a fixed version in the PR: https://github.com/input-output-hk/cardano-node/pull/4188

**Comment by deepfire** [comment]
@MarcFontaine, btw, thank you for your help in resolving this issue -- specifically, confirming that it is the genesis expenditure that fails in the generator.

This helped us (correctly) guess with @Jasagredo that `sgInitialFunds` handling is the root cause.
