### ISSUE TITLE
Generate a key pair and address

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#423]
`cardano-cli` should have a command to generate a functioning key pair & address.

Relevant: https://github.com/input-output-hk/cardano-sl/blob/parallel-restore/wallet/KeyToy.hs

**Comment by dcoutts** [comment]
When we get to this, it'll be much simpler. Just a `runSecureRandom keyGen` and write the key pair to a pair of files (CBOR serialised).Then another CLI command to read the pub key back in and use `makeAddress`, though this needs to know the network magic.

**Comment by kevinhammond** [comment]
Can we make sure this gets looked at please

**Comment by Jimbo4350** [comment]
This has been implemented.
