### ISSUE TITLE
[BUG] - CLI is not allowing process substitution on certain commands

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#4235]
**_Cardano-CLI 1.34.1_**

In the past it was no problem to use a common practice in linux to not write out files directly (if you only need them in ram) and use a process substitution -> file handler instead. 

For some commands in the CLI this is still working like (example):

**Setting up the variables**

`protocolParametersJSON=`
``` json
{
    "collateralPercentage": 150,
    "costModels": {
        "PlutusScriptV1": {
            "addInteger-cpu-arguments-intercept": 205665,
            "addInteger-cpu-arguments-slope": 812,
            "addInteger-memory-arguments-intercept": 1,
            "addInteger-memory-arguments-slope": 1,
    "....etc....etc.......",
    "stakePoolTargetNum": 500,
    "treasuryCut": 0.2,
    "txFeeFixed": 155381,
    "txFeePerByte": 44,
    "utxoCostPerWord": 34480
}
```

``` console
txBodyFile="/home/user/mytransaction.txbody"; txcnt=1; rxcnt=2; magicparam="--mainnet"; etc ...
```

**Executing the command**

```console
cardano-cli transaction calculate-min-fee \
                    --tx-body-file ${txBodyFile} \
                    --protocol-params-file <(echo "${protocolParametersJSON}") \
                    --tx-in-count ${txcnt} \
                    --tx-out-count ${rxcnt} \
                    ${magicparam} ...
```
The part i am talking about is `<(echo "${protocolParametersJSON}")`, **this is working fine for the command above**. 👍 

-----

But in other commands for example for the tx-file content, this is not working anymore:

**Setting up a variable**

`txFileJSON=`
```json
{
    "type": "Witnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a5008282582055c90e5f39ee7e638da909.....64732c204d617274696e203a2d29"
}
```

**Executing the command**

``` console
cardano-cli transaction txid --tx-file <(echo "${txFileJSON}")
cardano-cli transaction submit --tx-file <(echo "${txFileJSON}") --mainnet
```

**Results into the following error** 😢 
``` console
Command failed: transaction txid  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: /dev/fd/63: TextEnvelope type error:  Expected one of: TxSignedByron, TxSignedShelley, Tx AllegraEra, Tx MaryEra, Tx AlonzoEra, Tx BabbageEra Actual: Witnessed Tx AlonzoEra
TextEnvelopeCddl error: /dev/fd/63: Could not JSON decode TextEnvelopeCddl file at: /dev/fd/63 Error: Error in $: not enough input
```

**So this is not working anymore.** If you write out the content to a file and use the filename it works.

But why/how was this changed? **It worked in previous versions of the CLI.**

-----

As a simple demo that it is not an OS issue we create a simple script that is showing the content of a file:
**_showfile.sh:_**
``` console
#!/bin/bash
whatever_file="${1}"
cat "${whatever_file}"
```

**Execute the script with the process substitution like above:**
``` console
./showfile.sh <(echo "${txFileJSON}")
{
    "type": "Witnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a5008282582055c90e5f39ee7e638da909.....64732c204d617274696e203a2d29"
}
```

All good. So, something changed in the CLI and it would be good to fix it so it can be used like any other linux program together with process substitution on all parameters.

**Comment by gitmachtl** [comment]
The output redirection to the stdout is not working for the VRF-Key creation!

``` console
$ cardano-cli node key-gen-VRF --verification-key-file "test.vrf.vkey" --signing-key-file /dev/stdout

cardano-cli-1.35.3-rc1: /dev/: openTempFile: permission denied (Permission denied)
```

Why the heck on earth wants cardano-cli to write a TempFile in the path given for the output signing key!?
Writing to /dev/stdout works for all other commands, but not for the VRF keys. We need this to do secure key handling without the need to write them out to file on the HDD.

**Comment by LudvikGalois** [comment]
> Issue is most likely caused by libsodium.

It's actually caused by `writeFileWithOwnerPermissions` from `Cardano.API.SerialiseTextEnvelope`. Which makes a new file and then renames it to the target to clobber any existing file. This seems like a hack.

**Comment by saratomaz** [comment]
### Issue unsolved

_Setting up a variable_
```
txFileJSON=$(cat <<-EOF
{
  "type": "Unwitnessed Tx BabbageEra",
  "description": "Ledger Cddl Format",
  "cborHex": "84a300818258208a5a31ae52cdc140b1c532c47d5cb3c8dbc6c9b7a4aa537ed9e3543ea94cfad1000183a200581d60768d2bcd29a84ae015d96118e3285bc0cbd399ae16039ad471c8a806011a001e8480a200581d60768d2bcd29a84ae015d96118e3285bc0cbd399ae16039ad471c8a806011a002625a0a200581d600ac4d3db1163e7884959c0317aa19263a236db113fa0fbefbd49b335011a00958d31021a0003094fa0f5f6"
}
EOF
)
```

**Tested on tag 1.35.4-rc1**

`cardano-cli transaction txid --tx-file <(echo "${txFileJSON}")
`
```console
Command failed: transaction txid  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: /dev/fd/63: TextEnvelope aeson decode error: Error in $: not enough input
TextEnvelopeCddl error: /dev/fd/63: Could not JSON decode TextEnvelopeCddl file at: /dev/fd/63 Error: Error in $: not enough input
```
 _If you write out the content to a file and use the filename it works._
`cardano-cli transaction txid --tx-file <same_content_in_file>`
```console
a2e58d1b59d8c06535a1134f0022b1c77b5dc679248f635197546b6855830730
```


**Tested on latest master**

`cardano-cli transaction txid --tx-file <(echo "${txFileJSON}")
`
```console
cardano-cli: TODO
CallStack (from HasCallStack):
  error, called at src/Cardano/CLI/Shelley/Run/Transaction.hs:212:32 in cardano-cli-1.36.0-LXoqbxN0MejLJIylH9D3mJ:Cardano.CLI.Shelley.Run.Transaction(.env) 
```
 _If you write out the content to a file and use the filename it works._
`cardano-cli transaction txid --tx-file <same_content_in_file>`
```console
a2e58d1b59d8c06535a1134f0022b1c77b5dc679248f635197546b6855830730
```

**Comment by gitmachtl** [comment]
> The output redirection to the stdout is not working for the VRF-Key creation!
> 
> ```
> $ cardano-cli node key-gen-VRF --verification-key-file "test.vrf.vkey" --signing-key-file /dev/stdout
> 
> cardano-cli-1.35.3-rc1: /dev/: openTempFile: permission denied (Permission denied)
> ```

I can confirm that this is now working with cardano-cli 1.35.4 for the VRF-Key output redirection.

The issue with the filereading @saratomaz pointed out above is still not working.
