### ISSUE TITLE
[BUG] - Local encoding UTF-8 problem with cardano-testnet

### ISSUE THREAD

**Issue by guido-sofer** [input-output-hk/cardano-node#4244]
**Internal/External**
*Internal* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
 `cardano-testnet: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)` error while running cardano-testnet

**Steps to reproduce**
1. `$ cabal build cardano-cli cardano-node cardano-node-chairman cardano-testnet`
2. `$ cabal run cardano-testnet`

**Expected behavior**
running cardano-testnet

**System info:**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 6471c31f8b61798df57a9f3345548703295cac9e
- CLI version  6471c31f8b61798df57a9f3345548703295cac9e

**Additional context**
workarround: fixed it doing `export LANG=C.utf8` although doesn't seam correct

**Comment by mkoura** [comment]
Looks like similar issue as was fixed for `cardano-cli` by https://github.com/input-output-hk/cardano-node/pull/4018/

**Comment by Jimbo4350** [comment]
Closing. Please re-open if still relevant.
