### ISSUE TITLE
Pool withdrawn at epoch 349 but the deposit is still not returned

### ISSUE THREAD

**Issue by orelvis15** [input-output-hk/cardano-node#4245]
I removed my pool several weeks ago, this is the information that cntool returns to me:

```
Pool Name             : ore
ID (hex)              : 95058e35e724774838784aafa1a3479de1aa676efa97a30113089ea6
ID (bech32)           : pool1j5zcud08y3m5swrcf2h6rg68nhs65emwl2t6xqgnpz02v9ffq93
Registered            : NO - Retired in epoch 349
```

I never registered the rewards address, but they still don't return my deposit :(

Wallet information from cntool: 

```
Registered           : YES
Address              : addr1q95yjwq7q2phnc5c4zjsr8evekcmehhvkgsc9h3ueqvma2wtr0l7xw4pxnu80n5uh9pe8yrtwefd7uyzjl57jfteet7slhj30t
Enterprise Address   : addr1v95yjwq7q2phnc5c4zjsr8evekcmehhvkgsc9h3ueqvma2gem0uny
Reward/Stake Address : stake1u893hllr82snf7rhe6wtjsunjp4hv5klwzpf060fy4uu4lg6taa6p
Rewards Available    : 0 Ada
Funds + Rewards      : 0 Ada
Encoding             : bech32
```

**Comment by btbf** [comment]
Check with CLI and you will see that your deposit has been refunded.

cardano-cli query stake-address-info \
 --mainnet \
 --address stake1u893hllr82snf7rhe6wtjsunjp4hv5klwzpf060fy4uu4lg6taa6p

**Comment by orelvis15** [comment]
To which wallet should the deposit go, because the one registered in the pool has the same amount.

**Comment by orelvis15** [comment]
ready there I saw that in my Reward / Stake Address is the deposit. Thanks a lot!.

One question, is there any way to make a transaction using cardano-cli without having the cardano node synchronized?

**Comment by btbf** [comment]
Transactions must always be sent by a node that is synchronized with the latest block. 
Transmission is possible even from passive nodes.

**Comment by gitmachtl** [comment]
@orelvis15 please close the issue, thx
