### ISSUE TITLE
[FR] - Upgrade to GHC 9.2.4?

### ISSUE THREAD

**Issue by L-as** [input-output-hk/cardano-node#4256]
**Internal/External**
*External*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
Now that 9.2.4 is in haskell.nix (https://github.com/input-output-hk/haskell.nix/pull/1566)
it seems feasible to port the Cardano ecosystem to it.
It notably supports deep subsumption, which was a barrier to adoption before.

I made this issue here since this is the "root" of most of the relevant libraries.

**Describe alternatives you've considered**
Wait for 9.4.1

**Comment by reqlez** [comment]
9.2.4 could be good. However, everybody is now focused on 1.35.x release... maybe something to consider after all is released :)

**Comment by reqlez** [comment]
Maybe now that Vasil is over, somebody can work on GHC 9.2.5 support ( 9.2.4 got a bit too buggy )! Any takers ;-)

**Comment by locallycompact** [comment]
I think this isn't really blocked by much, but for the fact that a compatible version of plutus is required.

https://gitlab.homotopic.tech/horizon/wave-ocean/horizon-wave-ocean-platform/-/jobs/192861

**Comment by newhoggy** [comment]
`cardano-node` builds with `ghc-9.2.5`.  There may be remaining work with `ghc-9.2.5` in which case specific issues should be raised for those.

See https://github.com/input-output-hk/cardano-node/pull/4701
