### ISSUE TITLE
tx-generator: fix complexity problems with use of ix-set

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/cardano-node#4275]
Replace `type FundSet = IxSet FundIndices Fund` with `type FundSet = IxSet FundIndices (FundTag, FIFO Fund)`.
Split `Fund` into `Fund` and `FundTag`. (Maybe just remove sequence-number).
All transaction/funds created in a single loop/splitting-phase have the same Lovelace/FundTags. There is only a small variation
of FundTags/ouput-values and the complexity to manage those tags  in an `ix-set` is (most likely) OK.
All transactions with the same tag go into the same FIFO.

Question? it may even be possible to put 'walletName' in the `FundTag` and use only a single `FundSet` in the whole tx-generator.   
(This can be implemented in a second step)

**Comment by MarcFontaine** [comment]
An other approach to fix the ix-set problem was taken:
Remove ix-sets alltogether.

https://github.com/input-output-hk/cardano-node/pull/4292

**Comment by mgmeier** [comment]
merged: `IxSet` has been removed entirely. Funds are now organized in a fifo queue (`FundSet`).
