### ISSUE TITLE
Deprecate intermediate tx body cli format

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#4277]
## What 
Remove the ability to create tx bodies with the intermediate cli format. We want all transaction bodies to be serialized in the CDDL format. Note we maintain backwards compatibility for now, i.e we can still read tx bodies with the intermediate cli format.

## Why 
Having two serialization formats for the transaction body will create compatibility issues in the ecosystem. We don't have a good justification for this, therefore we want to only use the CDDL format.

## Personas - Who will this affect?

- [ ] SPO
- [x] Dapp Devs
- [ ] Exchanges

## Acceptance Criteria

* When building a transaction the user no longer has the options `--cddl-format` and `--cli-format` for the output transaction body. 

* The resulting transaction body from building transactions is always cddl formatted. 

* A transaction body created using --cli-format (i.e. created with a previous version) can still be signed and submitted to the chain successfully.  

* A transaction body created with --cddl-format  (i.e with a previous version) can be signed and submitted successfully 

## Definition of done

- [x] Code review
- [x] Builds successfully on CI
- [x] Includes documentation and/or examples for the functionality - N/A
- [x] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [x] Ticket number included in PR description
- [x] The new functionality is covered by [dev/unit/property tests](https://github.com/input-output-hk/cardano-node/pull/4303/commits/5ed7206d4b562bfaf42df0844d8681e3ef9e87be#diff-155921d904c0df296270e8d4e714e51883b66f3642290e83b717be2587ca1834R18) 
- [x] Acceptance Criteria met
- [ ] Test Engineering Sign-off + E2E automated tests

## Sign-off

- [ ] Dev
- [x] Test Engineering

**Comment by CarlosLopezDeLara** [comment]
PR --> https://github.com/input-output-hk/cardano-node/pull/4303

**Comment by dorin100** [comment]
@CarlosLopezDeLara does this ticket have any impact on any user functionalities? if yes, we would need Acceptance Criteria for it. If not, the acceptance criteria could state that this change will be transparent for the end users.
