### ISSUE TITLE
[BUG] - cardano-submit-api hardcodes 0.0.0.0:8081 for serving metrics

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#4280]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The `cardano-submit-api` REST service can be configured to listen on specific port and address for submitting transactions. However in addition to that address and port, it listens also on 0.0.0.0:8081 and this cannot be reconfigured, see https://github.com/input-output-hk/cardano-node/blob/006be46d424574d5bc29f1a51f32d103cc20558e/cardano-submit-api/src/Cardano/TxSubmit/Metrics.hs#L30

This has several consequences:
* it is impossible to run several instances of `cardano-submit-api` service on the same machine
* the service can collide with another service that is configured to use that port
* the service can potentially expose metrics to the internet (since it listens on 0.0.0.0).

**Expected behavior**
The metrics host and port is configurable.

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: 1.35.3-rc1
- CLI version: 1.35.3-rc1

**Comment by rdlrt** [comment]
#3452
