### ISSUE TITLE
New nodes have an odd warning about being TooFarAhead when first synced 

### ISSUE THREAD

**Issue by oneEdoubleD** [input-output-hk/cardano-node#429]
If you start a byron-proxy and node connected to that proxy, both without existing state, the node throws this warning:

[edward:cardano.node.Forge:warning:44] [2019-12-18 12:40:51.00 UTC] {"kind":"TraceCouldNotForge","reason":"TooFarAhead","slot":3523488}

It's not fatal and the node works once the proxy has booted up. Re-create it by cloning both repos, use `nix-build -A scripts.mainnet.node/proxy` and start them up around the same time.

**Comment by ArturWieczorek** [comment]
This is controlled through `IsProducer` now.

> If you pass in credentials (that are needed to sign blocks), `isProducer` will be enabled. 
> If no credentials are passed, it will be disabled.

_Information from Thomas Winant_

Closing this one as:

https://github.com/input-output-hk/ouroboros-network/issues/1370
https://github.com/input-output-hk/ouroboros-network/pull/1371

are closed/merged.
