### ISSUE TITLE
New Tracing System

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4312]
What?
---
The new tracing system, based on the `trace-dispatcher` and `cardano-tracer` components is a complete rewrite of the node tracing system.

Why?
---
The new tracing system provides the following benefits:

1. Maintainability: the legacy code is very difficult to reason about -- so features are harder to implement and bugs are harder to find.
2. Performance: the performance characterstics of the legacy tracing are hard to reason about.  The new system differs in following ways:
    - based on an _arrow-based_ contravariant abstraction, which allows for explicit separation and sharing of stateful computations -- enhancing our performance reasoning abilities.
    - generally, has a much cleaner implementation that is easier to reason about.
    - performs better (uses less memory and spends less CPU), and without performance hacks like `TraceXXX: false` cut-off flags.
3. Configuration simplicity:
    - there is just a single, namespace-based layer of configuration -- instead of two conflicting layers in the legacy system (all the `TraceXXX` options that control the performance-cutoff hack).
    - the RTView component is now part of the `cardano-tracer` component, so is very easy to enable.
4. Flexibility:
    - the configuration is dynamic, because there are no static performance cut-off flags.
5. Documentation:
    - the system is self-documenting -- therefore enabling automated generation of a central index of all tracers.  This is very important because there are hundreds of different traces emitted by the node.
6. Reduces the intra-node code complexity and overheads:
    - we move out all unnecessary trace handling complexity out of the node into a separate `cardano-tracer` component.
7. Enables the next-generation of RTView.
8. Provides a rich state API -- DataPoints now allow querying the node for structured state, in a metrics-like fashion.  This is an enabler for richer and simpler node integrations -- for components such as Daedalus and DB Sync.

Definition of done
---
1. The new tracing system is the default, and is released to the SPO community.
2. The distributed testnet benchmarks use the new tracing system.

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.
