### ISSUE TITLE
Review triaging bug reports workflow

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4327]
### WHAT 

Define roles on the triaging process. 
The triaging workflow needs to answer the following questions for a bug report.

- Is it a valid bug? i.e found on a supported version, is it reproducible 
- Does the bug report contain sufficient details?
- Has it been reported before? link/group similar tickets? 
- Whats the severity? (Impact on functionality)  
    - Critical
    - Major
    - Minor
    - Low
- Whats the priority? (urgency of fixing a defect)
    - Urgent
    - High
    - Medium
    - Low
- Is the bug report ready to be worked on by a developer?

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.
