### ISSUE TITLE
[FR] - Information about Cardano node environment

### ISSUE THREAD

**Issue by orelvis15** [input-output-hk/cardano-node#4333]
**Internal/External**

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
Is there an api that provides information about the environment where the cardano pools are running, for example
- Operating System
- Pool Resources (or an average)
- Percentage of use of the different versions of cardano node
- etc....

I think this information would be very useful for developers who want to create tools for pool administrators.
For example, I am currently developing [Cardano Version Manager](https://github.com/orelvis15/cvm) and having information like this helps me decide which way to go with regards to development.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.
