### ISSUE TITLE
[BUG] - cardano-node fatal Error on starting the mainnet node with existing configuration files.

### ISSUE THREAD

**Issue by nithb** [input-output-hk/cardano-node#4337]
**Internal/External**
*External* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Cardano-node is shutting down due to a fatal Error while reading the topology file. This error happens only for mainnet, testnet is working fine.

**Steps to reproduce**

All the files were downloaded from and run the bash with following commands.
[https://hydra.iohk.io/build/13695229/download/1/index.html]([https://hydra.iohk.io/build/13695229/download/1/index.html])

cardano-node run  --config $HOME/cardano-mainnet/mainnet-config.json  
--database-path $HOME/cardano-mainnet/db 
 --socket-path $HOME/cardano-mainnet/db/node.socket  
--host-addr 127.0.0.2  
--port 1302  
--topology $HOME/cardano-mainnet/mainnet-topology.json

Error: 
cardano-node: FatalError {fatalErrorMessage = "Cardano.Node.Run.handleSimpleNodeNonP2P.readTopologyFile: Cardano.Node.Configuration.Topology.readTopologyFile: home/cardano-mainnet/mainnet-topology.json\r: openBinaryFile: does not exist (No such file or directory)"}

**Expected behavior**
Node should start and sync the db

System info
- OS Name: Ubuntu 64 bit
- OS Version : 22.04
- Node version : 1.35.3 git rev 950c4e222086fed5ca53564e642434ce9307b0b9
- CLI version : 1.35.3 git rev 950c4e222086fed5ca53564e642434ce9307b0b9

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by erikd** [comment]
The problem and its solution is plain from the error message:
```
cardano-node: FatalError {fatalErrorMessage = "Cardano.Node.Run.handleSimpleNodeNonP2P.readTopologyFile: Cardano.Node.Configuration.Topology.readTopologyFile: home/cardano-mainnet/mainnet-topology.json\r: openBinaryFile: does not exist (No such file or directory)"}
```
The file topology file seems to be missing. Provide a topology file (same please you got `mainnet-config.json`) and it should be fine.

Also check how you have defined the `$HOME` environment variable. There should be a leading `/`.

**Comment by nithb** [comment]
Hi Erik,

There was another problem with bash, not sorted out all okay. Thank you
