### ISSUE TITLE
Announcements keep asking to use Vasil tags, but there are no github templates

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-node#4353]
Ideally, this should not have landed up on github, but since there was no response from Beck/Ben/Tim/co who manage comms/announcements, ending up creating issue here.

IO announcements ask SPOs to tag something on github when raising issues, but the only issue template on repositories are `bug` and `feature-request`. Thus, there isnt a way for us to add a label.

Ofcourse, this is expected on github platform, but given the lack of attention to feedback, either github templates OR comms need to adapt

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.
