### ISSUE TITLE
trace-dispatcher / node: metric registration clash

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4367]
We see the dreaded `ExceptionInLinkedThread "ThreadId 33" The name ""slotsMissed"" is already taken by a metric.` once more.

This time found by @fmaste, on a recent `master`, while running inside Docker:

```
node-4    | cardano-node: ExceptionInLinkedThread "ThreadId 33" The name ""slotsMissed"" is already taken by a metric.
node-4    | CallStack (from HasCallStack):
node-4    |   error, called at ./System/Metrics.hs:214:5 in ekg-core-0.1.1.7-LyPC4OzssyMIbAlQK2bJI4:System.Metrics
```

**Comment by jutaro** [comment]
We have to clarify if the code base used is the current version. The name "slotMissed" is not used any more for a metric, and the general problem should have been fixed in this patch https://github.com/input-output-hk/cardano-node/commit/ad316eabbe8da3b2ab72085387f835461c9e9f04

**Comment by jutaro** [comment]
I found out that commit https://github.com/input-output-hk/cardano-node/commit/ad316eabbe8da3b2ab72085387f835461c9e9f04 which was merged into master on 28. of June is missing for Release 1.35 branch.

**Comment by deepfire** [comment]
Already fixed.
