### ISSUE TITLE
db-synthesizer: add a DB append mode

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4368]
For disaster recovery, an append mode of the `db-synthesizer` would be instrumental -- whereas currently it only has a create-from-scratch mode.

It would appear that getting there "only" requires these steps:

1. introduce dispatch for the DB to use for block addition
2. as an option in this dispatch, add a mode where we open an existing DB
3. add a two-phase test -- create-then-append

**Comment by mgmeier** [comment]
cf. https://github.com/input-output-hk/ouroboros-network/pull/3972

- new append mode enhancement implemented for `db-synthesizer`
- added append step to existing test case

**Comment by deepfire** [comment]
Just needs to be merged.

**Comment by Jimbo4350** [comment]
Closing. Please re-open if still relevant.
