### ISSUE TITLE
[BUG] - misleading "MAIN THREAD FAILED" error message on shutdown/restart

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#4369]
*Internal*

**Area**
*Other* 

**Summary**
Commit fccd10ad2eab332ee6379526e8048bdfa6e88dd7 introduced a "MAIN THREAD FAILED" error message. This message is logged even during user initiated node shutdown/restart, which is misleading.

**Expected behavior**
No error message should be logged on clean shutdown initiated by user.

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: 4334fbeb2390d0afa7890ffd0d794ac10294c494
- CLI version: 4334fbeb2390d0afa7890ffd0d794ac10294c494

**Comment by mkoura** [comment]
CC @coot

**Comment by dorin100** [comment]
cc @CarlosLopezDeLara

**Comment by coot** [comment]
Oh, this is wrong indeed.
