### ISSUE TITLE
[BUG] - cardano-node docker image still supports "testnet" and does not support new networks ("preview", "preprod")

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/cardano-node#4370]
**Internal/External**
*Internal*  

**Area**
*Docker*   

**Summary**
One can still start `testnet` using cardano-node docker image:
```
docker run -v /data -e NETWORK=testnet inputoutput/cardano-node:1.35.3
```
However new configurations, like `preview` and `preprod` are not available, e.g.:
```
$ docker run -v /data -e NETWORK=preview inputoutput/cardano-node:1.35.3
[Error] Managed configuration for network preview does not exist
```
or
```
$ docker run -v /data -e NETWORK=preprod inputoutput/cardano-node:1.35.3
[Error] Managed configuration for network preprod does not exist
```

**Steps to reproduce**
```
$ docker run -v /data -e NETWORK=preview inputoutput/cardano-node:1.35.3
[Error] Managed configuration for network preview does not exist
```
or
```
$ docker run -v /data -e NETWORK=preprod inputoutput/cardano-node:1.35.3
[Error] Managed configuration for network preprod does not exist
```

**Expected behavior**
`testnet` should probably not be supported any longer.
It would be nice to have `preprod` and `preview` configs available.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version (1.35.3 from dockerhub)

**Additional context**
Having new configurations inside the cardano-node docker will let downstream components to easily provide docker-compose files containing cardano-node supporting new networks "out of the box" (e.g. cardano-wallet's [docker-compose.yml](https://github.com/input-output-hk/cardano-wallet/blob/master/docker-compose.yml))

**Comment by CarlosLopezDeLara** [comment]
Resolved with https://hub.docker.com/layers/cardano-node/inputoutput/cardano-node/1.35.3-configs/images/sha256-07d79d45f1798102b5f6b8f5ac54e4e9b8b5c9d22818fc4ccba0bb0cd6db60a6?context=explore

```
docker pull inputoutput/cardano-node:1.35.3-configs
1.35.3-configs: Pulling from inputoutput/cardano-node
91c7976d6c4f: Already exists
52b19659f8df: Pull complete
Digest: sha256:07d79d45f1798102b5f6b8f5ac54e4e9b8b5c9d22818fc4ccba0bb0cd6db60a6
Status: Downloaded newer image for inputoutput/cardano-node:1.35.3-configs

carloslopezdelara@iMacCLR-9 TEMP % docker run -v /data -e NETWORK=preprod inputoutput/cardano-node:1.35.3-configs
Starting: /nix/store/994ak83vm2hfbqm86grj0b0akv9gfaz6-cardano-node-exe-cardano-node-1.35.3/bin/cardano-node run
--config /nix/store/6rm1l2n0b68cif23j3qwapmmwkkz4whq-config-0-0.json
--database-path /data/db
--topology /nix/store/gz1l3l34lj0qda4i9pc5yxq1q9lj7kgw-topology.yaml
--host-addr 0.0.0.0
--port 3001
--socket-path /ipc/node.socket
...
```
