### ISSUE TITLE
[BUG] - Missing blocks on 1.35.3 with freshly generated operational certificate

### ISSUE THREAD

**Issue by DEADPXLZ** [input-output-hk/cardano-node#4383]
**Internal/External**
*External*   otherwise.

**Area**
Vasil / KES key rotation / Operational certificate

**Summary**
Missing blocks on 1.35.3 with freshly generated operational certificate and newly-rotated KES keys

**Steps to reproduce**
1. Upgrade to cardano-node v. 1.35.3

2. Issue new op. certificate by following the official guidelines found [here](https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/KES_period.md#warning-vasil-hard-fork-breaking-changes) and echoed by [this article](https://ecp.gitbook.io/how-to-guides-for-coincashew-method-cardano-spos/maintenance-and-daily-operations/maintenance-and-daily-operations/renew-kes-keys).

**Expected behavior**
Minting new blocks should behave normally

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 20.04
- Node version: 1.35.3
- CLI version: 1.35.3

**Before issuing new certificate** cardano-cli query kes-period-info outputs this:
![Screenshot 2022-08-24 at 21 42 08](https://user-images.githubusercontent.com/83417674/186515489-1bcbdecd-6b48-41cd-91ce-22c1d2feb7f0.png)

**After issuing new certificate** cardano-cli query kes-period-info outputs this:
![d4e64bfd11667aa31543c2e1e0e2a54c7c969241](https://user-images.githubusercontent.com/83417674/186515822-7af82482-b23f-4093-a0cb-c3c0b57ef4db.png)

Then, when we eventually reach the slot assigned to the node for block production the **logs on the BP** output this: 

```
Aug 24 16:30:45 cardano-node[558984]: [:cardano.node.LeadershipCheck:Info:253] [2022-08-24 16:30:45.00 UTC] {"chainDensity":4.8052527e-2,"credentials":"Cardano","delegMapSize":1213997,"kind":"TraceStartLeadershipCheck","slot":69792354,"utxoSize":8428808}
Aug 24 16:30:45 cardano-node[558984]: [cardano.node.Forge:Info:253] [2022-08-24 16:30:45.02 UTC] fromList [("credentials",String "Cardano"),("val",Object (fromList [("kind",String "TraceNodeIsLeader"),("slot",Number 6.9792354e7)]))]
Aug 24 16:30:45 cardano-node[558984]: [cardano.node.Forge:Info:253] [2022-08-24 16:30:45.04 UTC] fromList [("credentials",String "Cardano"),("val",Object (fromList [("block",String "350ec4c630a803bc9b6df2e2c9b0ab22f5f34ba5d294ede7a8fbe223c4c6f766"),("blockNo",Number 7667871.0),("blockPrev",String "82f0d662df2182fa2b817ab1efe457f5f3c86406363933013b46a1ccc4ec39fe"),("kind",String "TraceForgedBlock"),("slot",Number 6.9792354e7)]))]
Aug 24 16:30:45 cardano-node[558984]: [cardano.node.ChainDB:Notice:243] [2022-08-24 16:30:45.07 UTC] Chain extended, new tip: 350ec4c630a803bc9b6df2e2c9b0ab22f5f34ba5d294ede7a8fbe223c4c6f766 at slot 69792354
```
While **the relay logs** output this:
`Aug 24 16:30:51  cardano-node[3620399]: [:cardano.node.ChainDB:Info:12737] [2022-08-24 16:30:51.14 UTC] Block fits onto some fork: 350ec4c630a803bc9b6df2e2c9b0ab22f5f34ba5d294ede7a8fbe223c4c6f766 at slot 69792354`

I initially thought that I lost the block to a slot battle however pooltool does not show any slot battles for the lost block (at height 7667871):
![e56a96b6c0da5f5db63f94739353fc935160b96d](https://user-images.githubusercontent.com/83417674/186515794-797b7b13-a871-477d-8af5-857b6607ae3f.png)

After missing a couple of blocks because of this issue, I reverted back to my old **node.cert** and **kes.skey** files, restarted the BP without changing any other setting and lo and behold, a block was minted!

Anyone else bump into this issue? Any help would be appreciated!

**Comment by matiwinnetou** [comment]
I have not seen this issue as our opcert is still valid but... a workaround would then be to generate opcerts using 1.34.1?

**Comment by DEADPXLZ** [comment]
Yup, this is the on-going experiment atm - waiting to see if minting blocks works with 1.34.1-generated op cert + KES keys.

**Comment by CarlosLopezDeLara** [comment]
On which network is this?

**Comment by fuadiansyah** [comment]
> On which network is this?

Mainnet, I believe

**Comment by kevinhammond** [comment]
The slot number suggests mainnet

**Comment by kevinhammond** [comment]
Are you aware of the changes to op cert numbers?

- Restricted opcert issue number increment, as of Babbage. Previously op cert issue numbers could be anything, provided it was larger than previously used numbers. Now the op cert counter must be exactly one more than the previously *used* op cert.

**Comment by DEADPXLZ** [comment]
Mainnet, yes!

**Comment by psychomb** [comment]
Is there any reason why the relay sees the block ~6 seconds after production ?

**Comment by kevinhammond** [comment]
Also, can we confirm this is the tagged 1.35.3 release and not `master`, please

**Comment by feqifei** [comment]
I rotated my KES keys some weeks ago using 1.35.1 release. "qKesKesKeyExpiry" is null in my case too, but my node is producing blocks.
There is a difference compared to the output of your certificate. In my case "qKesNodeStateOperationalCertificateNumber" and "qKesOnDiskOperationalCertificateNumber" have the same value (9)

![image](https://user-images.githubusercontent.com/42180581/186968503-8b04451c-5892-441f-b6de-4cd77768997f.png)

**Comment by gitmachtl** [comment]
Had no issues so far with KES and Opcert generated on old and new nodes, in babbage era or in alonzo era. The “null” output of cli-1.35.3 is simply an output bug of the cli function imo. I am minting Blocks in all chains with mixed nodes, no problem here. The most important parameters are:

```
qKesNodeStateOperationalCertificateNumber
qKesOnDiskOperationalCertificateNumber
qKesStartKesInterval
```
So you can do a check if the curent opcert is still in the kes interval. BUT, i always generate a new KES + OpCert Pair, no reusing old KES keys over and over again.

**Comment by angelstakepool** [comment]
I am also seeing **qKesKesKeyExpiry: null** for a current certificate that is minting blocks on 1.35.3 and was generated with 1.34.1;  this kes key expires in 62 days though

I ran "cardano-cli query kes-period-info" with this certificate on a node that is still running 1.34.1 and the output was correct this time

**Comment by gitmachtl** [comment]
> I initially thought that I lost the block to a slot battle however pooltool does not show any slot battles for the lost block (at height 7667871):

That does not say anything. Pooltool is missing many "battles", because it depends on the data other users send in via there relays. So if the other blockhash was not seen by any of those, than pooltool can also not report it. Doesn't mean that there was not battle.

**Comment by gitmachtl** [comment]
This https://github.com/input-output-hk/cardano-node/blob/950c4e222086fed5ca53564e642434ce9307b0b9/cardano-cli/src/Cardano/CLI/Shelley/Output.hs#L103 should most likely be with `qKesInfoKesKeyExpiry` and not with `qKesKesKeyExpiry` ?

**Comment by mrbrinker** [comment]
Should not 
**qKesNodeStateOperationalCertificateNumber
qKesOnDiskOperationalCertificateNumber**
match in your 1.35.3 updated op.cert?

**Comment by fuadiansyah** [comment]
> Should not **qKesNodeStateOperationalCertificateNumber qKesOnDiskOperationalCertificateNumber** match in your 1.35.3 updated op.cert?

Yes and no. Yes, if you've already minted a block with your new op cert. No, but incremented by exactly one if you updated the op cert and haven't minted a block with the new cert yet.

Reference: https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/7_KES_period.md

**Comment by DEADPXLZ** [comment]
Happy to report that the node is minting blocks by using an op cert + KES keys created via 1.34.1
Note that as part of the effort to fixing this issue I also restarted relays, updated topology and added Chrony into the mix on both BP + relay nodes so as to offset any potential sync issues.

Nodes running on mainnet with this version
```
cardano-node 1.35.3 - linux-x86_64 - ghc-8.10
git rev 950c4e222086fed5ca53564e642434ce9307b0b9
```

**Comment by brouwerQ** [comment]
If you didn’t had Chrony installed before, the issue would probably be caused only because of this, especially because your relay saw the block only six seconds later. I had a similar issue in the very early lifetime of our pool (our second elected slot ever).

That this happened after rotating KES most likely is a coincidence.
