### ISSUE TITLE
[BUG] - Strange issue with vKey Witness - 1.35.3 - PreProd

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#4400]
Not sure currently if this is a node/cli or hw-signing problem. Original issue:

https://github.com/vacuumlabs/cardano-hw-cli/issues/133

@JaredCorduan

**Comment by JaredCorduan** [comment]
I've commented in the original issue.

**Comment by gitmachtl** [comment]
Was a testing-environment issue.
