### ISSUE TITLE
[BUG] - wrong systemd socket configuration

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#4407]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   systemd socket configuration.

**Summary**
A clear and specific description of what the bug is.

The [systemd socket](https://github.com/input-output-hk/cardano-node/blob/master/nix/nixos/cardano-node-service.nix#L636-L653) configuration should be improved.  The minimal configuration should look like:

```
[Socket]
ListenStream=IPv4Addr:PORT
NoDelay=true
ReusePort=true
FreeBind=true

[Socket]
ListenStream=IPv6Addr:PORT
NoDelay=true
ReusePort=true
BindIPv6Only=true
FreeBind=true

[Socket]
ListenStream=PATH
RemoveOnStop=true
```

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.
