### ISSUE TITLE
remove out of date config files

### ISSUE THREAD

**Issue by paradoxicalsphere** [input-output-hk/cardano-node#4415]
With the release of https://github.com/input-output-hk/cardano-node/releases/tag/1.35.3-configs please remove links to out of date configuration files from https://book.world.dev.cardano.org/environments.html

**Comment by dorin100** [comment]
duplicate of https://github.com/input-output-hk/cardano-node/issues/4406

**Comment by Jimbo4350** [comment]
Closing because this is a duplicate of #4406
