### ISSUE TITLE
[FR] - Example of FR

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4423]
## What - The user facing feature being implemented

Depeacating the CLI intermediate format

## Why 

Intermediate format does not follow the CDDL format which creates compatibility issues with libraries in the ecosystem. 

## Personas - Who will this affect?

- [ ] SPO
- [ ] Dapp Devs
- [ ] Exchanges

## Acceptance Criteria

As END USER for all personas

- [ ] We should be able to sign transaction bodies that are formatted in the cli intermediate format. 
cardano-cli transaction sign
- [ ] The following flags should no longer be available in the bulid and build-raw command `--cddl-format` and `--cli-format`
- [ ] We should be unable to create a tx body in the cli intermediate format

## Defiition of done

- [ ] Code review
- [ ] Builds successfully on CI
- [ ] Includes documentation and/or examples for the functionality
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number included in PR description
- [ ] The new functionality is covered by dev/unit/property tests
- [ ] Acceptance Criteria met
- [ ] Test Engineering Sign-off + E2E automated tests

## Sign-off 

- [ ] Dev 
- [ ] Test Engineering

# Related PR 

1.  PR # here

**Comment by Jimbo4350** [comment]
We can close this now as we have an issue template and examples of it in use
