### ISSUE TITLE
tracing: plan removal of the legacy tracing

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4451]
Current idea:

1. release officially the new one for cardano-node: make it the default, indoctrinate SPOs (some of which are already using it, btw, due to RTView) & announce deprecation of legacy -- with indefinite time frame
2. gauge feedback
3. decide on the date of removal, based on feedback & announce to SPOs
4. once №3 hits, execute the removal

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
