### ISSUE TITLE
[FR] - Make `cardano-api/gen` a normal library again due to haskell.nix incompatibility.

### ISSUE THREAD

**Issue by MangoIV** [input-output-hk/cardano-node#4455]
**Internal/External**
*External* When trying to depend on the `cardano-node/cardano-api/gen` lib, the `ghcWrapper` somehow doesn't include the lib in the shell environment. This makes it not really usable as a dependency. 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
I would like the `gen` library to be a normal toplevel library as long as all the bugs with `sublibs` aren't fixed. 

**Describe alternatives you've considered**
The alternative is fixing [`haskell.nix`](https://github.com/input-output-hk/haskell.nix/issues/1662) and/or `cabal` 

**Additional context / screenshots**
Also see [this issue on `haskell.nix`](https://github.com/input-output-hk/haskell.nix/issues/1662)

**Comment by newhoggy** [comment]
It's not possible to make `library cardano-api:gen` a separate package because `test-suite cardano-api:cardano-api-test` depends on `library cardano-api:gen` which in turn depends on `library cardano-api`.

`test-suite cardano-api:cardano-api-test` and `library cardano-api` are defined in the same package `cardano-api`, so `cabal` requires that the `gen` package exist in the same package as well.

Unfortunately, this means fixing `haskell.nix` and/or `cabal` is the only viable option.

**Comment by eyeinsky** [comment]
> Unfortunately, this means fixing `haskell.nix` and/or `cabal` is the only viable option.

Improving `haskell.nix` seems like a good thing!

**Comment by newhoggy** [comment]
@MangoIV , @eyeinsky I'm interested to know if this resolves the issue: https://github.com/input-output-hk/cardano-node/pull/4970

**Comment by MangoIV** [comment]
Afaict yes.

**Comment by newhoggy** [comment]
Can you point to where the library is used?  Is it for consumption via an `srp` entry in a `cabal.project` or something else?

**Comment by MangoIV** [comment]
I tried it with both srp and nix extra hackage. Neither do worth. Sublibs just don't work. At least for Haskell.nix devShells. See the attached issue. Thank you.

**Comment by Jimbo4350** [comment]
@MangoIV  Instead of making cardano-api/gen a top level library, will adding a `.cabal` file for the generators fix your issue? I'd rather not add another library to the `cardano-node` repo.

**Comment by MangoIV** [comment]
I will close this issue as I don't depend on this anymore. I still want to note that one probably wants to abstain from using public sublibs as they're not fully supported by cabal yet and haskell.nix cannot deal with them for that reason and stuff will break.
