### ISSUE TITLE
[BUG] - TxIdInMode type and constructor are not exported

### ISSUE THREAD

**Issue by jhbertra** [input-output-hk/cardano-node#4456]
**Internal*

**Other - Cardano API**

**Summary**
The type and constructor for `TxIdInMode` are not exported in any publically accessible module. As such, `LocalTxMonitorClient` and `queryTxMonitoringLocal` are unusable.

**Steps to reproduce**
1. Try to compile the following Haskell module with access to the `cardano-api` package:
   ```hs
   module Example where
   
   import Cardano.Api (TxIdInMode(TxIdInMode))
   ```

**Expected behavior**
Module compiles

**Actual behavior**
Module does not compile, but reports that `Cardano.Api` does not export `TxIdInMode`.

**System info (please complete the following information):**
- OS Name: N/A
- OS Version: N/A
- Node version: `cardano-node 1.35.3 - linux-x86_64 - ghc-8.10`
- CLI version: `cardano-cli 1.35.3 - linux-x86_64 - ghc-8.10`

**Additional context**
This is not the only occasion where I've encountered a problem like this in Cardano API. It would be a good idea to check in CI that the package exposes the complete closure of types and constructors needed to use the API. For example, a separate cabal project which proves via compilation that all exported functions can be called would be a way to do this.

**Comment by jonathangenlambda** [comment]
Can confirm this, stumbled across the same issue - `queryTxMonitoringLocal` with `LocalTxMonitoringQueryTx` is therefore unusable. Please fix asap, this is crucial functionality!

**Comment by jonathangenlambda** [comment]
I have created a fork and fixed this bug as well as adding a "QueryAllTxs" to the LocalTxMonitor. It is currently sitting at https://github.com/jonathangenlambda/cardano-node/tree/jonathan/fixlocaltxmonitor based on 1.35.3 but I have no idea to which branch I should submit this PR as I was not able to find any CONTRIBUTING.md / guidelines.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by jonathangenlambda** [comment]
Why is this closed? I have not submitted my PR, because there are simply no guidelines/rules to be found anywhere in the repo. Has this been fixed by IOHK?
