### ISSUE TITLE
Feature: tx-mempool CLI commands

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#4459]
## What - The user-facing feature being implemented
Expose Tx Mempool Monitoring Mini Protocol via CLI; There will be 3 new CLI commands available:
- `cardano-cli query tx-mempool info` - prints stats for the transaction mempool of the node
- `cardano-cli query tx-mempool next-tx` - returns the ID of the next transaction to be processed
- `cardano-cli query tx-mempool tx-exists <txid>` - tells you whether or not a transaction is in the mempool

## Why
- in order to give the CLI users the possibility to check the node mempool transactions 

## Personas - Who will this affect?

- [x] SPOs
- [x] Dapp Devs
- [x] Exchanges
- [x] CLI-based scripts owners

## Definition of done

- [ ] Acceptance Criteria + User Stories & DoD created and singed-off 
- [ ] Code & Test review
- [x] Builds successfully on CI
- [x] Includes documentation and/or examples for the functionality (+ usage and response examples)
- [x] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [x] Ticket number included in PR description
- [ ] The new functionality is covered by dev/unit/property tests
- [ ] Acceptance Criteria met
- [ ] Test engineer signs-off + system tests fully automated

## Sign-off Acceptance Criteria

- [x] Product Owner
- [ ] Dev Owner
- [x] Test Engineer Owner

# Related PR
- **FR** - https://github.com/input-output-hk/cardano-node/issues/3774
- https://github.com/input-output-hk/cardano-node/pull/4276

#### User Story 1
* As a CLI user (all Personas), I want to have the possibility to see stats for the transactions in the node's mempool - these stats should include: 

##### AC1.1
- When the local node is fully synced, the `cardano-cli query tx-mempool info` CLI command (both for relay and producer node types) returns the following stats for the transactions on the mempool:

    - The maximum capacity of the mempool
    - The summed byte size of all the transactions in the mempool
    - The number of transactions in the mempool
    - Slot number at which the mempool snapshot was taken

##### AC1.2
- When the local node is syncing (not fully synced), the `cardano-cli query tx-mempool info` CLI command should return: 

    - cardano-cli: Network.Socket.connect: <socket: >: does not exist (Connection refused)
   
##### AC1.3
- The `cardano-cli query tx-mempool info` CLI command offers an option, consistent with the existing CLI commands, to export the output in JSON format.

#### User Story 2
* As a CLI user (all Personas), I want to have the possibility to get the tx_id of the next transaction, from the mempool, that will be processed

##### AC2.1
- The `cardano-cli query tx-mempool next-tx` should return the txid of the next transaction from mempool that will be processed 

    - NextTxid: txId
    - Slot: Slot number at which the mempool snapshot was taken 

##### AC2.2
- The transaction with the `txid` returned by the `cardano-cli query tx-mempool next-tx` CLI command is processed before the other transactions in the mempool

##### AC2.3
- The  `cardano-cli query tx-mempool next-tx` CLI command offers an option, consistent with the existing CLI commands, to export the output in JSON format.

#### User Story 3
* As a CLI user (all Personas), I want to have the possibility to check if a specific transaction (based on txid) is, or is not, in the mempool

##### AC3.1
- The `cardano-cli query tx-mempool tx-exists <txid>` should return boolean (true/false) based on the existence of the transaction with the specifified `txid` in the mempool

    - Exists:  True or False
    - TxId: TxId
    - Slot: Slot number at which the mempool snapshot was taken 

##### AC3.2
- The  `cardano-cli query tx-mempool tx-exists <txid>` CLI command offers an option, consistent with the existing CLI commands, to export the output in JSON format.

##### AC3.3
-  The response returned by all 3 commands is instantaneous (less than 1 sec)

**Comment by CarlosLopezDeLara** [comment]
A.C.✅
