### ISSUE TITLE
tracing: `Forge.Stats.StartLeadershipCheck` not in autogenerated docs

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4461]
We have the following in the logs:

`{"at":"2022-09-21 16:25:00.0014Z","ns":"Forge.Stats.StartLeadershipCheck","data":{"blocksForgedNum":"3","kind":"ForgingStats","nodeCannotForgeNum":"0","nodeIsLeaderNum":"3","slotsMissed":"0"},"sev":"Info","thread":"33","host":"solaris"}`

..which mentions `Forge.Stats.StartLeadershipCheck` as the namespace entry.

However we don't have this entry in https://github.com/input-output-hk/cardano-node/blob/master/doc/new-tracing/tracers_doc_generated.md#forgestats

**Comment by jutaro** [comment]
I guess its already fixed, but the generated doc is not up to date, but I will check.
