### ISSUE TITLE
Feature: Rename TestEnableDevelopmentHardForkEras to TestEnableDevelopmentProtVer

### ISSUE THREAD

**Issue by LudvikGalois** [input-output-hk/cardano-node#4470]
## What

Rename TestEnableDevelopmentHardForkEras to TestEnableDevelopmentProtVer

## Why

The TestEnableDevelopmentHardForkEras flag is set when a node wants to enable support for the "new" protocol version
before it is actually released. It was decided that this is a bad name for the feature, so it's been renamed to something
hopefully more indicative about what it does.

## Personas - Who will this affect?

- [ ] SPO
- [ ] Dapp Devs
- [ ] Exchanges

## Definition of done

- [ ] Code review
- [x] Builds successfully on CI
- [ ] Includes documentation and/or examples for the functionality
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [x] Ticket number included in PR description
- [ ] The new functionality is covered by dev/unit/property tests
- [ ] Acceptance Criteria met
- [ ] Test Engineering Sign-off + E2E automated tests

## Sign-off

- [ ] Dev
- [ ] Test Engineering

# Related PR

1.  https://github.com/input-output-hk/cardano-node/pull/4341

**Comment by dorin100** [comment]
@CarlosLopezDeLara can you please add the AC?

**Comment by CarlosLopezDeLara** [comment]
> @CarlosLopezDeLara can you please add the AC?

Not a user-facing feature.
