### ISSUE TITLE
Feature: Allow transactions with no signatures

### ISSUE THREAD

**Issue by LudvikGalois** [input-output-hk/cardano-node#4471]
## What

Allow transactions with no signatures

## Why

It's possible to create a script which requires no signatures to claim, but it's wasn't possible to
submit a transaction which claims from a script address without supplying at least one signature.

## Personas - Who will this affect?

- [ ] SPO
- [x] Dapp Devs
- [ ] Exchanges

## Related issues

https://github.com/input-output-hk/cardano-node/issues/3835

## Acceptance Criteria

As a dapp developer I want 

* `cardano-cli transaction assemble` to be able to sign/witness transaction for txin simple script where "type": "atLeast", "required": 0 without needing any skey.

## Definition of done

- [x] Code review
- [x] Builds successfully on CI
- [x] Includes documentation and/or examples for the functionality
- [x] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [x] Ticket number included in PR description
- [ ] The new functionality is covered by dev/unit/property tests
- [x] Acceptance Criteria met
- [x] Test Engineering Sign-off + [E2E automated tests](https://github.com/input-output-hk/cardano-node-tests/blob/732ea5cd6589c10240019d8d71b9247ae70eff10/cardano_node_tests/tests/test_scripts.py#L603)

## Sign-off

- [ ] Dev
- [x] Test Engineering

# Related PR

1. https://github.com/input-output-hk/cardano-node/pull/4408

**Comment by dorin100** [comment]
@CarlosLopezDeLara can you please add the AC?
