### ISSUE TITLE
[BUG] - Orphaned block when previous block propagation exceeds 1s and produced in previous slot

### ISSUE THREAD

**Issue by johnnuy** [input-output-hk/cardano-node#4477]
**Internal/External**
External

**Area**
Block Production

**Summary**
Twice in the past couple of weeks I've had blocks orphaned because the block from the previous slot has been received by my node after my node has produced a block.

Most recent example:
Epoch 365, Slot in Epoch 109132. 

My node produced a block for slot 109132 with previous the previous hash "8d4b1b2bdc7a64c1bc593cb73cf2ba753d7bb65349c1119556d1e2f5c690af2e".  This was completed at 04:03:43.06 UTC.

At 04:03:43.25 UTC my node received the block that was produced at slot 109131 with hash "e2ab72b5328779331356ef369f1d0834f67657d57e4a26a646798199f803b8ef", and rather than keep my own block that was produced at 109132, it chose to accept the slowly propagated block that was produced at 109131 instead, which orphaned my block.

pooltool suggests the block from 109131 was propagated with a 1.06s delay... which coincides with my node receiving it after it has produced the previous block.  

**Steps to reproduce**
Do not know how to reproduce.

**Expected behavior**
Because there was approximately 0.75ms left in the current slot, I would expect the node t be capable of producing the block a second time, with a new previous block, and to be able to do that well within the time constraints of a full second, considering that it took only about 0.06 seconds for me to produce my own block, after receiving the new block, it could have easily produced a second block by 04:03:43.31 and started propagating the new block.  

OR 

I would expect my own node to prioritize blocks that i have produced, rather than penalize my node for the slow propagation of another block through the network.  

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 1.35.3
- CLI version  1.35.3

**Screenshots and attachments**
[orphaned block.txt](https://github.com/input-output-hk/cardano-node/files/9642030/orphaned.block.txt)

**Comment by njd42** [comment]
This is just normal emergent behaviour of the overall system - it is not a bug. 

What is occurring here is a (short lived) fork in the chain that occurs due to the propagation delays in a global distributed system.

**Comment by johnnuy** [comment]
I've seen this same thing happen with blocks that have taken upto 3 or 4 seconds to propagate through the network, and each time the consensus protocol has chosen the "oldest" block based on the slot it should have been produced (Assuming no height battles).  So what would prevent someone from delaying their system clock by 2 seconds such that they have additional time to receive previous blocks before producing their own block?  

For example if the block that was produced at slot 109132 was actually produced timewise 2 seconds later (due to a system block delay) then I would have received the block produced at 109131 and been able to build upon it.  In the scenario that there was another block produced at 109133 or 109134, then it appears that my block would be chosen anyways because it has the lower slot associated with it.

**Comment by johnnuy** [comment]
What makes a block worse?  when two blocks are produced at almost identical times (1 second apart) both built upon the same previous block, how is one deemed better than the other?

**Comment by njd42** [comment]
Their VRF values - that is used as the tie-breaker in this case not the slot time.

The chain length of each new chain extension, in this case, is the same - where one chain is longer than the other that would have been chosen.

**Comment by njd42** [comment]
The block forging code makes its decision at the start of the time-slot - it then "presents" it to itself  for adoption before it is forwarded. The adoption process is asynchronous  so the local block is considered for adoption in the context of any other blocks received. Note that these 'slot battles' can only occur less than 2.6% of the time - making code more complex (and also having to validate the design, create all the testing framework) needs to be considered in the context of this.

There is also the question of resource consumption attacks; performing re-work is a potentially dangerous thing to do, especially when your system is has the "real-time" progress properties that Cardano requires. We are concerned no to knowingly open up Cardano to such threats.

There _was_ a theoretical attack vector where a node could create lots of (valid) blocks which looked better than each other, potentially causing a lot of "busy work" to be done - this was the motivation to some of the recent (not shouted from the rooftop) changes in the ledger rules.
