### ISSUE TITLE
tx-generator: support tracing to cardano-tracer

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4492]
`tx-generator` has been converted to use the new tracing system.

Without configuring the new tracing system to connect to `cardano-tracer`, `tx-generator` is no longer capable writing logs to disc.

We need to extend `tx-generator` with a CLI option to connect to and submit tracer to `cardano-tracer`.

**Comment by deepfire** [comment]
https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Node/Tracing/API.hs#L94-L100 is one key bit.

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/4511

**Comment by mgmeier** [comment]
merged to master
