### ISSUE TITLE
[BUG] - cardano-node P2P - node crashed

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-node#4502]
Cardano-node latest version

Config:

```
  "EnableP2P": true,
  "TestEnableDevelopmentNetworkProtocols": true,
  "TargetNumberOfRootPeers": 150,
  "TargetNumberOfKnownPeers": 150,
  "TargetNumberOfEstablishedPeers": 120,
  "TargetNumberOfActivePeers": 60,
  "MaxConcurrencyDeadline":3,
```

Node crashed after some time with this message

```
[ns315724:cardano.node.PeerSelectionCounters:Info:209] [2022-10-04 04:06:40.91 UTC] PeerSelectionCounters {coldPeers = 58, warmPeers = 60, hotPeers = 60}
cn: A pick policy requested an attribute for peer address  which is outside of the set given to pick from
CallStack (from HasCallStack):
```

**Comment by Jimbo4350** [comment]
@cardanians is this still an issue?

**Comment by pascallapointe** [comment]
The bug still there on 1.35.5. I'm able to reproduce the node crash every 2-4h lapse with a certain topology configuration using 2 groups under local peers.
Did not experienced any crash using a more simple configuration.

```bash
cardano-node: A pick policy requested an attribute for peer address  which is outside of the set given to pick from
CallStack (from HasCallStack):
  error, called at src/Ouroboros/Network/PeerSelection/Governor/Types.hs:471:9 in ouroboros-network-0.1.0.1-a5985fbeb4dfc172191c055daca1b96db83053dad61c636a36de72ff5d4269fa:Ouroboros.Network.PeerSelection.Governor.TypesExit Status: 0
```

I'm currently trying to narrow down the the issue source with slight configuration change.
I'll provide more information once I'm done with test.

**Comment by coot** [comment]
Have you experienced this issue with a more recent node, e.g. `1.35.6` or `1.35.7`?

**Comment by pascallapointe** [comment]
No, I haven't experienced any issues recently.

I had a topology file that was pretty successful at reproducing the issue with 1.35.5, changing the preset of local peers set was enough to fix the problem, don't ask me why..!

I have a backup of it, so I just spun up a 1.35.7 node using that very same topology setting just to see if I can reproduce, will report back if I find something.
