### ISSUE TITLE
[FR] - Query a particular tx id for its status

### ISSUE THREAD

**Issue by bjing** [input-output-hk/cardano-node#4506]
**Internal/External**
*External*   otherwise.

**Area**
cardano-cli

**Describe the feature you'd like**
Being able to query a transaction status (pending, completed etc) through cardano-cli given a transaction id.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by CarlosLopezDeLara** [comment]
Have you tried this:

```
% cardano-cli transaction txid --tx-body-file tx.raw
ce40342ad65066af4a53825af82b46c95122400ddbccdfa170a49b3af583fa07

% cardano-cli transaction submit --testnet-magic 2 --tx-file tx.signed
Transaction successfully submitted.

% cardano-cli query utxo --tx-in ce40342ad65066af4a53825af82b46c95122400ddbccdfa170a49b3af583fa07#1 --testnet-magic 2 --out-file utxo.view | jq . utxo.view

{
  "ce40342ad65066af4a53825af82b46c95122400ddbccdfa170a49b3af583fa07#1": {
    "address": "addr_test1qqmz6kgthyv4c4pgu3k2egpfuzu5pyrcav6kjz95lxgt7g75jsksfxu29p622vqx2jhxvxg6jjtgqla3wwvyhjwlsjvstads72",
    "datum": null,
    "datumhash": null,
    "inlineDatum": null,
    "referenceScript": null,
    "value": {
      "lovelace": 3000000
    }
  }
}

```
Does this serve your purpose? 

You might also be interested in https://github.com/input-output-hk/cardano-node/pull/4276

**Comment by bjing** [comment]
Hi @CarlosLopezDeLara Thanks for your response! I didn't know that the tx id is actually the utxo hash. Also is the number after `#` always `1`?

All i wanted to do is after a tx has been submitted, I can monitor the state of the tx till it's finished so that I can carry out some specific actions. Looks like this will work.

**Comment by CarlosLopezDeLara** [comment]
The number is the Transaction index TxIx 
```

cardano-cli query utxo --tx-in ce40342ad65066af4a53825af82b46c95122400ddbccdfa170a49b3af583fa07#1 --testnet-magic 2

                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------
ce40342ad65066af4a53825af82b46c95122400ddbccdfa170a49b3af583fa07     1        3000000 lovelace + TxOutDatumNone

cardano-cli query utxo --tx-in ce40342ad65066af4a53825af82b46c95122400ddbccdfa170a49b3af583fa07#1 --testnet-magic 2 --out-file utxo.txix1 | jq . utxo.t
xix1
{
  "ce40342ad65066af4a53825af82b46c95122400ddbccdfa170a49b3af583fa07#1": {
    "address": "addr_test1qqmz6kgthyv4c4pgu3k2egpfuzu5pyrcav6kjz95lxgt7g75jsksfxu29p622vqx2jhxvxg6jjtgqla3wwvyhjwlsjvstads72",
    "datum": null,
    "datumhash": null,
    "inlineDatum": null,
    "referenceScript": null,
    "value": {
      "lovelace": 3000000
    }
  }
}
```

**Comment by bjing** [comment]
@CarlosLopezDeLara Looks like this is not a reliable way to check a particular transaction status right? I've seen Txix as 0, 1 and 2. How do I know what Txix to expect for a particular tx hash?

**Comment by bjing** [comment]
I've worked this out. Txix is used to number the outputs starting from 0 and it can go up to the number of outputs that you have.

Thanks for your help.
