### ISSUE TITLE
Add description of the p2p topology file 

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#4512]
Only the non p2p topology file is described [here](https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/configuring-a-node-using-yaml.md).  Both formats are described [here](https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/understanding-config-files.md) as well.

**Comment by bolt12** [comment]
This is done here: https://github.com/input-output-hk/cardano-node/pull/5399
