### ISSUE TITLE
Use the correct mainnet PBFT threshold

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-node#452]
The `configuration/configuration-mainnet.yaml` currently specifies:
```
PBftSignatureThreshold: 0.5
```
This is not the correct value for mainnet.

The right solution is not to specify it at all in the config file and use the default. The internal default should be `Nothing`, since the consensus initialisation takes `Maybe PBftSignatureThreshold` and fills in the properly calibrated value in the `Nothing` case.

**Comment by Jimbo4350** [comment]
Fixed in #472
