### ISSUE TITLE
[BUG] - Hydra: `error: cannot update flake input 'cardano-node/cardano-node-workbench/membench' in pure mode`

### ISSUE THREAD

**Issue by aciceri** [input-output-hk/cardano-node#4525]
**Internal/External**
*External*

**Area**
Nix

**Summary**
Hydra gives out this evaluation error when trying to evaluate a flake containing `cardano-node` as input.

```
hydra-eval-jobs returned exit code 1:
error: cannot update flake input 'cardano-node/cardano-node-workbench/membench' in pure mode
error: worker error: error: cannot update flake input 'cardano-node/cardano-node-workbench/membench' in pure mode
```
It looks like it tries to lock some inputs (but they should be all specified in the lockfile) but fails it Hydra works in pure mode.

Maybe this is due to its weird "recursive" inputs which also causes this warning using Nix from CLI:
```
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
``` 

Or maybe this is an error in Nix (or Hydra?) itself that can't manage `follows` as it should.

**Steps to reproduce**
Create a flake with `cardano-node` as input and add it to Hydra.

**Expected behavior**
It just works.

**System info (please complete the following information):**
- OS Name: NixOS
- OS Version 22.11
- Nix version: 2.9.1
- Hydra version: 0.1.20220820
- Node version: should be 1.35.3 (my flake input is `cardano-node/a0b000380a32155feb62d3bfd73513243c98a4f6`) 

**Additional context**
In case this was a bug in Hydra or Nix I think that IOG is using some workaround to make their stuff build on Hydra (or maybe IOG doesn't use Hydra? TBH I've no idea), maybe someone could share it here?
I tried adding several `following` to my inputs to be sure that they are locked but I had no luck.

**Comment by Kranzes** [comment]
I believe this comes from `github:input-output-hk/empty-flake` (which gets called many times) not having a flake.lock.

**Comment by aciceri** [comment]
I've just tried but it doesn't work.

I've added a lockfile to `empty-flake` ([here](https://github.com/mlabs-haskell/empty-flake/) if someone wants to try it) adding an input, running `nix flake lock` and then deleting the input (running `nix flake lock` without inputs doesn't create any lockfile). Then I've done this change to my flake
```
cardano-node.inputs.cardano-node-workbench.membench.url = "<emptyFlakeWithLockfile>";
```
but I got this error:
```
error: cannot find flake 'flake:cardano-node-workbench' in the flake registries

       … while updating the flake input 'cardano-node-recent/cardano-node-workbench'

       … while updating the flake input 'cardano-node-recent'

       … while updating the lock file of flake '<myFlake>'

```

So I've chose to fork `cardano-node` itself replacing `empty-flake` occurrences with my new empty flake with lockfile but I'm getting the same evaluation error by Hydra as before.

**Comment by marijanp** [comment]
Just to make sure I understood you correctly you've replaced all the occurences of `empty-flake` in the `cardano-node` flake, are you sure you've covered all transitive dependencies? And the error is the previous one?

I think someone responsible for this flake should join the discussion and hopefully explain why this `empty-flake` is needed in the first place....

**Comment by aciceri** [comment]
> ust to make sure I understood you correctly you've replaced all the occurences of empty-flake in the cardano-node flake, are you sure you've covered all transitive dependencies? And the error is the previous one?

I've not been able to cover all the transitive dependencies directly overriding inputs in the `flake.nix` since checking the `flake.lock` file I could see many `empty-flake` with `input-output-hs` as `owner`.
By the way I was getting same error.

So, now I've directly edited the lockfile replacing every occurrences there with my `empty-flake` which has a lockfile. Now `nix` CLI doesn't work anymore (it stucks indefinitely) and Hydra gives the same error as before.

I've also noticed that if I try to delete `cardano-node` lockfile and make `nix` (now I'm using my system version i.e. `2.11.0`) recreate it stucks again (not sure, I stop getting any output for minutes, but I can see that CPU is working).

> BTW: This error is triggered in hercules-CI too so it's not just hydra related. Seems like GHA has impurities
Maybe GHA impurities are due to [this line](https://github.com/input-output-hk/cardano-node/blob/3586f5bed4e392120158e476c51f9096627a63bc/.github/workflows/check-mainnet-config.yml#L29)?

> I think someone responsible for this flake should join the discussion and hopefully explain why this empty-flake is needed in the first place....
Not sure who to ping, maybe @jbgi since he has created `empty-flake`?

**Comment by aciceri** [comment]
Doing this seems to work:
```nix
empty-flake.url = "github:input-output-hk/empty-flake?rev=2040a05b67bf9a669ce17eca56beb14b4206a99a";
cardano-node-workbench = {
  url = "github:input-output-hk/cardano-node/ed9932c52aaa535b71f72a5b4cc0cecb3344a5a3";
  inputs.membench.follows = "empty-flake";
};
cardano-node = {
  url = "github:input-output-hk/cardano-node?ref=1.35.3";
  inputs.cardano-node-workbench.follows = "cardano-node-workbench";
  inputs.node-measured.follows = "cardano-node-workbench";
};
```

**Comment by marijanp** [comment]
@aciceri What are you doing there? using an older workbench-revision?

**Comment by disassembler** [comment]
I think this hack is what your looking for, but I thought this was fixed in 1.35.3 tag.

https://github.com/input-output-hk/cardano-world/blob/4890ca5aa358c83ecd1981ab0ec1fbb0f542f0b4/flake.nix#L18

**Comment by marijanp** [comment]
@disassembler I added that line and referred to `cardano-node` with tag `1.35.3-configs`.
This is the error I get when executing `nix flake lock --update-input cardano-node`:
```
warning: Git tree '/home/marijan/workspace/ardana/cardano-app-template' is dirty
warning: input 'cardano-node' has an override for a non-existent input 'membench'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
```

**Comment by marijanp** [comment]
@disassembler same issue for release `1.35.4`

**Comment by aciceri** [comment]
I confirm that this is still a problem and I add that I also get this error using Hercules CI.

**Comment by andreabedini** [comment]
Still a problem
```
❯ nix shell nixpkgs#hydra-unstable --command hydra-eval-jobs --flake github:input-output-hk/cardano-node/0c5d82b08160077cc415dcd2897bab2a62ccb5ee
warning: `--gc-roots-dir' not specified
error: cannot update flake input 'cardano-node-workbench/membench' in pure mode
error: worker error: error: cannot update flake input 'cardano-node-workbench/membench' in pure mode
```
