### ISSUE TITLE
Export more `cardano-api` generators

### ISSUE THREAD

**Issue by devfull** [input-output-hk/cardano-node#4529]
More generators should be exported, as some users may need them to test their application. For example, `plutus-apps` has some modules that reproduce the CardanoApi generators because they are not exported (e.g. [`plutus-ledger/test/Ledger/Tx/CardanoAPISpec.hs`](https://github.com/input-output-hk/plutus-apps/blob/5ff40dafcdb07483442093efb4eaa39d12f34880/plutus-ledger/test/Ledger/Tx/CardanoAPISpec.hs)).

```haskell
-- Copied from Gen.Cardano.Api.Typed, because it's not exported.
genAssetId :: Gen AssetId
genAssetId = Gen.choice
    [ AssetId <$> genPolicyId <*> genAssetName
    , return AdaAssetId
    ]
```

Here is a list of generators defined in [`cardano-api/gen/Gen/Cardano/Api/Typed.hs`](https://github.com/input-output-hk/cardano-node/blob/c657d5d7b026254986856845e98be62df0962474/cardano-api/gen/Gen/Cardano/Api/Typed.hs), with annotations regarding whether the function is exported and whether it is needed in `plutus-apps`.

| Exported | Plutus  | Name                                    |
| -------- | ------- | --------------------------------------- |
| Yes      | No      | `genAddressByron`                       |  
| No       | No      | `genAddressInEra`                       |
| Yes      | Yes     | `genAddressShelley`                     |
| No       | Yes     | `genAssetId`                            |
| Yes      | Yes     | `genAssetName`                          |
| Yes      | No      | `genByronKeyWitness`                    |
| Yes      | Yes     | `genCertificate`                        |
| Yes      | No      | `genCostModel`                          |
| No       | No      | `genEpochNo`                            |
| No       | No      | `genExecutionUnitPrices`                |
| No       | No      | `genExecutionUnits`                     |
| No       | No      | `genHashScriptData`                     |
| No       | No      | `genKESPeriod`                          |
| Yes      | No      | `genLovelace`                           |
| Yes      | No      | `genMaybePraosNonce`                    |
| No       | No      | `genNat`                                |
| No       | Yes     | `genNetworkId`                          |
| No       | Yes     | `genNetworkMagic`                       |
| Yes      | No      | `genOperationalCertificate`             |
| Yes      | No      | `genOperationalCertificateIssueCounter` |
| No       | No      | `genOperationalCertificateWithCounter`  |
| No       | Yes     | `genPaymentCredential`                  |
| No       | No      | `genPlutusLanguage`                     |
| Yes      | No      | `genPlutusScript`                       |
| No       | Yes     | `genPolicyId`                           |
| Yes      | No      | `genPraosNonce`                         |
| Yes      | Yes     | `genProtocolParameters`                 |
| Yes      | No      | `genProtocolParametersUpdate`           |
| No       | No      | `genQuantity`                           |
| Yes      | No      | `genRational`                           |
| No       | No      | `genRationalInt64`                      |
| Yes      | Yes     | `genReferenceScript`                    |
| Yes      | No      | `genScript`                             |
| Yes      | Yes     | `genScriptData`                         |
| Yes      | No      | `genScriptDataSupportedInAlonzoEra`     |
| Yes      | Yes     | `genScriptHash`                         |
| Yes      | No      | `genScriptInAnyLang`                    |
| Yes      | No      | `genScriptInEra`                        |
| No       | No      | `genScriptValidity`                     |
| No       | No      | `genSeed`                               |
| No       | No      | `genShelleyBootstrapWitness`            |
| No       | No      | `genShelleyHash`                        |
| Yes      | No      | `genShelleyKeyWitness`                  |
| Yes      | No      | `genShelleyWitness`                     |
| No       | No      | `genShelleyWitnessSigningKey`           |
| No       | No      | `genSignedQuantity`                     |
| Yes      | No      | `genSigningKey`                         |
| Yes      | No      | `genSimpleScript`                       |
| Yes      | No      | `genSlotNo`                             |
| Yes      | No      | `genStakeAddress`                       |
| No       | Yes     | `genStakeAddressReference`              |
| No       | Yes     | `genStakeCredential`                    |
| No       | No      | `genTtl`                                |
| Yes      | Yes     | `genTx`                                 |
| No       | No      | `genTxAuxScripts`                       |
| Yes      | Yes     | `genTxBody`                             |
| Yes      | No      | `genTxBodyContent`                      |
| No       | No      | `genTxCertificates`                     |
| No       | No      | `genTxFee`                              |
| Yes      | Yes     | `genTxId`                               |
| Yes      | Yes     | `genTxIn`                               |
| No       | No      | `genTxIndex`                            |
| No       | No      | `genTxInsCollateral`                    |
| No       | No      | `genTxInsReference`                     |
| No       | No      | `genTxMetadataInEra`                    |
| No       | No      | `genTxMintValue`                        |
| Yes      | Yes     | `genTxOutDatumHashTxContext`            |
| Yes      | No      | `genTxOutDatumHashUTxOContext`          |
| Yes      | Yes     | `genTxOutTxContext`                     |
| Yes      | No      | `genTxOutUTxOContext`                   |
| Yes      | Yes     | `genTxOutValue`                         |
| No       | No      | `genTxReturnCollateral`                 |
| No       | No      | `genTxScriptValidity`                   |
| No       | No      | `genTxTotalCollateral`                  |
| No       | No      | `genTxUpdateProposal`                   |
| No       | No      | `genTxValidityLowerBound`               |
| No       | No      | `genTxValidityRange`                    |
| No       | No      | `genTxValidityUpperBound`               |
| No       | No      | `genTxWithdrawals`                      |
| No       | No      | `genUnsignedQuantity`                   |
| Yes      | No      | `genUpdateProposal`                     |
| Yes      | Yes     | `genUTxO`                               |
| Yes      | No      | `genValue`                              |
| Yes      | Yes     | `genValueDefault`                       |
| Yes      | Yes     | `genValueForMinting`                    |
| Yes      | Yes     | `genValueForTxOut`                      |
| Yes      | No      | `genValueNestedBundle`                  |
| Yes      | No      | `genValueNestedRep`                     |
| Yes      | Yes     | `genVerificationKey`                    |
| Yes      | Yes     | `genVerificationKeyHash`                |
| No       | No      | `genWitnesses`                          |
| No       | No      | `genWitnessNetworkIdOrByronAddress`     |

At least those generators are not exported but needed by Plutus.

| Name                       |
| -------------------------- |
| `genAssetId`               |
| `genNetworkId`             |
| `genNetworkMagic`          |
| `genPaymentCredential`     |
| `genPolicyId`              |
| `genStakeAddressReference` |
| `genStakeCredential`       |

A suggestion would be to simply export them all.

**Comment by MarcFontaine** [comment]
As suggested, https://github.com/input-output-hk/cardano-node/pull/4534 adds all `cardano-api` generators to the export list.
Note however, that there are different generator functions in the code base,
which have the same name but incompatible types (for example `genPaymentCredential`).
