### ISSUE TITLE
Implement a single `testnet` function in `cardano-testnet`

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#4539]
Currently we have four `testnet` functions in `cardano-testnet`. We should have a single `testnet` function defined as follows:

`testnet ::  TestnetOptions era -> H.Conf -> Integration TestnetRuntime`

Where `TestNetOptions era` is defined as follows:
```
data TestnetOptions 
  =  ShelleyOnlyTestnetOptions ShelleyTestnetOptions  
  |  BabbageOnlyTestnetOptions BabbageTestnetOptions   
  |  CardanoTestnetOptions CardanoTestnetOptions
```
We can convert the current multiple definitions of `TestnetOptions` as is to the relevant `($era)TestnetOptions` via renaming

For simplicity we will not include a Byron era data constructor because it is unlikely users will want to spin up a Byron testnet

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/4544
