### ISSUE TITLE
[FR] - Export TxIns type synonym

### ISSUE THREAD

**Issue by phadej** [input-output-hk/cardano-node#4564]
Reopening #3732

The `TxIns` synonym is still not re-exported (not in 1.35.3)

As one can see from haddocks: `TxIns` is not a link, so one have to check the source to figure out what it is.

![Screenshot from 2022-10-27 12-39-44](https://user-images.githubusercontent.com/51087/198250269-72d18db3-c367-43af-b7ad-62aa44f47150.png)

(FWIW, only project members can reopen issues, I - the original reporter - cannot).

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/4565

**Comment by MarcFontaine** [comment]
done in https://github.com/input-output-hk/cardano-node/pull/4565
