### ISSUE TITLE
Document the P2P parameters

### ISSUE THREAD

**Issue by weebl2000** [input-output-hk/cardano-node#4573]
## What

Document the workings of the P2P parameters in the configuration

## Why

When running cardano-node in p2p mode there are four parameters that influence behavior:

TargetNumberOfRootPeers, TargetNumberOfKnownPeers, TargetNumberOfEstablishedPeers, TargetNumberOfActivePeers

I have been running P2P on both testnet and mainnet and I think I have a general idea of what the parameters indicate. However, I'm not entirely sure on the behavior. I think it would be a good idea if we have an explanation of the workings of these parameters in the docs/ folder.

If someone is willing to elaborate on the exact behavior I am willing to write a bit of text and createa a PR for adding this information to the docs. The most mysterious part to me is the term "Root Peer": what is a root peer? What does the target amount indicate? What happens to inbound connections if the number of root peers has been reached, stuff like that.

I'm sorry if this documentation is already out there, I have been searching for it but have not found an explanation that clears it all up for me.

## Personas - Who will this affect?

- [ x ] SPO
- [ no ] Dapp Devs
- [ maybe ] Exchanges

## Acceptance Criteria

As an operator of cardano-node I would like to see a short and concise definition of the workings of the above mentioned parameters.

## Definition of done

- [ ] Code review
- [ ] Builds successfully on CI
- [ ] Includes documentation and/or examples for the functionality
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number included in PR description
- [ ] The new functionality is covered by dev/unit/property tests
- [ ] Acceptance Criteria met
- [ ] Test Engineering Sign-off + E2E automated tests

## Sign-off

- [ ] Dev
- [ ] Test Engineering

# Related PR

1.  PR # here

**Comment by coot** [comment]
This was explained in `cardano-node-1.35.6` [release notes](https://github.com/input-output-hk/cardano-node/releases/tag/1.35.6), but we should document this somewhere in the `docs` or a create a wiki page for it.
