### ISSUE TITLE
[FR] - Export `RawBytesHexError` in `Cardano.Api.SerialiseRaw`

### ISSUE THREAD

**Issue by TotallyNotChase** [input-output-hk/cardano-node#4579]
**Internal/External**
*External*.

**Area**
*Other*.

**Describe the feature you'd like**
Export `Cardano.Api.SerialiseRaw.RawBytesHexError` because it is used by `deserialiseFromRawBytesHex`, which is part of the public API.

**Describe alternatives you've considered**
Having to stringify the error and use that instead.

**Additional context / screenshots**
None.

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/4599

**Comment by MarcFontaine** [comment]
The original code has a `TODO` which suggests that `RawBytesHexError` should contain
information about the expected type.
The `TODO` sound reasonable but I found no easy way to do that. (No `Show (AsType a)`).
The PR just exports `RawBytesHexError` as.
