### ISSUE TITLE
[FR] - Remove use of Haskell multi-line string literals

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#4585]
**Internal/External**
*Internal*

**Area**
Refactoring

**Describe the feature you'd like**
We sometimes use multi-line string literals in Haskell.  This can play badly with other Haskell language features.  We should avoid them and use string concatenation instead.

**Describe alternatives you've considered**
N/A

**Additional context / screenshots**
N/A

**Comment by CarlosLopezDeLara** [comment]
We should add this to  https://github.com/input-output-hk/cardano-node/blob/master/STYLE.md

**Comment by Jimbo4350** [comment]
bump

**Comment by newhoggy** [comment]
bump
