### ISSUE TITLE
[BUG] - misleading error message for missing `--fee` or `--ttl` arguments

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#4591]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
When trying to build a transaction without specifying fee (using `--fee` argument), the error message used to contain "fee must be specified".
Now, after merging https://github.com/input-output-hk/cardano-node/pull/4516/, the error message is `Transaction _ fee not supported in Babbage`, which doesn't make sense in this context.

```
$ cardano-cli transaction build-raw --invalid-hereafter 2033 --out-file 221101_122717084_qskb_tx.body --tx-in "c6eef2089120ed25b6b86e239a43a914e1c4f66efa1d44c688545c2ad89aef6e#0" --tx-out "addr_test1qpzluvlfcmauftc93zc3e309qwkx8zwx8gfnnr54f0ydyav9ha685w7u3ssnlpehwkz0sz7rlx8r2v7vq80zat5aatzq6nkr8l+999821387"

Command failed: transaction build-raw  Error: Transaction _ fee not supported in Babbage
```

EDIT:
Similar situation with missing `--ttl` (`--invalid-hereafter`) for Shelley-era transactions:

```
$ cardano-cli transaction build-raw --fee 178613 --out-file 221101_125508477_ibeb_tx.body --tx-in "ffdf0ecac69a6a50f1730272b832b62650db08eed4fb85b93ce9e9fce70061fc#0" --tx-out "addr_test1qq3x3ezmxvg6swp4na4w5gvnm7hfrtppuyxcrd3lrcdt5ukph6j2qr546cy2q7zlwcw227tmcgup99y7l7g7fygdtensw3tn69+999821387" --shelley-era

Command failed: transaction build-raw  Error: Transaction validity upper bound not supported in Shelley
```

**Expected behavior**
A clear message that fee is missing is printed out.
A clear message that `--ttl` (`--invalid-hereafter`) is missing is printed out.

**System info:**
- OS Name: Fedora 36
- Node version: 0e11afc07f7c5939d291d56e6bd1abd62439ad63
- CLI version: 0e11afc07f7c5939d291d56e6bd1abd62439ad63

**Comment by Jimbo4350** [comment]
@mkoura bump
