### ISSUE TITLE
Remove the double hop of our libsodium fork

### ISSUE THREAD

**Issue by vfrsilva** [input-output-hk/cardano-node#4594]
## What
Cardano uses a fork of libsodium for the implementation of Verifiable Random Function (VRF). However, what we use is a fork of Algorand's fork (i.e. a fork of a fork). Algorand have not been updating their fork, meaning that we are way back from current version of libsodium. The goal of this task is to remove this double hop (or double fork) from our dependencies, and directly fork the libsodium repo. 

## Why
Security. It is harder to maintain than a single fork, and we can see that from how far behind we are from the current upstream branch.

## Functional requirements
All our codebase that uses libsodium must use the updated fork. The old fork must be deleted. 
We will do this in two steps. 
1. Remove the fork of the fork, and have our code directly point to upstream libsodium
2. Update our fork to use the latest stable version of libsodium

## Risks
Latest stable version of upstream libsodium causes compilation problems (we had that in the past with naming issues with cryptonite).

## External dependencies
For 1., we just need Charles Morgan to help with the renaming of the library, and find a moment where the waters are calm. For 2., we need to update the tag that libsodium points to.

## Acceptance Criteria
The new repo contains the same commits as the old one (wrt to the VRF changes) but with the latest version of stable from upstream libsodium

## Definition of Done
The repo with the fork of the fork is deleted

## Working Assumptions
Hard fork not required

**Comment by iquerejeta** [comment]
Libsodium [fork](https://github.com/input-output-hk/libsodium) points directly to upstream libsodium.
