### ISSUE TITLE
Selectively expose modules from cardano-testnet

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#4602]
We currently expose all the modules in the cardano-testnet library. We should expose a single module to make it more obvious to users how this library should be used. I propose the following:

1. Intoduce a top level directory called `Cardano` (similarly to what is done in `cardano-cli`) i.e `cardano-testnet/src/Cardano/{Parsers,Testnet,...}`
2. Expose only `Cardano.Testnet`
3. Propagate the changes and expose whatever we need via `Cardano.Testnet` only

I.e we want this
```
exposed-modules: Cardano.Testnet
other-modules: ...
```

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/4636
