### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/cardano-node#4603]
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:
-Include the Standard Code of Conduct
-Identify the Core Maintainers

**Comment by Jimbo4350** [comment]
This is also not a bug

**Comment by Jimbo4350** [comment]
Closing this until I get a clarification from @ThatGuyLLC

**Comment by coot** [comment]
I'd suggest that maintainers should be included in `*.cabal` files, we ought to write this in the handbook.
