### ISSUE TITLE
Cardano node sync suddenly stopped at 97.79 %

### ISSUE THREAD

**Issue by shanhashcah** [input-output-hk/cardano-node#4604]
My cardano node was 100% synced and it is running in production environment. But suddenly I am seeing that my cardano node block get backed and sync percent is 97.78%. In log I am getting below error

[ip-30-0-:cardano.node.DnsSubscription:Error:9719] [2022-11-03 15:48:30.76 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 3.130.47.105:3001 MuxError MuxBearerClosed "<socket: 38> closed when reading data, waiting on next header True"
[ip-30-0-:cardano.node.ErrorPolicy:Warning:4967] [2022-11-03 15:48:30.76 UTC] IP 3.130.47.105:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 38> closed when reading data, waiting on next header True"))) 20s 20s
[ip-30-0-:cardano.node.DnsSubscription:Error:9716] [2022-11-03 15:48:30.97 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 54.250.21.52:3001 MuxError MuxBearerClosed "<socket: 35> closed when reading data, waiting on next header True"
[ip-30-0-:cardano.node.ErrorPolicy:Warning:4967] [2022-11-03 15:48:30.97 UTC] IP 54.250.21.52:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 35> closed when reading data, waiting on next header True"))) 20s 20s

Thanks

Pls help. As my node is running in production.

**Comment by Jimbo4350** [comment]
Please reopen this in https://github.com/input-output-hk/ouroboros-network
