### ISSUE TITLE
API Enhancements

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4611]
# What

Enhancements to the existing cardano-api so that it is more usefull for external users (CLI and dapp developers)

- [ ] https://github.com/input-output-hk/cardano-node/issues/4043
- [x] https://github.com/input-output-hk/cardano-node/issues/3725
- [x] https://github.com/input-output-hk/cardano-node/issues/4529
- [ ] Continued refactoring of cardano-api and cardano-cli, with the particular focus on extracting re-usable components of cardano-cli and moving them to cardano-api. This is harder to define but will manifest in stuff moving from cardano-cli to cardano-api

**Comment by Jimbo4350** [comment]
This is too generic. Let's wait till the google doc is consolidated and we can get together with Konstantinos to create a comprehensive issue. I am trying to prevent another proliferation of issues.
