### ISSUE TITLE
Difference of this repo and "cardano-haskell" repo

### ISSUE THREAD

**Issue by lazaridiscom** [input-output-hk/cardano-node#463]
It looks like this newly introduced repo does the same:

https://github.com/input-output-hk/cardano-haskell

What is this about?

**Comment by karknu** [comment]
cardano-haskell is intended to make it easier for developers to keep `cardano-node`, `ouroboros-network`, `iohk-monitoring-framework ` and other repositories which are needed for building `cardano-node` in sync.

**Comment by mrBliss** [comment]
I think the README in that repo explains it nicely: https://github.com/input-output-hk/cardano-haskell#workflow-for-building-the-cardano-haskell-node-and-related-components

**Comment by lazaridiscom** [comment]
Why do you close?

I still don't understand.

cardano-haskell is essentially cardano-node-dev-tools?
