### ISSUE TITLE
Presenting Values Indicating Hard Drive Requirements for Local Copies of the Cardano Blockchain Ledger

### ISSUE THREAD

**Issue by paradoxicalsphere** [input-output-hk/cardano-node#4637]
The current presentation of statistics related to space required to store local copies of the Cardano blockchain may be confusing. Presumably, the values currently are presented for new stake pool operators who have no existing local copies of the Cardano blockchain, yet. However, most SPOs upgrade. Therefore, data presentations similar to the following may be more useful for existing SPOs:

`120GB of free storage`

Current Ledger Size: 90 GB
Minimum Total Space Currently Recommended to Allocate for the Ledger: 120 GB
Minimum Space Currently Recommended to Allocate in Addition to the Current Ledger Size: 30 GB

`(200GB recommended for future growth)`

Current Ledger Size: 90 GB
Recommended Space to Allocate for Future Growth, in Addition to the Current Ledger Size: 110 GB
Total Space Currently Recommended to Allocate for Future Growth of the Cardano Blockchain Ledger: 200 GB

**Comment by disassembler** [comment]
These numbers would get out of date rather quickly. Also, this terminology is not correct, The current ledger size is only 3.9 GB. Most of the 90 is immutable block storage. With these numbers, we're more or less fudging what the current is + a percentage to give a general idea of how much disk storage the chain requires. What we could do is change the wording from "free storage" to something like chain state. e.g.:

Required disk for chain state: 120GB (200GB recommended for future growth)

**Comment by kevinhammond** [comment]
The recommendations are minimum requirements

**Comment by paradoxicalsphere** [comment]
Hi Samuel,

 

That makes sense.

 

All the best,

 

Oliver
