### ISSUE TITLE
Clocks on Air-gapped, Offline Computers

### ISSUE THREAD

**Issue by paradoxicalsphere** [input-output-hk/cardano-node#4645]
Do potentially inaccurate clocks--that is, clocks that do not synchronize with an Internet time server--on air-gapped, offline computers used to sign transactions that are eventually submitted to the network create any risks (security or otherwise) to the Cardano mainnet network?

**Comment by JaredCorduan** [comment]
@paradoxicalsphere if you ask on https://cardano.stackexchange.com I'll answer it :)

**Comment by JaredCorduan** [comment]
Someone beat me to it, but I agree with the answer (from [Christian Schmitz](https://cardano.stackexchange.com/users/7460/christian-schmitz)).

**Comment by ltouro** [comment]
> Someone beat me to it, but I agree with the answer (from [Christian Schmitz](https://cardano.stackexchange.com/users/7460/christian-schmitz)).

Just for future reference, the answer is here: https://cardano.stackexchange.com/questions/9460/clocks-on-air-gapped-offline-computers/9461#9461

**Comment by paradoxicalsphere** [comment]
Thanks for following up, Jared. I will remember your name as someone technical in the Cardano community who is patient and able to foster a learning environment for everyone.

 

I am currently in the process of working on a draft Cardano Improvement Proposal (https://cips.cardano.org/). Maybe you are interested https://github.com/cardano-foundation/CIPs/issues/376

 

Sincerely,

 

Oliver
