### ISSUE TITLE
Provide a (repo) Description, URL and README

### ISSUE THREAD

**Issue by ghost** [input-output-hk/cardano-node#465]
This repositories "Description" field is empty, as is the "URL" field. The README tells not much.

## Expected

* A concise description
* a URL pointing to the relevant documentation
* A README which describes the usual (what is this, how to build, how to setup dev-env etc.)

### cardano-haskell

relate issue: https://github.com/input-output-hk/cardano-node/issues/463

* document how this repo relates to https://github.com/input-output-hk/cardano-haskell
* ideally: include the cardano-haskell functionality right into this repo
* alternatively: rename "cardano-haskell" to something more descriptive (e.g. "**cardano-node-dev-env**")

**Comment by kevinhammond** [comment]
Can you take a look at this when you get a chance, please, Jared

**Comment by JaredCorduan** [comment]
These are all present now.
