### ISSUE TITLE
Decide what to do with `Cardano.CLI.Run.Friendly`

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/cardano-node#4657]
`Cardano.CLI.Run.Friendly` contains the implementation of the YAML encoding that is used in
`cardano-cli transaction view`.
Basically it implments an `toJSON` function that bypasses the instances from `cardano-api`
and is (could be) inconsistent with the `cardano-api` instances.

**Comment by Jimbo4350** [comment]
@MarcFontaine Tickets like these get stale and never resolved. Let's talk on slack and come up with a clear path forward and re-open a ticket with a decision.
