### ISSUE TITLE
[BUG] - Different outputs ordering before and after balancing transaction.

### ISSUE THREAD

**Issue by maian99** [input-output-hk/cardano-node#4658]
**Internal/External**
*External*

**Area**
*Plutus Related to Plutus Scripts*

**Summary**
Related to this issue: https://github.com/input-output-hk/cardano-node/issues/3725 change is appended to transaction outputs after balancing the transaction but validation will fail while balancing because change is still prepended to the outputs.

**Additional context**
This bug affects to Plutus validator which depends on output ordering.

**Comment by Jimbo4350** [comment]
@maian99 please update the ticket with how you are constructing the tx (_exactly_) and the validation failure

**Comment by maian99** [comment]
https://github.com/input-output-hk/cardano-node/blob/15556f3cd4489c34cd117d018fb832f3a2f68639/cardano-api/src/Cardano/Api/Fees.hs#L937-L952
`txbody0` is built by prepending the change output to `txOuts`, and then `exUnitsMap` calculates the execution units for of `txbody0`.
https://github.com/input-output-hk/cardano-node/blob/15556f3cd4489c34cd117d018fb832f3a2f68639/cardano-api/src/Cardano/Api/Fees.hs#L1132-L1138
However, when getting the final tx body content, the change output is appended.
What we want to do is to assert the format of the first output (e.g, address, datum and value must match the expected). If change output is always appended, it’s possible to do so. If change output is prepended like before, it’s also possible by switching to assert the second output, assuming that the first output is always reserved for change output. When both prepend and append are used, neither way works.

**Comment by Jimbo4350** [comment]
I don't understand `txbody0` is an intermediate tx body, why is this relevant? The on disk txbody should have the change output appended to the tx outs.

**Comment by infrmtcs** [comment]
Maybe we're wrong here, that we're understanding that this `exUnitMap` is computed by evaluating the scripts on `txbody0`.
https://github.com/input-output-hk/cardano-node/blob/15556f3cd4489c34cd117d018fb832f3a2f68639/cardano-api/src/Cardano/Api/Fees.hs#L946-L952
So if the script assert the first output format, it means this phase fails because the prepended change output doesn't match expectation.
