### ISSUE TITLE
[BUG] - Executable links from doc are broken

### ISSUE THREAD

**Issue by pgrange** [input-output-hk/cardano-node#4688]
**Area**
*Other*

**Summary**

Looking at the cardano-node binary for Linux, the [README](https://github.com/input-output-hk/cardano-node/blob/master/README.rst) points to the [release notes](https://github.com/input-output-hk/cardano-node/releases) to find them.

Then, [release note for 1.35.4](https://github.com/input-output-hk/cardano-node/releases/tag/1.35.4) contains broken links to download the binaries:

<img width="223" alt="Capture d’écran 2022-12-02 à 13 57 40" src="https://user-images.githubusercontent.com/378506/205298119-c2a305b2-9001-48b2-9aa2-08a886cab378.png">

For instance the Linux link from the release not is broken: https://hydra.iohk.io/build/21343721

As a matter of fact, https://hydra.iohk.io seems to be down.

**Steps to reproduce**

1. Go to [release note for 1.35.4](https://github.com/input-output-hk/cardano-node/releases/tag/1.35.4)
2. Look for Downloads/Hydra binaries/linux
3. click on the link to download the linux binary

**Expected behavior**

I should be able to download the Linux binary.

**Comment by rphair** [comment]
The problem above was reported on the Cardano Developer Portal as well, where we will have a problem on our heavily used [Installing the Cardano Node](https://developers.cardano.org/docs/get-started/installing-cardano-node/) page every time the link to the binary package changes... unless we also have a **link which redirects to the latest current version**.

For instance, the current "Static binaries > Linux" link on @disassembler's latest node release page is:
> `https://update-cardano-mainnet.iohk.io/cardano-node-releases/cardano-node-1.35.4-linux.tar.gz`

... so could we (at the Developer Portal, and the community in general) please have a URI that redirects to the latest release from e.g.:
> `https://update-cardano-mainnet.iohk.io/cardano-node-releases/latest`

... so we don't have to update our documentation manually (after a period of being out-of-date, until somebody reports it as in https://github.com/cardano-foundation/developer-portal/issues/871) every time a new `cardano-node` is released?

**Comment by rdlrt** [comment]
This request was also raised in #4631 alongwith artifact content changes
