### ISSUE TITLE
[BUG] - Unable to pull hydra binaries

### ISSUE THREAD

**Issue by AdamMachera** [input-output-hk/cardano-node#4689]
**Internal/External**
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
I'm unable to pull hydra linux binaries that you provided link to in release docs
https://github.com/input-output-hk/cardano-node/releases
I'm trying to pull from:
https://hydra.iohk.io/build/17428084

I tried asking on IOHK discord but no one replies.
I cannot find any page with information if there is outage.

**Comment by rdlrt** [comment]
(From @disassembler )
hydra.iohk.io is currently defunct, the github release notes for 1.35.4 have been updated to include new download links

**Comment by dorin100** [comment]
duplicate on https://github.com/input-output-hk/cardano-node/issues/4689
