### ISSUE TITLE
[BUG] - link to download the MacOS executable goes to linux executable

### ISSUE THREAD

**Issue by jwbaumann** [input-output-hk/cardano-node#4706]
**External**
**Other**

**Summary**
The link to download the Mac executable instead links to the linux executable.

**Steps to reproduce**
1. Go to https://github.com/input-output-hk/cardano-node/releases
2. Click on 'Mac' under static binaries
3. The linux executable downloads instead of the MacOS version
4. The MacOS version IS actually present at [https://update-cardano-mainnet.iohk.io/cardano-node-releases/cardano-node-1.35.4-macos.tar.gz](https://update-cardano-mainnet.iohk.io/cardano-node-releases/cardano-node-1.35.4-macos.tar.gz)

**Expected behavior**
The link should go to and download the MacOS executable.

**System info**
- OS Name: [e.g. MacOS]
- OS Version [e.g. any] (not an OS version issue)
- Node version  cardano-node 1.35.4 - darwin-x86_64 - ghc-8.10
git rev ebc7be471b30e5931b35f9bbc236d21c375b91bb
- CLI version   cardano-cli 1.35.4 - darwin-x86_64 - ghc-8.10
git rev ebc7be471b30e5931b35f9bbc236d21c375b91bb

**Screenshots and attachments**
None. The problem is almost self explanatory. 

**Additional context**
I'm building an Applescript wrapper for the cardano-cli and am mere days away from a one-click full install script.

**Comment by disassembler** [comment]
fixed
