### ISSUE TITLE
[BUG] - Problem with cardano-cli genesis create-cardano --gen-utxo-keys

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4725]
**Internal/External**
*Internal*   

**Area**
cardano-cli 

**Summary**
When running `cardano-cli genesis create-cardano` the option `--gen-utxo-keys` has no effect at all.  

It's supposed to default to zero, however  it always creates one utxo key with the amount in `--supply`
```
  --gen-utxo-keys INT      The number of UTxO keys to make [default is 0].
```

Also, using `--gen-utxo-keys`  with N > 1 does not change anything. Only one key is produced. 

**Steps to reproduce**

1. Get template files from cardano-world
2. Run 

```bash
cardano-cli genesis create-cardano \
--genesis-dir ./ \
--gen-genesis-keys 3 \
--gen-utxo-keys 3 \
--start-time $(date -u -d "now + 2 minutes" +%FT%Tz) \
--supply 30000000000000000 \
--security-param 45 \
--slot-length 100 \
--slot-coefficient 5/100 \
--testnet-magic 42 \
--byron-template template/byron.json \
--shelley-template template/shelley.json \
--alonzo-template template/alonzo.json \
--node-config-template template/config.json
```
3. The folder utxo-keys will contain only 1 set of utxo keys:
```
utxo-keys/
├── byron.000.key
├── shelley.000.skey
└── shelley.000.vkey

0 directories, 3 files
```

**Expected behavior**
It should either be explicit about numUtxoKeys being hardcoded to 1 or generate as many keys as the user sets in `--gen-utxo-keys` 

**System info (please complete the following information):**
```
$ cardano-node --version
cardano-node 1.35.4 - linux-x86_64 - ghc-8.10
git rev ebc7be471b30e5931b35f9bbc236d21c375b91bb
$ cardano-cli --version
cardano-cli 1.35.4 - linux-x86_64 - ghc-8.10
git rev ebc7be471b30e5931b35f9bbc236d21c375b91bb
```

**Comment by MarcFontaine** [comment]
The parameter is ignored in the actual implementation.
There is also a LOC where `1` is hardcode. It looks like this is easy to fix,
but could not find the right template files...
Where exactly did you find the template files ?

**Comment by CarlosLopezDeLara** [comment]
@MarcFontaine I use template files from devops https://github.com/input-output-hk/cardano-world/tree/master/docs/environments/testnet

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/pull/4761

**Comment by CarlosLopezDeLara** [comment]
Sorry I meant https://github.com/input-output-hk/cardano-world/tree/master/nix/cardano/environments/testnet-template
