### ISSUE TITLE
[FEATURE] -  extend `query stake-pool` to query for multiple pools

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#4732]
## What
Add the ability to query for multiple stake pools, or all stake pools in the `query stake-pool` command.  Previously it was only possible to query for one specific stake pool:

```bash
$ cardano-cli query stake-snapshot --cardano-mode --mainnet --stake-pool-id fc79a939d5986c6565fc5e21bb5dd292261ac5da564c30385b3bb8d4
{
    "activeStakeGo": 24453012636354912,
    "activeStakeMark": 24525857119151547,
    "activeStakeSet": 24463445965412728,
    "poolStakeGo": 8595693051,
    "poolStakeMark": 8595693051,
    "poolStakeSet": 8595693051
 }
```

The change introduces a `pools` object to accomodate more than one stake pool in the result like this and thus is a breaking change:

```bash
$ cardano-cli query stake-snapshot --cardano-mode --mainnet --stake-pool-id fc79a939d5986c6565fc5e21bb5dd292261ac5da564c30385b3bb8d4
{
    "activeStakeGo": 24453012636354912,
    "activeStakeMark": 24525857119151547,
    "activeStakeSet": 24463445965412728,
    "pools": {
        "fc79a939d5986c6565fc5e21bb5dd292261ac5da564c30385b3bb8d4": {
            "poolStakeGo": 8595693051,
            "poolStakeMark": 8595693051,
            "poolStakeSet": 8595693051
        }
    }
}
```

Then querying for multiple stack pools can be done by adding more `--stake-pool-id` switches, for example:

```bash
$ cardano-cli query stake-snapshot --cardano-mode --mainnet --stake-pool-id fc79a939d5986c6565fc5e21bb5dd292261ac5da564c30385b3bb8d4 --stake-pool-id 0dedea6dd97bfd6b0d3ddf8e42375266ade6ec6a9c1aceb8efeecdab
{
    "activeStakeGo": 24453012636354912,
    "activeStakeMark": 24525857119151547,
    "activeStakeSet": 24463445965412728,
    "pools": {
        "0dedea6dd97bfd6b0d3ddf8e42375266ade6ec6a9c1aceb8efeecdab": {
            "poolStakeGo": 547234244,
            "poolStakeMark": 547234244,
            "poolStakeSet": 547234244
        },
        "fc79a939d5986c6565fc5e21bb5dd292261ac5da564c30385b3bb8d4": {
            "poolStakeGo": 8595693051,
            "poolStakeMark": 8595693051,
            "poolStakeSet": 8595693051
        }
    }
}
```

It will also be possible to query for *all* stake pools by omitting `--stake-pool-id` altogether:

```bash
$ cardano-cli query stake-snapshot --cardano-mode --mainnet
{
    "activeStakeGo": 24453012636354912,
    "activeStakeMark": 24525857119151547,
    "activeStakeSet": 24463445965412728,
    "pools": {
        "0dedea6dd97bfd6b0d3ddf8e42375266ade6ec6a9c1aceb8efeecdab": {
            "poolStakeGo": 547234244,
            "poolStakeMark": 547234244,
            "poolStakeSet": 547234244
        },
        ... ... ...
        "fc79a939d5986c6565fc5e21bb5dd292261ac5da564c30385b3bb8d4": {
            "poolStakeGo": 8595693051,
            "poolStakeMark": 8595693051,
            "poolStakeSet": 8595693051
        }
    }
}
```

## Why
There is overhead in making each call for this sort of query so it would be useful for the user to be able to query for each of the stake pools they are interested in with a single query.

## Personas
This will affect

- [x] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [ ] ADA holders 

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

# Related PRs

1.  PR # here

## Acceptance Criteria

Acceptance Criteria & User Stories define here (or in a separate file (linked here) for a big feature)

Example - https://github.com/input-output-hk/cardano-node/issues/4453

**Comment by dorin100** [comment]
> $ cardano-cli query stake-snapshot --cardano-mode --mainnet --stake-pool-id 

Is the `--cardano-mode` parameter mandatory?

**Comment by dorin100** [comment]
The addition of the `pool` objects breaks the backward compatibility, right? If yes, we need to highlight this in the Feature file (here).

**Comment by dorin100** [comment]
Do we have any performance numbers for this CLI command (before and after this change)? Like how much time does it takes for the command to be executer before this change and after the change (for 1, 2, all pools on Mainnet)? Same for the RAM usage.

**Comment by dorin100** [comment]
@CarlosLopezDeLara can you please help us with defining the Acceptance Criteria for this feature (similar with https://github.com/input-output-hk/cardano-node/issues/4453)?

**Comment by dorin100** [comment]
fyi @saratomaz , @mkoura

**Comment by dorin100** [comment]
duplicate on https://github.com/input-output-hk/cardano-node/issues/4570
