### ISSUE TITLE
Migration of some core node cause chain quality to drop

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-node#478]
On shelley stagin cluster, migrating 2 core nodes to `cardano-node` resulted in chain quality dropping to 71% for the remaining `cardano-sl` nodes.
Metrics are also taking a while to be available (30min to a few hours) after a restart of legacy nodes.

**Comment by deepfire** [comment]
@jbgi, is the drop permanent, or does the chain density (the proper term) stay low?

If it does, that could be an indication that the new nodes don't produce blocks -- and that could be judged by the absence of `TraceForgeEvent`'s.

To make sense out of all this -- we'd need logs.

**Comment by kevinhammond** [comment]
Can we close this?

**Comment by jbgi** [comment]
yes.
