### ISSUE TITLE
[BUG] - 1.35.4: Error while trying to build Cardano Node on debian:11-slim with aarch64

### ISSUE THREAD

**Issue by drobakowski** [input-output-hk/cardano-node#4824]
**External**

**Area**
*Building*, *Node*, *Docker*, *tx-generator*

**Summary**
Cardano Node 1.35.4 fails building on debian:11-slim (aarch64) with the error message `cabal: Failed to build tx-generator-2.2 (which is required by test:tx-generator-test from tx-generator-2.2 and exe:tx-generator from tx-generator-2.2).`

**Steps to reproduce**
1. `git clone -b 1.35.4 --depth 1 https://github.com/input-output-hk/cardano-node.git`
2. `cabal update && cabal configure`
3. `cabal build all`

**System info (please complete the following information):**
- OS Name: `debian`
- OS Version: `11`
- Architecture: `aarch64`
- Node version: `1.35.4`
- GHC: `8.10.7`
- Cabal: `3.6.2.0`

**Screenshots and attachments**

<img width="977" alt="image" src="https://user-images.githubusercontent.com/81381/213883385-f4a0dfed-34eb-49fc-9c25-fb881d2ff289.png">
<img width="978" alt="image" src="https://user-images.githubusercontent.com/81381/213883409-a3f38b06-2015-48b7-b011-f5fef427bcac.png">

**Additional context**
I'm trying to build the node version 1.35.4 for a custom docker image for `arm64` architecture in order to prepare for the next Cardano upgrade on February 14, 2023. Are there any plans to release a new version 1.35.5 which maybe fixes the problem before February 14, 2023?

**Comment by Swordlash** [comment]
Workaround: adding this
```
package tx-generator
  ghc-options: -XConstraintKinds
```
to `cabal.project.local` may fix the problem.

**Comment by drobakowski** [comment]
Hi @Swordlash, thanks for the reply and your workaround. The workaround indeed fixed the build, but I did get some other follow-up compilation errors. Fortunately the new released version `1.35.5` fixed all errors for me so I'm closing this issue. Thanks again for your help!
