### ISSUE TITLE
[BUG] - cardano-cli should error if provided invalid cost model

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#4867]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
cardano-cli when given a cost model with invalid keys (in this case `PlutusScriptV1` and V2. It currently creates an update proposal with a null cost model (e.g. no change on-chain). This is problematic because the only way to tell this has happened is to look at the raw CBOR or wait until it's on chain and view it in db-sync. If it has the wrong key names, it would be better to error out loudly and break the script from running so the undesirable noop option isn't taken.

**Steps to reproduce**
`cardano-cli governance create-update-proposal --epoch 50 --max-block-execution-units '(20000000000,62000000)' --cost-model-file ~/cost-model-secp-preprod-mainnet.json --protocol-major-version 8 --protocol-minor-version 0 --genesis-verification-key-file foo.vkey --out-file update.proposal`
view resulting hex in cbor.me

**Expected behavior**
Throw an error if cost model is missing PlutusV1 or PlutusV2 attributes.

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]
- Node version (output of `cardano-node --version`)
- CLI version  (output of `cardano-cli --version`)

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by newhoggy** [comment]
@disassembler can you provide or link me to the `~/cost-model-secp-preprod-mainnet.json` you used?  Or provide some instructions on how to construct it?

**Comment by newhoggy** [comment]
[cost-model-secp-preprod-mainnet.json.gz](https://github.com/input-output-hk/cardano-node/files/10729282/cost-model-secp-preprod-mainnet.json.gz)
