### ISSUE TITLE
Parameterize analyse.sh script so it can use different networks

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#489]
Currently test builds for cardano-node nightly sync pipeline (https://buildkite.com/input-output-hk/cardano-node-nightly-sync) are failing for testnet.

Test build failed for testnet (mainnet is OK) with following error - `ls: cannot access 'state-node-mainnet/node-0-*.log': No such file or directory`  

`analyse.sh` is not paramterized to use anything elese apart mainnet: https://github.com/input-output-hk/cardano-node/blob/master/benchmarking/chain-sync/analyse-logs.sh

We need to parametrize the script (with default being mainnet).

**Comment by oneEdoubleD** [comment]
This change has been merged with `Master`. I think further work is required to update hardcoded directory paths in other scripts as the epochs are stored in `<network>-state` but they're looking for `mainnet-state`. Will double check the buildkite logs and open seperate issues for that. 

https://github.com/input-output-hk/cardano-node/commit/9301ffa1ed600a602f2c827ec556debb75da7e96
