### ISSUE TITLE
[FR] - Tooling for slot - unixtime conversion

### ISSUE THREAD

**Issue by nielstron** [input-output-hk/cardano-node#4928]
**Internal/External**
*External*  

**Area**
*Plutus* 

**Describe the feature you'd like**
There is currently only external tooling for converting between unixtime and slot time. This is a nuisance because

- Plutus works with Unix timestamps
- building a transaction with the CLI expects invalid-hereafter and invalid-before in slots
- native scripts work with slots

A simple command to convert between the two, given the network, would help a lot.

**Describe alternatives you've considered**
An alternative is adding a `invalid-hereafter-unixtimestamp`-ish flag to `transaction build`, but it is not nearly as widely applicable
 (for example tools may want to check what unix time a specific slot returned by the CLI corresponds to)

**Additional context / screenshots**
This would also be useful to be able to convert between native scripts and plutus scripts, see this comment: https://github.com/cardano-foundation/CIPs/pull/392#issuecomment-1450969771

**Comment by nielstron** [comment]
This is still relevant to me

**Comment by nielstron** [comment]
I don't think it is necessary. If its a major implementation hurdle, it may well just raise an Error in my case.

**Comment by carbolymer** [comment]
@nielstron would you mind taking a look at [the sample usage of the new proposed command](https://github.com/input-output-hk/cardano-node/pull/5149) if it works for you?

**Comment by nielstron** [comment]
This looks good to me :) Thank you!

**Comment by carbolymer** [comment]
Closing because https://github.com/input-output-hk/cardano-node/pull/5149 got merged.
