### ISSUE TITLE
systemd socket activation for cardano node

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#498]
Support systemd socket activation where the socket is passed by systemd to the node http://0pointer.de/blog/projects/socket-activation.html

**Comment by disassembler** [comment]
In addition, when the socket activation is not used, users should be able to set the socket path instead of the node choosing what naming scheme it wants to use in a socket-dir. Switching from socket-path to socket-dir was a horrible design decision, and now the name switched from `node-core-0.socket -> node-core-CoreNodeId 0.socket` just by upgrading the node.

**Comment by dcoutts** [comment]
The socket path option is still available. And I agree that we should remove the socket dir option. It is not helpful on balance.

Yes, systemd support would be nice, but we can just specify the socket path explicitly, and we can do that immediately.

**Comment by erikd** [comment]
The socket directory option is useful from some of the cluster scripts, so we may want to keep it, but we should hide it or make it clear that a filepath is the default.

**Comment by disassembler** [comment]
> Yes, systemd support would be nice, but we can just specify the socket path explicitly, and we can do that immediately.

That is correct, but permissions get screwed up on the socket every time the node restarts. However; this isn't as big of a problem once we get 1.5.0 on mainnet as we won't have the memory leak causing OOM errors 1-2 times a day.

**Comment by kevinhammond** [comment]
We are looking at implementation priorities. It is not obvious to me whether this is still needed - can you confirm please @disassembler

**Comment by disassembler** [comment]
yes, absolutely needed.

**Comment by disassembler** [comment]
We still have permission issues when the node restarts. It just doesn't crash causing permission errors anymore. But I would really like to just have systemd handle the socket and not have to deal with it manually.
