### ISSUE TITLE
don't change permissions for socket on restart

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#499]
If you restart the node, the explorer and tx endpoint can't communicate with it until the permissions are changed back on the socket. Ideally, restarting a node wouldn't screw up the permissions.

**Comment by kevinhammond** [comment]
Someone needs to look at this.  I believe it can wait until after release, but might be quick for someone to do

**Comment by disassembler** [comment]
resolved with systemd socket activation.
