### ISSUE TITLE
[FR] - Provide JSON instances for  

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#5000]
**External**

**Tracing / Consensus**

**Describe the feature you'd like**

Provide proper `JSON` instances for

* `ConsensusNetworkVersionTuple NodeToClientVersion blkVersion`
* `ConsensusNetworkVersionTuple NodeToNodeVersion blkVersion`

See [this](https://github.com/input-output-hk/cardano-node/pull/4691/files#r1038259309) comment.

**Comment by dnadales** [comment]
What about the instances mentioned in the comment linked above? Namely:

- BlockNodeToClientVersion
- BlockNodeToNodeVersion

**Comment by dnadales** [comment]
@coot To implement this I need to understand what "proper `JSON` instances" means in this context 🙏

**Comment by dnadales** [comment]
This will be closed by https://github.com/input-output-hk/cardano-node/pull/5022

CC: @Jimbo4350
