### ISSUE TITLE
[FR] - 

### ISSUE THREAD

**Issue by AAMARAB** [input-output-hk/cardano-node#5034]
**Internal/External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by AAMARAB** [comment]
تعليق الحساب وارسال

**Comment by erikd** [comment]
> تعليق الحساب وارسال

Using Google translate than translates to "Account suspension and sending". 

The common language amongst Cardano developers is English. Anything else is just wasting our time.
