### ISSUE TITLE
Simplify cardano-cli commands as much as possible

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#504]
Commands like `generate-txs` have an insane number of options, and some seem to be for testing and benchmarking.

Normally, this command should be just `generate-tx` which generates a single tx. Generating multiple txs should probably be a separate command. Anything that is really only for benchmarking should be hidden for regular users.

I also wonder about things like `(--byron-legacy | --bft | --praos | -mock-pbft | --real-pbft)`. Shouldn't these be extracted from the config file which is a separate command line parameter?

**Comment by kevinhammond** [comment]
Look at this after the Shelley node CLI. I’d probably use the command name to present a simpler set of options (ie one codebase but different options depending on how the command is invoked)

**Comment by Jimbo4350** [comment]
This has progressed significantly. A new ticket can be created if necessary.
