### ISSUE TITLE
[FR] - Governance CLI command design

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#5208]
*Internal*

**Area**
*Governance*

**Describe the feature you'd like**
Design for new CLI commands and modifications to existing CLI commands for [CIP-1694](https://github.com/JaredCorduan/CIPs/blob/voltaire-v1/CIP-1694/README.md)

The design can be found here: https://github.com/input-output-hk/cardano-node/pull/5209/files

**Comment by CarlosLopezDeLara** [comment]
Replaced by https://github.com/input-output-hk/cardano-cli/issues/14
