### ISSUE TITLE
[BUG] - Declaratively building cardano-node on NixOS using flakes broken since 1.35.6

### ISSUE THREAD

**Issue by pigofapool** [input-output-hk/cardano-node#5216]
**Internal/External**
*External*

**Area**
*Other*

**Summary**
Not sure whether to report this as a bug or a feature request, but as this was working with 1.35.5 and not working after that, I've raised it as a bug.
Specifically building a NixOS configuration that includes cardano-node has been failing since 1.35.5.

It's possible I'm doing something wrong here and there is a better way of doing this, in which case how is this supposed to be done?

**Steps to reproduce**
I've narrowed it down to the following Nix script building a NixOS live CD containing cardano-node:

```nix
{
  inputs = {
    nixpkgs.url =
      github:NixOS/nixpkgs/897876e4c484f1e8f92009fd11b7d988a121a4e7;

    cardano-node.url =
      github:input-output-hk/cardano-node/8.0.0;
  };

  outputs = { self, nixpkgs, ... } @ attrs: let

    config = args @ { config, pkgs, specialArgs, ... }: {

      environment.systemPackages = with pkgs; [
        cardano-node
      ];

      nix = {
        settings = {
          substituters = [
            https://cache.iog.io
          ];

          trusted-public-keys = [
            hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          ];

          auto-optimise-store = true;
          sandbox             = true;
        };

        extraOptions = ''
          experimental-features = nix-command flakes
        '';
      };

      system.stateVersion = "23.05";
    };

  in {
    nixosConfigurations = {
      livecd = nixpkgs.lib.nixosSystem {
        system      = "x86_64-linux";
        specialArgs = attrs;

        pkgs = import nixpkgs {
          system   = "x86_64-linux";
          overlays = [ attrs.cardano-node.overlay ];
        };

        modules = [
          config
          "${nixpkgs}/nixos/modules/installer/cd-dvd/installation-cd-minimal.nix"
        ];
      };
    };
  };
}
```

Building the above using
```bash
nix build .#nixosConfigurations.livecd.config.system.build.isoImage
```

results in the following error
```
error: attribute 'haskell-nix' missing

       at /nix/store/gcrrzpgj3wsvj996cdxfbfch5xcn067h-source/flake.nix:403:57:

          402|       overlay = final: prev: {
          403|         cardanoNodeProject = (import ./nix/haskell.nix {
             |                                                         ^
          404|           inherit (final) haskell-nix;
       Did you mean haskell-ci?
(use '--show-trace' to show detailed location information)
```

Replacing `github:input-output-hk/cardano-node/8.0.0` with `github:input-output-hk/cardano-node/1.35.5` fixes the problem.

**Expected behavior**
In the above example, a NixOS live CD ISO containing cardano-node should be successfully built.

**System info (please complete the following information):**
- OS Name: NixOS
- OS Version: 23.05.20230506.897876e (Stoat)
- Node version: 1.35.6 up to 8.0.0
- CLI version: N/A

**Comment by andreabedini** [comment]
@pigofapool Apologies for the long delay!

The problem is that the overlay that cardano-node exposes only contains cardano-node and not all its dependencies, which you can see here https://github.com/input-output-hk/cardano-node/blob/1f9f6dbc0c2c8aa618309b865525d94bcb72389e/flake.nix#L103-L126

Nevertheless, if you only need a nixpkgs with cardano-node, you can use `legacyPackages` which is exposed by cardano-node's flake. E.g.

```nix
nixpkgs.lib.nixosSystem rec {
  system = "x86_64-linux";
  specialArgs = attrs;

  pkgs = attrs.cardano-node.legacyPackages.${system};

  modules = [
    config
    "${nixpkgs}/nixos/modules/installer/cd-dvd/installation-cd-minimal.nix"
  ];
}
```

I have tested this with `github:input-output-hk/cardano-node/8.0.0` and it seems to work.
