### ISSUE TITLE
[BUG] - `cardano-cli ping` not working with unix socket

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#5245]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The `cardano-cli ping` doesn't work when unix socket is used instead of host and port:

```sh
$ cardano-cli ping --count 5 --unixsock /home/martink/Source/repos/cardano-node/state-cluster0/pool1.socket --magic 42
/home/martink/Source/repos/cardano-node/state-cluster0/pool1.socket network rtt: 0.000
/home/martink/Source/repos/cardano-node/state-cluster0/pool1.socket handshake rtt: 0.000198263s
/home/martink/Source/repos/cardano-node/state-cluster0/pool1.socket Negotiated version NodeToClientVersionV14 42
(AddrInfo {addrFlags = [], addrFamily = AF_UNIX, addrSocketType = Stream, addrProtocol = 0, addrAddress = /home/martink/Source/repos/cardano-node/state-cluster0/pool1.socket, addrCanonName = Nothing},MuxError MuxBearerClosed "<socket: 11> closed when reading data, waiting on next header True")
```

The node is listening on the socket, eg:

```
$ cardano-cli query tip --testnet-magic 42 --socket-path /home/martink/Source/repos/cardano-node/state-cluster0/pool1.socket
{
    "block": 122,
    "epoch": 1,
    "era": "Babbage",
    "hash": "088d3fde1274565067c4384a0f4534a4d94da2f7a89ef0e2367fca679a6022cb",
    "slot": 1188,
    "slotInEpoch": 188,
    "slotsToEpochEnd": 812,
    "syncProgress": "100.00"
}
```

**EDIT:**

In log file I can see

> [31m[fv-az365:cardano.node.LocalErrorPolicy:Error:65][0m [2023-05-16 00:03:43.76 UTC] IP LocalAddress "./state-cluster3/bft1.socket@3091" ErrorPolicyUnhandledApplicationException (MuxError MuxUnknownMiniProtocol "id = MiniProtocolNum 8")

**System info:**
- OS Name: Linux
- OS Version Fedora 37
- Node version: 1522f970676961cb4a88f89fb1896f5b33fb0ff4
- CLI version: 1522f970676961cb4a88f89fb1896f5b33fb0ff4

**Comment by carbolymer** [comment]
The output on https://github.com/input-output-hk/cardano-node/pull/5326 :
```
cabal run cardano-cli -- ping --magic 2 --count 5 --unixsock $CARDANO_NODE_SOCKET_PATH
/home/mgalazyn/workspace/iohk/network-preview/node.socket network rtt: 0.000
/home/mgalazyn/workspace/iohk/network-preview/node.socket handshake rtt: 0.000336436s
/home/mgalazyn/workspace/iohk/network-preview/node.socket Negotiated version NodeToClientVersionV15 2
```
so it looks like it's fixed

**Comment by mkoura** [comment]
The issue is still present on current master (51c9002988967e8afc13a6ebbffc5c8c9c76bd21):
```
$ cardano-cli ping --count 5 --unixsock /home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket --magic 42 --json
/home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket network rtt: 0.000
/home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket handshake rtt: 0.000178226s
/home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket Negotiated version NodeToClientVersionV14 42
] }
(AddrInfo {addrFlags = [], addrFamily = AF_UNIX, addrSocketType = Stream, addrProtocol = 0, addrAddress = /home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket, addrCanonName = Nothing},MuxError MuxBearerClosed "<socket: 11> closed when reading data, waiting on next header True")
```

**Comment by coot** [comment]
The commit 51c9002 no longer contains `cardano-cli`, it was moved to its own repo. Here's output from input-output-hk/cardano-cli@89cdd923a66afa9343d04864f89a9603143e290d against a node running on mainnet (thus no `--magic`):
```
cabal run exe:cardano-cli -- ping -u /var/run/user/1000/coot-node.socket
/var/run/user/1000/coot-node.socket network rtt: 0.000
/var/run/user/1000/coot-node.socket handshake rtt: 0.120501234s
/var/run/user/1000/coot-node.socket Negotiated version NodeToClientVersionV15 764824073
```
Note that `-c` flag is not supported on `node-to-client` protocol (it's noop), simply because `node-to-client` doesn't include the [keep-alive](https://input-output-hk.github.io/ouroboros-network/ouroboros-network-protocols/Ouroboros-Network-Protocol-KeepAlive-Type.html#t:KeepAlive) protocol which is used to send the pings.

**Comment by coot** [comment]
@mkoura oh, I realised that you might have tried `cardano-cli` which nix shell provides.  Probably a newer release of `cardano-cli` is needed and the update to the shell.
