### ISSUE TITLE
[BUG] - cabel build all  -error

### ISSUE THREAD

**Issue by 0xkf** [input-output-hk/cardano-node#5252]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   installing cardano-cli

**Summary**
A clear and specific description of what the bug will happen when I push "cabel build all"
error log is as below.

cabal: Failed to build exe:chain-sync-client-with-ledger-state from
cardano-client-demo-0.1.0.0.
Failed to build exe:scan-blocks from cardano-client-demo-0.1.0.0.
Failed to build exe:scan-blocks-pipelined from cardano-client-demo-0.1.0.0.
Failed to build exe:stake-credential-history from cardano-client-demo-0.1.0.0.

**Steps to reproduce**
1. Go to '.https://developers.cardano.org/docs/get-started/installing-cardano-node'
2. just follow the tutorial of installing cardano-node and cardano-cli ''
3. command "cabal build all"

**Expected behavior**
success

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]

**Additional context**
nothing

**Comment by CarlosLopezDeLara** [comment]
Looks like https://developers.cardano.org/docs/get-started/installing-cardano-node/ points to wrong libsodium version
please see instructions on the node repository:  

https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md

**Comment by CarlosLopezDeLara** [comment]
Please reopen if needed.
