### ISSUE TITLE
Add a `create-tx` command that uses `TxAux`

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#526]
https://github.com/input-output-hk/cardano-ledger/blob/master/cardano-ledger/src/Cardano/Chain/UTxO/TxAux.hs#L48

**Comment by dcoutts** [comment]
I think the point here is that while `GenTx blk` has a binary CBOR format, and this is the one used in the tx submission protocol, it is not necessarily the same as the format of objects as they appear on the chain.

**Comment by Jimbo4350** [comment]
This was completed.
