### ISSUE TITLE
tx submission tracing details at default log level

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-node#527]
We need to ensure that at the default tracing levels we get the crucial information needed to trace a tx through the mempool of multiple nodes, to see where it got to.

So at default logging level:
* for `TraceMempoolAddTxs` we must see the txids
* for `TraceMempoolRejectedTxs` we must see the txids and rejection reason
* for `TraceMempoolRemoveTxs` we  must see the txids
* for `TraceMempoolManuallyRemovedTxs` we must also see the txids here.

(I wonder if `TraceMempoolManuallyRemovedTxs` should not be merged with `TraceMempoolRemovedTxs` and include a reason enumeration instead. We can have things removed because of timeout or because of ledger state changes.)

We also need to trace at the default log level for the outbound side of tx submission:
* when a remote peer has requested a tx id, and we do send the tx to them, then we should log that the txid was requested and sent

**Comment by dcoutts** [comment]
So it looks like these ought to be included at the "Informational" severity level, not debug. Our default min severity level for the node is probably going to be set to Informational.

**Comment by intricate** [comment]
Added tracing for `TraceEventMempool`s in #538. 

The protocol-level tx submission tracing seem to requires a change to `ouroboros-network` so I'll be raising another PR for that.

**Comment by intricate** [comment]
Following the merge of https://github.com/input-output-hk/cardano-node/pull/569, I'll be raising another PR which will fully close this issue.

**Comment by intricate** [comment]
See https://github.com/input-output-hk/cardano-node/pull/584#pullrequestreview-360687721.
