### ISSUE TITLE
block forging tracing details at default log level

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-node#528]
We need to ensure that at the default tracing levels we get the crucial information needed to trace a tx through the mempool of multiple nodes and into a block, to see where it got to.

So at default logging level:
 * for `TraceAdoptedBlock` we must see the block hash and the txids included into the block

For log analysis this lets us correlate the new block hash with the txs that were included into it. From there on we can trace the block hash.

For unrelated reasons we must also trace at default log level:
 * `TraceNoLedgerState`
* `TraceNoLedgerView`
* `TraceBlockFromFuture`
* `TraceDidntAdoptBlock`
* `TraceForgedInvalidBlock`

These are all rare, but possible failures. These should be logged at "Error" level, not just "Warning".

**Comment by dcoutts** [comment]
So it looks like the `TraceAdoptedBlock` mentioned above ought to be included at the "Informational" severity level, not debug. Our default min severity level for the node is probably going to be set to Informational.

**Comment by CodiePP** [comment]
for analysing benchmarking runs we read the blocks <-> tx relation from `ChainSyncServerEvent.TraceChainSyncServerReadBlocked.AddBlock` events.
probably requires 'MaximumVerbosity' to also print the list of tx ids.

**Comment by CodiePP** [comment]
example:
```
{"at":"2019-12-05T07:27:42.02Z","env":"fromList [(\"value\",String \"Release-1.0.0\")]:0.1.10.1","ns":["cardano","node","ChainSyncBlockServer"],"data":{},"app":[],"msg":"{\"kind\":\"ChainSyncServerEvent.TraceChainSyncServerReadBlocked.AddBlock\",\"tip\":\"ad1611fa710e0124@3129\",\"addedBlock\":\"( header: ( hash: ad1611fa710e0124, previousHash: 360b63cbe8063333, slot: 3129, issuer: pub:66015c5e, delegate: pub:08eead5d), body: [Tx a17c1860bb4ac86c with inputs [TxInUtxo 09b723aa #0], outputs: [TxOut 2015999990000000 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa],Tx fc9cc64e495005a8 with inputs [TxInUtxo a17c1860 #0], outputs: [TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut 40309999800 lovelace -> 2cWKMJemoBahde4jY46AvTLaAkzMcRJRSNit75PLtdAyUxZD742i2QTUAcy5H3BMuoTAa, TxOut ....
```
