### ISSUE TITLE
[BUG] - P2P broken on 8.1.0-pre - nodes not communicating with each other

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#5294]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
When P2P is enabled for a node, the node is not communicating with other nodes. It is forging blocks, it is not printing any peer selection errors.

**Expected behavior**
A node is communicating with other nodes in the network.

**System info:**
- OS Name: Fedora 37
- Node version: 93c0307b33d4105156924b03a2316bea38e6d358
- CLI version: 93c0307b33d4105156924b03a2316bea38e6d358

**Screenshots and attachments**
Logs and config attached: [p2p_logs.tar.gz](https://github.com/input-output-hk/cardano-node/files/11633432/p2p_logs.tar.gz)

**Comment by feqifei** [comment]
I'm facing a similar problem, no incoming connection in the block producer from the relay (no incoming connection at all cos the relay is the only address declared in its topology file).
BP and relay are on the same VM with a public IP X.X.X.X and a LAN ip 10.42.80.240 and following configurations:
- Relay
8.1.0-pre with p2p enabled and "ExperimentalProtocolsEnabled": false
port 4003 open to internet 
startup command without --host-addr parameter (it should start on 0.0.0.0)
its topology contains the link to the BP
{
  "localRoots": [
    { "accessPoints": [
        {
          "address": "10.42.80.240",
          "port": 5002
        }
      ],
      "advertise": false,
      "valency": 1
    }
  ],
 ...
 
 - Block Producer
8.1.0-pre with p2p enabled and "ExperimentalProtocolsEnabled": false
port 5002 only open to LAN addresses
startup command with --host-addr 10.42.80.240
its topology contains the link to the relay
{
  "localRoots": [
    { "accessPoints": [
        {
          "address": "10.42.80.240",
          "port": 4003
        }
      ],
      "advertise": false,
      "valency": 1
    }
  ],
 ...

I tried to:
- disable p2p on the BP, 
- downgrade the BP to 8.0.0, (with and without p2p enabled),
- change the relay address  in the BP's topology file from the local one to X.X.X.X,
- start the BP node without --host-addr parameter
- open the 5002 port of the BP to internet and change the BP address from 10.42.80.240 to X.X.X.X in the relay topology

Finally I downgraded both nodes to 8.0.0 and restored their initial configuration and incoming connection to the BP came back working again.

**Comment by mkoura** [comment]
It is fixed in `8.1.1-pre`.

**Comment by feqifei** [comment]
I confirm, 8.1.1-pre fixes it

**Comment by CarlosLopezDeLara** [comment]
Closing as @mkoura confirmed the fix with 8.1.1
