### ISSUE TITLE
[BUG] - What is status of `1.36` cardano-api package release?

### ISSUE THREAD

**Issue by uhbif19** [input-output-hk/cardano-node#5295]
*External*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**

`1.36` version is already used by `hydra`, and consequently by us `hydra-auction`.
But it is still not on CHaP. At the same time there is some `8.0` version published, which, as far as I understand,
would follow `1.36`.

It looks that master is on `1.36.*` version for > half year, but I could not find plans on `1.36.*` release.
https://github.com/input-output-hk/cardano-node/pull/4391

What is it status?

**Steps to reproduce**

Go to:

https://input-output-hk.github.io/cardano-haskell-packages/all-package-versions/index.html

or github releases

and look for `cardano-api` version `1.36.*`.

**Expected behavior**

`1.36` version appear on CHaP.

**System info (please complete the following information):**

Not applicable.

**Screenshots and attachments**

![image](https://github.com/input-output-hk/cardano-node/assets/300919/ab4c7ddd-1706-4d7a-9d2a-77cf148acc71)

**Comment by uhbif19** [comment]
@disassembler @tatyanavych @cleverca22 @LaurenceIO .

**Comment by carbolymer** [comment]
Is this issue still relevant?

>It looks that master is on 1.36.* version for > half year, but I could not find plans on 1.36.* release.
https://github.com/input-output-hk/cardano-node/pull/4391
At this moment `cardano-node` is on 8.20 at this very moment: https://github.com/search?q=repo%3Ainput-output-hk%2Fcardano-node+cardano-api+language%3A%22Cabal+Config%22&type=code&l=Cabal+Config

>1.36 version is already used by hydra, and consequently by us hydra-auction.
But it is still not on CHaP. At the same time there is some 8.0 version published, which, as far as I understand,
would follow 1.36.

Can you try to use latest 8.x version?

**Comment by newhoggy** [comment]
Will this work for you?

https://github.com/input-output-hk/cardano-haskell-packages/pull/508

**Comment by uhbif19** [comment]
Yes, we moved to `8.x` once our dependency https://github.com/input-output-hk/hydra/ did the same, around a month a ago. So seems like issue is not important for our project anymore.

But this was overall, not smoothest way to do version bump, that is why `1.36` and some other pinned deps was used for a while.

**Comment by carbolymer** [comment]
@uhbif19 Thanks for the response. In that case I'm closing the issue. Let us know if you need further assistance.
