### ISSUE TITLE
[BUG] - 8.1.1pre exits with an "error" message on SIGINT

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#5312]
cardano-node 8.1.1-pre

If you send a `SIGINT` signal to the node to initialize a graceful shutdown/exit, the node exits with the message:
`cardano-node: DiffusionError user interrupt`

Not sure if its a feature or a bug, but at least a bit confusing to the user to get an error on such a shutdown.

**Comment by CarlosLopezDeLara** [comment]
I think this is the expected behavior (Exception)  when the user requests to terminate the program. I think @coot can confirm

**Comment by coot** [comment]
We just log every exception.  Is it confusing or is it reassuring that diffusion exited with the right exception?  I am thinking it's the latter.

**Comment by gitmachtl** [comment]
> We just log every exception. Is it confusing or is it reassuring that diffusion exited with the right exception? I am thinking it's the latter.

All good, just wanted to check that this is the intended output after exiting via `SIGINT`.

**Comment by coot** [comment]
Most of the tools I am used to do not print any error when `SIGINT` is sent and handled correctly, so I can see that it's confusing.

**Comment by CarlosLopezDeLara** [comment]
I agree it is a bit confusing. What do you want to do with this @coot? Perhaps turn it into a FR/Enhancement ticket?

**Comment by coot** [comment]
The PR I linked will handle exceptions wrapped in `DiffusionError` in exactly the same way as they used to be handled, and thus avoid printing `AsyncException` (one of which is  `UserInterrupt`).
