### ISSUE TITLE
[FR] - API or CLI to get raw txn hex of an onchain txn

### ISSUE THREAD

**Issue by evanzbitgo** [input-output-hk/cardano-node#5358]
**External**

**Area**
*Other*   API

**Describe the feature you'd like**
Are there any ways to get raw transaction hex of an onchain txn in Cardano? Something like [link](https://etherscan.io/getRawTx?tx=0x248b16e4cb8a624ab4bb3125a3a2cf6bd6d21200b773e3d9c1f0738b1b09dd22) in Ethereum

**Comment by nielstron** [comment]
AFAIK this is possible with ogmios, but not with the Cardano-CLI

**Comment by nielstron** [comment]
This was closed, it would be great to have a link or description to the feature that resolves this.
