### ISSUE TITLE
Cannot build version `8.1.1` due to a missing `blst` library.

### ISSUE THREAD

**Issue by andrejpodzimek** [input-output-hk/cardano-node#5378]
**Internal/External**
*External*

**Area**
*Other*

**Summary**
I cannot build `cardano-node` due to a missing `libblst`:

```
Failed to build cardano-crypto-class-2.1.2.0. The failure occurred during the
configure step.
Build log (
/home/andrej/.cabal/logs/ghc-8.10.7/cardano-crypto-class-2.1.2.0-3e2d0bbbe73f3319f517ff16860a1bbfc3757c052c18fbd90e85a870b9eeff59.log
):
Configuring library for cardano-crypto-class-2.1.2.0..
cabal-3.6.2.0: The pkg-config package 'libblst' is required but it could not
be found.

cabal: Failed to build cardano-crypto-class-2.1.2.0 (which is required by
test:tx-generator-test from tx-generator-2.5, test:tx-generator-apitest from
tx-generator-2.5 and others). See the build log above for details.
```

**Steps to reproduce**

0. Try to [get `libblst`](https://github.com/supranational/blst#c-static-library) somehow somewhere, then `./build.sh`, then (quick&dirty hack) copy `libblst.a` to `/usr/lib/`.
1. Take [this ArchLinux `PKGBUILD`](https://pastebin.com/Gmw4euR9) (a modified version of [the outdated AUR package](https://aur.archlinux.org/packages/cardano-node)).
2. Try to build it (`makepkg`), with `libsecp256k1` and `libsodium` properly installed _and_ with `/usr/lib/libblst.a` “hacked in” (see above).

**Expected behavior**
It should build. Or there should be some documentation on how to provide `blst`.

**System info (please complete the following information):**
- OS Name: ArchLinux
- OS Version: up-to-date
- Node version (output of `cardano-node --version`): **Irrelevant.** (Currently at `1.35.5`, trying to build `8.1.1`.)
- CLI version  (output of `cardano-cli --version`): **Irrelevant.** (Same as above.)

**Additional context**
Maybe a `libblst.so` is required? Any ideas how to (easily) get an `-fPIC` flavor of the `blst` library (if that’s what’s required)? Maybe a Haskell binding of some sort needs to be installed separately too?

**Comment by andrejpodzimek** [comment]
I’ve noticed [`iohk-nix`](https://github.com/input-output-hk/iohk-nix). Would it make sense (or is it required now) to [use `nix` on ArchLinux](https://wiki.archlinux.org/title/Nix) to get `cardano-node` to build on the distro? (No idea how to use [this](https://github.com/input-output-hk/actions) either. :disappointed: That’s where the three dependencies (+1) are explicitly listed.)

**Comment by andrejpodzimek** [comment]
This bug still makes `cardano-node` unusable / unbuildable on a number of distros. (The common “use the pre-built binary” answer doesn’t work for me for a couple of reasons (yes, hacks).) Some distros do have the `blst` package, but it’s unclear to me how it gets picked up by the build system to get the right Haskell bindings somehow.

I’ve found **[this snippet](https://github.com/input-output-hk/cardano-base/commit/b1a467dc9082b97aaa4ce0f6cd7c77e8be46d5de)**, which is technically not even part of `cardano-node` (nor `cardano-base`, as the warning message suggests), but provides the following clues:

0. It creates a piece of metadata that lets the `pkg-config` tool provide information about the package.
1. That information may (?) be used by the `cardano-node` build system to detect the `blst` library and actually use the `libblst.a`.
2. With that↑ said, my ugly homebrew “just copy `libblst.a`” approach probably failed due to this missing `libblst.pc` metadata. Another dependency, `libsecp256k1`, does have this particular metadata on ArchLinux (in `/usr/lib/pkgconfig/libsecp256k1.pc`, owned by the `libsecp256k1` package).

So the next thing to try might be to add `libblst.pc`, check if `pkg-config libblst` shows some output and then (maybe) the `cardano-node` could build again. (If only ArchLinux had a `blst` package, but I can’t find it even in AUR (yet).)

**Comment by angerman** [comment]
There are a bunch of annoying complications:
- blst has rather poor packaging.
- dealing with raw libraries (without pkgconfig) and getting the flags alright can get increasingly complex.
- we now depend on blst in node.

The easiest is to build your own blst.a, and create a corresponding .pc (pkg config) file. That file needs to be in the PKG_CONFIG_PATH environment variable.

The iohk-nix repo contains pre-builds for Linux, macOS and windows. They most likely should work on _any_ Linux despite packaged as .debs.

We could probabaly stick them into rpms and pkgs (for arch as well; we already hack pacman pkgs for mingw64 (windows)).

**Comment by mdvillagra** [comment]
I did exactly that. I manually compiled and copied the blst library and header files in their corresponding places and created a .pc file for pkg-config. Then all dependencies were solved but my last compile step failed with this:

`cardano-crypto-class-2.2.0.0: library-dirs: \\/usr/lib is a relative path
which makes no sense (as there is nothing for it to be relative to). You can
make paths relative to the package database itself by using ${pkgroot}. (use
--force to override)`

`cardano-crypto-class-2.2.0.0: dynamic-library-dirs: \\/usr/lib is a relative
path which makes no sense (as there is nothing for it to be relative to). You
can make paths relative to the package database itself by using ${pkgroot}.
(use --force to override)
)`

I think it is related to this [issue](https://github.com/haskell/cabal/issues/1317).

**Comment by andrejpodzimek** [comment]
I’ve “successfully” built `8.1.2`, but it’s hacky and incomplete, hence the double quotes.

0. Added `/usr/lib/pkgconfig/libblst.pc` with this content (on ArchLinux; other distros may need different settings):
   
   ```shell
   prefix=/usr
   exec_prefix=${prefix}
   libdir=${exec_prefix}/lib
   includedir=${prefix}/include
   
   Name: libblst
   Description: Multilingual BLS12-381 signature library
   URL: https://github.com/supranational/blst
   Version: 0.3.10
   Cflags: -I${includedir}
   Libs: -L${libdir} -lblst
   ```

0. After `git clone git@github.com:supranational/blst.git`, I built `blst` (`./build.sh`), manually “installed” the files and includes and made them world-readable.
   * `sudo cp libblst.a /usr/lib/`
   * `sudo cp blst_aux.h  blst.h  blst.hpp /usr/include/`
   * `sudo chmod u=rw,go=r /usr/{lib/{libblst.a,pkgconfig/libblst.pc},include/{blst.{h,hpp},blst_aux.h}}`

0. Then the usual `makepkg -c` completed successfully.

0. Sadly, [my `PKGBUILD`](https://pastebin.com/Gmw4euR9) is still outdated, because there are new things I need to merge into my configuration. [The config files](https://book.world.dev.cardano.org/environments/mainnet/) now add (at least)
   * `conway-genesis.json`, which is easy to add and referenced from `config.json` and
   * `topology-p2p.json`, which is a _way_ more complicated thing, [described e.g. here](https://forum.cardano.org/t/docs-and-procedures-for-p2p-how-to-run-p2p/107087/22) (without much detail though); it looks like one shoud be (?) running two relays, one in legacy mode and one in P2P mode.

That↑ said, it’s quite frustrating that there seems to be no straightforward howtos lists of migration steps in the release notes. :disappointed: P2P is _mentioned_, but quite hard to grasp for outsiders.

**Comment by CardenPool** [comment]
For reference, full instruction to install libblst can be found on [cardano-node-wiki](https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/getting-started/install.md#installing-blst)

**Comment by andrejpodzimek** [comment]
The good news is that [there is `blst` in AUR now](https://aur.archlinux.org/packages/blst).

The bad news is that the instructions no longer work (for reasons other than `blst`).

```
Warning: Requested index-state 2023-07-21T13:00:00Z is newer than
'cardano-haskell-packages'! Falling back to older state
(2023-07-21T12:48:43Z).
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] next goal: cardano-cli (user goal)
[__0] rejecting: cardano-cli-8.3.2.0, cardano-cli-8.3.1.0,
cardano-cli-8.3.0.0, cardano-cli-8.2.1, cardano-cli-8.2.0 (constraint from
user target requires ==8.1.2)
[__0] trying: cardano-cli-8.1.2
[__1] trying: ouroboros-consensus-protocol-0.5.0.4 (dependency of cardano-cli)
[__2] trying: cardano-crypto-tests-2.1.2.0 (dependency of
ouroboros-consensus-protocol)
[__3] next goal: cardano-crypto-praos (dependency of cardano-crypto-tests)
[__3] rejecting: cardano-crypto-praos-2.1.2.0, cardano-crypto-praos-2.1.1.2,
cardano-crypto-praos-2.1.1.1, cardano-crypto-praos-2.1.1.0,
cardano-crypto-praos-2.1.0.0, cardano-crypto-praos-2.0.0.1,
cardano-crypto-praos-2.0.0.0.1, cardano-crypto-praos-2.0.0 (conflict:
pkg-config package libsodium-any, not found in the pkg-config database)
[__3] fail (backjumping, conflict set: cardano-crypto-praos,
cardano-crypto-tests)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-praos,
cardano-crypto-tests, ouroboros-consensus-protocol, cardano-cli
Try running with --minimize-conflict-set to improve the error message.
```

Tried all combinations of with/without…

```
package cardano-crypto-praos
  flags: -external-libsodium-vrf
```

…and with 3 `libsodium` variants, (1) just [`libsodium`](https://archlinux.org/packages/extra/x86_64/libsodium/) from ArchLinux (which has _always_ been installed on my system), (2) [libsodium-git](https://aur.archlinux.org/packages/libsodium-git) from AUR and (3) the same `libsodium-git` package, just with [input-output-hk/libsodium](https://github.com/input-output-hk/libsodium) used instead of [jedisct1/libsodium](https://github.com/jedisct1/libsodium) while building it. It just doesn’t work. (Of course I’ve tried `rm -Rf ~/.{cabal,ghcup}` and all sorts of “hard resets”.) The full `PKGBUILD` I’m using is [here](https://pastebin.com/mxPJJ9jT).

My nodes are down and this is hugely exhausting.

**Comment by andrejpodzimek** [comment]
My comment above looks off-topic here, so I’ve filed a separate issue #5528 specifically for `libsodium`. The `blst` problem seems to be addressed now.
