### ISSUE TITLE
Prepare release 8.2

### ISSUE THREAD

**Issue by fraser-iohk** [input-output-hk/cardano-node#5380]
- [ ] release cardano-node 8.1.1

- [x] release `cardano-ledger` 8.2 packages
- [x] release `cardano-ledger` 8.2 packages
  - [x] missing `Arbitrary` instance for `ConwayCertPredFailure`
  - [x] missing `Arbitrary` instance for `ConwayDelegPredFailure`
  - [x] missing `Arbitrary` instance for `ConwayVDelPredFailure`
- [x] release `ouroboros-consensus` packages
  - [x] changes to `Cardano.Ledger.UMap`
  - [x] could not deduce `Arbitrary (ConwayCertPredFailure (ConwayEra MockCryptoCompatByron))`
  - [x] could not deduce `Arbitrary (ConwayDelegPredFailure (ConwayEra MockCryptoCompatByron))`
  - [x] could not deduce `Arbitrary (ConwayVDelPredFailure (ConwayEra MockCryptoCompatByron))`
- [x] release `cardano-ledger` 8.2 packages (second wave)
- [x] release `ouroboros-consensus` 8.2 packages (second wave to include changes in [ouroboros-consensus#191](https://github.com/input-output-hk/ouroboros-consensus/pull/191) and [ouroboros-consensus#140](https://github.com/input-output-hk/ouroboros-consensus/pull/140))
- [ ] release `cardano-api` packages
  - [ ] work required to handle change from `TxCert crypto` to `TxCert era` (this work is being completed by Jordan Millar)
- [ ] release `cardano-node` packages

**Comment by dnadales** [comment]
We were asked to also release the following changes:

- [ ] https://github.com/input-output-hk/ouroboros-consensus/pull/191
- [ ] https://github.com/input-output-hk/ouroboros-consensus/pull/140
