### ISSUE TITLE
CLI tool requirement to get tip information

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#541]
Should return tip data point (slot, hash and blockNum) as json.

This is required for monitoring to identify if nodes have forked between legacy/new environment while we're running a hybrid cluster.

This is a pre-requisite to changing any testnet or mainnet core nodes to the new code base.

**Comment by kevinhammond** [comment]
I have raised this as a requirement for the node CLI in JIRA.  Is this Byron or Shelley?
