### ISSUE TITLE
[BUG] - '404- page not found' on doc/getting-started/install.md Where is the Cardano-node getting started documentation?

### ISSUE THREAD

**Issue by Newman5** [input-output-hk/cardano-node#5433]
**Internal/External**

*External*   I am not a staff member

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
I'm trying to access the documentation at this address - https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md/  

which is referenced here: https://plutuspbl.io/modules/102/1021
and here: https://www.youtube.com/watch?v=csqvbw3F_BU&list=PLNEK_Ejlx3x2ut-Pq-hi0NFVsgKB3EddR&index=1

Where is the Cardano-node getting started documentation?

**Steps to reproduce**
This is a simple 404 error in the documentation .  Follow the links above to see the error

**Expected behavior**
I expect to see the documentation referenced in the above links

**System info (please complete the following information):**
NA

**Screenshots and attachments**

![image](https://github.com/input-output-hk/cardano-node/assets/1620405/2d7a6b49-e21b-4802-8cb3-797a16a11c72)

**Additional context**
I'm not sure if this is the write place to bring this up

**Comment by smelc** [comment]
> I found the documentation here: https://developers.cardano.org/docs/get-started/installing-cardano-node/
@Newman5> yep that's the correct one :+1:
