### ISSUE TITLE
Remove Buildkite jobs

### ISSUE THREAD

**Issue by sgillespie** [input-output-hk/cardano-node#5492]
**Internal/External**
*Internal* 

**Area**
*Build/CI*

**Summary**
The Buildkite agents have been decommissioned. Remove all references to Buildkite (`scripts` and `.github`)

**Comment by smelc** [comment]
@sgillespie> can this issue be closed? You've done everything that was required already rigth?

**Comment by sgillespie** [comment]
Not until https://github.com/input-output-hk/cardano-node/pull/5498 is completed
