### ISSUE TITLE
Release engineering: `cardano-node` 8.7.0 

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/cardano-node#5534]
### Revisions
- [x] Fork ekg packages (https://github.com/input-output-hk/ekg)
- [x] Release ekg packages into CHaP (https://github.com/input-output-hk/cardano-haskell-packages/pull/563)
- [x] Update `threepenny-gui`'s dependency on `aeson` and `template-haskell` (asked @HeinrichApfelmus)
- [x] Update `ekg-forward` dependency on `ouroboros-network-framework` (https://github.com/input-output-hk/cardano-haskell-packages/pull/566)
- [x] Revise fs-sim for io-classes (https://github.com/input-output-hk/cardano-haskell-packages/pull/568)

### Ledger
- [x] Update index-states 
- [x] https://github.com/input-output-hk/cardano-ledger/pull/3836
- [x] (if it arrives in time) https://github.com/input-output-hk/cardano-ledger/issues/3826
  - [x] https://github.com/input-output-hk/cardano-ledger/pull/3864
- [x] https://github.com/input-output-hk/cardano-ledger/pull/3856
- [x] Clarify what other features we want in this release (@lehins)
- [x] Tests passing
- [x] Update nix
- [x] https://github.com/input-output-hk/cardano-ledger/pull/3863
- [x] Final PR https://github.com/input-output-hk/cardano-ledger/pull/3854 (needs rebase)
- [x] Release to CHaP https://github.com/input-output-hk/cardano-haskell-packages/pull/560

### Network
- [x] Update index-states
- [x] https://github.com/input-output-hk/ouroboros-network/pull/4712
- [x] Clarify what other features we want in this release (@coot)
  Confirmed we want to release from input-output-hk/ouroboros-network@bb6958e957ba16822e72936de2758445f83fab5c
- [x] Tests passing
- [x] Update nix
- [x] Release to CHaP
- [x] https://github.com/input-output-hk/ouroboros-network/pull/4716
- [x] Release to CHaP

### Consensus 
- [x] Merge https://github.com/input-output-hk/ouroboros-consensus/pull/383 (currently included in the integration branch)
- [x] Clarify `idleTimeout` default value
- [x] Update index-states
- [x] Clarify what other features we want in this release (@dnadales)
- [x] Expose NTN.ChainSyncTimeout for the node (https://github.com/input-output-hk/ouroboros-consensus/pull/495)
- [x] Tests passing
- [x] Update nix
- [x] Fixup ChainSyncTimeout argument (https://github.com/input-output-hk/ouroboros-consensus/pull/509)
- [x] Release to CHaP (https://github.com/input-output-hk/cardano-haskell-packages/pull/565)

### API
- [x] Update index-states
- [x] Use new ledger `THKD`
- [x] Integrate ledger changes and update consensus (https://github.com/input-output-hk/cardano-api/pull/359)
- [x] Clarify what other features we want in this release (@Jimbo4350)
- [x] Tests passing
- [x] Update nix
- [x] Release to CHaP

### Cardano-node
- [x] Update index-state
- [x] https://github.com/input-output-hk/cardano-node/pull/5533
- [x] Clarify what other features we want in this release (@Jimbo4350)
- [x] Tests passing
- [x] Update nix
- [x] Release to CHaP
- [x] Github release

### Cardano-cli (https://github.com/input-output-hk/cardano-cli/pull/440)
- [x] Update index-state
- [x] Clarify what other features we want in this release (@newhoggy)
- [x] Tests passing
- [x] Update nix
- [x] Release to CHaP

### Other changes
- [x] Update `ekg-json` dependency on `aeson` plus changes to the code (do we need a fork?)

**Comment by coot** [comment]
> Clarify what other features we want in this release (@coot)

We don't need anything beside input-output-hk/cardano-haskell-packages#554.

**Comment by lehins** [comment]
This is the only bug fix I can think of that we would like to make in the next release, but it will only depend if we can squash soon enough: https://github.com/input-output-hk/cardano-ledger/issues/3826
