### ISSUE TITLE
[BUG] - Can't build cardano-node on Fedora - conflict: pkg-config package libsodium-any, not found in the pkg-config database

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#5561]
**Internal**

**Area**

Installation instruction:
**Installing the node from source**
https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/getting-started/install.md

**Summary**

Can't build cardano-node on Fedora.

We have tests https://github.com/input-output-hk/cardano-node-tests/tree/master/cabal_build_tests that check "Installing the node from source" instruction in dockerized environments on `Ubuntu` and `Fedora`. 

After updating tests - they are on a branch `artur/update-cabal-tests ` - an attempt to run `8.7.0-pre` on `Ubuntu` worked fine while the same test installation on `Fedora` failed with:

```
Downloading the latest package lists from:
- hackage.haskell.org
- cardano-haskell-packages
Package list of cardano-haskell-packages has been updated.
The index-state is set to 2023-11-30T14:34:52Z.
Package list of hackage.haskell.org has been updated.
The index-state is set to 2023-11-30T21:40:36Z.
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2023-11-30T20:29:10Z'
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: cardano-git-rev-0.1.3.0 (user goal)
[__1] trying: base-4.18.1.0/installed-4.18.1.0 (dependency of cardano-git-rev)
[__2] trying: cardano-node-8.7.0 (user goal)
[__3] trying: ouroboros-consensus-protocol-0.6.0.0 (dependency of
cardano-node)
[__4] trying: cardano-crypto-tests-2.1.2.0 (dependency of
ouroboros-consensus-protocol)
[__5] next goal: cardano-crypto-praos (dependency of cardano-crypto-tests)
[__5] rejecting: cardano-crypto-praos-2.1.2.0, cardano-crypto-praos-2.1.1.2
(conflict: pkg-config package libsodium-any, not found in the pkg-config
database)
[__5] rejecting: cardano-crypto-praos-2.1.1.1 (conflict:
base==4.18.1.0/installed-4.18.1.0, cardano-crypto-praos => base>=4.14 &&
<4.17)
[__5] skipping: cardano-crypto-praos-2.1.1.0, cardano-crypto-praos-2.1.0.0,
cardano-crypto-praos-2.0.0.1, cardano-crypto-praos-2.0.0.0.1,
cardano-crypto-praos-2.0.0 (has the same characteristics that caused the
previous version to fail: excludes 'base' version 4.18.1.0)
[__5] fail (backjumping, conflict set: base, cardano-crypto-praos,
cardano-crypto-tests)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, cardano-crypto-praos,
cardano-crypto-tests, ouroboros-consensus-protocol, cardano-node,
cardano-git-rev
Try running with --minimize-conflict-set to improve the error message.
```

Full logs are attached below.

**Steps to reproduce**
1. Clone `cardano-node-tests`
git clone git@github.com:input-output-hk/cardano-node-tests.git

2. Navigate to `cabal_build_tests` - there is a README there too:
cd cardano-node-tests/cabal_build_tests

3. Checkout branch `artur/update-cabal-tests`
git checkout artur/update-cabal-tests

4. Run tests:
./run-fedora.sh -t tag -o "8.7.0-pre"   --> Fails
./run-ubuntu.sh  -t tag -o "8.7.0-pre"  --> Passes

**Expected behavior**
Build is successful.

**System info (please complete the following information):**
Our `Dockerfile` uses `fedora:latest`
Node and CLI version: We are trying to build `8.7.0-pre`.

**Screenshots and attachments**
Fedora (Failing) full logs:
[fedora.txt](https://github.com/input-output-hk/cardano-node/files/13526298/fedora.txt)

Ubuntu (Successful) full logs:
[ubuntu.txt](https://github.com/input-output-hk/cardano-node/files/13526302/ubuntu.txt)

I found this posts that suggests that this issue is also present on Arch Linux:
https://forum.cardano.org/t/cardano-crypto-class-2-0-0-conflict-pkg-config-package-libsodium-any-not-found-in-the-pkg-config-database/56203/5

**Additional context**
N/A

**Comment by carbolymer** [comment]
```
(conflict: pkg-config package libsodium-any, not found in the pkg-config
database)
```
Seems that libsodium gets installed on fedora, but somehow is not visible for pkg-config. Maybe environment variables with paths are not configured correctly. I'll try to repro this and investigate later today.

**Comment by stefanobieler** [comment]
also on fedora facing a similar issue. when i try to build not only cardano node but any other project associated with cardano. strange too because i originally compiled my node on this machine. aside from regular system updates not sure what could of changed.


environment variables
```
LD_LIBRARY_PATH=/usr/local/lib
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```

/usr/local/lib
```
.
├── libblst.a
├── libsecp256k1.a
├── libsecp256k1.la
├── libsecp256k1.so -> libsecp256k1.so.0.0.0
├── libsecp256k1.so.0 -> libsecp256k1.so.0.0.0
├── libsecp256k1.so.0.0.0
├── libsodium.a
├── libsodium.la
├── libsodium.so -> libsodium.so.23.3.0
├── libsodium.so.23 -> libsodium.so.23.3.0
├── libsodium.so.23.3.0
└── pkgconfig
    ├── libblst.pc
    ├── libsecp256k1.pc
    └── libsodium.pc

```
versions of software.
```
❯ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
❯ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 
```

**Comment by stefanobieler** [comment]
Went to [pkg config repo](https://github.com/pkgconf/pkgconf) and check out the 2.0 tag. compiled and installed and now cardano-node compiles successfully. thank you @carbolymer for the tip

**Comment by carbolymer** [comment]
Closing then. Let me know if you need further assistance.
