### ISSUE TITLE
CAD-744 don't elide TraceLedgerReplayEvent.ReplayedBlock

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/cardano-node#562]
When the ledger snapshots on disk are old, invalid, or missing, a whole lot of blocks will need to be replayed against some older (or even the genesis) ledger state. In ouroboros-consensus, we currently trace [the following event](https://github.com/input-output-hk/ouroboros-network/blob/1a5e8d975574fd2a262c2494629fdaf1d1bd6945/ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/LgrDB.hs#L321) for *each block*:

```
-- | 'TraceReplayEvent' instantiated with additional information.
--
-- The @replayTo@ parameter is instantiated with the 'Point' of
-- the tip of the ImmutableDB.
type TraceLedgerReplayEvent blk = TraceReplayEvent (RealPoint blk) (Point blk)
```
This event has all the information needed to calculate the current progress. 

What the node currently traces:

```
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.46 UTC] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"2030400","epoch":"94"},"kind":"TraceEvent","tip":"genesis(o
rigin)"}                                                                                                                                                                                      
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.48 UTC] messages elided so far = 100  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.50 UTC] messages elided so far = 200  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.52 UTC] messages elided so far = 300  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.53 UTC] messages elided so far = 400  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.55 UTC] messages elided so far = 500  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.57 UTC] messages elided so far = 600  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.59 UTC] messages elided so far = 700  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.60 UTC] messages elided so far = 800  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.62 UTC] messages elided so far = 900  
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.64 UTC] messages elided so far = 1000 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.65 UTC] messages elided so far = 1100 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.67 UTC] messages elided so far = 1200 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.69 UTC] messages elided so far = 1300 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.71 UTC] messages elided so far = 1400 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.72 UTC] messages elided so far = 1500 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.74 UTC] messages elided so far = 1600 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.76 UTC] messages elided so far = 1700 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.78 UTC] messages elided so far = 1800 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.79 UTC] messages elided so far = 1900 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.81 UTC] messages elided so far = 2000 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.83 UTC] messages elided so far = 2100 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.84 UTC] messages elided so far = 2200 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.86 UTC] messages elided so far = 2300 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.88 UTC] messages elided so far = 2400 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.89 UTC] messages elided so far = 2500 
[desktop:cardano.node.ChainDB:Info:5] [2020-02-11 16:46:42.91 UTC] messages elided so far = 2600 
...
```

This just hides what is going on and is in this scenario, IMHO, useless.
Replaying *all the blocks in the current chain* against the genesis ledger will take quite a while (5 min? 10 min? more?). The user will have no idea what is going on and how much longer this will go on.

Can't we trace some human-friendly progress? For example: show a message after each epoch is replayed, showing epoch x of y? Or every 1000 blocks, showing block x of y replayed?

**Comment by CodiePP** [comment]
"useless"? it suppresses hundreds of messages that would otherwise appear in the logs.
sure, it can be adapted. please state your requirements.

**Comment by mrBliss** [comment]
> "useless"? it suppresses hundreds of messages that would otherwise appear in the logs.
> sure, it can be adapted. please state your requirements.

Remember @oneEdoubleD investigating all these elided messages a while ago?

I agree that tracing all of these messages would be bad, but just eliding them is also not that helpful. The user sees that messages are being traced, but they're *elided*, so hidden. That's even more frustrating. It will not be obvious to each user to scroll up and realise that the last traced message is being repeated with different parameters (even that depends on the equivalence you define for elision). Moreover, the user has no idea of the progress. As I said, this replay all the blocks in the current chain can take many minutes.

What I suggest: 

Instead of doing "elision" for `TraceLedgerReplayEvent.ReplayedBlock`, show in 5 or 10% increments. You can calculate the approximate progress by looking at:
```haskell
TraceReplayEvent (RealPoint blk) (Point blk)
```
The `RealPoint` is the replayed block and the `Point` is the final `Point` to replay to. So subtract the former's slot from the latter's slot and you have an approximation of the progress (ignoring chain density).

You can look use `ReplayFromSnapshot` or `ReplayFromGenesis`, or even the first `ReplayedBlock` message to compute the start slot.

IMO, seeing such progress is far more human-friendly :slightly_smiling_face:
