### ISSUE TITLE
Inaccurate ToObject instance for `Point blk`

### ISSUE THREAD

**Issue by intricate** [input-output-hk/cardano-node#570]
https://github.com/input-output-hk/cardano-node/blob/f1a5b69d205599ad99c07f19ed9d6cf50575564a/cardano-node/src/Cardano/Tracing/ToObjectOrphans.hs#L597-L602

This particular definition outputs a JSON object whose `"kind"` key is mapped to a value `"Tip"`. This seems incorrect as a `Point blk` is not necessarily the tip.

**Comment by kevinhammond** [comment]
Can you get someone to check this please and either clear it or fix it (should be quick)
