### ISSUE TITLE
Build failure on Ubuntu 18.04 using stack

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#571]
I tried building on Ubuntu 18.04 using stack and it fails.
```
aeson                            > [25 of 25] Compiling Data.Aeson.Encode
aeson                            > 
aeson                            > copy/register
aeson                            > Installing library in /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/aeson-1.4.2.0-8rF2ZWXkEY44oWnuVmoeBA
aeson                            > Registering library for aeson-1.4.2.0..
                       
--  While building package libsystemd-journal-1.4.4 using:
      /home/shawn/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/pkgdb --libdir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib --bindir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/bin --datadir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/share --libexecdir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/libexec --sysconfdir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/etc --docdir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/doc/libsystemd-journal-1.4.4 --htmldir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/doc/libsystemd-journal-1.4.4 --haddockdir=/home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/doc/libsystemd-journal-1.4.4 --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=hashable=hashable-1.2.7.0-ASqwrV5D8Rp79NspztLCgD --dependency=hsyslog=hsyslog-5.0.2-4YPEwpeEGKZ6PP1UUUwS4g --dependency=pipes=pipes-4.3.10-L3Z6Ybh33Ek9IuRvqza8eh --dependency=pipes-safe=pipes-safe-2.3.1-5A9QDYOug7DHQ02WZnt1Me --dependency=semigroups=semigroups-0.18.5-8pPnWqWrcWhEagTFf5Pnk2 --dependency=text=text-1.2.4.0-GrUF4lk2hk02X2GpHbr2GS --dependency=transformers=transformers-0.5.6.2 --dependency=uniplate=uniplate-1.6.12-9l9MSY5CbSuDznllPlYi4Q --dependency=unix-bytestring=unix-bytestring-0.3.7.3-6h267UVfHhj9ETGUdeUT8h --dependency=unordered-containers=unordered-containers-0.2.10.0-3WnzaWIoIVzESTPREXRwup --dependency=uuid=uuid-1.3.13-DdLTCx5E0s0ADZYFSuRt9I --dependency=vector=vector-0.12.0.3-LfvlcMFJAcY18uD1Y2O5Ig --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1
Progress 214/273

Apologies if this is an obvious problem on my end. I am new to Haskell.

stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

This is on master. Let me know if there is a particular release tag I should be using.

**Comment by shawnim** [comment]
Checked out 1.5.0 tag and it still failed with the following:

Cloning dd30455144e11efb435619383ba84ce02aee720d from https://github.com/input-output-hk/iohk-monitoring-framework
Cloning 1a258b6df7d9807d4c4ff3e99722223d31a2c320 from https://github.com/CodiePP/ekg-prometheus-adapter

Error: While constructing the build plan, the following exceptions were
encountered:

In the dependencies for ouroboros-network-0.1.0.0:
    io-sim needed, but the stack configuration has no specified version (no
           package with that name found, perhaps there is a typo in a package's
           build-depends or an omission from the stack.yaml packages list?)
needed due to cardano-node-1.5.0 -> ouroboros-network-0.1.0.0

Some different approaches to resolving this:


Plan construction failed.

**Comment by erikd** [comment]
How are you building this? What exact commands?

**Comment by shawnim** [comment]
Following the README, I did:
cd cardano-node
stack build

**Comment by Tisona** [comment]
I have the exact same issue on Ubuntu 16.04.

**Comment by Tisona** [comment]
Fixed it by adding io-sim in stack.yaml
```
- git: https://github.com/input-output-hk/ouroboros-network
    commit: 398004e1403367cc2a25c639eb6349d473e51b2d
    subdirs:
        - io-sim
        - io-sim-classes
        - network-mux
```

**Comment by erikd** [comment]
Current `master` has this, right?

https://github.com/input-output-hk/cardano-node/blob/master/stack.yaml#L123-L132

**Comment by shawnim** [comment]
I just checked out master, did a pull, and it still does not build.
kan-extensions                   > Registering library for kan-extensions-5.2..
katip                            > [4 of 5] Compiling Katip.Scribes.Handle
katip                            > [5 of 5] Compiling Katip
katip                            > copy/register
katip                            > Installing library in /home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/lib/x86_64-linux-ghc-8.6.5/katip-0.8.3.0-FgOJv9IgoEi9QrZXGFzPED
katip                            > Registering library for katip-0.8.3.0..
                       
--  While building package libsystemd-journal-1.4.4 using:
      /home/shawn/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/pkgdb --libdir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/lib --bindir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/bin --datadir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/share --libexecdir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/libexec --sysconfdir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/etc --docdir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/doc/libsystemd-journal-1.4.4 --htmldir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/doc/libsystemd-journal-1.4.4 --haddockdir=/home/shawn/.stack/snapshots/x86_64-linux/79a2576638b27e547ad18c8de262b1463fafba0f068599a8e750c9c8d95851d0/8.6.5/doc/libsystemd-journal-1.4.4 --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=hashable=hashable-1.2.7.0-ASqwrV5D8Rp79NspztLCgD --dependency=hsyslog=hsyslog-5.0.2-4YPEwpeEGKZ6PP1UUUwS4g --dependency=pipes=pipes-4.3.10-L3Z6Ybh33Ek9IuRvqza8eh --dependency=pipes-safe=pipes-safe-2.3.1-5A9QDYOug7DHQ02WZnt1Me --dependency=semigroups=semigroups-0.18.5-8pPnWqWrcWhEagTFf5Pnk2 --dependency=text=text-1.2.4.0-GrUF4lk2hk02X2GpHbr2GS --dependency=transformers=transformers-0.5.6.2 --dependency=uniplate=uniplate-1.6.12-9l9MSY5CbSuDznllPlYi4Q --dependency=unix-bytestring=unix-bytestring-0.3.7.3-6h267UVfHhj9ETGUdeUT8h --dependency=unordered-containers=unordered-containers-0.2.10.0-3WnzaWIoIVzESTPREXRwup --dependency=uuid=uuid-1.3.13-DdLTCx5E0s0ADZYFSuRt9I --dependency=vector=vector-0.12.0.3-LfvlcMFJAcY18uD1Y2O5Ig --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1
Progress 195/274

**Comment by erikd** [comment]
The part of the build logs does not seem to contain the actual cause of the build failure. It seems that the build failure occurred earlier and the bit you posted does not contain the *actual* error. Since the build logs are *huge*, please to not post the whole thing. Instead scroll back through the build log and fine the actual cause of the build error. It should not be more than 5 or 6 lines of log, and it is almost certainly due to missing development packages for C libraries. In this case, you are probably missing the `libsystemd-dev` package.

**Comment by shawnim** [comment]
Thanks for the tip! I wondered why there was not a more specific error at the end of the output. After installing libsystemd-dev it built fine. Thanks for the help!

**Comment by erikd** [comment]
Closing this.
