### ISSUE TITLE
More detailed TraceImmDBEvent and TraceVolDBEvent logging

### ISSUE THREAD

**Issue by intricate** [input-output-hk/cardano-node#576]
>Can we also pattern-match on the wrapped event and trace them too? Because now sometimes we get a whole bunch of `TraceImmDBEvent` events without any message after it. Same for `TraceVolDBEvent`.

_Originally posted by @mrBliss in https://github.com/input-output-hk/cardano-node/pull/569_

**Comment by kevinhammond** [comment]
Is this still an issue?

**Comment by mrBliss** [comment]
Yes, it still is, see
https://github.com/input-output-hk/cardano-node/blob/b4666bfb91d2ffb4f9306291c354c5a876ac2bc7/cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs#L637 and the line below.

Can somebody from the logging and monitoring team take care of this?
