### ISSUE TITLE
Chairman needs to take per-node chain density into account

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#578]
Hydra's run of chairman's cluster in https://github.com/input-output-hk/cardano-node/pull/577 exposes an undesirable laxitude of the CI check -- as long as we lose just slightly under half the blocks, the CI is green, as chairman will accept that situation.

Citing @dcoutts:
> we simply have to check that each node made at least N blocks in the chain, for an appropriate N based on K and how long we run it for

So, the upper bound for `N` for a node's block forging performance (measured in blocks) over a period of time `T` (measured in slots), with a fraction of stake `S` seems to be independent of `K` and is simply:

```
N = T / S
```

The lower reasonable bound `n` should be a reasonably high fraction of the upper bound (given that we run the network for a sufficient amount slots), and could be something like

```
n = N * 0.95
```

..where the slack would account for the initial network block lossage that used to happen due to initial connection setup & timeouts -- remember that we're linking two segments of the cluster via a proxy, so that exacerbates the problem.

**Comment by dcoutts** [comment]
It's even simpler while we're running BFT: in a run of N slots with M nodes, we expect each node to produce floor(N/M) blocks, or that -1 for startup slack.

**Comment by newhoggy** [comment]
The current status is:  We do a little bit better than what @deepfire reported, but not as much as he wants.  The testnet we create actually loses some blocks - more than we'd like - and the assertions on block count are set at a value just below the threshold that would make the tests flakey.  ie. `52` instead of `60`.

**Comment by CarlosLopezDeLara** [comment]
@deepfire is this still an issue?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open with more details.
