### ISSUE TITLE
TraceForgedInvalidBlock: extend the trace with explanation

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#579]
Hydra's run of chairman's cluster in #577 exposes a lack of information in logging of `TraceForgedInvalidBlock` -- only just the slot number is printed, but the explanation in `InvalidBlockReason blk` is omitted:

`machine# [  631.136442] 7bkh2qlp6brs3fsrnycrs64c514mcdk6-unit-script-cardano-node_-start[760]: [machine:cardano.node.Forge:Error:32] [2001-09-09 01:57:00.03 UTC] {"kind":"TraceForgedInvalidBlock","slot":31}`

We need to rectify that -- see https://github.com/input-output-hk/cardano-node/blob/4a3029572a71a7123d508a9622101f9c9920b3d2/cardano-node/src/Cardano/Tracing/ToObjectOrphans.hs#L900

**Comment by deepfire** [comment]
WIP in https://github.com/input-output-hk/cardano-node/pull/585/files, not sure about the chosen direction yet.

**Comment by deepfire** [comment]
Redid https://github.com/input-output-hk/cardano-node/pull/585 in accord with @dcoutts's suggestion.

**Comment by CodiePP** [comment]
CAD-641

**Comment by deepfire** [comment]
Closed by https://github.com/input-output-hk/cardano-node/pull/605
