### ISSUE TITLE
Poor sync time in cardano-node 1.6

### ISSUE THREAD

**Issue by karknu** [input-output-hk/cardano-node#589]
@ArturWieczorek first reported poor sync time in 1.6 but failed to reproduce it a second time.

When running chainsync towards multiple peers cardano-node will run the blockfetch protocol towards one of them. In 1.6 it has been observed that it may switch between different nodes which will dramatically increase the sync time.
A simple test, such as runing `scripts/mainnet.sh` can increase from 2h to 7h. This happens for users in Europe when they switch from using the first listed node (25ms away) to the second node (250ms away).

At the root of this is the fact that ouroboros-network currently treats all nodes as equally faraway and equally well connected.

**Comment by kevinhammond** [comment]
More recent versions of cardano-node have addressed sync times.
