### ISSUE TITLE
"Updated chain: " logs are getting too long

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-node#59]
After a while, [`Updated chain: ` logs](https://github.com/input-output-hk/cardano-node/blob/889cb13b2c42464b60f6b286eaa36ee0ddae3d30/app/Run.hs#L383) are spanning across multiple screen (wrapped).

**Comment by mrBliss** [comment]
@jbgi one possible way to solve this is to merge #61 (remove the current way of tracing the whole chain) and merge #57 (trace just the hash of tip in the trace prefix). I'm open to alternatives for #57.
