### ISSUE TITLE
Add instructions to README on how to run node with testnet and mainnet

### ISSUE THREAD

**Issue by tatyanavych** [input-output-hk/cardano-node#595]
As was fairly [pointed out on Reddit](https://www.reddit.com/r/cardano/comments/f879vw/docker_image_for_cardanonode_160_is_here/): there no instructions on
> ... how to connect the current code-base to either Byron mainnet or testnet, do you have some docs on that or is it going to be more of a trial and error type of thing?

**Comment by mark-stopka** [comment]
Would you prefer it as part of `README.md` or a separate document? Connecting my Docker images do the testnet and mainnet is my next step, so I'll be reverse-engineering the process from the [mainnet.sh](https://github.com/input-output-hk/cardano-node/blob/master/scripts/mainnet.sh) script and documenting it for myself anyway, so it's not much additional effort to make it fit for the upstream repo...
