### ISSUE TITLE
Tracing is costly

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#608]
@mrBliss reports a relatively high cost incurred by logging.

Description of his setup:

1. chain syncing between two local processes:
   > one fully-synced "server" node (nothing to do but serve blocks) and one empty "client" node (nothing to do but download blocks) 
2. log configuration from `configuration/configuration-mainnet.yaml`
3. two cases:
    - normal `cardano-node`, `50k blocks in 1 minute`
    - `cardano-node` with all tracers set to `nullTracer`: `75k blocks in 1 minute`

**Comment by deepfire** [comment]
@mrBliss, @dcoutts, how do you propose we should account for the non-framework costs of forcing the lazily-evaluated thunks of the traces?

It's pretty obvious that profiling needs to be done before any conclusions can be made, though..

**Comment by mrBliss** [comment]
> @mrBliss, @dcoutts, how do you propose we should account for the non-framework costs of forcing the lazily-evaluated thunks of the traces?
> 
> It's pretty obvious that profiling needs to be done before any conclusions can be made, though..

Most of the things that are being traced are already evaluated to (almost) normal form, at least on consensus side. Related: https://github.com/input-output-hk/ouroboros-network/issues/1386

**Comment by CodiePP** [comment]
this PR https://github.com/input-output-hk/cardano-node/pull/494 defines the set of tracers which are on per default.
the amount of logged information can be controlled by either turning on/off a tracer and setting the minSeverity filter.

**Comment by CarlosLopezDeLara** [comment]
This issue should have been closed after  https://github.com/input-output-hk/ouroboros-network/issues/1386 and https://github.com/input-output-hk/ouroboros-network/issues/1376#issuecomment-571094189
