### ISSUE TITLE
Add `SocketPath` and `GenesisFile` fields to yaml

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#611]
Adding these two fields to the config yaml file will allow a further reduction in the number of arguments necessary for certain commands in `cardano-cli`. The socket path can still be specified from the command line and will override the `SocketPath` field in the config yaml file.

**Comment by cleverca22** [comment]
i'm thinking the `GenesisFile` within the config, should be either an absolute path
or a relative path, relative to where the config is, not the current working dir
