### ISSUE TITLE
`cardano-node` should not require genesis file and genesis hash arguments

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#613]
After #611 is completed, the genesis file can be obtained from the config yaml file and therefore the genesis hash can be derived from this.

**Comment by rhyslbw** [comment]
#611 is closed. Does #648 now unblock this?

**Comment by Jimbo4350** [comment]
It wasn't blocked, however I will wait until the end of this sprint before starting on this issue.
