### ISSUE TITLE
[FR] Node Peer overview and control

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/cardano-node#616]
Shelley version of the **cardano-node** needs to address certain open issues that are behind the unsatisfactory ITNv1 performance, missing [Node Peer overview and control #883](https://github.com/input-output-hk/jormungandr/issues/883) would be example of such feature to enable Shelley mainnet pool operators to implement leader / relay topology with more trusted peers operated either by themselves or independent service operators effectively creating a Shelley block distribution CDN beneficial for leader nodes operators.

How is the p2p communication protocol planned for Shelley maintain version of the node formally specified? And does it include the properties required to enable effective peer control on both bootstrap and during runtime?

For instance Jormungandr does not support standard `--reload` functionality typically implemented in unix-principles inspired services upon receiving a `HUP` signal, does this implementation support dynamic configuration reload or does it like Jormungandr require a node restart?

**Comment by kevinhammond** [comment]
The network implementation will be completely different in the Shelley Cardano node, so we do not anticipate that performance will be the major issue that it was in ITNv1.  We will monitor this, though, and ensure that we provide the support that stakepool operators require.  For now, I have marked this as low priority.

**Comment by mark-stopka** [comment]
I still think live reload (on `HUP` signal) of network peers to be relevant for current implementation of `cardano-node`, especially considering DNS support for peers, is this going to be implemented?

**Comment by nyetwurk** [comment]
`kill -HUP` is [documented](https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/understanding-config-files.md#understanding-your-configuration-files-and-how-to-use-them):

> You can tell the node that the topology configuration file changed by sending a SIGHUP signal to the cardano-node process, e.g. pkill -HUP cardano-node. After receiving the signal, cardano-node will re-read the file and restart all dns resolution. Please note that this only applies to the topology configuration file!

but doesn't seem to be implemented that I can tell

**Comment by coot** [comment]
This is already implemented but only available for the still experimental p2p version.
