### ISSUE TITLE
Review logging configuration

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#636]
The networking team needs to review the configuration of the logging system in various files.

**Comment by karknu** [comment]
One tracer option to consider is the one for errorpolicy, it is disabled in `configuration/configuration-mainnet.yaml`. This means that events such as connections reset, network errors or unhandled exceptions aren't logged.

**Comment by CodiePP** [comment]
what is the progress with this task? may we offer our help?

**Comment by coot** [comment]
@CodiePP yes.  All the configuration files in `cardano-node` should have:
```
# Trace error policy resolution.
TraceErrorPolicy: True
```
I would even consider removing this from node options, as this allows one to make all unhandled exceptions to be silent.

**Comment by coot** [comment]
and btw way, thanks for offering help!

**Comment by coot** [comment]
Closed prematurely, there are still things we'd like to fix.

**Comment by coot** [comment]
Fixed in #732
