### ISSUE TITLE
cardano-wallet - removal

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#649]
Cardano wallet has a bug: https://github.com/input-output-hk/cardano-node/blob/3ee2d525b2bc8ba8c42d30e86d59a63dc508ad48/cardano-node/src/Cardano/Wallet/Client.hs#L115
The arguments of `nodeToClientProtocols` should be swapped.

But the demo is not used, the wallet team is working on a proper implementation and I don't think they need it.

**Comment by Jimbo4350** [comment]
@coot can you confirm this with @KtorZ

**Comment by coot** [comment]
^ confirmed.

**Comment by dcoutts** [comment]
This is done and merged.
