### ISSUE TITLE
CAD-721 TraceLabelPeer messages are cluttering the log output

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#650]
The console log output (after starting node on `master` branch, `commit 1f022ec185`) is cluttered with messages:

> [artur-de:cardano.node.BlockFetchDecision:Info:46] [2020-03-09 12:46:52.36 UTC] {"length":"1","kind":"TraceLabelPeer"}
> [artur-de:cardano.node.BlockFetchDecision:Info:46] [2020-03-09 12:46:52.36 UTC] {"length":"1","kind":"TraceLabelPeer"}
> [artur-de:cardano.node.BlockFetchDecision:Info:46] [2020-03-09 12:46:52.36 UTC] {"length":"1","kind":"TraceLabelPeer"}
> [artur-de:cardano.node.BlockFetchDecision:Info:46] [2020-03-09 12:46:52.36 UTC] {"length":"1","kind":"TraceLabelPeer"}

I didn't notice those messages for 1.6.0 and earlier versions.

**Comment by CodiePP** [comment]
this looks like wrong context name, so the filters do not apply.

**Comment by coot** [comment]
Just to confirm, the node downloads blocks as normal, right?

**Comment by ArturWieczorek** [comment]
> Just to confirm, the node downloads blocks as normal, right?

@coot Yes, that is correct.
