### ISSUE TITLE
Errors after shutting down node

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node#651]
Happens on `master` branch: commit 1f022ec185e77541

**Edit:** This does not happen every single time so it might be hard to reproduce, however I run into it 3 times already

when I `ctrl+C` node process - instead of seeing `shutting down..` message as it was before, I see some consensus related errors now:

> [artur-de:cardano.node.ChainDB.text:Notice:36] [2020-03-09 13:09:54.30 UTC] [5182538@30683] Chain extended, new tip: (Point 30684, 9ef3840a55939880)
> cardano-node: ExceptionInLinkedThread "ThreadId 40" (ImmDbFailure (FileSystemError (FsError {fsErrorType = FsIllegalOperation, fsErrorPath = /home/artur/Projects/Node_Master/cardano-node/state-node-staging/db-staging/immutable/00001.epoch, fsErrorString = "illegal operation", fsErrorNo = Nothing, fsErrorStack = [("ioToFsError",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.FS.IO", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/IO.hs", srcLocStartLine = 85, srcLocStartCol = 41, srcLocEndLine = 85, srcLocEndCol = 68}),("handleError",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.FS.IO", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/IO.hs", srcLocStartLine = 81, srcLocStartCol = 23, srcLocEndLine = 81, srcLocEndCol = 38}),("rethrowFsError",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.FS.IO", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/IO.hs", srcLocStartLine = 53, srcLocStartCol = 39, srcLocEndLine = 53, srcLocEndCol = 56}),("hPutSome",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.FS.API", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/API.hs", srcLocStartLine = 97, srcLocStartCol = 5, srcLocEndLine = 97, srcLocEndCol = 13}),("hPutAllStrict",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.FS.CRC", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/CRC.hs", srcLocStartLine = 69, srcLocStartCol = 20, srcLocEndLine = 69, srcLocEndCol = 47}),("hPutAllCRC",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.FS.CRC", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/CRC.hs", srcLocStartLine = 80, srcLocStartCol = 19, srcLocEndLine = 80, srcLocEndCol = 37}),("hPutCRC",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.ImmutableDB.Impl", srcLocFile = "src/Ouroboros/Consensus/Storage/ImmutableDB/Impl.hs", srcLocStartLine = 753, srcLocStartCol = 29, srcLocEndLine = 753, srcLocEndCol = 73}),("appendEpochSlot",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.ImmutableDB.Impl", srcLocFile = "src/Ouroboros/Consensus/Storage/ImmutableDB/Impl.hs", srcLocStartLine = 672, srcLocStartCol = 7, srcLocEndLine = 673, srcLocEndCol = 55}),("appendBlockImpl",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.ImmutableDB.Impl", srcLocFile = "src/Ouroboros/Consensus/Storage/ImmutableDB/Impl.hs", srcLocStartLine = 227, srcLocStartCol = 32, srcLocEndLine = 227, srcLocEndCol = 64}),("appendBlock",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.ImmutableDB.API", srcLocFile = "src/Ouroboros/Consensus/Storage/ImmutableDB/API.hs", srcLocStartLine = 143, srcLocStartCol = 5, srcLocEndLine = 143, srcLocEndCol = 16}),("appendBlock",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.ChainDB.Impl.Background", srcLocFile = "src/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs", srcLocStartLine = 161, srcLocStartCol = 9, srcLocEndLine = 161, srcLocEndCol = 39}),("copyToImmDB",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-5K7KUu5k5RJBZ5Ac45HrdN", srcLocModule = "Ouroboros.Consensus.Storage.ChainDB.Impl.Background", srcLocFile = "src/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs", srcLocStartLine = 251, srcLocStartCol = 7, srcLocEndLine = 251, srcLocEndCol = 22})], fsLimitation = False})))
> [artur-de:cardano.node.BlockFetchDecision:Info:46] [2020-03-09 13:09:54.30 UTC] {"length":"2","kind":"TraceLabelPeer"}

**Comment by CodiePP** [comment]
@edsko might be interested to see this error message.

**Comment by edsko** [comment]
cc @mrBliss .
