### ISSUE TITLE
CAD-710 All tracers are transformed to structured output

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#675]
Currently, there is a number of traces in `cardano-node/src/Cardano/Tracing/Tracers.hs`, that are simply output using `showTracing`, which means their structure is flattened.

We should go over all traces and ensure they have a proper structured conduit.

**Comment by deepfire** [comment]
CAD-710 is a sister issue, that seeks to ensure that all structured traces have a human-readable presentation -- basically a properly handled `TextualRepresentation` case in the corresponding `Transformable` instance.

**Comment by CarlosLopezDeLara** [comment]
Resolved by https://github.com/input-output-hk/cardano-node/pull/760
