### ISSUE TITLE
LiveView not working on windows?

### ISSUE THREAD

**Issue by Anviking** [input-output-hk/cardano-node#692]
I'm trying the [windows build](https://hydra.iohk.io/build/2025521) and running

```bash
./cardano-node.exe run --database-path db --topology configuration/mainnet-topology.json --socket-path socket/mainnet-socket --config "configuration/configuration-mainnet.yaml" --port 7776
```
But I get no GUI nor _any_ terminal output. Is this expected/known?

I do see logs written to disk, and high CPU / memory usage, so it seems to be working otherwise.

**Comment by dcoutts** [comment]
I think the live view is not expected to work on Windows, right @CodiePP ?

**Comment by CodiePP** [comment]
> I think the live view is not expected to work on Windows, right @CodiePP ?

no, unfortunately not. the "brick" library we are using is only available on Linux and Mac (and other Unizes).
we are working on a webified version "RTview" that is then available on all platforms.
