### ISSUE TITLE
Error building katip-0.8.3.0

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/cardano-node#703]
OS : ubuntu 19.10
cabal version : 3.0.0.0
ghc version : 8.6.5

Hello, I'm facing the following error trying to build the cardano-node 1.8.0.
The error is also described in issue #661 that has been closed, but I didn't find any hint on how to solve it.
Can you give me a suggestion abt how to solve it?
Thank you in advance

~/haskell/cardano-haskell (master) : cabal build cardano-node -j24
Build profile: -w ghc-8.6.5 -O0
In order, the following will be built (use -v for more details):

katip-0.8.3.0 (lib) (requires build)
iohk-monitoring-0.1.10.1 (lib) (first run)
lobemo-scribe-systemd-0.1.0.0 (lib) (first run)
lobemo-backend-monitoring-0.1.0.0 (lib) (first run)
lobemo-backend-ekg-0.1.0.1 (lib) (first run)
lobemo-backend-aggregation-0.1.0.0 (lib) (first run)
cardano-config-0.1.0.0 (lib) (first run)
cardano-tx-generator-1.7.0 (lib) (first run)
cardano-node-1.8.0 (lib) (first run)
cardano-node-1.8.0 (exe:chairman) (first run)
cardano-node-1.8.0 (exe:cardano-node) (first run)
cardano-node-1.8.0 (exe:cardano-cli) (first run)
Starting katip-0.8.3.0 (lib)
Building katip-0.8.3.0 (lib)
Failed to build katip-0.8.3.0.
Build log (
/home/ubuntu/.cabal/logs/ghc-8.6.5/katip-0.8.3.0-8017431350051aea179fbb4d8d73e1e28bf6c1b4d852420a0ef5a7da9d4e43fc.log
):
Configuring library for katip-0.8.3.0..
Preprocessing library for katip-0.8.3.0..
Building library for katip-0.8.3.0..
[1 of 5] Compiling Katip.Core ( src/Katip/Core.hs, dist/build/Katip/Core.o )

src/Katip/Core.hs:904:3: error:
‘askUnliftIO’ is not a (visible) method of class ‘MonadUnliftIO’
|
904 | askUnliftIO = KatipT $
| ^^^^^^^^^^^
cabal: Failed to build katip-0.8.3.0 (which is required by exe:chairman from
cardano-node-1.8.0, exe:cardano-node from cardano-node-1.8.0 and others). See
the build log above for details.

Log file contains the same details.

**Comment by coot** [comment]
Maybe try to restrict `unliftio-core` to version `<2.0.0`; You can add this to your `cabal.project.local` file:
```
constraints:
  unliftio-core < 0.2.0.0
```

**Comment by feqifei** [comment]
> Maybe try to restrict `unliftio-core` to version `<2.0.0`; You can add this to your `cabal.project.local` file:
> 
> ```
> constraints:
>   unliftio-core < 0.2.0.0
> ```

it works, thank you!
Now I'm facing another problem, 
 Ambiguous occurrence ‘canonicalDecodePretty’

but I will dig a little bit and in case I'll open another issue.

Thanks!

**Comment by coot** [comment]
The repo builds for me without any modifications using `cabal`; are you using `cabal-install` >= `3.0.0.0`?, if not please update.

**Comment by feqifei** [comment]
> The repo builds for me without any modifications using `cabal`; are you using `cabal-install` >= `3.0.0.0`?, if not please upgrade it.

yes, same version 3.0.0.0
I'm following its readme doc: https://github.com/input-output-hk/cardano-haskell
Did you pre-install any cabal library before running the cabal build all ?
