### ISSUE TITLE
Error building cardano-config-0.1.0.0

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/cardano-node#704]
OS : ubuntu 19.10
cabal version : 3.0.0.0
ghc version : 8.6.5

Hello, I'm facing the following error trying to build the cardano-node 1.8.0.

~/haskell/cardano-haskell (master) : cabal build cardano-node -j24
Build profile: -w ghc-8.6.5 -O0
In order, the following will be built (use -v for more details):
 - cardano-config-0.1.0.0 (lib) (first run)
 - cardano-tx-generator-1.7.0 (lib) (first run)
 - cardano-node-1.8.0 (lib) (first run)
 - cardano-node-1.8.0 (exe:chairman) (first run)
 - cardano-node-1.8.0 (exe:cardano-node) (first run)
 - cardano-node-1.8.0 (exe:cardano-cli) (first run)
Preprocessing library for cardano-config-0.1.0.0..
Building library for cardano-config-0.1.0.0..
[9 of 9] Compiling Cardano.Config.Protocol ( src/Cardano/Config/Protocol.hs, /home/ubuntu/haskell/cardano-haskell/dist-newstyle/build/x86_64-linux/ghc-8.6.5/cardano-config-0.1.0.0/noopt/build/Cardano/Config/Protocol.o )

src/Cardano/Config/Protocol.hs:249:28: error:
    Ambiguous occurrence ‘canonicalDecodePretty’
    It could refer to either ‘Cardano.Prelude.canonicalDecodePretty’,
                             imported from ‘Cardano.Prelude’ at src/Cardano/Config/Protocol.hs:21:1-32
                             (and originally defined in ‘cardano-prelude-0.1.0.0:Cardano.Prelude.Json.Canonical’)
                          or ‘Cardano.Config.Protocol.canonicalDecodePretty’,
                             defined at src/Cardano/Config/Protocol.hs:269:1
    |
249 |                          $ canonicalDecodePretty delegCertFileBytes
    |                            ^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build cardano-config-0.1.0.0 (which is required by
exe:chairman from cardano-node-1.8.0, exe:cardano-node from cardano-node-1.8.0
and others).

Any suggestion?
Thanks in advance

**Comment by erikd** [comment]
Hour are you building this? That is the current git revision? This builds correct for me at current `HEAD` which is commit `3abc24a1b5372b79b69c6cad036969f9fc45cd2c` .

**Comment by feqifei** [comment]
3abc24a1b5372b79b69c6cad036969f9fc45cd2c, yes, the same

**Comment by erikd** [comment]
So how are you building this?

**Comment by feqifei** [comment]
I'm following the README.md of the top level repository https://github.com/input-output-hk/cardano-haskell.
Additional  actions I made that are not listed in the readme were:
1. I added cardano-node/cardano-tx-generator package in the cabal.project file because I received a missing package error when I execute the command: cabal configure --with-compiler ghc-8.6.5 -O0
2.  I added constraints: unliftio-core < 0.2.0.0 in cabal.project.local because I was facing issue #703

**Comment by coot** [comment]
> I'm following the README.md of the top level repository https://github.com/input-output-hk/cardano-haskell.
Does it mean you build it from `cardano-haskell` directory?  It's better to just build from within `cardano-node` - this should work.  `cardano-haskell` is for development only, and it is not guaranteed to build without significant changes at times.

**Comment by feqifei** [comment]
> > I'm following the README.md of the top level repository https://github.com/input-output-hk/cardano-haskell.
> 
> Does it mean you build it from `cardano-haskell` directory? It's better to just build from within `cardano-node` - this should work. `cardano-haskell` is for development only, and it is not guaranteed to build without significant changes at times.

ok, I will try it. Thank you!

**Comment by dcoutts** [comment]
I have updated the `cardano-haskell` readme to clarify that it is only intended for developers working on the components, and it is not intended to provide reproducible builds, and give a pointer to what to use to build particular stable releases.
