### ISSUE TITLE
Fails to build on ubuntu

### ISSUE THREAD

**Issue by Oqulent** [input-output-hk/cardano-node#715]
The node fails to build with stack on ubuntu 18.04

....Installing library in /home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/lib/x86_64-linux-ghc-8.6.5/statistics-0.15.0.0-8LRpzeoHiRG4u6FgAjrxbu
statistics                       
> Registering library for statistics-0.15.0.0.
--  While building package libsystemd-journal-1.4.4 using:
      /home/user/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/pkgdb --libdir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/lib --bindir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/bin --datadir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/share --libexecdir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/libexec --sysconfdir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/etc --docdir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/doc/libsystemd-journal-1.4.4 --htmldir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/doc/libsystemd-journal-1.4.4 --haddockdir=/home/user/.stack/snapshots/x86_64-linux/fa0ca9e3abec1dfd7d353a90eebe68eb44f3c160771267c794794f46e65b38e3/8.6.5/doc/libsystemd-journal-1.4.4 --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=hashable=hashable-1.2.7.0-ASqwrV5D8Rp79NspztLCgD --dependency=hsyslog=hsyslog-5.0.2-4YPEwpeEGKZ6PP1UUUwS4g --dependency=pipes=pipes-4.3.10-L3Z6Ybh33Ek9IuRvqza8eh --dependency=pipes-safe=pipes-safe-2.3.1-5A9QDYOug7DHQ02WZnt1Me --dependency=semigroups=semigroups-0.18.5-8pPnWqWrcWhEagTFf5Pnk2 --dependency=text=text-1.2.4.0-GrUF4lk2hk02X2GpHbr2GS --dependency=transformers=transformers-0.5.6.2 --dependency=uniplate=uniplate-1.6.12-9l9MSY5CbSuDznllPlYi4Q --dependency=unix-bytestring=unix-bytestring-0.3.7.3-6h267UVfHhj9ETGUdeUT8h --dependency=unordered-containers=unordered-containers-0.2.10.0-3WnzaWIoIVzESTPREXRwup --dependency=uuid=uuid-1.3.13-DdLTCx5E0s0ADZYFSuRt9I --dependency=vector=vector-0.12.0.3-LfvlcMFJAcY18uD1Y2O5Ig --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

**Comment by erikd** [comment]
You don't say how you are building this, which makes helping you far more difficult.

I do however see:
```
 While building package libsystemd-journal-1.4.4 using:
```
which suggests that the `libsystemd-dev` package is not installed.

**Comment by Oqulent** [comment]
Thanks. this resolved the issue.

**Comment by erikd** [comment]
We are working on providing better build/install docs.
