### ISSUE TITLE
Improve build/install docs

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#716]
The current (about to be merged) Readme contains build and running instructions. Since the node is so complex it would be better to spit the build docs out into a separate document.

Once that is done:

* It should suggest Nix instead of raw machine (has a higher likelihood of success for non-Haskell-devs)
* Must include a list of system libs that need to be installed first (eg libsystemd-dev).
* It should suggest `cabal` over `stack` because `cabal` gives better error messages about missing system libs.

**Comment by Jimbo4350** [comment]
I think this has been achieved with `/cardano-node/doc/getting-started/install.md`.
