### ISSUE TITLE
Submitted tx on cardano-node testnet is not propagated

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/cardano-node#720]
Pls note transaction is submitted via `cardano-wallet`.
`cardano-node 1.8.0`

**To reproduce:**
 - start cardano-node testnet
```
cd cardano-node/ 
git fetch --tags && git checkout tags/1.8.0
nix-build -A scripts.testnet.node -o testnet-node-local && ./testnet-node-local
```
 - start `cardano-wallet`
 - restore a wallet and submit transaction.
 - transaction lands in mempool
 - in the log there is:
cardano-node: [node.log](https://github.com/input-output-hk/cardano-node/files/4386336/node.log)
relay: [reject.log](https://github.com/input-output-hk/cardano-node/files/4386524/reject.log)

**Current result:**
 - transaction is infinitely `pending` on the wallet backend
 - transaction never appears on the testnet explorer: http://byron-testnet-develop-explorer.s3-website-ap-southeast-2.amazonaws.com/en/no-search-results/?query=3f9fbbe6f7515a9da91fb13b7623c09c65d4808219149d0780f0ec8083ee477d

**Expected result:**
 - transaction should be submitted and propagated successfuly

 <details>
<summary>Cardano-wallet requests</summary>

Start wallet:
```
cardano-wallet-byron serve --node-socket ~/wb/cardano-node/state-node-testnet/node.socket --testnet /nix/store/7106qjwral616j6p5049m7hhi5ih0r33-testnet-genesis.json --database ./testnet
```

Restore wallet:
```
curl  -vX POST http://localhost:8090/v2/byron-wallets \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"style": "random",
"name": "Byron",
"mnemonic_sentence": ["recycle","august","horse","awesome","shuffle","agent","almost","cheap","fury","speak","duty","enemy"],
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
Submit tx:
```
curl  -vX POST http://localhost:8090/v2/byron-wallets/d3358ac0fc699784af021710e7aba2a3e31fbbd1/transactions \
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
	"payments": [
		{
			"address": "37btjrVyb4KFcfEEYyBU8j4VazP5he8iktF5uyD95avRpUHU6aWuLhuhGMmyFiJjtinJQPSjgGmh5w8qmuxDpHjK2JmCnPALuA4dyUkMpHF5Rf4PBd",
			"amount": {
				"quantity": 40,
				"unit": "lovelace"
			}
		}
		],
	"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
 </details>

**Comment by dcoutts** [comment]
@piotr-iohk if you want to put details here, include the local node log, and the relay log when you get it.

**Comment by piotr-iohk** [comment]
This issue can be closed. It is no longer seen since upgrading cardano-node relays to 1.9.3.
