### ISSUE TITLE
Inconsistency in rendering of tx ids in logs

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-node#721]
In some log messages we get:
```
tx: Tx 3f9fbbe6f7515a9d
```
e.g.
```
{"kind":"TraceMempoolAddedTx","txAdded":"tx: Tx 3f9fbbe6f7515a9d with inputs [TxInUtxo b6559d0a #1], outputs: [TxOut 1 lovelace -> 37btjrVyb4KFcfEEYyBU8j4VazP5he8iktF5uyD95avRpUHU6aWuLhuhGMmyFiJjtinJQPSjgGmh5w8qmuxDpHjK2JmCnPALuA4dyUkMpHF5Rf4PBd, TxOut 3276763 lovelace -> KjgoiXJS2coaswHQPmK6sKrmLwH71rLdqXyJ2yuNB83K1Zn4p32MPRBaR5jZV631TnZvCZUyQ1JSHndFZpqtk7Jixcw3w1RtTn6GyUbfmyfV]\nwitnesses: [\n    VKWitness: key = pub:514f62a3, key hash = 9f3c639f, sig = <signature>\n]","mempoolSize":"MempoolSize {msNumTxs = 1, msNumBytes = 359}"}
```

But in other cases we get a much shorter form
```
txid:3f9fbbe6
```
as in
```
{"kind":"TraceTxSubmissionOutboundRecvMsgRequestTxs","txIds":"[txid: txid:3f9fbbe6]"}
```
But also notice the weird duplication here `"txIds":"[txid: txid:`. This should ideally be rendered as an actual JSON structure, not a string containing Haskell rendering. So it should be `"txIds":["3f9fbbe6"]`.

We should make the txid rendering consistent, and always the same length. I think 8 chars is probably enough. This makes it possible for people to search the logs properly to match up occurrences of txs.

**Comment by dcoutts** [comment]
The examples in this ticket come from #720

**Comment by mrBliss** [comment]
I suspect this is because the trace formatters are using `condense`, which is an *internal* method of consensus that we use for readable test output. It is not meant to be used outside of consensus, but I think it is being (ab)used by the tracers.

The code in `ouroboros-consensus` that probably caused the `txid: `s:
https://github.com/input-output-hk/ouroboros-network/blob/e65152888b0a6c24c68587992b03dfdd85258b3f/ouroboros-consensus-byron/src/Ouroboros/Consensus/Byron/Ledger/Orphans.hs#L111
https://github.com/input-output-hk/ouroboros-network/blob/e65152888b0a6c24c68587992b03dfdd85258b3f/ouroboros-consensus-byron/src/Ouroboros/Consensus/Byron/Ledger/Mempool.hs#L190

**Comment by dcoutts** [comment]
Agreed re use of `Condense`.

Currently we have a mass of such constraints:
```
type TraceConstraints blk =
    ( Condense blk
    , Condense [blk]
    , Condense (Header blk)
    , Condense (HeaderHash blk)
    , Condense (GenTx blk)
    , Condense (TxId (GenTx blk))
    , HasTxs blk
    , HasTxId (GenTx blk)
    , Show (ApplyTxErr blk)
    , Show (GenTx blk)
    , Show (GenTxId blk)
    , Show blk
    , Show (Header blk)
    , Show (TxId (GenTx blk))
    , ToObject (GenTx blk)
    , ToJSON   (TxId (GenTx blk))
    , ToObject (LedgerError blk)
    , ToObject (ValidationErr (BlockProtocol blk))
    )
```
I suggest we aim to prune that down to:
```
type TraceConstraints blk =
    ( HasTxs blk
    , HasTxId (GenTx blk)
    , ToObject blk
    , ToObject (Header blk)
    , ToJSON (HeaderHash blk)
    , ToObject (GenTx blk)
    , ToJSON (TxId (GenTx blk))
    , ToObject (ApplyTxErr blk)
    , ToObject (LedgerError blk)
    , ToObject (ValidationErr (BlockProtocol blk))
    )
```
And instances used and provided to fit that (probably missing some details, but you get the idea).

**Comment by deepfire** [comment]
@dcoutts, @mrBliss, I've resurrected (probably not entirely) a PR from the past, that was aiming to have a proper solution to the problem of lack of abstraction & hash rendering: https://github.com/input-output-hk/cardano-node/pull/851

I've mainly did it to facilitate a discussion -- not hell-bent on a particular implementation etc.

**Comment by CarlosLopezDeLara** [comment]
Resolved by https://github.com/input-output-hk/cardano-node/pull/3429
