### ISSUE TITLE
Cardano-Node:1.9.1 syncs slowly on Windows

### ISSUE THREAD

**Issue by oneEdoubleD** [input-output-hk/cardano-node#736]
`cardano-node:1.9.1` is syncing slowly on Windows. There has been a wide range of reported times for a complete sync of `staging` which is > 180 epochs. Reports range from 2 hours to 5 hours. 

@kevinhammond -> 2h (i5-3470 3.2GHz, 8GB RAM, Windows 10)
@ArturWieczorek -> 5h (AMD Ryzen 5 2600, 4GB RAM, VM Windows 10 (1 Core))
@oneEdoubleD  -> 5h (i5-7300u @ 2.60GHz, 8GB RAM, Windows 10)

This is completely different to Linux where we have seen a 45 minute sync (i7, 8GB RAM) with `-n4` or, more commonly, 1-1.5 hour syncs. I'll update this issue with the results of the Daedalus integration testing once it's completed. Also, one possible factor for the slower syncing speeds today, is that new relays were being added which could have caused sync speed instability.

**Comment by kevinhammond** [comment]
My fast sync was with -N4.  -N2 is slower, as you'd expect.  Interestingly, I was seeing about 7GB memory usage after an overnight run.

Below is a similar result from an -N2 run. After about 5 hours, the memory usage has reached 5GB (working set).  I think the system is now synced (network and disk traffic has dropped).

![Image](https://user-images.githubusercontent.com/12563287/77939263-d1536180-72ae-11ea-95b5-3511a0d02572.jpeg)

**Comment by oneEdoubleD** [comment]
Our first port of call is to investigate the possible space leaks. This requires a profiled build but I'm unable to build on Windows using Stack at the moment (cabal project dependencies). 

@kevinhammond If you have a working `stack` set-up for Windows could you share it with me? Or submit a PR and I'll review! It takes _hours_ to build on my machine and when I make a change it unregisters > 100 dependencies, so my debug cycle is almost an entire working day per change...

**Comment by oneEdoubleD** [comment]
We've seen significant improvements to Windows sync speeds since this issue was first open. As we're releasing 1.10.1 which includes these improvements I'm going to close the issue. We will no doubt still see some improvements as we go on!
