### ISSUE TITLE
Node client count metric

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/cardano-node#753]
Currently, node does not appear to have a connected client count metric to indicate how many clients the node is actively serving blocks to.  The closest available metric appears to be: 

```
cardano_node_BlockFetchDecision_peers_connectedPeers_int
```

However, this only yields a producer  peer count.  Currently, the client count load on a node is being estimated by TCP conn count on that node server.  A metric providing a real-time client count would be more accurate to have.

**Comment by ThaiTheo** [comment]
I don't think this should have the label 'networking' instead I suggest it gets the label 'logging and monitoring'.
This metric is available in LiveView but not in SimpleView.

**Comment by coot** [comment]
The `networking` label indicates that it's a task for the networking team.  `logging and monitoring` label explains that it's for logging and monitoring system.  These labels are probably skewed by the developers perspective, and not the general audience that tries to follow issues.

**Comment by boli** [comment]
I dont even have this 

>cardano_node_BlockFetchDecision_peers_connectedPeers_int

what do i need to turn on in my config to get it in the supplied metrics?

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open with more details.
