### ISSUE TITLE
Creating Named Pipe on Windows

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#754]
[Freeze after restart.  https://iohk.zendesk.com/agent/tickets/92048
[logs-2020-04-02T085736.0128Z.zip](https://github.com/input-output-hk/cardano-node/files/4423237/logs-2020-04-02T085736.0128Z.zip)

Your logs show an error creating the named pipe with the message a required privilege is not held by the client. Our assumption is this is a system on a windows domain with group policy settings that limit the named pipes that can be accessed. Some more details can be found in this article: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-named-pipes-that-can-be-accessed-anonymously

If you have administrator access, you could try the following:

Go to Control Panel | Administrative Tools | Local Security Policy | Local Policies | Security Options.

Double-click “Network access: Named Pipes that can be accessed anonymously" from the Policy list.

Add: cardano-node-mainnet_flight to the list. Click Apply.

Click OK.

Re-run Daedalus

Note that each environment will have a different named pipe, so with the mainnet installer you would need to add cardano-node-mainnet and testnet would need cardano-node-testnet when those are released in the future.

**Comment by kevinhammond** [comment]
Also https://iohk.zendesk.com/agent/tickets/91993

**Comment by dorin100** [comment]
The user that reported this in https://iohk.zendesk.com/agent/tickets/91993 was using an unsupported version of Windows (windows 7).

**Comment by coot** [comment]
@kevinhammond if so I think we can close it, please re-open if you don't agree.
