### ISSUE TITLE
Node not Syncing

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#755]
The node is not syncing even after deletion and restart.  Further investigation is needed.

https://iohk.zendesk.com/agent/tickets/92014

**Comment by islishude** [comment]
met this issue with node 1.8.0/1.9.2/1.9.3,and no exception prints.

**Comment by islishude** [comment]
HI,could anyone fix it?Out nodes was stuck many times.

<img width="1792" alt="截屏2020-04-07 上午6 30 06" src="https://user-images.githubusercontent.com/24730006/78611304-3acc0500-7899-11ea-9aab-d21420ce703b.png">

**Comment by mrBliss** [comment]
That screenshot shows that the tip of your chain is at slot 3998783. Wasn't that simply the tip of *the* blockchain at the time of taking the screenshot? In other words: your node is *fully synced* and will only receive a new block when one is produce by the network, i.e., once every 20 seconds.

**Comment by islishude** [comment]
@mrBliss I'm sure that no new block receives,and when I restart node,it starts receiving new blocks.

**Comment by ArturWieczorek** [comment]
Can't reproduce it, asked other QEs - they also didn't experience such problems.
