### ISSUE TITLE
Node Stuck with Lost Connection Message (Windows NTP Issue)

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#756]
This could be an NTP issue.

https://iohk.zendesk.com/agent/tickets/92052

**Comment by coot** [comment]
It seems the ntp client run just fine.  It was trigger by the user every few minutes, and everytime it returned successfully (the `BothSucceded` means that queries over `ipv4` and `ipv6` returned successfully):

```
[cardano-wallet.api-server:Info:261523] [2020-04-02 10:44:49.10 UTC] [RequestId 20138] [GET] /v2/network/clock
[cardano-wallet.ntp-client:Info:16] [2020-04-02 10:44:49.86 UTC] ntp client run protocol results: BothSucceded [NtpOffset {getNtpOffset = Microsecond (-1057145)},NtpOffset {getNtpOffset = Microsecond (-1057056)},NtpOffset {getNtpOffset = Microsecond (-1056389)},NtpOffset {getNtpOffset = Microsecond (-1055894)},NtpOffset {getNtpOffset = Microsecond (-1058039)},NtpOffset {getNtpOffset = Microsecond (-1051536)}]
[cardano-wallet.ntp-client:Info:16] [2020-04-02 10:44:49.86 UTC] ntp client gives result of NtpDrift (NtpOffset {getNtpOffset = Microsecond (-1058039)})
```

However, the logs contain these warnings:
```
[cardano-wallet.api-server:Info:260337] [2020-04-02 10:39:00.05 UTC] [RequestId 20047] [GET] /v2/network/information
[cardano-wallet.api-server:Warning:260337] [2020-04-02 10:39:30.05 UTC] [RequestId 20047] 503 Service Unavailable in 30.0020016s
```
Which are surrounded by quite a few 
```
[cardano-wallet.api-server:Info:255096] [2020-04-02 10:15:44.05 UTC] [RequestId 19646] [GET] /v2/network/information
[cardano-wallet.api-server:Info:255096] [2020-04-02 10:15:44.05 UTC] [RequestId 19646] 200 OK in 0.003989s
```
I am not sure what that means, @KtorZ do you recognize theses messages?

**Comment by KtorZ** [comment]
Perhaps the wallet server isn't waiting "long enough" for the check to resolve? Seems like the request is failing exactly 30 seconds after it was received, which is an oddly round value :) 

I'll check tomorrow what could be the root cause. If the ntp-client is however succeeding, it could be that the api server and the ntp client both use a different timeout value, which is unfortunate.

**Comment by kevinhammond** [comment]
Is this still live?

**Comment by CarlosLopezDeLara** [comment]
Solved. https://iohk.zendesk.com/agent/tickets/92052
