### ISSUE TITLE
Memory leak in `cardano-node` on Windows

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#769]

**Comment by kevinhammond** [comment]
This is connected to #736

**Comment by coot** [comment]
PRs:

* https://github.com/input-output-hk/cardano-node/pull/762
* https://github.com/input-output-hk/ouroboros-network/pull/1902
* https://github.com/input-output-hk/cardano-base/pull/89 (not  necessary, but it helped in some explorations).

**Comment by coot** [comment]
We discovered two issues here:

* memory leak of `PINNED` data, which is fixed in input-output-hk/ouroboros-network#1902
* very interesting unfortunate interaction between over-performing network code and gc. The heart of the problem is that the networking code on Windows will create a thread every time it reads from the network. If the network and operates to fast, the created threads are not timely gc-ed.

**Comment by coot** [comment]
Fixed in #788
