### ISSUE TITLE
Obtaining Sync Percentage Value

### ISSUE THREAD

**Issue by Mercurial** [input-output-hk/cardano-node#771]
Hi Guys, I'm trying to write a software that integrates with the cardano node but I have no details on how to get the sync percent value so I will know when to interact with the blockchain.

Thanks!

**Comment by erikd** [comment]
Getting this directly from the node is currently not really possible, but is definitely possible with [cardabo-db-sync](https://github.com/input-output-hk/cardano-db-sync) where it would simply be an SQL query.

**Comment by erikd** [comment]
Querying the `db-sync` database, the slot number of the most recent slot added to the database can be obtained using:
```
select slot_no from block where block_no is not null
    order by block_no desc limit 1 ;
```
The current slot (possibly not in the database) can be calculated using:
```
select extract(epoch from (select now() - start_time from meta)) * 1000 /
    slot_duration from meta ;
```

**Comment by Mercurial** [comment]
Thank you, but I also just found out that Cardano Wallet has a  /v2/network/information API that provides the following information that I need. For example

```
{
  "network_tip": {
    "epoch_number": 185,
    "slot_number": 12505
  },
  "node_tip": {
    "height": {
      "quantity": 5032,
      "unit": "block"
    },
    "epoch_number": 0,
    "slot_number": 5031
  },
  "sync_progress": {
    "status": "syncing",
    "progress": {
      "quantity": 0.13,
      "unit": "percent"
    }
  },
  "next_epoch": {
    "epoch_start_time": "2020-04-10T21:44:51Z",
    "epoch_number": 186
  }
}
```
