### ISSUE TITLE
shelley-testnet-live.sh  - 3some Nodes stopped working

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#786]
Hi,

the 3node testcluster stopped working, high cpu usage and no more blocks generated. I got this error in the logs:

![image](https://user-images.githubusercontent.com/47434720/79077207-13918f80-7d00-11ea-8f2b-4836c558962e.png)

I deleted the db-0, db-1 and db-2 subfolder and tried again, then i got these errors:

![image](https://user-images.githubusercontent.com/47434720/79077220-2a37e680-7d00-11ea-8f1a-ad6bc4c1a68a.png)

I then deleted the content of the genesis folder and startet over again, now the node are running normal and the blocks a rolling again.  I can provide the logfiles if you need them.

Thanks a lot!

**Comment by kevinhammond** [comment]
I think we can close this?
