### ISSUE TITLE
Confusing build instructions for Cardano node

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-node#841]
The build instructions in https://github.com/input-output-hk/cardano-node/blob/master/README.md are incomplete. However the file https://github.com/input-output-hk/cardano-node/blob/master/doc/building-running.md seems to contain complete instructions for Centos 8. The location of installation instructions need to easy to find for the uninitiated not requiring me to poke around the repository to find them.

**Comment by kevinhammond** [comment]
Can we check that this is fixed in the recent changes, please.

**Comment by Jimbo4350** [comment]
This has been rectified with the various docs in `doc/getting-started/`
