### ISSUE TITLE
Bad constant value for epochSlots

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#848]
These two lines are correct for mainnet and stagenet but is, in general, incorrect:

https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Tracing/Tracers.hs#L352

https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/src/Cardano/CLI/Ops.hs#L176

These should be fixed sooner rather than later.

This issue was found by members of the Cardano Operators Guild.

**Comment by Jimbo4350** [comment]
There is still a hardcoded `EpochSlots` in the logging machinery which needs to be removed.

**Comment by mrBliss** [comment]
See #1085 for the hard-coded 21600 in the tracing.

**Comment by Jimbo4350** [comment]
The hard coded `EpochSlots` value in the Tracing module has been removed.
