### ISSUE TITLE
EKG access from outside a container

### ISSUE THREAD

**Issue by Willburn** [input-output-hk/cardano-node#857]
This article sums up the problem https://pythonspeed.com/articles/docker-connection-refused/
Basically you need to be able to bind to the outside ip (0.0.0.0 for example) to access EKG from outside container.
A workaround is using socat to forward the port for example if EKG is port 12000 `socat -d tcp-listen:12100,reuseaddr,fork tcp:127.0.0.1:12000`
To make this work you also need to add the assets of EKG as can be seen in this discussion
https://github.com/tibbe/ekg/issues/22

It would probably be easier for docker container users to be able to bind EKG to an outside IP as you can do with for example prometheus.

**Comment by Willburn** [comment]
Here is an example of a dockerfile and entrypoint that works around this issue:
https://gist.github.com/Willburn/c56628b116584818b1d6936fa869a667
https://gist.github.com/Willburn/031e8c5b9a97ed214b5845da2101fff6

**Comment by mark-stopka** [comment]
The 127.0.0.1 IP address is hard-coded in [iohk-monitoring-framework](https://github.com/input-output-hk/iohk-monitoring-framework/blob/d6f760591bc6f54e8c333986cf6cf7fb737747df/plugins/backend-ekg/src/Cardano/BM/Backend/EKGView.lhs#L225)

`        ehdl <- (forkServer "127.0.0.1" evport`

**Comment by redoracle** [comment]
> This article sums up the problem https://pythonspeed.com/articles/docker-connection-refused/
> Basically you need to be able to bind to the outside ip (0.0.0.0 for example) to access EKG from outside container.
> A workaround is using socat to forward the port for example if EKG is port 12000 `socat -d tcp-listen:12100,reuseaddr,fork tcp:127.0.0.1:12000`
> To make this work you also need to add the assets of EKG as can be seen in this discussion
> [tibbe/ekg#22](https://github.com/tibbe/ekg/issues/22)
> 
> It would probably be easier for docker container users to be able to bind EKG to an outside IP as you can do with for example prometheus.

Did you file a feature request to customise the IP as well the port in the configuration file?
 As mark-stopka said the IP is hardcoded, but I guess is a quick change to implement the ip as well..
Now is:
evport <- getEKGport config
        ehdl <- (forkServer "127.0.0.1" evport)

while it should be more like (or similar :P ):

evport <- getEKGport config
evip <- getEKGip config
        ehdl <- (forkServer "evip" evport)

**Comment by Willburn** [comment]
I guess for me its both an issue (broken ekg in cointainer) and also a feature request as I agree it would be great to set the ip - thats why i referenced to the prometheus service where you can do this. Btw where do I go to suggest features for cardano-node?

**Comment by mark-stopka** [comment]
> where do I go to suggest features for cardano-node?

IMO here...

**Comment by CodiePP** [comment]
maybe you can `ssh` into the container end tunnel this port?
```
ssh -f -L 12100:localhost:12100 container.local "sleep 3000"
```
this brings port 12100 in the container and binds it in the outside environment to the same port number. then you might be able to access EKG metrics on http://localhost:12100

**Comment by redoracle** [comment]
With socat is fine too..

It was more to avoid 3rd apps

Kind Regards
Michael

**Comment by CodiePP** [comment]
tracked in CAD-1207

**Comment by Willburn** [comment]
With the docker.com image from inputoutput/cardano-node you will get a "No handler accepted "/"" error still unless you do some of the workaround solutions suggested here.

**Comment by CodiePP** [comment]
@denisshevchenko solved this in PR https://github.com/input-output-hk/iohk-monitoring-framework/pull/570
the change will be included in the next release of the node.

**Comment by nyetwurk** [comment]
None of this works with topologyUpdater, since all the silly ss/lsof stuff is looking for cardano-node and not docker-proxy, which is what is actually listening on the ports.

**Comment by gufmar** [comment]
> None of this works with topologyUpdater

client side TU does not need any ss/lsof 
it just queries the ekg port for the current blockNo

https://github.com/cardano-community/guild-operators/blob/alpha/scripts/cnode-helper-scripts/topologyUpdater.sh#L127

**Comment by nyetwurk** [comment]
Unfortunately, there is no way to tell the script that because if it's contorted hardcoded dependency on env:
https://github.com/cardano-community/guild-operators/blob/724aa0dc76eb9b23a4240db720381c15ca361bd7/scripts/cnode-helper-scripts/env#L265
 unless I reverse engineer it from scratch.

**Comment by nyetwurk** [comment]
Is there a stripped down version of the topologyUpdater, or a simple spec on how to retrieve a topology so I can make a simple one?

Also, I can't find any documentation whatsoever on the socket protocol, so even getting something as simple as the version is impossible w/o docker exec

**Comment by redoracle** [comment]
This is how we download it within a container:
https://github.com/cardano-community/guild-operators/blob/alpha/files/docker/node/addons/guild-topology.sh

With this line the scripts download the topology:
curl -s -k -o /tmp/guild_topology2.json "https://api.clio.one/htopology/v1/fetch/?max=20"

While to get EKG outside the container I use this workaround:
socat -d tcp-listen:12782,reuseaddr,fork tcp:127.0.0.1:12781 

I hope this help

**Comment by nyetwurk** [comment]
https://github.com/cardano-community/guild-operators/blob/alpha/files/docker/node/addons/guild-topology.sh
This makes no sense, why doesn't it use jq?

**Comment by nyetwurk** [comment]
EKG isn't a problem, you can edit config.json 
```
"hasEKG": [
    "0.0.0.0",
    12788
  ]
  ```

**Comment by redoracle** [comment]
> https://github.com/cardano-community/guild-operators/blob/alpha/files/docker/node/addons/guild-topology.sh
> This makes no sense, why doesn't it use jq?

Many thanks for your gentle reply...
To be honest I don't understand what you are looking for.

**Comment by redoracle** [comment]
> EKG isn't a problem, you can edit config.json
> 
> ```
> "hasEKG": [
>     "0.0.0.0",
>     12788
>   ]
> ```

Yes this is correct.
My implementation was ante the ability to do it within the configuration

**Comment by gufmar** [comment]
> Is there a stripped down version of the topologyUpdater, or a simple spec on how to retrieve a topology so I can make a simple one?

This one should be a good start
https://cardano-community.github.io/guild-operators/#/Scripts/topologyupdater

In very shory
First your node must subscribe, by repeating a couple of hourly subscription requests. They are valid only if the request contains the current blockheight (hence the ekg request)

A subscribed node becomes published to other nodes as peer.

Only a subscribed node is allowed to fetch a fresh peer list

The topology server does connection checks (miniprotocol) towards the subscribed ip:ports

A subscribed (known) peer becomes temporarily and quickly paused if not reachable, even if he continue with valid hourly subscription calls.

The goal is to have a complete Account/permissionless system, constantly providing a list of reliable peers

**Comment by nyetwurk** [comment]
@gufmar Thank you, this is extremely helpful. I am doing just that now.

**Comment by rdlrt** [comment]
@nyetwurk Best to use https://github.com/cardano-community/guild-operators in future. Your discussion thread is quite out of context on cardano-node repository.
