### ISSUE TITLE
systemd notify when service is up

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#869]
If systemd is enabled, we should issue a notify: https://hackage.haskell.org/package/systemd-2.3.0/docs/System-Systemd-Daemon.html#g:1 when the service is completely up. This would a) let our deployments properly report if the service is up or not and b) make the chairman test much less ugly as we could just use `waitForUnit`.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open with more details.
