### ISSUE TITLE
Clean the CLI interface for tx-submission

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-node#90]
At the moment it's not clear weather all the arguments for tx submission are really needed. If it's not possible to keep a minimal set of arguments to construct transactions for various protocols, we could submit raw transactions instead of elaborating mock transactions to real ones.

Note: this issue is just to record the problem, not to suggest the right solution.

**Comment by Jimbo4350** [comment]
Closing as this has improved significantly. A new issue can be re-opened if necessary.
