### ISSUE TITLE
How To Know To Run Scripts Mainnet.Sh Etc?

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-node#923]
There is no guide or instruction in https://github.com/input-output-hk/cardano-node that you should go to the folder https://github.com/input-output-hk/cardano-node/tree/master/scripts to find the scripts that will help you to connect to mainnet or testnets. How will users know this? The site docs need to be updated so user knows where to go to complete the process of running a node. Whats in https://github.com/input-output-hk/cardano-node after cabal build does not really help that much since you don't know critical configuration information to run the node effectively.

**Comment by Jimbo4350** [comment]
`Scripts
=======

Please see ``scripts/README.md`` for information on the various scripts.
`
is now is the top level readme
