### ISSUE TITLE
Could not run shelley-testnet.sh as missing tmux on Centos 8

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-node#924]
Script shelley-testnet.sh failed to run as tmux not installed on Centos 8
Pre-requisites need to be updated to include the fact it needs to be installed otherwise script will continue to fail

_[gerard@centos-4gb-hel1-1 cardano-node]$ scripts/shelley-testnet.sh
-- executable mode: cabal
-- git commit:  60a8756aebef56671dd343b0828b9b186d633580
-- process group id (PGID): 29983
-- to list the process tree:  pstree -Tulap 29983
-- ..or, interactively:       watch --interval=1 "pstree -Tulap 29983"
-- using genesis /opt/cardano-node/configuration/defaults/simpleview/genesis with hash 879c3bd34624e368bf46e509fa807c550e6a96cef43f0f2750e9d4275c0365c0
-- prebuilding the "cardano-node:cardano-node" executable in "cabal" mode..
-- RTS options:
-- cabal v2-run exe:cardano-node -- --help
scripts/lib-cluster.sh: line 13: tmux: command not found_

**Comment by Jimbo4350** [comment]
I've created a new script that does not require `tmux` at `scripts/lite/shelley-testnet.sh`
