### ISSUE TITLE
Persistent Error When Running Shelley-Testnet.sh

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-node#925]
The following error repeats itself when running the 3 node shelley testnet. Not sure if am doing something wrong here. Can you advise?

_[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] aboutToLeadSlot│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] aboutToLeadSlot
Last = 20                                                                                     │Last = 20
[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Testing for leadership at s│[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Testing for leadership at s
lot 20                                                                                        │lot 20
[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList []            │[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList []
[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] nodeNotLeader =│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] nodeNotLeader =
 20                                                                                           │ 20
[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Not leading slot 20        │[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Not leading slot 20
[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList []            │[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList []
[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] aboutToLeadSlot│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] aboutToLeadSlot
Last = 21                                                                                     │Last = 21
[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:54.00 UTC] Testing for leadership at s│[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:54.00 UTC] Testing for leadership at s
lot 21                                                                                        │lot 21
[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:54.00 UTC] fromList []            │[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:54.00 UTC] fromList []
[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] nodeNotLeader =│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] nodeNotLeader =
 21_

**Comment by kevinhammond** [comment]
Not sure how to label this one.  Is it still an issue @gmanroney

**Comment by zamrih** [comment]
> The following error repeats itself when running the 3 node shelley testnet. Not sure if am doing something wrong here. Can you advise?
> 
> _[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] aboutToLeadSlot│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] aboutToLeadSlot Last = 20 │Last = 20 [centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Testing for leadership at s│[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Testing for leadership at s lot 20 │lot 20 [centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList [] │[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList [] [centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] nodeNotLeader =│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:34.00 UTC] nodeNotLeader = 20 │ 20 [centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Not leading slot 20 │[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:34.00 UTC] Not leading slot 20 [centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList [] │[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:34.00 UTC] fromList [] [centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] aboutToLeadSlot│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] aboutToLeadSlot Last = 21 │Last = 21 [centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:54.00 UTC] Testing for leadership at s│[centos-4:cardano.node.Forge:Info:36] [2020-05-10 14:48:54.00 UTC] Testing for leadership at s lot 21 │lot 21 [centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:54.00 UTC] fromList [] │[centos-4:cardano.node.ForgeTime:Info:36] [2020-05-10 14:48:54.00 UTC] fromList [] [centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] nodeNotLeader =│[centos-4:cardano.node.Forge.metrics:Critical:36] [2020-05-10 14:48:54.00 UTC] nodeNotLeader = 21_

Running a 3 nodes testnet as well and the blocks are actually produced.
As far as I understands it, the nodes are quite verbose in the logs.

Try to run the "cardano-cli -- get-tip" to check where each node is at in terms of blocks produced.
You can go on with generating keys and addresses and testing submitting transactions and staking.

Would be happy to assist if still experiencing an issue with that.

**Comment by Jimbo4350** [comment]
I have created a new script at `scripts/lite/shelley-testnet.sh`. This should work and if not re-open the issue.
