### ISSUE TITLE
LiveView not updating

### ISSUE THREAD

**Issue by michaeljfazio** [input-output-hk/cardano-node#951]
**Expected Behavior:**

When enabling LiveView, the ncurses interface should update to show various stats about the current runtime of cardano-node.

**Actual Behavior**

Stats are not updating as per:

<img width="1224" alt="Screen Shot 2020-05-13 at 12 57 03 am" src="https://user-images.githubusercontent.com/1845178/81722913-ab77ca00-94b4-11ea-8ed0-dcbcaeb0d971.png">

Furthermore the "Release" shows "Byron".

**Steps to Reproduce the Problem**

Enable LiveView. 
Start node.

**Specifications**
Version: 1.11.0-9957fb3 (pioneer)
Platform: Amazon Linux 2
Chain: Friends and Family

**Comment by rdlrt** [comment]
There is a [hardcoded reference (a TODO)](https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Node/TUI/LiveView.hs#L514-520) for LiveView, and its not obtained from the config - thus, not limited to Pioneer branch, but a general defect. Could you update the title accordingly?

**Comment by erikd** [comment]
@michaeljfazio Which particular things do you think are not being updated correctly

I know of:
* "Release" being incorrect (I have a WIP fix for this)
* Two hard coded values mentioned by @rdlrt, (I have a fix for one and working on the other).
