### ISSUE TITLE
A few container based cardano-node issues

### ISSUE THREAD

**Issue by Willburn** [input-output-hk/cardano-node#953]
Having isolated that indeed my cardano-nodes work outside containers and having tried to failsafe that there are no setting issues and also having some 2nd eyes look at the same I believe there could be a few potential container based cardano node issues:

1. A production cardano-node that has only relays and is inside a container seems to make no contact with the relays. This is with host network as the network for container. Take the exact same files and use then outside a container and they will find the relays (even if the relays are in a container)

2. A relay cardano-node that has only IOHK current topology peer in peer list will not get to the current tip or recieve any network update. Adding any of FF peers and the relay node works also inside the container.

3. A relay not on the same computer as the producer that does not use the 0.0.0.0 interface will not reach the production node. If I use my external ip it does not reach it.

The main problem here is that I cannot 100% rule out there are some configuration issues that has caused this behaviour but I have to my best of ability tried to make sure I rule out other issues:
1. Made sure to use host network instead of a bridging docker network.
2. Made sure all ports are open on host network that is required.
3. Made sure all configurations are correctly set
4. Made sure to build the correct build tags/pioneer
5. Fail checked internet connections and made sure all are reachable.
6. Made sure each computer only have one gateway (the internet ip)

Potential causes that are mentioned:
I use two or more networks on each computer. An external to internet and an internal for a local lan. Also both computers have a few virtual networks for docker. Could one gateway multiple ip/network interfaces cause problems?

**Comment by kevinhammond** [comment]
We are pointing the Pioneers away from using docker.  We have a task to look at this in future.  We will need to balance this with other priorities.

**Comment by Willburn** [comment]
I can understand that and I think its wise to balance this with other priorites. I want to add in the regards of this discussion maybe also the 
https://testnets.cardano.org/en/shelley-haskell/about/supported-platforms/ "It is also possible to run a testnet node on any platform using a virtual machine or Docker image." should be updated if this is not something currently supported?

**Comment by Willburn** [comment]
I believe I have found the issue. To resolve dns a cointainer user needs to have access to /etc/ folder to read the resolv.conf file.  This was why dns round robin based addresses did not work while single IP address from my peers worked. So any dockerbuild files needs to make sure to give access to /etc/resolv.conf (or whatever resolve file your image uses) to work around this problem (or use root if security is not a concern)

**Comment by Willburn** [comment]
Installing bind-9 in the container resolve a lot of the dns errors so it seems very much to be related to dns resolving. Still working on solving this one but believe I am getting closer.

**Comment by kevinhammond** [comment]
@rhyslbw please update the documentation

**Comment by rcmorano** [comment]
I've came across with the DNS issue also and found [0] that it's related to `/etc/services` being missing.
On an ubuntu-based system, the problem is solved by installing the `netbase` package.

[0] https://github.com/DataDog/integrations-core/issues/1569

**Comment by Willburn** [comment]
The netbase is a cleaner solution so appriciate the feedback rcmorano. I guess this issue can be closed as the communty has found a workaround :)
