### ISSUE TITLE
CLI command: query KES data

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#956]
example usage: `cardano-cli shelley query kes --testnet-magic 42`
and return something like:
```
{
"current period": 3,
"inital period": 1,
"evolutions": 2
"remaining evolutions": 12
}
```

where those correspond to `kp_`, `c0_`, `t`, and `maxKESEvolutions - t`

Would be good to expose these to EKG for prometheus as well, but we could follow-up with that.

**Comment by disassembler** [comment]
per @dcoutts probably best to trace this into EKG first.

**Comment by vix-io** [comment]
enhancement?

**Comment by disassembler** [comment]
This is slightly high priority, as pool operators will need to know what the current KES period is and how long they have left to replace their KES key for them to generate new keys. Otherwise, they have to do math (which is what we're currently doing) based on genesis start time, max KES evolutions and slots per KES period.

**Comment by kevinhammond** [comment]
Highly desirable, but not 100% essential - medium-high :).  Much less critical when we go to mainnet, I presume, so if we do it, it's most useful to do it soon.

**Comment by erikd** [comment]
This should be be closed. Dropping the priority is fine.

**Comment by kevinhammond** [comment]
Covered by 1029/1030?

**Comment by kevinhammond** [comment]
I will close this in favour of the two open tickets, but the discussion is still relevant.

**Comment by 7-of-9** [comment]
This (or something similar) needs implementing ASAP. Kind of ridiculous that you're live without this, tbh.
