### ISSUE TITLE
No documentation for LiveView 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#961]
Or if there is any, could you please share it here? Thank you.

**Comment by erikd** [comment]
I am not aware of any. You could try starting to write some or even just list the things that you think should be in such a document.

**Comment by vix-io** [comment]
should we move this to cardano-tutorials?

**Comment by dorin100** [comment]
Considering that it is part of the logs, ideally, it should be documented into the Official Documentation that Rob is coordinating.

**Comment by CodiePP** [comment]
tracked in CAD-1149
