### ISSUE TITLE
Documentation: no documentation for genesis, node-configuration and topology

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#962]
There is no documentation for the parameters used inside the files required to start a node - genesis, node-configuration, and topology

For example, what `valency` inside the topology file means?

**Comment by erikd** [comment]
Valency: https://github.com/input-output-hk/cardano-node/blob/master/cardano-config/src/Cardano/Config/Topology.hs#L66-L71

Yes, we need more docs.

**Comment by vix-io** [comment]
should we move this to cardano-tutorials?

**Comment by dorin100** [comment]
Than you @erikd 

@vix-io, I think that this is something that needs to be part of the User Docs / Official Documentation.

**Comment by kevinhammond** [comment]
These should be internal node documentation.  There is good explanatory documentation in tutorials.  This is just a short explanation of the fields. The two should be linked to ensure that consistency is maintained.

**Comment by rcmorano** [comment]
> These should be internal node documentation. There is good explanatory documentation in tutorials. This is just a short explanation of the fields. The two should be linked to ensure that consistency is maintained.

JFTR, I've just searched for it and found this issue and that specific info here: https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/understanding-config-files.md#the-topologyjson-file

**Comment by Jimbo4350** [comment]
@dorin100 I believe your questions are covered here: https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/understanding-config-files.md

Feel free to re-open a new issue if not.
