### ISSUE TITLE
Create GitHub Templates

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#963]
We should create GitHub Templates for external users for:

- bug reports
- new feature requests

Anything else?

**Comment by i-o-m** [comment]
@kevinhammond Not sure this should be against Node Repo as it's not related to the Node. Can you have a task in JIRA for TSD?

**Comment by kevinhammond** [comment]
I already did that.  This was specifically for the node repo.  I put it here so that only one person did the task.

https://jira.iohk.io/browse/CAD-978?filter=-2

**Comment by kevinhammond** [comment]
We seem to be blocked on this by organisational issues...

**Comment by kevinhammond** [comment]
Done by Viktor
