### ISSUE TITLE
build-raw should be removed from the parser

### ISSUE THREAD

**Issue by oneEdoubleD** [input-output-hk/cardano-node#970]
We have removed `build-raw` from the CLI (technically we've commented it out) and @erikd has said that this has been replaced with a newer command. However, `build-raw` is still in the parser and appearing in the `cli` help text. I believe this line should be removed from `Parsers.hs`:

```
Opt.command "build-raw"
          (Opt.info pTransactionBuild $ Opt.progDesc "Build a transaction (low-level, inconvenient)")
```

**Comment by erikd** [comment]
Sorry, I goofed. I was thinking about "address build-raw" (which may or may not have been a thing).

The "transaction build-raw" needs to stay. Closing this.
