### ISSUE TITLE
CLI Command: use same option for filepath in transaction commands

### ISSUE THREAD

**Issue by Mixxaz** [input-output-hk/cardano-node#975]
![image](https://user-images.githubusercontent.com/58254786/82037726-d758a280-96a2-11ea-8574-62e457accd9d.png)

In the above image we see the 3 commands related to building, signing and submitting. 
The command parameters don't align and it would be easier if they would.

For build-raw output is --tx-body-file.
In sign this is input and output is --tx-file
In submit input file is --tx-filepath.

To me we could progress with setting --tx-body-file as input and --tx-file as output.
2nd option is to keep as is but replace --tx-filepath with --tx-file to follow the current setup of build-raw -> sign

**Comment by erikd** [comment]
The CLI is still very much a work in progress. It very definitely needs some polish.

I do agree that we should not have `--tx-file` and `--tx-filepath`. The former should be replaced.

However, some things like `--tx-body-file` are some times an input and sometimes an output. Are the help comments that specify input/output sufficient or should we separate them as `--tx-body-file-in` and `--tx-body-file-out` ?

**Comment by Mixxaz** [comment]
no the tx-body-file is fine for me. It also clearly shows the flow of commands.

My main issue is with `--tx-file` vs `--tx-filepath`.

Why would you replace the former instead of the latter?

**Comment by erikd** [comment]
> Why would you replace the former instead of the latter?

Maybe that is the coder not thinking as the user. The type used to represent file names is `FilePath`.

**Comment by Mixxaz** [comment]
Ok makes sense. Would that mean that `--tx-body-file` should also be replaced to `--tx-body-filepath` ?

**Comment by erikd** [comment]
I have actually changed by mind. The sorter version is better and should be used throughout.

**Comment by Mixxaz** [comment]
Ok perfect. Just think uniformity will make this better.
Thanks for the quick update.

You want me to go over all commands to check for discrepancies?

**Comment by erikd** [comment]
Absolutely agree on the uniformity and we are very happy to have input from users, but be aware that this still is very much a work in progress.

**Comment by Mixxaz** [comment]
Yes I understand.
