### ISSUE TITLE
Node Status Report

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-node#980]
It would be great if there could be something like

cardano-cli node-status with

- node uptime
- no. peers
- leader(s) ( array with leaders-node ids); if no leader loaded, then empty array
- node IP
- lastBlockHeight
- lastBlockHash
- lastParent 
- lastSlot 
- lastEpoch
- version HCN
- md5 checksum

- json output available

**Comment by rdlrt** [comment]
Duplicate/addition to #801 ?

**Comment by erikd** [comment]
Moved this request as an addendum to #801 .
