### ISSUE TITLE
Implement bash completion for file arguments

### ISSUE THREAD

**Issue by intricate** [input-output-hk/cardano-node#981]
From @cleverca22 on Slack:

>`releaseNotesP = (Just . T.pack <$> strOption ( long "release-notes" <> metavar "RELEASE_NOTES" <> (help "Path to release notes (html)") <> (completer (bashCompleter "file") )))`

> it needs a `completer` added to any argument that can take a file

**Comment by erikd** [comment]
I think this is fixed.
