### ISSUE TITLE
LiveView peer count is zero and peers list is empty

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#982]
On the main LiveView page the peer count is always zero and the peers list is always empty even for a node is on Byron and where the block number is incrementing every 20 or so seconds.

My understanding is that this issue is independent of Byron/Shelley.

There is a separate Byron only problem that the Byron mempool stats are not being updated correctly. Since this is correct in Shelley and Bryon is about to be replaced fixing Byron is probably not a high priority.

**Comment by kevinhammond** [comment]
Is this a bug that we must fix, @erikd, or simply an irritation?  Could you classify it please :)
I assume it hasn't been raised by the Pioneers?

I added the minorfix label for irritants

**Comment by AndrewWestberg** [comment]
This might be fixed by changing this config setting to true.
```
"TraceBlockFetchDecisions": true
```

**Comment by erikd** [comment]
@AndrewWestberg I have that set to true already.

**Comment by erikd** [comment]
This is a bug!

If the configuration is set to LiveView and the rest of the settings are not correctly set for LiveView the program should either exit with a helpful error message or automatically set them so that LiveView works correctly.

**Comment by denisshevchenko** [comment]
Since `LiveView` is officially deprecated and will be removed from the node very soon, I'm closing this issue. Please check [RTView](https://github.com/input-output-hk/cardano-rt-view/), our new tool for real-time watching for Cardano nodes. You can open an issue [here](https://github.com/input-output-hk/cardano-rt-view/issues/).
