### ISSUE TITLE
LiveView TXs Processed counter remains 0

### ISSUE THREAD

**Issue by PegasusPool** [input-output-hk/cardano-node#987]
# What I did

- Built the node from source using the `pioneer-2` tag.
- Connected a relay node to the FF testnet
- Confirmed that the node is in sync
- Sent a successful transaction from address A to B (create, sign, submit)
- Verified that the transaction is settled on address B

# Issue

`TXs processed` in `LiveView` remains 0

# Expected

`TXs processed` in `LiveView` to be 1

![Screenshot from 2020-05-17 19-25-36](https://user-images.githubusercontent.com/58512297/82156637-36214600-9874-11ea-9db8-93a1cfa7e2a4.png)

**Comment by erikd** [comment]
You have a non-zero peer count! Any idea what you did to achieve that?

**Comment by PegasusPool** [comment]
I did nothing special to get that.
Here are the [config](https://pastebin.com/3cgDya6q) and [topology](files).

**Comment by erikd** [comment]
Right so your config file would just be from commit 4a2c92c7448d21ed3c747fe51e4f98744df791fa .

Something in the logging has changed.

**Comment by kevinhammond** [comment]
The discussion we had was whether the count meant number of transactions processed by this pool (which would be zero), or number of transactions processed by the Blockchain (which would not be zero).  We need to clarify this and then decide how to fix it

**Comment by PegasusPool** [comment]
To further demonstrate the issue:
This is a screenshot from another pioneer after sending a few hundred transactions to the network (the node is not a block producer)

![76f435dc-f030-4e10-87da-ca91fa5bbb26](https://user-images.githubusercontent.com/58512297/82292466-e0978700-99a2-11ea-9947-593e2636c634.png)

**Comment by erikd** [comment]
@PegasusPool the second screen shot is for a different git hash. :confused:

**Comment by rdlrt** [comment]
@erikd I think newer commits dont have the issue indeed.
Its probably because FnF are using specific tag (old commit) for now

**Comment by PegasusPool** [comment]
That's probably the case since I noticed the counter increase on a newly built node (even though I haven't sent any transactions myself) 

![Screenshot from 2020-05-19 20-23-03](https://user-images.githubusercontent.com/58512297/82371049-736f0a80-9a11-11ea-9dc0-f872e29bc93a.png)
