### ISSUE TITLE
LiveView - toggle to StdoutSK

### ISSUE THREAD

**Issue by matthijs-aeon** [input-output-hk/cardano-node#991]
Please consider adding functionality to toggle between LiveView, Peer List and StdoutSK from within the same window. This would be very convenient when monitoring the node.

**Comment by vix-io** [comment]
Hi matthijs-aeon, this is Viktor at IOHK Tech Support. Thank you for submitting this Feature Request. We have added it to our backlog and we`ll allocate it to one of our future development sprints. We appreciate your participation and support for the Cardano project!

**Comment by CodiePP** [comment]
the node determines from the configuration in which mode it starts: either LiveView or "default" which outputs to _stdout_
we cannot change the mode after startup.
I propose that one follows the textual output in another terminal using `tail -F ` on a log file in format: "ScText"
